### ISSUE TITLE
TLS origination doesn't seem to work with wildcard domains

### ISSUE THREAD

**Issue by rchernobelskiy** [istio/istio#10041]
**Describe the feature request**
TLS origination with wildcard domains

**Describe alternatives you've considered**
The only alternative seems to be for something outside of Istio, like Nginx, to do TLS origination as a forward proxy.

**Use case**
We interact with AWS Services through their HTTP APIs and would like calls to AWS to appear as part of our end-to-end traces in Jaeger. To do this, we tell the AWS sdk to send out plain HTTP requests and have Istio originate TLS with AWS. This works if we configure each AWS service in Istio individually but there are two problems with this:
 1) It generates massive amount of dns traffic as every sidecar is periodically healthchecking every one of the hundreds of aws service domains that we configured.
 2) Some AWS services, for example S3, use dynamic domains that we can't pre-configure.

To overcome the above, we need to define a wildcard domain for access to all AWS service domains. Ideally we would have Istio switch the port from 80 to 443, originate TLS, and route to AWS.
From what I understand, Envoy doesn't support routing to wildcard destinations so we utilize Nginx as a forward proxy. At this point, we can configure Istio to just originate TLS and configure Nginx to switch the port and route to destination via sni. When trying this however, it doesn't seem like sni is being properly set for wildcard domains, whether using ROUND_ROBIN or PASSTHROUGH load balancer. With the above situation, the only option left seems to be to forward all wildcard egress traffic unencrypted to Nginx and have it originate TLS and do the routing.

Initial discussion started here: https://github.com/istio/istio/issues/9488#issuecomment-439256152

**Comment by vadimeisenbergibm** [comment]
Implementation of this depends on https://github.com/envoyproxy/envoy/pull/4973 and https://github.com/envoyproxy/envoy/pull/4334.

**Comment by vadimeisenbergibm** [comment]
Regarding _The only alternative seems to be for something outside of Istio, like Nginx, to do TLS origination as a forward proxy._

Note that this way you will not be able to implement keepAlive, envoy will open a new connection to the forward proxy every time, and it will hurt performance. I tried various options here - https://github.com/vadimeisenbergibm/envoy-generic-forward-proxy.

**Comment by elevran** [comment]
@rchernobelskiy would an nginx based solution work for you (assuming minimal performance impact)? What, if any, would be some of the concerns?

**Comment by vadimeisenbergibm** [comment]
@rchernobelskiy We checked the options for configuring Envoy and Nginx to implement keep alive. The issue is not with Envoy (I edited my comment https://github.com/istio/istio/issues/10041#issuecomment-440182562), but with Nginx.

The [keepalive directive of Nginx](http://nginx.org/en/docs/http/ngx_http_upstream_module.html#keepalive) is applied to the `upstream` section, which does not exist for `proxy_pass` to arbitrary domains. In short, for wildcard hosts, Nginx's keepalive cannot be configured.

We considered setting `Content: Keep-Alive` header together with the Nginx's `proxy_pass`, however, according to [Nginx's documentation](http://nginx.org/en/docs/http/ngx_http_upstream_module.html#keepalive) it is not recommended:
> Alternatively, HTTP/1.0 persistent connections can be used by passing the “Connection: Keep-Alive” header field to an upstream server, though this method is not recommended.

A related Stackoverflow question: [Why does nginx proxy_pass close my connection?](https://stackoverflow.com/questions/46771389/why-does-nginx-proxy-pass-close-my-connection)

**Comment by munrodg** [comment]
@vadimeisenbergibm Please confirm this is required for 1.1.

**Comment by linsun** [comment]
@vadimeisenbergibm didn't you already have a solution for 1.1 as part of your POC to use nginx as a sidecar to egress?

is that something supported officially via istio.io?

**Comment by duderino** [comment]
@vadimeisenbergibm looks like the Envoy PR has been merged.  What's left to be done here?

**Comment by vadimeisenbergibm** [comment]
@duderino I asked a question in 
https://github.com/envoyproxy/envoy/pull/5337#issuecomment-455847185, let's see the answer.

**Comment by duderino** [comment]
@vadimeisenbergibm looks like the Envoy PR was merged.  What's left to be done here?

**Comment by ImAjayS** [comment]
Is this supported now? I'm looking to create a `ServiceEntry` and `DestinationRule` for `*.domain.com`(as the subdomains will be different) with requests from app to proxy in HTTP and originate TLS from proxy in order to have better controls(Circuit breaker/Outlier detection), retry policy, and better observability. 
@vadimeisenbergibm
