### ISSUE TITLE
Response headers missing x-envoy-attempt-count

### ISSUE THREAD

**Issue by michaelkipper** [istio/istio#10194]
**Describe the bug**
I set up an environment with a server that holds on to requests until they time out at the client side. We have monitoring set up on the client side to report the attempt count so we can get a signal when things are starting to get flaky, even when we're getting consistent successful responses.

**Expected behaviour**
I expected to see `x-envoy-attempt-count` in the headers of the response (https://www.envoyproxy.io/docs/envoy/latest/configuration/http_filters/router_filter#x-envoy-attempt-count). It's not there, even when I see the retries happen on the server side.

There's an `include_request_attempt_count` in route.proto (https://github.com/envoyproxy/envoy/blob/master/api/envoy/api/v2/route/route.proto#L132) that might not be set. I'm not sure how to set it, from the Istio config.

**Steps to reproduce the bug**
Just take a look at the headers in the responses from Envoy.

**Version**
Istio 1.0.2

**Installation**
We have a custom deploy script that generates YAML from the Helm charts via `helm template` using our own `values.yaml` file.

**Environment**
GKE

**Cluster state**
{{ If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue. }}

**Comment by briancecker** [comment]
This has already been marked as stale, but would it be possible to get an update on this from a maintainer? I would also like this to be enabled in order to allow rate limiting on retries. I don't think this is necessarily a bug, it's just not enabled in the envoy configuration pushed by pilot as far as I can see. 

Enabling this looks straight forward, but the only question I have is whether I should enable it for all `VirtualHost`s by default, or make sure it is configurable somehow.

**Comment by howardjohn** [comment]
In 1.3 this can probably be handled with https://preliminary.istio.io/docs/reference/config/networking/v1alpha3/envoy-filter/. Or we could expose this through an API/make it on by default. I am not sure the impact this would have if enabled by default, or how generally useful it would be to make an API though
