### ISSUE TITLE
Install Kiali in one command

### ISSUE THREAD

**Issue by linsun** [istio/istio#10200]
Based on our doc of Kiali, a user will have to do a 2 steps installation and configuration:

https://preliminary.istio.io/docs/tasks/telemetry/kiali/#before-you-begin

The step installs istio first, then update istio with kiali.dashboard.jaegerURL and kiali.dashboard.jaegerURL.   Is it possible to consolidate this into 1 helm cmd where user can just pass in the in cluster or external grafana or jaeger service?

cc @dcberg

**Comment by gbaufake** [comment]
Hi @lisun,

I think the main problem on Helm is that you don't know for sure what is going to be the URL for grafana and jaeger before istio is installed... (even query the ingress would not solve the problem, because there is no ingress installed if you we are going to use one command)

On Ansible Installer installing on Openshift, it is possible to use one command because we can grab the openshift route for those services 

https://github.com/istio/istio/blob/3cae633c3498708aa920a9f6d50cf0eae2d7dd2b/install/kubernetes/ansible/istio/tasks/install_on_cluster.yml#L22-L29

Maybe @jmazzitelli has more thoughts and insights about this one.
Best Regards, 
Guilherme

**Comment by jmazzitelli** [comment]
@linsun @gbaufake 

This request is actually already documented as a Kiali JIRA issue here: https://issues.jboss.org/browse/KIALI-1939 

Knowing the Jaeger and Grafana URLs beforehand is the problem, and why you need 2 commands. If you know of a way to find out what Jaeger and Grafana's URLs are going to be BEFORE you install them (or at least BEFORE you run that kiali install command) then let us know. But right now, we know of no way to determine correctly those URLs.

We originally tried to have Kiali auto-detect those URLs at runtime (so you could leave those settings blank and let Kiali determine what the URLs are by finding Jaeger and Grafana in the cluster automatically) but we could not figure out a way to do this that worked for all use-cases across k8s and openshift environments. (this is mentioned in that JIRA).

For sure, I would like Kiali to be able to find a way to do this at runtime - if anyone has any ideas how Kiali can auto-detect where Jaeger and Grafana are at runtime in both k8s and OpenShift environments, let the kiali team know.

**Comment by linsun** [comment]
@jmazzitelli could we at least simplify it for the demo profile which kiali is enabled by default now.  Given the demo profile installs everything into istio-system ns, could we simply set `kiali.dashboard.jaegerURL={jaeger-service-name}.{namespace} where the {namespace} and {jaeger-service-name} is pre-configured for the demo profile.

**Comment by jmazzitelli** [comment]
@linsun yes, for the demo profile I think that would work, assuming kiali and jaeger and grafana are all installed in the same namespace and kiali can access them (which is true - as you say, everything goes into istio-system).

**Comment by jmazzitelli** [comment]
one thing is that the jaeger and grafana need to be accessible to the end user (i.e. it is not just that Kiali needs to access them - but rather, Kiali is simply providing links for the user to click to see the Jaeger and Grafana screens). So we need ingresses defined for jaeger and grafana and those ingress URLs are the ones that Kiali needs to know about.

Does Jaeger and Grafana have ingress definitions? I just tried installing via helm from master branch and I don't see any ingresses defined using the demo.yaml

**Comment by linsun** [comment]
I think it is fair to hardcode it for demo profile, it provides the best experience for our users.

**Comment by linsun** [comment]
Given it is the same namespace, it is possible to simply use:  http://tracing:80

**Comment by linsun** [comment]
Oh i see your point about user access jaeger or grafana via UI... i had thought it is just kiali consumes it...

**Comment by sdake** [comment]
@linsun did you intend to set this as a P1 for 1.1?  Since none of the telemetry code implements HTTPS, I'd consider the telemetry integration beta at best.  This seems like an optimization that could wait for 1.2...

Can you clarify on the priority?  If you indeed want it as a p1, someone needs to get cracking on a PR.

Cheers
-steve

**Comment by linsun** [comment]
@sdake sorry I had thought it is a simple fix for demo profile thus setting to P1... Now after further discussion, I realized this is not something simple.   I'm okay for 1.2.
