### ISSUE TITLE
why the sidecar can not process trace span

### ISSUE THREAD

**Issue by JadeQin** [istio/istio#10201]
**Describe the feature request**

now if you want use jaeger,you must process the header params like `x-request-id` in your code.why the sidecar can not process this? it only get the header params from requesr and put it into reponse,there is not any business logic. 

**Describe alternatives you've considered**

process the header params in the code

**Additional context**

**Comment by objectiser** [comment]
The problem is that, although the same sidecar may process in the inbound request to the service, and the outbound request from the service, it has no implicit way of knowing that the two requests are connected - we need some way to determine that the two requests are correlated, and this can only be achieved by some information in the inbound request header being explicitly copied over to the outbound request header by the service (application).

**Comment by douglas-reid** [comment]
@objectiser I feel like this (and related questions) continue to crop up around tracing. I think we should probably work on a detailed FAQ entry, and maybe companion doc / blog post on tracing with Istio.  Thoughts?

I have a doc from awhile back that attempts to explain various aspects of distributed tracing. Do you have time to collaborate?

**Comment by loveai88** [comment]
Thanks

**Comment by douglas-reid** [comment]
@objectiser I added a first draft to the community drive. PTAL: https://docs.google.com/document/d/1fHKozeDC1bQlY58dN2SP-IQxtD2TzZ0COOyRc7kcao4/edit#
