### ISSUE TITLE
ISTIO mesh expansion in AWS

### ISSUE THREAD

**Issue by geeknoid** [istio/istio#10210]
@devops083 commented on [Tue Nov 27 2018](https://github.com/istio/community/issues/104)

setupMeshEx.sh is for only GCP?
how to implement ISTIO mesh expansion in AWS?

**Comment by morvencao** [comment]
Need to update annotation for each loadbalancer server at: https://github.com/istio/istio/blob/master/install/kubernetes/mesh-expansion.yaml

And for https://istio.io/docs/setup/kubernetes/mesh-expansion/#setting-up-the-machines
select run `install/tools/setupMeshEx.sh machineSetup VM_NAME`

But not sure if mesh expansion is still working or not.

**Comment by leecalcote** [comment]
@incfly is setupMeshEx.sh deprecated as of 1.1?

**Comment by incfly** [comment]
It's not officially deprecated. We need a few tweaks to make it work again. I recently get it working on master branch. I plan to update the doc with automation in 1.2 release, but if anyone is interested in getting 1.1.x release working, we probably can do it (assuming it fits release schedule although)

Re AWS, I haven't tried it on AWS, but I believe we just need to make `istioCP` command working instead of `gcloud compute scp`, maybe few other things.  I'm happy to provide some help if anyone is interested.

**Comment by gumdelli** [comment]
We just published a blog post about it: https://www.paxos.com/istio-mesh-expansion-on-aws/

**Comment by sdake** [comment]
@gumdelli thanks for the blog post.

Cheers
-steve

**Comment by leecalcote** [comment]
Nice callout to ‘iptables -t nat nVL’, @gumdelli
