### ISSUE TITLE
deleting chart doesn't remove added CRDs

### ISSUE THREAD

**Issue by ts4z** [istio/istio#10221]
**Describe the bug**
Deleting the istio chart, then re-installing it, doesn't work, because of added CRDs. The documentation says that CRDs must be deleted (`kubectl delete -f istio-1.0.4/install/kubernetes/helm/istio/templates/crds.yaml` or similar) but I had to do this with a later version of helm.

It would be best if the deletion was automatic, but at a minimum the docs seem to be wrong. They say this isn't required for 2.10, but I think that it is.

**Expected behavior**
I expected the Helm chart to clean up after itself.

**Steps to reproduce the bug**
Install Helm chart. Delete helm chart. Install helm chart, which will fail.

**Version**
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-30T21:39:38Z", GoVersion:"go1.11.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T09:56:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Installation**
via helm, as per the documentation

**Environment**
kops install, running on AWS, from a new cluster

**Cluster state**
N/A

**Comment by mabushey** [comment]
I recommend never installing anything with helm. Use helm template to create the yaml file. Then you can install/uninstall correctly.

**Comment by magic7s** [comment]
Hitting this same issue when removing istio via helm 2.11.0. `helm delete`. CRDs are not cleaned up. I think this should be at least a variable and the default to clean up what it installs.

Found this documentation on https://github.com/helm/helm/blob/master/docs/charts_hooks.md#hook-resources-are-not-managed-with-corresponding-releases


### Automatically delete hook from previous release

When helm release being updated it is possible, that hook resource already exists in cluster. By default helm will try to create resource and fail with `"... already exists"` error.

One might choose `"helm.sh/hook-delete-policy": "before-hook-creation"` over `"helm.sh/hook-delete-policy": "hook-succeeded,hook-failed"` because:

* It is convenient to keep failed hook job resource in kubernetes for example for manual debug.
* It may be necessary to keep succeeded hook resource in kubernetes for some reason.
* At the same time it is not desirable to do manual resource deletion before helm release upgrade.

`"helm.sh/hook-delete-policy": "before-hook-creation"` annotation on hook causes tiller to remove the hook from previous release if there is one before the new hook is launched and can be used with another policy.

**Comment by jpza** [comment]
FWIW, I ran into this on AWS EKS and had to switch to the helm template install option. I had to apply the templated manifests twice due to some 'no matches for kind` errors on the initial `kubectl apply`.
