### ISSUE TITLE
Error: failed to convert to proto. yaml: line 67: mapping values are not allowed in this context

### ISSUE THREAD

**Issue by purushothamgk** [istio/istio#10422]
**Describe the bug**
Error: failed to convert to proto. yaml: line 67: mapping values are not allowed in this context
error: no objects passed to apply

**Expected behavior**
To deploy the pods

**Steps to reproduce the bug**
kubectl apply -f <(istioctl kube-inject -f private.yaml)

**Version**
Version: 1.0.0
GitRevision: 3a136c90ec5e308f236e0d7ebb5c4c5e405217f4
User: root@71a9470ea93c
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean

Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**
Ubuntu

**Comment by esnible** [comment]
@purushothamgk can you attach a version of _private.yaml_ that demonstrates this?

I have seen this message before, usually because of tabs in the yaml file.  It might also be useful to paste the message you get when you pass the same file to `kubectl apply -f private.yaml --dry-run=true` to see what the message looks like there.

**Comment by linsun** [comment]
close - no response from user after 30 days.  pls reopen if needed.
