### ISSUE TITLE
Configuration validation for traffic routing

### ISSUE THREAD

**Issue by iandyh** [istio/istio#10541]
**Describe the feature request**
Validation for service mesh/gateway configurations. For example, when traffic shifting is enabled, if a version of an app is being used by traffic shifting, deleting the deployment should be disallowed. On the other hand, if the traffic routing(virtual services, destination rules) is applying traffic to non-existent application, it should also be rejected. 

**Describe alternatives you've considered**
The most straight forward solution will be using ValidationWebHook. After discussing with @christian-posta @ZackButcher at KubeCon, an alternative approach like having a cli tool or sandbox for simulation dry run can be a good start. 

**Additional context**
We are putting istio into production so having the feature will be really useful. As a result, We are willing to work on this feature and provide back to the upstream. 

Thanks for your time!

**Comment by linsun** [comment]
I suggest we need a flag to enable this type of validation.  While this can be useful in production, in dev environment, it is intended to bring deployment or traffic routing up and down without matching resources.   I think having a cli tool (or even build a dry run into istioctl) is a good start.

**Comment by iandyh** [comment]
@linsun The validation can only happen in webhook stage. Having a flag will be helpful in dev environment. 

Speaking of dry run, does something like `istioctl verify -f ${virtual_service_file}` look good to you?

**Comment by esnible** [comment]
The user is asking for web-hook validation that considers more than the CRD being modified.

For example, creating a VirtualService that uses a subset that is not defined in a DestinationRule.  It is a reasonable desire.  The problem is that if we have a 2-part .yaml file with both a VirtualService and a DestinationRule the .yaml would be valid if the DR was first, but not if it was second.  This is also difficult to explain.

The user is also asking for a webhook that will block deleting a Deployment if there is a traffic being sent to it by a VirtualService.  The problem is the similar.  Users may expect to be able to delete the Deployment and revise the DR in any order.

There is a 3rd party project to validate Istio deployments looking at more than one resource at a time.  I encourage people to try https://github.com/aspenmesh/istio-vet .  I tried it.  It is a bit confusing to use Istio-vet on IBM cloud because of the .pem file security.  Here is how to do it:
```
MYCLUSTER=istio-test-paid3
MYDC=dal13
docker run --rm -v ~/.bluemix/plugins/container-service/clusters/$MYCLUSTER/kube-config-$MYDC-$MYCLUSTER.yml:/root/.kube/config -v ~/.bluemix/plugins/container-service/clusters/$MYCLUSTER/ca-$MYDC-$MYCLUSTER.pem:/root/.kube/ca-$MYDC-$MYCLUSTER.pem quay.io/aspenmesh/istio-vet:master
```

There is a work item to support dry-run.  I hope to implement it soon to resolve https://github.com/istio/istio/issues/11560 .

**Comment by iandyh** [comment]
@esnible Hi Thanks for the reply.

>  The problem is that if we have a 2-part .yaml file with both a VirtualService and a DestinationRule the .yaml would be valid if the DR was first, but not if it was second. This is also difficult to explain.

I think it's a good practice to always define the required resource first. A bit like variable declaration in any programming language.
