### ISSUE TITLE
how client app send https request with certificate to access external https server which already has its own certificate

### ISSUE THREAD

**Issue by GavinLin168** [istio/istio#10573]
Follow https://github.com/jonashackt/spring-boot-rest-clientcertificate and wrote a spring boot https server and client application. Run the client application with istio sidecar inject , istio is "globally enabling mutual TLS"，and run the server in another vm .  I try many ways like config a serviceentry , disable tls , and some other way from https://preliminary.istio.io/docs , while can't find a way to make it works.  When client call server api, error happen like "I/O error on GET request for "https://ip:8443/test": Connection reset; nested exception is java.net.SocketException: Connection reset". Any idea for this ? thanks!

**Comment by esnible** [comment]
You have configured Istio to globally enable mutual TLS.  This means the istio-proxy sidecars are 
will send all traffic via TLS.  Your Spring client and server are also explicitly doing TLS.

Although your Spring server is doing HTTPS one approach is to tell Istio that the server is doing raw TCP.  This will configure the sidecar to pass the data along unchanged.  Follow the instructions at https://github.com/istio/istio/tree/master/samples/tcp-echo .  It is best if you use a port number that isn't used elsewhere in the cluster.  (443 is probably used elsewhere in the cluster).  Because Istio does not know the traffic is HTTPs most of the route rules will not work.

Disabling the mTLS done by Istio was not sufficient because the Istio proxy expects to receive plain HTTP from the application container it shares the pod with.

If you can get your Spring example working as TCP you can attempt to disable the second mTLS wrapping using the techniques you described.

**Comment by esnible** [comment]
@GavinLin168 Re-open if you have any more questions.
