### ISSUE TITLE
Docs don't match repo for install

### ISSUE THREAD

**Issue by thockin** [istio/istio#10632]
**Describe the bug**
The docs at https://istio.io/docs/setup/kubernetes/quick-start/ say "kubectl apply -f install/kubernetes/istio-demo.yaml" and the README in that dir points back to those docs, but there's no such file.

**Expected behavior**
I expected to find the file that the docs mention.

**Version**
HEAD for istio

**Comment by vadimeisenbergibm** [comment]
@thockin `install/kubernetes/istio-demo.yaml` is in release archives https://github.com/istio/istio/releases. The assumption is that the user uncompresses the archive and runs the commands in the root directory of the archive.

**Comment by rvennam** [comment]
Follow the steps in the Prerequisites section to [download and prepare for the installation](https://istio.io/docs/setup/kubernetes/download-release/). This should put you inside the Istio package directory where you can kubectl commands.

**Comment by sdake** [comment]
@thockin I'd highly recommend if you are working with Istio to use the release-1.1 branch.  The master branch has been blocked for months and is in a bit of a state of disrepair.

Cheers
-steve

**Comment by gnarly-cl0s** [comment]
release-1.1 branch doesn't look to have the istio-demo.yaml file as well... Any recommendations which release to use that will align with the following documentation https://istio.io/docs/setup/kubernetes/install/helm/ ? I ask this because when I tried deploying with tiller, I only see 23 CRDs get created and looking at the crd*yaml files looks to be less than the suggested 53. Im new to istio so I apologies if I am missing something.

**Comment by howardjohn** [comment]
As mentioned above, you need to download the release, please don't install from the repo directly.

I am going to close this as there is no further work that needs to be done, this is already documented. if there are any other questions please reach out on https://discuss.istio.io
