### ISSUE TITLE
K8s: Using common labels with namespace 'app.kubernetes.io' 

### ISSUE THREAD

**Issue by thomschke** [istio/istio#10724]
There are [common labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels) for K8s and Helm [recommends](https://github.com/helm/helm/blob/master/docs/chart_best_practices/labels.md) using these:

- `app.kubernetes.io/name`
- `app.kubernetes.io/version`

Actually Istio requires its [own label set](https://istio.io/docs/setup/kubernetes/spec-requirements):

- `app`
- `version`

Istio should use the common labels (if exists).

**Comment by thomschke** [comment]
Due to multiple app instances are able to run in one service mesh 
Istio has to check following common labels (in this order): 

- `app.kubernetes.io/instance` and if not exists then
- `app.kubernetes.io/name` and if not exists then
- `app`.

and

- `app.kubernetes.io/version` and if not exists then
- `version`.

**Comment by douglas-reid** [comment]
I believe the only changes required here are in the default set of configs for logs/metrics.  Do you want to own the PR to change the default config, @thomschke ?

**Comment by thomschke** [comment]
Hi @douglas-reid, I'm afraid I do not have time for that at the moment.

There are a lot of existings charts out there using `app` and `version`. For backward compatibility it could be better to change the order:

- `app`
- `app.kubernetes.io/instance`
- `app.kubernetes.io/name`

and

- `version`
- `app.kubernetes.io/version`

**Comment by jmazzitelli** [comment]
This has some big ramifications for Kiali. Is this saying that now Istio will look at those other labels as a replacement for "app" and "version"?

So if a deployment has "app.kubernetes.io/instance" that this is the same as saying "app" in the old implementation?

What will be the telemetry label? Right now, the telemetry labels are things like "destination_app" and "source_version". Will these be the same regardless of which actual k8s label was the source of the value for those telemetry labels?

**Comment by jmazzitelli** [comment]
This also is going to require a change in istio.io - the glossary is one place where I know these labels are discussed: https://preliminary.istio.io/docs/setup/kubernetes/spec-requirements/ (see the bulleted item "Deployments with app and version labels")

**Comment by douglas-reid** [comment]
@jmazzitelli my understanding of the request is to pull the information from additional places, not to update the telemetry labels.

**Comment by jmazzitelli** [comment]
> my understanding of the request is to pull the information from additional places, not to update the telemetry labels.

OK. That helps. So it won't affect Kiali's graph querying/generation. Kiali still does look up these optional labels via k8s API for other things it does, so Kiali is going to have to be updated in order to support these multiple app and version labels. Kiali team will track that work here: https://issues.jboss.org/browse/KIALI-2211

**Comment by douglas-reid** [comment]
There is a PR open that is attempting to address this issue. Let's all review that: https://github.com/istio/istio/pull/10807

**Comment by jmazzitelli** [comment]
Please see my comment in the PR regarding this issue - I am questioning if we really want to support multiple label keys to refer to the same app (or same version). See: https://github.com/istio/istio/pull/10807#issuecomment-458659223

**Comment by douglas-reid** [comment]
This is something we should revisit for 1.2. It is not going to be addressed in the 1.1 timeframe.

**Comment by Stono** [comment]
Just to throw my two cents into this, we have 220 or so apps deployed with `app: name`.  Any change you make here would be breaking for us, and difficult to roll out in a non impacting way.

As such I'd need really both labels to be valid for a while, with `app` being deprecated

**Comment by chrisob** [comment]
Any current plans to support the new label names in Istio? We're having to do some hacking to add the legacy `app` label in our clusters just for this issue.

**Comment by cpick** [comment]
I don't think I understand how @istio-policy-bot works, but this would still be very useful.

**Comment by jshaughn** [comment]
In Kiali we allow a single set of configurable app and version label names, defaulting to "app" and "version" to be in line with Istio.  If Istio changes its label names we'll change our defaults likewise.  If Istio allows a mix of label names for app and version, we'll have to deal with it, although it will cause pain because we'll likely need perform multiple queries and aggregate query results for each supported name.  That's for when we query k8s, we would not expect any changes to Prometheus labeling.

**Comment by nesl247** [comment]
Many helm charts are already moving away from `app` and `version`, so we'd now have to add custom labels to get this back for those cases. This should definitely be solved. And since `1.3` is out already, I'm not sure why it's still on the milestone.

**Comment by ryedin** [comment]
Super late to the party, but could this possibly be configurable via a special ConfigMap that both istio and kiali would look for (and if not found just use current defaults)?

**Comment by gustavovalverde** [comment]
Ouch! Going into 1.5

**Comment by douglas-reid** [comment]
Adding @smawson to this issue, as this is at least somewhat related to the Canonical Service proposal.

**Comment by jwenz723** [comment]
+1 for `app.kubernetes.io/name` label to be functional in istio.

**Comment by hzxuzhonghu** [comment]
I donot think we should do this change in risk of breaking existing users.  labels like `app/kubernetes.io` are not officially defined in API, they are just recommendations. Istio does not only work on k8s, it is also for vm app.

**Comment by smawson** [comment]
Is this obsolete with the canonical service work? That supports app.kubernetes.io/name I believe. Doug anything left to do here?

**Comment by douglas-reid** [comment]
We should double-check that v2 telemetry supports the "app" dimension being pulled form `app.kubernetes.io/name` in the short-term (until removal of `{source|destination|_app}` labels).

I think the other bits are maybe updating our `samples` to adopt the convention?

**Comment by jshaughn** [comment]
I think adding canonical_service and canonical_revision in the metrics solves the labeling issue for telemetry.  But because it's unknown which label was used to set the canonical fields it's not possible to use the telemetry values to query for the config objects.  So, for Kiali it's still important that users use a single convention for their labeling, either app/version or app.kubernetes.io/app.kubernetes.io/version.  Kiali currently defaults to app/version for querying objects by label selector.  But it is configurable.  If labeling were mixed it would mean querying different labels to lookup objects, and that is not something we want to do.

**Comment by sshishov** [comment]
Hi guys, we are also aiming to use Istio in our setup, but before starting, we do not want to support `app` and `version` labels as we do not have them. And we do not want to add them just use in Istio because it does not make any sense and bring no value and just adding a lot of duplicating information in our metrics. Can we somehow expect this to be supported in some close version?
Why we just cannot release backward-incompatible release stating that if you want to upgrade to this release, you have to add additional labels to your setup. After the upgrade, they will be able to delete old labels if they do not use them themselves is some metrics collection or other custom logic.

**Comment by jmazzitelli** [comment]
I just want to leave this comment here, because this will come up for those folks that do not want to use "app" and "versions" labels but instead want to use some other convention.

Kiali supports a *single* set of labels - but they can be whatever set you want. The default set is "app" and "version". If you use a different convention (say, "app.kubernetes.io/name" and "app.kubernetes.io/version") then you have to tell Kiali this by defining the "istio_labels" configuration settings with the appropriate label names you are using. For example:

```
istio_labels:
  app_label_name: "app.kubernetes.io/name"
  version_label_name: "app.kubernetes.io/version"
```

See this for details on where this configuration goes:

https://github.com/kiali/kiali/blob/v1.15.0/operator/deploy/kiali/kiali_cr.yaml#L526-L535

**Comment by sshishov** [comment]
@jmazzitelli thanks for update. Looks very easy to set. Do we need any additional changes from `istio` side? Or in other words, what should be overridden to support `app.kubernetes.io` labels E2E?

**Comment by jmazzitelli** [comment]
@sshishov I do not know all the areas within Istio that need to be touched (I'm fairly confident it can be done though). @douglas-reid might know?

**Comment by jshaughn** [comment]
@sshishov Starting in v1.5 Istio introduced canonical_service and canonical_revision into their Prometheus metrics, and these are also now supported by Kiali.   You can use the standard istio labels: "app" and "version" or the standard kubernetes labels: "app.kubernetes.io/name" and "app.kubernetes.io/version".   I believe you can use custom labels by defining the label names onyour service via "service.istio.io/canonical-name" and "service.istio.io/canonical-revision".

If you don't use any of the above then in the metrics canonical_service defaults to the workload name and  canonical_revision defaults to "latest".

If your labelng scheme does not use "app" and "version" then you should configure Kiali as mentioned above by @jmazzitelli or Kiali will fail when searching via these label names.

**Comment by Eslamanwar** [comment]
@jshaughn Thank you for your comment ,but we install istio using istio Operator , and istio operator install kiali as helm chart not with kiali operator , so how to configure kiali to point to "app.kubernetes.io/name" and "app.kubernetes.io/version". labels

**Comment by jmazzitelli** [comment]
> install kiali as helm chart not with kiali operator , so how to configure kiali

Edit the Kiali ConfigMap and reboot the Kiali pod. Something like:

```
kubectl edit cm kiali -n istio-system
kubectl delete $(kubectl get pods -l app=kiali -n istio-system) -n istio-system
```

**Comment by Cajga** [comment]
Ok, so just to summarise the state of this as of today: thanks to the canonical_service and canonical_revision work, it is possible to use the k8s recommended labels "app.kubernetes.io/name" and "app.kubernetes.io/version" for the deployments/pods in Istio.
At the same time, Kiali supports a single label set which is configurable through it's [config map](https://github.com/kiali/kiali/blob/v1.15.0/operator/deploy/kiali/kiali_cr.yaml#L526-L535) (defaults to app/version).

@douglas-reid, @smawson am I correct? Should this ticket be closed? Should we update the [docs](https://istio.io/latest/docs/ops/deployment/requirements/) about this?

P.S.: I am working on a PR to get [ArgoCD installation compatible](https://github.com/argoproj/argo-cd/issues/2784) with Istio and as they use the k8s recommendation for "app.kubernetes.io/name" already I would only add the "app.kubernetes.io/version" for their manifest if this is true...

**Comment by jmazzitelli** [comment]
> At the same time, Kiali supports a single label set which is configurable through it's [config map](https://github.com/kiali/kiali/blob/v1.15.0/operator/deploy/kiali/kiali_cr.yaml#L526-L535) (defaults to app/version).

It is true that if you installed Kiali using today's `istioctl` that is how you configure this for Kiali (i.e. via its ConfigMap). Note that in this case if you change the ConfigMap, you must reboot the Kiali pod.

However, if you install Kiali using the Kiali Operator (which is Kiali's official installation/management mechanism - istioctl will soon no longer be responsible for installing Kiali) then you would update the Kiali CR (not the ConfigMap directly). In this case, no reboot of the Kiali pod is required because the Kiali Operator will handle all the details of updating the ConfigMap and rebooting the pod for you. Note that the link you provided earlier is to [the example Kiali CR](https://github.com/kiali/kiali/blob/v1.15.0/operator/deploy/kiali/kiali_cr.yaml#L526-L535) (though the ConfigMap follows essentially the same yaml format - same names of the settings).

**Comment by douglas-reid** [comment]
@Cajga I think that is *mostly* correct, but there are some edge cases:
- the `(source|destination)_app` labels on metrics still exist and are populated in the v2 extensions directly from the "app" label (example: https://github.com/istio/proxy/blob/master/extensions/stats/plugin.cc#L65-L67). Those labels are "deprecated", but not yet removed.
- Mixer, while deprecated, still exists and populates the `(source|destination)_app` labels when it is used for telemetry.

Should we leave this open until 1.8 dev cycle and remove the old labels then?

**Comment by mwohlin** [comment]
Hello, can you please tell me the current status of this issue?

I am having this problem with Kiali.
If a pod has the label 'app.kubernetes.io/name' then Kiali is using that for the app name.
Otherwise, Kiali is using the label 'app'.

This causes the Kiali graph to separate the pods into different applications in the graph, which is incorrect and confusing to the users.

**Comment by douglas-reid** [comment]
All pods should now have a label derived from either source label: `service.istio.io/canonical-name`. It would be great if Kiali could use that.

**Comment by jshaughn** [comment]
@douglas-reid, @mwohlin  I'm not sure which Istio/Kiali versions are being used in the comment above, but recent versions of Kiali use only the canonical_service and canonical_revision prometheus attributes for graph generation.   Also, when querying k8s for underlying object definitions Kiali consistenly uses either the  app/version or app.kubernetes.io/name/app.kubernetes.io/version scheme, depening on Kiali's configuration (default is app/version).   So it's unclear why you would be seeing mixed results in the graph, but if you are using a mixture of labeling schemes you will at some point end up with issues, as Kiali won't always find the underlying objects.

**Comment by mwohlin** [comment]
@jshaughn @douglas-reid Thank you for the replies.
I am using Istio 1.9.1 and Kiali 1.31, using the istio Operator and Kiali Operator.
After further investigation I have found my issue is related to a mixture of labeling schemes, as you suggested.

When my apps are deployed with helm, via spinnaker, the pod label 'app.kubernetes.io/name' is added, and it has a different value than the 'app' label I supplied. So when I have apps deployed without spinnaker and using helm directly, the label 'app.kubernetes.io/name' is not present. In both cases the 'app' label is also present. From my testing, this version of Kiali is using the label 'app.kubernetes.io/name' if it exists, and otherwise is falling back to the 'app' label.

I will look at setting the app and version label in the Kiali CR as a previous post mentioned to resolve this.

**Comment by jshaughn** [comment]
@mwohlin Glad to help.  Note that canonical_service prefers  `app.kubernetes.io/name` over `app`, and so if the k8s label exists it will be used.  So, if k8s labels are used anywhere then they should be used everywhere.  And Kiali would have to be configured to use them.

**Comment by mwohlin** [comment]
@jshaughn OK, I will set that up. Thank you.

But why is Kiali using `app.kubernetes.io/name` when it is configured to use `app`?

**Comment by jshaughn** [comment]
@mwohlin Kiali uses the configured labels to query k8s when pulling the objects.  So, for example, assume Kiali is configured for `app` and we're looking for `foo` deployments.  We'd query for deployments where `app=foo`.   But that is independent of the istio metric attributes (and it is the metrics that are used to generate the graph).  Istio populates the `canonical_service` attribute using a heuristic that prefers   `app.kubernetes.io/name` over `app`.  And so if something is labeled with both labels, with different values, the metrics will use the value of `app.kubernetes.io/name` for canonical_service.   The metrics DON'T indicate which label value was used to set canonical_service and so Kiali (or any other consumer) doesn't really know where the value came from.  Kiali *assumes* the label value came from label name configured in Kiali when it tries to tie together metrics and object definitions.

**Comment by blatobi** [comment]
Is the documentation [istios application requirments](https://istio.io/latest/docs/ops/deployment/requirements) still wrong? It doesn't state the possibility in using `app.kubernetes.io/name` or `app.kubernetes.io/version` and still recommends `app` and `version`.
From this issue I would have expected, that common `app.kubernetes.io`-labels are preferred in usage.

**Comment by hzxuzhonghu** [comment]
Yes,  to be clear we are now taking `app.kubernetes.io/version` as first option, the docs need to be updated

**Comment by Kyslik** [comment]
Relevant link where this is now documented https://istio.io/latest/docs/ops/deployment/application-requirements/.
