### ISSUE TITLE
if enable istio_cni will take place of OpenShift's network plugin Open vSwitch 

### ISSUE THREAD

**Issue by GavinLin168** [istio/istio#10776]
## Description

Follow https://github.com/istio/cni install `istio` with `helm` by setting 
```
--set istio_cni.enabled=true
```

I found every time container creating will occur error like below
```
Failed create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "1f744d023031c077b7c55d100464e45172b8395e638b1451e3fe0a809b004226" network for pod "istio-pilot-6d86f97f4f-t7qjp": NetworkPlugin cni failed to set up pod "istio-pilot-6d86f97f4f-t7qjp_istio-system" network: incompatible CNI versions; config is "0.3.0", plugin supports ["0.1.0" "0.2.0"], failed to clean up sandbox container 

"1f744d023031c077b7c55d100464e45172b8395e638b1451e3fe0a809b004226" network for pod "istio-pilot-6d86f97f4f-t7qjp": NetworkPlugin cni failed to teardown pod "istio-pilot-6d86f97f4f-t7qjp_istio-system" network: incompatible CNI versions; config is "0.3.0", plugin supports ["0.1.0" "0.2.0"]]
``` 

I have two questions:
- If I set `istio_cni.enabled=true` when deployed istio, if `istio_cni` plugin will take place of OpenShift's default network plugin `Open vSwitch`?  
- How to solve this issue `incompatible CNI versions` ? 

## ENV
```
OpenShift version is 3.11
istio version is 1.0.3
```

**Comment by morvencao** [comment]
@tiswanso Any thought about this?

**Comment by morvencao** [comment]
Let me answer the first question:

CNI plugins are organized as plugin chains, each plugin in the chain should be match the condition specified in plugin configuration before executing it.
1. For `istio-cni` plugin, it will be added to the end of plugin chain and execute when the pod are not in `exclusion` list (plugin config). 
2. If excluded, ignore the pod and return `prevResult` that created by the plugin before.
3. If not excluded, get the pod info for kube api-server and check if pod has a container named `istio-proxy` AND pod has more than 1 container.
4. If yes for the last step, setup `iptables` with the required port list.
5. If not for step 3,  return `prevResult` that created by the plugin before.

**Comment by tiswanso** [comment]
The Istio CNI sets the CNI plugin chain config header with the version 1.3.0 always.  That looks like it's incompatible with this Openshift CNI plugin.  I will open an issue against the istio/cni repo to make this value configurable via the helm chart for istio cni install.

**Comment by luksa** [comment]
> If I set istio_cni.enabled=true when deployed istio, if istio_cni plugin will take place of OpenShift's default network plugin Open vSwitch?
No, the istio-cni plugin is added on top of OpenShift's CNI plugin. When a container is being costructed, first, the OpenShift plugin gets called, then the istio-cni plugin. 

> How to solve this issue incompatible CNI versions ?
The problem is in the openshift-sdn plugin, not in Istio. Openshift-sdn only supports cniVersion 0.1.0 and 0.2.0, but chained plugins were only introduced in CNI 0.3.0. 

Istio-cni can only work with CNI plugins that support CNI version 0.3.0 and higher.

**Comment by tiswanso** [comment]
@luksa is correct.  The CNI v0.2.0 specification doesn't specify "Network Configuration Lists" allowing the chaining of plugins required by Istio-CNI.  

See https://github.com/containernetworking/cni/blob/spec-v0.2.0/SPEC.md  
versus 
https://github.com/containernetworking/cni/blob/spec-v0.3.0/SPEC.md#network-configuration-lists

IMO, we resolve this issue by improving the documentation for the Istio-CNI plugin.

**Comment by morvencao** [comment]
It's really disappointing to know that. 
Looks like there is no better way to workaround `privileged` permission in openshift env, 
except the unofficial `pod-networking-controller` here: https://github.com/sabre1041/istio-pod-network-controller

**Comment by GavinLin168** [comment]
> > If I set istio_cni.enabled=true when deployed istio, if istio_cni plugin will take place of OpenShift's default network plugin Open vSwitch?
> 
> No, the istio-cni plugin is added on top of OpenShift's CNI plugin. When a container is being costructed, the OpenShift plugin gets called first, then the istio-cni plugin.
> 
> > How to solve this issue incompatible CNI versions ?
> 
> The problem is in the openshift-sdn plugin, not in Istio. Openshift-sdn only supports cniVersion 0.1.0 and 0.2.0, but chained plugins were only introduced in CNI 0.3.0.
> 
> Istio-cni can only work with CNI plugins that support CNI version 0.3.0 and higher.

If OpenShift can upgrade openshift-sdn plugin to support cni 0.3.0 ?  Or any other ideas can make istio-cni worked with Openshift-sdn ? Thanks!

**Comment by luksa** [comment]
@morvencao, @GavinLin168:
I'm actually working on making sure that Istio can run on Openshift without any elevated privileges. Effectively, this means I need to make sure that istio-cni works on OpenShift. At this very moment, I'm implementing changes in openshift-sdn, so it will support 0.3.x.

**Comment by GavinLin168** [comment]
@luksa 
May I know which version of OpenShift will support 0.3.x and when it will be ready for use ?

**Comment by luksa** [comment]
@gargnupur Most likely 4.0, but I'll publish my patch as soon as I finish it. Don't know how long it will take - this is the first time I've seen or worked in this part of the code :)

**Comment by GavinLin168** [comment]
@luksa 
Got it. Anyway , thanks very much.

**Comment by luksa** [comment]
@GavinLin168, @morvencao Good news. I have istio-cni working properly with a patched version of openshift-sdn 3.11. See https://github.com/luksa/openshift-origin/commits/cni-0.3.1-support

I need to refactor and clean up before I submit a PR to openshift, but you build and try this out, if you wish.

Note that even with istio-cni, application pods still won't run properly with the `restricted` SCC, because of a different problem - one related to admission control ordering. There is a way around it, but it's not ideal.

**Comment by morvencao** [comment]
> Note that even with istio-cni, application pods still won't run properly with the `restricted` SCC, because of a different problem - one related to admission control ordering. There is a way around it, but it's not ideal.

@luksa Do you mean the `webhook` admission controller order for Istio sidecar auto-injection?

**Comment by luksa** [comment]
@morvencao yes. The SCC admission controller rejects the pod, because the sidecar is injected _after_ the SCC controller adds the necessary capabilities.drop and runAsUser fields to the main pod container. On the second pass, the SCC controller wants to do the same for the sidecar, but isn't allowed to, since this is only a validation pass and mutation is no longer allowed. You can work around this by adding the capabilities.drop and the appropriate runAsUser uid to the sidecar template. But this works only if you know exactly which SCC will get applied to the pod (out of the box, it's the "restricted" SCC, but it could be a different one, depending on the pod definition, any additional SCCs added after openshift installation, etc.).
