### ISSUE TITLE
Remove all nodeports in gateway chart

### ISSUE THREAD

**Issue by thomschke** [istio/istio#10795]
**Describe the bug**
Sometimes there is an install error like this: `release istio failed: Service "istio-ingressgateway" is invalid: spec.ports[1].nodePort: Invalid value: 31390: provided port is already allocated`

**Expected behavior**
Please remove all nodePort (if possible)

https://github.com/istio/istio/blob/565aaa99dcfc7d584e9f8eb9a04844b0b0faa1d5/install/kubernetes/helm/subcharts/gateways/values.yaml#L38
https://github.com/istio/istio/blob/565aaa99dcfc7d584e9f8eb9a04844b0b0faa1d5/install/kubernetes/helm/subcharts/gateways/values.yaml#L41
https://github.com/istio/istio/blob/565aaa99dcfc7d584e9f8eb9a04844b0b0faa1d5/install/kubernetes/helm/subcharts/gateways/values.yaml#L45

**Version**
k8s (1.11.5-gke.5), istio (1.1.0-snapshot.3)

**Installation**
Helm chart

**Environment**
GKE

**Comment by quanjielin** [comment]
/cc @costinm @quanjielin 
is this issue propose removing nodeport type option from istio ingress-gateway ? if yes, then pls keep this since we have a user case that requires istio ingress-gateway to be nodeport type.

**Comment by ymesika** [comment]
@quanjielin This issue is not about removing the type. It's about avoid using our fixed values for the requested node ports so k8s can assign one of the avail ones.

Anyway, since our users (with their docs, scripts, etc) are pretty much used to the port number that we have historically chose for them I guess it's too late to remove this.

@thomschke If you have such an issue you can comment the predefined nodes locally on your deployment as I tend to agree we need to keep those values for the reason above.

**Comment by thomschke** [comment]
LGTM

like this:
https://github.com/istio/istio/blob/565aaa99dcfc7d584e9f8eb9a04844b0b0faa1d5/install/kubernetes/helm/istio/values-istio-gateways.yaml#L70
https://github.com/istio/istio/blob/565aaa99dcfc7d584e9f8eb9a04844b0b0faa1d5/install/kubernetes/helm/istio/values-istio-gateways.yaml#L73
https://github.com/istio/istio/blob/565aaa99dcfc7d584e9f8eb9a04844b0b0faa1d5/install/kubernetes/helm/istio/values-istio-gateways.yaml#L76
