### ISSUE TITLE
The log format of ingressgateway is incorrect 

### ISSUE THREAD

**Issue by wjwinner** [istio/istio#10871]
**Describe the bug**
```
[2019-01-10T16:05:53.571Z] "GET /api/card/sendHTTP/1.1" 200 - 0 2 1 1 "10.20.1.2" "-" "f562355c-351b-4ab6-aeaa-805c85c439a5" "cm.demo.com" "10.18.57.206:8080" outbound|8080|online-iqigu|web-online.demo.svc.cluster.local - 10.18.56.160:80 10.20.1.2:49700
```

as you can see, the uri path and protocol are mixed together.

**Version**
1.0.5

**Comment by l10xbin** [comment]
I think this issue was resolved latest code.  Here are the logs in version1.1-20181202-09-15.

 "GET /productpage HTTP/1.1" 200 - 0 5719 99 95 "10.244.0.0" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.80 Safari/537.36" "18065eca-40bd-43f4-a2bd-a41d90c22020" "xxxx:31380" "10.244.1.56:9080" outbound|9080||productpage.default.svc.cluster.local - 10.244.1.52:80 10.244.0.0:58967 -

**Comment by hzxuzhonghu** [comment]
Remember it's resolved
