### ISSUE TITLE
TestSecretCreationKubernetes is failing

### ISSUE THREAD

**Issue by hklai** [istio/istio#10989]
Error log
https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/10984/istio-integ-k8s-tests/1722

```
error	CI	Wait for Istio pods failed: timeout while waiting (last error: 4 errors occurred:
info	CI	=== FAILED: Deploy Istio ===
info	CI	=== BEGIN: Dump state (citadel_test) ===

```

**Comment by JimmyCYJ** [comment]
I have set up a GKE cluster and run this test a few times, all those runs passed. I think this error is caused by the test framework. The error shows that istio is not deployed successfully because some containers are not ready (pilot, mixer, galley). Citadel is running and is ready.

info	CI	Checking pods...
info	CI	  [ 0]                 istio-citadel-8cdb5fc59-2kh4h         Running (Ready)
info	CI	  [ 1] istio-cleanup-secrets-70985297d22d0c9b1ae52f49c5afc41a-wzd9j       Succeeded (Ready)
info	CI	  [ 2]          istio-egressgateway-6ddd6cd9fb-jpl97         Running (Ready)
info	CI	  [ 3]                 istio-galley-8579478bb9-wd296         Pending (Pending)
info	CI	  [ 4]         istio-ingressgateway-56cc9bf5b9-57j5m         Running (Ready)
info	CI	  [ 5]                  istio-pilot-7594cdffbd-6hlhq         Running (container not ready: 'discovery')
info	CI	  [ 6]                  istio-policy-9df4956b4-gpc6p         Running (container not ready: 'mixer')
info	CI	  [ 7] istio-security-post-install-70985297d22d0c9b1ae52f49c5afc4qhbfg       Succeeded (Ready)
info	CI	  [ 8]        istio-sidecar-injector-5d485cc9c-br7cm         Running (Ready)
info	CI	  [ 9]              istio-telemetry-6595854c7d-gzfk8         Running (container not ready: 'mixer')
info	CI	  [10]                   prometheus-58ffbfd8f4-kjjr2         Running (Ready)
error	CI	Wait for Istio pods failed: timeout while waiting (last error: 4 errors occurred:

https://github.com/istio/istio/pull/11038 and https://github.com/istio/istio/pull/11048 addressed this issue.

**Comment by hklai** [comment]
It still fails after those two PRs.
https://gubernator.k8s.io/build/istio-prow/logs/istio-integ-k8s-tests/1873

**Comment by smawson** [comment]
I think this is still failing, Jimmy can you take a look?

**Comment by ozevren** [comment]
Can you add more details, and open another bug? We can disable the test to reduce overall flakes, but let's try to understand what the root cause is. What was causing the pods to be in the pending state? Did you check their status to see what might be going wrong?

**Comment by ozevren** [comment]
This is fixed.
