### ISSUE TITLE
e2e-bookinfo TestExternalDetailsService is flaky

### ISSUE THREAD

**Issue by hklai** [istio/istio#11026]
Example: https://gubernator.k8s.io/build/istio-prow/logs/e2e-bookInfoTests-envoyv2-v1alpha3/12667

`main_test.go:230: could not find 0486424618 in response`

**Comment by linsun** [comment]
@mbanikazemi can you help look at this issue?

**Comment by linsun** [comment]
would be good to check if this flaky also exists in circle....

**Comment by mbanikazemi** [comment]
I see a single test failing in one run in the past couple of weeks: https://testgrid.k8s.io/istio-postsubmits#e2e-bookInfoTests-envoyv2-v1alpha3
That test fails because the details is not returned in the bookinfo example page. This can possibly be because the details service was not available on time for the request sent to it to get a response. Anyway, I will keep an eye on this test to see if it fails again. As is there has not been a failure for several days.

**Comment by mbanikazemi** [comment]
@hklai  Shall we close this issue?

**Comment by duderino** [comment]
@hklai assigning back to you to accept or reject

**Comment by hklai** [comment]
This has not happened for over a week according to testgrid. Closing for now.
