### ISSUE TITLE
istio upgrade failed at roll back stage

### ISSUE THREAD

**Issue by linsun** [istio/istio#11054]
Based on https://storage.googleapis.com/istio-prow/pr-logs/pull/istio-releases_pipeline/209/release-upgrade-tests-1.0.2/223/build-log.txt

upgrade actually worked from 1.0.x to 1.1
Roll back data plane also worked, but roll back control plane failed:

****************

Starting rollback - first, rolling back data plane to istio-release-1.1-20190117-09-15

****************

configmap "istio-sidecar-injector" deleted
configmap "istio-sidecar-injector" created

****************

Restarting deployment echosrv-deployment-v1, patching label to force restart.

****************

RUNNING kubectl patch deployment echosrv-deployment-v1 -n test -p{"spec":{"template":{"spec":{"containers":[{"name":"echosrv","env":[{"name":"RESTART_1547718243","value":"1"}]}]}}}}
deployment.extensions "echosrv-deployment-v1" patched

****************

helm installing version 1.0.2 from istio-1.0.2.

****************
...
Error from server (InternalError): error when applying patch:
{"metadata":{"annotations":{}}}
to:
&{0xc420eb8600 0xc42008de30 istio-system istio-autogenerated-k8s-ingress /home/prow/go/src/istio.io/istio/istio.yaml 0xc4204c43c8 17092 false}
for: "/home/prow/go/src/istio.io/istio/istio.yaml": Internal error occurred: failed calling admission webhook "pilot.validation.istio.io": Post https://istio-galley.istio-system.svc:443/admitpilot?timeout=30s: no endpoints available for service "istio-galley"

**Comment by ostromart** [comment]
I'm guessing this may be due to pods being ready from the last version, not the target version. 
The script applies a new manifest and immediately checks if pods are ready:

installIstioSystemAtVersionHelmTemplate "${FROM_HUB}" "${FROM_TAG}" "${FROM_PATH}"
waitForPodsReady "${ISTIO_NAMESPACE}"

This just greps kubectl get pods output to check pod status. 
It's reasonable to do that from a clean slate, but not for downgrade, because new pods may not yet be fully visible in get pods output. 
If this is the root cause a sleep 10 should make the problem go away. Let's try that, if it works we can figure out a more robust way of testing for pod readiness.

**Comment by linsun** [comment]
That seems odd @ostromart.  Looking at the script, it starts roll back data plane then control plane.  I don't see any where it removes 1.1 control plane or 1.0 control plane either so no reason for galley to be not ready.

**Comment by linsun** [comment]
checked 1/21's log, it is failing at roll back too.

My guess is that we have an CRD incompatible.  when 1.1's CRD is installed, it will fail 1.0's control plane.

**Comment by ostromart** [comment]
The script doesn't explicitly remove the control plane but since the images are updated there's a restart. We're updating control plane in place, not doing both versions side by side (we should try this sometime but afaik we it's completely untested so if it works it's by accident rather than intent).

Coming back to the error log I looked at, the error says:
webhook "pilot.validation.istio.io": Post https://istio-galley.istio-system.svc:443/admitpilot?timeout=30s: no endpoints available for service "istio-galley"

So what seems to be happening is that the k8s API server is calling out to the admission webhook (for which galley has registered itself) but it's not there (yet).
I tried the same script with the same version locally and the downgrade worked for me so that also points to a race on the test cluster. It also happens that galley is usually the last pod to come up typically.
I think the way forward would be to retry applying the manifest, because galley itself  and the things it's verifying are in the same manifest. 
Currently the focus of this script is checking for 503 during up/downgrade and we are not checking all the different ways of upgrading. We may also want to consider doing a separate test which is more of a tiller functionality test. That will be a bit more complex because the recipes are different for different versions.
