### ISSUE TITLE
DestinationRule resolution allows for cross-namespace interference

### ISSUE THREAD

**Issue by louiscryan** [istio/istio#11058]
**Describe the bug**
The current behavior of Pilot attempts to resolve a DestinationRule for a k8s Service or ServiceEntry by first looking in the namespace where the service is being consumed and then searching in all namespaces in the system. This global search makes resolution of DestinationRules hard to reason about and can lead to situations where peer namespaces interfere with each others behavior potentially leading to security issues

**Expected behavior**
The DestinationRule to be applied when a service is consumed should be resolved in the following order
- Search the namespace where the service is being consumed
- Search the namespace where the service is defined
- Search a default 'root' namespace under administrator control. Default should be 'istio-system' but should be overrideable.

**Steps to reproduce the bug**
Setup a structure like the following

Namespace A:
     ServiceEntryA1(host=myservice.internal.net)
     DestRuleA1(host=*, TLS:off)

Namespace B:
     VirtualService(blah, destination=myservice.internal.net)

... at this point DestRuleA1 will be used, now create ...

Namespace C:
     DestRuleC1(host=*.net, TLS:on)

... and the TLS behavior of the VirtualService defined in Namespace B changes to that defined by DestRuleC1 which is problematic. In the proposed solution DestRuleA1 would remain in effect

**Version**
1.0 and earlier

**Comment by louiscryan** [comment]
@Stono can you take a look and see if this works for you

**Comment by louiscryan** [comment]
For those reading along there is a similar issue in 1.0 with VirtualService declarations having impacts across namespaces for sidecar behavior. The new Sidecar resource resolves that problem substantially though it doesn't change the default behavior when Sidecar is not used. In general the project is working to correct these issues by treating namespaces as isolation boundaries.

**Comment by myidpt** [comment]
@diemvu

**Comment by boazjohn** [comment]
Hi, 

Would agree @louiscryan, I feel it'll be better if the `ServiceEntry` and `VirtualService` defined in namespaces would be applied for that namespace alone. Is there any reason behind this being extended to all namespaces?

I didn't know this could create problem. I have two namespaces right now which usually has similar rules or non-colliding rules and there are some core components sitting outside the mesh (mostly legacy).

**Comment by linsun** [comment]
at the first glance, I am hesitate to introduce another new rules for this now that we have sidecar API.  I'm worried about 2 types of valid configuration (when side car api is used or not) to resolve this conflict and the complexity that user has to understand the caveats.

**Comment by frankbu** [comment]
Would a more general configuration approach be better, or overkill? Allow administrators to configure a `namespacePath`, which is used instead of "any namespace". The algorithm would then be:

1. Search the namespace where the service is being consumed.
1. Search the namespaces in the configured `namespacePath`. A `namespacePath` set to '.:istio-system', where `.` is the namespace where the service is defined, would work the same as the suggested algorithm above, but would be more generally configurable.

Maybe this configured `namespacePath` could even be useful for other things as well?

**Comment by rshriram** [comment]
fixed by #11153 and #11387 
@boazjohn in 1.1, you can set a global default export setting in the mesh config (defaultServiceExportTo, defaultVirtualServiceExportTo, defaultDestinationRuleExportTo) to '.' (for namespace local visibility) or '*' for global visibility.

You can also set the exportTo field in a virtualService or ServiceEntry to . or * for a more fine grained control over whether the service/vs/dr is visible locally or globally.
