### ISSUE TITLE
Ingress routes to incorrect podIP

### ISSUE THREAD

**Issue by Gadigg** [istio/istio#11112]
**Describe the bug**
We have a cluster with a lot of services. This doesn't always happen, but is frequent enough. Ingress returns 503 error, browser displays: `upstream connect error or disconnect/reset before headers.`
It seems that the istio-pilot does not map a new service deployed to the right IP thus making the pod unreachable.
The weighted routing works as expected but when routed to the new pod it's unreachable.

**Expected behavior**
The IP of the new pod should be routed correctly

**Steps to reproduce the bug**
Deploying a virtual service with weighted routes that points to different pods.

**Version**
```
istioctl version: 1.0.4
kubectl client version: v1.13.1
kubectl server version: v1.11.5-eks-6bad6d
```

**Installation**
Using Tiller and Helm

**Environment**
running on AWS EKS

I didn't find any new issue about this bug in this repo but did find someone that posted it on the old repo and had no answer since v0.8 apparently, you can find it [here](https://github.com/istio/old_issues_repo/issues/342)

Thanks!

**Comment by esnible** [comment]
503 means "Service Unavailable".  My experience with Istio has been that 503s are usually caused by a problem with TLS, not with Pod IP addresses.  Both your pod and the Ingress must read the mTLS configuration option and certs.  If the pod didn't contact, or if a cert has expired, this can happen.

Run `istioctl authn tls-check` to make sure the pods have the expected TLS settings.

To check the IP that the Ingress uses, do `kubectl -n istio-system port-forward $(kubectl -n istio-system get pod --selector istio=ingressgateway --output jsonpath='{.items[0].metadata.name}') 15000` and then use your browser to visit http://localhost:15000/clusters .  You will see something like `outbound|<port>||<hostname>::<ip>::cx_total::<number>`.  If the IP is correct for the hostname then the problem is NOT the PodIP.

If you are still getting 503 errors reply here and I will suggest additional troubleshooting strategies.

**Comment by linsun** [comment]
closing this, no response in 30 days.  Most if not all 503 are fixed with sidecar resources when there are lots of services.
