### ISSUE TITLE
Do not store generated installation files

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#1113]
To reduce the likelihood of conflicts in istio/istio, the proposal is to not store the generated istio.yaml, istio-auth.yaml..., since they can easily be produced by running install/updateVersion.sh.

They will still be part of the weekly release artifacts.
e2e tests need to be updated to generate them.

**Comment by ldemailly** [comment]
that's an easy starter task for anyone who wants to start helping with istio install

can also be done as part of https://github.com/istio/istio/issues/851 or https://github.com/istio/istio/issues/706

**Comment by andraxylia** [comment]
Related to #1187

**Comment by yutongz** [comment]
fyi @sebastienvas 
We will switch to use yaml template in pilot and mixer to generate install yaml for istio/istio e2e, under the assumption of visual/physical mono-repo. And this also requires change on the way Prow works.

**Comment by sebastienvas** [comment]
I think this aligns with https://goo.gl/v5jv1o. I am also thinking of getting rid of the updateVersion.sh all together since istio.VERSION is going away. More details once we have a global build working.

**Comment by mattdelco** [comment]
The release build no longer relies on the generated files since it does run updateVersion.sh before creating the tarballs.  I didn't nix the generated files in git since I didn't know what else might depend on them.  I also tried to adjust updateVersion.sh so it can't be told to output to a different directory location, though I'm not actually using it yet since the runtime behavior of the script still seemed to have some dependencies on the source tree that still needed to be straightened out.

**Comment by andraxylia** [comment]
The files were there mostly for the release, developers can always run updateVersion. Let's nuke them.

**Comment by ldemailly** [comment]
see also #2141

I think we need a make target to generate istio.VERSION for the last green build for developers as well for custom tags

**Comment by mattdelco** [comment]
Most of the comments I've heard about istio.VERSION was to eventually get rid of it but I don't know what alternative was in mind (nor which people might be confusing it with istio.RELEASE).  The green builds from CI aren't saved.  There are the daily builds, and for that I don't have all the details on how people might consume those.  The Release Process will explicitly start tests on successful daily builds, and docker users will eventually have tags they can reference, but I don't know about debian.  Some test are fired off based on a PR (I think it's on the istio-releases/daily-release repo), and it likes like commits are being made to the repo with references to the build so that source (or similar) might be what people have in mind.

**Comment by costinm** [comment]
Using semantic labels solves this problem.

Users want to install or update current stable/weekly/testing/nightly
version. Some developers reproducing a bug may need
a bug report that includes an actual git commit or sha.

It is very rare for a prod user to download a .tar.gz with files and run
some shell scripts from the internet.
People may use 'apt-get install' or helm or "docker run", but almost all
software I know switched to semantic
versioning.

Let's just get rid of istio.VERSION.

**Comment by ldemailly** [comment]
I'll repeat we need a way to get the latest validated tag (and use it for dev install and local e2e tests before local modifications and an clear way to apply local changes)

having a way to drive it all from say a single `0.5.0-pre20180101` tag for the base, that would be whatever was the last good known build on 1/1/2018 (in this example) would be great. we could also have "latest-daily" but I think a real version/tag is cleaner

**Comment by costinm** [comment]
Let's not conflate 'end users' with developers and automated tools.

I was talking about removing istio.VERSIONS from the release and from
github, and not exposing it to end users.

For istio devs - yes, we do need the 'lock' file and all other git version
info part of the artifacts. I don't mind
generating an istio.VERSIONS next to the lock file if it helps some tool. I
agree with you, it is critical
for debugging/repro to know exactly what was used.

But the istio user experience should be 'apt-get install istio' or 'helm
install istio' or click a button.
( with brew or whatever to install istioctl/kubeclt on a mac). Ideally long
term istio will just be
pre-installed.

**Comment by andraxylia** [comment]
Until we have better alternatives, kubectl apply -f istio.yaml is still a good option.

It means istio.yaml is available in the release, and not necessarily that it is stored in github.

**Comment by rkpagadala** [comment]
Fixed.

**Comment by ldemailly** [comment]
fixed in #2378
