### ISSUE TITLE
Missing namespace definition for Bookinfo samples

### ISSUE THREAD

**Issue by kramvan1** [istio/istio#11202]
**Describe the bug**
Resource in kube that are namespace specific should specify the namespace in the resource definition.

**Expected behavior**
Bookinfo resources have namespace defined, even pull from chart value if wanted.

**Steps to reproduce the bug**

**Version**
1.0.5

**Installation**

**Environment**

**Cluster state**

**Comment by kramvan1** [comment]
@linsun

**Comment by mabushey** [comment]
Istio is amazing, but the docs are so far off that it's a wild goose chase. Your Istio time can be better optimized by ignoring any Istio docs / tutorial that are anything but conceptual/high level.

**Comment by esnible** [comment]
The reason _samples/bookinfo/platform/kube/bookinfo.yaml_ has no namespace is so that users can easily deploy to other namespaces.

For example, some Kubernetes environments are locked down so a user only has a particular namespace, not called "default".  I can say `kubectl apply -n esnible -f samples/bookinfo/platform/kube/bookinfo.yaml` to start BookInfo in the `esnible` namespace.
