### ISSUE TITLE
Support http 1.0 traffic in Istio

### ISSUE THREAD

**Issue by wattli** [istio/istio#11235]

**Comment by duderino** [comment]
@costinm @rshriram @PiotrSikora, any objection to just turning HTTP/1.0 on by default?  Does it have to be exposed to the user or can this just be between Pilot and Envoy?

**Comment by duderino** [comment]
@philrud will work on this, but I can't assign the bug to him until he becomes a member of the github org

**Comment by PiotrSikora** [comment]
@wattli any context?

@duderino isn't Pilot<>Envoy over gRPC?

**Comment by duderino** [comment]
More specifically, this is for traffic from the application to the sidecar (aka sidecar capture).   

See https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/core/protocol.proto#envoy-api-msg-core-http1protocoloptions - specifically  "accept_http_10"

In the interest of expediency, @costinm will take this on himself.

**Comment by PiotrSikora** [comment]
Yup, sorry, I got confused by "can this just be between Pilot and Envoy", but I see that you only meant that for "hardcoded" config emitted from Pilot (i.e. always set `accept_http_10: true`) and not for HTTP/1.0 traffic between Pilot and Enovy.

**Comment by esnible** [comment]
Adding the user-experience tag because this greatly confused me when I started Istio.

Our documentation at https://istio.io/docs/setup/kubernetes/quick-start/ says "... HTTP/1.0 is not supported"  If we choose NOT to support 1.0, we should add some documentation that if installing Istio causes "426 Upgrade Required" errors for apps using 1.0.  Users who hit this will do a web search on the error code, 426, not the problem.

**Comment by costinm** [comment]
Fixed in 1.1

**Comment by hmakkapati** [comment]
Costin's fix: https://github.com/istio/istio/pull/11511

**Comment by Sherler** [comment]
> Fixed in 1.1

Is there any instructions to help us enable this feature?

**Comment by wu0407** [comment]
> > Fixed in 1.1
> 
> Is there any instructions or demo to help us enable this feature? @costinm

istioctl manifest apply  --set values.pilot.env.PILOT_HTTP10=1
