### ISSUE TITLE
1.0  1.1 compat error for pinned proxy

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#11295]
1.1 introduced a new options `--statusPort`  and `applicationPort` to the pilot agent.

Istio also supports annotation
`sidecar.istio.io/proxyImage: gcr.io/istio-release/proxyv2:release-1.0-20180703-03-01` to force the sidecar injector to use a specific version of the proxy. 

At present,  1.1 control plane cannot use 1.0 proxy because the sidecar injector generates command line that the pilot agent cannot understand. we get the following error message
```
kubectl --namespace test logs fortio10rc1-7dcf96576c-d6csr --tail=20 -c istio-proxy
Error: unknown flag: --statusPort
2019-01-26T01:58:15.866535Z     error   unknown flag: --statusPort
```

We have several options
1. If you pin a proxy version, it is up to the user to ensure they are compatible
2. Make the sidecar injector cognizant of the pinned versions and generate correct config for at least 1 prior version.
3. To address the current problem, use good default in the code for --statusPort`  and `applicationPort`, which means the sidecar injector should only add those params if they differ from the defaults.

Additionally, for future proofing, we should make pilot agent accept unknown command line parameters with a warning.

**Comment by mandarjog** [comment]
@costinm @sdake Should we care about this type of upgrade? or proxy annotations not supported with upgrades ?

**Comment by sdake** [comment]
@mandarjog,

We lack a written upgrade policy (and we should probably develop one or present a best practices guide to guide development).

For pinned proxy sidecars via annotations where an operator is using an old proxy with a new control plane, I'm not clear we support that model (option 1 in your list).

for option 2, I was thinking of this exact workaround as I was reading the problem description.

I am a little concerned with the future proofing proposal, as that may result in a situation where proxy n-1 doesn't work with control plane n because a specific option was added that is completely incompatible.

My general question is what happens when the control plane is upgraded to 1.1 and all sidecars are running proxy 1.0?  They are not reinjected unless the pod is deleted (and recreated by the deployment).  In a deletion/recreate condition, there is an upgrade to the proxy 1.1 image.

Does the control plane continue to work with Istio proxies from 1.0 for existing proxies in the mesh that haven't been reinjected?

One final question - when does the annotation occur?

One thing we want to ensure continues to work is a control plane upgrade to 1.1 with proxy 1.0 images in the mesh (without annotation) as this should be the general case if annotation addition is not automated.

Thoughts?

Cheers
-steve

**Comment by incfly** [comment]
`statusPort` and `applicationPorts` are already there when I started build liveness health check on top of it. I don't have full context of why they were introduced in the first place.

The health check prober rewrite logic already look at injection spec and see if the `statusPort` is present or not. If not, skip rewriting.

I'll make sure the liveness probe to use environment variable to pass app prober config, not making the problem more complicated.

**Comment by sdake** [comment]
@mandarjog need more information if I am to take a look.
