### ISSUE TITLE
Mixer Performance Issues

### ISSUE THREAD

**Issue by clyang82** [istio/istio#11400]
from our performance testing results - https://ibmcloud-perf.istio.io/index.html/. when enabled istio, the TPS is around 2000. it is reduce 1400+ comparing with no mixer.

| Release | (A) Istio Full | (B) No Mixer | (C) Ingress Only |
|-- | -- | -- | -- |
| release-1.1-20190128-09-16 | 1980 | 3411 | 4776

With the above result, it seems the mixer is a blocker for the real production environment. I know that some users choose to disable the mixer for the production. Do we have some best practices to improve the TPS with mixer enabled? @douglas-reid @geeknoid @mandarjog 

for instance:
1. remove stdio and stdiotcp rules
2. change accessLog to ''

FYI @gyliu513 @morvencao

**Comment by iandyh** [comment]
afaik, mixer has two components: 1. policy 2. telemetry. `istio-policy` sits in the data plane and will be called when new connection is established. So having policy will impact the performance.

On the other hand, `istio-telemetry` is an async call. It should not affect the overall performance too much. 

Since 1.1, you can disable policy when installing the istio. So probably use that option?

Hope it helps.

**Comment by clyang82** [comment]
@iandyh Thanks for your information. I think this option (disable policy) is worth to have a try.
@suryadu is it possible to add this case in https://ibmcloud-perf.istio.io/index.html/? Thanks.

**Comment by jnativio** [comment]
@clyang82  You are seeing the impact of telemetry in the final throughput basically because all Istio components run in the same worker node in regression patrol. That means that Telemetry (the biggest user of CPU) "steals" CPU cycles from other components, in particular from the Ingress GW.  As said before, Telemetry is not directly in the data path, but in situations like this can impact drastically the performance. So, one recommendation is to keep Telemetry pods in a separate nodes, if the size of your cluster supports that. Stdio adapter is already disabled in regpatrol, and should not be enabled in production. We are experimenting filtering the metrics to prom adapter to decrease the CPU required by Telemetry, and there are other optimization initiatives ongoing.

**Comment by jnativio** [comment]
As for the impact of disabling policy checks, I have made this measurement in the past and there is not much, at least in a small scale environment. We can refresh this measurement, but it would be impractical to add this scenario to regpatrol.

**Comment by suryadu** [comment]
@clyang82 Istio Performance WG has been working on many optimizations across Istio components many of them targeted for v1.1 (https://docs.google.com/document/d/17PfZkXGpiVk3qAQdnB_ASSIGvnV7ZKwH6RXBN3c8_so/edit). Your issue appears to be caused by application services not getting enough resources to process the transactions. Please try to remove the bottleneck by moving Mixer pods to a separate node from app services. As Jose mentioned, the main resource cost in mixer is coming from Telemetry and we have many optimization ideas to reduce this resource usage. For now, please place mixer components in a separate node and give enough resources which will help scale your application services.

Here is the CPU distribution of current Istio v1.1 build using our Blueperf microservices workload.
The 2 pie charts below show the CPU distribution of Blueperf app with Istio and CPU distribution among Istio components respectively (so dissecting that 28% Istio resulted in 2nd pie chart). 
![image](https://user-images.githubusercontent.com/13684010/52059801-5ff41380-2530-11e9-813c-76a3ecf16c27.png)

**Comment by suryadu** [comment]
We are in the process of preparing a Performance Best Practices guide, Sizing and Capacity planning guide and Istio performance report and we will make this available on istio.io @mandarjog @douglas-reid @clyang82 @iandyh @geeknoid

**Comment by iandyh** [comment]
@suryadu Thanks for your information! In the V1.0, the expected performance of telemetry is 1core per 1000QPS, is this number get improved in the 1.1? Thank you.

**Comment by mandarjog** [comment]
This is the [1.1-snapshot.4 performance dashboard](https://snapshot.raintank.io/dashboard/snapshot/jkyC88H4PAIiHHYY6Oa6lY7aVp4gwC0M).
~0.8 core per 1000QPS

**Comment by douglas-reid** [comment]
Can this issue be resolved?  We have encoded the best practices in the defaults for 1.1.

**Comment by clyang82** [comment]
Yes. release 1.1 have some best practices to improve the performance issues. Let me close it. Thanks.
