### ISSUE TITLE
When istio opens readiness, connection reset by peer appears？

### ISSUE THREAD

**Issue by kuaiwenwu** [istio/istio#11467]
**D

Hello, everyone. I have a problem here.

I run in istio service. After opening readiness check, kubectl description found that random IP and random port forwarding could not be detected. It prompted the following errors:

Ps: Enter the total curl of pods and access http://10.244.3.212:8083/sys/actuator/health normally.

**### **_Node3.server Readiness probe failed: Get http://10.244.3.212:8083/sys/actuator/health: read TCP 10.244.3.1:49372->10.244.3.212:8083: read: connection reset by peer

Warning Unhealthy 5m kubelet, node3.server Readiness probe failed: Get http://10.244.3.212:8083/sys/actuator/health: read TCP 10.244.3.1:49400->10.244.3.212:8083: read: connection reset by peer

Warning Unhealthy 5m kubelet, node3.server Readiness probe failed: Get http://10.244.3.212:8083/sys/actuator/health: read TCP 10.244.3.1:49418->10.244.3.212:8083: read: connection reset by peer

Warning Unhealthy 4m kubelet, node3.server Readiness probe failed: Get http://10.244.3.212:8083/sys/actuator/health: read TCP 10.244.3.1:49432->10.244.3.212:8083: read: connection reset by peer_****
How can I solve this problem?

![wechatimg1](https://user-images.githubusercontent.com/24381401/52101260-bb4c0180-2615-11e9-9623-6136447dc91f.png)

**Comment by eason574671212** [comment]
Plus: My istio version is 1.0.2

**Comment by pauldthomson** [comment]
I was having the same issue, mine was because I was using the same port for the app and health check and we have mutual TLS enabled. Kubelet doesn't present a client cert as mentioned here: 
_"Note that the image in liveness-http exposes two ports: 8001 and 8002 (source code). In this deployment, port 8001 serves the regular traffic while port 8002 is used for liveness probes. Because the Istio proxy only intercepts ports that are explicitly declared in the containerPort field, traffic to 8002 port bypasses the Istio proxy regardless of whether Istio mutual TLS is enabled. However, if you use port 8001 for both regular traffic and liveness probes, health check will fail when mutual TLS is enabled because the HTTP request is sent from Kubelet, which does not send client certificate to the liveness-http service."_ 
from https://istio.io/docs/tasks/traffic-management/app-health-check/

**Comment by taitelman** [comment]
I must admit I hit this same bug with Istio v1.9.6 . I had a deployment which is not exposed to HTTP at all. I added , just for sake of health check , an HTTP endpoint at port 9200. didn't edit the deployment.yaml and for some reason it worked well for most of istio 1.8 and 1.9 . However, in istio 1.9.6, I was forced to add the `containerPort: 9200` to make HTTP health endpoint work again.
