### ISSUE TITLE
have telemetry be able to discern mirrored traffic from "normal" traffic

### ISSUE THREAD

**Issue by jmazzitelli** [istio/istio#11475]
**Describe the feature request**

Right now there is a bug #11093 that causes a hole in the telemetry when mirroring traffic.

There is a separate discussion (see that bug #11093 for the start of that discussion) involved - and that is, how can Istio indicate that traffic is "mirrored" traffic versus "normal" traffic.

This enhancement request is to ask if Istio could somehow specifically indicate that telemetry came from mirrored traffic or not.

**Describe alternatives you've considered**

Using that hole in telemetry is kinda useful - but it isn't necessarily true that if you see destination telemetry but not source telemetry, that means this traffic was dark traffic. So this isn't proof of mirrored traffic, only a hint, and users must be on the lookout for that hint - it isn't obvious unless you know you are looking for it.

Also, this only indicates mirrored traffic on the "first hop" - not further downstream.

If it is not possible to mark telemetry all the way downstream that it was generated from a mirrored request, at minimum it would be useful to know for sure that the "first hop" came from mirrored request (i.e. do not rely on a coincidental side-effect of a hole in telemetry to know this).

**Comment by douglas-reid** [comment]
@jmazzitelli will the work to add virtual service and destination rule metadata (which will get converted into attributes) start to help here?

It should enable us to tag traffic (for the first hop, at least) as coming from a particular virtual service.

We'd probably need to expand that metadata to include subset names and/or mirror indications, however.

**Comment by jshaughn** [comment]
I'm not sure how important it is to be able to identify downstream traffic that started due to a mirrored request.  That borders on tracing.

What makes Istio telemetry tough to represent is that a single request is sometimes found only in source telemetry (failed requests that does not make it to a workload), sometimes only in dest telemetry (istio-system traffic, unknown traffic, this intial mirrored traffic situation) and often in both source and dest telemetry (most successful traffic).

In the Kiali graph we generally use source telemetry and special-case the needs where we know there is only dest telemetry.  That is why there is this "gap" or "missing first request" in the mirrored situation; it has no source telemetry.  I'm not sure what the best solution is, but maybe "virtual" source telemetry would be useful, where the source is the VS.  That would likely result as a node in the graph that represents the root of the mirrored traffic.  We'd likely need the time series to contain enough information to find the definition via istio api (perhaps to know if the VS is still defined) but minimally some indication that it is a "virtual" node.

**Comment by pilhuhn** [comment]
This is imo still valid

**Comment by jshaughn** [comment]
@douglas-reid , Will the proposed addition of request service info help resolve this issue?  In other words, will we see the original, and mirrored requests in source telemetry, each with the same request service?

**Comment by jmazzitelli** [comment]
@douglas-reid I think this is still valid. How will telemetry be able to discern mirrored traffic versus non-mirrored traffic?

**Comment by jshaughn** [comment]
I'm not aware of anything that has resolved this issue.  The initial question is whether it's even feasible to provide this telemetry in V2.  If it's not feasible or not going to be done then this issue should be closed and the telemetry hole just made a known issue.  Otherwise, it would probably look like something where you have time-series with the same source and request_host, but with different destination services.  It may be hard to know that these are mirrored and not explicit requests.

**Comment by jotak** [comment]
I thought it would be nice to have some kind of flagging for mirrored requests, similar to the DI / FI of fault injection. Except that here it would be a requests flag, not a response flag.

**Comment by douglas-reid** [comment]
i'm in favor of leaving this open, as it should be possible to appropriately capture this somehow.

**Comment by douglas-reid** [comment]
Not stale

**Comment by jmazzitelli** [comment]
I am assuming this is still something good to have.

**Comment by douglas-reid** [comment]
Yes. We need to identify an owner to drive design here.
