### ISSUE TITLE
Test failure in postsubmit: Mixer K8s Integration tests

### ISSUE THREAD

**Issue by ozevren** [istio/istio#11557]
https://gubernator.k8s.io/build/istio-prow/logs/istio-integ-k8s-tests/3131#istioioistiotestsintegration2mixer-testcheck_allow

**Comment by irisdingbj** [comment]
Error getting logs from pod/container istio-citadel-d74945c45-499qq/citadel: exit status 1: Error from server (BadRequest): container "citadel" in pod "istio-citadel-d74945c45-499qq" is waiting to start: trying and failing to pull image

Checking the post-submit, almost all the beginning testing failes due to it fails to pull image and deploy istio within 480 seconds.  It succeed in the following test due the relate containter images have been present in previous testing. 

@ozevren Simply increase the DeployTimeout:   480s to a longer value should fix this. In e2e , the timeout is set as :maxDeploymentRolloutTime       = 960 * time.Second

**Comment by ozevren** [comment]
There is a test ordering problem that significantly effects timings. https://github.com/istio/istio/issues/12606 tracks this (there is already a pending PR fixing it). We also have new test framework refactoring that adds stability checks which I ran in the CI systems and it has been quite stable.

I am closing this bug. If we observe new failures after this, we can open new bugs.
