### ISSUE TITLE
Proposal: Switch off Mixer policy enforcement by default in 1.1

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#11736]
We are considering switching off Mixer policy enforcement by default in Istio 1.1

1. Most customers do not use Istio policy, but still pay latency cost of using istio-policy. P99 latency doubles in the test setup.  (6ms -> 12 ms)
2. Even for customers that want to use policy, Istio rbac can be used in most cases. It is evaluated client side, and thus does not suffer from the latency issue.
3. Mixer V2 will evaluate policies at the client, so the inherently extra hop problem goes away in that architecture.
4. If Mixer-policy is down, customer incurs the risk of an outage even though no policy is active. We should not make customers carry the risk of an SPOF unnecessarily.
5. 1.1 supports `policy.istio.io/check: enable` annotation to enable policy checks on a per workload basis.
 
Risks
1. Upgrade from 1.0 to 1.1
  If a customer is using istio policy in production, they will simply have to pass in an extra argument to retain the previous behaviour. 
Mitigation:Make it clear in the release notes that this has changed. Send out notifications on the mailing lists.

2. Demo and Docs
Demo and docs assume that policy is turned on. We will have to update docs.

Other mitigations:
1. Add a post install job to detect if installation uses any Mixer policy rules. 
   a. Check if mixer metrics show any check adapter is dispatched.
   b. Check configuration to see if any non report adapter is deployed.
This still leaves some missed cases where a custom Mixer build is used.

**Comment by mandarjog** [comment]
@theganyo @louiscryan @geeknoid @douglas-reid @rshriram @costinm

**Comment by geeknoid** [comment]
My $0.02

Given that we're trying to ship 1.1 in earnest, instead of having a note somewhere that tells people about the breaking change, I think we should instead publish a note informing them how they can turn policy checks off and get the benefits of increased perf and resiliency to failure.

We will eventually get the benefits of Galley making intelligent decisions about which paths to light up or not based on actual config state which will eliminate the need for manual intervention. But until then, I'd rather not rock the boat wrt the 1.1 release and existing 1.0 deployments being upgraded.

**Comment by theganyo** [comment]
It seems to me that the safer, more consistent, and backward compatible play would be to have it on by default, but allow it to be turned off. It's on in 1.0 and I assume that in Mixer v2, policy would be on by default as the issue goes away... so having it off by default in 1.1 seems both incompatible and inconsistent.

(Ideally, of course, it would be even better if Istio could detect if there is no policy and inform the proxy to elide the call, but I understand that may be very difficult or impossible.)

**Comment by costinm** [comment]
Also: in 1.1 we have ability to enable policy for specific workloads ( Mandar - please add a link to an example).

The proposal is to not make Check calls from all workloads, by default - policy server will still run, but will need to be enabled by user either at workload or by explicit setting.

**Comment by linsun** [comment]
+1 on switch off policy by default.  No one is using policy afaik, and everyone isn't happy that they are paying for that latency cost of using istio-policy even when they don't have any policy enforcement configs deployed.  In fact, that comes as a surprise to everyone, as they don't expect to pay for that latency.

It is a breaking change, but it aligns with what people are expecting of the behavior of the system, especially not many users (if there is any) are using it.

**Comment by linsun** [comment]
This could have improved in 1.1, but last time when I tried (maybe 1.0.x), I don't have any mixer policy deployed but it is still calling to mixer to check if a call is allowed.

**Comment by rshriram** [comment]
Do we have a clear idea of who is using policy in prod in 1.0? It seems to be a very small fraction of people, while the 99% of majority dont use it. If we keep policy on for backward compatibility for this 1% of user base, we are unduly adding the latency overhead to teh rest of the 99% that dont even use RBAC for instance. 

My vote would be to turn it off in 1.1, and make big bold release notes that it is off by default. While it is true that we have enhancements coming in future, the key word here is "future". The user base right now doesn't use it and is still suffering from the additional latency overhead (not to mention, optics wise, we are perceived as having higher latency for out of hte box setup). Telling this 99% to use a custom istio deployment with no policy does not seem useful.

Those who are using it in prod certainly have more expertise than the common folk who end up using istio-demo or istio-demo-auth.yaml. Those who are using Helm based templates will simply have to add an extra flag to enable mixer policy.

**Comment by ssuchter** [comment]
It seems like there are 2 distinct but related questions:
1. Do we want to ever change policy checking to be off-by-default?
2. Do we want to make that change in 1.1?

Addressing just #1:

We know the common use case does not need this check, so it'd be good to cater to that. The main problem is backwards compatibility. I'm personally in favor of turning this off, but I could see multiple ways of doing it:
A. Turn off by default, calling it out in big bold in the release notes
B. Off by default with a post-install checker (the mitigation proposed in the tail of the description) that re-enables.
C. Add a new mode "autodetect" that is the default, that attempts to detect and enable/disable. Allow force-on and force-off modes that are not the default.
D. Turn off by default, but make some kind of runtime detection that checks are attempted but are disabled. Figure out some what to surface this to the operator. (Not sure what mechanism we have for this.)

I'm kind of worried about the post-install checker, because it seems like it is an automated system that sets some config. Then later, we won't know if that config is the operator intent or not. E.g. what if the auto-detector says "I think policy checks should be disabled" so turns them off. Then we rev the software and a new detector thinks they should be enabled. Should it enable them, or should it leave them off because it sees a config that the operator seems to have indicated that they should be off? (Repeat same concern with on/off reversed)

I don't love the "autodetect" magic either, but I could live with it because its only necessary while we have separate policy checking that is so expensive. There certainly seems to be a trend to incorporate policy checks into the Envoy itself (currently with Lua filters) and if that trend continues, maybe its moot. (So we could live with autodetect given that we know there's light at the end of the tunnel.)

WRT timing - as I stated above, I'm personally in favor of some method of turning these off by default. That being said, I'm fairly apprehensive about making this change so late in the 1.1 release process.

**Comment by smawson** [comment]
I am strongly opposed to making breaking changes in software that could negatively impact production users of the project, as a general rule.

The right solution here is to turn off policy checks for envoys that don't need them (and likewise turn off telemetry reports if they aren't needed, and turn off the rbac filter if it isn't needed). We shouldn't even need a global setting, that's just making users do work that we should be doing. If the user has policy for a workload that needs a call to Mixer.Check, we should call Mixer.Check. If they don't have that policy, we shouldn't call it.

This seems like a straightforward feature request for Pilot, and we should get it into 1.2.

For 1.1, just add a note that if you are not using policy you should turn it off for performance, and we're working on a fix in 1.2 to make this automated.

**Comment by rshriram** [comment]
The problem is mixer doesn't have "policy for a workload" kind of setup. The adapters/templates/etc.. dont define workload label selectors or anything that can be gleaned from the config, can they? With RBAC, we already do this. Same goes for authN policies as well. Mixer is the only exception as of now.

**Comment by douglas-reid** [comment]
@rshriram I share your concern that detection of use of policy, especially for a workload, is a challenge -- and is not completely supported by the current config scheme. Perhaps the system _should_ work that way, but we haven't designed it to make that particular task easy.

This change does have the disadvantage of being a silent failure. If your policy enforcement was an action seldom taken, but critical, it would be bad to discover that it stopped working some days/weeks/months after an upgrade. You might notice that `istio-policy` wasn't receiving traffic, but only if you were really paying attention.

There was a proposal somewhere to have `Check` _disabled_ by default for **new** installs and _enabled_ for **upgrades**. If that could be readily achieved, and was done with proper notifications through all the corresponding channels (release notes, mailing-lists, forums, etc.), I think that would get my vote.

**Comment by geeknoid** [comment]
So we have two approaches here:

- Breaking change. We tell users about the breaking change. If a user misses the note and depends on policy checks, they are broken and they don't know it.

- Leave as-is. We tell users about the ability to turn off policy checks to gain additional perf. If the users don't notice the note, life goes on as before. If did do notice the note, they can change things on their timeline and get the benefits.

I'm not clear exactly why we're even discussing this. Istio is a shipped product with backward compat assurances. We must leave things as is.

**Comment by ssuchter** [comment]
I can explain why there is a discussion: I know of at least one company that switched from Istio to Linkerd because they thought Istio's performance was worse. Their measured delta was explainable by policy checks that were unnecessary. I think that having policy checks by on by default (because of their cost) is a bad state and the above situation will keep repeating. Should we keep things forever the way they are?

**Comment by linsun** [comment]
can we do what @douglas-reid suggested and honor this for upgrade but disable it for new install?  I think that is a good meet-in-the-middle method :)

**Comment by geeknoid** [comment]
@ssuchter 1.1 != forever.

In Mixer V2, the overhead will be eliminated. Additionally, Galley will be well established and in a position to control exactly what the data plane is doing, based on what features the user has enabled.

**Comment by ssuchter** [comment]
Do we have a way to achieve honor for upgrade but disable for new install? What if the customer's method of "upgrade" is to uninstall Istio entirely, install the new version, and deposit their same config? How could we detect that?

I think we're having trouble deciding between two evils:
1. We've got a "default" that is penalizing 99% of the users (quoting Shriram here) with performance and SPOF-ish behavior.
2. We need to have backwards compatibility.

I think we need new options, not just to choose between the two.

Here's another option:

I perceive that the below is the worst-case compatibility issue:

A customer is using policy checks and depends on them for security. Without those checks sensitive data will be exposed. We change the default to policy checks off, and they upgrade to that version, and don't realize that they're exposing sensitive data. They completely lose trust in Istio, because exposing sensitive data is even worse than being down.

How about this as a proposal:

We change the default to off, and change the Envoy behavior when policy checking is off. (Or perhaps in the default state - maybe there are 3 states). When in the default state, if an Envoy attempts to do a check, instead of returning "True" (allowing the action that requested the check) or "False", the Envoy crashes. (Even better if we can make more things crash. Best if there is some way to make this situation unignorable and clear what's happening.)

This way the 99% of the users get benefit, and the 1% who are affected by this non-backwards-compatible upgrade either notice the big flag and fix it, or they will notice it during the upgrade.

Happy to entertain more options, though!

**Comment by douglas-reid** [comment]
@mandarjog what happens if we turn the default TTL for check cache entries up to basically infinity (and stripped referenced attributes when no check adapters were used, eliminating noise from APAs)?  Do we have perf impact assessments for essentially infinite caching of OK responses with the minimal set of referenced attributes?

hopefully, we would just pay the one-time cost of `Check` per proxy in the path, and then whatever overhead was associated with that lookup for the lifetime of the proxy.

Right now, we call every minute or 10000 requests, iirc.  But we use `source.uid` and `source.ip` as a key, which I think makes the effective rate less than desired.

**Comment by costinm** [comment]
@douglas-reid interesting idea. My understanding was that checking the cache is also a bit expensive, but it may help a bit on latency side, and maybe a bit on SPOF. 

Regarding upgrade: I want to remind everyone that we have many other changes in default behavior.
We're allocating more CPU - some users may have scheduling problems. CRD install mechanism
has changed - users who don't read the release notes and instructions will likely end up with a broken
install ( Galley is very sensitive to a missing CRD ). Many install options have been 'refactored' and 
cleaned up - and will require reading the new doc. 'discoveryDomain' is now 'clusterDomain' - if you customized it because you don't use cluster.local - you'll be broken.   That's just doing a quick diff - because settings moved around is not easy even to find the differences ( I'm trying to create a list since
we'll need to document them... )

**Comment by mandarjog** [comment]
Checking cache is not very expensive, so I think increasing the TTL and usecount to a high level for demo setup works well. `destination.uid`  is a good static referenced attribute since it is used to lookup config.

For anything other than demo, this will not work as well. We can potentially reduce the usecount and TTL for prod use, but then we are back to where we started.

It is also cleaner and more aligned with istio `a la carte` to disable what you do not use. If we cannot make this breaking change between 1.0 to 1.1, how can we make it from 1.1 to 1.2 ?

**Comment by geeknoid** [comment]
In the 1.2 timeframe, we should be able to make this dynamically selected
by Galley. In the 1.3 timefrsme, we'll start to roll out Mixer V2.

**Comment by ssuchter** [comment]
> Additionally, Galley will be well established and in a position to control exactly what the data plane is doing, based on what features the user has enabled.

Does this mean that we could build a smarter thing into Galley that would disable policy checking in Mixer V1 when it is unnecessary? Will Galley be able to correctly detect this?

**Comment by rshriram** [comment]
fwiw, we have had the option to disable mixer since 1.0 but to @ssuchter 's point, people drop Istio because they dont read the fine print.
At the very least, in all our docs on the main site, we should advertise that people turn mixer off for the standard install. And change the demo.yamls (since its "demo"). This way, we could keep mixer on by default in the helm charts for people who generate the istio.yaml in the usual way. But all our docs, the default istio-demo.yaml [which is absolutely not recommended for production install] can ship with mixer off, so that people choosing istio based on horse race numbers wont be discouraged.

**Comment by kyessenov** [comment]
Here's another implementation proposal to avoid making unnecessary Mixer policy calls.
1. Let pilot call out to mixer with partially filled attributes at regular intervals.
2. Interpret results as trivially true, trivially false, or maybe, where maybe happens if there are referenced attributes that are not in the original partial attribute set.
3. Only insert mixerfilter if the result is maybe.

**Comment by rshriram** [comment]
for every pod?

**Comment by louiscryan** [comment]
Mixer folks - Is there a way to introspect the Mixer job at runtime and
figure out if it has any enabled policy checks, either through a call as
Kuat suggests or via its metrics ?

**Comment by douglas-reid** [comment]
Starting assumption:  `Check` is provided by Istio's Mixer (and not some other workload).

Then, yes, it would be possible to tell at any given time whether or not there are any templates of variety `Check` in Mixer's internal routing table. That info is not currently exposed in a consumable fashion today, but it could be added.

My PoC PR is essentially using that information to create a proxy-lifetime cachable (the only key being `destination.uid`) OK response.  We could also exploit the information in other ways (with more work).

**Comment by kyessenov** [comment]
@rshriram I was hoping we can do that per namespace since O(mixer filter configs) = O(namespaces). Referenced attributes should show if pod ID is necessary to make a policy decision.

**Comment by douglas-reid** [comment]
PoC PR for adding metrics to enable metrics-based detection: https://github.com/istio/istio/pull/11790

**Comment by louiscryan** [comment]
As mentioned in the TOC meeting it sounds like we are already giving users a significant upgrade burden though all the changes to values.yaml that have been made for other reasons (thanks @costinm 
 for taking us through that). These changes already require the user to walk through documentation to understand how the options have changed and to make decisions on how to translate their config from the version being upgraded from.

Given that we're already giving users that burden it seems reasonable to pull this change and other default behavior changes in. If we're going to give users that upgrade burden we can give them some benefits for their hard work (performance, reduced install footprint etc)

@geeknoid 
@smawson 
@rshriram

**Comment by wenchenglu** [comment]
@mandarjog
any update on this issue?

**Comment by mandarjog** [comment]
Fixed by #12114

**Comment by zengyuxing007** [comment]
@mandarjog  where i can found the mixer v2 design document? thanks
