### ISSUE TITLE
Enable Kiali runtimes dashboards

### ISSUE THREAD

**Issue by jotak** [istio/istio#11836]
Kiali is now able to display more than Istio metrics, it can show some dashboards using metrics found in Prometheus (either Istio's Prometheus, or a different one that needs to be configured in Kiali).

In order to do so, we defined a new CRD for dashboards. Kiali can also come with a few default dashboards for some popular frameworks (at the moment: node.js, thorntail and vert.x ; springboot soon to come; and more can be added of course).

If we want this feature enabled by default, we need to update Kiali charts to include the new CRD and/or the available default dashboards.

So, questions are opened:
- Do we want that CRD added by default?
- Do we want the default dashboards installed?

**Comment by jotak** [comment]
cc @jmazzitelli

**Comment by jotak** [comment]
Example of a dashboard:

![vertx metrics](https://i.imgur.com/u1J8pfN.png)

**Comment by esnible** [comment]
Can you point us to some instructions for setting up the dashboard CRDs or a tutorial on how to see the new dashboards?

**Comment by jmazzitelli** [comment]
@esnible Kiali Runtimes Monitoring documentation that talks about setting up the dashboards: https://www.kiali.io/documentation/runtimes-monitoring/

The bottom of that docs page gives some docs on the spec for the dashboard CRs. The dashboard CR yamls that Kiali has currently are found here: https://github.com/kiali/kiali/tree/master/deploy/dashboards

Here is an additional blog with some instructions/examples: https://itnext.io/how-to-view-application-metrics-in-kiali-482bd1733942

**Comment by jotak** [comment]
Also if you want a full working example with runtimes dashboards you can check https://github.com/jotak/bookinfo-runtimes (it's more or less bookinfo rewritten with the current supported runtimes, just don't expect to see all the capabilities of your existing bookinfo, it has been simplified)

**Comment by linsun** [comment]
@jotak can we do this in the kiali chart and enable only when kiali is enabled (e.g. demo profile)?

**Comment by linsun** [comment]
@jmazzitelli would be great if you or someone from Kiali team can step up and help with this.

**Comment by jmazzitelli** [comment]
@linsun I think what I would like to do is see if we can integrate the new Kiali Operator in the kiali helm chart (we just released the Kiali Operator today). The Kiali Operator will install Kiali with these runtime dashboards. So rather than add all the kiali monitoring dashboard yamls and the kiali monitoring dashboard CRD into the existing kiali helm chart, I would like to see if its possible to get the kiali helm chart to simply install the kiali operator and a kiali CR. This should also simplify the kiali helm chart in the istio repo as all the config would go into a single kiali CR that the helm chart would deliver (of course, the helm chart would need to include/install the kiali operator yaml, but that would have less churn I think because the operator's yaml files shouldn't change as much - plus the operator will provide a better install experience).

Hopefully that all made sense. :)

**Comment by linsun** [comment]
That makes sense, should we close this then? :)
