### ISSUE TITLE
Single control plane multiclusters - Cluster-aware: Incoming traffic through the Gateway should only be routed to local endpoints and avoid routing it back to the originating cluster or to a 3rd connected cluster

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/istio#11841]

**Comment by vadimeisenbergibm** [comment]
The proposed implementation:

1. Ingress gateways should route traffic to the local endpoints only
1. Egress gateways should route traffic to the remote endpoints only

Implementation details:

1. Remove `ISTIO_META_ROUTER_MODE sni_dnat` from the egress gateway, since this mode is for internal services and the egress gateway should not route to internal services.
2. In `EndpointsByNetworkFilter()`, return only local endpoints to a sidecar with `ISTIO_META_ROUTER_MODE sni_dnat`
3. In `EndpointsByNetworkFilter()`, return only remote endpoints to a sidecar with `ISTIO_META_REQUESTED_NETWORK_VIEW external`

**Comment by vadimeisenbergibm** [comment]
^ @costinm @rshriram

**Comment by costinm** [comment]
sounds P0. 

I assume this is only about the service-to-service - Gateway should be able to route and load balance normal ingress to any endpoints, while respecting the normal load balancing.

**Comment by rshriram** [comment]
this works properly for the gateway connected clusters. i have no idea about split horizon stuff.. The sni dnat stuff was not meant to be used with anything other than gateway connected clusters.. So, I am not surprised it breaks.

**Comment by vadimeisenbergibm** [comment]
@rshriram Is it OK to add some other metadata, for example a value `ingress` to ISTIO_META_REQUESTED_NETWORK_VIEW? Or another metadata key, e.g.  ISTIO_META_INGRESS `true`:`false`?

**Comment by rshriram** [comment]
how will that help?
this feels like a structural issue with the way split horizon has been implemented.

**Comment by vadimeisenbergibm** [comment]
So in EndpointsByNetworkFilter(), pilot will return only local endpoints to a sidecar with metadata that indicates it is an ingress gateway.

**Comment by linsun** [comment]
@vadimeisenbergibm can you clarify if this is just for split horizon single control plane multiclusters?  I had thought this already worked in gateway multi control plane multiclusters.

+1 on this feature, would prefer to route local cluster unless local service is overloaded or died, as the default behavior for single control plane multiclusters.

**Comment by vadimeisenbergibm** [comment]
@linsun Right, it is for split horizon single control plane multiclusters. This is a rather serious issue: with some probability, the gateways might ping-pong a request between them forever. @elevran and @ymesika discovered it.

**Comment by rshriram** [comment]
this ping ponging issue was known a while ago :). That was one of the reasons for setting up the .global namespace for proper routing. Network names for endpoints are not supposed to carry any meaning. And by default, the network is "" which pulls all cluster local endpoints. So fix the split horizon implementation to add the remote gateway endpoints with a network name instead of adding more semantics to the simpler network name concept.

**Comment by mikebryant** [comment]
We're getting very stuck on this issue. We're trying to get single control plane multicluster working, and what we can see in the endpoints for pilot is both the local (cluster1) ones and also an endpoint for the gateway of cluster2.

We believe this is because we do have a Service/Endpoints object in cluster2, configured statically to point at the cluster1 gateway for the initial bootstrap

Then when it all comes up, the cluster2 pods start having trouble talking to pilot and mixer, because the cluster1 gateway is sending the traffic back down in a loop. (cluster2 gateway actually has a lot greater weight, since it has 3 IPs of an amazon NLB in it)

Does anyone have any suggestions on how to mitigate this?

**Comment by vadimeisenbergibm** [comment]
@mikebryant We are currently in the process of writing integration tests for multi-cluster, and then I will work on fixing this issue, I will not be able to work on it before the KubeCon Europe (20-th of May).

**Comment by fpesce** [comment]
@andraxylia I'm seeing @vadimeisenbergibm said that he can't work on this before KubeCon Europe, we're going to freeze in this interval (May 21st), is this realistic that this issue is going to be addressed in 1.2?

**Comment by duderino** [comment]
I think this is not a regression from 1.1 so therefore not a P0.  Please correct me if I'm wrong

**Comment by linsun** [comment]
Propose to move this to 1.4 since this is a new requirement.

cc @ericvn
