### ISSUE TITLE
helm dep update not working for istio 1.1.0-snapshot6

### ISSUE THREAD

**Issue by zhqworld** [istio/istio#11865]
**Describe the bug**
helm dep update not working for istio 1.1.0-snapshot6

**Expected behavior**
helm dep update should work

**Steps to reproduce the bug**

```
cd istio-1.1.0-snapshot.6/install/kubernetes/helm/istio
helm dep update
Error: no repository definition for @istio.io. Please add them via 'helm repo add'
```

**Version**
`kubectl version`: 1.10.3
`istioctl version`: 1.0.3

**Comment by ostromart** [comment]
Please follow the steps for 1.1: 
https://istio.io/docs/setup/kubernetes/helm-install/#option-2-install-with-helm-and-tiller-via-helm-install
Note that you cannot upgrade from template installed Istio using "helm upgrade", per https://github.com/istio/istio/issues/11868
You have to stick with the same method for both versions (either template or tiller).

**Comment by zhqworld** [comment]
Updated the issue, it is about `helm dep update` failure.

**Comment by ostromart** [comment]
This was a stale doc issue which was fixed in https://github.com/istio/istio.io/pull/3276
If you refresh your docs, they should be up to date now.
You should not run helm dep update anymore, only helm repo add. 
We had a lot of complaints about the extra dep update step, so that's why it was removed.
