### ISSUE TITLE
Allow Citadel to accept configurable DNS

### ISSUE THREAD

**Issue by wattli** [istio/istio#11912]
Currently the DNS support of Citadel is limited, we only support ServiceAccount.Namespace and ServiceAccount.Namespace.svc, in multi-cluster galley, this is not enough, we need Citadel to be more flexible to accept customized DNS

**Comment by wattli** [comment]
It's fixed by: https://github.com/istio/istio/pull/11986

**Comment by costinm** [comment]
Can you explain a bit how it is fixed - custom DNS names were supported in 1.0 as well, and they work - the problem was making sure Galley (which is the only component using DNS names outside cluster) can be configured as part of the install so it has a 2-SAN DNS, one for Gateway (for other namespaces) and one for internal services. 

An integration test would help a lot - but even docs with the steps needed to configure.
