### ISSUE TITLE
Istioctl warns about not being able to exec into Pilot pod

### ISSUE THREAD

**Issue by ozevren** [istio/istio#11947]
https://preliminary.istio.io/help/ops/component-debugging/

ozben@recyclebin:~/istio/istio-1.1.0-rc.0/bin$ ./istioctl proxy-status
Warning! error execing into istio-pilot-69fb5878b-27stb/istio-system discovery container: gc 1 @0.015s 8%: 0.008+2.7+1.4 ms clock, 0.017+0.21/0.43/1.5+2.8 ms cpu, 4->4->2 MB, 5 MB goal, 2 P
gc 2 @0.026s 12%: 0.012+2.8+1.6 ms clock, 0.025+0.14/0.63/2.0+3.3 ms cpu, 4->4->3 MB, 5 MB goal, 2 P

NAME                                                   CDS        LDS        EDS               RDS          PILOT                           VERSION
istio-egressgateway-ffbb468b6-5cqks.istio-system       SYNCED     SYNCED     SYNCED (100%)     NOT SENT     istio-pilot-69fb5878b-27stb     1.1.0
istio-ingressgateway-585c5f7f89-dvk2w.istio-system     SYNCED     SYNCED     SYNCED (100%)     NOT SENT     istio-pilot-69fb5878b-27stb     1.1.0

**Comment by ozevren** [comment]
Tested on both linux and mac.

**Comment by howardjohn** [comment]
I think the problem is pilot is installed with `pilot.env.GODEBUG=gctrace=2` (or similar), so the gc stats get logged to stderr. When we exec into the pod, we capture this as a potential error and print out this message.

Possible solution is to change the command to `kubectl exec -n istio-system istio-pilot-67d9dd7d4d-9f7jq -- sh -c 'GODEBUG= pilot-discovery request GET /debug/syncz'`.

It seems to work but doesn't seem like the best solution. Any other ideas @ozevren? If not I can make the change.

**Comment by ozevren** [comment]
Sounds reasonable to me.
/cc @liamawhite  (original author), @ayj

**Comment by ayj** [comment]
`pilot-discovery request` makes an HTTP request to localhost:15014. We can't use `curl` for this purpose because it doesn't exist in the scratch base image. Alternatively, we could use port-forwarding (see k8s.io/client-go/tools/portforward/portforward.go:114) and make the HTTP request directly from istioctl.

**Comment by ozevren** [comment]
It looks like changing env, so that GODEBUG= is not specified could be a cheaper option?

**Comment by ayj** [comment]
`GODEBUG=` is a quicker fix. `port-forward` instead of `exec` would be a longer term change to eliminate some complexity.

**Comment by liamawhite** [comment]
Are you suggesting we port-forward directly from istioctl to Pilot? IIRC, this won't work if control plane has mTLS enabled unless you get your CLI an identity which would be a PITA.

**Comment by ayj** [comment]
Yes. Last I checked, port-forwarding uses socat to bridge between the node and pod network namespaces. This means traffic originates from "localhost" and thus bypasses the proxy via the current iptables rules. See https://discuss.istio.io/t/how-does-kubectl-port-forward-bypass-envoy-mtls-enforcement/731/2. FWIW, `pilot-discovery request` also relies on the iptables to bypass the proxy.

**Comment by liamawhite** [comment]
Ah, this is interesting was unaware of this when I wrote the original code. `request` was intentionally written to come from localhost 🙂.
