### ISSUE TITLE
Pods created with istio injection are not accessible if no service is created

### ISSUE THREAD

**Issue by iandyh** [istio/istio#11967]
Looking at the new changes: https://github.com/istio/istio/blob/b8e30e07ec7b36cf1ba1b445b78c81fdf0d417b9/pilot/cmd/pilot-agent/status/ready/probe.go#L42

sidecar proxy will mark itself as not ready if no service is created(no listeners being pushed from the pilot). This somehow makes senses if you think service is a switch for network layer.

This also breaks liveness/readiness check for the main container as it will return 404. 

@hzxuzhonghu

**Comment by hzxuzhonghu** [comment]
@iandyh I am not sure if you have noticed the pr by @incfly ,which rewrite the liveness/readiness probe. Can help resolve the probe failure.  But It does not help to access directly from outside.

@rshriram @costinm Any commments?

**Comment by hzxuzhonghu** [comment]
https://github.com/istio/istio/pull/10470/

**Comment by hzxuzhonghu** [comment]
For kubernetes  pod, I think we can get the container port and generate a listener for it.     Just as it has a associated service with ip = podIP and port=conatinerPort.  We should also assume the protocol is TCP

**Comment by iandyh** [comment]
@hzxuzhonghu Yes. I fully agree. Sidecar proxy should not break any kubernetes semantics in this case. 

I saw the probe fixes is being merged to 1.1. Do you think fixes to this issue will be merged into 1.1 as well? Or we have to wait next releases?

**Comment by hzxuzhonghu** [comment]
Since 1.1 will be released very soon, I think we have to wait until 1.2.

**Comment by rshriram** [comment]
or 1.1.1

**Comment by incfly** [comment]
If I understand the problem correctly,

- Injector is correct, passing application port into the sidecar cmd flag as `applicationPorts`
- No service definition however, No xDS.
- Prober doesn't report ready.

So this has nothing to do with health check rewrite with mTLS, correct?

Regarding solution,

```
I think we can get the container port and generate a listener for it. Just as it has a associated service with ip = podIP and port=conatinerPort. We should also assume the protocol is TCP
```

You mean do this at Pilot level such that we always have a default LDS so this case will be covered? 

My thoughts of this problem,
- Can Pilot generate a bit to tell Sidecar, "hey sidecar, you should consider yourself ready in terms of xDS config"
- Pilot agent only look at this bit, instead of reading `applicationPorts` and compare that to the number of xDS received? (Maybe I miss something, but I don't understand why we pass `containerPort` from app to sidecar originally? Shouldn't it be xDS per service not per deployment?)

Thoughts? @hzxuzhonghu @rshriram @costinm

**Comment by mandarjog** [comment]
if the crux of the matter is that our readiness is tied to listeners, and these pods don't have listeners..., isn't it better to not have readiness for these pods at all? If they don't expose a service what is readiness doing anyway.

If there is a way to disable highjacking readiness for this deployment, lets us it. Otherwise we can add a new annotation that exempts it from readiness checks.

**Comment by incfly** [comment]
> if the crux of the matter is that our readiness is tied to listeners, and these pods don't have listeners..., isn't it better to not have readiness for these pods at all?

Do you mean checking service existing on a particular deployment during injecting time?

If so, I don't think fixing on injector side will work, given deployment & injector is once and static. Service definition are dynamic by its nature. Only pilot can capture that anatomically.

**Comment by iandyh** [comment]
> if the crux of the matter is that our readiness is tied to listeners, and these pods don't have listeners..., isn't it better to not have readiness for these pods at all? If they don't expose a service what is readiness doing anyway.
> 
> If there is a way to disable highjacking readiness for this deployment, lets us it. Otherwise we can add a new annotation that exempts it from readiness checks.

Not sure if I understand the reply correctly. Firstly, HTTP liveness will also fail due to sidecar injects the traffic, not just readiness check. Secondly, those pods do listen on certain ports but those ports become inaccessible due to no Envoy side car proxy listeners being pushed from the pilot.

**Comment by mandarjog** [comment]
If pods are listening on ports then they are implementing a service. In which case it is ok to attach a service to these pods, right?

**Comment by iandyh** [comment]
Some applications will just use this port as a liveness check, which will become pointless due to current design. `Deployment` should be decoupled from `Service`.
