### ISSUE TITLE
Cluster-Aware Service Routing: Hostnames not supported

### ISSUE THREAD

**Issue by jkbschmid** [istio/istio#12017]
**Describe the bug**
[Step 2.1 ](https://preliminary.istio.io/docs/examples/multicluster/split-horizon-eds/#setup-cluster-2) of the example 'Cluster-Aware Service Routing' fails, if a hostname instead of an ip is provided. This is the case, although the documentation explicitly states that 'you can set it to a DNS name instead, if you have one' (see previous step).
```
Error from server (Invalid): error when creating "istio-remote-auth.yaml": Endpoints "istio-pilot" is invalid: [subsets[0].addresses[0].ip: Invalid value: "xxxxx.eu-central-1.elb.amazonaws.com": must be a valid IP address, (e.g. 10.9.8.7), subsets[0].addresses[0].ip: Invalid value: "xxxxx.eu-central-1.elb.amazonaws.com": must be a valid IP address]
```

**Expected behavior**
The templated istio-remote-auth.yaml is created.

**Steps to reproduce the bug**
Set LOCAL_GW_ADDR to an arbitrary hostname and execute [step 2.2](https://preliminary.istio.io/docs/examples/multicluster/split-horizon-eds/#setup-cluster-2) (helm template ..).

**Version**
K8s:
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-04T04:49:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:00:57Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

Istio 1.1.0-rc.0

**Installation**
Happens before installation.

**Environment**
AWS. This makes it necessary to use a hostname, as AWS does not provide a fix IP under '.items[0].status.loadBalancer.ingress[0].ip', but instead only a hostname under '.items[0].status.loadBalancer.ingress[0].hostname'.

**Comment by jkbschmid** [comment]
This issue was discovered during community testing, I'd like to set the milestone 1.1, but I am unable to.

**Comment by linsun** [comment]
seems this can be fixed by updating the doc to incorporate the hostname case.  cc @ymesika for thoughts.

**Comment by ymesika** [comment]
The limitation of having an IP for the gateway is coming from Envoy because the idea behind _Split Horizon EDS_ (used in Cluster-Aware) is to return remote gateway as an endpoint in the EDS results. Because Envoy accepts IP addresses within each endpoint you can't put at the moment hostname.

**But** we definitely want to support it and find a way to do the resolution on the fly. Thing is that we don't want to do it for each EDS request because it's heavy and time consuming. Anyway, just thoughts and as mentioned, we will find a way to support it in the following releases.
