### ISSUE TITLE
TestRotateMaxBackups is flaky

### ISSUE THREAD

**Issue by ozevren** [istio/istio#12065]
https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/11998/istio-unit-tests/21455

```
=== RUN   TestRotateMaxBackups
--- FAIL: TestRotateMaxBackups (0.84s)
	config_test.go:263: Expecting at most 2 backup logs, got 3
=== RUN   TestGlogV
--- PASS: TestGlogV (0.00s)
```

**Comment by utka** [comment]
I found https://github.com/istio/istio/pull/9551 where you trying to fix the same issue, the flake is still happening, can you look into that?

**Comment by yangminzhu** [comment]
The test is moved to https://github.com/istio/pkg/blob/master/log/config_test.go and seems passing successfully: https://circleci.com/gh/istio/pkg/tree/master 

@fpesce 
can we close this now?

**Comment by ozevren** [comment]
@geeknoid It looks like some of the new repos are in CircleCI plan. Should we consider moving them to Prow?

With Prow + TestGrid (and your bots) it should be easier to visualize the trends. As things stand, it is not easy to see if the test is failing or not.

Personally, I am ok with closing this bug and waiting it reappear in the new repo. My only concern is, we don't have a reliable detection mechanism at this point.

**Comment by yangminzhu** [comment]
@ozevren could the test failed in the istio repo due to some resource issue in CircleCI? It never fails in the new repo since added about 1 month ago.

**Comment by ozevren** [comment]
I am not familiar with the test, but if that is the case, then it points to a problem in the test itself then.

**Comment by geeknoid** [comment]
This is likely still a problem, it's just less likely. Consider this PR that tried to fix it by adding a delay:

https://github.com/istio/pkg/commit/a1b70c634b1701b2837ec607d3c683be41dc440f

We need to implement a more deterministic approach to the test rather than waiting. I didn't realize this bug was here. Since this is code I wrote, I'll take over the bug and fix this.

As for the overall situation, yes, we need to move all this stuff to prow so we get consistent reporting.
