### ISSUE TITLE
Make improvement for ingress gateway controller + Cert-Manager

### ISSUE THREAD

**Issue by JimmyCYJ** [istio/istio#12132]
**Describe the feature request**
Istio release-1.1 is going to support dynamic credential at ingress gateway controller using service discovery service (SDS). With SDS and a specified credentialName, Customer could configure a TLS ingress gateway controller or mutual TLS ingress gateway controller. User guide is currently under review.

To configure a mutual TLS ingress gateway controller, customer needs to create a secret via 
```
kubectl create -n istio-system secret generic httpbin-credential --from-file=key=httpbin.example.com/3_application/private/httpbin.example.com.key.pem --from-file=cert=httpbin.example.com/3_application/certs/httpbin.example.com.cert.pem --from-file=cacert=httpbin.example.com/2_intermediate/certs/ca-chain.cert.pem
```

However Cert-Manager only creates TLS secrets, which do not have "cacert" field to hold CA cert. To accommodate CA cert generation part while using Cert-Manager for auto secrets creation, @thomschke proposes a solution [comment](https://github.com/istio/istio/pull/11496#issuecomment-467339267). That requires ingress gateway agent to accept two secret: istio-ingressgateway-certs with tls.key and tls.crt, and istio-ingressgateway-certs-cacert with cacert. We could make change to ingress gateway agent as a work around. 

An ideal change would be supporting Cert-Manager to create secrets that have CA cert. Because in the long term, we would like to let ingress gateway agent talk directly to Cert-Manager or let's encrypt to fetch key, server cert and CA cert. All ideas are welcomed.

**Comment by munnerz** [comment]
> An ideal change would be supporting Cert-Manager to create secrets that have CA cert.

FWIW, cert-manager v0.6 & v0.7 *do* include the CA bundle in the generated Secret resources. This will be stored with a key named `ca.crt` in the Secret.

This is **not** supported when using the ACME issuer however.

**Comment by JimmyCYJ** [comment]
Thanks @munnerz, are there any examples that support ca.crt? I would like to run an experiment with cert-manager and Istio.

**Comment by venezia** [comment]
@JimmyCYJ @munnerz @prune998 

I could be wrong, but here is my understanding:

* Istio 1.1 comes with SDS which, among other things, allows for [dynamic reloading of certificates](https://istio.io/docs/tasks/traffic-management/secure-ingress/sds/#configure-a-tls-ingress-gateway-using-sds), which would alleviate one of the TODOs in [certmerge operator](https://github.com/prune998/certmerge-operator#todo)
* Istio ingress certificates have a somewhat inverse relationship than ingress-nginx:
  * Ingress-nginx watch tls secrets from all namespaces (obviously not the best security) to match ingress records with their secrets.  Essentially a user creates an ingress record in namespace X, cert manager can create a matching certificate secret in namespace X, even if the ingress controller may be running in namespace Y
  * In istio with SDS, certificates must be secrets present in the namespace that the ingress gateway is actually running (essentially the equivalent of namespace Y in the previous bullet point) and _not_ the namespace that a `Gateway` record is held in, that actually references said secret's name
* Some people view ingress as a "cluster service"
  * Istio allows for any `Gateway` to use any ingress gateway
  * Often many examples for ingress-nginx suggest one ingress controller could be shared by multiple users of the same cluster
* But this is somewhat incomplete
  * TCP Services can't typically be handled through SNI
  * ingress-nginx requires a single config map for the ingress controller to map TCP services to specific services (so not "self service" - a cluster administrator would have to define this routing for any users, catching conflicts as well)
* Istio has a somewhat haphazard relationship with namespaces (some Custom Resources are namespaced but are global in effect, see #9275 )

I'm mentioning ingress-nginx because I believe it is probably the ingress solution most people are familiar with (beyond a cloud provider specific solution)

I don't think I can change how istio handles some of this stuff, as I'm sure some of these decisions were made intentionally, especially considering istio is not kubernetes-specific.  But I would argue some of it seems a little inconsistent and probably frustrating to new users who are familiar with kubernetes, ingress-nginx, and want to grow into istio as their needs grow.

I think many have read [blog articles](https://medium.com/@prune998/istio-1-0-2-envoy-cert-manager-lets-encrypt-for-tls-certificate-merge-7a774bff66c2) and even [an operator created out of frustration](https://github.com/prune998/certmerge-operator) mitigate some of the certificate user experience issues.

I do think that anyone considering using istio on top of Kubernetes is probably also considering complimentary projects (external-dns, cert-manager) and that Istio should try to bridge these gaps.  There's a lot to learn about istio, a lot of new concepts for people and to add "learning how to kludge something together to have interoperability with these popular projects" makes it harder to sell istio as an upgrade to ingress-nginx to anyone arguing such to their group.

I understand that production environments may not leverage cert manager (or Let's Encrypt) but that doesn't mean that we cannot offer a better user experience for those that intend to do so

I want to try to make istio easy to show off to others, complete with integration with cert-manager (and more specifically, Let's encrypt)
Here's what I would propose in the near term:
* Be clearer to the user that ingress gateways names are cluster-global in scope
* Be clearer that `Gateways` created in one namespace with SDS are reference secret names in probably a different namespace.  While [the task](https://istio.io/docs/tasks/traffic-management/secure-ingress/sds/#configure-a-tls-ingress-gateway-using-sds) shows the secret being in `istio-system` namespace and the `Gateway` and `VirtualService` are probably in the `default` namespace (no namespace is provided for those calls, so it really could have been any namespace, depending on the kubeconfig) and I'm quite sure many people gloss over those details
* Update `certmerge-operator` to leverage SDS
* Employ a pattern of `<namespace>-<name>` for certificate secret names in the ingress gateway's namespace to avoid collisions between two namespaces both creating a certificate named `foo`

So here's what I would like longer term:
* A better guideline of how multitenant istio looks and works, complete with examples
  * Perhaps like with kubernetes storage classes, there is a "default" istio ingress gateway (and possibly a default ingress gateway namespace)
  * Allow cluster administration to setup cluster-wide ingress controllers that can be used without a namespace declaration
  * Allow users of a cluster to possibly deploy ingress gateways of their own, which would be scoped out of other users
* Adopt certmerge-operator as part of standard istio interoperability with the kubernetes community tools

Thoughts?  Is my understanding of all of this incomplete?  Multi tenant Kubernetes is still somewhat problematic, but I think trying to ensure things work with multi tenant in mind is a good goal.

Thanks

**Comment by prune998** [comment]
Hi @venezia 
I'm the one who wrote the blog and the `certmerge-operator` out of frustration 😃 
Here are few comments : 

- `certmerge-operator` is just filling a void. It suppose `Cert-Manager` does add specific `labels` on generated secret, which it doesn't as the PR was refused (to preserve API...). This operator is not supposed to stay around once Istio have a better management of certificates (with/without cert-manager)
- different gateways usually means different public IPs, which can be good for some, not for others. 
   Envoy, Nginx, haproxy... can handle a lot of connexions/virtualhosts/gateways (in the Istio CRD way) by themselves. One should not have to deploy it's own gateway `pod` to handle the `services` in it's namespace (even if still possible).
- Istio provides (or will provide) a way to give the SSL certificates to the Gateway by using `Citadel` and `SDS`. It definitely is the right way to go. Sounds it's not yet ready (reading the `credentialName` description) yet. Once done, this features should solve almost every issue we may have, right ?

**Comment by venezia** [comment]
@prune998 

>     * different gateways usually means different public IPs, which can be good for some, not for others.
>       Envoy, Nginx, haproxy... can handle a lot of connexions/virtualhosts/gateways (in the Istio CRD way) by themselves. One should not have to deploy it's own gateway `pod` to handle the `services` in it's namespace (even if still possible).

Sure, but there are situations, specifically for TCP services, where this will not work.  Suppose there are two gitlab installations on a cluster and both want to have git over ssh enabled at port 22.  Similarly you seemingly cannot have one Gateway using one port (say 80) as http1 and another gateway using the same port as http2 using the same ingress gateway.  The point largely was while nginx-ingress and istio's default ingress gateway can accommodate multi tenant needs of sharing http/https traffic, there are situations where this will not work.

>     * Istio provides (or will provide) a way to give the SSL certificates to the Gateway by using `Citadel` and `SDS`. It definitely is the right way to go. see [secure-ingress/sds](https://istio.io/docs/tasks/traffic-management/secure-ingress/sds/) This features should solve almost every issue we may have, right ?

My understanding is no, it will not, at least not without some security concerns.  If you look at [this task](https://istio.io/docs/tasks/traffic-management/secure-ingress/sds/#configure-a-tls-ingress-gateway-using-sds) you will see the following workflow:
* Create a secret/secrets in `istio-system` namespace containing a certificate/certificates
  * `httpbin-credential` and `helloworld-credential`
* Reference these secrets in a `Gateway` record located in the (presumably) `default` namespace

So while it is possible that you could create a `Certificate` object in `istio-system`, this would mean that every user of the cluster would have to be able to create (and I assume delete, modify, get) `Certificate` objects in `istio-system` which might not be desirable.  Furthermore it is a little clunky that the `Gateway` record lives in one namespace but is reference a secret that does not exist in that namespace but rather another.  The only way you know where the secret is supposed to exist is to consult what ingress gateway the `Gateway` is attaching to and to find out what namespace _that_ deployment is living in.  

Perhaps I'm coming in with a nginx-ingress-centric view where the Ingress record (arguably analogous to `Gateway` + `VirtualService` resources) lives in the same namespace where the TLS secret they are referencing lives in.  Either way, I think the user experience a little clunky here.

**Comment by nitishm** [comment]
> Thanks @munnerz, are there any examples that support ca.crt? I would like to run an experiment with cert-manager and Istio.

@JimmyCYJ did you ever get a chance to try this ? I gave it go and I don't see the <credential name>-cacert lot message in the ingress-sds logs, which leads to mTLS failures for me. Wondering if anyone knows a work around to make mTLS work with cert-manager.

**Comment by JimmyCYJ** [comment]
There is a user guide for ingress-sds + cert-manager at https://istio.io/docs/examples/advanced-gateways/ingress-certmgr/

There is a blog about using cert-manager with ingress gateway. SDS is not enabled in that case, but the guide is also helpful. https://istio.io/blog/2019/custom-ingress-gateway/

**Comment by Timoses** [comment]
> There is a user guide for ingress-sds + cert-manager at https://istio.io/docs/examples/advanced-gateways/ingress-certmgr/
> 
> There is a blog about using cert-manager with ingress gateway. SDS is not enabled in that case, but the guide is also helpful. https://istio.io/blog/2019/custom-ingress-gateway/
> 
> There is a PR #13339 that helps to make it easier to add cacert when cert-manager is deployed. And it is pending review.

This unfortunately does not help in a multitenant scenario where users of one namespace should be able to define their own secured ingress (with certificates).

It would be great if it were possible to customize an ingress-gateway in such a way that it accepts Secrets from other namespaces.
Of course, this poses a security risk. However, there may be scenarios where exactly this is required (such as an internal cluster where the only users are developers).
For more secure access another ingress-gateway could be used.


I don't think the solution would be to promote every user of a namespace to run their own istio-gateway just to allow for namespaced Certificates to be used by that gateway.

**Comment by JimmyCYJ** [comment]
https://github.com/istio/istio/pull/15496
