### ISSUE TITLE
cluster.local vs. mesh.local

### ISSUE THREAD

**Issue by geeknoid** [istio/istio#12138]
At the moment, we use 'cluster.local' to identity resources that are inherently mesh-local. This is confusing for customers, and will likely lead to some conflicts in cases where there actually is a distinction between cluster-local and mesh-local and the user wants both things at once.

We should inventory all uses of cluster.local and assess whether they should be migrated to mesh.close and how.

@smawson @wenchenglu @ozevren

**Comment by loewenstein** [comment]
@geeknoid Sounds good in principle. Is DNS configuration (either CoreDNS or KubeDNS) a mandatory part of Istio already? Otherwise, how would we resolve *.mesh.local URLs?

**Comment by esnible** [comment]
@loewenstein There is some new documentation at https://preliminary.istio.io/docs/setup/kubernetes/multicluster-install/gateways/

@geeknoid Kubernetes has a limit of 6 DNS search paths on pods, which is cannot be fixed because Linux libc also has a limit of 6.
https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-config
https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/#known-issues

Kubernetes always adds `search <namespace>.svc.cluster.local svc.cluster.local cluster.local`.  Multicluster adds 1 or 2 .global.  Some cloud providers add a few more for local services and it is already causing problems when we configure these users for multicluster.  We don't dare add more.

**Comment by esnible** [comment]
Removing myself because I have no idea how to solve it.

To inventory uses of `cluster.local` in did `find . -name "*.go" -not -name "*_test.go" -not -name "*_mock.go" -not -path "*test*" | xargs grep "^[^/]*cluster.local"` which found 25 occurrences of "cluster.local" that are not comments, tests, or mocks.  I am not sure what do do with them.

**Comment by howardjohn** [comment]
This doesn't seem feasible based on Ed's comments, do we have any plans to do this?

**Comment by ayj** [comment]
cc @liminw, can you help clarify the current thinking on suffixes w.r.t policy and trust?

**Comment by ayj** [comment]
`cluster.local` is the local trust domain alias. Users should this when writing policy. See https://docs.google.com/document/d/1ncrENtF6PBVZVjhYePbvZ6F1obbNApKJh5mUDRvwHMw.
