### ISSUE TITLE
DestinationRules don't follow Sidecar scope isolation

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#12198]
**Describe the bug**
Apply config here - https://github.com/istio/tools/pull/75

We have a Sidecar exposing only `istio-system/*` and `withsidecar/*`. However, the reviews DestinationRule from the `default` namespace is used.

**Expected behavior**
DestinationRules should respect the Sidecar scope. In this case, no DestinationRule should be used for the reviews service, unless we add it to the Sidecar scoping.

**Steps to reproduce the bug**
See config above

**Version**
1.1 rc1

**Comment by duderino** [comment]
Note that version number was most likely 1.1rc1.  rc2 is not out yet

**Comment by howardjohn** [comment]
Hopefully this isn't present in rc2 as well then

**Comment by rshriram** [comment]
So this is behaving as expected.. 
we search for the most specific PUBLIC dest rule for reviews service..
 since there is no dest rule in withsidecar namespace, we look elsewhere.
 we find reviews.withsidecar.svc.cluster.local in the default namespace and its a PUBLIC rule. So it gets used..

You can hide the rule in default namespae by declaring the exportTo field with value `.` . Or, you can define the global config root namespace in helm charts. When you do that, we only check calling proxy's namespace, the service's namespace (both of which are withSidecar), and finally in config root namespace (e.g., istio-config).

**Comment by howardjohn** [comment]
My understanding was it shouldn't be able to pick up the rule, because we want to be able to have complete isolation. Someone on some other team, etc working in another namespace shouldn't be able to impact another's if they are using the Sidecar resource the and not importing from this namespace.

@rshriram offline:
> you have to set the global `defaultDestinationRuleExportTo` to ‘.’
> if you do that, then all dest rules become namespace local only

/cc @costinm you originally brought up this issue, what do you think?

**Comment by costinm** [comment]
Once again, export means it can be used, not that it forces use of a rule. 

Default exportTo should remain public, it is not relevant to this discussion ( except that if a rule has explicit exportTo that doesn't include a namespace, it will not be used ).

If a namespace has an explicit 'egress' section in the Sidecar, and it is not */* - than only the namespaces listed in the egress can be used, everything else is isolated. No matter what exportTo they use - the user controls what configs to import, not the exporter.

**Comment by costinm** [comment]
To be clear: my concern and the P0 are about respecting the "egress" semantics in Sidecar, if it is present. 

Separate bug/priority for the case Sidecar is not present, or it imports */*.

But in all cases, exportTo will be respected - but won't override the import.

**Comment by frankbu** [comment]
Maybe I'm missing something, but the problem here doesn't appear to be Sidecar import, but rather the default DestinationRule resolution algorithm. A Sidecar's egress section only imports Services, not DestinationRules. Corresponding DestinationRules are imported implicitly along with the services according to the algorithm: 1) proxy's namespace, 2) service's namespace, 3) any-namespace. To take unrelated namespaces out of the lookup path, Istio needs to be configured with a global config namespace, as @rshriram  mentioned above. Then the lookup path will be: 1) proxy's namespace, 2) service's namespace, 3) config root namespace (e.g., istio-config). That would solve this issue right?

Why is that not the default DestinationRule lookup algorithm in 1.1? Backwards compatibility? If so we should really document this and recommend a global config namespace be set.

**Comment by duderino** [comment]
@howardjohn I think you verified @rshriram's PR.  Is any work left here?

**Comment by howardjohn** [comment]
Nope, should be good now.
