### ISSUE TITLE
telemetry-gateway chart is installed if default ingress gateway is disabled 

### ISSUE THREAD

**Issue by ashutoshgngwr** [istio/istio#12200]
**Describe the bug**
I am not sure if this is Istio's expected behaviour but `telemetry-gateway` sub-chart is installed after disabling default ingress gateway in chart values. Although this is doesn't have any visible effects, I think it shouldn't be installed if default ingress gateway is disabled.

**Expected behavior**
`telemetry-gateway` sub-chart should not be installed if default ingress gateway is disabled.

**Steps to reproduce the bug**
`helm install install/kubernetes/helm/istio --set gateways.enabled=false --name istio --namespace istio-system`

**Version**
Kubernetes: 1.11
Istio: 1.0.6

**Installation**
`helm install install/kubernetes/helm/istio --set gateways.enabled=false --name istio --namespace istio-system`

**Environment**
Minikube v0.34.1

**Cluster state**
_N/A_

**Comment by douglas-reid** [comment]
It is possible to use the 1.0.6 `telemetry-gateway` without coupling it to the ingress gateway. In that case, it would be a purely internal proxy for the telemetry services (in your case, prometheus).  The configuration is harmless, as you point out, if you do not intend to use it.

That being said, `telemetry-gateway` was removed in 1.1, in favor of individual gateways for each telemetry service, iirc. 

I'm going to close this, as this was intentional and is unlikely to be fixed in a `1.0.X` release.
