### ISSUE TITLE
upgrade fails when gateways for addons are enabled

### ISSUE THREAD

**Issue by sdake** [istio/istio#12286]
**Describe the bug**
When upgrades are enabled for addons, upgrade fails.

**Expected behavior**
Upgrade should not fail.

**Steps to reproduce the bug**
```sdake@beast-01:~$ more helm-deploy.sh 
helm repo add istio.io "https://gcsweb.istio.io/gcs/istio-prerelease/daily-build/release-1.1-latest-dail
y/charts/"
sleep 1
sleep 10
kubectl delete -f $HOME/istio-1.0.6/install/kubernetes/helm/istio/templates/crds.yaml
helm install $HOME/istio-1.0.6/install/kubernetes/helm/istio --name istio --namespace istio-system --set
 tracing.enabled=true --set grafana.enabled=true
sleep 60
helm install istio.io/istio-init --name istio-init --namespace istio-system
helm upgrade istio istio.io/istio --namespace istio-system --timeout=600 --set global.tag=sdake --set gl
obal.hub=docker.io/sdake --set tracing.enabled=true --set grafana.enabled=true --set tracing.enabled=tru
e --set prometheus.enabled=true --set tracing.gateway.enabled=true --set grafana.gateway.enabled=true --
set tracing.gateway.enabled=true --set prometheus.gateway.enabled=true
```

**Version**
release-1.1 commit f9683ae0def09e5660246c95445ce242f2d20c9b

**Installation**
see reproducer

**Environment**
Istio release 1.1 latest tip, kubernetes 1.13.14, metallb 0.7.3
**Cluster state**
```
Error: UPGRADE FAILED: failed to create resource: admission webhook "pilot.validation.istio.io" denied the request: configuration is invalid: domain name "istio-system/istio-grafana-gateway" invalid (label "istio-system/istio-grafana-gateway" invalid)
```

**Comment by sdake** [comment]
@morvencao if you can take a look at this, it would be highly appreciated.  @gyliu513 ^^

**Comment by morvencao** [comment]
@rshriram 
Gateway `ns/name` syntax was introduced into Istio 1.1. During helm upgrade for Istio 1.0.x to Istio 1.1, the new galley instance hasn't started when the virtualservice with `ns/name` syntax are ready to validating server. So the old galley instance take the responsibility and return `validate failed` results.

In order to skip the issue, I suggest to remove the `namespace/` prefix and keep the old syntax. From the gateway definition, it should be working since the gateway and virtualservice are defined in the same namespace. 

If you think it's OK, let' merge this https://github.com/istio/istio/pull/12288

**Comment by rshriram** [comment]
ack.. thanks for the fix

**Comment by linsun** [comment]
thank you @morvencao for fixing this!!
