### ISSUE TITLE
Authorization with Open Policy Agent

### ISSUE THREAD

**Issue by spikecurtis** [istio/istio#1235]
Allows authorization policy for Istio-enabled services to be specified using Open Policy Agent policies written in Rego.

[Design Doc](https://docs.google.com/document/d/1U2XFmah7tYdmC5lWkk3D43VMAAQ0xkBatKmohf90ICA/edit)

**Comment by jasonmacdonald** [comment]
Questions, is the desire to design policies around containers and infrastructure, or can it also be used as a Authorization mechanism for services to evaluate requests against an external policy?

The reason I ask (_and I apologize if I'm hijacking this ticket, just not sure if this is what this might address_), is I'm trying to solve service policy authorization that doesn't require every service calling out to a central AuthZ service. I'd love to find a way to employ an Enovy (side-proxy) style approach to AuthZ, where containers are only asking the proxy, and the proxies are distributing the required policies (and check logic) between each other, reducing the single point of failure and limiting cross network chatter to only when policies update. So far I've found nothing like this, and there's very limited information around regarding AuthZ in MSA.

**Comment by tsandall** [comment]
@jasonmacdonald this solution addresses API authorization for services deployed on top of Istio. It's intended to be used as means of enforcing authorization policies over requests sent to services in the mesh. However, the current solution is designed or Istio's Mixer component which is logically centralized (for now.)

That being said, the [Open Policy Agent (OPA)](https://github.com/open-policy-agent/opa) is designed to be used as a library, sidecar, or host-level daemon like you described. OPA can run beside your service so that policy checks do not require a network hop (and so they're not subject to network partitions and share fate with your service.) This is probably outside the scope of this ticket so please reach out to me if you're interested in chatting further.

**Comment by sirajmansour** [comment]
Should the OPA adapter expose the OPA agent REST API to simplify pushing policy and data updates without having to push those through CRD deployments ? Our use case is to handle user fine grained authorization through OPA and having that at the proxy level offers the best flexibility, but because data related to users and user permissions changes frequently and could be quite large / expensive to regenerate, pushing updates without the OPA REST API is going to be cumbersome and expensive.

**Comment by tsandall** [comment]
I can't speak authoritatively for the Mixer team but I suspect they will not want to see Mixer adapters listening for incoming connections and/or maintaining state.

Currently the OPA adapter only has access to the *policy* that's contained in the adapter configuration. We should investigate whether it's possible to load data from additional CRDs into adapters (assuming that approach will scale well enough.)

@spikecurtis @liminw is this something we should discuss in the security SIG or would it be better suited for another group?

**Comment by sirajmansour** [comment]
It is definitely not the usual idea of the mixer adapter i have to say. Maybe calling an external opa sidecar/deployment then ?

**Comment by mandarjog** [comment]
opa adapter loading directly from CRDs was part of the plan, so that is always possible.
An external opa process that is watching CRDs is also equivalent. In both cases it will not change the configuration surface and user experience.

The current implementation choice was for expediency.

**Comment by liminw** [comment]
@tsandall As Mandar said, OPA adapter loading from CRD is always the plan. Current implementation is just the first step to get it out. You can bring this topic up in the security SIG (just enter your topic in the agenda).

**Comment by ultrasaurus** [comment]
should this issue be closed and more specific issues be opened?  It looks like the adapter is already merged and available here: https://github.com/istio/istio/tree/master/mixer/adapter/opa

**Comment by liminw** [comment]
Yes, this issue can be closed. I filed a related issue ([#3498](https://github.com/istio/istio/issues/3498)) recently to track further improvement for the OPA adapter.
