### ISSUE TITLE
Make improvements for better usability on SDS config

### ISSUE THREAD

**Issue by JimmyCYJ** [istio/istio#12443]
**Describe the bug**
Per discussion from https://github.com/istio/istio/pull/12433#issuecomment-472248486, currently SDS.enabled is not used as a guard for setting the sds.udsPath in the global mesh config map. And if someone accidentally adds some dummy path to this udsPath (while setting sds.enabled=false), it literally enables SDS in pilot. This will cause all envoys to crash. We need to guard SDS fields in the mesh config.

**Comment by JimmyCYJ** [comment]
cc @quanjielin @wenchenglu @hzxuzhonghu @rshriram

**Comment by wenchenglu** [comment]
It will be great if we can fix it before we cut the final release tomorrow. Otherwise, can we at least document this risk to warn users about dummy uds path setting?

**Comment by quanjielin** [comment]
1. Ideal fix would add sdsenable flag into meshconfig, though it takes time/risk since need api/update sha/a little pilot change.
2. documentation (my understanding it already documented in api and istio.io) - 
https://github.com/istio/api/blob/master/mesh/v1alpha1/config.proto#L187
https://preliminary.istio.io/docs/tasks/security/auth-sds/ (which point to helm config users should use)



I vote for use documentation for 1.1 cut tomorrow, and make the code fix in 1.1.1 like 
1. add sdsenable flag to meshconfig in api. 
2. add some check in [ValidateMeshConfig](https://github.com/istio/istio/blob/a9fe655d1d/pilot/pkg/model/validation.go#L1089).

**Comment by wattli** [comment]
Agree with Quanjie's proposal, since it is not a trivial change and we don't want to make the last minute rush.

**Comment by quanjielin** [comment]
close this, documentation is fine per discussion in https://github.com/istio/istio/pull/12534,
