### ISSUE TITLE
Galley validation tests frequently failing on k8s environment

### ISSUE THREAD

**Issue by incfly** [istio/istio#12480]
https://testgrid.k8s.io/istio-presubmits#integration-k8s-tests

It sometimes can pass, but most time fails, for example, https://prow.k8s.io/view/gcs/istio-prow/pr-logs/directory/istio-integ-k8s-tests/4951

**Comment by incfly** [comment]
Might help for https://github.com/istio/istio/issues/12267

**Comment by ozevren** [comment]
I believe this is due to: https://github.com/istio/istio/issues/12606
The CI version of the tests are running steadily after the landing of the refactored framework: 
https://testgrid.k8s.io/istio-presubmits#circleci-integration-kubernetes

In light of this, I am closing this bug. Feel free to reopen it if the problem reappears.
