### ISSUE TITLE
Istioctl unable to reach proxies in remote clusters

### ISSUE THREAD

**Issue by hmakkapati** [istio/istio#12501]
**Describe the bug**
Istioctl is unable to fetch config from proxies in remote clusters when Istio is deployed in a single control plane multi-cluster topology. Running the `istioctl proxy-status` and `istioctl proxy-config` commands for remote proxies from control plane cluster will fail.

```
$ istioctl proxy-status <remote proxy pod>.<namespace>
Error: unable to retrieve proxy container name: unable to retrieve Pod: pods "<pod name>" not found
```

```
$ istioctl proxy-config clusters <remote proxy pod>.<namespace>
Error: failed to execute command on envoy: unable to retrieve proxy container name: unable to retrieve Pod: pods "<pod name>" not found
```

**Expected behavior**
istioctl should return proxy config and sync diff with `proxy-config` and `proxy-status` respectively for remote proxies

**Steps to reproduce the bug**

1. Provision a single control plane multi-cluster mesh
2a. Run `istioctl proxy-status <remote proxy pod>.<namespace>`
2b. Run `istioctl proxy-config clusters <remote proxy pod>.<namespace>`

**Version**
$ istioctl version --remote --short
client version: 1.1.0-rc.5
citadel version: 1.1.0-rc.5
galley version: 1.1.0-rc.5
pilot version: 1.1.0-rc.5
sidecar-injector version: 1.1.0-rc.5
telemetry version: 1.1.0-rc.5

**Comment by hzxuzhonghu** [comment]
I guess `istioctl` does not support multicluster @liamawhite @ymesika

**Comment by liamawhite** [comment]
No, it requires kubectl access to the remote cluster. This is something we would like to support but it will need a rethink of how the command works. We should consider this as part of the CNI work changes as and when we need to do them.

**Comment by esnible** [comment]
`istioctl proxy-config` can access the remote cluster today if there is a Kubernetes context:

```
istioctl --context <my-other-cluster> proxy-config bootstrap <pod-in-my-other-cluster>.default
```

Would it be reasonable to extend the commands to allow arguments for two Kubernetes contexts and have it continue working like it does today?  `istioctl proxy-status --remote-context <context> <remote proxy pod>.<namespace>`

**Comment by liamawhite** [comment]
Ah, interesting. Yes, sounds like a good idea. We should make sure to add the same ability to `proxy-config` as well. My typical debug flow here is to run `proxy-status` to get a list of proxies then paste that into `proxy-config`.

**Comment by hmakkapati** [comment]
@esnible What you propose sounds very reasonable. However, should `istioctl` be topology aware eventually? I'm not sure of the technicalities here, so feel free to educate me :)

**Comment by esnible** [comment]
We want it to be topology aware.

I find it frustrating that Istio's `helm` chart knows how to set up different forms of multicluster, but `istioctl` doesn't know how to tell the user what was chosen.

I have an early draft of `istioctl mc` commands at https://docs.google.com/document/d/19mQojPz0A6W56CE9iREjSfCXjrvCf_hkU-bw5trzRpI/edit .

For `istioctl proxy-status <pod>` the tool reports any differences between what Pilot believes it told Envoy and what Envoy believes it was told by Pilot.  The implementation of that requires that istioctl be able to talk to both istio-pilot.istio.system:8080 and <pod>:15000.  (Currently we use `kubectl exec` to do that, it could be done other ways, such as starting a transient pod and `curl`ing from it).  Sometimes there are security reasons the current approach won't work.  This means multicluster, but also the case where the istioctl user lacks permission to manipulate pods in `istio-system` namespace.

Instead of error message `pods "<pod name>" not found` the error message should be `Pilot knows about <pod name> but it is in `network-abc`, not the current Kubernetes context "mycluster".  Please supply "--remoteK8sContext network-abc" parameter" (or something similar.)

**Comment by duderino** [comment]
@esnible I need to find an owner for this one.  Do you want this?

**Comment by esnible** [comment]
@duderino Can we move this to 1.2 or nebulous future?

**Comment by esnible** [comment]
This is not coming in 1.3.  Retargeting for 1.4 and adding networking area.  This is not a networking feature -- we must solve it in _istioctl_, but it relates to multicluster and we need to make sure that tests get created for it for the various networking styles.
