### ISSUE TITLE
How to save the metrics in prometheus more than one day？ 

### ISSUE THREAD

**Issue by linjinjin123** [istio/istio#12567]
Hi, I have run a hipster demo with istio, but the metrics(such as service duration) were saved only one day(look like restart at 12:00 am). I want to know how to modify the configure so that I can save the metrics for longer time?
![image](https://user-images.githubusercontent.com/10062840/54533399-fdae7f80-49c4-11e9-9de4-8921cbc542ca.png)

**Comment by jmazzitelli** [comment]
When installing via helm, use `--set prometheus.retention=2d` to store data for 2d. Obviously, replace "2d" with your desired retention period.

When you look at your installed Prometheus pod that Istio provides you, it passes in the retention rate in the command line - so presumably if you already have Istio/prometheus installed, you can just edit the deployment yaml and redeploy the pod.

**Comment by linjinjin123** [comment]
@jmazzitelli Thanks! I have found this parameter in my istio.yaml 
 
![image](https://user-images.githubusercontent.com/10062840/54534096-a27d8c80-49c6-11e9-8244-318796cda574.png)

**Comment by jmazzitelli** [comment]
Yup  - that's it. If you had passed that --set option to helm when you installed, that "6h" would have been whatever you passed in for its value.

You could alter that "6h" in your yaml and redploy to get a new retention period.

**Comment by douglas-reid** [comment]
Closing, as this has been answered.

**Comment by linjinjin123** [comment]
> Yup - that's it. If you had passed that `--set prometheus.retention` option to helm when you installed, that "6h" would have been whatever you passed in for its value.
> 
> You could alter that "6h" in your yaml and redploy to get a new retention period.

I have tried to modify the --stroage.tsdb.retention=30d in istio-demo.yaml, and use "kubectl apply -f istio-demo.yaml" to redeploy it, but it seems doesn't work, the data still save only 6 hours. 

I found there is a file in  install/kubernetes/helm/charts/istio/charts/prometheus/values.yaml which defined "retention: 6h" , but I think I haven't use helm to deploy my istio.  I just use "kubectl apply -f istio-demo.yaml" to deploy istio.
![image](https://user-images.githubusercontent.com/10062840/54734671-20ff4780-4bdc-11e9-93e4-af0e52de76ec.png)
I think that maybe this values.yaml override my custom args in istio-demo.yaml ?

**Comment by linjinjin123** [comment]
![image](https://user-images.githubusercontent.com/10062840/54741144-6cbfea00-4bf8-11e9-9ce6-0f37b0f53ead.png)
I have tried to use a small retention (2m), and then I entered the docker container to look the parameter, it looks like that the retention is changed.
But when I open the grafana, the data still remain more than 2 minutes.

**Comment by linjinjin123** [comment]
![image](https://user-images.githubusercontent.com/10062840/54743958-9e3cb380-4c00-11e9-9be6-41e0674644a5.png)
![image](https://user-images.githubusercontent.com/10062840/54743984-b44a7400-4c00-11e9-97f1-99db499a2f99.png)
I opened the website of prometheus, the website shows storage.tsdb.retention=2m, but the data still more than 2minutes.

The version of prometheus is v2.3.1

**Comment by douglas-reid** [comment]
@linjinjin123 if you are having prometheus issues around their configuration, I suggest seeking out support via prometheus channels.

**Comment by kylebevans** [comment]
@linjinjin123 

I recently dug into this for my own purposes and found that a 6 hour retention in prometheus will actually store 11 hours of data:

- Prometheus stores data in 2 hour chunks
- It stores the 2 hours data it's currently ingesting in memory in 128MB blocks
- It also stores a WAL of the current data on disk
- After it finishes a 2 hour block, it will wait another hour before running compaction and officially "retaining" the original 2 hour block to disk.  So at this point, it has 3 hours of data but the retention timer has only just started.
- Fast forward 6 hours, it's about to write it's 7th and 8th hour of data to disk officially.  If I had to guess, I think it checks for expired data to delete first, and doesn't find any since there are only 6 hours officially retained.  Now it writes another 2 hours so there are 8 hours on disk, but it is still ingesting new data. It has 9 hours of data at this point.
- Finally, after another 2 hours for a total of 11 hours, it deletes the oldest two hour block, but that ended up keeping a total of 11 hours of data that could show up on a graph.  If you are looking at your graph at this point, you should see your data drop from 11 hours down to 9.


https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/CreatingNewSubdomain.html#UpdateDNSParentDomain

**Comment by olegkovalichin** [comment]
have ran out into similar issue with more than 6h of data being held 

have used manifest-generate command and have manually edited the yaml

to achieve this;

![image](https://user-images.githubusercontent.com/54437963/79561663-9bc9b900-80a1-11ea-81e6-d1ea7181a0eb.png)

have searched the repo and found 4 instances of storage.tsdb.retention
will it be possible to change them to "storage.tsdb.retention.time"

the former is bound to be deprecated at some point 
just wondering if it might be misbehaving already
