### ISSUE TITLE
How can I open the Jaeger UI in a remote browser, not the localhost machine

### ISSUE THREAD

**Issue by qiaozhi58** [istio/istio#12593]
The official document said:
We can access the Jaeger UI by the following action:
kubectl port-forward -n istio-system $(kubectl get pod -n istio-system -l app=jaeger -o jsonpath=’{.items[0].metadata.name}’) 16686:16686 &

Then can use http://localhost:16686.
But the localhost is a Linux machine, there haven’t a browser.
I must open the browser on a remote machine.
How can I do?
thanks.

**Comment by serefacet** [comment]
@qiaozhi58 you could bind the listen address to 0.0.0.0 in order to open 16686 port to outside.

`kubectl port-forward **--address 0.0.0.0** -n istio-system $(kubectl get pod -n istio-system -l app=jaeger -o jsonpath=’{.items[0].metadata.name}’) 16686:16686 &
`

References
[https://github.com/kubernetes/kubernetes/issues/40053](https://github.com/kubernetes/kubernetes/issues/40053)

**Comment by esnible** [comment]
Create a VirtualService for the path /jaeger and set the destination to the Jaeger service.

@frankbu Should we consider a sample or other documentation showing how to expose the internal services?

**Comment by douglas-reid** [comment]
@esnible We added documentation already on how to expose the telemetry services. See: https://preliminary.istio.io/docs/tasks/telemetry/gateways/.

This was also filed against istio/istio.io. Closing.

**Comment by qiaozhi58** [comment]
@serefacet @esnible @douglas-reid 
thank you very much!
