### ISSUE TITLE
Grafana - Mesh 

### ISSUE THREAD

**Issue by Erick-Yataco** [istio/istio#12651]
after install istio 1.1.0 with helm and tiler using configuration profile  demo-auth, i deploy a single services in a custom namespace and expose gafana by loadbalancer (aws), but in mesh dashboard of grafana i can't see any register for the services

**Comment by douglas-reid** [comment]
The first thing to check is whether or not you've injected the proxy for your service's workload. Then you need to check that you've properly exposed container ports and followed the naming conventions around ports.

Let's move this to discuss.istio.io, which I think is a more appropriate forum for help.  Please open a thread there. If it turns out that there is an underlying issue, we can re-open.
