### ISSUE TITLE
wrong PROXY_TAG in istio.VERSION for release 0.2.10

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#1278]
export PROXY_TAG="docker.io/istio,0.2.10"

while 0.2.7 has
export PROXY_TAG="5d544187a15e11b593e931902e2d74f8dca26ef7"

**Comment by ldemailly** [comment]
the good news (!) is it is correct in the generated yaml and in kube-inject

so only https://github.com/istio/istio/search?utf8=%E2%9C%93&q=PROXY_TAG&type=
consul/eureka may be broken

(and if the users tries to regenerate the yaml)

**Comment by chxchx** [comment]
Please review
The bug is that udpateVersion.sh takes a slightly different flag on proxy to update the SHAs, where proxy does not need a hub like auth or pilot would. 
```
-c <hub>,<tag> new ca image
-r <tag> new proxy tag
```
The release tool was passing in a proxytag that was still in the form of <hub,tag>, which is wrong. The fault originated from this PR https://github.com/istio/test-infra/pull/519 which I LGTM-ed. Oops. It won't happen again.

**Comment by mattdelco** [comment]
I doubt we'll be patching 0.2.10 for this (and I doubt that there will be future patches for any 0.2 release now that 0.3 is out).  0.2 had a "semi-automated" release process that allowed for human error, and 0.4 should now be automated, at least as far as this step/issue is concerned (0.3 used a preliminary implementation of 0.4's that was semi-manually executed).  As of 0.3 the script release/update_and_create_archives.sh is used to make 2 sets of tarballs -- one "testonly" set that points to the prerelease storage location, another set that points to the anticipated release storage location (which will only become valid if/when the release is published as a monthly release, hence the "testonly" set that permits testing prior to publishing). So, I don't think there's anything more left to do regarding this issue and it can probably be closed.
