### ISSUE TITLE
Error from server (BadRequest): a container name must be specified for pod istio-telemetry-78c647b78c-zp5gs, choose one of: [mixer istio-proxy]

### ISSUE THREAD

**Issue by planeo1105** [istio/istio#12904]
**Describe the feature request**
Use helm to deploy this error in the version of isti 1.1.1

# kubectl logs -f istio-telemetry-78c647b78c-zp5gs -n istio-system
Error from server (BadRequest): a container name must be specified for pod istio-telemetry-78c647b78c-zp5gs, choose one of: [mixer istio-proxy]

**Describe alternatives you've considered**
nothing

**Additional context**
no

**Comment by howardjohn** [comment]
The istio-telemetry pod has two containers - mixer and istio-proxy. Because of this, you need to specify which one you want to pull the logs from. 

You have three options:
* `kubectl logs -f istio-telemetry-78c647b78c-zp5gs -n istio-system -c istio-proxy` to get proxy logs 
* `kubectl logs -f istio-telemetry-78c647b78c-zp5gs -n istio-system -c mixer` to get telemetry logs
* `kubectl logs -f istio-telemetry-78c647b78c-zp5gs -n istio-system --all-containers` to get all logs

This is all Kubernetes by the way, and happens any time you have two containers in a pod, unrelated to Istio.

Feel free to reopen this if that does not solve your problem.
