### ISSUE TITLE
Injector: Document all annotations used

### ISSUE THREAD

**Issue by geeknoid** [istio/istio#12939]
Need to document all annotations used in the code. Search for annotations.Register and fill in the necessary description string. These descriptions will go to istio.io as end-user docs.

**Comment by howardjohn** [comment]
Done https://preliminary.istio.io/docs/reference/config/annotations.html

**Comment by frankbu** [comment]
I wonder if we should include some text that shows examples of how/where to put the annotations in a resource spec. I'm pushing back on PRs like [this one](https://github.com/istio/istio.io/pull/5026) because I think it would be better to just link to some place where it shows, for example, how to add a pod annotation in a deployment. I was hoping there was some such k8s doc, but I haven't found it.
