### ISSUE TITLE
Authorization policy not enforced

### ISSUE THREAD

**Issue by akyyy** [istio/istio#13038]
**Describe the bug**
When RbacConfig is turned on, I can still access my service.

**Expected behavior**
When RbacConfig object is created, I should get access denied error.

**Steps to reproduce the bug**
1. Create a gke cluster
2. Install istio addon 
gcloud beta container clusters update cluster1 \
    --update-addons=Istio=ENABLED --istio-config=auth=MTLS_PERMISSIVE
3. Enable envoy injection for default namespace
kubectl label namespace default istio-injection=enabled --overwrite
4. Create a RbacConfig object.
5. Deploy my service.
6. User should get access denied.

**Version**
kubectl version v1.14.0
istio version --remote:
version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.0-17-g2b13318"}
Error: error execing into istio-citadel-7c4864c9d5-kplg6 citadel container: command terminated with exit code 255

**Installation**
gcloud beta container clusters update cluster1 \
    --update-addons=Istio=ENABLED --istio-config=auth=MTLS_PERMISSIVE

**Comment by akyyy** [comment]
The pilot discovery container doesn't have much logs for "rbac". The pilot istio-proxy container had errors "shutting down due to child request". 
I don't see any log "built filter config for" for pilot.

**Comment by yangminzhu** [comment]
Talked with @akyyy offline and logged into the user's cluster for debugging, the reason is you applied the wrong service which Istio doesn't support,
you need to name your service port following the Istio spec: https://istio.io/docs/setup/kubernetes/prepare/requirements/
I deleted one service and renamed the other one to start with `http-`.

Also please be noted, The RBAC in Istio 1.0 only supports HTTP, the RBAC in1.1 will also support TCP

**Comment by yangminzhu** [comment]
Note, debugged with the customer offline for using Istio 1.1 in the customer's GKE cluster and it turns out the GKE cluster is started with some special arguments and it seems some firewall rules are preventing the connection to docker.io, which breaks the installation of Istio. Closing as this is not related to Istio.
