### ISSUE TITLE
Need a CI check to validate istio YAMLs

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#13220]
Working on https://github.com/istio/istio/pull/13196 got me thinking that we need a lightweight and robust way to validate the existing samples statically.

I think istioctl is the right place for this. What might be missing is _deep_ validation that supports extensible schemas and referential checks. For example, Mixer allows uploading a new schema for handlers and templates that need to be cross linked from the use places.

We should try to extend istioctl to support as much validation as possible, and enable it on the repo as a presubmit check on all samples.

/cc @geeknoid 
/cc @esnible

**Comment by esnible** [comment]
I validate with `find samples -name "*.yaml" | xargs -n 1 istioctl validate -f`.  (This does a pretty good job now that on failure we return 1 instead of 255.)  Obviously it is local validation, not global.

For validation of lots of things there is https://github.com/istio/istio/issues/12523 or working with the https://github.com/aspenmesh/istio-vet folks who have a tool for checking Istio beyond single object correctness.

**Comment by kyessenov** [comment]
This is done via `bin/check_samples.sh`  script.
