### ISSUE TITLE
Which tag should I use to build Istio package, 1.1.1 or 1.1.2?

### ISSUE THREAD

**Issue by shuiqing05** [istio/istio#13236]
Hi, 
    From the reply (https://github.com/istio/istio/issues/13016#issuecomment-479513981), @howardjohn said the release 1.1.2 is not a real release.
    And, the commit IDs of tag 1.1.2 and 1.1.1 are same. Hence, I am confusing. If I want to build istio package from source code, which tag should I checkout to, the 1.1.2 or 1.1.1?
    By the way, how do I know whether the built package is 1.1.2, not 1.1.1
    Thanks!

**Comment by howardjohn** [comment]
1.1.2 was a bit of a weird release as we just changed the proxy image I believe, so the commit Id was the same.  So you could checkout 1.1.1 or 1.1.2 since they are the same.

I assume this is not relevant anymore since we are well past 1.1.2, sorry we didn't get to this earlier. If it is still relevant please reopen
