### ISSUE TITLE
Investigate using additional image scan for istio docker images

### ISSUE THREAD

**Issue by linsun** [istio/istio#13262]
Our team within IBM has done vulnerability scan on our shipped 1.1 images and found some images have issues.  It would be really good if we can integrate our scanner as it picked up some stuff that the redhat one or GCR didnt for example, its a simple curl to use it, `curl -Ls http://imagescanner.cloud.ibm.com/scan?image=$image`

**Comment by linsun** [comment]
cc @jsloyer

**Comment by linsun** [comment]
@johnma14 : would be great if you can investigate the issues with some of the images:

docker.io/istio/proxyv2:1.1.2  "Progress": "Scan completed: FAIL",
docker.io/kiali/kiali:v0.14  "Progress": "Scan completed: FAIL",  --> @jmazzitelli will move to 0.18
grafana/grafana:5.4.0  "Progress": "Scan completed: FAIL",  --> I opened PR to move to 6.0.2
istio/examples-bookinfo-ratings-v1:1.10.1  "Progress": "Scan completed: FAIL",
istio/examples-bookinfo-reviews-v1:1.10.1  "Progress": "Scan completed: FAIL",
istio/examples-bookinfo-reviews-v2:1.10.1  "Progress": "Scan completed: FAIL",
istio/examples-bookinfo-reviews-v3:1.10.1  "Progress": "Scan completed: FAIL",

**Comment by linsun** [comment]
#13273

**Comment by johnma14** [comment]
This note is to serve as a summary of the work done in this WI:

The istio images that were showing security vulnerabilities are the following:
- bookinfo-reviews (https://github.com/istio/istio/pull/13716)
- bookinfo-mysqldb (https://github.com/istio/istio/pull/13774)
- bookinfo-mongodb (the fix for booking-reviews should fix the vulnerabilities for this app)
- bookinfo-ratings (https://github.com/istio/istio/pull/13748)

bookinfo-details app does not have any security vulnerabilities but I added a fix to update the ruby version to the latest one (https://github.com/istio/istio/pull/13747)

Thanks.
