### ISSUE TITLE
Mirror traffic to multiple hosts

### ISSUE THREAD

**Issue by myelinproj** [istio/istio#13330]
**Describe the feature request**

I would like to mirror the traffic to multiple hosts in the virtual service. 

I assume this is not possible looking at the current schema of the virtual service as `http[].mirror` only accepts one destination (not an array). 

Is this possible? If not, can anyone suggest a workaround?

**Comment by arianmotamedi** [comment]
@howardjohn correct me if I'm wrong but I think this needs to be a feature request for https://github.com/envoyproxy/envoy since right now it only supports mirroring traffic to [only one extra host](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto#route-routeaction-requestmirrorpolicy), and Istio's `HTTPRoute.Mirror` simply generates a mapping to Envoy's `Route.RouteAction.RequestMirrorPolicy`. When (if) Envoy supports mirroring requests to an array of clusters, the implementation on the Istio side will be fairly simple.

**Comment by howardjohn** [comment]
Nice workaround @arianmotamedi. As mentioned, this would need envoy support. I would encourage you to open an issue there and if/when it gets merged let us know and we can add support for it (or you can as well, contributions are always welcome!)

**Comment by xpepermint** [comment]
This is not supported by Envoy: https://github.com/envoyproxy/envoy/pull/9164
Can we expect this feature to be supported by Istio?

**Comment by PiotrKlimczak** [comment]
Same question here: now supported by envoy, when expected in Istio?

**Comment by adriank-convoy** [comment]
@howardjohn wondering if we can reopen this issue now that Envoy has deprecated `route.RouteAction.request_mirror_policy` in favor of the new `route.RouteAction.request_mirror_policies` [option in v3](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#config-route-v3-routeaction). It looks like the istio code has already been updated to set the policies value as an array https://github.com/istio/istio/blob/4a95796e44fd00fb26e90782e592d4d331e0fd27/pilot/pkg/networking/core/v1alpha3/route/route.go#L442 but it's not exposed in the istio api.

FWIW we're running a standalone Envoy instance with file based config to use as an edge proxy for a cluster in production specifically for this feature. It turns out it's pretty useful for a variety of things... Thanks!

**Comment by omerfsen** [comment]
+1

**Comment by yingzhuivy** [comment]
+1 can we reopen this feature request? it will be useful

**Comment by gs-alt** [comment]
+1

**Comment by yossisal** [comment]
+1

**Comment by Stono** [comment]
@howardjohn any chance we can reopen this?  I'd find it useful!

**Comment by mrajib321** [comment]
+1

**Comment by murphye** [comment]
With the ability to mirror traffic to multiple upstreams, I feel there is a compelling new use case here to consider. 

Let's say that you have an existing point-to-point event-driven microservices. Maybe there is a new requirement to distribute these events to 3 more microservices in a **fire-and-forgot manner**. In this case, using something like Kafka is overkill and would be a "good enough" implementation where dropped events are not the end of the world. 

This may be valuable for IoT applications, especially when the latency of introducing something like Kafka would be of high concern.

Thoughts?

**Comment by fatedier** [comment]
Is anyone working on implementing this feature?

**Comment by fatedier** [comment]
@howardjohn Can you help review on this PR https://github.com/istio/api/pull/2805
