### ISSUE TITLE
Kiali fails to fetch pod logs

### ISSUE THREAD

**Issue by APuertaSales** [istio/istio#13420]
**Bug description**
Error shown in Kiali when accessing a workload Logs:
Failed to fetch pod logs: pods "XXXXX" is forbidden: User "system:serviceaccount:istio-system:kiali-service-account" cannot get resource "pods/log" in API group "" in the namespace "XXXXX"

**Expected behavior**
Show the POD log.

**Steps to reproduce the bug**
Go to Kiali and navigate to a Workloads/Namespace/Workload/Workload Info and click on "Logs".

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Istio 1.1.0
Kubernetes v1.13.3
Kubectl Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"windows/amd64"}

**How was Istio installed?**
Helm chart.

**Comment by APuertaSales** [comment]
Can be resolved in kiali clusterrole:
adding 
`  - pods/log`

to
```
- apiGroups:
  - ""
  resources:
```

https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/kiali/templates/clusterrole.yaml

**Comment by jmazzitelli** [comment]
Kiali does not access logs (at least, not in the versions Istio installed - today it is v0.14 in Istio 1.1 and v0.16 in master). A newer Kiali does provide log views, but that is not available in the Kiali installed by Istio today.

How did you install Kiali? I assume not through Helm but by some other outside mechanism. Or you tried to bump up the Kiali version via the helm kiali.tag property, but you can't just bump up the version and expect it to work because, as you see, some yaml also needs to change with newer versions.

This permission has already been added to the latest Kiali - but this work is done over in the Kiali project. We'll move this over to Istio when we get Istio upgraded to the latest Kiali.

See http://github.com/kiali/kiali

But suffice it to say, this is what you are asking for: https://github.com/kiali/kiali/blob/v0.18/operator/roles/kiali-deploy/templates/kubernetes/clusterrole.yaml#L17

I would close this issue - it is not relevent to Istio and the versions of Kiali it ships with.

**Comment by douglas-reid** [comment]
Closing, per @jmazzitelli. Please track in kiali repo.
