### ISSUE TITLE
Support configurable shared span context 

### ISSUE THREAD

**Issue by morvencao** [istio/istio#13508]
## Describe the feature request

The configuration `shared_span_context` allows us to determine whether client and server spans will shared the same span id. And this value seems to be set to `false` by Istio.

Maybe we should consider to make this field configurable in the API since some customers really want this to be `true`.

## Describe alternatives you've considered
Expect Istio to support new API or enhance current tracing API to support envoy `shared_span_context` configuration.

**Comment by bianpengyuan** [comment]
cc @douglas-reid @objectiser 

shared_span_context false by default is making zipkin generating wrong span hierarchy, I think we should definitely make this value adjustable, or at least give it reasonable default value based on data model expected by the tracing system.

**Comment by objectiser** [comment]
@bianpengyuan Do you have an example illustrating how the wrong span hierarchy is generated?

**Comment by bianpengyuan** [comment]
@objectiser  See this: https://github.com/istio/istio/issues/13391#issuecomment-484986113

**Comment by objectiser** [comment]
@bianpengyuan Are you referring to the `shared_span_context` config [here](https://github.com/istio/istio/blob/master/tools/packaging/common/envoy_bootstrap_v2.json#L302)? If so, then this governs how span data is generated from the envoy proxy, which is not relevant when generating span data from the adapter.

**Comment by bianpengyuan** [comment]
Sorry maybe I was not very clear in the linked comment. The graph attached in that comment was from envoy reporting span directly to zipkin. I found it was wrong when I try to debug the linked issue.

**Comment by bianpengyuan** [comment]
@objectiser I checked my test cluster again and seems like zipkin could render separated server/client span correctly this time:

<img width="1424" alt="Screen Shot 2019-04-22 at 10 38 47 AM" src="https://user-images.githubusercontent.com/34738376/56514706-de869e80-64ea-11e9-93e3-ea91da4535dc.png">

Let me dig more and I will share my finding here.

**Comment by zhu0516123** [comment]
We have such a situation：
Two systems in kubernetes. System A is in istio, and the spans were generated by envoy. System B is not in istio, and the spans were generated by other distributed tracing  system, such as libraries which been supported by the OpenZipkin. The service of system A access The service of system B. Then the spans  of system A and system B were send to the same zipkin-collector. If we want to see the correct span context in zipkin-ui, it is necessary to set the [shared_span_context](https://www.envoyproxy.io/docs/envoy/v1.8.0/api-v2/config/trace/v2/trace.proto) true.

**Comment by bianpengyuan** [comment]
@zhu0516123  How does` shared_span_context` help in this case? `shared_span_context` controls envoy whether to generate new span for ingress request or not. If system B is not even using envoy, how would shared_span_context affect span generation in systemB? Instead, the tracing library used by systemB should properly handle tracing context from request headers so that spans from two systems could correlate.

**Comment by zhu0516123** [comment]
@bianpengyuan It seems that if the **shared_span_context** is true, the spans in two systems will be  normaller in zipkin-ui.

shared_span_context=true:
![shared_span_context=true](https://user-images.githubusercontent.com/20107856/56564766-6222b700-65e1-11e9-8d02-794e04572e46.PNG)


shared_span_context=false:
![shared_span_context=false](https://user-images.githubusercontent.com/20107856/56564792-6f3fa600-65e1-11e9-9746-a9330f3bb610.PNG)

**Comment by bianpengyuan** [comment]
@zhu0516123  Thanks for the detailed explanation! I see, it is to make istio tracing behavior consistent with non-istio environment. That makes sense to me. I've created the api change: https://github.com/istio/api/pull/907. Once that is in, I will update the code in main repo.

**Comment by zhu0516123** [comment]
@bianpengyuan Thanks!

**Comment by foshantiger** [comment]
@morvencao @zhu0516123 for now, there are two ways to override the shared_span_context value:
1. define a custom-bootstrap.yaml and apply it, then add the annotation to the deployment, refer to [https://github.com/istio/istio/tree/master/samples/custom-bootstrap](url)
```apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-custom-bootstrap-config
  namespace: default
data:
  custom_bootstrap.json: |
    {
      "tracing": {
        "http": {
          "name": "envoy.zipkin",
          "config": {
            "collector_cluster": "zipkin",
            "collector_endpoint": "/api/v1/spans",
            "trace_id_128bit": "true",
            "shared_span_context": "true"
          }
        }
      }
    }
```
```
template:
    metadata:
      annotations:
        sidecar.istio.io/bootstrapOverride: "istio-custom-bootstrap-config"
```
2. mount a configmap to the path /var/lib/istio/envoy/envoy_bootstrap_tmpl.json at istio-proxy container to override the envoy_bootstrap_tmpl.json, when the proxy start, it will generate the bootstrap config file from that template file.

**Comment by morvencao** [comment]
@foshantiger we'd better have Istio API support configurable shared span context.

**Comment by silencehe09** [comment]
> @zhu0516123 Thanks for the detailed explanation! I see, it is to make istio tracing behavior consistent with non-istio environment. That makes sense to me. I've created the api change: [istio/api#907](https://github.com/istio/api/pull/907). Once that is in, I will update the code in main repo.

@bianpengyuan  Is the api change in ?

**Comment by bianpengyuan** [comment]
@silencehe09 No I think the api change won't make it, because it conflicts with the plans for operator and tracing api support in Sidecar API. For now I think we are in favor of customized bootstrap template and annotation. I will keep this issue open until to track this FR until we have a better way to provide configurability on this.

**Comment by silencehe09** [comment]
> @zhu0516123 Thanks for the detailed explanation! I see, it is to make istio tracing behavior consistent with non-istio environment. 
@bianpengyuan  I had met a problem when trying to make istio tracing behavior consistent with non-istio environment **if istio ingress gateway is used**.  Can you give some suggestions? 

Consider this situation (whether share_span_context is set to  true or not; the following share_span_context is set to false):
![istio-tracing](https://user-images.githubusercontent.com/4385562/57456967-366e2500-72a1-11e9-8d0a-2c5ad123f51e.png)

Because the istio ingress gateway is running in "route" mode, it seems that it only reports one span(outbound span) and ignores the inbound span , but the tracing headers is modified inbound. 
As a result, one span is missing for this trace.  I had tried out some experiments and analyzed the span data in json format , just found only one span reported by istio ingress gateway for per trace. 

Is there any method to solve this problem?  To make tracing  disabled in istio ingress gateway or make tracing headers pass through?

**Comment by silencehe09** [comment]
> @zhu0516123 Thanks for the detailed explanation! I see, it is to make istio tracing behavior consistent with non-istio environment. That makes sense to me. I've created the api change: [istio/api#907](https://github.com/istio/api/pull/907). Once that is in, I will update the code in main repo.

@bianpengyuan  I had met a problem when trying to make istio tracing behavior consistent with non-istio environment **if istio ingress gateway is used**. Can you give some suggestions?

Consider this situation (whether share_span_context is set to true or not; the following share_span_context is set to false):
![istio-tracing](https://user-images.githubusercontent.com/4385562/57458056-4555d700-72a3-11e9-9ba9-6a5aa9d10f82.png)

Because the istio ingress gateway is running in "route" mode, it seems that it only reports one span(outbound span) and ignores the inbound span , but the tracing headers are modified inbound.
As a result, one span is missing for this trace. I had tried out some experiments and analyzed the span data in json format , just found only one span reported by istio ingress gateway for per trace.

Is there any method to solve this problem? To make tracing disabled in istio ingress gateway or make tracing headers pass through?

**Comment by bianpengyuan** [comment]
@silencehe09 Are you seeing trace generated by istio cannot connect to the ones generated outside of istio? If that is the case, I think maybe it is because ingressgateway is not aware of the trace initiated by the external client. Could you please try to set `x-client-trace-id` headers? https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/tracing#how-to-initiate-a-trace

**Comment by silencehe09** [comment]
@bianpengyuan Thanks. It seems to be right when I initialte the span of external client.

**Comment by silencehe09** [comment]
@bianpengyuan  By the way, can we only disable the tracing of istio ingress gateway?

**Comment by bianpengyuan** [comment]
No, I don't think we could control tracing at per workload granularity. @douglas-reid has a wip proposal  about better tracing control via API: https://tinyurl.com/y3lnlf7n

**Comment by douglas-reid** [comment]
@silencehe09 is your desire to not have a span for the ingress gateway, but have spans for the rest of the services involved?  we don't have a way to do that yet.  as @bianpengyuan relates, we are working towards a proposal that may allow us to do that.
