### ISSUE TITLE
TestGrid missing test Failures

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#13789]
Testgrid marks a lot of failed tests as still running, giving us a false sense of our tests - things look green when they really are not.

I believe there are 3 distinct causes of this

1. Status not reported to gubernator. Already fixed in https://github.com/istio/istio/issues/13208
2. Status reported to gubernator, but test grid not updated
Example: 
https://prow.k8s.io/view/gcs/istio-circleci/presubmit/test-integration-kubernetes/406226 shows the failure and https://circleci.com/gh/istio/istio/406226 shows the result was uploaded. https://testgrid.k8s.io/istio-presubmits#circleci-integration-kubernetes still shows it as running though.
3. CircleCi gets into a broken state where the test has failed but it doesn't finish running jobs.
Example: 
https://circleci.com/gh/istio/istio/405501#tests/containers/0
Filed a bug to CircleCI https://discuss.circleci.com/t/tests-marked-as-failed-but-are-still-running/30169

**Comment by duderino** [comment]
Hi @icygalz since this is a 1.2 blocker and Maria is on vacation, can you take this?

**Comment by icygalz** [comment]
Is the issue for Postsubmit or Presubmit? The postsubmit seems doing just fine because it is posting to the right bucket/directory.

For presubmit, I think the culprit for this issue is that CircleCI tests didn't post JUnit results into our gcs bucket:

This is our gcs bucket for circleci test:
https://console.cloud.google.com/storage/browser/istio-circleci

TestGrid are scanning these gcs bucket for their result:
```
- name: istio-circleci-e2e-simple-presubmit-release-1.2
  gcs_prefix: istio-circleci/presubmit/release-1.2/e2e-simple
```
https://github.com/kubernetes/test-infra/blob/master/testgrid/config.yaml#L1383

That bucket or directory did not exist.

**Comment by howardjohn** [comment]
@icygalz that is a different issue than the one in the original description but sounds like it needs to be fixed too. In the case of 1.2, there are 0 tests results: https://testgrid.k8s.io/istio-presubmits-release-1.2#circleci-e2e-simple

In the originl issue, the tests failed but werent reported to test grid in some case (while successes were!)

For #2, the history is lost and I haven't seen it since so not sure if we can do much.

For #3 I opened a discuss topic on circleCi since it is a bug on their side. I also just opened a support ticket which I think we get premium support on now

**Comment by howardjohn** [comment]
For 3, I contacted CircleCI, they said its fixed. If we run into it again we can investigate further but I haven't personally seen it.

More troubling is I found the same issue on Prow. See https://testgrid.k8s.io/istio-presubmits-master#pilot-e2e-envoyv2-v1alpha3

A bunch of tests are marked as running, but they are completed. Some failed, some not failed
![2019-11-06_09-57-37](https://user-images.githubusercontent.com/623453/59291297-5f326300-8c2f-11e9-9d36-5ac6d99c0895.png)

Here is one marked as running that failed: https://prow.k8s.io/view/gcs/istio-prow/pr-logs/directory/istio-pilot-e2e-envoyv2-v1alpha3-master/1505

Here is one marked as running that is aborted: https://prow.k8s.io/view/gcs/istio-prow/pr-logs/directory/istio-pilot-e2e-envoyv2-v1alpha3-master/1509 (prow interface says still running as well until you click see more information)

Here is one marked as running that is pending: https://prow.k8s.io/view/gcs/istio-prow/pr-logs/directory/istio-pilot-e2e-envoyv2-v1alpha3-master/1511

Here is one marked as running that passed: https://prow.k8s.io/view/gcs/istio-prow/pr-logs/directory/istio-pilot-e2e-envoyv2-v1alpha3-master/1516

**Comment by icygalz** [comment]
To give an update:

After talking with k8s testgrid engineers:
Usually TestGrid will show the state as "Running" if finished.json file failed to get uploaded into GCS.

Some of these "Running" tests are in that state where finished.json file didn't get uploaded one way or another. We might need to catch one whose pod are still laying around and read why it failed to upload finished.json file.


There are some instances where john posted above for example:
1. https://prow.k8s.io/view/gcs/istio-prow/pr-logs/directory/istio-pilot-e2e-envoyv2-v1alpha3-master/1505
2. https://prow.k8s.io/view/gcs/istio-prow/pr-logs/directory/istio-pilot-e2e-envoyv2-v1alpha3-master/1509

These two are real issue because finished.json file are uploaded but testgrid are still showing as "Running". i am working with k8s testgrid engineer on this.

**Comment by icygalz** [comment]
In my understanding for prow tests, we should assume the worst(test can/will fail) for test in "not finished" state. From the problem stated above, it is pretty consistent that when testgrid shows "Not Finished":
1. test failed and didn't post finished.json to gcs (can happened for many different reasons but usually happens on presubmit stage, for ex: new commit while in the middle of test run, etc)
2. test failed, posted finished.json, and testgrid didn't update its state.

For circleci presubmit testgrid tab, I found some issue with how we separate the presubmit results for each branch in testgrid. The actual circleci presubmit results are still all combined under this i[stio-presubmit](https://testgrid.k8s.io/istio-presubmits) tab. CircleCi postsubmit results separation works as expected so let me know if you see the same issue in postsubmit result.

I agree there are several issues we need to fix but i don't believe this should be a release blocker. We shouldn't block releases based on presubmit results.

**Comment by howardjohn** [comment]
Agree its not a release blocker. Lets move this to P1 and then once the release is out we can move to P0 like we are doing with other mauve improvements

**Comment by howardjohn** [comment]
Seems all cases now are ones where prow doesn't report the test as completed; this means the pod was probably evicted or something and restarted -- it didn't pass or fail, so not reporting is ok.
