### ISSUE TITLE
Generate Istio certs on demand

### ISSUE THREAD

**Issue by edussx** [istio/istio#13836]
**Describe the feature request**
Currently Citadel generates certs for each ServiceAccount in each Namespace upon installation. However, this brings 2 problems in our use cases:

1. Since we didn't enable side car auto injection in all the namespaces, some users were confused with `istio.default` secret in their own namespaces. And they also complained that Istio cert secrets ate up secret resourcequota
2. Due to the previous problem, we set `--server-only` flag for istio_ca and then disabled control plane TLS and it worked. But soon we found `ISTIO_MUTUAL` in `DestinationRule` is unusable.

So I wonder if it were possible to generate these secrets on demand. For example, if `istio-injection=enabled` annotation is not set for a namespace, then Citadel won't generate those secrets upon installation. Later user can manually request Istio to generate cert secret,  probably by annotate the namespace or by creating a `DestinationRule` telling Istio `ISTIO_MUTUAL` is enabled in a specific namespace if side car is injected manually.

**Describe alternatives you've considered**

**Additional context**

**Comment by elevran** [comment]
@edussx please see https://github.com/istio/istio/pull/15503 and let us know if this resolves your issue.
CC @Monkeyanator

**Comment by Monkeyanator** [comment]
As @elevran pointed out, the changes in #15503  give users more control over which namespaces Citadel will generate `ServiceAccount` secrets for (through namespace labels, as you mentioned, and a configurable default behavior). Currently working on docs and integration tests for this feature, but I'm not sure it will be stable/documented before 1.3 release.

Until then, the best option might be the `listened-namespaces` flag ([documented here](https://istio.io/docs/reference/commands/istio_ca/))- the issue here is that changing the list of listened namespaces requires a Citadel restart. The `explicit-opt-in` flag, which disables secret generation as the default behavior, and then allows you to tag namespaces with `istio-managed=enabled`, does something similar, but I don't believe the version in the latest release will work due to [this issue](https://github.com/istio/istio/pull/15113).

**Comment by edussx** [comment]
@elevran @Monkeyanator Thanks for this fix! I have looked at the PR and think it should fix our issue. Just one more question towards #15503: will `--explicit-opt-in` and `--listened-namespaces ` be removed in the future release, as long as #15503 is released? It looks like `--explicit-opt-in` is sort of duplicated with label `ca.istio.io/env` from my perspective.

**Comment by Monkeyanator** [comment]
@edussx Yes, `--explicit-opt-in` will be removed entirely in the next release, and `--listened-namespaces` will be deprecated.

**Comment by edussx** [comment]
@Monkeyanator Got it and thank you for the PR again. Let me close this issue.
