### ISSUE TITLE
[Test Framework] Galley: Support multiple namespaces in Apply/Delete

### ISSUE THREAD

**Issue by nmittler** [istio/istio#13920]
The Galley API currently only supports a single namespace for each call to `ApplyConfig`/`DeleteConfig`. It would useful to allow the user to pass a yaml doc with namespaces already defined, so that they could mix namespaces in a single doc.

FYI @ozevren @pitlv2109

**Comment by nmittler** [comment]
Actually, it appears that the Galley Apply/Delete methods already support nil namespaces.  Closing this for now, we can re-open if it appears this doesn't work as expected.

**Comment by pitlv2109** [comment]
Actually Galley support nil namespaces when applying, but not deleting.
https://github.com/istio/istio/blob/ec8795e9149ac64c24fb7c6aa30604b524ac3629/pkg/test/framework/components/galley/kube.go#L182

It will give a segfault (in `ns.Name()` if `ns` is nil). Should be a quick fix. I will send you a PR soon.

**Comment by ozevren** [comment]
Thanks for fixing it. Can you also make sure to add a regression test to
the framework integration test suite?

*From: *Phillip Quy Le <notifications@github.com>
*Date: *Wed, May 8, 2019 at 3:09 PM
*To: *istio/istio
*Cc: *Ozben Evren, Mention

Reopened #13920 <https://github.com/istio/istio/issues/13920>.

**Comment by nmittler** [comment]
@pitlv2109 thanks!

**Comment by pitlv2109** [comment]
@ozevren Where is the framework integration test suite?

**Comment by ozevren** [comment]
integration/tests/framework

**Comment by pitlv2109** [comment]
You guys already have test for that https://github.com/istio/istio/blob/6089adf96580abed81f56fb7f87bc78d78a5bdd8/tests/integration/framework/galley_test.go

However, only native env support deleting multiple namespaces at once. And since maybe unit tests are using native env by default, the test passes. I think we can just add the nil check and use `""` for ns if ns is nil for and verify manually that it works for kube env.
