### ISSUE TITLE
Allow DirectHttpResponses to return multiple keys of the same name.

### ISSUE THREAD

**Issue by sandmman** [istio/istio#14240]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Allow *DirectHttpResponse* to return multiple header key/value pairs with the same key.

```
e.g.

Set-Cookie: <cookie-name-1>=<cookie-value-1>
Set-Cookie: <cookie-name-2>=<cookie-value-2> 
```

**Describe alternatives you've considered**

1. Tried folding multiple cookies into the same header. Firefox and chrome ignored all except the first declared.

2. Attempted to combine `DirectHttpResponse` and `RouteDirectives`. However, `DirectHttpResponse` is only applied on a non-OK response https://istio.io/docs/reference/config/policy-and-telemetry/istio.policy.v1beta1/#DirectHttpResponse, while `RouteDirectives` are only applied on OK responses https://istio.io/docs/reference/config/policy-and-telemetry/istio.policy.v1beta1/#Rule

**Additional context**

*DirectHttpResponse* currently allows Mixer adapters to send a custom HTTP status code and map of headers after a 401 response. This enables adapters to do things like initiate redirects or set cookies.

Unfortunately, some default HTTP headers do not support multiple being folded into the same header field, but instead require two separate headers of the same name. 

See `Set-Cookie` and its accompanying [RFC6265](https://tools.ietf.org/html/rfc6265#section-3).
```
Excerpt from RFC6265:
An origin server can include multiple Set-Cookie header fields in a single response.

Origin servers SHOULD NOT fold multiple Set-Cookie header fields into a single header field.  The usual mechanism for folding HTTP headers fields (i.e., as defined in [RFC2616]) might change the semantics of the Set-Cookie header field because the %x2C (",") character is used by Set-Cookie in a way that conflicts with such folding.
```

**Comment by elevran** [comment]
There are several options to implement this enhancement. For example:

1. expand set of headers (e.g., `set-cookie` or another "safe" subset) to multiple `key=value` headers, using comma as a value separator. 
This requires only a change in istio-proxy. The behavior would be correct based on the new and old RFC (see [rfc2616](https://tools.ietf.org/html/rfc2616#section-4.2)) - assuming my reading of it is correct.
> Multiple message-header fields with the same field-name MAY be present in a message 
> if and only if the entire field-value for that header field is defined as a comma-separated 
> list [i.e., #(values)].  It MUST be possible to combine the multiple header fields into one
> "field-name: field-value" pair, without changing the semantics of the message, by appending
> each subsequent field-value to the first, each separated by a comma.

2. introduce a `override_headers map[string][]string` in the http response protobuf.
If key is specified in both maps (`headers` and `override_headers`), the `override_headers` is used. This requires changes to the istio/api, istio-proxy and istio repositories. Existing adapters continue to work without code changes. Adapters can use the new multi-header, as needed. 

I would prefer the first option for now. The second option has more moving parts.

@kyessenov @lizan @duderino @silentdai - would appreciate your feedback on whether the approach makes sense. If so, I'd be happy to contribute a PR to address this.

**Comment by kyessenov** [comment]
RouteDirective supports appending header values, so you can could use that to add two operations that append two values to the same key. See the documentation https://github.com/istio/api/blob/master/policy/v1beta1/cfg.proto#L162.

For direct HTTP response, have you tried space-separated values in the header map? That _might_ work. Direct HTTP response is translated in Mixer, so we can refine the specification without touching the rest of istio.

**Comment by elevran** [comment]
@kyessenov I'll try space separated values - thanks!

My understanding is that the istio-proxy generates/encodes the HTTP response based on the direct response attributes sent by Mixer. Is this correct? Your response could by understood to mean that the Mixer encodes the actual byte buffer sent to the Web client.

In the use case above, the header values are computed by a mixer adapter that returns the response code and the header values in its direct response. It seems that I would need another handler to compute the secondary value and add RouteDirective to add that to the response.
The issue is that if the values are added to the same key, *and* the header is encoded as multi-value and not multi header (i.e., `set-cookie: a=b,c=d` and not `set-cookie: a=b` and a separate `set-cookie: c=d`) the browser only picks up the first value (`a=b`) from the multi-value header. The enhancement would need to always generate separate headers with the same key (e.g., `set-cookie` in this case).

**Comment by kyessenov** [comment]
@elevran Looking at this issue, I think you are right about the problem with `set-cookie`. Our mechanism for changing headers is left to Envoy. I believe Envoy right now appends a new key-value pair to the header stream if you use the APPEND operation, so it should behave as expected with two rules/handlers adding two headers with the same key. Regarding, the DirectHTTPResponse, this means we do need to extend map[string]string to map[string][]string, _and_ also translate it as a sequence of APPEND operations instead of folding all the values into a single string. This can still be done within Mixer domain since the underlying Mixer-Envoy protocol supports multiple header operations.

**Comment by elevran** [comment]
@kyessenov my understanding of Envoy's code, is that the [following](https://github.com/istio/proxy/blob/e035673263abd92efd1809ac61bb06aa2b94ca39/src/envoy/http/mixer/filter.cc#L131)
 
```cpp
      case ::istio::mixer::v1::HeaderOperation_Operation_APPEND:
           headers.addCopy(LowerCaseString(iter.name()), iter.value());
           break;
``` 
will first find the existing [header key](https://github.com/envoyproxy/envoy/blob/89eb31bcbe2308bf1e9073620e843bf472363495/source/common/http/header_map_impl.cc#L423) then add comma separated values using [appendHeaders](https://github.com/envoyproxy/envoy/blob/89eb31bcbe2308bf1e9073620e843bf472363495/source/common/http/header_map_impl.cc#L298).
So the underlying support for multiple header keys might be currently unsupported in Envoy's code base.

**Comment by elevran** [comment]
Feature request [7488](https://github.com/envoyproxy/envoy/issues/7488) submitted to Envoy proxy repository

**Comment by elevran** [comment]
Following discussion with Alyssa Wilk on Envoy Slack - this is an Istio issue. Will submit a PR
