### ISSUE TITLE
Add watchers for mesh configmap

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1449]
@rshriram commented on [Wed Aug 30 2017](https://github.com/istio/old_pilot_repo/issues/1143)

Istio has a global config map that enables/disables mixer, auth, tracing. We need to watch the global mesh configmap for changes. Users adopting istio incrementally (which is the case in production) will not want to bring down all of istio just to enable mixer or auth or tracing in the mesh configmap. If we watch the configmap for changes and react, we can enable mixer without downtime, turn on or turn off auth without having to reinstall istio, enable or disable tracing.

We need not ship this in the very next pre-release, but we definitely need to ship this in the main release (0.2.x) as many bits of our docs would depend on this feature (showcasing incremental istio adoption).

cc @louiscryan @kelseyhightower (relates to the incremental istio adoption conversation),
cc @kyessenov

**Comment by rshriram** [comment]
@kyessenov is no longer working on this. @costinm / @andraxylia since you folks had some serious concerns on an earlier PR that implemented this feature two months ago (https://github.com/istio/old_pilot_repo/pull/1223), I am assigning this to you so that you can design it in the way you wish to. 

My suggestion would be to dump the config map and use a CRD so that you can take advantage of the watchers we have. But I leave it up to you. Deleting pilot and restarting it is not a viable option for any one eyeing to adopt Istio.

**Comment by sbezverk** [comment]
@andraxylia if this issue is not urgent to fix, I would like to look into it. Could you please point me in the code where you have already implemented CRD watchers.

**Comment by loewenstein** [comment]
Shriram proposed to give this another shot. I have started to look into the code and would like to get some feedback on my current thoughts. 

# Scope
The primary target that Shriram and I agreed upon is feature configuration in Pilot itself, i.e. we do not plan to tackle any sidecar life update (i.e. `ProxyConfig`). Instead we plan to make mTLS, Mixer, ... dynamically configurable.

# Dynamic vs. static config
As a first step we should agree upon what exactly should be dynamic.
Taking a look at https://github.com/istio/vendor-istio/blob/a4eb186992d43abb7cf4d75bf44ca63ffc54da19/istio.io/api/mesh/v1alpha1/config.pb.go#L342-L404

I see the following grouping
1. Mixer config (MixerCheckServer, MixerReportServer, DisablePolicyChecks, MixerAddress, MixerCheck, MixerReport)
1. Proxy configuration (ProxyListenPort, ProxyHttpPort, ConnectTimeout, AccessLogFile, DefaultConfig)
1. Ingress configuration (IngressClass, IngressService, IngressControllerMode)
1. mTLS configuration (AuthPolicy, MtlsExcludedServices)
1. RdsRefreshDelay - is that used at all? I found  https://github.com/istio/istio/blob/4c6004df320d1f4c88f26c13dc74b385c4f49f45/pilot/pkg/proxy/envoy/v1/config.go#L425-L429, but I can't find a reference to `config.RDS. RefreshDelayMs` anywhere in the project.
1. Tracing configuration (EnableTracing, also there is a lot more to tracing, see https://github.com/istio/api/pull/363)

I'd see 1, 3 and 4 as dynamic configuration in scope of this issue. It should allow to dynamically enable/disable mtls, telemetry, ingress and policy from `istio gen-deploy`, also I suppose for telemetry and policy there will be some mixer configuration that is not taken care of in this issue.

For 5 I don't know if that should be dynamic as well.

I suppose 6 should be dynamic but out of scope for this issue. For one the scope this config has to be distributed to is much broader, i.e. the whole data plane in contrast to just the control plane. In addition there is much more to tracing configuration (see PR mentioned above).

The proxy configuration in 5 is anyway not as dynamically configurable without redeployment of the control plane, e.g. `ControlPlaneAuthPolicy` depends on the sidecars of the control plane itself and is currently decided at container launch time (via `--controlPlaneAuthPolicy`). In addition the same configuration distribution problem as for tracing config would apply.

*Should we separate dynamic from static configuration or keep them in the same place?*

# CRD vs. ConfigMap
When we know which configurations have to be dynamic, the next step is deciding on how to do it. There seem to be two different approaches to that:
1. We could move the configuration to CRDs similar to Kuat's approach in https://github.com/istio/old_pilot_repo/pull/1223 
1. We could use fsnotify to watch config map file changes like Jason is doing it in https://github.com/istio/istio/blob/f7a5071331ae73ddf32ef1e60a23c4cf63b95d10/pilot/pkg/kube/inject/webhook.go#L150-L157

Going forward with 1 we will find a lot of infrastructure already in place. Having https://github.com/istio/istio/blob/f7a5071331ae73ddf32ef1e60a23c4cf63b95d10/pilot/pkg/proxy/envoy/v1/discovery.go#L357-L364
we basically have to add `MeshConfig` (or some subset if we decide to split configuration) to `IstioConfigTypes`. 
Some more places need to be hooked up with listeners instead of a static mesh config, but that is not specific to CRD as an approach.

Going forward with 2 we would need to get update infrastructure in place (although we might be able to add config map capabilities to the ConfigStore(Cache) infrastructure to limit the required changes. I suspect config maps provide better scalability, i.e. it update delivery should scale with the number of k8s nodes (instead of the number of listeners).

As far as I see the sidecar injector does only access properties that I would keep static, so if we decide to split configuration we would not need to align pilot and injector code to use the same mechanism for dynamic configuration updates.

# Decisions to be taken
1. Should we split config in static and dynamic parts? (Is my judgement correct concerning static and dynamic parts of MeshConfig?)
1. Should we go for CRD or stay with ConfigMap?

@rshriram @andraxylia @costinm @ayj @kyessenov @douglas-reid What do you think?

**Comment by costinm** [comment]
Thanks for the details ! I will defer to your choices on both decisions,
however I have few additional requirements
regardless of what you chose:

1. For few releases we need to keep reading the existing config map, and
use it if your new config is missing.
Ok to ignore the current config if user explicitly set the new one, but we
have existing users who want to be
able to upgrade.

2. Keep in mind a big requirement for 1.0 is to support per-namespace
overrides for many of the settings
(and per pod/service too - like we have the opt-in for mtls).

3. While I like all settings to be dynamic, some changes - like mtls policy
- would break existing workloads.
We need to be very careful with this.

I would add that both CRD and ConfigMaps can be watched just the same, so
if you go with ConfigMap
you probably don't need to watch the file or make big changes.

**Comment by loewenstein** [comment]
@costinm thanks for the feedback 

> For few releases we need to keep reading the existing config map, and use it if your new config is missing.

how do people usually upgrade? I'd expect  hooking into the installation templates and creating either separate config maps or CRDs would instead of the current single config map should be compatible enough?

> Keep in mind a big requirement for 1.0 is to support per-namespace
overrides for many of the settings

Are there any thoughts on that already other than the requirement itself? 

> While I like all settings to be dynamic, some changes - like mtls policy
- would break existing workloads

I'd expect people knowing what they do (hopefully because they follow documentation on gradual adoption of Istio features) when they activate mTLS in an existing Istio mesh.

**Comment by ayj** [comment]
cc @xiaolanz @ozevren from Config WG

**Comment by ayj** [comment]
I'd like to see this proposal reviewed in the Config WG. Part of that group's focus is on enabling reliable, dynamic control over per-service config (e.g. mtls, telemetry, policy) with considerations for scoping, etc. that overlaps with some of the suggestions in this proposal.

**Comment by xiaolanz** [comment]
We should definitely discuss this during our next week config WG community meeting. It happens 10:15am PST  every Thursday. 

We have discussed the dynamic config and static config over the last a few months. Please see and comment on the [glossary](https://docs.google.com/document/d/1OIKeip1QnZvOe76rrI1glUG6mk1eOfa4JPb-iY92ue4/edit#) and [analysis](https://docs.google.com/document/d/1xztb3S1mKV6iL3DGDzXPq2IbzODpex53ZPa7wTUCZwE/edit#heading=h.x9snb54sjlu9) 

The current plan is to move all "dynamic config" into CRDs. And we are working on Config Model V2 to adding atomic rollout, referential integrity validation features on top of it, and a new configuration service Galley. See the [roadmap](https://docs.google.com/document/d/11xm_dUYVYBbn1b3mQ9XneWRYj05h-hd_29DM8myvoRE/edit)

**Comment by kyessenov** [comment]
Thanks for taking the charge of it! I support the move to CRD which I still
think was a mistake not to merge to begin with.
