### ISSUE TITLE
istioctl version output msg improvement

### ISSUE THREAD

**Issue by linsun** [istio/istio#14594]
```
$ istioctl version
1.2.0-rc.0
Error: unable to find any Istio pod in namespace istio-system
```

i am following instructions here:  https://preliminary.istio.io/docs/setup/kubernetes/getting-started/#downloading-the-release
Istio
Getting Started
Download and install Istio.

how about something like `Warning: Unable to determine server side version - no istio pods in istio-system`?
instead of an error msg

**Comment by linsun** [comment]
@irisdingbj @esnible FYI ^^

**Comment by esnible** [comment]
How about

```
Error: unable to determine control plane version - no Istio pods in namespace "istio-system"
```

I was able to change "Error" into "Warning" but this required changes to the new project _istio/pkg_ and affects the $? / ERRORLEVEL returned by the command.  Working with the `version` subcommand is tricky because it is shared between all the Istio command lines, not just client-side ones.

I will do a PR for _istio/istio_ with the text.  If you wish to change "Error" to "Warning" we will do a follow-up PR in _istio/pkg_.
