### ISSUE TITLE
When istio is upgraded, the pod restarts and cannot be accessed

### ISSUE THREAD

**Issue by springrain** [istio/istio#14659]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
kubectl apply -f istio-demo.yaml When upgrading isito, kubernetes has restart of isito-proxy pod, business interruption access

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

**Expected behavior**
The service can be accessed normally during the upgrade
**Steps to reproduce the bug**
kubectl apply -f istio-demo.yaml
**Version (include the output of `istioctl version --remote` and `kubectl version`)**
client version: version.BuildInfo{Version:"1.1.8", GitRevision:"145b18a441045d6fad33d7916380d8642c7bf21d", User:"root", Host:"11387264-87af-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.7-14-g145b18a"}

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
kubectl create -f istio-demo.yaml
**Environment where bug was observed (cloud vendor, OS, etc)**
os:CentOS Linux release 7.6.1810 (Core) 
kernel:Linux 5.1.3-1.el7.elrepo.x86_64
kubernetes:1.14.3
istio: Upgrade from 1.1.7 to 1.1.8
Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
It isn't clear to me what the problem is. Can you add some logs or `kubectl describe` of the issue?

What pods are restarted and cannot be accessed? It is expected during an update that pods will restart

**Comment by springrain** [comment]
During the update process, the pod is restarted, and the service is temporarily inaccessible. After the pod is restarted, the service can be accessed normally.

**Comment by howardjohn** [comment]
Which pod? The control plane (pilot, galley, mixer, etc) or your applications?

**Comment by springrain** [comment]
My own applications

**Comment by howardjohn** [comment]
When you upgrade istio, the control plane should restart, but your applications should not automatically be restarted. In order to fully complete the update, you should need to manually restart the pods so they get the new proxy image. See https://istio.io/docs/setup/kubernetes/upgrade/steps/#sidecar-upgrade.

Is this not happening? Are the immediately restarted? If so they are probably crashing for some reason? Can you provide the logs for one possibly

**Comment by springrain** [comment]
I did not install helm, use kubectl apply -f istio-demo.yaml to upgrade, I will provide logs as soon as possible

**Comment by springrain** [comment]
https://istio.io/docs/setup/kubernetes/upgrade/steps/#sidecar-upgrade    
Both methods need to install helm, I hope to improve it, do not rely on helm

**Comment by howardjohn** [comment]
The steps should still be the same though, `kubectl apply -f istio-demo.yaml` is the equivalent to the "kubernetes rolling upgrade" tab except you skip the first few steps. But I agree we should improve that

By the way: The demo install is NOT intended for production use. You WILL run into issues if you use it in production. This is why we don't have docs for upgrading using the demo, because you are likely only doing an upgrade if you are using in production. more info at https://istio.io/docs/setup/kubernetes/additional-setup/config-profiles/

**Comment by springrain** [comment]
Because it is included in the istio-demo.yaml, it is convenient and easy for novices to use. I hope that istio-demo.yaml can be used in the production environment.

**Comment by springrain** [comment]
Because istio-demo.yaml contains Addons components, it is convenient and easy for novice users. I hope that istio-demo.yaml can be used in production environments.

**Comment by howardjohn** [comment]
In the next release were are moving to a model where installing the production set up is just as easy as the demo. Until then, I suggest using `helm template`. It is just a few flags to enable kiali, tracing, grafana, etc.

**Comment by springrain** [comment]
Ok, thank you very much for pointing me, I will continue to use and promote istio
