### ISSUE TITLE
ALLOW_ANY mode doesn't send any telemetry data

### ISSUE THREAD

**Issue by linsun** [istio/istio#14664]
In 1.1, we have enabled allow_any mode for accessing external services from a service inside of the mesh.  While this is helping users to get onboard with Istio, one important thing that comes as surprises to many of our users is that in this ALLOW_ANY mode, there is no telemetry data sent from the service inside the mesh to the external services.

this is counter intuitive for our users and not acceptable IMHO.  

@vadimeisenbergibm kindly provided me the docs for this limitation:

https://istio.io/docs/tasks/traffic-management/egress/#envoy-passthrough-to-external-services:

```
This simple approach to access external services, has the drawback that you lose Istio monitoring and control for traffic to external services; calls to external services will not appear in the Mixer log, for example.
```

https://istio.io/docs/tasks/traffic-management/egress/#understanding-what-happened
```
the second approach lets you use all of the same Istio service mesh features for calls to services inside or outside of the cluster. In this task, you learned how to monitor access to external services and set a timeout rule for calls to an external service.
```

**Comment by howardjohn** [comment]
There is some context here: https://github.com/istio/istio/issues/7669 as well

**Comment by rshriram** [comment]
someone needs to setup mixer filter for catch all listener, catch all http conn manager

**Comment by nrjpoddar** [comment]
@linsun the fix for this issue is merged into master so it should make it into release 1.3. However, there are few additional steps that users would need to take to make the metrics show up for Passthrough cluster. I'm interested in knowing your opinion if we should make these defaults or document them, the changes are:

* For any TCP telemetry `destination.ip` needs to be added as a label as when Passthrough cluster is hit, tcp proxy is used and only thing we get is destination IP address.
* For any HTTP telemetry `route.Host` needs to be added as for Passthrough cluster, this attribute contains the original request header.

In both of these cases, `destination_service_name` and `destination_service` labels will be set to `PassthroughCluster` and `destination_service_namespace` would be `unknown`.

**Comment by linsun** [comment]
@nrjpoddar thank you much for taking the time to fixing the issue.  This is a great first step!  

It would be great if these labels can be detected by default so no user action is required.  It would not be intuitive to add these labels and different labels for tcp or http traffic.  Do you also need the values for `destination.ip` or `route.Host`?  For example, I assume you need to not only add the `destination.ip` label but the value of the IPs for tcp.

**Comment by linsun** [comment]
@vadimeisenbergibm @frankbu thoughts?

cc @esnible

**Comment by nrjpoddar** [comment]
@linsun we can easily make these labels default for metrics we provide like `istio_requests_total`, `istio_tcp_connections_opened_total`

`destination.ip` is needed for TCP metrics and yes, that will also work for HTTP. `request.host` is very convenient to have when protocol is HTTP.
