### ISSUE TITLE
Secure Gateways (File Mount) - Multiple-hosts-scenario not working

### ISSUE THREAD

**Issue by jkbschmid** [istio/istio#14695]
**Bug description**
When following the docs for [Secure Gateways (File Mount)](https://preliminary.istio.io/docs/tasks/traffic-management/ingress/secure-ingress-mount/), the segment [configure a TLS ingress for multiple hosts](https://preliminary.istio.io/docs/tasks/traffic-management/ingress/secure-ingress-mount/#configure-a-tls-ingress-gateway-for-multiple-hosts) cannot be followed.

When trying to [redeploy the ingress-gateway](https://preliminary.istio.io/docs/tasks/traffic-management/ingress/secure-ingress-mount/#redeploy-istio-ingressgateway-with-the-new-certificates), the following command fails (after removing an erroneous quotation mark):
```
$helm template $HOME/istio-fetch/istio --name istio --namespace istio-system -x charts/gateways/templates/deployment.yaml --set gateways.istio-egressgateway.enabled=false \
--set 'gateways.istio-ingressgateway.secretVolumes[0].name'=ingressgateway-certs \
--set 'gateways.istio-ingressgateway.secretVolumes[0].secretName'=istio-ingressgateway-certs \
--set 'gateways.istio-ingressgateway.secretVolumes[0].mountPath'=/etc/istio/ingressgateway-certs \
--set 'gateways.istio-ingressgateway.secretVolumes[1].name'=ingressgateway-ca-certs \
--set 'gateways.istio-ingressgateway.secretVolumes[1].secretName'=istio-ingressgateway-ca-certs \
--set 'gateways.istio-ingressgateway.secretVolumes[1].mountPath'=/etc/istio/ingressgateway-ca-certs \
--set 'gateways.istio-ingressgateway.secretVolumes[2].name'=ingressgateway-bookinfo-certs \
--set 'gateways.istio-ingressgateway.secretVolumes[2].secretName'=istio-ingressgateway-bookinfo-certs \
--set 'gateways.istio-ingressgateway.secretVolumes[2].mountPath'=/etc/istio/ingressgateway-bookinfo-certs > \
$HOME/istio-ingressgateway.yaml
Error: stat /User/istio/istio-fetch/istio: no such file or directory
```

After adjusting the path to the istio helm charts ("$HOME/istio-fetch/istio" -> "install/kubernetes/helm/istio") , step 4 in [configure traffic for the bookinfo.com host](https://preliminary.istio.io/docs/tasks/traffic-management/ingress/secure-ingress-mount/#configure-traffic-for-the-bookinfo-com-host) fails with:
```
curl -o /dev/null -s -v -w "%{http_code}\n" -HHost:bookinfo.com --resolve bookinfo.com:$SECURE_INGRESS_PORT:$INGRESS_HOST --cacert bookinfo.com/2_intermediate/certs/ca-chain.cert.pem -HHost:bookinfo.com https://bookinfo.com:$SECURE_INGRESS_PORT/productpage
* Added bookinfo.com:443:130.211.105.61 to DNS cache
* Hostname bookinfo.com was found in DNS cache
*   Trying 130.211.105.61...
* TCP_NODELAY set
* Connected to bookinfo.com (130.211.105.61) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: bookinfo.com/2_intermediate/certs/ca-chain.cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [218 bytes data]
* TLSv1.2 (IN), TLS handshake, Server hello (2):
{ [96 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [1354 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [300 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [37 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
{ [1 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-CHACHA20-POLY1305
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=Denial; L=Springfield; O=Dis; CN=bookinfo.com
*  start date: Jun 11 13:51:16 2019 GMT
*  expire date: Jun 20 13:51:16 2020 GMT
*  common name: bookinfo.com (matched)
*  issuer: C=US; ST=Denial; O=Dis; CN=bookinfo.com
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fa19c006600)
> GET /productpage HTTP/2
> Host:bookinfo.com
> User-Agent: curl/7.54.0
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 404
< location: https://bookinfo.com/productpage
< date: Tue, 11 Jun 2019 13:58:02 GMT
< server: istio-envoy
<
{ [0 bytes data]
* Connection #0 to host bookinfo.com left intact
404
```
Curling httpbin fails as well:
```
curl -v -HHost:httpbin.example.com --resolve httpbin.example.com:$SECURE_INGRESS_PORT:$INGRESS_HOST --cacert httpbin.example.com/2_intermediate/certs/ca-chain.cert.pem https://httpbin.example.com:$SECURE_INGRESS_PORT/status/418
* Added httpbin.example.com:443:130.211.105.61 to DNS cache
* Hostname httpbin.example.com was found in DNS cache
*   Trying 130.211.105.61...
* TCP_NODELAY set
* Connected to httpbin.example.com (130.211.105.61) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: httpbin.example.com/2_intermediate/certs/ca-chain.cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Request CERT (13):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS alert, Server hello (2):
* error:1401E410:SSL routines:CONNECT_CR_FINISHED:sslv3 alert handshake failure
* stopped the pause stream!
* Closing connection 0
curl: (35) error:1401E410:SSL routines:CONNECT_CR_FINISHED:sslv3 alert handshake failure
```
All troubleshooting steps mentioned in the docs are successful, but do not solve the problem.

**Expected behavior**
Curls succeed.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-07T09:55:27Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:45:25Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```
Istio version: 1.2.0-rc.0

**How was Istio installed?**
```
kubectl apply -f install/kubernetes/istio-demo.yaml
```

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

**Comment by JimmyCYJ** [comment]
I have repeated this set up and test against 1.2.0-rc.0.
The request to productpage fails with 404, but the request to httpbin still succeeds.

I turn on trace level log at ingress gateway proxy, and issue curl command again. It shows that the SSL handshake is finished, Envoy proxy sends a Mixer Check call, wait for the Check response, and then immediately sends 404 back.
Here is the related piece of log. It looks like the Mixer Check decides to return 404 because quota is not available.
[2019-06-11 23:07:19.638][25][debug][filter] [src/istio/mixerclient/check_cache.cc:163] Add a new Referenced for check cache: Absence-keys: destination.port, destination.uid, source.ip, Exact-keys: context.protocol, context.reporter.kind, source.namespace, source.uid, 
[2019-06-11 23:07:19.638][25][debug][filter] [src/istio/mixerclient/client_impl.cc:263] CheckResult transport=OK, policy=OK, quota=NA, attempt=0
[2019-06-11 23:07:19.638][25][debug][filter] [src/envoy/http/mixer/filter.cc:162] Called Mixer::Filter : check complete OK
[2019-06-11 23:07:19.638][25][trace][http] [external/envoy/source/common/http/conn_manager_impl.cc:1640] [C14][S2991863874130813356] continuing filter chain: filter=0x2dd3680
[2019-06-11 23:07:19.638][25][trace][http] [external/envoy/source/common/http/conn_manager_impl.cc:833] [C14][S2991863874130813356] decode headers called: filter=0x3205860 status=0
[2019-06-11 23:07:19.638][25][trace][http] [external/envoy/source/common/http/conn_manager_impl.cc:833] [C14][S2991863874130813356] decode headers called: filter=0x3205900 status=0
[2019-06-11 23:07:19.638][25][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:1137] [C14][S2991863874130813356] Sending local reply with details direct_response
[2019-06-11 23:07:19.638][25][trace][http] [external/envoy/source/common/http/conn_manager_impl.cc:1224] [C14][S2991863874130813356] encode headers called: filter=0x3205630 status=0
[2019-06-11 23:07:19.638][25][trace][http] [external/envoy/source/common/http/conn_manager_impl.cc:1224] [C14][S2991863874130813356] encode headers called: filter=0x2d7d810 status=0
[2019-06-11 23:07:19.638][25][debug][filter] [src/envoy/http/mixer/filter.cc:141] Called Mixer::Filter : encodeHeaders 2
[2019-06-11 23:07:19.638][25][trace][http] [external/envoy/source/common/http/conn_manager_impl.cc:1224] [C14][S2991863874130813356] encode headers called: filter=0x3149c20 status=0
[2019-06-11 23:07:19.638][25][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:1329] [C14][S2991863874130813356] encoding headers via codec (end_stream=true):
':status', '404'
'location', 'https://bookinfo.com/productpage'
'date', 'Tue, 11 Jun 2019 23:07:19 GMT'
'server', 'istio-envoy'

**Comment by JimmyCYJ** [comment]
The log in bold indicates that the Proxy sends local response which is 404. I check the mixer client code and confirm that this 404 is not sent by mixer client. It is sent from Envoy internally.
I attached the config dump of ingress gateway, find that the route config has the setup of 404. Not clear if that is the reason.

In the bookinfo filter chain, the rds config is like this
           "rds": {
            "route_config_name": "https.443.https-bookinfo.bookinfo-gateway.default",
            "config_source": {
             "ads": {},
             "initial_fetch_timeout": "0s"
            }
           },

The corresponding rds config that match "https.443.https-bookinfo.bookinfo-gateway.default" is here
   "dynamic_route_configs": [
    {
     "version_info": "2019-06-11T22:51:55Z/22",
     "route_config": {
      "name": "https.443.https-bookinfo.bookinfo-gateway.default",
      "virtual_hosts": [
       {
        "name": "blackhole:443",
        "domains": [
         "*"
        ],
        "routes": [
         {
          "match": {
           "prefix": "/"
          },
          "direct_response": {
           "status": 404
          },
          "per_filter_config": {
           "mixer": {}
          }
         }
        ]
       }
      ],
      "validate_clusters": false
     },
     "last_updated": "2019-06-11T22:51:56.898Z"
    },

**Comment by JimmyCYJ** [comment]
[config_dump.txt](https://github.com/istio/istio/files/3278987/config_dump.txt)

**Comment by JimmyCYJ** [comment]
@fpesce could you ask networking team to take a look?

**Comment by JimmyCYJ** [comment]
[ingressgateway-log.txt](https://github.com/istio/istio/files/3279026/ingressgateway-log.txt)
[pilot-log.txt](https://github.com/istio/istio/files/3279027/pilot-log.txt)

**Comment by JimmyCYJ** [comment]
Envoy log(ingressgateway-log.txt) shows that there are many attempts to fetch type.googleapis.com/envoy.api.v2.RouteConfiguration but get failed. I also attached pilot-log.txt, but I don't know how to find the corresponding logs at Pilot side.

```
[2019-06-11 23:53:30.844][18][debug][config] [external/envoy/source/common/config/grpc_mux_subscription_impl.cc:70] gRPC update for type.googleapis.com/envoy.api.v2.Listener failed
  41490 [2019-06-11 23:53:30.844][18][debug][config] [external/envoy/source/common/config/grpc_mux_subscription_impl.cc:70] gRPC update for type.googleapis.com/envoy.api.v2.RouteConfiguration failed
  41491 [2019-06-11 23:53:30.844][18][debug][config] [external/envoy/source/common/config/grpc_mux_subscription_impl.cc:70] gRPC update for type.googleapis.com/envoy.api.v2.RouteConfiguration failed
  41492 [2019-06-11 23:53:30.844][18][debug][config] [external/envoy/source/common/config/grpc_mux_subscription_impl.cc:70] gRPC update for type.googleapis.com/envoy.api.v2.Cluster failed
  41493 [2019-06-11 23:53:30.844][18][debug][config] [external/envoy/source/common/config/grpc_mux_subscription_impl.cc:70] gRPC update for type.googleapis.com/envoy.api.v2.ClusterLoadAssignment failed
  41494 [2019-06-11 23:53:30.844][18][debug][config] [external/envoy/source/common/config/grpc_mux_subscription_impl.cc:70] gRPC update for type.googleapis.com/envoy.api.v2.ClusterLoadAssignment failed
  41495 [2019-06-11 23:53:30.844][18][debug][config] [external/envoy/source/common/config/grpc_mux_subscription_impl.cc:70] gRPC update for type.googleapis.com/envoy.api.v2.ClusterLoadAssignment failed
```

**Comment by wattli** [comment]
Thanks Jimmy for the investigation! The TLS handshake actually finished successfully.

Reassign back to @fpesce since it's the error on pilot RouteConfiguration

**Comment by philrud** [comment]
The referenced doc contains the following errors:

1. As mentioned above, path to Istio charts indeed needs to be adjusted ```$HOME/istio-fetch/istio -> install/kubernetes/helm/istio```
2. VirtualService definition for the bookinfo service has a typo in the gateway name ```httpbin-gateway -> bookinfo-gateway```. This is what's causing 404 (referenced gateway doesn't exist, so the behavior is correct).
3. The last curl to httpbin is missing key&cert flags. At this point httpbin gateway has mTLS enabled, that's why handshake fails (again correct behavior).

With those issues fixed the rest of the example works as expected, so this is docs issue only. I'll follow up with a PR against the docs repo.
