### ISSUE TITLE
Prow running old images in integration tests

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#14717]
Last 4 test runs are failing at https://testgrid.k8s.io/istio-presubmits-release-1.2#integ-security-k8s-presubmit-tests&width=20

Examples:
https://prow.k8s.io/view/gcs/istio-prow/pr-logs/directory/integ-security-k8s-presubmit-tests-release-1.2/104
https://prow.k8s.io/view/gcs/istio-prow/pr-logs/directory/integ-security-k8s-presubmit-tests-release-1.2/105
https://prow.k8s.io/view/gcs/istio-prow/pr-logs/directory/integ-security-k8s-presubmit-tests-release-1.2/106

**Comment by yangminzhu** [comment]
Another example is here: https://github.com/istio/istio/pull/14591#issuecomment-501407971

**Comment by howardjohn** [comment]
The weird thing is we get these clumps of successes: https://testgrid.k8s.io/istio-presubmits-release-1.2#integ-security-k8s-presubmit-tests

Normally the flakes are like every other test fails, but this we get 10 fails then 5 success.

**Comment by howardjohn** [comment]
So the logs are missing "Failed to create a self-signed Citadel" but have "Failed to write secret to CA"

Looking at the logs I saw `		2019-06-12T19:35:49.528237Z	error	Failed to write secret to CA (error: secrets "istio-ca-secret" already exists). This CA will not persist when restart.` which is what the error said until ~1 day ago when this test was added: https://github.com/istio/istio/commit/6efd5850fa52e94326907dcb3b1cdb37d65c2966

I looked at the git tree for one where it always fails and see this PR is NOT in the tree. See https://github.com/istio/istio/commits/93e831745e013fc0e7ef6e9f9e14203f3e6ec3de

So somehow, I have a PR that is created before this other change that includes a code change + test, and prow is running the new test but not the new code? The fact that it is picking up the new test isn't that weird, since prow does rebase before testing -- what is weird is it picks up the test but not the code.


My theory:
1. Due to https://github.com/istio/istio/pull/14351, the image is built with the changes in the original PR
2. THEN prow rebases the test (and the code!)
3. The tests run with the image running old code, leading to this problem

I am not sure if that theory is correct but I think we can say this is not a bug in real code, but an issue with our testing.

cc @fpesce 


It seems we build images like `SHA-test.integration.framework.kube.presubmit` but then are running images in the form of `SHA`. Could be related? See [this build](https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/14591/integ-security-k8s-presubmit-tests-release-1.2/131/build-log.txt), we pass `--istio.test.tag=e58133f2df179cd03680ede17e38a9167df34641`.

@icygalz any ideas

**Comment by icygalz** [comment]
release-1.2 shouldn't be affected by https://github.com/istio/istio/pull/14351 because that PR is only for master. We didn't cherry pick it to release-1.2 so the images will be built only with istio.test.tag=sha and the test will also use that tag.

Only master branch has BUILD and test for each test. Release-1.2 is still using the old logic; only 1 BUILD and test are re-using the created images.

**Comment by howardjohn** [comment]
I see. Does the image get built before the rebase logic then?

**Comment by icygalz** [comment]
For release-1.2 branch, the image gets built during istio-presubmit.sh test. That test will be run after the rebase. So the image should be built after the rebase and all other tests which depends on these images will only get started AFTER istio-presubmit.sh succeed.

**Comment by icygalz** [comment]
I am not sure whether this is the same issue or not but AFAIK, that test on master branch was failing when we first created the branch. If you remember this issue https://github.com/istio/istio/issues/14364. Seems like the same issue?

**Comment by howardjohn** [comment]
@icygalz the tests are grouped into one target but (should) be completely distinct from each other.

My two new theories: when PR is submitted, image is created and all is good. Then when the new test is merged:
1. a new image is NOT made because it already exists (same tag as the first test run)
2. or a new image is made, but prow caches the image and uses the old one (if imagePullPolicy is set to IfNotPresent on the cluster then this is possible)

**Comment by icygalz** [comment]
if theory 1 is true then we are really in a bad shape. It means we are not testing anything during merge. We can check istio-presubmit.sh logs to see if it pushed new images or not.

theory2 is highly unlikely because each prow/*.sh test rent out a new boskos resource. The cluster(s) inside newly rented boskos resource are new/unused so it is unlikely for those clusters to have any istio images cached. After the test is done, the test will return their rented boskos resources and the clusters inside that rental will be destroyed.


in one of you comment above:
"So somehow, I have a PR that is created before this other change that includes a code change + test, and prow is running the new test but not the new code? "
Can we track down this "code change + test" PR and make sure the "code change" exists in release-1.2?

**Comment by howardjohn** [comment]
Here is the PR https://github.com/istio/istio/pull/14704. If we browse the tree at this point we see: https://github.com/istio/istio/commits/93e831745e013fc0e7ef6e9f9e14203f3e6ec3de.

A commit immediately after this PR was created was merged, https://github.com/istio/istio/commit/6efd5850fa52e94326907dcb3b1cdb37d65c2966. Note that the tree I posted above does NOT have this change in it. This change adds a test, and changes a log statement.

Now when the tests run for PR #14704, it runs the test (which does not exist in the PR, so it must be getting it from rebasing). Yet if you look in the logs, it does not pick up the changes to the log statement which are made in the same PR. Therefor, the images that it is testing and the test are out of sync.

Does that make sense? It is a bit convoluted

**Comment by icygalz** [comment]
So i talked with Prow/tide experts and the culprit is highly likely to be: "run_after_success" mechanism.

We build the images as part of istio-presubmit test and all other tests will only be starter after istio-presubmit test pass. Each test will create a git clone/checkout with base_branch and the changes on that PR.

so let's call:
PR #14704 --> PRa
https://github.com/istio/istio/commit/6efd5850fa52e94326907dcb3b1cdb37d65c2966   --> PRb

This is the failing test on PRa:
https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/14697/integ-security-k8s-presubmit-tests-release-1.2/141/build-log.txt

this is the corresponding checkout/clone log for failing test:
https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/14704/integ-security-k8s-presubmit-tests-release-1.2/137/clone-log.txt

From that clone log, we see that the base_branch is https://github.com/istio/istio/commit/b3ab248bbe9b46527321576e4ee887c377c0bef2  which includes PRb. and  https://github.com/istio/istio/pull/14704/commits/93e831745e013fc0e7ef6e9f9e14203f3e6ec3de is the current head commit of PRa and is what is merged into the base branch.

so it made sense that integ-security-k8s-presubmit-tests-release-1.2 has the PRb code BUT the one that is building and pushing the image is not integ-security-k8s-presubmit-tests-release-1.2 .
It is entirely possible for the base_branch to be different for istio-presubmit and integ-security-k8s-presubmit-tests-release-1.2 and it will be resulting in this issue...
re-triggering istio-presubmit.sh test will solve this issue.

This is also one of the reason why prow got rid of "run_after_success" in the head binary...

**Comment by myidpt** [comment]
The findings here makes sense to me (though I don't know the details of how the testing system picks up the versions).
Seeing the failing test on PRa:
https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/14697/integ-security-k8s-presubmit-tests-release-1.2/141/build-log.txt
The log `This CA will not persist when restart` exists, but it's actually removed by https://github.com/istio/istio/commit/6efd5850fa52e94326907dcb3b1cdb37d65c2966.
I see now the test isn't flaky since yesterday. I guess it's because the Citadel version being tested caught up.
Guys from testing team, please feel free to assign and let me know if I can help here.

**Comment by howardjohn** [comment]
Rescoped the issue to general prow issue, the citadel one was just a symptom of the problem as you mentioned

**Comment by howardjohn** [comment]
We no longer have run after success - images are built in each test, so I don't think this is an issue. The only problem could be if we don't have image pull policy Always and it pulls the old version, but I don't think this is a problem. Closing this now as it should be impossible to happen now
