### ISSUE TITLE
TestMTLSGateway test failure

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#14721]
https://testgrid.k8s.io/istio-presubmits-master#integ-security-k8s-presubmit-tests&width=20

Example failures:

* https://prow.k8s.io/view/gcs/istio-prow/pr-logs/directory/integ-security-k8s-presubmit-tests-master/1585
* https://prow.k8s.io/view/gcs/istio-prow/pr-logs/directory/integ-security-k8s-presubmit-tests-master/1586
* https://prow.k8s.io/view/gcs/istio-prow/pr-logs/directory/integ-security-k8s-presubmit-tests-master/1584
* https://prow.k8s.io/view/gcs/istio-prow/pr-logs/directory/integ-security-k8s-presubmit-tests-master/1572

**Comment by JimmyCYJ** [comment]
This is a test flakiness, not a production failure. I will fix the test, but I think it is not a P0.

**Comment by howardjohn** [comment]
It is also blocks other PRs due to failures though. If we are sure its not a bug in real code, and it isn't something easy to fix maybe it could be disabled for presubmit (by adding "flaky" label)?

**Comment by JimmyCYJ** [comment]
I will add a flaky label first and then make it stable. Thanks! @howardjohn

**Comment by howardjohn** [comment]
No problem. Is the test new or was it passing fine before? Just want to make sure we don't hide a problem that is a real bug

**Comment by JimmyCYJ** [comment]
They are new tests, and it were passing when I run the presubmit test. It is the test framework or test set up issue.

**Comment by fpesce** [comment]
@JimmyCYJ it looks like the #14729 automatic cherrypick of #14728 failed, and you'll have to manually cherrypick it on 1.2 branch.

**Comment by JimmyCYJ** [comment]
The tests are not in release 1.2 branch. The PR https://github.com/istio/istio/pull/14307 is not in release cut.
Maybe we don't need to cherry pick this one.

**Comment by JimmyCYJ** [comment]
Currently, the test creates k8s secret and sleep 30s by assuming that it takes less than 30s for gateway agent to pick the k8s secret, and provide key/cert to ingress gateway via SDS, and ingress gateway SDS will update its ssl socket factory to use the new key/cert pair. Apparently, 30s is not sufficient. 
To fix this flakiness, one option is to check ingress gateway /stats endpoint, especially this counter  listener.<LISTENER_IP>.server_ssl_socket_factory.ssl_context_update_by_sds. If the counter has updated, then let the test to send request to the ingress gateway. 

But many stats are not enabled for Istio proxy due to CPU and memory cost. I have filed https://github.com/istio/istio/issues/14773, as the stats are useful for testing, debugging and monitoring.

**Comment by howardjohn** [comment]
Checking the gateway directly is probably the best approach, much better than a time based wait since often times they pass locally and fail in prow or circle. Too bad config_dump doesn't have SDS stuff. Is it in `http://localhost:15000/certs`? If not the stats approach discussed in #14773 should work

**Comment by JimmyCYJ** [comment]
@howardjohn That is a good question. Currently, http://localhost:15000/certs does not differentiate certs fetched by SDS and certs fetched by file mount. It has limited information such as expiration date, and that is not a direct signal to differentiate dynamic certs and file mounted certs. We have filed https://github.com/envoyproxy/envoy/issues/7111 to make improvements at Envoy side. But stats are also important and adding them will help to fix the flaky tests.

**Comment by howardjohn** [comment]
@JimmyCYJ after re-enabling they are still flaky it seems

https://prow.k8s.io/view/gcs/istio-prow/logs/integ-security-k8s-postsubmit-tests-master/550

https://prow.k8s.io/view/gcs/istio-prow/logs/integ-security-k8s-postsubmit-tests-master/547

**Comment by JimmyCYJ** [comment]
The requests passed. first request got 200, after secret rotation, the second request got 0 because it used old key/cert and handshake failed as expected, the third request picked new key/cert and got 200.
The test failed at this check "single_mtls_gateway_compound_secret_test.go:57: total active listener stats does not match: active listener stats does not meet expection in 30s: Expected 2, Last stats: 1"
That indicates number of active listeners do not meet expected number within 30s, but the https listener handled requests properly after that. It would be a timing issue, maybe the listener is up and active soon after the 30s listener check.
I will deflake the tests.

**Comment by JimmyCYJ** [comment]
The proxy log shows this error "listener '0.0.0.0_443' failed to listen on address '0.0.0.0:443' on worker", that is why 443 listener takes longer to be active, and the verification of Envoy stats failed with timeout.
