### ISSUE TITLE
User process listen to pod ip result to traffic failure

### ISSUE THREAD

**Issue by zhongfox** [istio/istio#14738]
**Bug description**
in data panel, the final `socket_address` of inbound xds is `127.0.0.1`,  generated by pilot.
it works if user process listen to `0.0.0.0`
but some case, user process listen to the specific pod ip, the traffic route will not work.

**Affected product area**
- [x] Networking

**Expected behavior**
server which listen to pod ip should get traffic from istio proxy pellucidly.  

see discuss: https://discuss.istio.io/t/user-process-listen-to-pod-ip-result-to-traffic-failure/2643

**Comment by sdake** [comment]
From Slack:
```
we should get this solved if there is a viable solution.  Could you file a defect?  One of the challenges of using pod ips all the time for lds is that pod ips change…  0.0.0.0 doesn[t.  I hear you though re the wildcard binds, they are inherently insecure (although not in the way we use them in Istio).  As wildcard bind mounts are insecure in the general case, alot of software doesn’t permit wildcard bind mounting at all.
```

**Comment by zhongfox** [comment]
I made a experimental change, finally make it work, summary:

1. use pod ip to generate inbound end socket address, see: https://github.com/zhongfox/istio/commit/dd0ef4e02f5661b4448d63c55ddcb9d86fe3ee34
2. change pod iptables of initContainer, remove first rule of Chain ISTIO_OUTPUT:
   ```
   ISTIO_REDIRECT  all  --  any    lo      anywhere            !localhost.localdomain
   ```
though it's not thoughtful patch yet, it may be done in similar way.

**Comment by esnible** [comment]
This seems to be a duplicate of (or related to) https://github.com/istio/istio/issues/13906 ; should we close this one and move the discussion there?

See also https://github.com/istio/istio/issues/6029

We should document this problem under https://istio.io/help/ops/traffic-management/troubleshooting/ because I have also been bitten by this.  @frankbu Should I open a work item for documentation?  This is what I tell people when they suspect this problem:

"`kubectl exec -it <pod> -c istio-proxy bash` to get into your service.  Once in, test it in the usual way for the service it offers, for example `curl localhost:5984/_all_dbs`.  Localhost connections should not be affected by Istio. Because your service and its sidecar share a single network talking to localhost is not affected by Istio.  If your application cannot talk on localhost because it explicitly binds listening sockets to an IP address it will not work under Istio.  If localhost connections don't work, run `netstat -tulpn` and make sure the *Local Address* is 0.0.0.0 or 127.0.0.0 for all listeners. Applications that explicitly listen on their external address (e.g. 10.233.98.142) will not work under Istio. This is because the Envoy proxy traffic does not come from off-pod and will appear to your application as if it arrived via localhost."

**Comment by frankbu** [comment]
So, is there anything that can be done to fix this? If not, I suggest we add an entry in the operations guide troubleshooting section. @esnible, can you help to put something together?

**Comment by esnible** [comment]
@frankbu I propose https://github.com/istio/istio/issues/14738 covers fixing this.  I propose to create an Issue in https://github.com/istio/istio.io to add an entry about listening on 0.0.0.0 to the https://istio.io/docs/setup/additional-setup/requirements/ page.  Do you agree?

**Comment by zhongfox** [comment]
@frankbu @esnible this issue is still unsolved, right? shall we add some doc to requirements page? like esnible said.
