### ISSUE TITLE
Istio log entry Integer/Double value for Latency(response.duration)

### ISSUE THREAD

**Issue by xDouglasx** [istio/istio#14907]
Hi, i'm trying to use istio logs to create alerts on CGP, doing well so far for all alerts, but i facing some problems to create alerts based on latency field.

apiVersion: "config.istio.io/v1alpha2"
kind: logentry
metadata:
  name: accesslog
  namespace: istio-system
spec:
  severity: '"Default"'
  timestamp: request.time
  variables:
    sourceIp: source.ip | ip("0.0.0.0")
    destinationIp: destination.ip | ip("0.0.0.0")
    sourceUser: source.principal | ""
    method: request.method | ""
    url: request.path | ""
    protocol: request.scheme | "http"
    responseCode: response.code | 0
    responseSize: response.size | 0
    requestSize: request.size | 0
    latency: response.duration | "0ms"
  monitored_resource_type: '"UNSPECIFIED"

As showed above latency is a String formatted as "3.4543ms", and it turns out kind useless when creating filters in stackdriver, because you cant create Thresholds based on a string.

i went through the code on istio-telemetry and mixer.
You guys are using the type "DURATION" on the values.yml and the filed is also a duration on golang files. my question is, there is  way to easily change the latency to double or integer when configuring a log entry? if no, i think would be way better have this field as numeric type for logging analysis.

**Comment by bianpengyuan** [comment]
Could you try to use `latency` field in [httpRequest](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry#HttpRequest)? SD should be able to interpret it as duration string. Config wise It needs an extra mapping in stackdriver handler. See an example config here: https://github.com/istio/istio/blob/release-1.1/mixer/adapter/stackdriver/operatorconfig/stackdriver.yaml#L56-L94

**Comment by xDouglasx** [comment]
Sorry, i don't see how it would help me, first because we should use the latency of the response, and second because the logs is already written and collected on Stackdriver, and i'm using the advance filters to filter when the latency is above 1000ms for example, but i cant use mathematical operator on an string, so i cant create thresholds, if the format was 1000 for example it would be way more simple. and i can't see any useful use case for having the format "1000ms". 

but maybe i got you wrong

**Comment by bianpengyuan** [comment]
@xDouglasx I mean you could update your stackdriver handler config following the [example](https://github.com/istio/istio/blob/release-1.1/mixer/adapter/stackdriver/operatorconfig/stackdriver.yaml#L56-L94) to populate the latency field in [httpRequest](https://github.com/istio/istio/blob/release-1.1/mixer/adapter/stackdriver/operatorconfig/stackdriver.yaml#L56-L94). Essentially this will make stackdriver adapter to send latency with duration type instead of a  string label: 
https://github.com/istio/istio/blob/a8a573b8a5a079e216b83e131ef5580280de6e07/mixer/adapter/stackdriver/log/log.go#L285-L288
and I think stackdriver should be able to duration comparison with the value provided in that field.
