### ISSUE TITLE
Needles ports in Envoy configuration in virtual host domains

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#14992]
Remove hosts:port in the domains generation.
Virtual host matching in Envoy does not consider port. Port matching is performed at the Listener and FilterChainMatch stage. By the time Envoy processes RouteConfiguration, the port is ignored.

Example:

"route_config": {

   "name": "9080",

   "virtual_hosts": [

    {      

      "name": "ratings.default.svc.cluster.local:9080",

        "domains": [

         "ratings.default.svc.cluster.local",

         "ratings.default.svc.cluster.local:9080",   *** to be removed

         "ratings",

         "ratings:9080",  *** to be removed

         "ratings.default.svc.cluster",

         "ratings.default.svc.cluster:9080", *** to be removed

         "ratings.default.svc",

         "ratings.default.svc:9080", *** to be removed

         "ratings.default",

         "ratings.default:9080", *** to be removed

         "10.0.9.203",

         "10.0.9.203:9080" *** to be removed

        ],
....

**Comment by silentdai** [comment]
Thank you for creating this. I list the main blockers here. I have less knowledge at istio flows and use cases so please add what's missing.

[x] Split inbound capture port and outbound capture port
[ ] Better LDS: the ability to drain partial of the filterchains(currently envoy could only drain a full listener). A milestone of FilterChainDiscoveryService
[ ] Use separate `FilterChainMatcher` for inbound and outbound listener. Motivation: Avoid share not-bind-to-port listeners. Align with the goal of deprecating these listener spec at envoy community.

Alternative solutions: Below are not designed to resolve the issue here but could be utilized to solve.
k8s-CNI. Protocol-sniff.

**Comment by howardjohn** [comment]
@andraxylia does envoy actually completely ignore the port?

* If you have `domains: [ foo.com ]` and I send `curl foo.com -H "Host foo.com:80"` will it match?
* If you have `domains: [ foo.com:9090 ]` and I send `curl foo.com -H "Host foo.com:80"` will it match?

**Comment by andraxylia** [comment]
Related to envoyproxy/envoy#886

**Comment by howardjohn** [comment]
Thanks Andra, it sounds like the port is still required from that though?

**Comment by hzxuzhonghu** [comment]
The port is required, otherwise `curl foo.com -H "Host foo.com:80` will fail

**Comment by PiotrSikora** [comment]
> * If you have `domains: [ foo.com ]` and I send `curl foo.com -H "Host foo.com:80"` will it match?

No.

> * If you have `domains: [ foo.com:9090 ]` and I send `curl foo.com -H "Host foo.com:80"` will it match?

No.

The port is required (Envoy performs exact match against `Host` / `:authority` headers), but please leave the port-less virtual host as well, since reverse proxies usually don't append port to the `Host` header, so you might see `Host: foo.com` on port `9090`.
