### ISSUE TITLE
ci: TestCheckCoverage cannot open or parse report file: /go/out/codecov/pr/coverage.html, bufio.Scanner: token too long

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#15060]
cf. https://circleci.com/gh/istio/istio/448696?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by elevran** [comment]
@kyessenov could this be intermittent due to some environmental issue (e.g., low resources on the CircleCI machines)?
I've downloaded the artifacts from the [above failed test](https://circleci.com/gh/istio/istio/448696#artifacts/containers/0) and they pass just fine locally:
```sh
$ go run ./tests/codecov/main.go -report_file ./out/codecov/pr/coverage.html -baseline_file ./out/codecov/baseline/coverage.html -threshold_files ./out/codecov/codecov.threshold 
$ echo $?
0
```
 
The files all seem to have properly terminated new lines and subsequent runs of the same pass.
Further, the code sets the `Scanner.Buffer()` to 32KB initial and 512KB max.
We can set this to be arbitrary larger (e.g., the `coverage.html` in the test is ~13M, so an initial buffer of 32M out to either fail fast or work successfully if the problem is resources... The machine spec says 16GB so this is likely not the case, but some other flake issue)
