### ISSUE TITLE
Update builds to use Go modules

### ISSUE THREAD

**Issue by ericvn** [istio/istio#15093]
We have updated the _master_ branch to use Golang 1.12.5 for builds and testing.

Our builds/tests continue to use Golang _vendor_ing because we build on the GOPATH.

This issue is move to using Go modules and not use the _vendor_ directory (and it could be removed).

Note: this issue is created based on a discussion with @geeknoid about what needs to be done to get to Go modules.

**Comment by ericvn** [comment]
A first step to see where we are is to create a new Istio-builder image where GO111MODULE is set to on (will force module usage even on the GOPATH) https://github.com/istio/test-infra/pull/1370

Once this image is created, the test-infra yaml for the prow-staging branch can be updated to use the image and we can see what additional changes are required.

Note that other issues are needed to finish this work:
  https://github.com/istio/istio/issues/14795
  https://github.com/istio/istio/issues/14475

**Comment by ericvn** [comment]
Note that there is discussion on this within #14795 as well.

**Comment by hzxuzhonghu** [comment]
We could not assume every user can access the vendor pkgs very easily. Take me as an example, i can not access k8s.io, gcr.io, etc, directly.

**Comment by hzxuzhonghu** [comment]
#15056 added vendor check in ci

**Comment by ericvn** [comment]
PR #15166 uses an Istio-builder image which set GO1111MODULE=on as a test in the _prow-staging_ branch.

**Comment by qfel** [comment]
Note that there are some places doing hacky stuff with paths (like computing GOPATH from something istio-specific instead of $(go env GOPATH), putting istio-specific stuff under GOPATH and using all that to locate other things like test data). If you just enable GO111MODULE but don't get rid of dependencies on GOPATH from scripts and code, it may work correctly by accident but start doing weird things as soon as somebody decides to move the Go module somewhere else (because, why not? Go modules are supposed to work from anywhere on the file system..).

All that is to say to setting GO111MODULE is a step forward, but alone it may leave us in a more brittle state so if we're going to do it we should commit to eradicating GOPATH dependencies.

**Comment by howardjohn** [comment]
Done by https://github.com/istio/istio/pull/16668. Thanks for all the work from @ericvn and @geeknoid to allow me press to easily press the `rm -rf vendor` button
