### ISSUE TITLE
Pilot agent to detect certificate provider and inform pilot.

### ISSUE THREAD

**Issue by costinm** [istio/istio#15168]
**Describe the feature request**
Pilot-agent should detect:

- if the mounted SDS UDS path is present
- if secrets exist under /etc/certs

and communicating this information to Pilot. 

A new values.yaml option will control the behavior if neither UDS path nor certs are present - if set to 'FAIL' it will immediately exit, so the error can be detected and the pod possibly re-scheduled, or 'PLAINTEXT' in which case pilot will generate a config not using certificates ( similar with cases where security is not enabled). 

In no case should we start envoy with a config referencing secrets or UDS socket when the secrets/UDS are missing - this results in obscure, hard to detect errors - typically taking very long to crash due to readiness failures. We need to either fail fast, or use plain text if certs are not available - not be in a limbo state.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by costinm** [comment]
Also: the presence of the k8s token must be checked. Both UDS socket and k8s token are required to enable SDS.

**Comment by esnible** [comment]
What is the plan for reporting the error to the user?

In addition to crashing can we generate a K8s Event so that `kubectl describe` will show why the pod is being continuously rescheduled?

If Pilot generates config without certificates will communication work?  (I assume communication will all fail with 503s.)  How will users diagnose the difference between a 503 caused by Pilot skipping the certificate config vs other reasons?

**Comment by JimmyCYJ** [comment]
About checking the UDS path, I have already filed a feature request on adding SDS prober in https://github.com/istio/istio/issues/15096
