### ISSUE TITLE
Bad environment variables in proxy lead to misleading metadata

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio#15229]
**Bug description**

There are some bad values for ENV vars for the proxy images:
- `ISTIO_PROXY_VERSION` is hardcoded to `"1.1.3"` (https://github.com/istio/istio/blob/master/pilot/docker/Dockerfile.proxyv2#L44)
- `ISTIO_VERSION` is set to `$istio_version`, which comes from `$VERSION` in the `Makefile`, which defaults to `"1.0-dev"` (https://github.com/istio/istio/blob/master/Makefile#L23)

If I build a `proxyv2` image from HEAD and inspect the metadata, I see:

```json
...
"bootstrap": {
  "node": {
     "metadata": {
         "ISTIO_PROXY_VERSION": "1.1.3",
         "ISTIO_VERSION": "1.0-dev"
     }
   }
}
```

This information is incorrect.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ X ] Networking
[ ] Performance and Scalability
[ X ] Policies and Telemetry
[ ] Security
[ X ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

If there is metadata being collected, it should be accurate. We probably also should not have two different ways of reporting the same information.

**Steps to reproduce the bug**

Build a proxy image and use it.

**Comment by howardjohn** [comment]
Some more context, my understanding is that:

`ISTIO_PROXY_VERSION` is used as the "proxy capabilities version". In the code we check for this var to determine what the proxy can do (can it serialize `Any` types? etc).

`ISTIO_VERSION` is the actual istio version. While this is 1.0-dev when you build it, in the actual releases this (should) be correct.

It is a common source of confusion though. In 1.2 we switched `istioctl ps` to show ISTIO_VERSION instead of ISTO_PROXY_VERSION.

**Comment by howardjohn** [comment]
Fixed by https://github.com/istio/istio/pull/15886
