### ISSUE TITLE
Makefile needs cleanup

### ISSUE THREAD

**Issue by ostromart** [istio/istio#15237]
The current makefile needs some TLC. In particular:
- vfsgen should have dependencies on data/
- go generate should be fixed
Generally tidy it up and make consistent with istio.io.

**Comment by ayj** [comment]
@elfinhe will be working on this

**Comment by elfinhe** [comment]
@ostromart need some help to clarify this task:
1. The ultimate goal of this task is to use `make` instead of `go build -o $GOPATH/bin/iop ./cmd/iop.go`, include all deps and `go generate` used by vfsgen? 

2. By saying cleanup, do you also mean we have some unused legacy parts (safe-to-remove) in this makefile?

**Comment by ostromart** [comment]
Hi, yes, we want to have make iop build the command and vfsgen dependency.
You can also get rid of gen_patches, gen_patch and proto_orig.

**Comment by ostromart** [comment]
Oh, proto should also be a dependency of iop and vfsgen.
