### ISSUE TITLE
JRMP protocol support in Istio

### ISSUE THREAD

**Issue by kish3007** [istio/istio#15293]
Looks like JRMP is not one of the supported protocols in Istio, rmi calls over JRMP with envoy side car proxy injected on pods. Here is the failure i noticed: ```java.rmi.ConnectIOException: error during JRMP connection establishment; nested exception is:
        javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake```

**Comment by esnible** [comment]
@kish3007 Do you have a sample for testing possible fixes?

**Comment by esnible** [comment]
Related? https://github.com/istio/istio/issues/10053

**Comment by esnible** [comment]
I was able to recreate the problem using Cassandra and jmxterm-1.0.0-uber.jar.  I did some preliminary troubleshooting.  JMX has a lot of options that are configured using `-Dcom.sun.management.jmxremote.*` and `-Djava.rmi.server.*`.  I suspect some of the security default features of RMI and Envoy are in conflict.  I will do some experiments tomorrow.

**Comment by kish3007** [comment]
Thanks @esnible 👍

**Comment by esnible** [comment]
I verified that locally I can do `java -jar jmxterm-1.0.0-uber.jar --url localhost:7199` and then use the command `beans` from the Cassandra pod with Envoy sidecar.

If I try remotely using `java -jar jmxterm-1.0.0-uber.jar --url cassandra:7199` I get

```
...
java.rmi.ConnectIOException: error during JRMP connection establishment; nested exception is: 
	java.io.EOFException
...
```

`tcpdump -i any tcp port 7199` seems to show an initial handshake working between pods, but then localhost:7199 gets involved.  I thought perhaps the client side was not listening properly and tried starting Cassandra with `export CASSANDRA_OPEN_JMX=true`.  I also tried `JVM_EXTRA_OPTS=-Djava.rmi.server.useLocalHostname=true`.  Neither helped.  I also tried with STRICT and no mTLS instead of permissive, also unsuccessfully.

This work item is to determine if there is a set of JVM options or Istio config that will allow RMI JRMP to work under Istio.  If there is a way we must document it.  If no configuration will solve this problem we must add support to Istio.

**Comment by mbanikazemi** [comment]
RMI JRMP works fine under Istio.
The above setup for Cassandra needs to be modified such that the remote access using jmxterm works. These changes are required with and without Istio.

Modify `/etc/cassandra/cassandra-env.sh` to allow remote access. For a simple test, add userid and password to password file specified in the script (`/etc/cassandra/jmxremote.password`). Furthermore, add `POD_IP=<pod ip>` to `run.sh`. For some reasons if this is not added, the script does not find the IP itself.

After these changes, use the following for remote access:
 
```
java -jar jmxterm-1.0.0-uber.jar --url cassandra:7199 -u cassandra
```

**Comment by mbanikazemi** [comment]
I will be updating this issue with more information soon.

**Comment by mbanikazemi** [comment]
The main issue with use of JRMP in an Istio mesh is that during the first phase of exchange between a client and a server, the server provides the address at which it should be contacted. So for the rim to work this address must be set appropriately. In the setup described above this can be set using a config parameter:  java.rmi.server.hostname 
The simplest thing would be to set this address to the server pod IP address. This will make the remote procedure call succeed but this will not enable the use of istio features such as destination rules on the client side and for example enable mtls on the client side will not take affect. Therefore this solution will not be acceptable as a complete solution.
To take advantage of all features provided by Istio, the service could be accessed through a service virtual IP address. That is the server provides the service IP address as where it wants to be contacted. This will work only if there is one POD that implements the service. Otherwise, one service pod may get contacted in the first phase and another for the final phase. This will obviously fail as a general solution.
The only reasonable solution seems to be use of headless services with stateful sets where a server can explicitly specify its pod IP address as the address to contact while the connection go through Istio listener on the client site where for example mtls can be enabled or disabled.

**Comment by esnible** [comment]
@mbanikazemi If java.rmi.server.hostname isn't set how does RMI/JRMP calculate the address?

**Comment by mbanikazemi** [comment]
It is not set automatically and if left unset it result in failure. 
In the setup above, it is set through the run, sh script before running Cassandra.

**Comment by kish3007** [comment]
Looks like Istio does support RMI protocol, the way i got it working was exposing both rmi ports in my pod and service yaml definitions and port names as `tcp-rmi1` and `tcp-rmi2`.

**Comment by JessHolle** [comment]
> Looks like Istio does support RMI protocol, the way i got it working was exposing both rmi ports in my pod and service yaml definitions and port names as `tcp-rmi1` and `tcp-rmi2`.

@kish3007 Did you manage to get this working with PeerAuthentication.MutualTLS.Mode Strict / auto mTLS by any chance?

**Comment by JessHolle** [comment]
> > Looks like Istio does support RMI protocol, the way i got it working was exposing both rmi ports in my pod and service yaml definitions and port names as `tcp-rmi1` and `tcp-rmi2`.
> 
> @kish3007 Did you manage to get this working with PeerAuthentication.MutualTLS.Mode Strict / auto mTLS by any chance?

Never mind.  There was a port access misconfiguration underlying our issues.  Yes, RMI works fine with Istio auto-mTLS.
