### ISSUE TITLE
Getting origin authentication failed when X service calling Y service(Mtls + origin authentication)

### ISSUE THREAD

**Issue by ayan1207** [istio/istio#15357]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Getting origin authentication failed when X service calling Y service(Mtls + origin authentication)**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**When we enable mtls(PERMISSIVE) and origin authentication for a particular service(Y) and we exposed Y on nodeport . Then we are trying to send request to Y service using authorization bearer token it is working fine as expected. Now inside service mesh we are having one more service X  which internally calls Y and try to access Y , it is getting failed(Origin authentication failed) because Y service have both the policies enabled. Can we do something that when X calls Y that time Y should avoid origin authentication as it is inside a mesh**

**1. Y service exposed on nodeport
   2. Enable mtls (PERMISSIVE) and origin authentication on service Y
    3. deployed one more service X which call Y
    4. While X calling Y it is getting failed as Y expect token **

**Version (include the output of istioctl version --remote and kubectl version)
istioctl version --remote

client version: version.BuildInfo{Version:"1.1.7", GitRevision:"eec7a74473deee98cad0a996f41a32a47dd453c2", User:"root", Host:"341b3bf0-76ac-11e9-b644-0a580a2c0404", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.6-6-geec7a74"}
citadel version: version.BuildInfo{Version:"1.1.7", GitRevision:"eec7a74473deee98cad0a996f41a32a47dd453c2-dirty", User:"root", Host:"341b3bf0-76ac-11e9-b644-0a580a2c0404", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.6-6-geec7a74"}
egressgateway version: version.BuildInfo{Version:"1.1.7", GitRevision:"eec7a74473deee98cad0a996f41a32a47dd453c2", User:"root", Host:"341b3bf0-76ac-11e9-b644-0a580a2c0404", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.6-6-geec7a74"}
egressgateway version: version.BuildInfo{Version:"1.1.7", GitRevision:"eec7a74473deee98cad0a996f41a32a47dd453c2", User:"root", Host:"341b3bf0-76ac-11e9-b644-0a580a2c0404", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.6-6-geec7a74"}
galley version: version.BuildInfo{Version:"1.1.7", GitRevision:"eec7a74473deee98cad0a996f41a32a47dd453c2-dirty", User:"root", Host:"341b3bf0-76ac-11e9-b644-0a580a2c0404", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.6-6-geec7a74"}
ingressgateway version: version.BuildInfo{Version:"1.1.7", GitRevision:"eec7a74473deee98cad0a996f41a32a47dd453c2", User:"root", Host:"341b3bf0-76ac-11e9-b644-0a580a2c0404", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.6-6-geec7a74"}
ingressgateway version: version.BuildInfo{Version:"1.1.7", GitRevision:"eec7a74473deee98cad0a996f41a32a47dd453c2", User:"root", Host:"341b3bf0-76ac-11e9-b644-0a580a2c0404", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.6-6-geec7a74"}
ingressgateway version: version.BuildInfo{Version:"1.1.7", GitRevision:"eec7a74473deee98cad0a996f41a32a47dd453c2", User:"root", Host:"341b3bf0-76ac-11e9-b644-0a580a2c0404", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.6-6-geec7a74"}
ingressgateway version: version.BuildInfo{Version:"1.1.7", GitRevision:"eec7a74473deee98cad0a996f41a32a47dd453c2", User:"root", Host:"341b3bf0-76ac-11e9-b644-0a580a2c0404", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.6-6-geec7a74"}
ingressgateway version: version.BuildInfo{Version:"1.1.7", GitRevision:"eec7a74473deee98cad0a996f41a32a47dd453c2", User:"root", Host:"341b3bf0-76ac-11e9-b644-0a580a2c0404", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.6-6-geec7a74"}
pilot version: version.BuildInfo{Version:"1.1.7", GitRevision:"eec7a74473deee98cad0a996f41a32a47dd453c2-dirty", User:"root", Host:"341b3bf0-76ac-11e9-b644-0a580a2c0404", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.6-6-geec7a74"}
pilot version: version.BuildInfo{Version:"1.1.7", GitRevision:"eec7a74473deee98cad0a996f41a32a47dd453c2-dirty", User:"root", Host:"341b3bf0-76ac-11e9-b644-0a580a2c0404", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.6-6-geec7a74"}
pilot version: version.BuildInfo{Version:"1.1.7", GitRevision:"eec7a74473deee98cad0a996f41a32a47dd453c2-dirty", User:"root", Host:"341b3bf0-76ac-11e9-b644-0a580a2c0404", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.6-6-geec7a74"}
pilot version: version.BuildInfo{Version:"1.1.7", GitRevision:"eec7a74473deee98cad0a996f41a32a47dd453c2-dirty", User:"root", Host:"341b3bf0-76ac-11e9-b644-0a580a2c0404", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.6-6-geec7a74"}
pilot version: version.BuildInfo{Version:"1.1.7", GitRevision:"eec7a74473deee98cad0a996f41a32a47dd453c2-dirty", User:"root", Host:"341b3bf0-76ac-11e9-b644-0a580a2c0404", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.6-6-geec7a74"}
policy version: version.BuildInfo{Version:"1.1.7", GitRevision:"eec7a74473deee98cad0a996f41a32a47dd453c2-dirty", User:"root", Host:"341b3bf0-76ac-11e9-b644-0a580a2c0404", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.6-6-geec7a74"}
policy version: version.BuildInfo{Version:"1.1.7", GitRevision:"eec7a74473deee98cad0a996f41a32a47dd453c2-dirty", User:"root", Host:"341b3bf0-76ac-11e9-b644-0a580a2c0404", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.6-6-geec7a74"}
sidecar-injector version: version.BuildInfo{Version:"1.1.7", GitRevision:"eec7a74473deee98cad0a996f41a32a47dd453c2-dirty", User:"root", Host:"341b3bf0-76ac-11e9-b644-0a580a2c0404", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.6-6-geec7a74"}
telemetry version: version.BuildInfo{Version:"1.1.7", GitRevision:"eec7a74473deee98cad0a996f41a32a47dd453c2-dirty", User:"root", Host:"341b3bf0-76ac-11e9-b644-0a580a2c0404", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.6-6-geec7a74"}
telemetry version: version.BuildInfo{Version:"1.1.7", GitRevision:"eec7a74473deee98cad0a996f41a32a47dd453c2-dirty", User:"root", Host:"341b3bf0-76ac-11e9-b644-0a580a2c0404", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.6-6-geec7a74"}

kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:43:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:43:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**

**How was Istio installed?
We have installed using no-tls mode**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by neelmyrx** [comment]
facing same issue. Any progress?

**Comment by yangminzhu** [comment]
So basically you would like to apply a JWT policy on service Y and and make it only validate requests out of the mesh but ignore request from within the mesh, right?

ideally you could apply the JWT policy on ingress gateway and use it to route the traffic to service y. The service x could access service y directly to bypass the jwt policy.

The other workaround is to combine the authentication and authorization together, you can set the [originIsOptional](https://istio.io/docs/reference/config/istio.authentication.v1alpha1/#OriginAuthenticationMethod) to make the JWT validation optional and then verify it in the authorization level. You can create ServiceRole/ServiceRoleBinding to check if the jwt token is presented for requests based on the source IP in order to distinguish whether the request is from within the mesh or not.

**Comment by MrSaints** [comment]
Potentially related #8496.

If anyone is coming across a similar use-case of having two services - service A, and service B - with the same underlying workload selector - but with the desire to only apply a JWT policy on one of the services, save yourself the time, and avoid it for now (at least at the time of writing).

The JWT policy is propagated to the underlying workload that the service selects, so it will "affect" service B even if the policy only mentions service A.

You can try to combine authentication, and authorisation, but the next problem is having to distinguish the source IP. Indeed, there are other ongoing discussions on correctly receiving, and handling the source IP due to how the edge load balancer, and how pilot handles / translates traffic. You will also have to deal with quite a lot of config if running in permissive mode (to enable mTLS Egress / between services) which often is _desirable_ initially if you are running lots of different kinds of workloads, e.g. databases that aren't currently well supported / has edge cases (see other discussions). Even if it was simplified, it doesn't seem very pleasant to have to deal with hardcoded IP CIDRs.

Your best bet is going JWT all the way, attaching the policy to an Ingress Gateway (which by the way, will require even more configuration, and a costlier infrastructure in most cloud providers) or simply having an internally hosted proxy instead of using Istio's JWT end-user authentication. I feel the last solution is probably the simplest.

**Comment by yangminzhu** [comment]
> Potentially related #8496.
> 
> If anyone is coming across a similar use-case of having two services - service A, and service B - with the same underlying workload selector - but with the desire to only apply a JWT policy on one of the services, save yourself the time, and avoid it for now (at least at the time of writing).
> 
> The JWT policy is propagated to the underlying workload that the service selects, so it will "affect" service B even if the policy only mentions service A. Admittedly, this is not clear in the documentation.
> 

This is the API design problem in both authN and authZ. The new v1beta1 authorization policy (planned for 1.4) will use the [workload selector](https://github.com/istio/api/blob/2387a8cbe150ae27b2372a22f3d2228625cd664d/security/v1beta1/authorization.proto#L158) instead of service name to select where to apply the policy. This should make it super clear that the policy is applied and enforced on workload but not service.

The same change will also go to the next version of JWT policy. We're still working on this. The transition to workload selector also aligns with the direction of many other APIs in Istio, e.g., the Sidecar, EnvoyConfig and Gateway.

> You can try to combine authentication, and authorisation, but the next problem is having to distinguish the source IP. Indeed, there are other ongoing discussions on correctly receiving, and handling the source IP due to how the edge load balancer, and how pilot handles / translates traffic. You will also have to deal with quite a lot of config if running in permissive mode (to enable mTLS Egress / between services) which often is _desirable_ initially if you are running lots of different kinds of workloads, e.g. databases that aren't currently well supported / has edge cases (see other discussions). Even if it was simplified, it doesn't seem very pleasant to have to deal with hardcoded IP CIDRs.
> 
> Your best bet is going JWT all the way, attaching the policy to an Ingress Gateway (which by the way, will require even more configuration, and a costlier infrastructure in most cloud providers) or simply having an internally hosted proxy instead of using Istio's JWT end-user authentication. I feel the last solution is probably the simplest. Also alternatively, you probably want to have a more configurable Ingress (thinking Traefik, Kong, Ambassador, etc), and a simpler service mesh (thinking linkerd2 here) - don't get me wrong, I still use Istio extensively, and love it, but you shouldn't have to battle with your tooling.

**Comment by diemtvu** [comment]
Stay tune for 1.5. The API model for JWT (and authZ) will be on workload.

**Comment by joberdick** [comment]
I found a workaround that I will try to share after the holiday break. Basically, using origin optional setting in combination with newer authz policies in 1.4, I can enforce JWT only on external calls and still allow non JWT calls internally in the mesh.

**Comment by incfly** [comment]
I'm closing this issue after scanning the history.

- The service selection model on mtls/origin(jwt) is addressed in 1.5. no ambuitilty now.
- the option to ignore the internal worklod origin authn should achieved by @yangminzhu suggestion using ingress gateway.

Feel free to reopen if you find any gap still exists. (I did a quick scan might miss some details...)
