### ISSUE TITLE
Define and implement a naming convention for our samples and examples

### ISSUE THREAD

**Issue by rcaballeromx** [istio/istio#15469]
**Describe the feature request**

The current naming convention of using the name of a service to name configuration resources is confusing to documentation readers. Additionally, the latest best practice is to use fully qualified names for the host field, which our examples and samples don't follow.

The new naming convention must satisfy at least the following requirements:

- Enable readers to distinguish configuration resources and services through the value in the `name` field.
- Follow the project's best practices.

The naming convention defined would be optional for production-ready configuration resources but mandatory for all code samples and examples employed in the docs.

**Describe alternatives you've considered**

Currently, all configuration resources for a service are named using the name of the service.
While convenient in production deployments, this naming convention leads to a lot of confusion for new Istio users. This problem is confounded when the short names are used as the value for the `host` and `hosts` fields. New users have a lot of difficulty distinguishing configuration resources from the service.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ X ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ X ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by frankbu** [comment]
Browsing through docs and samples, I can see that using the same name for configuration resources related to a service is a very common pattern in both Istio and Kube. It's a very common pattern. Kube deployments, for example, often have the same name as the corresponding service. In most Istio configs the service name is the same the corresponding virtual service name, service entry name, and destination rule name.

If we want to make them different we need some kind of prefix or suffix, which is not a popular naming convention in any programming or configuration language.

I agree that we should consider using fully qualified host names in the sample configs (it is the Istio recommended best practice), but IIRC the problem was that we wanted to make the sample configs namespace-independent, so users can choose to run the sample in any namespace they'd like.

**Comment by esnible** [comment]
This is marked P0 for 1.3.  What is needed?

**Comment by frankbu** [comment]
Given the issues described above, I don't think we should make any changes here, so I would suggest closing. Otherwise move it to a future release.

**Comment by howardjohn** [comment]
> Browsing through docs and samples, I can see that using the same name for configuration resources related to a service is a very common pattern in both Istio and Kube. It's a very common pattern. Kube deployments, for example, often have the same name as the corresponding service. In most Istio configs the service name is the same the corresponding virtual service name, service entry name, and destination rule name.

+1 this is a good practice
