### ISSUE TITLE
Validate trust domain in authentication policy

### ISSUE THREAD

**Issue by yangminzhu** [istio/istio#15631]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
When mTLS is used in authentication policy (either PERMISSIVE or STRICT mode), the server should validate the client is in the same trust domain and reject the connection if it's not.

The trust domain will be extracted from the client and server x509 certificate and will be checked in the server side authentication filter.

User could opt-out the validation by setting a flag to true if this breaks their existing usage.

cc @myidpt @diemtvu 

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by duderino** [comment]
@yangminzhu is anything left here?

**Comment by yangminzhu** [comment]
@duderino We need one more PR to expose the opt-out flag to users: https://github.com/istio/istio/pull/16798, sorry I added it only in the filter config before but forgot to expose it in pilot.

**Comment by brianwolfe** [comment]
@yangminzhu would it make more sense to make this part of authorization & AuthorizationPolicy?

If a trust domain is not intended to be trusted for authentication, it should probably not be trusted by the root CA installed in the proxy. I'm currently coming up with our multi-trust-domain PKI and am running into difficulty understanding the trust model this is actually intending to implement.

If it is intended for authorization control, the authorization policy seems like a more appropriate place to add this check.
If this is intended to be part of authentication, it seems better to implement it as part of PKI & TLS, equally for HTTP and TCP maybe as a certificate extension (e.g. by adding a Name Constraint to the CA installed for Citadel).

The existing solution only appears to work for HTTP and mysteriously fails with an authorization failure (401) inside the authentication filter instead of being a configurable property of the AuthorizationPolicy.

As it is, if we want to have cross-trust-domain traffic, we will need to disable this feature and only authorize services based on their full principal string because that is the only exposed Source in the AuthorizationPolicy.

If you think it's worthwhile, I'll open up a new Issue where we can discuss this.

**Comment by yangminzhu** [comment]
@brianwolfe Yeah, I think you raised a good point of delegating the trust domain validation to the authorization layer which gives more flexibility. @myidpt and I had some discussions recently about this but we haven't looked deep to see how to improve this. Would you mind to open an issue for further discussions? Thanks.
