### ISSUE TITLE
Easy way to view which services are part of the mesh

### ISSUE THREAD

**Issue by linsun** [istio/istio#15635]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Easy way to view which services are part of the mesh, aka mTLS ready.

**Describe alternatives you've considered**
It is pretty hard to get this info today other than check if the corresponding pod for the service has envoy proxy.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x ] User Experience
[ ] Developer Infrastructure

**Additional context**
Lin Sun [3:39 PM]
with the mTLS auto config, do you think it is valuable to add an istioctl cmd to see which services are mTLS ready?
this is good to also see which services are part of the mesh

Gregory Hanson [4:23 PM]
this is something I had a hard time tracking in my early days of testing and agree it would be pretty helpful for visualizing

Lin Sun [4:27 PM]
@snible thoughts?

Edward Snible [4:34 PM]
We need a way to see which services are able to do mTLS, are strictly mTLS, or are permissive.

cc Kiali team, this would be good to visualize from Kiali too @knrc @jmazzitelli

**Comment by esnible** [comment]
This is related to `istioctl inspect pod` (https://github.com/istio/istio/pull/15827 and it needs a review).

That command will tell you if a pod is part of the mesh.

I can imagine a simple output for `istioctl get services`

```
NAME            MESH
cassandra       istio-system
details         istio-system
hello-service   istio-system
kubernetes
myclient
productpage     istio-system
proxy-service   istio-system
ratings         istio-system
reviews         istio-system
sleep           istio-system
```

This sample prints the namespace of the Istio control plane because in Istio 1.3 there might be >1 Istio control plane so Yes/No won't help.

Many of the problems I've had lately have been with multi-port services and TCP vs HTTP.  We can add complexity.  How much complexity were you expecting in the output?

```
NAME            PLANE        MESHED PORTS         UNMESHED PORTS
cassandra       istio-system 9042/mTLS,7000,7001  7199
details         istio-system 9080/mTLS
hello-service   istio-system 3000/TCP
kubernetes                                        443
myclient                                          85
productpage     istio-system 9080/mTLS
proxy-service   istio-system                      8080
ratings         istio-system 9080/mTLS
reviews         istio-system 9080/mTLS
sleep           istio-system                      80
```

I don't like the complex version.  I like the simple version with documentation suggesting the user use `istioctl inspect` for further details.

@GregHanson What do you think the output should look like?

**Comment by mwringe** [comment]
The way the Kiali does this is to just check if the sidecar is available or not.

We have two main areas where you can see this:

- if you are on the graph view, we can show a label on the workload if its missing the side car.

- if you go to the list view of workloads, you can ask it to show you only workloads that have the sidecar, or only the ones that are missing the side car. 

I believe we can also warn users if they have an workload where some of the pods contain the sidecar and some don't,

**Comment by esnible** [comment]
@linsun is `istioctl x describe service <svc>` sufficient?  Shall we close this Issue?
