### ISSUE TITLE
The certificate of https://gcsweb.istio.io/ has been expired.

### ISSUE THREAD

**Issue by ebensom** [istio/istio#15699]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
The certificate of https://gcsweb.istio.io/ has been expired. Please replace.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**
helm repo add https://gcsweb.istio.io/gcs/istio-release/releases/1.1.9/charts/
Error: Looks like "https://gcsweb.istio.io/gcs/istio-release/releases/1.1.9/charts/" is not a valid chart repository or cannot be reached: Get https://gcsweb.istio.io/gcs/istio-release/releases/1.1.9/charts/index.yaml: x509: certificate has expired or is not yet valid

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by jameshochadel** [comment]
+1. This is blocking installation of Istio via Helm for us.

**Comment by hausdorff** [comment]
This is, by my count, the second time Istio upstream has caused catastrophic failure in downstream CI because they moved or failed to maintain critical infrastructure that allows downstream to access to the official mechanisms for installing Istio.

I should not have to tell you that these sorts of failures are _very_ costly for people running production infrastructure on top of this technology. What do you need from downstream to fix this issue permanently?

**Comment by Katharine** [comment]
This happened because of a Helm bug that caused a cert-manager update to incorrectly purge its CRDs, causing automatic certificate renewal to fail. We've restored the CRDs and automatic certificate renewal is working again.

The issue was not escalated to the test infrastructure oncall until yesterday, and I was unaware that gcsweb was critical infrastructure until I saw this issue just now. I am very surprised that it is - for production usage I would've expected direct references to GCS (e.g. `https://storage.googleapis.com/istio-release/releases/1.1.9/charts/`).

Proper monitoring here would obviously be good, but I would also like to know how a convenience tool for viewing test artifacts ended up in any critical path and whether it is necessary for it to be there.

**Comment by hausdorff** [comment]
Thanks for the information—that's useful.

To answer your question directly, this found its way into production CI pipelines because until March 14th, [the documentation seemed to present this as official way to install the chart](https://github.com/istio/istio.io/commit/dd8b7aac40c2dd35a6a33cf0bcae58eb3e8077c7#diff-bdb2f51593ff055fcf1cb12933550cb3L62). Before that, the only "official" way to get the Chart was with the undocumented http://istio.io/charts, which even now redirects to the latest release of on https://gcsweb.istio.io.

My feedback to you and the rest of Istio upstream is: documenting an API as the official way to do something that could impact production systems signals to downstream that the API is going to be maintained and monitored in a way that is commensurate to the risk of breaking all of downstream using it. For APIs that are or were on this path, it would be _very_ nice if we could commit to maintaining them to this standard. :)

**Comment by Katharine** [comment]
To be clear, I'm not suggesting that anyone downstream did anything wrong here - my comment was targeted at upstream.

Thanks for the context -- while I am involved in maintenance of the test infrastructure, I am not otherwise involved in Istio upstream development.

**Comment by hausdorff** [comment]
Sure, we're all good. I'm not trying to call you or anyone else out specifically, just to provide transparent feedback about the effect this issue has on downstream.

**Comment by Katharine** [comment]
To mitigate this in the future, I've updated https://istio.io/charts to bypass gcsweb entirely (though this will not deploy until the next Istio release), and added monitoring to gcsweb so oncall gets alerts if it goes down. It's not a perfect solution (it only alerts after things have gone wrong), but should reduce resolution time from days to minutes.

**Comment by sdake** [comment]
This appears resolved by the T&R WG.  As such, closing this issue.  If this clsoure is in error, feel free to reopen.

Cheers
-steve
