### ISSUE TITLE
Use envoy http proxy filter for egress gateway

### ISSUE THREAD

**Issue by rshriram** [istio/istio#15778]
Envoy now has support for generic http proxy. We should investigate using this facility at egress gateway for http traffic. At the very least we should have a default http proxy listener at the egress gateway with the http proxy enabled. The new envoy filter crd apis should come in handy for this.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by hzxuzhonghu** [comment]
More details, i can not understand this.

**Comment by vadimeisenbergibm** [comment]
Envoy's dynamic forward proxy https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/dynamic_forward_proxy_filter#config-http-filters-dynamic-forward-proxy

Should be used instead of additional (SNI) proxy in https://istio.io/docs/tasks/traffic-management/egress/wildcard-egress-hosts/#setup-egress-gateway-with-sni-proxy, to support egress control of traffic to wildcard hosts, e.g. to `*.wikipedia.org`.

**Comment by hzxuzhonghu** [comment]
> HTTP dynamic forward proxy support should be considered alpha and not production ready.

**Comment by vadimeisenbergibm** [comment]
@hzxuzhonghu So we have time to add it before it becomes production ready. Before it is production ready, we can add it as alpha.

**Comment by hzxuzhonghu** [comment]
agree

**Comment by doujiang24** [comment]
Any suggestion or plan for this?
We want this feature, if there is a plan, we could have a try. Thanks.
