### ISSUE TITLE
Switch to prototool for compatibility checking

### ISSUE THREAD

**Issue by geeknoid** [istio/istio#15884]
Instead of protolock, we should switch to using 'prototool break check' which works by comparing the current set of files with what is checked into a particular git branch. So for us, upon checking any changes into the proto, we can compare them against the prior release's branch and know whether we have any breaking changes. 

This is simpler and strictly more correct than our current use of protolock.

I tried to do this switch but ran into docker image issues that needed to be sorted out, so I punted this to an issue instead.

**Comment by ozevren** [comment]
@jasonwzm Is this something that you can take a look at?

**Comment by jasonwzm** [comment]
prototool offers similar mechanism when checking compatibility with the previous version. Instead of basing off a static file for checks, it can use a git branch as the base. The output of the prototool is an equivalent of the `Status` file in protolock. The behavior of the two is similar. Will tackle just using prototool later.

**Comment by jasonwzm** [comment]
prototool does not check alpha APIs e.g. v1alpha1. so it is not ideal in our use case. Closing it for now and we will re-assess in the future.
