### ISSUE TITLE
External Service Entry to support non-http protocols like ldap,netconf,ssh,FTP etc.,

### ISSUE THREAD

**Issue by mkharibalaji** [istio/istio#15972]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**External Service Entry to support non-http protocols like ldap,netconf,FTP etc.,**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**It would be great if you guys to help workaround to make the container execute the above protocols**

**Comment by esnible** [comment]
@mkharibalaji You should assign protocol-specific `name` to the Port name on the Service Entry.

See https://istio.io/docs/reference/config/networking/v1alpha3/gateway/#Port for example of how to do this.

See https://istio.io/docs/setup/kubernetes/additional-setup/requirements/ for Istio's list of protocols that can be applied to the name.

**Comment by howardjohn** [comment]
Related to https://github.com/istio/istio/issues/15776

I don't know the details of all these protocols, but we are bounded by what envoy supports. For FTP at least I think it requires UDP so we are blocked by https://github.com/istio/istio/issues/1430

**Comment by howardjohn** [comment]
I think the state of this is:
* Any protocol we support needs to be supported by Envoy (since that is what it means for us to support a protocol)
* If there is a protocol supported by envoy that we don't yet support, it shouldn't be that much work for us to add support
* Any protocol that needs UDP is blocked by https://github.com/istio/istio/issues/1430
* Any protocol that is not UDP and not supported by Envoy specially can just use the TCP proxy

So I don't think there is any work to do here
