### ISSUE TITLE
istio/gogo-genproto rely github.com/gogo/protobuf v1.2.2 not publish

### ISSUE THREAD

**Issue by jacky-lk** [istio/istio#16070]
**Bug description**
Our project rely istio to develop service mesh. Today we execute "dep ensure update -v " in our project. We find build error like the photo below:
![image](https://user-images.githubusercontent.com/50770015/62512595-24bdfe80-b84b-11e9-87b8-ac79213cf83c.png)
And we find the struct dose not define MarshalToSizedBuffer and then we check the version of "github.com/gogo/protobuf" is v1.2.1. We go to the github of protobuf and  find the newest version is v1.2.1. But we go to the site of istio/gogo-genproto (https://github.com/istio/gogo-genproto/blob/master/go.mod) and find it rely v1.2.2
![image](https://user-images.githubusercontent.com/50770015/62512786-01478380-b84c-11e9-93ab-7a798820c53d.png)
So we have no idea that how to upgrade to v1.2.2 and we try it but failed.
![image](https://user-images.githubusercontent.com/50770015/62512827-32c04f00-b84c-11e9-9adf-27cb0f01e77e.png)
At last I am sorry write issue in istio, because we can not find issure in gogo-genproto. And we
hope that you can give us some suggestions. Thank you

**Comment by geeknoid** [comment]
Sorry, we need the currently latest bits of gogo/protobuf for Istio to work, otherwise we had been encountering a code generation bug. The change we need is after 1.2.1 and 1.2.2 hasn't been released officially yet, so we took a direct  depending on a specific SHA.

Additionally, gogo has changed their code generation a bit. You cannot combine code generated from a previous version of gogo with code generated with the current version. If you do, you end up with the missing MarshalToSizedBuffer symbol that you've encountered. The only  solution is thus to recompile all of your own generated code using the same  version of gogo that Istio is using.

As soon as 1.2.2 is officially available, we will switch to it.

I hope this helps. I'm going to close this issue for now as we don't have  a choice but to use the current bits. Please let me know if we can do anything else to help.

**Comment by jacky-lk** [comment]
> Sorry, we need the currently latest bits of gogo/protobuf for Istio to work, otherwise we had been encountering a code generation bug. The change we need is after 1.2.1 and 1.2.2 hasn't been released officially yet, so we took a direct depending on a specific SHA.
> 
> Additionally, gogo has changed their code generation a bit. You cannot combine code generated from a previous version of gogo with code generated with the current version. If you do, you end up with the missing MarshalToSizedBuffer symbol that you've encountered. The only solution is thus to recompile all of your own generated code using the same version of gogo that Istio is using.
> 
> As soon as 1.2.2 is officially available, we will switch to it.
> 
> I hope this helps. I'm going to close this issue for now as we don't have a choice but to use the current bits. Please let me know if we can do anything else to help.

Thanks for your reply on this issue. We have rollbacked 'go-control-plane' version to 0.8.2 to solve this problem. Now our project is ok.
