### ISSUE TITLE
In the multiple control plane multi-cluster mesh pattern, all the services are exposed by default.

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/istio#16407]
Following the Networking WG meeting on 15-th of August 2019: In the [multiple control plane multi-cluster mesh](https://istio.io/docs/setup/kubernetes/install/multicluster/gateways/) pattern, all the services are exposed by default. This is the behaviour as it is documented in the installation example.

There is a claim that it is a P0 bug, while in my opinion it is a feature of the pattern, it was implemented this way by design. The multi-cluster mesh by design designates a single _logical_ mesh spread between multiple _physical_ clusters, so it is reasonable to expect that all the services within a single logical mesh are exposed by default within the single mesh. I will explain the implementation of the pattern in a separate comment.

Since in the [multiple control plane multi-cluster mesh](https://istio.io/docs/setup/kubernetes/install/multicluster/gateways/) all the services are exposed by default and there is no control of the incoming traffic at the boundary of the cluster, it does not provide boundary protection (see [this blog post](https://github.com/istio/istio.io/pull/4776)). The question is how to fix this behaviour and what is the amount of effort required.

The requirements for the boundary protection:
1. the services should be not exposed unless explicitly configured to be exposed
1. there should be access control: which source principle (at least the identity of the consuming cluster) may access specific services in the  providing cluster
1. the access control must be enforced **at the boundary** (at the ingress gateway).

Proposed next steps:
1. Someone provides a design how to implement boundary protection for [multiple control plane multi-cluster mesh](https://istio.io/docs/setup/kubernetes/install/multicluster/gateways/) .
1. Someone provides estimation of effort for the required design.
1. If there is a significant effort to implement boundary protection for [multiple control plane multi-cluster mesh](https://istio.io/docs/setup/kubernetes/install/multicluster/gateways/) (for example if it would mean reimplementing the whole pattern) we should decide if it is worth to invest this effort, considering that we have [another pattern](https://github.com/istio/istio.io/pull/4776) that provides boundary protection and works today with Istio AS IS.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by vadimeisenbergibm** [comment]
duplicate, closing

**Comment by costinm** [comment]
What is it duplicating ? 

To answer your comments: Gateway provides a clear mechanism to control what hosts can be exposed, since Istio 1.1.  

Multicluster for multiple networks is using Gateway - configured in SNI-proxy mode. The SNI-proxy
port - just like any other port in the Gateway - should follow the same rules, and allow configuration
of which namespaces and services can be exposed.

The control of the Gateway resides with the gateway admin - he can decides which ports and hosts are exposed, and which namespaces are allowed to bind to a gateway.

**Comment by costinm** [comment]
Also "multiple control plane" has nothing to do with the issue - one or more control plane is not a factor. 

Neither is the number of clusters:  even if you have a single cluster with just mesh expansion, the Gateway should still follow its own specification in exposing internal services via SNI-routing mode.

The real bug is in Gateway implementation of SNI-proxy mode - which may be used in various topologies and for multicluster, but it is not specific to MC.

**Comment by vadimeisenbergibm** [comment]
@costinm Sorry, it is duplicating https://github.com/istio/istio/issues/16406, I accidentally opened the same issue twice. Let me copy your comments to that issue.
