### ISSUE TITLE
Pilot: Out-of-process platform adapters

### ISSUE THREAD

**Issue by rosenhouse** [istio/istio#1643]
As part of the Cloud Foundry (CF) integration work (https://github.com/istio/istio/issues/1371), considerations for availability and scalability have led us to consider introducing a new platform component in CF (working name: `copilot`) that will serve service discovery data to the (work-in-progress) CF Pilot platform adapter.

```
Pilot Core <--> CF Platform Adapter   <--- gRPC ---   Copilot  <----> Cloud Foundry APIs (CAPI,Diego)
^----------------------------------^                   ^
         Pilot binary                             separate binary
```

We're thinking that the in-process CF Platform Adapter will be a relatively thin gRPC client, with the bulk of the data fetching & joining living in Copilot.

In fact, the gRPC protocol *could* mirror the [Golang interfaces that Pilot Core defines for `ServiceDiscovery`](https://github.com/istio/istio/blob/5ca8a9599e7ddd6c5b84f99343c9fb1cb8a6b082/pilot/model/service.go#L194-L230), which are implemented by platform adapters.   That gRPC could become platform agnostic and the `CF Platform Adapter` might eventually be just a `Remote Platform Adapter`, with all the platform-specific logic living on the gRPC server.

We're thinking we'll build this out for Cloud Foundry support right now without working too hard to be fully-platform agnostic.  But would be happy to have the interface evolve in that direction long-term.

Thoughts?  Any existing work / design docs on this?

**Comment by mandarjog** [comment]
We have similar plans for Mixer grpc adapters. We want to make it a build time decision. You should be able to build it in process or out of process if written in go.

Are you planning to implement `copilot` in a language other than go ? For availability and scalability we could simply scale Pilot with built in CF adapter. How different is it from that.
I think the operator should see clear benefits of managing yet another component.
Even though for a CF operator one extra component is not much.

**Comment by rshriram** [comment]
This is no different than us talking to service registries today (kube api server, consul, eureka). From that point of view, you really should not be focusing on standardizing the service registry interface as there is no standard. Besides, the service model undergoes changes. Many newly introduced fields can be derived from existing fields. 

I suggest you use whatever protocol/data format that is expedient to communicate with your DB backends/api servers in front. Internally in the code, adhere to the service model as other adapters do. This model has served us very well for the last year and we have been able to easily expand from kubernetes to consul to Eureka (and some teams internally at watson have been able to map some bespoke systems into this model without any pain). But please do publish the API exposed by your service registry, just like apis from consul, eureka, etc., so that we can mock and test. If your service registry server happens to be open source and comes with some mock data, its all the more better because it will allow us to test the integration continuously.

p.s. not a fan of name copilot but thats a matter of personal taste. I prefer something like air traffic controller or registrar or CFR (cloud foundry registry)

**Comment by rosenhouse** [comment]
@mandarjog That's good to know about Mixer.  Long-term we can think about maybe allowing an option between in-process/out-of-process.  As for scaling, yes, we plan to horizontally scale the Pilots.  But then we have to consider the load they put onto the upstream platform API servers.   Suffice to say, we think a new component, scaled independently, is a good plan to start with.

@rshriram These are good points, especially about flexibility in the interfaces and being able to derive new fields from old ones on the client side.  For that reason, I think we'll steer clear of anything that tries to look generic -- and I'll close this issue.

Thanks!
