### ISSUE TITLE
tools: runner/graph.py cannot generate latency graph as expected

### ISSUE THREAD

**Issue by carolynhu** [istio/istio#16740]
With all csv test data points gathered correctly. When I run 
```
(runner) bash-3.2$ python runner/graph.py  /path_to_csv_data.csv p90
```
I got the following Bokeh Warnings:
```
BokehUserWarning: ColumnDataSource's columns must be of the same length. Current lengths: ('x', 0), ('y', 7)
```
The generated graph is missing x-axis labels, also without any plotted data points:
![bokeh_plot](https://user-images.githubusercontent.com/29208297/64073155-c10ed180-cc4e-11e9-811c-99041b9b72b8.png)

**Comment by carolynhu** [comment]
Except for the above, the line label is also incorrect.

**Comment by carolynhu** [comment]
New errors:
```
Wrote 21 json records to /var/folders/9_/rb_dp8jn1qjf_dgcnw4nvm1800m_9h/T/tmp8y8ubhe1.json
Traceback (most recent call last):
  File "./runner/fortio.py", line 298, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./runner/fortio.py", line 264, in main
    args.csv_output)
  File "./runner/fortio.py", line 217, in sync_fortio
    write_csv(csv, data, csv_output)
  File "./runner/fortio.py", line 230, in write_csv
    out = open(csv_output, "w+")
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by carolynhu** [comment]
graph.py also cannot properly generate graph for linkerd.csv, i.e.` python ./runner/graph.py linkerd.csv p90 --mesh=linkerd` command is broken somehow.

**Comment by johscheuer** [comment]
I just took a quick look and the labels for the tests currently are generated for no reason (at least I couldn't find any reason). If we set the labels according to the "mode" we can dynamically read all used modes and generate the graph. This should at least solve the issue that some data is not shown (e.g. because a `mode` is not defined in modes). If I find some free time today I will provide a PR to solve the dynamically identification of the modes.
