### ISSUE TITLE
V2 telemetry emits durations in `millis` instead of `seconds`

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#16799]
V2 telemetry in 1.3.0.rc1 emits latency numbers in `milliseconds`.
Mixer telemetry emits them in `secods`, which is what the dashboard assumes.

Update the dashboard so that it works both with the `istio_requests_duration` and `envoy_requests_duration_seconds` and scales `envoy_requests_duration_seconds` by `/1000.0`

**Comment by mandarjog** [comment]
consider updating the metric name to `istio_request_duration_milis`

**Comment by howardjohn** [comment]
is it feasible to have it output the same metrics? it would be nice to be able to smoothly transition to v2 without having to change the dashboards. And for kiali, custom dashboard, etc

**Comment by jmazzitelli** [comment]
I agree with @howardjohn .... I suggest you add a new metric with the new time unit rather than re-using the same metric name but changing to ms instead of seconds - at least as a temporary bridge. Otherwise, there will be breakage in ANY client using telemetry (it isn't just dashboards and kiali - its anyone that is looking at telemetry - I bet there are people out there with scripts that query prometheus and obtain metrics for their own reporting and statistical analysis).

@jshaughn @jotak this has impact on Kiali - we need to keep on top of this and change the name of the metric Kiali looks for and change Kiali's algorithms since the time unit is changing.

**Comment by mandarjog** [comment]
Before we call this “ready” it will be identical to the current metric.
This issue is so that the preview can be used.

My 1st comment is what you are asking for, add a new _milisecond metric.

**Comment by jotak** [comment]
@jmazzitelli maybe in kiali we'll want to keep backward compatibility? (e.g. with some setting flag to disable telemetry v2). Or once 1.3 is supported we drop support for all previous versions?

**Comment by douglas-reid** [comment]
The Grafana dashboard approach to this issue should be to use an updated prom query for places that require latency info. The query will use the `or` operator with the `_millis` value(s) converted to seconds. We should have a PR soon that demonstrates this approach.

I imagine that something similar can be done in Kiali.
