### ISSUE TITLE
prow should checkout project at $gopath/src/istio.io/istio

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#1683]
Prow boostrap checks out source code at it's github location inside the `GOPATH`.
Workaround requires creating a symlink from 
`GOPATH/src/istio.io/istio --> GOPATH/src/github.com/istio/istio`

Even this is not good because it makes the same package available at two different locations within `GOPATH`.

This should be fixed. It may as simple as passing `--jobsdir` parameter correctly.

**Comment by yutongz** [comment]
I guess this should be opened at test-infra but anyway. Can you specify a priority of this fix, does it affect current developing?

**Comment by sebastienvas** [comment]
Maybe the right way to fix this would be to have a proper golang setup and
to be able to go get and clone from istio.io

**Comment by mandarjog** [comment]
That will work too. I think simply providing an alternative place where the project is checked out is easier. That way this CI/CD is not predicated on go gettability of the project.

**Comment by ayj** [comment]
FWIW, `go get -u istio.io/istio` should already work.

**Comment by sebastienvas** [comment]
bootstrap supports multiple repos, so its not that simple. the --job-dir flag is common to every repo checked out so if job-dir = istio.io, you ll end up with istio.io/github.com/istio. Since we have a fork already for bootstrap we can just hard code it for istio.io:
https://github.com/istio/test-infra/blob/master/docker/istio_builders/prow_builder/bootstrap/bootstrap.py#L201

@ayj do you know why git clone does not work ?

**Comment by ayj** [comment]
Golang supports vanity domains and [canonical import paths](https://golang.org/doc/go1.4#canonicalimports); git does not.

Hardcoding this case seems like the most expedient thing to do, especially considering that is how k8s handles it.

**Comment by hklai** [comment]
Please reopen if this is still an issue.
