### ISSUE TITLE
Static IP or Static Domain name for Ingress Gatway

### ISSUE THREAD

**Issue by jwlai** [istio/istio#16855]
As the title sort of points out is there a way to attach the Static IP or a Static Domain to the controller? (I.e. in AWS I don't need to go to Route 53 and change the CName of an entry everytime I deploy//redeploy)

If anyone has tips on this topic that'd be great (maybe it's not possible? depends on the cloud?) If I could get material to read or investigate I'll take that too.

**Comment by jfeddern** [comment]
You could deploy a k8s service of type LoadBalancer and add the selector app=istio-ingressgateway to it in order to route the traffic to the ingressgateway pods. For the LoadBalancer you can provide a static ip. For more informations refer to the kubernetes documentation: https://kubernetes.io/docs/concepts/services-networking/#loadbalancer

**Comment by jfeddern** [comment]
Please take a look at the following file also (for ingress-gateway configuration) https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/example-values/values-istio-gateways.yaml

**Comment by howardjohn** [comment]
As mentioned above, this can be done just like any other kubernetes service -- see the docs linked above. Thanks!
