### ISSUE TITLE
More request and response timestamps

### ISSUE THREAD

**Issue by theganyo** [istio/istio#1701]
Currently, there are just 2 timestamp attributes for a request in Mixer:
  request.time
  response.time

In contract, Apigee metrics uses a much more granular breakdown of request and response timestamps:
  client received start time
  client received end time
  target sent start time
  target sent end time
  target received start time
  target received end time
  client sent start time
  client sent end time

In other words, Apigee creates a bracket of the start + end timestamps for the ingress and egress of the Apigee proxy. I believe it would be useful to track these 8 timestamps for Istio as well. In fact, I believe these should likely be tracked for each service in Istio... not just the ingress and egress. Especially as we look toward workflows that encompass multiple services, I believe the value of this would be clear.

(FYI, details description Apigee of the attributes here: https://docs.apigee.com/api-services/reference/variables-reference)

**Comment by mandarjog** [comment]
This sounds like trace spans around every hop, is that correct?

**Comment by theganyo** [comment]
Yes

**Comment by theganyo** [comment]
I don't believe this should be considered stale without additional discussion.

**Comment by kyessenov** [comment]
I also find `context.time` and `request.timestamp` insufficient. The stale bot aggressively closes issues unless it's tagged help wanted, so I'm going to do that.

**Comment by douglas-reid** [comment]
This issue came up in a different context yesterday. The use case presented in that scenario was the need to understand "total time added by the istio proxy". In other words, there was a request to know:
- time proxy received the first byte from the client
- time proxy sent the first byte to backend
- time proxy received the first byte from the backend
- time proxy sent the first byte to the client

I *think* that this information is already available. Hopefully, we can add a few attributes and send this information along to Mixer.

**Comment by douglas-reid** [comment]
Relevant envoy code: https://github.com/envoyproxy/envoy/blob/329e591d3f579535412daade4c3249b7c4ed7619/include/envoy/request_info/request_info.h#L110-L197

**Comment by douglas-reid** [comment]
@theganyo with the transition to v2, i believe those timestamps should now be more readily available. i'm gonna close this issue, as v1 is not going to receive any new functionality in this area.  I'm sorry we couldn't provide more when Mixer was still an on-going concern.
