### ISSUE TITLE
istioctl describe provide info on a pod without sidecar ready for mesh

### ISSUE THREAD

**Issue by linsun** [istio/istio#17049]
**Describe the feature request**

A good user flow is while user moves their existing deployment to Istio:

1. istioctl describe pod 
(check if the pod is ready to be added and take action if needed)

2. istioctl add-to-mesh service

**Describe alternatives you've considered**
Currently it doesn't output much useful info other than the pod doesn't have a sidecar.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x ] User Experience
[ ] Developer Infrastructure

@esnible @irisdingbj i noticed inconsistency between add-to-mesh cmd that takes a service name and describe takes a pod name.  Is this something we could generate consistency among the two?

**Comment by linsun** [comment]
@esnible Thank you - I think handling at deployment or/and service level is easier than pod.

for describe service, I 'm not sure if I'm interested in how many pods implement the service.  I would only want to know if there is issue for adding to istio first.

Once user feels confident and have added service to the mesh, then user may start debug traffic issue, that is where subset and mTLS strict/permissive etc can be useful.

**Comment by esnible** [comment]
@linsun I'm trying to understand the use case.

If I do `istioctl x describe pod <pod>` I get several messages such as `WARNING: <pod> is part of mesh; no Istio sidecar`.

These messages are low-level because the tool tried to get the Envoy config and failed.

What kind of feedback does the user expect?  There are several cases to consider:

1. The pod shouldn't be added to the mesh because it doesn't belong in the mesh.  For example istio-citadel.istio-system pods, or kube-dns.kube-system pods.
2. The pod has annotations because the user didn't want it in the mesh.  In that case, telling the user to `add-to-mesh` doesn't help
3. The pod is in a namespace that has been tagged for inject, but it didn't get restarted and will get the sidecar on restart.
4. The pod is in a namespace without auto-inject, and we want to inject it anyway, to gradually join the mesh.

There seems like a bunch of ad-hoc reasoning needed to determine what the user expects to see.  Is there a way to simplify this?
