### ISSUE TITLE
tools/dump_kubernetes.sh: Add granular filtering support

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#17098]
tools/dump_kubernetes.sh supports fetching debug artifacts for the whole cluster or you can filter / limit by
1. total size of the dump
2. namespace
3. pod labels

In addition to this, we need the ability to fetch these artifacts for a list of pods.
This will greatly increase our ability to gather debug info during support.

**Comment by howardjohn** [comment]
Maybe a separate issue, but it may be valuable to get an opt in "analytics" mode. Users can run it an tell us stats like cluster size, which features the use, etc. This will allow us to send this our to our users and get a little survey of how people are using Istio.

**Comment by howardjohn** [comment]
I think we need the following info. I would suggest we split the what we capture to a few flags so that users can opt into what the are comfortable sharing/for execution speed.

`--control-plane` 
* `kubectl get pods -n istio-system`
* `kubectl get describe -n istio-system`
* foreach pod in istio-system `kubectl logs --all-containers`
* `istioctl version`
* `istioctl proxy-status`
* `kubectl get configmap istio` && `kubectl get confimap istio-sidecar-injector`

`--cluster`
* `kubectl get nodes`
* `kubectl get services --all-namespaces`
* `kubectl get pods --all-namespaces`

`--proxy PROXY|LABEL`
* Fetch /config_dump, /clusters, /stats, /certs (?), /memory
* `kubectl logs POD -c istio-proxy`

Somewhere we should probably get all the istio configs as well. maybe a `--config NAMESPACE` flag or something

**Comment by duderino** [comment]
Setting to P0, which is a bit of a stretch, but this would really improve our efficiency when debugging random clusters

**Comment by nmittler** [comment]
@mandarjog @fpesce @howardjohn @duderino

We definitely need this! My main concern is about visibility and simplicity of the UX. I think we'd be better off baking this into istioctl, which customers likely already have and are familiar with.

Some (very rough) ideas for UX:

```bash
# Shorthand for cluster-info, control-plane, proxy, and logs
> istioctl dump all

# Dump cluster-info and control-plane, but only dump selected user pods
> istioctl dump all -l `app in (myapp)` -n mynamespace

# Dump nodes, services, and pods in the cluster
> istioctl dump cluster-info

# Dump control plane version, logs, config maps, and proxy info for all control plane pods.
> istioctl dump control-plane

# Dumps the envoy info ( /config_dump, /clusters, /stats, /certs (?), /memory) for all pods
> istioctl dump proxy -l `app in (myapp)` -n mynamespace

# Dumps only selected pods
> istioctl dump logs -l 'app in (myapp)' -n mynamespace

# Dumps selected pods in the given namespace
> istioctl dump logs -l `app in (myapp)` -n mynamespace

# All of these commands have the option to direct output to a directory
# where we can nicely organize the outputs.
> istioctl dump all -f /tmp/mydir
``` 

WDYT?

**Comment by mandarjog** [comment]
Hey @fpesce is this done now? If not please reopen .

**Comment by howardjohn** [comment]
open...

**Comment by howardjohn** [comment]
???

**Comment by howardjohn** [comment]
@therealmitchconnors what is going on?

**Comment by mandarjog** [comment]
The bot believes that there should not be any more work on this issue.

**Comment by bianpengyuan** [comment]
@ostromart @mandarjog Does the new bug report tool take over this? Shall we close this issue or create a new one against bug report tool if it does not support the feature described in this issue?

**Comment by bianpengyuan** [comment]
I moved to 1.9 for now, since this is not a blocking issue for 1.8. Let me know if this is not the case, thanks!

**Comment by howardjohn** [comment]
I think this is addresed by bug report
