### ISSUE TITLE
Operator should consider reducing golang dependencies

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#17245]
Looking at the operator code, which is directly linked into istioctl, there is a very large amount of dependencies. Some examples are depending on the entire `k8s.io/kubernetes` and Helm Tiller. It seems most of these usages are not really needed.

We should consider reducing this, because it makes upgrades in istio/istio much harder.

**Comment by howardjohn** [comment]
This is going to block stuff like https://github.com/istio/istio/issues/17158 if not fixed. Alternatively, we can split istioctl out of the istio/istio build process

**Comment by costinm** [comment]
Unlikely to happen in 1.4 - helm is needed. I agree it would be better to split istioctl out of istio/istio, and even revisit the decision to have a single binary that links everything in. 
However with the plan to move config to Mesh.yaml and start reducing the dependency on helm, and possibly the number of components - we may be better off waiting until this stabilizes, and just stop using templates and helm if it works out.

**Comment by ostromart** [comment]
I'd love to get helm out as well which I think starts to look realistic for post 1.5. If we can work towards migrating everything we need into meshconfig in 1.5 then we should be in a position to pull the plug for 1.6. 
I also think it's a great idea to move istioctl out to a separate repo which will remove all the deps due to operator. 
Finally, many of the k8s deps are due to the controller rather than the pkgs istioctl uses so some restructuring here will reduce the transitive k8s deps that istioctl pulls in.

**Comment by howardjohn** [comment]
done
