### ISSUE TITLE
Injection analyzer needs to deal with Istio being enabled by default

### ISSUE THREAD

**Issue by davidebbo** [istio/istio#17279]
galley/pkg/config/analysis/analyzers/injection/injection.go currently assumes the default is off, but it can be turned on `sidecarInjectorWebhook.enableNamespacesByDefault=true` in the istio-sidecar-injector configmap.

[Seems I'm not a member yet, but please assign to me]

**Comment by sushicw** [comment]
Do you have an example of how this is used in the configmap? I don't see any code that parses this value out for injection. AFAICT we're just using the helm variable directly in the [mutatingwebhook helm template](https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/sidecarInjectorWebhook/templates/mutatingwebhook.yaml). Doesn't that mean that changing the value in the config map would be a no-op, or am I missing something? 

Regardless, we still need to make the analyzer smarter, but the path to doing so may require looking at the mutatingwebhookconfiguration resource instead of the configmap. I don't believe we have any runtime access to the values of helm variables, do we? 

P.S. When we do fix this we should make sure we document in the associated doc that the error can also be fixed in this way.
