### ISSUE TITLE
First class workloads in Istio

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1727]
(thoughts after discussion with @mandarjog @louiscryan)

There is currently a gap in Istio model for naming and assigning config to workloads. We've made a simplifying assumption early on that workloads (e.g. pods) carry _source service_ attribute, and that drives the entire Istio request processing workflow from pilot configuring envoys to mixer selecting configs for a request. We need to address this soon, as it creates constant tension within the model (examples: not allowing dual service pods, source labels referring to pod labels rather than service labels, prioritizing app label as special, etc).

For Pilot (cc @rshriram): 
- the selection of local instances should not be based on service model, but instead on the workload description. Sidecar proxy should expose the ports that are declared by the workload. HTTP features would require an extra annotation on the pod to enable HTTP filtering. The inbound listeners can be opened prior to registration with the service, and remain open for the lifecycle of the workload. Concretely, service/deployment model needs to expose an interface:
```go
func WorkloadDescription(id string) []Port
```
which can be used either statically through injection or dynamically through xDS.

- the selection of rules by source should be driven by the source _workload_ properties. The workload has a unique identity, labels, and may or may not have multiple services associated through the service model. Concretely, the config model needs to be oriented towards this interface:
```go
func RouteRules(sourceWorkloadSelector LabelOrNameSelector, destinatioService LabelOrNameSelector) []RouteRule 
```

Secondary, the selection of rules for inbound traffic should be avoided. Once we permit workloads with no services, we no longer control the traffic from it. We should find another solution for WS protocol support.

For Mixer (cc @mandarjog, @ayj ):
- the server side proxy can only reliably supply `destination.workload` attributes. Destination services need to be inferred either by Pilot or by Mixer and supplied dynamically. All configuration within Mixer filter should dynamically adjust and allow multiple `destination.services`.

**Comment by ayj** [comment]
`source.workload` instead of `source.service` makes some sense. The need for `destination.workload` is less clear to me.

A server Proxy/Mixerclient needs to invoke Check() conditional on local route/domain/port info (e.g. destination.service) for things like Quota and APISpec and not simply rely on Mixer to disambiguate.

**Comment by kyessenov** [comment]
@ayj agree that destination workload should _always_ lead to derivation of a derivation service. I can't come with a case when a workload can address another workload without a name. This derivation can be made deterministic with mTLS and authority enforcement. I'm suggesting here that either Mixer or Pilot needs to push the derived attribute down to the proxy.

**Comment by costinm** [comment]
I think it is reasonable to make most decisions based on the identity and
attributes of the workload - both for source and destination.

source.service doesn't make any sense - a workload initiates the request,
and it may belong to multiple services with no way to
determine in which capacity it is acting.

destination.service is also tricky - what if a request is made directly to
the IP.

My only concern is to make sure this is implemented in a way that is
flexible enough for VMs. Ideally the workload itself
in case of VMs should be able to supply the information without additional
complexity and overhead, since the workload
info is quite deterministic and can be know by the workload.


Another important concept that is starting to become important is that of
'canonical name' - where a workload or
service may be associated with multiple names, but for purpose of policy
and logging wants to use a specific
name. If such a 'canonical name' becomes a feature - I think it should
override any workload or service identity that
may be guessed/derived by us.

Costin

**Comment by ayj** [comment]
> destination.service is also tricky - what if a request is made directly to
the IP.

Mixerclient defines policy (e.g. quota, apispec, authn) per service. Pilot can provide service identity through authority (e.g. domain:port) with some reasonable default behavior (e.g. falllback default service name).

**Comment by kyessenov** [comment]
ping @rshriram. I'd like to eliminate `HostInstances` use and use workload IP as the query key. This has several implications:
1. inbound calls are TCP by default (override requires pod annotations)
2. health ports are extracted from pod template and are opened up automatically.
3. mTLS vs health ports are reconciled per pod.
4. mixerfilter needs conditional attributes.

**Comment by rshriram** [comment]
Well, I am glad that you have finally decided to ditch the host level sidecar :). While this is generally in the right direction, my main concern is that we are losing a bunch of out of the box features that users have become used to so far. The key feature being metrics for inbound http, and the access logs on the inbound path.

Not worried about websockets because it works out of the box with tcp listener in the inbound path. Another issue is tracing, though its not that bad, because if a user is going to modify the service to propagate trace headers, adding port level annotation is not a big deal.

Why can't we detect the listener type based on the port name, if present in the right format, like http-foo ?

We already do (2), unless you mean that we no longer have to explicitly extract health ports and create TCP listeners for them.

(3) what do you mean? what is mTLS port? This still does not solve the mTLS with health check issue. This is not going to solve the `mixer filter not working for health check ` issue either since the mixer expects or wants to derive destination.service attribute, and that is not available until the readiness probes pass.

(4) what type of conditional attributes?

**Comment by kyessenov** [comment]
Re-assigned to @rshriram since he's driving v1alpha2 design. Workloads ultimately should be surfaced there.

**Comment by louiscryan** [comment]
I think this issue is stale. The new networking APIs are in place and we've ironed out some of the attribution concerns and others are being tracked elsewhere.
