### ISSUE TITLE
bundled certmanager will be blocked on 1st November

### ISSUE THREAD

**Issue by robotlovesyou** [istio/istio#17356]
**Bug description**
I'm currently running a v1.2 cluster with certmanager and ingress-sds enabled. I have recieved an email from jetstack warning me that they will be disabling all versions of certmanager below 0.8.0 on 1st November 2019, which is pretty soon. The bundled version is 0.6.2

I've checked the chart for 1.3 and it is still installing version 0.6.2.

Patching to version 0.8.0 of certmanager appears to work so far, but my tests have not yet been very thorough

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
A version of certmanager which will not be disabled soon is installed.

**Steps to reproduce the bug**
Install istio with certmanager enabled. Version 0.6.2 will be installed

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
istio version 1.2
kubectl version 1.13.7

**How was Istio installed?**
Helm/Tiller

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

**Comment by howardjohn** [comment]
We are likely going to be pushing people to install certmanager using the upstream installation methods https://github.com/istio/istio.io/issues/5022

We don't really do anything custom in the certmanager install, we don't have tests for it, and we don't really have anyone maintaining it (hence the 0.6.2 version), so it doesn't really make sense for us to manage it.

That being said, it does seem like the fix is just to change 0.6.2 -> 0.8.0, so if that does work we could do that in the mean time

**Comment by howardjohn** [comment]
We have removed our bundled certmanager
