### ISSUE TITLE
HTTP request with special X-Request-Id can NOT be traced in Istio

### ISSUE THREAD

**Issue by idouba** [istio/istio#17437]
curl  a service with following two ways:
```
curl http://svc:20888/path  -H 'X-Request-Id: 8cda17a5-eb41-4ced-9843-acc826f95c8c'
curl http://svc:20888/path -H 'X-Request-Id: 27290d28d5c38da315a78399d71fc20b'
```
The former request with a valid uuid as x-request-id can be  traced successfully,
while the latter with a invalid uuid does not be traced, thex-request-id is generated by some old app. 

My question is why the formation of  x-request-id affects the tracing.

**Comment by idouba** [comment]
@douglas-reid  could pls help check it?

**Comment by kyessenov** [comment]
Envoy uses request ID to correlate requests across hops for tracing and logging. Typically, Envoy generates one for external origin requests and for internally generated requests due to this flag https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/network/http_connection_manager/v2/http_connection_manager.proto#envoy-api-field-config-filter-network-http-connection-manager-v2-httpconnectionmanager-idle-timeout, and then the application is responsible to propagate it.

**Comment by kyessenov** [comment]
Please use https://discuss.istio.io for further questions.
