### ISSUE TITLE
Move new installer to Mixer v2 by default

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#17450]
Currently we are shipping Mixer by default. For the operator it may make sense to start shipping mixerv2 by default instead - while still support mixer until mixerv2 is stable. This will simplify the install and encourage people to move off of mixer

@douglas-reid @costinm

**Comment by mandarjog** [comment]
Mixerv2 is still at least 1 (possibly 2) quarters away from claiming full parity with Mixer.

If this is only about switching the defaults for to MixerV2, I support it.
caveat: It only support http for now, tcp support will be added in 1.4

We should *not* preclude users from using Mixer, because they choose to use the operator.

**Comment by howardjohn** [comment]
I would agree. Ideally we could use the operator as an opportunity to simplify install and only support mixerv2, but due to lack of parity we probably can't - we don't want people deciding between TCP telemetry/stability and operator. That is why I would suggest we make it disabled by default, but still supported
