### ISSUE TITLE
Double click TAB key after `make` command shows less goals

### ISSUE THREAD

**Issue by waret** [istio/istio#17483]
When double click TAB key, after `make` command, goals from Makefile.core.mk and tools/istio-docker.mk are no longer prompted.
After my testing,  when comment out the line `.DEFAULT_GOAL := default` in Makefile.overrides.mk, it turns ok. And this line was introduced by #17370

**Comment by howardjohn** [comment]
My tab completion never works not since we have `Makefile.core.mk` instead of `Makefile`, regardless of the `DEFAULT_GOAL`. Curious what setup you have?

**Comment by XanderStrike** [comment]
I composed an alternative dynamic bash completion script for another project that works _okay_ for istio. It errs on the side of showing more targets than are actually possible because it digs down recursively for any makefile that _might_ be included. It only works in the root directory of the repo.

    complete -W "\`find . -iname \"?akefil*\" | grep -v vendor | xargs -I {} grep -hoE '^[a-zA-Z0-9_.-]+:([^=]|$)' {} | sed 's/[^a-zA-Z0-9_.-]*$//' | sort -u\`" make

I have this in my bash profile, but it could be made more accurate and added to an `.envrc` or something

**Comment by waret** [comment]
on my mac:
- without `DEFAULT_GOAL` or `complete...`, there are 249 possibilities
- with or without `DEFAULT_GOAL, but with `complete...`, there are 109 possibilities

on centos 7 vm:
- with or without `DEFAULT_GOAL, but with `complete...`, there are 109 possibilities
