### ISSUE TITLE
Analyzers & the new config analysis framework

### ISSUE THREAD

**Issue by sushicw** [istio/istio#17499]
The new analysis framework has reached a point where we can usefully add analyzers. This serves as a parent issue to track specific analyzers that should be added, as well as further improvements and fixes to the framework.

[Multi-object validation overview](https://docs.google.com/document/d/1m19jkLyiIXNmUH_TYClRH-IOmuCJO4-vduy5KaCa99E/edit#)

[README](https://github.com/istio/istio/blob/master/galley/pkg/config/analysis/README.md) for creating analyzers

[Survey of multi-object validation tools for Istio and K8s](https://docs.google.com/document/d/1cXQ1kpaCjcERw5lAiBB9HRnE0Qenlv7Dt_OpNzwi-ZA/edit#) - Useful inspiration for what would be some high-value targets

[Slack channel](https://istio.slack.com/archives/CNA8KLE3X) specific to config analysis

**Comment by lucasponce** [comment]
cc @xeviknal and @burmanm

One action item would be to study which validations performed in Kiali:
https://www.kiali.io/documentation/validations/

Can be ported as part of Istio analyzers using the analyzer framework.
Individual validations can be added as separated issues and linked with this Epic.

One note that was discussed yesterday is that @sushicw is also looking for feedback from the initial framework, so any improvement and/or ideas are welcome.

**Comment by sushicw** [comment]
@lucasponce @nrjpoddar 

I went ahead and did exactly that, and added issues to this epic for creating analyzers that cover nearly everything from Kiali and istio-vet. If you don't mind, PTAL and make sure I've got it more or less right. :) 

Below is the list of validations that I have so far *not* added to the epic, and why (comments appreciated!):

*From istio-vet:*
* We already have analyzers that should be covering these. (But please do check to make sure that the implementations aren't missing something important!)
    * https://github.com/aspenmesh/istio-vet/blob/master/pkg/vetter/danglingroutedestinationhost/README.md
* This is purely informational, and doesn't actually do any validation:
    * https://github.com/aspenmesh/istio-vet/blob/master/pkg/vetter/podsinmesh/README.md
* I'm not sure on this one, it seemed like enforcement of a best practice rather than something that causes direct problems, but maybe I'm wrong about that?
    * https://github.com/aspenmesh/istio-vet/blob/master/pkg/vetter/applabel/README.md

*From Kiali:*
* We already have analyzers that should be covering these. (But please do check to make sure that the implementations aren't missing something important!)
    * https://www.kiali.io/documentation/validations/#_more_than_one_gateway_for_the_same_host_port_combination
    * https://www.kiali.io/documentation/validations/#_destinationweight_on_route_doesn_t_have_a_valid_service_host_not_found
    * https://www.kiali.io/documentation/validations/#_virtualservice_is_pointing_to_a_non_existent_gateway
    * https://www.kiali.io/documentation/validations/#_subset_not_found
* This is covered by single-object validation (enforced by the admission webhook) already, isn't it? (If not, it should be!)
    * https://www.kiali.io/documentation/validations/#_virtualservice_doesn_t_define_any_route_protocol
* This is a purely k8s error, so it seems like it's outside the scope of what Istio should validate. But maybe we can make a case for doing it anyway?
    * https://www.kiali.io/documentation/validations/#_service_port_and_deployment_port_do_not_match
* The error underlying this should be covered with an existing analyzer, but we're not generating a specific error message about the cross-namespace problem. Do you think we should?
    * https://www.kiali.io/documentation/validations/#_servicerole_does_not_exists_in_this_namespace

**Comment by nrjpoddar** [comment]
@sushicw you're missing https://github.com/aspenmesh/istio-vet/tree/master/pkg/vetter/invalidserviceforjwtpolicy which we added recently.

**Comment by nrjpoddar** [comment]
I have issues filed for these two which are very helpful:

https://github.com/aspenmesh/istio-vet/issues/61
https://github.com/aspenmesh/istio-vet/issues/63

**Comment by sushicw** [comment]
@nrjpoddar 

> @sushicw you're missing https://github.com/aspenmesh/istio-vet/tree/master/pkg/vetter/invalidserviceforjwtpolicy which we added recently.

Nice! Added it. (By the way, you may also want to add a reference to this on your main README.md file in istio-vet, I didn't see it there.)

> I have issues filed for these two which are very helpful:
> 
> aspenmesh/istio-vet#61
> aspenmesh/istio-vet#63

I agree, those do sound helpful. Can you please create issues for them and attach them to this epic?

**Comment by nrjpoddar** [comment]
I agree, those do sound helpful. Can you please create issues for them and attach them to this epic? -> @sushicw done.

**Comment by xeviknal** [comment]
> From Kiali:
> 
> - We already have analyzers that should be covering these. (But please do check to make sure that the implementations aren't missing something important!)
>   - https://www.kiali.io/documentation/validations/#_more_than_one_gateway_for_the_same_host_port_combination

As far as I understood, the currently implemented analyzers don't cover this scenario. In that scenario Kiali tries to cover the fact of two Gateways that points to the same host and port. What I could see in the [Gateway Analyzer](https://github.com/istio/istio/blob/master/galley/pkg/config/analysis/analyzers/gateway/gateway.go#L114) is that it covers the ['No matching workload found for gateway selector in this namespace'](https://www.kiali.io/documentation/validations/#_no_matching_workload_found_for_gateway_selector_in_this_namespace)

>   - https://www.kiali.io/documentation/validations/#_destinationweight_on_route_doesn_t_have_a_valid_service_host_not_found

Yes, I believe is already covered in [DestinationHosts Analyzer](https://github.com/istio/istio/blob/master/galley/pkg/config/analysis/analyzers/virtualservice/destinationhosts.go#L71).

>   - https://www.kiali.io/documentation/validations/#_virtualservice_is_pointing_to_a_non_existent_gateway

Yes, I believe is already covered in [Gateways Analyzer](https://github.com/istio/istio/blob/master/galley/pkg/config/analysis/analyzers/virtualservice/gateways.go)

>   - https://www.kiali.io/documentation/validations/#_subset_not_found

You are right. Implemented in the [DestinationRule Analyzer](https://github.com/istio/istio/blob/master/galley/pkg/config/analysis/analyzers/virtualservice/destinationrules.go)

> - This is covered by single-object validation (enforced by the admission webhook) already, isn't it? (If not, it should be!)
>   - https://www.kiali.io/documentation/validations/#_virtualservice_doesn_t_define_any_route_protocol

You are right. Just checked that and this validation is no longer necessary.

> - This is a purely k8s error, so it seems like it's outside the scope of what Istio should validate. But maybe we can make a case for doing it anyway?
>   - https://www.kiali.io/documentation/validations/#_service_port_and_deployment_port_do_not_match

Yes, it is up to you guys. We found that scenario useful for our users. And as you said, it probably makes sense at Kiali level but not that much at Istio level, IMO.

> - The error underlying this should be covered with an existing analyzer, but we're not generating a specific error message about the cross-namespace problem. Do you think we should?
>   - https://www.kiali.io/documentation/validations/#_servicerole_does_not_exists_in_this_namespace

Yep, I see this is already covered in the [Auth/ServiceRoleBinding](https://github.com/istio/istio/blob/master/galley/pkg/config/analysis/analyzers/auth/servicerolebindings.go). Regarding the namespace mention in the validation: In kiali adopted the position to only perform the validation within the same namespace. One of the reasons for this was because of the performance. It was really costly for us to fetch the whole cluster information in order to process a search. Said that, we started to have more clear messages like this one you mentioned.
So, no action required for this one either.

**Comment by sushicw** [comment]
> > From Kiali:
> > 
> > * We already have analyzers that should be covering these. (But please do check to make sure that the implementations aren't missing something important!)
> >   
> >   * https://www.kiali.io/documentation/validations/#_more_than_one_gateway_for_the_same_host_port_combination
> 
> As far as I understood, the currently implemented analyzers don't cover this scenario. In that scenario Kiali tries to cover the fact of two Gateways that points to the same host and port. What I could see in the [Gateway Analyzer](https://github.com/istio/istio/blob/master/galley/pkg/config/analysis/analyzers/gateway/gateway.go#L114) is that it covers the ['No matching workload found for gateway selector in this namespace'](https://www.kiali.io/documentation/validations/#_no_matching_workload_found_for_gateway_selector_in_this_namespace)

You're absolutely right. Added an issue to track this one. Thanks for vetting these for me!

**Comment by howardjohn** [comment]
this is implemented
