### ISSUE TITLE
istioctl add-to-mesh confusing messages

### ISSUE THREAD

**Issue by esnible** [istio/istio#17559]
To reproduce:

```
istioctl --istioNamespace=foo x add-to-mesh service bar
Error: could not read valid configmap "istio" from namespace  "istio-system": configmaps "istio" not found - Use --meshConfigFile or re-run kube-inject with `-i <istioSystemNamespace> and ensure valid MeshConfig exists
```

There are two spaces between `namespace` and `"istio-system"`.
The user ran `add-to-mesh`, not `kube-inject`, but the message says `kube-inject`.

**Comment by waret** [comment]
This message is from func `getMeshConfigFromConfigMap` of istioctl/cmd/kubeinject.go, and called by both `add-to-mesh` and `kube-inject`. One way to solve this problem is to to pass the command through the parameter.

https://github.com/istio/istio/blob/f7858d54bea424b495d5b09c4685c1f45f6dcac3/istioctl/cmd/kubeinject.go#L57-L82
