### ISSUE TITLE
Fix for [YellowSquirrel] not correctly applied over 1.2.7 and 1.1.16

### ISSUE THREAD

**Issue by fpesce** [istio/istio#17735]
**Bug description**
request.total_size reports 0 (as seen in several unit tests failing) instead of accurate size
**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

c.f. https://github.com/istio/proxy/commit/2846f60b51c56083cd0f15235aabfaf637047179
is the correct implementation with call to refreshByteSize()

https://github.com/istio/proxy/commit/a95f0c8cedd900b297b9443f0ab17b12d189e382 and 
https://github.com/istio/proxy/commit/fa97ad1e58c3cff4191abba5c1879aa05bd110da

just call byteSize().value_or(0)

**Comment by fpesce** [comment]
Important to mention, the vulnerability is correctly addressed, but all mixer features using request.total_size might be broken right now.

**Comment by lambdai** [comment]
More precisely, total_size might omit the header and trailer size.

**Comment by kyessenov** [comment]
@lambdai can you check Mixer v2 implementation here: https://github.com/envoyproxy/envoy/blob/master/source/extensions/filters/common/expr/context.cc#L82

**Comment by lambdai** [comment]
The envoy core change the promise: 
1. byteSize() return the header size cache
2. refreshByteSize() does recalculation and refresh the cache: so the method is not const
3. byteSizeInternal() does recalculation but not update the cache: it's const method. 

I choose the method 3 in 1.1 and 1.2 because @mandarjog confirms that the cost is limited in mixer filter.

I don't have the full context of mixer v2. Is it still true that mixer v2 api will calculate header size with a upper limit? If so method 3 can also be applied to mixer v2

**Comment by fpesce** [comment]
NB: This affects https://github.com/istio/istio/pull/17707 and https://github.com/istio/istio/pull/17698
They must be force-merged despite this bug being present to reflect the state of published (privately-built) releases.
(adding this comment added for building cross reference with this PR)

**Comment by fpesce** [comment]
Merged.
