### ISSUE TITLE
Istioctl Operator CLI release is using incorrect default hub and tag from installer repo 

### ISSUE THREAD

**Issue by elfinhe** [istio/istio#17799]
Now the released operator CLI is using 
```yaml
  hub: gcr.io/istio-release
  tag: master-latest-daily
```
by default, which is directly retrieved from installer repo by giving a sha to a revision and complied into binary.

But when Istio get released, the hub and tag for the current installation method (`helm template`) will be replaced with the defaults like below:
```yaml
  hub: docker.io/istio
  tag: 1.3.2
```

Using daily build is not a good practice, we should change operator CLI to align with the release version.

**Comment by howardjohn** [comment]
Talked to @ostromart, some thoughts:

The operator bakes the charts into the binary, so we cannot do the simple string replace we do for istio/istio. Note that we *do* do this replace on the operator charts packaged in the archive here: https://gcsweb.istio.io/gcs/istio-build/dev/1.4-alpha.ecbed5df617655d6aa72a7b9d19204294fecf7c5. 

Some possible ideas:
* When we build istioctl, checkout istio/operator, `sed` the charts, rebuild the vfsgen, add a replace directive to `go.mod`, then build istioctl. I don't really like this, because then we are not actually building the sources that are in git.
* We add a new variable `operatorHub` `operatorTag` into istioctl. We always pass these as the default flags to the operator code. These can be set at build time with `-ldflags -X operatorHub=foo -X operatorTag=bad`. This may be sort of hard to pass these flags through.

Both are not great solutions, so I am open to others.

**Comment by elfinhe** [comment]
@ostromart Hi Martin, what's your take on this?

**Comment by ostromart** [comment]
After mulling this over and chatting with John I haven't been able to think of anything better than the ldflags idea that wouldn't require a lot of effort.

**Comment by ostromart** [comment]
Already fixed for istioctl, still need fix for controller.

**Comment by ostromart** [comment]
https://github.com/istio/operator/pull/566
