### ISSUE TITLE
Citadel cannot rotate certs with plugged external CA

### ISSUE THREAD

**Issue by ayj** [istio/istio#17835]
Cert rotation fails with plugged external CA. The self-signed root check in `scrtUpdated` in workloadsecret.go fails to find `istio-ca-secret` and returns with an error without updating the cert. 

The logs show a lot of the following:

```
2019-10-13T03:53:36.944455Z     error   k8sController   Fail to load CA secret istio-system:istio-ca-secret (error: secrets "istio-ca-secret" not found), skip updating secret istio.pvc-protection-controller
2019-10-13T03:53:37.144176Z     error   k8sController   Fail to load CA secret istio-system:istio-ca-secret (error: secrets "istio-ca-secret" not found), skip updating secret istio.clusterrole-aggregation-controller
```

**Comment by myidpt** [comment]
I think we should not log this false alarm. Jimmy, can workloadsecret.go check if the system is using self-signed cert? if not, we should skip this.
In the near future, we will need to handle multiple Citadels be able to handle updated plugin certs. But that's a TODO.

**Comment by JimmyCYJ** [comment]
Yes, for plugin cert mode, we don't start root cert rotator. 
Currently in the workload secret controller, it checks if root cert in local key cert bundle is the same as the root cert in workload secret. If they are not identical, the secret controller tries to fetch istio-ca-secret and reload root cert into local key cert bundle.

When Citadel is in plugin mode, the root cert in local key cert bundle and root cert in workload secret should always be identical, therefore workload secret controller will not fetch istio-ca-secret.
This is because Citadel reads cert from file during only once (when Citadel starts).

I will add a check for the plugin mode in workload secret controller and fetching istio-ca-secret if that is true.

**Comment by JimmyCYJ** [comment]
This issue should be fixed in https://github.com/istio/istio/pull/18713. Closing now. Please feel free to reopen the issue. Thanks.
