### ISSUE TITLE
istioctl analyze (and validate) accidentally log deprecation warnings

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#17842]
```
$ ik x analyze -k
2019-10-13T23:34:29.932463Z     warn    envoy filter: Filters is deprecated. use configPatches instead
2019-10-13T23:34:29.932510Z     warn    envoy filter: workloadLabels is deprecated. use workloadSelector instead
Warn [IST0004](EnvoyFilter/istio-system/istio-multicluster-egressgateway) Deprecated: EnvoyFilter.workloadLabels is deprecated; use EnvoyFilter.workload_selector
Warn [IST0004](EnvoyFilter/istio-system/istio-multicluster-egressgateway) Deprecated: EnvoyFilter.filters is deprecated
```

Reproduce by applying this yaml:

```yaml
apiVersion: v1
items:
- apiVersion: networking.istio.io/v1alpha3
  kind: EnvoyFilter
  metadata:
    annotations:
      install.operator.istio.io/owner-generation: "2"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"networking.istio.io/v1alpha3","kind":"EnvoyFilter","metadata":{"annotations":{"install.operator.istio.io/owner-generation":"2"},"labels":{"app":"istio-egressgateway","install.operator.istio.io/owner-group":"install.istio.io","install.operator.istio.io/owner-kind":"IstioControlPlane","install.operator.istio.io/owner-name":"example-istiocontrolplane","release":"istio"},"name":"istio-multicluster-egressgateway","namespace":"istio-system"},"spec":{"filters":[{"filterConfig":{},"filterName":"envoy.filters.network.sni_cluster","filterType":"NETWORK","listenerMatch":{"listenerType":"GATEWAY","portNumber":15443}}],"workloadLabels":{"istio":"egressgateway"}}}
    creationTimestamp: "2019-10-13T23:31:13Z"
    generation: 1
    labels:
      app: istio-egressgateway
      install.operator.istio.io/owner-group: install.istio.io
      install.operator.istio.io/owner-kind: IstioControlPlane
      install.operator.istio.io/owner-name: example-istiocontrolplane
      release: istio
    name: istio-multicluster-egressgateway
    namespace: istio-system
    resourceVersion: "13478453"
    selfLink: /apis/networking.istio.io/v1alpha3/namespaces/istio-system/envoyfilters/istio-multicluster-egressgateway
    uid: 8b988e5e-ee11-11e9-854d-42010a800fcb
  spec:
    filters:
    - filterConfig: {}
      filterName: envoy.filters.network.sni_cluster
      filterType: NETWORK
      listenerMatch:
        listenerType: GATEWAY
        portNumber: 15443
    workloadLabels:
      istio: egressgateway
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

**Comment by esnible** [comment]
@howardjohn Thanks for finding this.  The problem is not unique to `istioctl analyze`, I see the same thing in `istioctl validate`.  Changing title.

To reproduce with `istioctl validate`:

```
@sushicw This is caused by your work to bring in existing Istio validations: https://github.com/istio/istio/pull/17770

@howardjohn @ozevren The bigger problem is there is a disconnect between what we want when running on a control plane pre-Analysis framework, and what we want running in a CLI with an Analysis framework.

There are two ways to solve this.  One is to eliminate all `log.Warn()` in validations, on the assumption that Istio users will no longer be looking through ```

**Comment by esnible** [comment]
@sushicw This is caused by your work to bring in existing Istio validations: https://github.com/istio/istio/pull/17770

@howardjohn @ozevren The bigger problem is there is a disconnect between what we want when running on a control plane pre-Analysis framework, and what we want running in a CLI with an Analysis framework.

There are several ways to solve this.

- Eliminate all `log.Warn()` in validations, on the assumption that Istio users will no longer be looking through Webhook logs to find deprecated fields.
- Turn of warning-level logging on `istioctl` the way we do for `istioctl kube-inject`.
- Have this code get log level from a Go context or Istio structure instead of always using Warn

Does anyone have a preference for how to handle this in 1.4?

**Comment by howardjohn** [comment]
Seems like we should just disable logs on all Istioctl commands, do we ever want logs? Seems like logging is a server thing, explicit printing is a CLI thing, and we never really want them mixed?

**Comment by sushicw** [comment]
@esnible @howardjohn 
This behavior exists for `istioctl validate` in 1.3 as well, actually. 

> Seems like we should just disable logs on all Istioctl commands, do we ever want logs? Seems like logging is a server thing, explicit printing is a CLI thing, and we never really want them mixed?

The exception that comes to mind is debugging. While as a user I never want to see logs, as a dev it's very useful to be able to use the `--log_output_level` controls to get a clearer view of what's going on in the tool. 

The default log level of INFO can be overriden per-scope here: https://github.com/istio/istio/blob/master/istioctl/cmd/root.go#L60-L68 An immediate tactical option is to just add the `envoy` scope as one that has a ERROR as the default log level instead of INFO, like we do for `processing` and `source`. Any objections to that? 

If we want to go further, we can just set the default log level to NONE, and require explicit opt-in to any log output via `--log_output_level`.
