### ISSUE TITLE
istioctl x analyze should display istioctl-style names for resources

### ISSUE THREAD

**Issue by esnible** [istio/istio#17924]
Instead of

```
Error [IST0101](VirtualService/default/productpage) Referenced host not found: "productpage"
```

We should show `virtualservice productpage.default`.

Instead of

```
Error [IST0106] The resource has one or more schema validation errors: unsupported protocol: UnsupportedProtocol
```

We should output the resource.

cc @sushicw

**Comment by esnible** [comment]
Because the origin is hidden in an interface I can't format it differently in _istioctl_.

In istioctl we format pod names as <name>[.<namespace>], and we leave off the namespace if it matches the default namespace.

I am not sure if we should change the "friendly name" code throughout the Analyze framework, or just for _istioctl_ output.

**Comment by sushicw** [comment]
I'm pretty sure we can just update the FriendlyName implementation function for kube resources here: https://github.com/istio/istio/blob/master/galley/pkg/config/source/kube/rt/origin.go#L35-L38

There shouldn't be anything depending structurally on the format.

**Comment by esnible** [comment]
@sushicw I am happy to take this on if it is merely updating the FriendlyName implementation.  To make FriendlyName() work like the other _istioctl_ outputs I could pass in a "namespaceContext string", if it matched the namespace then the namespace would be suppressed.  That felt like too much behavior to bake into FriendlyName().  I am struggling because the method is supposed to be independent of Kubernetes, but Kubernetes is the only implementation we have.  It isn't clear what a generic non-Kube FriendlyName would look like.

**Comment by sushicw** [comment]
I think we're OK doing the simple thing. The file we're updating *is* the kube-specific implementation, so it's OK for it to use kube-specific conventions. I don't think we're making istioctl any more kube-coupled than it is already. 

By the way, the second issue you mention here (where the resource is missing) is happening because the resource being evaluated was generated at runtime (e.g. synthetic service entries, or virtualservices auto-generated from a k8s ingress resource). That issue is discussed / tracked in more detail in https://github.com/istio/istio/issues/17807.
