### ISSUE TITLE
galley needs permission to list deployments

### ISSUE THREAD

**Issue by ayj** [istio/istio#18002]
https://github.com/istio/istio/pull/17714 added the deployment collection to galley. The clusterrole charts need to be updated with permission for this new resource. Otherwise the server-side analyzer feature won't work as expected and galley logs are filled with the following:

```
2019-10-17T20:59:32.051503Z     error   k8s.io/client-go@v11.0.1-0.20190409021438-1a26190bd76a+incompatible/tools/cache/reflector.go:98: Failed to list *unstructured.Unstructured: authorizationpolicies.security.istio.io is forbidden: User "system:serviceaccount:istio-system:istio-galley-service-account" cannot list resource "authorizationpolicies" in API group
"security.istio.io" at the cluster scope
```

**Comment by esnible** [comment]
@sushicw It seems we are traveling down a dark path.

Oz' comment https://github.com/istio/istio/issues/17272#issuecomment-539590894 suggested that it should be possible to get _istioctl_ to validate Deployments without Galley being aware of them.  It certainly doesn't need them.  Was Oz mistaken or did I screw up the implementation?

**Comment by sushicw** [comment]
As I understand it, right now a running galley instance shouldn't be paying any attention to deployments. The snapshots in [metadata.yaml](https://github.com/istio/istio/blob/master/galley/pkg/config/meta/metadata/metadata.yaml#L496) should be controlling that: galley uses the "default" and "synthetic" snapshots, while istioctl uses "localanalysis" and "synthetic."

But it looks like something is wrong, seeing this in my logs with enableAnalysis disabled:

```
2019-10-18T18:21:41.459711Z	error	k8s.io/client-go@v11.0.1-0.20190409021438-1a26190bd76a+incompatible/tools/cache/reflector.go:98: Failed to list *v1.Deployment: deployments.apps is forbidden: User "system:serviceaccount:istio-system:istio-galley-service-account" cannot list resource "deployments" in API group "apps" at the cluster scope
```

Tweaking the log levels and looking at the actual snapshot being published, it looks like Galley isn't including Deployments in the snapshot, so the outbound work is unpolluted at least.

Would it be a problem if Galley is listening to Deployment events, but not including them in distributed output? If not, let's just update the clusterrole permissions. Otherwise, I think there's some coding work to do to make Galley smarter about what it starts listeners for.

**Comment by esnible** [comment]
It is a waste of CPU for Galley to watch Deployments.  It has no interest in them.  Rather than granting it permission to watch them let's find a way to for Galley and Istioctl to select different sub-sets of resources.

**Comment by sushicw** [comment]
Noting a sub-mystery: why is Deployments getting a watcher, but services / pods / namespaces are not?

The answer is that we only watch the latter if service discovery is enabled. We have an "Excluded Resource Kinds" field that by default is based on the old set of resources in `galley/pkg/source/kube/builtin/types.go`. Deployments isn't included here, so the "disable kube built-ins unless service discovery is enabled" logic never kicks in. 

</tangent> I agree that we should just make Galley smarter. I think I know how to do that, so I'll take this.

**Comment by ayj** [comment]
+1 to making galley smarter.

**Comment by sushicw** [comment]
https://github.com/istio/istio/pull/18070 will fix the immediate issue. 

There's still future work to decouple the set of collections being analyzed from the collections being distributed, tracked as part of https://github.com/istio/istio/issues/17543.
