### ISSUE TITLE
TestTcpMetric flaky, especially on newer kubernetes versions

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#18105]
On k8s 1.14 and 1.16 fails ~50% of the time
* https://testgrid.k8s.io/istio_istio_postsubmit#integ-k8s-116_istio_postsubmit&width=20&exclude-non-failed-tests=
* https://testgrid.k8s.io/istio_istio_postsubmit#integ-k8s-114_istio_postsubmit&width=20&exclude-non-failed-tests=

On k8s 13, seems to fail much less: https://testgrid.k8s.io/istio_istio_postsubmit#integ-k8s-113_istio_postsubmit&width=20&exclude-non-failed-tests=

On k8s 1.12, doesn't seem to ever fail: https://testgrid.k8s.io/istio_istio_postsubmit#integ-k8s-112_istio_postsubmit&width=20&exclude-non-failed-tests=

**Comment by gargnupur** [comment]
Looks like values obtained from labels is null
istio_tcp_sent_bytes_total{connection_security_policy="unknown", destination_app="unknown", destination_principal="unknown", destination_service="mongodb.istio-bookinfo-1-17738.svc.cluster.local", destination_service_name="mongodb", destination_service_namespace="istio-bookinfo-1-17738", destination_version="unknown", destination_workload="unknown", destination_workload_namespace="unknown", instance="10.244.0.159:42422", job="istio-mesh", reporter="source", response_flags="-", source_app="ratings", source_principal="unknown", source_version="v2", source_workload="ratings-v2", source_workload_namespace="istio-bookinfo-1-17738"} => 0 @[1571881696.004]
Ex: destination_app: destination.labels["app"] | "unknown"

Doesn't look like anything changed with respect to labels in changelog(**https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.16.md#changelog-since-v1161**)
But to improve reliability of test I will change it to depend on attribute obtained directly from k8s.. 
destination_service_name (destination.service.name)

**Comment by howardjohn** [comment]
Are these relevant?
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.16.md#metrics-changes

**Comment by gargnupur** [comment]
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.16.md#metrics-changes saw these earlier too.. but nothing looks specific to this scenario..
