### ISSUE TITLE
Trim license whitelist

### ISSUE THREAD

**Issue by sdake** [istio/istio#18155]
**Bug description**
Copyleft licenses are used in the Istio dependency chain. Some legal people think that any transitive dependency that is copyleft changes the whole license to copyleft for the rest of the source base, making copyleft licenses fundamentally incompatible with ASL2.

See https://storage.googleapis.com/istio-prerelease/prerelease/1.4.0-alpha.0/LICENSES

**Comment by esnible** [comment]
I am not experience in Go Modules.  Given a package such as `modernc.org/cc` how do I determine the direct dependency?

I am not familiar with the output of the tool.  For modernc.org/cc I see six different licenses.  Is this an "or", where we can choose which of the licenses we are using the tool under?

`github.com/docker/docker` also seems to have multiple licenses.  One is GPL, but it also seems to have Apache 2.  We have a direct dependency to docker in our test framework, but not in our shipped components.

**Comment by sdake** [comment]
Direct dependencies are not the only concern.  Any transitive dependency is a problem IMO. `go mod graph` should help you answer some of your questions.

Cheers
-steve

**Comment by howardjohn** [comment]
modernc is not gpl license, but it vendors in TCC as testdata (it is some sort of compiler type module, so it using it as test data). Not sure if that means we can use it or not. Considering the dependency comes from k8s, its a sign maybe its fine? I have no clue :slightly_smiling_face: https://github.com/cznic/cc/blob/master/testdata/tcc-0.9.26/COPYING

Why do we have github.com/juju/errors whitelisted when its gplv3 though?

**Comment by howardjohn** [comment]
juju comes from one direct usage, which is easy to remove, and one direct usage from https://github.com/signalfx/golib/blob/58afbab2478d6a64752ad20ecf518ef881b934ee/Gopkg.toml#L86 which is potentionally extremely hard to remove. Interestingly, this is only used by signalfx to test compatibility: https://github.com/signalfx/golib/blob/master/errors/compatibility_test.go. It is NOT used in anything we import, but go modules pulls in test deps as well

**Comment by geeknoid** [comment]
@esnible "go mod why" will give you a dependency chain for a given module. The license tool we use grovels through the full transitive dependencies from go.mod. For each dependency, it extracts any LICENSE files within that module. Some modules have many LICENSE files, so they are all displayed by the tool.

The dependency on docker/docker was updated yesterday in master to a newer version which doesn't have GPL code in it. We should merge this to 1.4.

@howardjohn I've got a PR to remove the direct dependency we have on juju. We'll address the signalfx dependency in the next few days. The reason why juju was on the whitelist is because I just introduce license linting recently and created the whitelist at that time to grandfather in all modules so that things would build. Now that the steady state is achieved and we're not introducing new undesirable dependencies, we need to clean up the whitelist.

**Comment by esnible** [comment]
@geeknoid I have been looking at adding color to _istioctl_.  We indirectly require a color library, because the operator requires k8s.io/kubectl, and kubectl requires the color library.  Why does `go mod graph` tell me Istio requires a color library but not `go mod why [-m]`?

```
~/go/src/istio.io/istio$ go mod graph | grep color
k8s.io/kubectl@v0.0.0-20191003004222-1f3c0cd90ca9 github.com/daviddengcn/go-colortext@v0.0.0-20160507010035-511bcaf42ccd
~/go/src/istio.io/istio$ go mod why github.com/daviddengcn/go-colortext
# github.com/daviddengcn/go-colortext
(main module does not need package github.com/daviddengcn/go-colortext)
$ go mod why -m github.com/daviddengcn/go-colortext
# github.com/daviddengcn/go-colortext
(main module does not need module github.com/daviddengcn/go-colortext)
```

**Comment by geeknoid** [comment]
@esnible Not sure why there is this discrepancy. Maybe it has to do with direct vs. indirect dependency?

**Comment by howardjohn** [comment]
We removed signalFX and juju it sounds like, any other work to be done here? @geeknoid

**Comment by geeknoid** [comment]
The only other thing left would be to trim the license whitelist that's defined in common-files.

**Comment by howardjohn** [comment]
Thanks @geeknoid I assume thats not release blocker so I droppped it down
