### ISSUE TITLE
Consider sending "Not Ready" endpoints over EDS as unhealthy

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#18367]
Currently, we are only sending "Ready" endpoints over EDS. This makes some fields like minHealthPercent (panic threshold) a bit hard to reason about. If we keep removing endpoints from the endpoint set, then we keep moving the target. If envoy health checking perfectly aligned with k8s (generally it won't, since one is passive and one is active), you could never actually hit this since envoy would almost never have "unhealthy" endpoints -- Pilot would just remove them right when they became unhealthy.

This same applies to Locality load balancing. Generally, after some % of endpoints becomes unhealthy we start sending more and more traffic to other localities, but this % moving as endpoints are marked unhealthy by k8s readiness.

We should investigate other benefits of sending unhealthy endpoints, as well as costs/problems. 

This will of course be slightly less performant, but generally there are few "not ready" endpoints. We may actually see better performance in Envoy side for pods that are flipping between healthy/unhealthy.

@rshriram @hzxuzhonghu

**Comment by hzxuzhonghu** [comment]
I am concerned about too many not ready endpoints will lead to 503. As the default max retry is limited.

**Comment by howardjohn** [comment]
I mean we send them with "health_status=unhealthy" so traffic is not routed
to them

**Comment by ramaraochavali** [comment]
IMO, while it is good to not send an initial NOT ready endpoint to Envoy i.e Pod becomes initially ready, I think later flips back to Not ready/Live check failures should be better handled by Envoy. The outlier detection, retries etc are meant to handle such scenarios assuming that POD readiness/liveness flip is a transient one.  Otherwise control plane is doing what Envoy is supposed to do and if there is a gap , we should fix it in Envoy.

BTW, How will this work for VMs and external services created with service entries?

**Comment by howardjohn** [comment]
External services have no notion of 'not ready' in the service entry API, so there would be no changes there, this would only apply to k8s.

Just wondering, why do you think we should not send the initial not ready endpoint?

**Comment by ramaraochavali** [comment]
> External services have no notion of 'not ready' in the service entry API, so there would be no changes there, this would only apply to k8s.

Agree. I am more wondering about from the behavior perspective, not from the actual change. Those services will depend on Envoy's capabilities because control plane has no knowledge of their health/readiness.

> Just wondering, why do you think we should not send the initial not ready endpoint?

Because the instance is not ready even at least once - so was wondering what is the point in sending it to Envoy. Also if it hits lbpanic, it Envoy might route it to not ready endpoint (which we know for sure it is not ready). https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/panic_threshold#panic-threshold. But I agree we will have to investigate and see the behavior.

**Comment by howardjohn** [comment]
I see, that makes sense to me.. It would make the implementation much
easier if we sent all not ready endpoints. I'll think about it some more.
Thanks for the input

**Comment by brianwolfe** [comment]
@howardjohn we have confirmed this issue in our tests. When we simulate gradual failures (that fail both readiness probes and normal requests with 503s), we don't see traffic fail over to another availability zone even when 10% of the original hosts are ready to serve traffic.

Do you think this will be high enough priority to fix before istio 1.5? Sending all endpoints, including not ready endpoints, seems like a good solution to us.

**Comment by howardjohn** [comment]
I think its a good idea. One thing I would say is we should consider not send new not ready endpoints probably, or for every new pod we send 2x EDS pushes. 

One problem I can see with this approach is that if a pod goes from Healthy -> Unhealthy it is counted, but if it goes from Healthy -> Unhealthy -> Killed (liveness probe?) -> restarted and never gets healthy then it is not counted. I am not sure if that is worth the increased EDS load.

What do you think @brianwolfe @hzxuzhonghu

**Comment by brianwolfe** [comment]
I understand the excess load concern. Liveness probes should just kill/restart the container, which should leave the pod & endpoint stable if I understand correctly. We would still have significant EDS load if endpoints flap up and down, but that is already true.

Endpoint stability during liveness probe failures reduce the risk of the Healthy -> Unhealthy -> Killed -> Unhealthy loop IMO. I think the only times we should be seeing mass restarts are when doing major operations that cause imbalance (deploys, node draining, and forced pod restarts).

**Comment by howardjohn** [comment]
@brianwolfe good point about killing just the container, so it should be feasible. I guess we will just have to see if maintaining that state in Pilot is too complex to make the optimization worth it. Until a week ago or so we were actually triggering EDS pushes on not ready endpoints anyways (but they changed nothing), so we wouldn't regress in perf, just undo an optimization that hasn't yet been released

**Comment by hzxuzhonghu** [comment]
> I think its a good idea. One thing I would say is we should consider not send new not ready endpoints probably, or for every new pod we send 2x EDS pushes.

> One problem I can see with this approach is that if a pod goes from Healthy -> Unhealthy it is counted, but if it goes from Healthy -> Unhealthy -> Killed (liveness probe?) -> restarted and never gets healthy then it is not counted. I am not sure if that is worth the increased EDS load.

If we need this for failover, then we must send every endpoints no matter ready or not.  By this, we can achieve the expected behavior.  But as you said, the eds load may be doubled.  So i suggest we let users choose. If they do not need failover at all, we disable this, only send ready endpoints as before. Otherwise, enable this feature.

**Comment by brianwolfe** [comment]
@hzxuzhonghu if users have locality load balancing enabled, as by default when Outlier Detection is enabled, when would they not want failover?

**Comment by hzxuzhonghu** [comment]
As #18903 said, user may want to disable locality load balancing per service.

**Comment by yingzhuivy** [comment]
@howardjohn wondering if there is any update on this issue

**Comment by hzxuzhonghu** [comment]
We haven't done this as there are concerns.

**Comment by howardjohn** [comment]
not stale

**Comment by howardjohn** [comment]
not stale!!

**Comment by howardjohn** [comment]
...

**Comment by sangwa** [comment]
This issue is actual for us. We have a configuration with priority load balancing that requires the knowledge of unhealthy endpoints to function properly. Now we're considering transition to Istio as a control plane for our envoys and this feature is required to reproduce the configuration. There is another concern as there is no built-in support of priority routing settings in Istio AFAIK, but I suppose that can be implemented with bespoke EnvoyFilters. Having a more reliable locality failover would also be nice.

I think we can implement this under a feature flag in pilot and allow per-service control with annotations. I can submit a PR if there are no other plans to work on it soon.

**Comment by hzxuzhonghu** [comment]
There is a feature `PILOT_SEND_UNHEALTHY_ENDPOINTS`, you can enabled it, then unhealthy endpoints will be sent
