### ISSUE TITLE
Changes to Pilot to use MSA as an exclusive / additional source of endpoint registry 

### ISSUE THREAD

**Issue by gnirodi** [istio/istio#1839]
Design doc reference:  https://goo.gl/AQARBs#heading=h.3j0if6igt06b

This has yet to be fully fleshed out. So let's keep this for the last thing to do
Things to discuss:
1. We'd like Pilot to only fetch information on demand rather than asking for a complete mesh view. i.e. when Envoy asks for a particular service, Pilot queries MSA just for that service. We give a all info for that service with a TTL attached.
2. Pilot should invalidate its in-memory endpoint list for that service beyond the TTL
3. Whatever the Pilot sends to Envoy should also adhere to that TTL. Changes in Envoy ought to be a separate issue that depends on the current one.

**Comment by kyessenov** [comment]
Pilot/Envoy are entirely poll-based. You can achieve the TTLs by removing endpoints/services from MSA backend. You should also add DNS trapping to for on-demand requirement.

**Comment by kyessenov** [comment]
I'm strongly against making MSA as the only backend of pilot. Are you proposing Consul backends to MSA instead of Pilot?

**Comment by gnirodi** [comment]
Sure. Let's discuss pros cons on exclusive / additional in the design doc.

On the topic polling and TTL - I'm fine deferring the implementation to Q1/Q2-18.

**Comment by kyessenov** [comment]
I actually prefer github issues for discussion, since gdocs comment/change tracking is difficult.
My recommendation - can you please keep the issue more focused, instead of calling "changes to pilot". It's unclear what changes you have in mind and why we need them.

**Comment by ldemailly** [comment]
we've been using gdoc for design doc discussions and plan to continue to do so as it's better for that use case than github

**Comment by gnirodi** [comment]
kyessenov: objections noted. I'll cross reference all issues in the design doc. That way both are kept up-to-date

**Comment by ZackButcher** [comment]
I agree with Kuat: there's no reason to require that Pilot use the MSA as an exclusive backend. @gnirodi like we discussed in person, the whole idea behind MSA should be "Pilot scraping Pilots", i.e. federating Pilots. In that world, it's obvious that MSA cannot be the exclusive backend that Pilot talks to, because if MSA is "just another pilot" then how do we ever get new data _into_ the system?

IMO, approaching this problem with the idea that Pilot only talks to MSA, and that MSA is something special and not just another service registry, is a fundamentally flawed way of thinking about our system. If MSA cannot be implemented as just another registry, our design needs to be improved.
