### ISSUE TITLE
Include a link pointing to documentation in the output of `istioctl analyze`

### ISSUE THREAD

**Issue by sushicw** [istio/istio#18451]
When `istioctl analyze` finds validation issues, in addition to listing them it should also print a link to the documentation.

Mockup:
```
Error [IST0101] (VirtualService ratings-bogus-starhost.default) Referenced host not found: "*.ratings"
Error [IST0101] (VirtualService ratings-bogus-starhost.default) Referenced host+subset in destinationrule not found: "*.ratings+v1"
Warn [IST0107] (Deployment details-v1.default) Misplaced annotation: sidecar.istio.io/statsInclusionPrefixes can only be applied to Pod
Error: Analyzer found issues. For more information about these message codes, see https://istio.io/docs/reference/config/analysis/
```

Note that the docs don't actually exist yet on istio.io, but do appear in preliminary.istio.io. 

We should add this message once we have the reference on istio.io and it's fleshed out enough to be basically useful.

**Comment by sushicw** [comment]
Once we have support for YAML/JSON output, we can include links to the specific doc for each message code directly. We don't want to do so for the "regular" output, though, because it would be very cluttered.

**Comment by esnible** [comment]
Are there tasks to write the https://preliminary.istio.io/docs/reference/config/analysis/ detail links?  I see some messages are linked to a detail page.

**Comment by selmanj** [comment]
@adammil2000 suggested printing doc links for regular output as well (along with using a specially crafted url so we can get insight on what sort of error codes users are usually hitting).

**Comment by adammil2000** [comment]
As of today, the doc pages for each analyzer message are live on the Istio docs site here:
https://istio.io/docs/reference/config/analysis/

You can now link directly to the doc page dedicated to each message from inside Istio code. Each message follows this url format:
https://istio.io/docs/reference/config/analysis/<message ID>
For example:
https://istio.io/docs/reference/config/analysis/ist0001/

Please note some messages were hidden from the autogenerated doc index like NotImplemented, and others. As of this comment, we did not add a dedicated page for the IST0002: Deprecated message because the plan was to hide it, but it's still present. If we need to keep it, let me know and I'll add a page for it.

**Comment by sushicw** [comment]
@adammil2000 Let's go ahead and add a simple boilerplate page for IST0002 like we have for IST0001. Do you have bandwidth to handle that?

**Comment by sushicw** [comment]
https://github.com/istio/istio.io/pull/5885
