### ISSUE TITLE
support zone aware routing of envoy

### ISSUE THREAD

**Issue by ckcd** [istio/istio#18500]
For now istio support [Locality weighted load balancing](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/locality_weight#arch-overview-load-balancing-locality-weighted-lb) of envoy with the `localityLbSetting` config. it's a great function but it may causes imbalance across all upstream hosts if replicas of a service is NOT equal in each zones.

And, for k8s, it's hard to make pod replicas spread in different zones equally, even with `Affinity and anti-affinity`, see https://github.com/kubernetes/kubernetes/issues/68981

And, envoy support [zone aware routing](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/zone_aware#arch-overview-load-balancing-zone-aware-routing):

> The purpose of zone aware routing is to send as much traffic to the local zone in the upstream cluster as possible while roughly maintaining the same number of requests per second across all upstream hosts (depending on load balancing policy).

So, can we support [zone aware routing](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/zone_aware#arch-overview-load-balancing-zone-aware-routing) of envoy to gives another choices for users.

Thanks !

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by howardjohn** [comment]
Envoy cluster name must be static, In Istio this isn’t true - cluster names change based on Istio configuration so they aren’t static.

**Comment by howardjohn** [comment]
Based on the above I don't think this is feasible for Istio

**Comment by ramaraochavali** [comment]
I think we can support zone aware routing using priorities rather than using Envoy's default zone aware routing routing which has many [limitations](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/zone_aware#arch-overview-load-balancing-zone-aware-routing-preconditions) and also it needs a local cluster to be defined in static bootstrap config as @howardjohn  noted above.

But as documented in [here](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/overview#global-load-balancing) we can add priorities to endpoints and use [priority load balancing](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/priority#priority-levels) that effectively provides zone aware routing. 

For example we can enhance the [LocalityLoadBalancerSetting](https://github.com/istio/api/blob/7fd43ea7fc2b2392c9e02b41a71776c6938416b2/networking/v1alpha3/destination_rule.proto#L993) and allow users to specify priority , we should be able to support zone aware load balancing
Example :
locality A --> locality A Priority P0 
locality A --> locality B Priority P1 

Depending on healthy hosts in each priority, Envoy will route %age of traffic as explained [here](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/priority#priority-levels)

@howardjohn @hzxuzhonghu @rshriram WDYT? Is this some thing that would be useful to support priority based load balancing?

**Comment by ramaraochavali** [comment]
Looks like we already assign priorities based on region/zone/subZone https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/v1alpha3/loadbalancer/loadbalancer.go#L151 so does it not equivalent to support zone aware routing?

**Comment by yan-dblinf** [comment]
Though the locality prioritized load balancing provides a counterpart of zone aware routing, load balancer [metrics](https://www.envoyproxy.io/docs/envoy/v1.13.1/configuration/upstream/cluster_manager/cluster_stats#id9) will be missing, which is valuable for monitoring.

**Comment by mcblair** [comment]
> Looks like we already assign priorities based on region/zone/subZone https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/v1alpha3/loadbalancer/loadbalancer.go#L151 so does it not equivalent to support zone aware routing?
> 
> But we do that only if Traffic Policy and outlier detection is available in DR https://github.com/istio/istio/blob/master/pilot/pkg/proxy/envoy/v2/eds.go#L494 do not use mesh config?

Has this been confirmed? I'm looking to determine with certainty whether Istio already supports Zone Aware routing(with a properly configured DR). The documentation is not clear.

**Comment by hzxuzhonghu** [comment]
Yes, feel free to use this feature

**Comment by howardjohn** [comment]
`priority` is used. "Zone aware routing" is another Envoy feature that is *not* used and generally doesn't fit Istio's needs.

**Comment by sschepens** [comment]
@howardjohn i think zone aware routing covers some cases that you cant handle with priorities, if your services are not perfectly balanced between zones, then your traffic will not be balanced and could cause greater load on some zones.

I think this could be implemented in Istio. I know Zone Aware requires Cluster Name to be static and istio cluster names are dynamic, but we could make Istio generate a "fake" cluster (only visibile to the sidecar communicating with Istiod) with the name Envoy is expecting and only containing EDS for that cluster, but not configuring routing and stuff. This is something we've done in our own control plane. This way you meet the requirements for Zone Aware without much trouble.

**Comment by sschepens** [comment]
@howardjohn how do you think about reopening this issue or creating a new one with my proposal?

**Comment by howardjohn** [comment]
Sounds great, would love to hear more info about the idea.

**Comment by sschepens** [comment]
@howardjohn opened https://github.com/istio/istio/issues/35102 with a more detailed proposal

**Comment by laxmiprasanna-gunna** [comment]
I was trying to enable zone based routing config via EnvoyFilter on Istio mesh with following configuration
```
   patch:
      operation: MERGE
      value: # cluster specification
        common_lb_config:
          zone_aware_lb_config:
            routing_enabled: 
              value: 100.0
            min_cluster_size: 2
```

The config is getting applied, can see the envoy config getting reflected, but I don't see any affect on the load-balancing/traffic distribution. So this would not be possible until #35102 is implemented?
