### ISSUE TITLE
Enable sub-resources patch on incremental SyntheticServiceEntry MCP update

### ISSUE THREAD

**Issue by seflerZ** [istio/istio#18731]
**Describe the feature request**
Refer to this [merge](https://github.com/istio/istio/pull/12276), Pilot has supported incremental updates for SyntheticServiceEntry. However this update only works incrementally for SyntheticServiceEntry resource itself only, not for sub-resources like endpoints within it. We would like to update(add/delete) the endpoints incrementally, not replace the whole enpoints with those passed in.

**Describe alternatives you've considered**
None at present

**Additional context**
With large scale clusters, the number of endpoints are 1000+ and updated frequently. By enabling incremental on endpoints, we can significantly increase the performance of Pilot and be more responsive.

**Comment by howardjohn** [comment]
Can you have multiple SSE for the same service and shard the endpoints?

**Comment by seflerZ** [comment]
@howardjohn  Endpoints shard just split the change but do not do it incrementally. I must figure out how many shards I need according to the scale of the cluster. The problem is every cluster is different, some get 1000 endpoints, some get 5000 and the shard's configuration is static. Besides, the endpoint shards is originally designed to have different sidecars serving the same cluster getting different endpoints. I don't think it quite fits the schema.

I also feel it weird and confusing if incremental update for SyntheticServiceEntry works only for ServiceEntry discarding the endpoints within. If Pilot and Envoy both supported the endpoints patching, the performance will boost incredibly for large clusters.

**Comment by howardjohn** [comment]
@seflerZ I completely agree that we want full incremental endpoint updates. I do think the focus should be on Envoy though, because you generally have 1000x as many Envoys as Pilot so the performance improvements there are 1000x more effective, not to mention the EDS response is much larger than MCP so it's more expensive as well

**Comment by nmittler** [comment]
MCP is eventually going to be replaced with XDS, so I"m not sure we want to spend too many cycles refactoring the incremental protocol there. I'm not sure if the incremental XDS work addresses this.

In the meantime, would it help to move out endpoints into a separate structure that can be versioned independently from SE?

**Comment by Nino-K** [comment]
One way to optimize what we currently have might be to introduce some sort of annotation keys for endpoints added, deleted and updated. This way we can apply those endpoints incrementally in Pilot, although not sure how the performance of the pilot or the protocol would look like by having to include a large list of endpoint entries in the annotations. This way we could still update "a service" individually via EDS and if endpoints are sharded more logically(e.g by hostName, vips etc) the performance might not look that terrible. Furthermore, it may be beneficial to run one Pilot per cluster if those services are running in different clusters?? Having said that as others suggested too the ultimate bottleneck would still exist at envoy since envoy still does not support EDS patch for endpoint subsets yet.

**Comment by howardjohn** [comment]
I am not sure what the aversion to sharding the endpoints is? Am I missing something where this will not work? This is exactly what Kubernetes has done to solve the same problem with EndpointSlice. We should just add native support to pilot for EndpointSlice. I have a WIP doing this in https://github.com/istio/istio/pull/18394, but would need to send it over MCP as well (this is just reading from k8s).

**Comment by seflerZ** [comment]
@nmittler Are you sure the MCP is a temporary solution talking to xDS? If it is, what about the compability and works we have done? Although as I know MCP is originally derived from xDS, still there're differences. We must be careful.

Anyway, no matter what the protocol used for communitcation, I think incremental on every resource is still needed, especially for thoese changing frequently like endpoints.

@Nino-K I agree with you on implementing incremental endpoints updated based by current work. As for details and performance impacts, I'll try to investigate and figure out. Deploying a Pilot per cluster is the solution we've tried and found it nerely impossible due to high cost and difficulties on maintaince.

@howardjohn Thank you for your support. As the K8s [doc](https://kubernetes.io/docs/concepts/services-networking/endpoint-slices/) shows, the Endpoint Slices feature is need in alpha state in K8s 1.16. As far as I know, the Endpoint Slices is a scalable alternative to Endpoints as the cluster goes big. EndPoint Slices allow developers to manage endpoints indepently despite of services. That is to say, Endpoints Slices can be assgined to multiple resoureces. Because Endpoint Slices is limited to 100 endpoints as most, deploying them to services leds endpoins changes to units with 100 endpoints at most. It did solved the incremental endpoints update problem some how because with 1000 endpoints only 100 or less will be sent when state changes, but this is not a perfect solution as still more data was sent with only one changed.

**Comment by howardjohn** [comment]
In the kubernetes controller, Endpointslice will be split at 100 endpoints, but for your case you are the controller, so you can decide yourself how to create the endpoint slices, and could include one endpoint per Endpointslice if desired.

While it's alpha in 1.16 kubernetes you can still send it over mcp even on older k8s where it doesn't exist in mcp (once we add support for mcp) since they are not persisted to the k8s cluster.

**Comment by seflerZ** [comment]
@howardjohn Yes, the Endpoint Slice IS a solution and worth looking into. The only thing we need to worry is whether it generates too many configs if every slice is set to 1 endpoint.

**Comment by hzxuzhonghu** [comment]
> The only thing we need to worry is whether it generates too many configs if every slice is set to 1 endpoint.

Endpointslice is not expected to be used like this way. IIRC. `100` is by default. I agree with you the right way is to do endpoints merging.

**Comment by seflerZ** [comment]
Close this issue since SSE resources and controller has been removed refer to this [issue](https://github.com/istio/istio/pull/20763#event-3032600507)

**Comment by seflerZ** [comment]
Close this issue since SSE resources and controller has been removed refer to this [issue](https://github.com/istio/istio/pull/20763#event-3032600507)
