### ISSUE TITLE
VirtualService destination routes / mirrors should respect global.outboundTrafficPolicy.mode

### ISSUE THREAD

**Issue by sushicw** [istio/istio#18764]
VirtualService analyzers should respect global.outboundTrafficPolicy.mode.  Route or mirror destinations that point to external services (i.e. not in `svc.cluster.local`) should *not* generate a validation error if they are missing a ServiceEntry, unless `global.outboundTrafficPolicy.mode` is `REGISTRY_ONLY`. 

See https://istio.io/docs/tasks/traffic-management/egress/egress-control/

We might want to still generate a warning / recommendation message encouraging users to create a ServiceEntry for all external services, if we want to make it easier to follow that as a best practice.

One aspect that makes this tricky: getting `outboundTrafficPolicy.mode` will mean checking the control plane configmap, which means the analyzer will need some way of knowing where to look for that. We can't always assume it will be configmap `istio` in namespace `istio-system`. Knowing where to find the control plane is likely to affect other analysis scenarios as well. 

@nrjpoddar @jwendell Please let me know if the above needs any editing or clarification.

**Comment by nrjpoddar** [comment]
Thanks @sushicw for filing this issue. I agree with description, in general we would need to parse Mesh configuration in analyzers for many advanced validations so we should start thinking about a generic way to consume them.

**Comment by howardjohn** [comment]
@nrjpoddar am I missing something? I am pretty sure you cannot create a virtual service without a ServiceEntry

**Comment by howardjohn** [comment]
In the doc linked they created the service entry at the start of the doc

**Comment by nrjpoddar** [comment]
> @nrjpoddar am I missing something? I am pretty sure you cannot create a virtual service without a ServiceEntry

IIUC you can create a VirtualHostRouting paradigm where the host of the VirtualService is a platform service which eventually gets routed to an external service.  What I have not verified is if you have “allow_any” set for outbound, whether it is allowed to have the route destination host of a VirtualService not be a platform service (K8s service or serviceentries ).

**Comment by howardjohn** [comment]
Can you provide a virtual service that works without a ServiceEntry? Just the basic one in the doc definitely does not work. The route will be created but it points to a cluster that does not exist

**Comment by nrjpoddar** [comment]
I will try it tomorrow and update this issue. I think what you’re saying might be correct, the route destination host always refers to a named cluster

**Comment by nrjpoddar** [comment]
@sushicw @howardjohn I verified the behavior and as of release-1.4, the observed behavior is this:

* If `global.outboundTrafficPolicy.mode` is set to `ALLOW_ANY` and there's no VirtualService configured for routing to an external host, the VirtualOutbound listener is invoked which will proxy the traffic as TCP.
* If `global.outboundTrafficPolicy.mode` is set to `ALLOW_ANY` and there's a VirtualService configured for routing to an external host, the listener specific to the port/protocol will be invoked, which eventually points to a named cluster like `outbound|80||httpbin.org`. The expectation is that users will configure these via ServiceEntries otherwise any requests receive `503`.

Based on my findings and like @howardjohn was suggesting above, the current analyzer is good as it is and we should close out this issue.

There's a separate conversation we should have if this is the right behavior as it's kind of a bad user experience in my view to ask them to configure ServiceEntry just for the sake of create internal Envoy configuration. We can very easily fall back to `ORIGINAL_DST` cluster if `global.outboundTrafficPolicy.mode` is set to `ALLOW_ANY` and there are no explicit ServiceEntries.

**Comment by sushicw** [comment]
Thanks for looking into this Neeraj. I'll close this out, and we can refer to it if/when this comes up later.
