### ISSUE TITLE
Support automatic sidecar injection on replicaset, daemonset, or statefulset instead of pod

### ISSUE THREAD

**Issue by igsong** [istio/istio#18795]
Currently, automatic sidecar injection is achieved by mutating a pod when it is created.

This way looks intuitive and straightforward.
However, if a replicaset try to create a pod when a webhook pod (istio-sidecar-injector pod) is gone for a while, the replicaset could be failed to launch a new pod. In some cases, it is permanently failed, so all the pod in an injection enabled namespace are never launched. We can make this situation by terminating all the nodes and then turning on again.
 
Therefore, I would like to suggest to make an another alternative injector which is injecting a proxy container into replicaset, statefulset, or daemonset. 

Since they are usually created(or modified) by a user on deployment process, the user can know the failure when the injection webhook is failed. Moreover, even if all the nodes are crashed and re-started, all the system will be successfully started.

One of the alternatives to treat this problem could be to provide a way to install the sidecar injector on the separate infrastructure. 

**Additional context**

**Comment by ayj** [comment]
This would also make it easier to roll-out proxy updates in a controlled fashion. @Stono had requested this a while back but I had pushed back since it complicated how we supported different workload types. In hind sight, that was probably the wrong decision.

**Comment by Stono** [comment]
https://github.com/istio/istio/issues/3831 *blows off the dust*

**Comment by igsong** [comment]
In my case, I've set up the istio-sidecar-injection service on multiple separate nano EC2 instances instead of running it on Kuberenetes with other services. It works, but causes complexity.

**Comment by howardjohn** [comment]
> In my case, I've set up the istio-sidecar-injection service on multiple separate nano EC2 instances instead of running it on Kuberenetes with other services. It works, but causes complexity.

I am still waiting for a sidecar-injector-as-a-service offering to come out :slightly_smiling_face: 

If we go with this approach how do you re-inject your deployment? Just modify any field (or `kubectl rollout restart deployment`?)

**Comment by Stono** [comment]
When we roll out new Istio versions now, we patch all deployments with label `RESTARTED_ON: timestamp`.  

So that should still work, what this would give us work be more deterministic versions of sidecars per deployment (eg, a deployment autoscaling won't end up with different versions of a sidecar). 

However, the more I think about it, honestly, the less I think I'd actually use it.  We manage our deployment objects with Helm, having something else modify that spec outside of the helm CI/CD process we have is likely going to mess up at some point (we strictly don't modify state outside of infra as code).

**Comment by ptzianos** [comment]
@igsong @stono found this by accident. I think it's a nice idea but I have one question/reservation: what happens when a deployment/statefulset/... has been created and is managed by an operator? Isn't there a good chance that modifying these high level objects will cause most operators to perceive them as being in the wrong state which will trigger a reconciliation and a removal of the sidecar container?
