### ISSUE TITLE
Cannot delete istio-operator namespace

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#18815]
Repro:

Install operator + ICP
`kubectl delete ns istio-operator`

The namespace gets stuck forever because the ICP won't get removed.

`kubectl delete icp --all` also hangs forever, need to manually remove the `finalizer`

**Comment by richardwxn** [comment]
this happened to me occasionally but not always. I think @morvencao did some work before around this?

**Comment by morvencao** [comment]
Maybe there is 'deadlock' there in controller, but normally the finalizer will be cleaned after all  the resources managed by icp are removed.

**Comment by howardjohn** [comment]
How can that happen? the first thing that happens when I remove the namespace is the operator pod dies, at which point there is no hope of it recovering

**Comment by ostromart** [comment]
There's a simple explanation for this. Because the CR is also in istio-operator, deleting the ns deletes both the controller and CR in non-deterministic order. At times, the controller will get the chance to add the finalizer to the CR before it's deleted, but will not have time to remove the finalizer before it disappears. In that case we are stuck with a CR with a finalizer, which cannot be deleted (by k8s design). 
You can work around it by removing the finalizer field in the CR - otherwise the solution is to move the CR into istio-system, which I think we've either done or are about to do.

**Comment by spoilerdo** [comment]
I get the same error
