### ISSUE TITLE
New Envoy readiness probe delays startup

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#18875]
Running master

(I had to truncate logs since they are from a user with personal information) Logs look like:
```
...init clusters...
..init listeners...
[Envoy (Epoch 0)] [2019-11-11 23:39:07.817][23][info][upstream] [external/envoy/source/server/lds_api.cc:63] lds: add/update listener 'virtual'
2019-11-11T23:39:08.499334Z     info    Envoy proxy is NOT ready: failed to get server info: stats version is not preset:
[Envoy (Epoch 0)] [2019-11-11 23:39:09.660][23][info][config] [external/envoy/source/server/listener_manager_impl.cc:578] all dependencies initialized. starting workers
2019-11-11T23:39:10.496402Z     info    Envoy proxy is NOT ready: failed to get server info: stats version is not preset:
2019-11-11T23:39:12.496729Z     info    Envoy proxy is ready
```

After 23:39:07 we should be ready, as listeners have been initialized, but that stats version is apparently not there until 5s later.

If Envoy should NOT be marked ready during this time, then what is happening during that 5s?
If Envoy should be marked ready during this time, then why is version not present? Should we look at another stat?

**Comment by ramaraochavali** [comment]
We are basically ready right after this line [Envoy (Epoch 0)] [2019-11-11 **23:39:09.660**][23][info][config] [external/envoy/source/server/listener_manager_impl.cc:578] all dependencies initialized. starting workers . 

Not at  23:39:07, because at that point it is still creating listeners. 

I see that Envoy is setting that stat in the next flush cycle. Fixed it in Envoy https://github.com/envoyproxy/envoy/pull/8987 to set it as soon as Envoy starts workers.

**Comment by howardjohn** [comment]
Thanks!

**Comment by ramaraochavali** [comment]
@howardjohn The Envoy PR is merged, so it should be fixed when we upgrade Envoy.

**Comment by howardjohn** [comment]
Closing as this has been fixed in envoy
