### ISSUE TITLE
Add a istioctl manifest uninstall option

### ISSUE THREAD

**Issue by jwendell** [istio/istio#18900]
users should be able to run `istioctl manifest uninstall` in favor of using `manifest generate > file.yaml` and then `kubectl delete -f file.yaml`

there could be a flag to delete everything (crd's, other global resources) or just the control plane?

**Comment by ostromart** [comment]
I think this will be a nice addition and quite easy to implement, bumping up to P1.

**Comment by esnible** [comment]
Should https://github.com/istio/istio/issues/19292 (removing non-current CRDs) be part of this?

**Comment by esnible** [comment]
What should we uninstall?  The namespace where Pilot was deployed, the webhook, and some resources deployed to other namespaces?

The intention of this issue is to reverse Apply, not Create.  We don't always know which things in the manifest were created and which existing things were used by the manifest.

On PR https://github.com/istio/istio/pull/20766 @howardjohn pointed out that if we uninstall all the namespaces "apply", we are in danger of deleting a namespace such as "telemetry" because the install put some configs there.

For my initial prototype PR I started with the strategy @jwendell asked for in the issue "users should be able to run istioctl manifest uninstall in favor of using manifest generate > file.yaml and then kubectl delete -f file.yaml".  My first version just generated and deleted.  A correct implementation can't do that for the reasons discussed on the PR.

**Comment by sdake** [comment]
> users should be able to run `istioctl manifest uninstall` in favor of using `manifest generate > file.yaml` and then `kubectl delete -f file.yaml`
> 
> there could be a flag to delete everything (crd's, other global resources) or just the control plane?

CRDs, as per environments workgroup prior policies, should never be deleted - they should instead always be leaked to prevent data loss of configuration information.

Deleting the control plane sounds good in theory - in practice, it is very difficult to properly clean a control plane. One major source of trouble are webhooks. When a namespace is deleted that a webhook is connected with, the webhook fails on future installs to that namespace. I believe this is a fundamental design flaw in K8s, but what do I know, I'm just an expert in strategic analysis.

**Comment by sdake** [comment]
The condition of deleting CRs needs careful consideration. Deleting CRs that Istio installs, and are exact duplicates of the intalled CRs is ok - any other CR deletion is not ok. @esnible I think this is the logic you seek.

The challenge with deleting a namespace as @howardjohn implied, is some of these (shouldn't be deleted CRs because they were installed by the end user) end up in the namespace of the application. In this case a namespace deletion isn't the right solution.

The @istio/wg-environments-maintainers has a **strict policy** of no customer data loss.

**Comment by howardjohn** [comment]
The problem gets worse when we have multiple control planes as well. We will need to be careful about what is a shared resource (not many, likely just webhooks+CRD) and what is not. If we want, we could go with a `--really-really-really-delete-everything` flag and just kill everything, but the default should be err on the side of caution I think

**Comment by howardjohn** [comment]
Besides, who wants to delete Istio :wink:

**Comment by sdake** [comment]
One implementation option you have availble to you is to delete any resource created by the operator. These have ownerrefs (K8s will clean these up automatically) - or annotations (not clear on why we use annotations rather than ownerrefs to the control plane CR...).

One possible solution to this is to ensure ownerrefs are used in all objects installed by the operator (rather than a mix of annotations and ownerrefs as used today). If this were the case, simply deleting the control plane CR would delete the installation correctly.

Getting the ownerrefs set properly is not an easy implementation.

**Comment by sdake** [comment]
> The problem gets worse when we have multiple control planes as well. We will need to be careful about what is a shared resource (not many, likely just webhooks+CRD) and what is not. If we want, we could go with a `--really-really-really-delete-everything` flag and just kill everything, but the default should be err on the side of caution I think

As long as `--really-really-really-delete-everything` still results in leakage of the user's CRs, and Istio's CRDs, this meets the no data loss policy and wfm 👍

**Comment by sdake** [comment]
> The problem gets worse when we have multiple control planes as well. We will need to be careful about what is a shared resource (not many, likely just webhooks+CRD) and what is not.

Great point @howardjohn - If you can list the shared resources you are aware of (CRDs and webhooks are the obvious ones, wonder if there are any others lurking in the implementation) - we must not delete these on a cleanup.

**Comment by howardjohn** [comment]
Definitely shared is the namespace, CRDs, possibly some of the default CRs we install (mesh policy, default destination rules, etc), the validation webhook. We will also likely share the addon stuff (part of why the "bring your own addon" is appealing), which is probably the most problematic here since we can't just do some heuristic like "delete all deployments"

**Comment by sdake** [comment]
This is a very difficult problem to solve correctly, however, adds significant value to Istio. 

The use case of Istio deletion is simple:

When evaluating Istio, you might install and uninstall it 30-60 times (this has been my experience in prior projects) - trying different things out until you find the setup that works for you. If deletion = I gotta delete my cluster (as is the case today.... **GROAN**) - the user experience during product evaluation - where the experience should be gold plated - is pretty terrible.

**Comment by sdake** [comment]
@ayj in the linked PR, you mentioned something about webhooks and their ownerrefs that I didn't quite understand. Would you mind explaining what would be the best way to proceed given the exchange in this thread and assuming helm used in prior versions is long gone?

Cheers
-steve

**Comment by esnible** [comment]
For a while I have been asking that the IstioOperator/IstioControlPlane CR used to install Istio be preserved on the cluster to document the user's intention.  https://github.com/istio/istio/issues/20000

If the command line creates the CR in cluster we could use OwnerRef against that resource for everything that is unique to that install.

**Comment by ayj** [comment]
Here are some options for how we can manage the lifecycle of webhook configuration.

### Option 1
* validatingwebhookconfiguration ownerRef is the `istio-system` namespace. Deleting the `istio-system` namespace deletes the validation. `helm template | kubectl delete` will leak the config.

### Option 2 
* validatingwebhookconfiguration ownerRef is the `istiod`/`istio-galley` clusterrole
* Deleting the clusterrole deletes the webhook.  `helm template | kubectl delete` works (good) but deleting the `istio-system` namespace now leaks the config (bad). From personal experience, option (1) is more obvious than option (2). I frequently delete the namespace to "reset" during development. I rarely cleanup the clusterroles and instead rely on updating to the latest during testing.

### Option 3
1) make validatingwebhookconfiguration at top-level resource that is applied directly just like the mutatingwebhookconfiguration. istiod only needs to patch the caBundle and not reconcile the entire config.
2) update istioctl / operator / templates to always install the Istio custom resources before applying the validatingwebhookconfiguration. Document that the user shouldn't apply their own config until the webhook is patched. istioctl could also enforce this.

Option 3 is my first choice. It is consistent with how we manage the mutatingwebhookconfiguration. Also, we want to eventually get the webhook control logic out of istiod anyway. This would require some notion of a 'post-install` phase in istioctl. istioctl already has a `post-install` subcommand to create/patch the webhook config. We could make that the default for 1.5. cc @lei-tang 

My second choice would be option 1. This seems more obvious to me than option 2.

**Comment by esnible** [comment]
This item was briefly discussed at the UX meeting.

@sdake pointed out that currently there is no way to uninstall for technical reasons.  He will work on getting agreement for Uninstall RFC.

Someone, I think Jason, asked "Would uninstall remove sidecars and restart?"

I pointed out that there is a user expectation that the data plane should be removed FIRST before we remove control plane for a version.  No user wants to uninstall istio-system with a bunch of sidecars dependent on it for config.  Whatever we decide on, it must include removing pods from a mesh before removing the control plane.

(Or, once we have multiple control planes working smoothly, pointing those pods at the new global master Istio control plane).

**Comment by ayj** [comment]
We should probably have a "uninstall" page under "setup" on istio.io. This is especially important if we don't have an uninstall command and the recommended sequence is non-trivial.

**Comment by esnible** [comment]
Note: on the unrelated document https://docs.google.com/document/d/1d1z5PC8wvh9QiR3NesAaPm6w2HnE4-KIfjB7GB-_Wf8/edit Brian Wolf points out that we "apply" a manifest.  We should use a word that is the opposite of "apply".  "delete?"

**Comment by esnible** [comment]
Yesterday I learned that Kiali expected `istio.io/key-and-cert` secrets.  We no longer make them.  `manifest delete` should probably get rid of them.

It seems `manifest apply` can't get rid of them because 1.4 sidecars might be using them until those pods restart.  Yet it is confusing for the user to see secrets from an older control plane that are no longer being rotated still living in the cluster.  I propose `remove` and `apply` purge any `istio.io/key-and-cert` secrets containing **expired** certificates.

**Comment by howardjohn** [comment]
Deleting secrets is pretty dangerous, I would recommend we make it an explicit action and not implicit. Would it make sense to offer an extra step to do `kubectl delete -listio.io/key-and-cert --all` when a user determines its appropriate, or a `--delete-secrets` to istioctl to explicitly do this? They do not hurt anyone if they are there, but deleting them may cause quite a few issues

**Comment by esnible** [comment]
@ostromart Added you because we need to work on this together.

I have no problem doing the CLI pieces but I have concern about the removal itself.

Related is https://github.com/istio/istio/issues/23889 , promoting a canary to master.  When we do this we should uninstall the original master at the end of a successful promotion.  That will probably be a manual step.  I am thinking the flow to be something like:

```
istioctl install --revision canary
kubectl label default istio.io/rev=canary
// wait a few hours, look at metrics, etc
istioctl experimental promote-canary-to-master --revision=canary
kubectl label default istio-injection=enabled
// wait an hour or so
istioctl manifest uninstall --revision canary
```

**Comment by esnible** [comment]
@ostromart Is there a design for what will be removed?

- Do we think this can be contained for removing a single control plane?
- If the master control plane is uninstalled, and there are canaries, will the canary become the master.  (Master means "handles `istio-injection=enabled` namespaces)
- Will removing the CRDs be a different operation or will it happen automatically when the last/master control plane is removed?

**Comment by esnible** [comment]
https://github.com/istio/istio/issues/23479 may be a dependency for this work.

**Comment by esnible** [comment]
@richardwxn @ostromart Is this handled by https://github.com/istio/istio/pull/25076 ?  May I close it?
