### ISSUE TITLE
`istioctl version` on a cluster without istio shows strange warning

### ISSUE THREAD

**Issue by rvennam** [istio/istio#18986]
**Bug description**
```
~ 🏎  $ istioctl version
2019-11-15T14:48:41.027389Z	warn	will use `--remote=false` to retrieve version info due to `no Istio pods in namespace "istio-system"`
1.4.0
```

**Expected behavior**

**Steps to reproduce the bug**
Run `istioctl version` on a cluster which does not have istio installed

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.4.0

**How was Istio installed?**
Not Installed

**Environment where bug was observed (cloud vendor, OS, etc)**
IKS

@esnible

**Comment by rvennam** [comment]
Similar confusing message appears during installation, before the control plane has started.

**Comment by tonydalhoff** [comment]
@rvennam I'm trying to familiarize myself with how to solve this issue and have a quick question. Is the right way to check if Istio is installed on a cluster by checking whether the cluster has a namespace defined with the Istio namespace? I assume tha the `istioctl version` command would have access to the namespace flag since it _is_ a Cobra PersistentFlag, correct?

Pulled this guess straight from https://github.com/istio/istio/blob/master/istioctl/pkg/install/pre-check.go#L91s

**Comment by shamsher31** [comment]
The version is returned from the function [`GetIstioVersions`](https://github.com/istio/istio/blob/cee3fed405c6ebc2d19316de011287efd8b86cdd/istioctl/pkg/kubernetes/client.go#L246) and if the Istio is not installed on cluster it prints warning message form [this line](https://github.com/istio/istio/blob/cee3fed405c6ebc2d19316de011287efd8b86cdd/istioctl/pkg/kubernetes/client.go#L255).

I'm not sure but the `warning` message is a little misleading and it should be just an `info` instead of `warning`.

If the Istio is installed on the cluster.
```go
$ istioctl version
client version: 1.4.3
control plane version: 1.4.3
data plane version: 1.4.3 (8 proxies)
```
If the Istio is not installed on the cluster, the message should be simple enough to inform the user that the version info is fetched from downloaded Istio release which is available at `istio-1.4.3/bin`. 
```go
$ istioctl version
1.4.3
Note: As the Istio is not installed on the cluster, the version is fetched from `istio-1.4.3/bin`

OR

$ istioctl version
1.4.3
Note: Version info is available from  `istio-1.4.3/bin` because Istio is not installed on the cluster
```
cc: @brian-avery @howardjohn Let me know if this sounds ok and I will work on it.

**Comment by esnible** [comment]
@shamsher31 The log messages should be removed.  Earlier versions of the `version` subcommand were shared by server-side code such as Pilot which needed to log.  The Istioctl CLI should not log under any ordinary circumstances.

I recommend either eliminating the `log.Warnf()` statements or lowering the level to debug.

It is nearly impossible to refactor the `version` command because it exists in two Github repos: istio/istio and istio/pkg.

I have an idea.  I will sketch it out and explain it here.

**Comment by shamsher31** [comment]
> The log messages should be removed

That was my first thought, I think as a user you shouldn't be bothered about whether you are getting `version` from cluster's `istio-system` or from anywhere else.

> I recommend either eliminating the log.Warnf() statements or lowering the level to debug.

That's a good idea, I think keeping it to `debug`  will be sufficient.

**Comment by esnible** [comment]
Lowering the message to DEBUG level is good enough, but if you want to do better read on.

FYI, to test on my cluster with Istio installed, I use `istioctl version --istioNamespace=bogus`

The problem is the API between istio/istio and istio/pkg does not allow us to pass the Cobra output stream to `getRemoteInfo()`.  You COULD write informative messages to os.Stderr if Istio is not found.  That will help the user.

You may not need to go all the way, but it is considered bad form to write to os.Stderr in spf13/cobra programs because it is hard to automate tests for that output.  Cobra tests expect all output to be written to cmd.OutOrStderr().  This is hard because you don't have cmd.  There is a way to sneak it in.  First, write a wrapper for `getRemoteInfo()`, a function that returns a closure with the Cobra command:

```
func getRemoteInfoWrapper(pc **cobra.Command) func() (*istioVersion.MeshInfo, error) {
	return func() (*istioVersion.MeshInfo, error) {
		retval, err := getRemoteInfo()
		if retval == nil {
			fmt.Fprintf((*pc).OutOrStderr(), "Istio is not present in namespace %q\n", istioNamespace)
		}
		return retval, err
	}
}
```

Then, invoke the wrapper to get the closure when calling `CobraCommandWithOptions()`:

```
	versionCmd := istioVersion.CobraCommandWithOptions(istioVersion.CobraOptions{
		GetRemoteVersion: getRemoteInfoWrapper(&versionHolder),
		GetProxyVersions: getProxyInfo,
	})
```

There are lots of variations on this, such as passing a Writer instead of a Cobra Command.  Do whatever you think will improve the user experience without adding much complexity to the code.
