### ISSUE TITLE
Have a command-line tool to dump Istio snapshots

### ISSUE THREAD

**Issue by zerobfd** [istio/istio#18994]
It seems like it would be useful to be able to generate a serialized dump of a snapshot (the one in galley code that istioctl analyze runs analysis on) to save for later, and also to be able to then run analysis on it. At the very least this would give an easy way to have a golden data set for regression tests for any kind of analysis, as well as enable some neat remote debugging help/remote analysis scenarios.

**Additional context**

**Comment by esnible** [comment]
When I have a problem I do `kubectl get gw,vs,dr,se,policy --all-namespaces -o yaml > istio-before.yaml` and `kubectl get service,deployment --all-namespaces -o yaml > k8s-before.yaml`.

This is my standard technique, because when I fix things I want to be able to diff and make sure I understand what I have done.

Perhaps we should add some hints like these to our ops / troubleshooting docs?
