### ISSUE TITLE
gogoprotobuf and golang/protobuf create some serious pain in the operator

### ISSUE THREAD

**Issue by sdake** [istio/istio#19018]
Please see the precedent for converting out of gogo to a straight golang/protobuf implementation set by the rest of the Istio project:

https://github.com/istio/istio/issues/18826#issuecomment-554664631

Doing so would simplify much of our code.

A work in progress PR: https://github.com/istio/operator/pull/382

with much more detail about 'why?".

**Comment by howardjohn** [comment]
For what it's worth the linked issue is because go-control-plane switched to golang protos - istio/API is still on gogo. Basically anything sent over XDS is golang and everything sent over MCP is gogo

as far as I know there blocked for moving istio apis is Mixer, although it might be possible to move the other apis to golang as well, not sure.

I am all for switching the operator if it makes sense

**Comment by ostromart** [comment]
We've discussed doing something around this but it's not so simple. We need gogo to unmarshal enums and jsonpb due to our structs being protoc generated. It would be nice to investigate if some improvements can be made but we've already sunk a lot of time in trying to figure this out so it's not going to be a low hanging fruit for whoever takes it. I'm not opposed but we should be mindful of the cost/benefit.

**Comment by howardjohn** [comment]
@ostromart aren't we on golang proto now?
