### ISSUE TITLE
KinD does not export sidecar log when running with new test framework

### ISSUE THREAD

**Issue by bianpengyuan** [istio/istio#19062]
**Bug description**
When running tests written with new test framework, it seems like kind only export logs for control planes, e.g.
https://gcsweb.k8s.io/gcs/istio-prow/pr-logs/pull/istio_istio/19057/integ-telemetry-k8s-tests_istio/4030/artifacts/kind/istio-testing-control-plane/containers/
https://gcsweb.k8s.io/gcs/istio-prow/pr-logs/pull/istio_istio/19057/integ-pilot-k8s-tests_istio/4034/artifacts/kind/istio-testing-control-plane/containers/

For test written with legacy framework, KinD exports logs for both control planes and applications:
https://gcsweb.k8s.io/gcs/istio-prow/pr-logs/pull/istio_istio/19057/e2e-mixer-no_auth_istio/4015/artifacts/kind/istio-testing-control-plane/containers/

**Expected behavior**
KinD exports application and sidecar logs when running test written with new framework.

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
there are two lot exports - one is part of the test framework and one is at a higher level in kind, which runs immediately before the test exits. The new test framework must be cleaning up some of the pods, so it doesn't grab the logs when kind does a log dump.

The correct fix here is to make sure the test framework log dump is sufficient, otherwise we just get a snapshot once the test exists which isn't useful since there are many test functions that run.

**Comment by bianpengyuan** [comment]
@nmittler Is there a way to dump container logs in new test framework already?

**Comment by howardjohn** [comment]
@bianpengyuan there are some attempts at doing this already, and it works sometimes. See https://github.com/istio/istio/blob/f8149a108b613994be519b42a96e671f303ec80f/pkg/test/framework/components/istio/kube.go#L215. I suspect there are some cases where this is not correctly called

**Comment by howardjohn** [comment]
This has been fixed
