### ISSUE TITLE
About Zipkin Monitor

### ISSUE THREAD

**Issue by flyer1212** [istio/istio#19091]
When I use istio to deploy the application, how can my Zipkin monitor the call chain of MySQL At present, my zipkin  can only monitor my springboot web application.  I want it to monitor MySQL too, and show it in zipkin's  call chain graphy, thanks for your answer.

**Comment by flyer1212** [comment]
![image](https://user-images.githubusercontent.com/18101769/69219787-8f066f00-0bae-11ea-8aab-dac33f060b59.png)
when  use kiali ,  it can monitot mysql  as above,  is this function exist in zipkin? how to open this function?

**Comment by bianpengyuan** [comment]
Tracing is only for HTTP traffic, which utilizes HTTP headers to carry tracing context and does not apply to MySql protocol. See https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/observability/tracing for some background knowledge. What you probably should do is writing application code with zipkin client library in your `ts-food-service` to create spans for the MySQL queries with trace context extracted from HTTP header and send them directly from your application to zipkin server.

Close since this works as expected. Let me if you have further questions. Thanks!
