### ISSUE TITLE
Cannot set TRACE_SAMPLING percentage with istioctl

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#19177]
Running operator from latest master

```
$ /home/howardjohn/go/out/linux_amd64/release/istioctl manifest generate --set values.pilot.traceSampling=50 | rg SAMPL -A 1
        - name: PILOT_TRACE_SAMPLING
          value: "1"
$ /home/howardjohn/go/out/linux_amd64/release/istioctl manifest generate -f /tmp/icp.yaml| rg SAMPL -A 1
        - name: PILOT_TRACE_SAMPLING
          value: "1"
$ /home/howardjohn/go/out/linux_amd64/release/istioctl manifest generate --set profile=demo | rg SAMPL -A 1
        - name: PILOT_TRACE_SAMPLING
          value: "100"
```

my ICP:
```yaml
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  values:
    pilot:
      traceSampling: 100.0
```

So somehow it seems like the profile can properly apply it, but I cannot with `--set` or `-f`

This is blocking https://github.com/istio/istio/pull/18991 so putting as a P0

**Comment by richardwxn** [comment]
I think setting it in component k8s spec works, try this below? I would check why the overlay part doesn't work
```yaml
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  trafficManagement:
    enabled: true
    components:
      pilot:
        enabled: true
        k8s:
          env:
            - name: PILOT_TRACE_SAMPLING
              value: "50"
```

**Comment by richardwxn** [comment]
Did some investigation, seems like it is because the k8s resource settings from IstioControlPlaneSpec would override the values pass through overlay. https://github.com/istio/operator/blob/master/pkg/component/component/component.go#L755

Do we need to support this use case, e.g. setting traceSampling under values.pilot? I think we may need to support only setting k8s resource settings from iscp components spec and corresponding overlays field.

@ostromart WDYT since you made this part of change

**Comment by howardjohn** [comment]
@richardwxn I think we definitely do. The fact that its an environment variable is an implementation detail that we should not expose to users
