### ISSUE TITLE
Operator should detect cloud environment and apply specific values

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#19182]
The operator can detect which kubernetes distro it is running in and apply specific defaults. The primary use case I am thinking of here is for CNI, where different vendors need different values set. While a simple thing, I think this is one of the things holding cni back from being the default

**Comment by howardjohn** [comment]
specifically for CNI we may want to see if we can determine what values we need to set directly, rather than encoding some logic like "on GKE set xyz". not sure if that's possible

**Comment by howardjohn** [comment]
We may also want to detect if "trustworthy jwts" are enabled and turn SDS on/off based on that.

**Comment by howardjohn** [comment]
this would be useful for CNI. We cannot detect the cniBinDir apparently, but we can add hardcoded `if GKE -> ..., if openshift -> ....`.

@jwendell what is the best way to tell which version of openshift someone is on? Just parse `kubectl version` (that is what my plan for GKE was)? Or does it not matter since people are using Maistra on openshift?

**Comment by jwendell** [comment]
I would say it's not a top priority because OpenShift users should use Maistra.

That said, `oc version` parses the output of `<cluster-url>/apis/config.openshift.io/v1/clusteroperators/openshift-apiserver` to determine the OpenShift version, falling back to the behavior of `kubectl version` if that URL gives a 404 (ie, the cluster does not run OpenShift)

**Comment by ostromart** [comment]
I'm going to keep this open for 1.6 to revisit if there's anything else which makes sense to have provider specific logic.

**Comment by jwendell** [comment]
not stale
