### ISSUE TITLE
ServiceEntry protocol HTTPS vs TLS documentation + Virtual Services requirements

### ISSUE THREAD

**Issue by piotrgwiazda** [istio/istio#19188]
**Describe the feature request**
On these two documentation pages: 
- https://preliminary.istio.io/docs/tasks/traffic-management/egress/egress-control/
- https://preliminary.istio.io/docs/tasks/traffic-management/egress/wildcard-egress-hosts/
one can find multiple examples of egress traffic control. However, the samples on these two pages differ with no clear reason. Please update the documentation and clarify:

1. For a simple traffic control (no egress gateway) when specifying a ServiceEntry/port, the first page uses `protcol: HTTPS` and the other `protocol:tls`. What is the difference and why? Is "tls" needed when using wildcards?
2. Is there a required naming convention for ports?
3. When to use `resolution: DNS` vs `resolution: NONE`? Is NONE for wildcards and DNS for full FQDN or can I use NONE for all entries? It's for simple egress control only.
3. When is the VirtualService required if only a simple egress traffic control is the case? Can it be safely omitted if no egress gateway is used? The [first page does](https://preliminary.istio.io/docs/tasks/traffic-management/egress/egress-control/#access-an-external-https-service) not show Virtual Service in samples, while [the latter sample contains it](https://preliminary.istio.io/docs/tasks/traffic-management/egress/wildcard-egress-hosts/#configure-direct-traffic-to-a-wildcard-host).

**Describe alternatives you've considered**
I've tried searching through the github issues and discuss.istio.io

**Additional context**

**Comment by howardjohn** [comment]
> For a simple traffic control (no egress gateway) when specifying a ServiceEntry/port, the first page uses protcol: HTTPS and the other protocol:tls. What is the difference and why? Is "tls" needed when using wildcards?

@vadimeisenbergibm can you help here? I am not sure

> Is there a required naming convention for ports?
https://istio.io/docs/ops/traffic-management/protocol-selection/

> When to use resolution: DNS vs resolution: NONE? Is NONE for wildcards and DNS for full FQDN or can I use NONE for all entries? It's for simple egress control only.

NONE will pass traffic through. So if you your client resolves `foo.com` to 1.2.3.4 we will send the traffic to 1.2.3.4. This is generally pretty useful for external services. DNS will do the resolution inside envoy and then do envoys smart load balancing between those. So if you have a DNS setup where you return multiple IPs and want to do some advanced LB that may be more useful, but general NONE is acceptable.

> When is the VirtualService required if only a simple egress traffic control is the case? Can it be safely omitted if no egress gateway is used? The first page does not show Virtual Service in samples, while the latter sample contains it.

You shouldn't need a VirtualService unless you want to use some of the features of them like fault injection, etc

**Comment by piotrgwiazda** [comment]
Thanks! 
So it seems that DNS resolution is not useful for connecting to cloud services (document databases, APIs, queues, vaults). I'll stick to NONE unless I know "why" I need DNS.

I'm struggling with connection errors when pods are starting and trying to narrow down then the problem.
Please clarify the HTTPS vs TLS protocol as well. 

Your comment looks like a great piece of documentation.

**Comment by vadimeisenbergibm** [comment]
@piotrgwiazda cc @howardjohn 
1. It seems HTTPS could be used in both cases, let me check and update the documentation. I think TLS can be used as well, since in this case HTTPS is treated the same as TLS, the Istio proxies see the encrypted traffic only (with SNI), they do not perform TLS termination.
1. As @howardjohn wrote
1. DNS resolution NONE should not work for the full FQDN gateway since this gateway will not be able to resolve the IP of the request (the IP of the request the gateway sees is the IP of the gateway, not the IP of the external service). The wildcard gateway uses an additional proxy, which performs DNS resolution on its own.
1. As @howardjohn wrote, let me remove the VirtualService from the[ the latter sample](https://preliminary.istio.io/docs/tasks/traffic-management/egress/wildcard-egress-hosts/#configure-direct-traffic-to-a-wildcard-host).

**Comment by piotrgwiazda** [comment]
@vadimeisenbergibm thank you! Since I have your attention for a while, I'd like to clarify few details

**ad 1 and 2:**
Looking at the [documentation of the protocol selection](https://istio.io/docs/ops/traffic-management/protocol-selection/) mentioned by @howardjohn I see that the protocol is actually selected by a name prefix. What is the meaning of the `protocol` attribute then?
Let;s say
```yaml
  ports:
    - number: 443
      name: https
      protocol: HTTPS # <--- what do I put here?
```
Should the `protocol` match the name prefix? Is it respected by Istio or just an optional label?

ad 3.
Having entry like this:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: httpbin
spec:
  hosts:
    - httpbin.org
  ports:
    - number: 443
      name: https
      protocol: HTTPS
  resolution: NONE
  location: MESH_EXTERNAL
```
I cannot observe a difference between `resolution: NONE` and `resolution: DNS`.

ad 4. Clear, thanks.

**Comment by vadimeisenbergibm** [comment]
@piotrgwiazda Honestly,  I am not sure what the protocol field is used for in Istio. To be on the safe side, I specify the protocol name.

Regarding `resolution: NONE` and `resolution: DNS`. Sometimes they both work. `Resolution: DNS` is more secure since it instructs Envoy not to trust the original IP of the request, which can be set by a malicious client. `Resolution: DNS` instructs Envoy to the resolve the IP itself.

To check the differences, in the egress traffic control without egress gateway, send an HTTP request to some IP with the HOST header of httpbin.org. With `Resolution: NONE`, Envoy will forward the request to the original IP. With `Resolution: DNS`, Envoy will forward the request to httpbin.org.

**Comment by howardjohn** [comment]
The protocol is only selected by port name for Service because there isn't a proper protocol field on service. On service entry we don't look at the name.

**Comment by piotrgwiazda** [comment]
Thanks for all of your answers. It would be fsntastic if your notes made it to the documentation.

**Comment by eperdeme** [comment]
Really glad this issue is here, been scratching my head on what resolution setting resulted in and HTTPS vs TLS.

**Comment by ldemailly** [comment]
Sorry to necro this but I can't seem to figure out for a ServiceEntry what is the difference between TLS and HTTPS?
(is there one, are they an alias of one another?)

**Comment by learnbyseven** [comment]
Does any one clarify on TLS vs HTTPS ? Its still seems a mystery

**Comment by j-zimnowoda** [comment]
@[vadimeisenbergibm](https://github.com/vadimeisenbergibm) Thanks for clarification about TLS vs HTTPS for `ServiceEntry`
