### ISSUE TITLE
Mixer should pass current istio namespace to adapter

### ISSUE THREAD

**Issue by manlinl** [istio/istio#1924]
The problem I encountered was when I implemented quota handler, the quota name received in handler is fully qualified name `ratelimit.quota.istio-system` instead of just `ratelimit`.  

apiVersion: "config.istio.io/v1alpha2"
kind: quota
metadata:
  name: ratelimit
  namespace: istio-system
spec:
  dimensions:

Can we pass current istio namespace to adapter in adpater.Env to make adapter namespace aware?

**Comment by geeknoid** [comment]
We've talked about this before. We must pass fully-qualified names, otherwise things fall apart if the same name is used in different namespaces within the mesh.

**Comment by douglas-reid** [comment]
Can we provide some clarity on the problem?  It sounds like the fully-qualified name *was* passed. Why is that an issue?  Or am I not understanding something?

Mixer knows the config default space it is operating in (https://github.com/istio/istio/blob/master/mixer/cmd/server/cmd/server.go#L81). But I'm not sure what problem passing that into adapters solves exactly.

Is what is desired the ability to not have to use namespaces for config defaults in names in adapter code?

**Comment by guptasu** [comment]
Manlin is the concern how to separate the full name into individual components ? We might be able to provide some helpers for that. The format of the full name is <instance short name>.<kind i.e. template name>.<namespace of the instance. Which might not always be  default namespace>. Using the format, adapter should be able to parse what they want.

Question for Mixers : 
1. what does it mean to have two different 'ratelimit' metric inside different namespaces ? 
2. How are adapters suppose to use the namespace ? Will it show in the vendors UI ? 
3. Should we disallow such case, basically template and instance short name combination should be unique.

**Comment by manlinl** [comment]
I think @guptasu  calls out some good questions.

**Comment by mandarjog** [comment]
We are already passing fully qualified names.

Quota is a different beast because it is a partially disintermediated API. The client is aware of the specific quota instance, where as that is not the case for check and report.

So far mixer client calls Mixer with exactly one quota name called "RequestCount".
( However now mixer client can call Mixer with specific quota names if so configured.)
Regardless there are two mapping steps here.

* `client.quotaName`  which is used to lookup instance.QuotaName 
    The current impl will end up matching the first occurrence of instance shortname,
* instance.QuotaName --> quotaServer.quotaName 

If we enforce at validation time that quota instance names are unique, we are good to go, but it will  reduce our flexibility of different namespaces using independently dimensioned ratelimits.

```
   service_configs:
     - mesh_service_name: "echo.local.svc"
       google_service_name: "echo.endpoints.cloud.goog"
       quotas:
         - name: ratelimit.quota.istio-system
           google_quota_metric_name: read-requests
           expiration: 1m
```
@manlinl Is the problem https://github.com/istio/old_mixer_repo/issues/1323

**Comment by manlinl** [comment]
@mandarjog, yes istio/old_mixer_repo#1323 is part of the concern. Bigger concern is
" from client point of view, "ratelimit" is a global identifier. But to mixer, it is a namespaced identifier"
