### ISSUE TITLE
rotateDNSCertificatesWhenCertExpired test failure

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#19269]
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/19266/integ-security-k8s-tests_istio/4560
https://prow.istio.io/view/gcs/istio-prow/logs/integ-k8s-116_istio_postsubmit/778

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/19266/integ-security-k8s-tests_istio/4571

**Comment by lei-tang** [comment]
- The statistics for the tests TestDNSCertificate and TestDNSCertificate/regenerateDNSCertificates
from 11-12-2019 to 11-27-2019: out of 93 post-submit tests on https://testgrid.k8s.io/istio_istio_postsubmit#integ-k8s-116_istio_postsubmit, there is one failed test (https://prow.k8s.io/view/gcs/istio-prow/logs/integ-k8s-116_istio_postsubmit/778) for the PR https://github.com/istio/istio/pull/19248.
- The statistics for the test TestDNSCertificate and TestDNSCertificate/rotateDNSCertificatesWhenCertExpired from 11-12-2019 to 11-27-2019: 
out of 535 presubmit tests on https://testgrid.k8s.io/istio_istio#integ-security-k8s-tests_istio, there are 4 failed tests (two failed for the PR https://github.com/istio/istio/pull/19266 and the other two failed for the PR https://github.com/istio/istio/pull/18991).
- To figure out whether the failures are caused by the PRs themselves or caused by bugs of existing Istio code, more investigation is needed.

**Comment by howardjohn** [comment]
on pr 19266 it's an issue with the pr itself, no clue why only this test fails though

**Comment by howardjohn** [comment]
I get logs like 
```
2019-11-27T18:04:42.584522Z	error	failed to update secret istio-system/dns.istio-galley-service-account (error: Operation cannot be fulfilled on secrets "dns.istio-galley-service-account": the object has been modified; please apply your changes to the latest version and try again)
```

In CI and when I run locally

**Comment by myidpt** [comment]
@howardjohn Is this fixed today?

**Comment by zuehlke-dea** [comment]
@howardjohn I would also be interested in that. We see the same error on our production cluster with istio certificates. 
kubernetes version 1.16.7 and istio 1.3.1
