### ISSUE TITLE
istioctl verify-install gives an error if istio-system ns exists

### ISSUE THREAD

**Issue by jwendell** [istio/istio#19350]
If `istio-system` namespace already exists, it doesn't necessarily mean that Istio cannot be deployed, therefore it should not be considered an error by `verify-install`. Warning sounds more realistic. Unless there are Istio pods/deployments/objects in it. This is a signal that in fact Istio might be already installed.

**Comment by esnible** [comment]
@jwendell after talking with Iris we came to the conclusion that changes are needed in `verify-install`

- We should separate out the compatibility check from the Istio-is-healthy check.
- We need to understand how `verify-install` will work when the user has multiple Istio control planes in the same cluster.

See https://github.com/istio/istio/issues/20355 for separating out precheck.

**Comment by esnible** [comment]
@irisdingbj the feedback from Erin Gannon regarding install using the Operator shows that users want to watch the progress if Istio install.  If they are installing via the Operator, and not the CLI, it isn't obvious when Istio becomes available for use.

We need to make sure that `istioctl verify-install` produces good output so that users who are installing via the Operator can run this command **DURING** installation and get output to tell them if their Istio is installing, ready, or failed.  I don't know if this should be part of this work item or a different work item.  Can you do a test where Istio is installed (via `manifest apply` or the Operator) and in another window `istioctl verify-install` is run continually in a loop and verify that during installation it doesn't terrify the user by saying installation has failed when actually it is still proceeding?)

**Comment by esnible** [comment]
Fixed with https://github.com/istio/istio/pull/22846
