### ISSUE TITLE
Make mx filter configurable on selectively upstream/downstream exchange

### ISSUE THREAD

**Issue by bianpengyuan** [istio/istio#19385]
Metadata exchange filter decides injection and removal of metadata based on direction information from listener. The logic works well for ingress and inter mesh case. But for cases like egressgateway where listener is configured as outbound, or white box middle proxy configured by Sidecar API, header injection/removal purely based on listener direction might not be intended. We probably should make mx filter configurable to selectively exchange on upstream/downstream connection.

cc @kyessenov @gargnupur @mandarjog

**Comment by kyessenov** [comment]
Sure. Let's just specify what we want from egressgateway / middlebox and apply it consistently by adding it to envoy xDS traffic direction. I bet it affects more than exchange, things like tracing, sanitizations, etc.

**Comment by kyessenov** [comment]
I'm not sure configuration is the solution. The problem is that a single listener context is shared between routes with different security levels. E.g. if I have an outbound listener with two routes:
- route 1 sends to another internal micro-service;
- route 2 sends to `cia.gov`
then I would like to forward trace context and peer metadata to route 1 but not route 2.
What we're looking for is a route property that indicates whether the route is internal or external regardless of the traffic direction. This way we don't have to specialize our filter per route, and we can tolerate the switch of route 2 to use egress gateway better.
