### ISSUE TITLE
is it possible to use istio and traefik  at the same time?

### ISSUE THREAD

**Issue by hillbun** [istio/istio#19536]
is it possible to use istio and traefik  at the same time?

**Comment by howardjohn** [comment]
Sure, you can use traefik just like any other applications. You can replace ingressgateway if you want

**Comment by LaysDragon** [comment]
I have try myself to get traefik together,it work fine,but here is a problem 
traefik connect to the pod directly via pod ip,and that seems escape the server mesh and caused tracing graph lost a piece of data of traefik to pod on kiali. I can only see a PassthroughCluster here
and connection directly to pod ip seems not handle by istio,that the down side if you use traefik it 
 seems outside the server mesh and visual service might won't work,I still trying to find a way if traefik can connect to service instead of pod ip

![image](https://user-images.githubusercontent.com/10185394/73638339-2acf5380-46a5-11ea-827f-a19850900803.png)

**Comment by howardjohn** [comment]
I see, I didn't realize traefik would use pod IP without host header? This is tracked in https://github.com/istio/istio/issues/23494 which has some conversation around this. To simplify things, lets consolidate there. Thanks!

**Comment by freek-hoekstra-cardano** [comment]
@howardjohn Do I understand correctly from reading #23494 that it should now be possible to use Traefik ingress with Istio service mesh?

**Comment by howardjohn** [comment]
https://github.com/istio/istio/issues/23494 only makes it work with a pretty narrow set of use cases + config. 

FWIW Ambient works out of the box in this regard.

**Comment by howardjohn** [comment]
https://preliminary.istio.io/latest/docs/ops/integrations/loadbalancers/ is a new doc just merged about this

**Comment by freek-hoekstra-cardano** [comment]
Thanks for the quick replies! I will look into it. A chained setup might be good for us. My problem is that a subset of the services on my cluster rely heavily on very specific behavior of Traefik routers. If it is not too difficult, I would like to install istiod on the cluster and start using the Istio service mesh, mainly for its mTLS authentication layer, while keeping Traefik as is.

If that is too difficult though, I will use the full Istio setup with the Istio Ingress controller. It looks customizable enough that we should be able to get it to work however we need.

**Comment by ra-ramos** [comment]
> Thanks for the quick replies! I will look into it. A chained setup might be good for us. My problem is that a subset of the services on my cluster rely heavily on very specific behavior of Traefik routers. If it is not too difficult, I would like to install istiod on the cluster and start using the Istio service mesh, mainly for its mTLS authentication layer, while keeping Traefik as is.
> 
> If that is too difficult though, I will use the full Istio setup with the Istio Ingress controller. It looks customizable enough that we should be able to get it to work however we need.

did you check this article?
[https://thenewstack.io/using-traefik-ingress-controller-with-istio-service-mesh/](url)
