### ISSUE TITLE
Propagated trace ID changed unexpectedly

### ISSUE THREAD

**Issue by kelvin-yue-scmp** [istio/istio#19545]
**Bug description**

I have two applications (namely A & B) running on the namespace. The request flow would be like below

Client -> Istio ingressgateway -> App A -> App B

A trace ID would be generated by the ingressgateway, both A, B are instrumented to propagate tracing headers.

However, I have met the situation that the trace id is modified when pass on to app B.

The logs of both application are as below

App A logs
```
Route /send
request header { host: '47.56.4.233',
  'cache-control': 'max-age=0',
  'upgrade-insecure-requests': '1',
  'user-agent':
   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
  accept:
   'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
  'accept-encoding': 'gzip, deflate',
  'accept-language': 'zh-HK,zh-TW;q=0.9,zh;q=0.8,en-US;q=0.7,en;q=0.6',
  'if-none-match': 'W/"16-AyckYgrkAeF1fMc1+tTxlLJ8Of8"',
  'x-forwarded-for': '172.17.28.104',
  'x-forwarded-proto': 'http',
  'x-request-id': '253a8939-661e-97f1-80c5-e0bd81d2a57f',
  'content-length': '0',
  'x-envoy-internal': 'true',
  'x-b3-traceid': 'b551dcc09f045657e3ced8e9010ec440',
  'x-b3-spanid': 'de5bc54c53e7160c',
  'x-b3-parentspanid': 'e3ced8e9010ec440',
  'x-b3-sampled': '1' }
build header 1 { 'x-b3-traceid': 'b551dcc09f045657e3ced8e9010ec440',
  'x-b3-parentspanid': 'de5bc54c53e7160c',
  'x-b3-spanid': 'aabe57e21b9d6914',
  'x-b3-sampled': '1',
  'x-custom-tag': 'send' }
```

App B logs
```
receive header { host: 'node-app-b:3000',
  'x-forwarded-proto': 'http',
  'x-request-id': '2567e78f-c8e6-9081-b75e-a371d591a1ae',
  'content-length': '0',
  'x-b3-traceid': '39afe2c9b3726360563e3f897b1bf368',
  'x-b3-spanid': 'fdbc4ce0abc93537',
  'x-b3-parentspanid': '563e3f897b1bf368',
  'x-b3-sampled': '1' }
forward header { 'x-request-id': '2567e78f-c8e6-9081-b75e-a371d591a1ae',
  'x-b3-traceid': '39afe2c9b3726360563e3f897b1bf368',
  'x-b3-spanid': 'fdbc4ce0abc93537',
  'x-b3-parentspanid': '563e3f897b1bf368',
  'x-b3-sampled': '1' }
```

So you can see from the trace ID in header sent from ingressgateway is `b551dcc09f045657e3ced8e9010ec440` (App A request header)
The trace ID in header sent to App B is also `b551dcc09f045657e3ced8e9010ec440` (App A build header)

The trace ID in header sent from A to B has changed to `39afe2c9b3726360563e3f897b1bf368` (App B request header)

The app above are using with jaeger client.
I have also tried to use without instrumentation by just pass the span headers directly, but it doesn't have the issue.

**Expected behavior**

the trace id should be propagate properly

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

istioctl output

```
client version: 1.4.2
control plane version: 1.4.2
data plane version: 1.3.0 (6 proxies), 1.4.2 (5 proxies)
```

kubectl version

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:18:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-aliyun.1", GitCommit:"51888f5", GitTreeState:"", BuildDate:"2019-10-16T08:29:13Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

Using helm with customization

**Environment where bug was observed (cloud vendor, OS, etc)**

Istio 1.4.2, Kubernetes 1.14.8

**Comment by chris-ng-scmp** [comment]
I have the same issue too! wanna know why....

**Comment by bianpengyuan** [comment]
Most likely proxy of App A generates a new trace id because it cannot find any trace context in the headers of App A -> App B call.

> I have also tried to use without instrumentation by just pass the span headers directly

Do you mean you tried manually copy trace context headers (trace id, span id etc), and then app B could receive the same trace id? I have never use jaeger client, but seems like the jaeger client is not properly used to populate trace context for correlated calls.

**Comment by kelvin-yue-scmp** [comment]
> Most likely proxy of App A generates a new trace id because it cannot find any trace context in the headers of App A -> App B call.
> 
> > I have also tried to use without instrumentation by just pass the span headers directly
> 
> Do you mean you tried manually copy trace context headers (trace id, span id etc), and then app B could receive the same trace id? I have never use jaeger client, but seems like the jaeger client is not properly used to populate trace context for correlated calls.

Yes, I have tried another version of the program without using Jaeger client, which directly copy trace context header then app B can correctly receive the trace context.

**Comment by kelvin-yue-scmp** [comment]
@bianpengyuan

Without instrumentation, pass through header
<img width="1332" alt="Screenshot 2019-12-31 at 10 36 11 AM" src="https://user-images.githubusercontent.com/45190481/71608129-ae36ea00-2bb9-11ea-92f8-cddece15b1ec.png">
<img width="1419" alt="Screenshot 2019-12-31 at 10 36 33 AM" src="https://user-images.githubusercontent.com/45190481/71608130-b000ad80-2bb9-11ea-88ae-0b6b4bbc65c7.png">

Instrumented, using jaeger client
<img width="1322" alt="Screenshot 2019-12-31 at 10 36 03 AM" src="https://user-images.githubusercontent.com/45190481/71608127-abd49000-2bb9-11ea-8d71-7ea26fefc4f6.png">
<img width="1415" alt="Screenshot 2019-12-31 at 10 36 59 AM" src="https://user-images.githubusercontent.com/45190481/71608132-b2fb9e00-2bb9-11ea-9d78-796faa1e5ddc.png">

there would be an error showing invalid parent span id

**Comment by bianpengyuan** [comment]
So all the spans share the same trace id? istio proxy supposes to copy span id to the parent span id. Could you check whether the invalid parent span id is the same as `node-app-a.default` server span id? Anyway, it does not look like an istio issue. Most likely it is because jaeger client does not work along with istio proxy.

**Comment by objectiser** [comment]
@kelvin-yue-scmp Seems like two different issues - in your original description you were showing that the trace id from service A was different to service B. However in the screenshots above it shows that service A and B are both reporting spans for the same trace id. So it looks like your originally described issue no longer exists.

In both trace views, with and without jaeger java client, it shows the same number of spans. So the most likely cause of the issue is that your jaeger java client instrumented app is creating spans within the app, but they are not being reported to the backend. So as these intermediate spans are not available in the backend, the full end to end trace cannot be represented in the UI.

**Comment by kelvin-yue-scmp** [comment]
@bianpengyuan @objectiser Thanks for the reply, have some inspiration for solving the issue.
