### ISSUE TITLE
Add feature gate to enable incremental MCP

### ISSUE THREAD

**Issue by kevin21th** [istio/istio#19622]
**Describe the feature request**
Currently, whether the incremental MCP is enabled was hardcoded, and there‘s no way to enable incremental MCP in mcpController.

**Describe alternatives you've considered**
On Galley side, add a feature gate to control whether enabled incremental or not.
On Pilot side, add a feature gate to set incremental flag on MCP request.

**Additional context**
In 1.4, only SyntheticServiceEntry support incremental update, why?

**Comment by seflerZ** [comment]
There is no controller support for MCP incremental except "SyntheticServiceEntryController" at present. I think you can describe your business process and tell us why and which resource you want to make it incremental.

I personally suggest that the next step on MCP incremental should be endpoints because endpoints are coupled in "ServiceEntry". This makes it hard to handle changes within large clusters.

**Comment by kevin21th** [comment]
@seflerZ Exactly, the coredatamodel controller does not yet support incremental MCP, so it must be implemented first.
