### ISSUE TITLE
Istio 1.1 web sockets are disconnecting

### ISSUE THREAD

**Issue by searceinc** [istio/istio#19664]
We have deployed Istio 1.1 on Openshift 3.11 cluster. One of our application is Websockets application. While connecting websockets from browser, after 2-3 minutes the websockets connection is getting closed. We are not getting any logs at both client (Javascript) level and server application level. 

Istio :- 1.1
Openshift OKD :- 3.11
Cloud Environment:- AWS

**Comment by howardjohn** [comment]
Connections will drain if Istio sends new listener config. We have fix a few similar bugs since 1.1. 1.1 is no longer supported, per https://istio.io/blog/2019/announcing-1.1-eol/, so I would suggest you upgrade and see if you are still impacted.

When doing so, it may be useful to get a config_dump from before and after the connection closes

**Comment by adamzhoul** [comment]
same question.

 since my ingress(istio envoy) is working on production, we can't upgrade easily.
 is there another way?  like, upgrade envoy image only?

 by the way, I capture net traffic use tcpdump.
 get Fin package, send by ingress.   But, I  never changed the listener config.  

 
thanks @howardjohn

**Comment by adamzhoul** [comment]
update

  when I deploy a new pod, I can reproduce this.

  I think that deploying a new pod triggers eds push. which leads to envoy hot restart.

  And envoy dropped this long connection.
