### ISSUE TITLE
Port name analyzer is too spammy

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#19688]
As mentioned in the PR, this analyzer is too spammy. For example, on a tiny cluster I get:

```
Info [IST0118] (Service istio-ingressgateway.istio-system) Port name status-port (port: 15020, targetPort: 15020) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service knative-service-8dbvq-private.knative-1-40835) Port name queue-metrics (port: 9090, targetPort: queue-metrics) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service knative-service-j4nt6-service.knative-1-40835) Port name metrics (port: 9090, targetPort: queue-metrics) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service knative-service-j5pv2-private.knative-1-66474) Port name queue-metrics (port: 9090, targetPort: queue-metrics) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service kube-dns.kube-system) Port name metrics (port: 9153, targetPort: 9153) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service tiller-deploy.kube-system) Port name tiller (port: 44134, targetPort: tiller) doesn't follow the naming convention of Istio port.
```

There is a near 0 chance I am going to change kube-system, so we probably don't want to analyze that. Our own ingressgateway install doesn't even follow the convention either...

Out of the box we should probably have 0 analysis messages, so it seems wrong to report these.

I think this cannot be truly solved without just making this analyze opt-in?

cc @sushicw

**Comment by sushicw** [comment]
For context convenience: this was introduced in https://github.com/istio/istio/pull/19375. 

CC @selmanj since this is very relevant to recent discussions about suppression & selection. 

I agree that as it stands, this analyzer is too broad, and needs to be more narrowly targeted. Even if it were "opt in" (something I'm not entirely comfortable with), if a bunch of the messages shown are meaningless or unactionable, it's not valuable to the user. Maybe even worse than nothing. 

I'm still not comfortable with the idea that we're simultaneously touting protocol detection as an easier way to configure their mesh, and also telling users no, it's actually not good enough. Our docs do not make the tradeoff (security) clear at all. We should get clarity on exactly what configuration we want to recommend to the user, and what we want to have by default. Not having security-by-default seems antithetical to a lot of what we're trying to do with Istio, IMHO.

**Comment by selmanj** [comment]
I could see an argument for providing analyzers like these, disabled by default but can be run on demand. @sushicw has pointed out this isn't a great experience though as users have to discover and reason about what each analyzer does. Perhaps we could have some preconfigured profiles (e.g. '`istioctl analyze --profile=secure`')?

I think Chris is right though - this is pointing to a painful UX/security tradeoff that is probably more fundamental to the usability of istio itself than something that should be addressed purely with an analyzer.

@yxue , if a user isn't using protocol detection, is it still a security issue if a user hasn't labeled their ports?

**Comment by howardjohn** [comment]
@selmanj there is no security issue with port labeling if its off, but you lose functionality. If your port name is `foo` it is treated as tcp, and therefor you won't get http metrics for example.

**Comment by selmanj** [comment]
And, just to be clear, it _is_ a security issue if you're using protocol detection, right? From issue #19387 :

>>Could you help me understand why a user would want to migrate to named ports if protocol detection is working for them?

> The traffic could bypass authN/authZ policy when using protocol detection. E.g., if the user apply the policy to enable GET only. Because pilot cannot infer the protocol from the port name, it will create both HTTP and TCP filter chains and the client can send TCP traffic to bypass that policy.

**Comment by howardjohn** [comment]
Yes, it is a security issue if you are using protocol detection. This was brought up very often in the original design and decided it wasn't a big issue :woman_shrugging:

**Comment by yxue** [comment]
John has explained a lot. I'd like to give more details.

```
 -- protocol detection on ---- named ports (secure) 
 |                                       |
 |                                       |--- unnamed ports ----- TCP ports (secure)
 |                                                           |--- others (not secure)
 |- protocol detection off ---- all ports (secure)
```

**Comment by sushicw** [comment]
> Yes, it is a security issue if you are using protocol detection. This was brought up very often in the original design and decided it wasn't a big issue

...and this is where I feel like we're being a bit uncomfortably schizophrenic. If it's not a big issue, why report it to the user at all? I guess this is the argument for opt-in, that it's useful but only for a very niche set of users. 

I'd still prefer to make the analyzer smarter, if possible, so that we're only triggering on unsecure user configurations. This maybe means updating the messaging as well, so users aren't confused that they're getting complaints about unnamed ports when they turned on protocol detection so they wouldn't have to name ports. 

@howardjohn Should we at least be updating the docs (https://preliminary.istio.io/docs/ops/configuration/traffic-management/protocol-selection/) to clarify the security implications?

**Comment by selmanj** [comment]
I see two uses for this analyzer:

1. **Warn the user they're missing out on functionality**

An analyzer probably makes sense, here. You could imagine how frustrating it'd be to discover that your service hasn't been logging http metrics for the past three months because you forgot to label it an http service. I don't think we should do it by default though just because of the sheer number of messages it can produce, and the fact that an unlabeled port is not a problem with the mesh.  

The analyze that complains when a namespace isn't labeled for injection is actually pretty similar to this analyzer (it complains about the namespace not being explicitly labeled for sidecar injection), but I guess it doesn't suffer similarly since the number of namespaces is expected to be much smaller than the number of services.

2. **Warn the user of a potential security issue with protocol detection and unlabeled ports**

This is a great use for an analyzer! However, I think it should be a different analyzer to the one currently implemented. "doesn't follow the naming convention of Istio port" makes the issue sound pretty innocuous.

Consider what it _should say - something like "Port 8080 does not have a protocol labeled and the mesh is using automatic protocol detection. AuthN policies that are HTTP-specific can be bypassed by callers." That's much more alarming, and users are going to be upset if they discover this potential security issue on a live mesh.

 I can't help but repeat my message from the PR:
>Some users won't care about the security issue, and just want things to work (maybe they're not using authn policies at all). Those users are benefitting from using protocol detection because it's less work on their part. They will be annoyed by this message.
> 
> Some users will care about the security issue. For users who care, why would they continue using protocol detection if they have to label all their ports anyway?

**Comment by sushicw** [comment]
The first issue should go away in 1.5 anyway, right? Once protocol detection is on by default, the only reason the user would care is to handle the security issue. Or am I missing something?

**Comment by selmanj** [comment]
@sushicw I think protocol detection can only detect http/http2, which is a small subset of the supported protocols (but maybe it's better now?).

**Comment by esnible** [comment]
Does anyone know what `needs-escalation` means?

**Comment by howardjohn** [comment]
@esnible https://github.com/istio/istio/wiki/Issue-and-Pull-Request-Lifecycle-Manager

**Comment by esnible** [comment]
This is P0 because the messages @howardjohn shows are unhelpful.  It is unfortunate the original PR was merged without more review.
Info [IST0118] (Service istio-ingressgateway.istio-system) Port name status-port (port: 15020, targetPort: 15020) doesn't follow the naming convention of Istio port.  @sushicw 's approval was enough.

Istio probably shouldn't complain about things in `kube-system`.  Can we disable checks for `kube-system`, or for all namespaces that aren't labeled for Istio injection?

This message complains about istio-ingressgateway.istio-system.  That service exposes **8** ports.  Do we really expect that every port a service expose be annotated for Istio data plane configuration?

Can we make this item opt-in for the hardening path only?  Even if opt-in, should we skip non-injected namespaces, or namespaces that end in `-system`?  Should we skip Services with >N ports?

**Comment by howardjohn** [comment]
> Can we make this item opt-in for the hardening path only?

+1

> Even if opt-in, should we skip non-injected namespaces

No, non-injected services still matter if you are calling them

> or namespaces that end in -system? 

Probably more specific to just kube-system and istio-system?

> Should we skip Services with >N ports?

I don't think we should do this

**Comment by yxue** [comment]
I am going to skip the check for services in kube-system and istio-system.

**Comment by sushicw** [comment]
My concern with making this analyzer opt-in is that we'll end up maintaining something that never gets used. If we do go this route, can we make it on by default for the "hardening path?" Does that even mean anything concrete at this point?

**Comment by sushicw** [comment]
On a fresh cluster with just Istio installed from master, here's what I currently see related to port name analyzer:

```
$ for i in install/kubernetes/helm/istio-init/files/crd*yaml; do kubectl apply -f $i; done
...
$ istioctl manifest apply --set profile=demo
...
$ istioctl analyze -v --all-namespaces
...
Info [IST0118] (Service jaeger-collector-headless.istio-system) Port name jaeger-collector-grpc (port: 14250, targetPort: 14250) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service jaeger-collector.istio-system) Port name jaeger-collector-grpc (port: 14250, targetPort: 14250) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service jaeger-collector.istio-system) Port name jaeger-collector-http (port: 14268, targetPort: 14268) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service jaeger-collector.istio-system) Port name jaeger-collector-tchannel (port: 14267, targetPort: 14267) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service jaeger-query.istio-system) Port name query-http (port: 16686, targetPort: 16686) doesn't follow the naming convention of Istio port.

```

It looks like looking for label `istio: <anything>` isn't quite enough to catch all control plane components after all. They all do seem to have label `release: istio` though. Maybe we should check that as well? 

@howardjohn , any thoughts on this?

**Comment by howardjohn** [comment]
I don't think they all have release=istio either (hurray for consistency). But you could probably do `istio: || release: istio` I guess

**Comment by sushicw** [comment]
After the above fix I'm not seeing any more port name analyzer false positives on a fresh istio install. @howardjohn Are you still seeing (or anticipating) other false positives we aren't yet handling?

**Comment by howardjohn** [comment]
I wouldn't say false positives. There is still the case though that you have a huge cluster, install Istio and inject a couple namespaces that call each other. You run the tool and it tells you that 40000 services have unnamed ports, when logically you only care (and can control!) about the few namespaces. But not the biggest issue
