### ISSUE TITLE
Istio Multicluster DNS lookup of remote service without .global suffix.

### ISSUE THREAD

**Issue by venkatnsrinivasan** [istio/istio#19682]
Hello All
I have setup a istio multicluster mesh using replicated control planes as specified here

https://istio.io/docs/setup/install/multicluster/gateways/

Everything is actually working fine but there is one thing i am not able to figure out .
If i execute
curl httpbin.bar.global:8000/headers it works fine.
but if i execute
curl httpbin.bar:8000/headers it consistently gives me a 503 with
“upstream connect error or disconnect/reset before headers. reset reason: connection failure” . The dns resolution in either case seems to be fine and it does connect to 240.0.0.2 but in the second case the request never reaches the proxy on the other end as indicated by the istio-proxy logs on the httpbin pod.  The proxy on the outbound service (sleep) detects the IP configured in the cluster but passes it to the PassthroughCluster. Here are the two different outputs with and 
without ".global" suffix

"GET /headers HTTP/1.1" 200 - "-" "-" 0 533 13 11 "-" "curl/7.64.0" "96b17548-4fb6-4e66-85cc-9b1a49623f6a" "httpbin.bar.global:8000" "10.11.84.71:15443" outbound|8000||httpbin.bar.global - 240.0.0.2:8000 101.125.99.102:50544 - default

GET /headers HTTP/1.1" 503 UF "-" "-" 0 91 1001 - "-" "curl/7.64.0" "28b0f9be-3f2d-4fd0-990d-cc9c60a72aa8" "httpbin.bar:8000" "240.0.0.2:8000" PassthroughCluster - 240.0.0.2:8000 101.125.99.102:50576 - -

Thanks

**Comment by johscheuer** [comment]
The error probably happens on the remote gateway (you will see this if you add debug logs or use something like tcpdump). The problem is that the remote gateway only knows for `*.global` and not for `*.bar` what to do. If you really require this you need to add `*.bar` to the gateway config (see: https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/gateways/templates/preconfigured.yaml#L155-L184) or you add some enoyfilter that appends `global` if it is missing for the ip range (actually I don't know how trivial/possible this is).
