### ISSUE TITLE
Istio proxy should advertise capabilities

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#19711]
At present istio proxy has build versions like the following
`node.build_version: a7b2578494d79fe098f0e99282e0236946562fa0/1.12.0/Clean/RELEASE/BoringSSL`
`node.metadata.ISTIO_VERSION: 1.4.2`

When https://github.com/envoyproxy/envoy/pull/9301/files merges we should advertise capabilities.

**Comment by howardjohn** [comment]
One problem with this that looking at the version doesn't have is we may not know we should be advertising until later. So I may support field "foobar" but not realize I should be advertising it, then months later we decide we need to set foobar in pilot but proxies that support it didn't advertise it. The version works though since we can backtrack and realize we supported foobar since 1.x.y
