### ISSUE TITLE
Authn filter should use first SAN URI with spiffe:// for principal

### ISSUE THREAD

**Issue by prabushyam** [istio/istio#19767]
**Bug description**
We use a custom CA for workload mTLS and when the SAN URIs field contain multiple items, the [current logic](https://github.com/istio/proxy/blob/24e971ff31c5cce22e9ab49f8478629f50664846/src/envoy/utils/utils.cc#L50) takes the first item irrespective of the URI scheme as the principal for subsequent authorization.

e.g. 
```URI:schemexyz://domain/subdomain/nsA/svcA, URI:spiffe://domain/ns/nsA/sa/svcA```

The first URI is used by our CA provider for a different purpose, and the SPIFFE URI is used for Istio authN/Z. When such a cert is used for mTLS, the authn filter uses the first item(`schemexyz://...`) as the `source.principal` and hence results in a subsequent authorization failure as the policies are defined for the URI with `spiffe://...`. 

As a temporary workaround, we are able to switch the order of the URIs to have the SPIFFE as the first item and have the authentication set the desired `source.principal`. However, this order cannot be always guaranteed, as it depends on the CSR generation process.

Since we already strip out the `spiffe://` prefix from the URI while setting the `source.principal`, would it make sense to use the first URI that *contains* the `spiffe://` prefix?

One potential impact with the fix would be users that do not currently use the `spiffe://` URIs. We could always support backward compatibility by returning the first URI if one with `spiffe://` prefix is not found.

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
Istio 1.3.6
Kubernetes 1.13.7
**How was Istio installed?**
Use helm templates 
**Environment where bug was observed (cloud vendor, OS, etc)**
Private cloud

**Comment by yangminzhu** [comment]
> One potential impact with the fix would be users that do not currently use the spiffe:// URIs. We could always support backward compatibility by returning the first URI if one with spiffe:// prefix is not found.

I think this is not a problem because the istio authN filter always assume the workload certificate is issued by Citadel, which puts only 1 URI SAN in the certificate.

I think it seems fine to change the authN filter to be more tolerant here by checking all SANs in the certificate and use the one with spiffe prefix. 

@prabushyam But please be noted that the change is only an implementation detail because Istio doesn't officially support to use custom CA for workload issuing certificate with multiple URI SANs.

Note `An X.509 SVID MUST contain exactly one URI SAN.` (https://github.com/spiffe/spiffe/blob/master/standards/X509-SVID.md#2-spiffe-id)

 @myidpt @diemtvu could you provide some feedback on this? thanks

**Comment by prabushyam** [comment]
Fixed with https://github.com/istio/proxy/pull/2617
