### ISSUE TITLE
Refactor mesh config used by pilot to use a platform registry spec

### ISSUE THREAD

**Issue by gnirodi** [istio/istio#1980]
This refactor is being done as part of Multi-Zone Istio capability
Design doc ref: https://goo.gl/AQARBs

The plan should be to use the same spec both, in the mesh config file and  later on the cluster registry.
Low level design details:
- Determine the  Istio Registry Spec. These are common elements required for all clusters participating in the config.
- The registry spec should contain the Istio zone spec
- The only field other required at the registry level may be the config.istio.io/mesh-sync.namespace-blacklist
- At the moment the Istio cluster spec may need 3 fields at least
  1. config.istio.io/mesh-sync.platform (Eureka, Consul, K8s)
  2. config.istio.io/mesh-sync.zone i.e the Istio Zone 
  3. config.istio.io/mesh-sync.zone-agent i.e. the IP+port (mostly VIP) of the pilot's xZone gRPC Endpoint. This field should only be required for the actual cluster running the pilot. Others can skip

- Upcoming PRs will integrate with the K8s cluster registry and we'll adopt portions of  the mesh config pertaining to the cluster list and the individual Istio cluster spec. Talking to k8s folks, these portions are best represented as annotations on K8s resource objects.

**Comment by gnirodi** [comment]
jfyi - I'm expecting baoli@cisco.com to pick this up and incorporate portions of his POC code into it.

**Comment by baodongli** [comment]
I spent some time on the k8s cluster registry. There is a user doc in a PR although it doesn’t provide an example that illustrates each of the fields supported by the ClusterSpec . First of all, it seems to be developed for k8s only. Secondly, I compared the ClusterSpec with the kubeconfig, and it seems to contain only a portion of the kubeconfig’s contents. 

Given the time we have to deliver, for the first iteration, I'm planning to implement the following cluster spec:

apiVersion: config.istio.io/v1alpha1
kind: Cluster
metadata:
name: string # the cluster’s name
label: string
spec:
    platform: <istio|k8s|euraka|consul> # ‘istio’ indicates this is a cross-zone registry
    registry:
         istioRegistryFor: string                # pilot zone name. If not null,                                                            this is the pilot’s CRD/ingress controller registry.
         registryEndpoint:  string             # endpoint in the form of IP:PORT, hostname:port, URL?
         accessConfig: string                     # a kubeconfig file in case of k8s, a consul config in case of consul, etc. 
   serviceBlacklist:  […]                         # services not participating the service mesh, interpreted by individual platform. For k8s, it’s a list of namespaces.
    istioZone: string                                 # the pilot zone name this cluster belongs to

The reason to use the kubeconfig file directly for now, is that I need more research on what should be abstracted out of all the platforms. Alternatively, accessConfig can be a separate resource later when we use a registry (instead of files) to implement the clusterspec. 

This Is how to use it:
-	Create a file for each of the clusters that’s going to be part of the service mesh and saved into a directory.
-	Create a config map off of the directory
-	Load the config map as a volume in pilot’s deployment
-	Each pilot is started with a unique zone name
-	Pilot processes the config files and instantiate registries/controllers.

When deploying istio, users can put all the files in a well-known directory and the above can be achieved as part of the deployment.

Let me know your feedback or any comments on naming, layout, missing fields, etc. I will start coding it up as soon as we have this initial version nailed.

**Comment by cmluciano** [comment]
@ayj How does this play with #1895

**Comment by ayj** [comment]
@gnirodi, @baodongli - the automatic proxy injection code (webhook/initializer) needs access to mesh and proxy configuration to properly configure injected sidecar proxies. It needs access to the `ProxyConfig` from https://github.com/istio/api/blob/master/mesh/v1alpha1/config.proto via ConfigMap. What does this proposed change mean for that workflow? Will injection service need to look elsewhere for the `ProxyConfig` now?

**Comment by baodongli** [comment]
@ayj @cmluciano I think the 'mesh config' referenced in this PR is different from that in #1895. Refer to 'mesh config' in https://goo.gl/AQARBs.

@gnirodi, we might want to change the terminology here? or Have I misunderstood it?

**Comment by cmluciano** [comment]
Does mesh config in the design doc mean "configuring the xDS" for the mesh or is it the configuration of the mesh runtime itself i.e. https://github.com/istio/istio/blob/master/install/kubernetes/istio.yaml#L947-L1019

**Comment by gnirodi** [comment]
https://goo.gl/AQARBs is about configuring the Pilot for multi-cluster. 

In an upcoming PR we hope to source this info from a K8s cluster registry which stores a list of clusters along with metadata. All we need is a list of clusters, the cluster name, the pilot endpoint for that cluster, the platformRegistry type (Consul/K8s....) and the optional istio-zone (we may rename this to cluster-group)

As we speak we see that this info is represented in MeshConfig https://github.com/istio/api/blob/master/mesh/v1alpha1/config.proto#L109 read here by Pilot
https://github.com/istio/istio/blob/master/pilot/cmd/pilot-discovery/main.go#L86

We think we need both - reading from a file for development / testing and in the future reading from the cluster registry.

What is your proposal for doing this with the least of disruption for everyone?

**Comment by ayj** [comment]
I propose https://github.com/istio/istio/pull/1895 continue to use https://github.com/istio/api/blob/ecdcbe628b39330bb236a1d2a9f5ff228149cc3b/mesh/v1alpha1/config.proto#L109. The PR that adds the multi-zone-aware mesh config needs to update consumers anyway (e.g. pilot). As part of that PR the code injection code can also be updated. @cmluciano or myself can help review the injection specific parts to make sure the conversion doesn't break anything.

**Comment by gnirodi** [comment]
@baodongli  do you think you could sequence this PR immediately after #1895 goes in? All this PR does is allow for multiple K8s clusters, the addition of cluster-group and changes to https://github.com/istio/istio/blob/master/pilot/cmd/pilot-discovery/main.go#L86

**Comment by gnirodi** [comment]
#2880 has been merged
