### ISSUE TITLE
istioctl --set cannot handle numeric strings

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#19921]
```
$ ik manifest apply --set hub=localhost:5000 --set tag=1578154376
Error: failed to generate and apply manifests, error: failed to generate tree from the set overlay, error: bad path=value: tag=1578154376
```

This works in helm with --set-string if I understand correctly

**Comment by ostromart** [comment]
This seems to be a problem with StringSliceVarP, since it seems I can pass numbers to StringVarP flags ok. May need to re-implement that flag as a StringVarP in that case.

**Comment by morvencao** [comment]
It's actually caused `ParseValue` at: https://github.com/istio/operator/blob/master/cmd/mesh/manifest-common.go#L195 

If you try to print the ummarshal error at https://github.com/istio/operator/blob/master/cmd/mesh/manifest-common.go#L206
you will find it's actually caused a bad type after parsing the value:
```
json: cannot unmarshal number into Go value of type string
```

**Comment by ostromart** [comment]
In fact the issue here is that tag is defined as type string in the proto, which seems reasonable enough - the only problem is that since we are using jsonpb, a number cannot be unmarshaled into a string type. The solution is the make the proto tag field a sythetic type which yields an interface{} when compiled into Go structs.
