### ISSUE TITLE
iptables: subcommand under pilot-agent

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#20038]
istio-init is already using the proxyv2 docker image, with two (maybe 3, not sure if we have the "clean" binary as well) binaries for init and proxying. We should just merge the two into a single binary with multiple cobra commands. This makes operation simpler since there is a single binary and makes the build, image pull, etc faster since the image is smaller.

cc @lambdai @rlenglet @abhide

**Comment by rlenglet** [comment]
I agree. I think this should be fairly straightforward, since @abhide has made the code modular.

When Istio CNI will integrate that implementation, it will be in the form of a library too, not as a command.
It may be a good opportunity to replace all the `fmt.Print*()` calls with proper logging, and maybe also to move this code from `istio/tools` to `istio/pkg`.

**Comment by lambdai** [comment]
The 2 you mean istio-iptables and pilot-agent? I think it's nice to merge into one.

> It may be a good opportunity to replace all the fmt.Print*() calls with proper logging, and maybe also to move this code from istio/tools to istio/pkg.
+1

**Comment by howardjohn** [comment]
> The 2 you mean istio-iptables and pilot-agent

Yes, so you would have `pilot-agent proxy` and `pilot-agent iptables` or something
