### ISSUE TITLE
Locality aware routing even when disabled

### ISSUE THREAD

**Issue by Stono** [istio/istio#20060]
**Bug description**
We have `global.localityLbSetting.enabled=false` in our installation as per https://istio.io/docs/ops/configuration/traffic-management/locality-load-balancing, so why are we seeing locality clusters in envoy metrics which seem to imply it is running (more traffic being sent to europe_west4), eg:

```
envoy_cluster_zone_europe_west4_c_europe_west4_a_upstream_rq_time_sum{cluster_name="outbound|80||app.search-one.svc.cluster.local"} 48534298.75
envoy_cluster_zone_europe_west4_c_europe_west4_b_upstream_rq_time_sum{cluster_name="outbound|80||app.search-one.svc.cluster.local"} 3275293.4500000001862645149230957
envoy_cluster_zone_europe_west4_c_europe_west4_c_upstream_rq_time_sum{cluster_name="outbound|80||app.search-one.svc.cluster.local"} 3128675.5499999998137354850769043
```

The metrics it produces are also very high cardinality, you're taking `buckets` and multiplying the existing metrics x number of zones!

I noticed this whilst investigating https://github.com/istio/istio/issues/20055

**Expected behavior**
Locality aware routing being disable should disable it, including any high cardinality metrics it produces?

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.4.2

**How was Istio installed?**
Helm

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

**Comment by howardjohn** [comment]
Isn't this an envoy metric that is disabled by default? are you explicitly enabling it?

I would need to look into it more but my initial thought is that envoy still knows about the zones it's just not respecting them when load balancing since you have the feature disabled

**Comment by Stono** [comment]
Hey @howardjohn. 

Yeah we are setting the inclusion prefix (`sidecar.istio.io/statsInclusionPrefixes: cluster.outbound,listener,cluster,cluster_manager,listener_manager,http_mixer_filter,tcp_mixer_filter,server,cluster.xds-grpc`), because we're interested in the non-locality versions of these metrics, i wouldn't have expected to get locality metrics with the feature disabled (or they'd have a value of 0).

As for traffic, that doesn't explain why 25% more traffic has gone to west4-a though (when there was one pod in each zone).

**Comment by howardjohn** [comment]
See the doc here: https://www.envoyproxy.io/docs/envoy/latest/configuration/upstream/cluster_manager/cluster_stats#per-service-zone-dynamic-http-statistics

Here is what I did:

* Set up a few deployments across zones (with locality lb enabled). Send traffic to them.
* Witness the same metrics you see, but traffic distribution is even (outlier detection is required)
* Add outlier detection, all traffic stays within zone.
* Turn off locality lb, traffic is now evenly distributed (sort of... This did point me to another issue that could be related to yours, but initially seems like its not since you have regions for all: https://github.com/istio/istio/issues/20077)

If you were inadvertently getting locality lb applied I would expect near 0 requests to the other regions unless they have a lot of errors, so I think its possible its from other factors

**Comment by Stono** [comment]
It’s a super simple deployment :( Is there any more deterministic in a config dump that would tell me if locality is enabled or not?  As trying to infer it from the metrics is weak at best

**Comment by howardjohn** [comment]
@Stono envoy doesn't include EDS in the config dump which makes it a bit challenging. But /clusters general gives enough info, may help to post that here?. We also improve the edsz debug interface to take in a specific proxy like `8080/debug/edsz?proxyID=shell-868c4ccf97-xnkn5.default` but its not great since it requires you to happen to land on the pilot that proxy is connected to, and I think its only in master not 1.4

**Comment by Stono** [comment]
Closing, old issue and things seem to be fine on 1.4.6
