### ISSUE TITLE
Investigate missing datasets in perf dashboard for master since 20191228

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#20064]
http://perf.dashboard.qualistio.org/benchmarks/cpu_memory/
http://perf.dashboard.qualistio.org/benchmarks/latency/

"master" charts are missing many configurations since 20191228.

**Comment by carolynhu** [comment]
There are 2 hours difference because mixer_both and v2_both is not triggered and run. I will make a fix.

**Comment by carolynhu** [comment]
The missing both mode is because, after this PR: https://github.com/istio/tools/pull/653
we replace `--clientsidecar` to `--bothsidecar`. We need to explicitly make `--bothsidecar` to be `True` in order to make sure both mode being triggered and run. 

This issue is fixed in this PR: https://github.com/istio/tools/pull/690
