### ISSUE TITLE
istioctl manifest apply: use "smart" CLI output for progress

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#20189]
Current output looks like:
```
- Applying manifest for component Base...
✔ Finished applying manifest for component Base.
- Applying manifest for component Citadel...
- Applying manifest for component Addon...
- Applying manifest for component SidecarInjector...
- Applying manifest for component Galley...
- Applying manifest for component Telemetry...
- Applying manifest for component Policy...
- Applying manifest for component IngressGateways...
- Applying manifest for component Pilot...
✔ Finished applying manifest for component SidecarInjector.
✔ Finished applying manifest for component Citadel.
✔ Finished applying manifest for component Addon.
✔ Finished applying manifest for component Galley.
✔ Finished applying manifest for component Policy.
✔ Finished applying manifest for component IngressGateways.
✔ Finished applying manifest for component Pilot.
✔ Finished applying manifest for component Telemetry.
```

It would be nice if instead of printing a new line when its done we were replacing the `-` with a `✔`. We can do similar for the output to --wait (this is a bigger motivator, since the output is really long).

Other CLI tools like linkerd, kind are doing this. If its 1000s of lines to write this though then obviously not worth the investment..

**Comment by esnible** [comment]
Erin Gannon’s deck on friction encountered by new users installing Istio (video at https://youtu.be/nGnKkyltm9w?t=284 ) says "Output of successful commands should print as warnings rather than errors."  The current output, "Finished applying manifest for component X" is not especially clear.  The last line, "✔ Installation complete".  I am not sure what is output when there is problems.  Should we also consider a progress bar output?

**Comment by esnible** [comment]
Erin Gannon’s deck on friction encountered by new users installing Istio (video at https://youtu.be/nGnKkyltm9w?t=284 ) mentions that users who are deploying Istio on a cluster with existing apps don't know what to do next.

"✔ Installation complete" means the control plane is installed.  Users don't know
- That they may need to enable auto-injection on namespaces and restart pods to "install" the sidecars that make up the data plane.
- After the data plane is up they can check their work using `istioctl dashboard grafana` and friends.

Should we also add a line or two of output telling the user what to do once the control plane is active?

**Comment by esnible** [comment]
@howardjohn I am tempted to close this because your work adds much better support for `apply` output.

The remaining work are the bullet points on what a user should do post-install https://github.com/istio/istio/issues/20189#issuecomment-576833124 .  Shall I create a new issue that `apply`, `install`, and `upgrade` should also output a few lines of text making suggestions about what to do AFTER installing Istio?

**Comment by howardjohn** [comment]
Yeah I would say the original issue presented here is done. The followups of the actual output and "next steps" type info is not, could be separate issue if you want or this one
