### ISSUE TITLE
gRPC config stream closed: 13

### ISSUE THREAD

**Issue by Emmerson-Miranda** [istio/istio#20360]
**Bug description**
Envoy proxy close connections on a HTTPS service.

I have published a service using HTTPS following Istion official documentation [Secure Gateway using SDC](https://istio.io/docs/tasks/traffic-management/ingress/secure-ingress-sds/) 

Differences:
- I did generate certificates using Hashicorp Vault (using REST pi), not mtls-go-example.
- Gateway, VirtualService, Deployment and Secret are on dev namespace (not default one).

**Affected product area**

**Expected behavior**
Be able to consume the service using https.

Bellow the curl command with the error.
````
$ curl -iv -HHost:httpbin.dev.uk \
> --resolve httpbin.dev.uk:$SECURE_INGRESS_PORT:$INGRESS_HOST \
> --cacert /Users/emmerson/Desktop/VAULT-ISTIO/tmp/httpbin-dev-uk.ca_chain \
> https://httpbin.dev.uk:$SECURE_INGRESS_PORT/status/418


* Added httpbin.dev.uk:443:192.168.99.103 to DNS cache
* Hostname httpbin.dev.uk was found in DNS cache
*   Trying 192.168.99.103...
* TCP_NODELAY set
* Connection failed
* connect to 192.168.99.103 port 443 failed: Connection refused
* Failed to connect to httpbin.dev.uk port 443: Connection refused
* Closing connection 0
curl: (7) Failed to connect to httpbin.dev.uk port 443: Connection refused
 ````

**See below the sidecar Envoy error log.**
````
$ kubectl logs -l app=httpbin -c istio-proxy -n ucmdev -f

[Envoy (Epoch 0)] [2020-01-21 01:42:21.661][19][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:91] gRPC config stream closed: 13
````

**Steps to reproduce the bug**

- Create root CA, Intermediate and Identity certificates using Hashicorp Vault REST API.
- Create the secret using certificates given by Vault responses
- Make CURL call to the service

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**
Using Helm charts

**Environment where the bug was observed (cloud vendor, OS, etc)**

A local machine with macOS Catalina version 10.15.2

Istio
````
client version: 1.4.2
control plane version: 1.4.2
data plane version: 1.4.2 (13 proxies)
````

Minikube
````
minikube version: v1.6.2
commit: 54f28ac5d3a815d1196cd5d57d707439ee4bb392
````

**Comment by freedome-max** [comment]
UnsubscribeSent from my Samsung Galaxy smartphone.
-------- Original message --------From: Emmerson <notifications@github.com> Date: 1/21/20  10:03 AM  (GMT-06:00) To: istio/istio <istio@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [istio/istio] gRPC config stream closed: 13 (#20360) Bug description
I have published a service using HTTPS following Istion official documentation Secure Gateway using SDC
Differences:

I did generate certificates using Hashicorp Vault (using REST pi), not mtls-go-example.
Gateway, VirtualService, Deployment and Secret are on dev namespace (not default one).

Affected product area
[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
Expected behavior
Be able to consume the service using https.
Bellow the curl command with the error.
$ curl -iv -HHost:httpbin.dev.uk \
> --resolve httpbin.dev.uk:$SECURE_INGRESS_PORT:$INGRESS_HOST \
> --cacert /Users/emmerson/Desktop/VAULT-ISTIO/tmp/httpbin-dev-uk.ca_chain \
> https://httpbin.dev.uk:$SECURE_INGRESS_PORT/status/418


* Added httpbin.dev.uk:443:192.168.99.103 to DNS cache
* Hostname httpbin.dev.uk was found in DNS cache
*   Trying 192.168.99.103...
* TCP_NODELAY set
* Connection failed
* connect to 192.168.99.103 port 443 failed: Connection refused
* Failed to connect to httpbin.dev.uk port 443: Connection refused
* Closing connection 0
curl: (7) Failed to connect to httpbin.dev.uk port 443: Connection refused

See below the sidecar Envoy error log.
$ kubectl logs -l app=httpbin -c istio-proxy -n ucmdev -f

[Envoy (Epoch 0)] [2020-01-21 01:42:21.661][19][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:91] gRPC config stream closed: 13

Steps to reproduce the bug

Create root CA, Intermediate and Identity certificates using Hashicorp Vault REST API.
Create the secret using certificates given by Vault responses
Make CURL call to the service

Version (include the output of istioctl version --remote and kubectl version and helm version if you used Helm)
How was Istio installed?
Using Helm charts
Environment where the bug was observed (cloud vendor, OS, etc)
A local machine with macOS Catalina version 10.15.2
Istio
client version: 1.4.2
control plane version: 1.4.2
data plane version: 1.4.2 (13 proxies)
```

Minikube
```
minikube version: v1.6.2
commit: 54f28ac5d3a815d1196cd5d57d707439ee4bb392
```

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/istio/istio/issues/20360?email_source=notifications\u0026email_token=AOK33QLFBDPUN7M55GU5BQLQ64MD5A5CNFSM4KJV4M6KYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IHVVTSQ",
"url": "https://github.com/istio/istio/issues/20360?email_source=notifications\u0026email_token=AOK33QLFBDPUN7M55GU5BQLQ64MD5A5CNFSM4KJV4M6KYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IHVVTSQ",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by JimmyCYJ** [comment]
That gRPC status code 13 is not the cause to this failure.
We haven't tested whether Vault generated cert fits the ingress gateway. Perhaps you can check Envoy config_dump to make sure whether Envoy has active dynamic listener on httpbin 443.
You can also check ingress-sds log to make sure whether a k8s secret which has the gateway TLS key/cert is created, detected by ingress-sds, and check if the key/cert are extracted by ingress-sds and pushed to Envoy.

**Comment by incfly** [comment]
I'm inclined to close this, ingress SDS has enough test coverage, I suspect this is a setup specific issue, but I'll let @JimmyCYJ to decide.

**Comment by howardjohn** [comment]
Closing as this hasn't gotten the required debug info for a few months. Please reopen if you are still seeing issues!
