### ISSUE TITLE
Kubernetes Ingress with Cert-Manager not working on a brand-new cluster.

### ISSUE THREAD

**Issue by sanigo** [istio/istio#20680]
**Bug description**
It is a new installed `1.4.3` cluster.
According to the guide, <https://istio.io/docs/tasks/traffic-management/ingress/ingress-certmgr/>.
The tls certificate will not be issued normally.
The auto generated ingress named `cm-acme-http-solver-xxxxx` which serves `http://$INGRESS_DOMAIN/.well-known/acme-challenge` is not working:
`HTTP/1.1 503 Service Unavailable`
If i delete the sample helloworld-ingress and recreate the certificate, the `cm-acme-http-solver-xxxxx` will become available, and the certificate will be issued.
And if i create the certificate before creating the sample helloworld-ingress, the certificate could also be issued.
It seems that the existing helloworld-ingress would break the acme process.

**Expected behavior**
The certificate should be issued even if there are existing ingress.

**Steps to reproduce the bug**

1. Create a new istio 1.4.3 cluster.
2. Follow the guide: <https://istio.io/docs/tasks/traffic-management/ingress/ingress-certmgr/>

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
istio: 1.4.3
kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:29Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
helm version
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Error: could not find tiller

**How was Istio installed?**
helm

**Environment where bug was observed (cloud vendor, OS, etc)**
I have tried to reproduce the issue in the following env:
- Minikube 1.5.2 & Kubernetes 1.14.2
- Kubernetes 1.3.10

**Comment by blhagadorn** [comment]
@sanigo I've also run into problems with that documentation and cert-manager as well recently.  Might I ask what version of `cert-manager` you are using?

**Comment by sanigo** [comment]
> @sanigo I've also run into problems with that documentation and cert-manager as well recently. Might I ask what version of `cert-manager` you are using?

It is the latest version: 0.13.0. And I have modified the apiVersion while tesing.

**Comment by blhagadorn** [comment]
@sanigo Can I also ask if you are using Helm to install cert-manager (and what command). Are you specifying `istio-system` namespace?

**Comment by sanigo** [comment]
@blhagadorn The cert-manager was installed according to the https://cert-manager.io/docs/installation/, I did not use helm and just use the kubectl apply.

**Comment by ArieLevs** [comment]
@sanigo where you able to get the `kubernetes.io/ingress.class: istio` annotation to work?

`Gateway` and `VirtualService` works fine, but using the kubernetes ingress resource does not.

**Comment by haf** [comment]
I experience the same issue and have debugged it a bit further. Background:

- mTLS: false, i.e. the mesh config is ` spec:  peers: mtls: mode: PERMISSIVE`
- However, I have a default route: ```yaml
spec:
  host: '*.local'
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
```
- furthermore, cert-manager (0.13) generates a service with this annotation: `auth.istio.io/8089: NONE` which is warned about from `analyze -k`: `Warn [IST0108] (Service cm-acme-http-solver-jx7g7.monitoring) Unknown annotation: auth.istio.io/8089`.
- furthermore, the ingress for cert-manager doesn't "find the selector": `Error [IST0101] (Ingress cm-acme-http-solver-6fcgp.monitoring) Referenced selector not found: "istio=ingress"`
- However, I don't think either of these is the issue! But on the deployment/pod, there's this annotation: `sidecar.istio.io/inject: "false"`, which indeed causes no sidecar to be injected
- Then, if you also enable envoy access logs (which *really* should log warn/error as default, Istio-people!), you get log lines like this in ingressgateway: `istio-ingressgateway-868c599574-7k76c istio-proxy {"downstream_remote_address":"10.200.0.57:36314","authority":"alerts.dev.afa.nu","path":"/.well-known/acme-challenge/-pAgREGt3j_3nONCquRUr--0yUTLj0jOL_60uXlR6Lc","protocol":"HTTP/1.1","upstream_service_time":"-","upstream_local_address":"-","duration":"24","downstream_local_address":"10.40.3.10:80","upstream_transport_failure_reason":"TLS error: 268435703:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER","route_name":"-","response_code":"503","user_agent":"Go-http-client/1.1","response_flags":"UF,URX","start_time":"2020-02-19T09:33:43.754Z","method":"GET","request_id":"2412a1da-d700-9538-b81b-14a6f49d3e39","upstream_host":"10.40.4.5:8089","x_forwarded_for":"10.200.0.57","requested_server_name":"-","bytes_received":"0","istio_policy_status":"-","bytes_sent":"91","upstream_cluster":"outbound|8089||cm-acme-http-solver-jx7g7.monitoring.svc.cluster.local"}` — AND you get this despite the service's port name being `http` and NOT `https`, most likely due to the `DestinationRule` that I quoted above. Now, I could disable the destination rule, but it would be much better either if cert-manager doesn't forbid the sidecar, or alternatively, if the routing/control layout of Istio would recognise that the target service has opted out of the sidecar, and not try to set up a mTLS connection to it (which is what I believe is happening).

cc @howardjohn

**Comment by haf** [comment]
Related:

- https://github.com/jetstack/cert-manager/pull/1749
- https://github.com/istio/istio.io/issues/868#issuecomment-462761222
- https://github.com/istio/istio/issues/20680#issuecomment-588124135
- https://github.com/jetstack/cert-manager/issues/1535
- https://github.com/istio/istio/issues/6486
- https://github.com/istio/istio/issues/19296#issuecomment-578841838
- https://istio.io/docs/tasks/traffic-management/ingress/ingress-certmgr/

**Comment by haf** [comment]
Update: so it DOES NOT get the cert since it's a TLS type cert; converting the secret to a generic secret, with a `cert` (not `tls.crt` as is the default) and a `key` (not `tls.key` as is the default), *and* placing it in `istio-system` makes it work (as opposed to placing the secret in the actual namespace I've deployed the service in, which would be the sane solution)... I'll file bugs about this, but I got it working at least.

**Comment by verysonglaa** [comment]
> * mTLS: false, i.e. the mesh config is ` spec:  peers: mtls: mode: PERMISSIVE`
> * However, I have a default route:
>   ```yaml
>   spec:
>    host: '*.local'
>    trafficPolicy:
>      tls:
>        mode: ISTIO_MUTUAL
>   ```

@haf 
I had the default DestinationRule only when istio was installed using istioctl and the following value:
spec:
  values:
    global:
      mtls:
        enabled: true

After switching to enabled: true and reapplying it with istioctl this default rule was unfortunately NOT deleted, I guess this is a bug.
After deleting this default DestinationRule Permissive Mode works. I have no idea how to do it in Strict mode without adding istio-injection: enabled to the istio-system namespace (which I guess would bring other problems)

**Comment by verysonglaa** [comment]
tested again: The default rule is indeed there with 1.4.3 in Permissive mode on the first installation on a new cluster. After deleting this Rule it works.

**Comment by incfly** [comment]
Correct me if I'm wrong, after reading through this, seems this is a gap on two features can't work well together: our auto generated ingress.class with SDS feature (two require different type of secrets)

Worth thinking a built-in better support of this two. Place myself as temporary holder.

**Comment by howardjohn** [comment]
We are now supporting `type: kubernetes.io/tls` types, except ca.crt which is sort of a cert-manager extension, see https://github.com/istio/istio/issues/21076. We also are now generating configs that use SDS instead of file mounts (in master)

**Comment by howardjohn** [comment]
I think both of these are done in 1.6. See https://preliminary.istio.io/docs/tasks/traffic-management/ingress/kubernetes-ingress/ and https://preliminary.istio.io/docs/tasks/traffic-management/ingress/secure-ingress/ for docs

**Comment by Anujay-Saraf** [comment]
@howardjohn @gustavovalverde @prune998

Need one help here with your expertise.

I am unable to receive a working certificate thru letsencrypt prod/staging API:

Snapshot

![image](https://user-images.githubusercontent.com/27989098/88177320-4aa00700-cc46-11ea-8724-b75b60cc4816.png)

The current setup includes below approach

K8s cluster setup with 1.0.2 Istio Dex Yaml, mentioned in kubeflow.org documentation, which comes with istio 1.3.1 and cert-manager by default.
As my major task is to complete this with kubeflow enabled with istio-ingressgateway along with HTTPS Lets-Encrypt ACME SSL Certificate generation.
Kindly let me know a possible solution.

K8s API version 1.14
Istio -1.3.1
Cert-Manager: the same which comes with default manifest.

**Comment by aniruddhachoudhury** [comment]
> @howardjohn @gustavovalverde @prune998
> 
> Need one help here with your expertise.
> 
> I am unable to receive a working certificate thru letsencrypt prod/staging API:
> 
> Snapshot
> 
> ![image](https://user-images.githubusercontent.com/27989098/88177320-4aa00700-cc46-11ea-8724-b75b60cc4816.png)
> 
> The current setup includes below approach
> 
> K8s cluster setup with 1.0.2 Istio Dex Yaml, mentioned in kubeflow.org documentation, which comes with istio 1.3.1 and cert-manager by default.
> As my major task is to complete this with kubeflow enabled with istio-ingressgateway along with HTTPS Lets-Encrypt ACME SSL Certificate generation.
> Kindly let me know a possible solution.
> 
> K8s API version 1.14
> Istio -1.3.1
> Cert-Manager: the same which comes with default manifest.

Ya please i am seeing this same error.
