### ISSUE TITLE
BookInfo with Consul: Istio Routing not working

### ISSUE THREAD

**Issue by steffengy** [istio/istio#2080]
Tested using the 0.3 release with docker on windows.

## Steps taken:
- Used `install/*` and `samples/` folder as of e52148bfcbe0caed864aeeb3f0c937c2ca28866f
  since install/consul lacks the kubeconfig file, which leads to very annoying issues to debug
  (Using just kubeconfig from master shows the same behavior)
- Followed steps on https://istio.io/docs/setup/consul/quick-start.html 
- Followed steps on https://istio.io/docs/guides/bookinfo.html#running-on-docker-with-consul-or-eureka
- Ran `istioctl create -f samples/bookinfo/consul/route-rule-all-v1.yaml`
- Accessed `http://localhost:9081/productpage` mutliple times

The last 2 steps are basically the first 2 from https://istio.io/docs/tasks/traffic-management/request-routing.html

## Expected
The round-robin load balance between the different review-service-versions
stops (e.g. consistent result, which would mean that istio actually handles the traffic)

## Actual result
Sometimes the rating stars are red, sometimes they are missing (as they consistently should),
sometimes they are black.

Any idea what's going wrong here, am I just better of with using minikube for now?

**Comment by GregHanson** [comment]
Appears to be two separate problems here.  First, there is a missing step in the docs for bringing up the bookinfo service containers.  Correct steps are:

``` 
docker-compose -f samples/bookinfo/consul/bookinfo.yaml up -d
docker-compose -f samples/bookinfo/consul/bookinfo.sidecar.yaml up -d
```

Second, there is a bug in the `samples/bookinfo/consul/bookinfo.sidecar.yaml` file.  Before running the command above, please replace all occurrences of 

```
    image: docker.io/istio/proxy_debug:0.3.0
```

with 

```
    image: docker.io/istio/proxy_debug:0.2.12
```

in the `samples/bookinfo/consul/bookinfo.sidecar.yaml`  file while the issue is diagnosed

**Comment by steffengy** [comment]
I was wondering how or rather what is responsible for the execution of `bookinfo.sidecar.yaml` - now that explains a lot, thanks!

From a high-level technical point, starting the sidecars, spawns 2 containers: 
proxy and for a short time proxy_init which sets up redirection (iptables) to proxy right?

**Comment by GregHanson** [comment]
yes, that is correct.  The init container runs the iptables rules that redirects all pod traffic through the proxy_debug container, and then it exits on completion.  So the service containers in samples/bookinfo/consul/bookinfo.yaml are just the service containers.  The reason things were working before any rules were created (i.e. seeing the roundrobin behavior between reviews service versions) is because Consul DNS was round robining between the versions by default when it resolves `reviews:9080/reviews`

**Comment by GregHanson** [comment]
bug was a bad default discovery port for xDS API's between pilot-discovery and pilot-agent, 8080 vs 15003.  Code fix in https://github.com/istio/istio/pull/2166

Doc fixed here: https://github.com/istio/istio.github.io/pull/799

**Comment by GregHanson** [comment]
Looks like the openshift guys were hit by a similar issue:
https://github.com/istio/istio/issues/2031
