### ISSUE TITLE
istio_ca causes latency/5xx problems

### ISSUE THREAD

**Issue by kdillane** [istio/istio#2090]
We have seen an interesting problem in our Kubernetes cluster where there are periodic errors and latency increases hourly.  This behavior seems to be caused by the istio-ca pod.  When it attempts to renew the self-signed certificates in the cluster (presumably), it causes both our application Pods and the Istio Ingress to display high latency and 5xx responses.   Please let me know if there are any details that would be helpful with diagnosing this issue.

**Comment by kdillane** [comment]
Just a follow-up, we disabled the istio-ca pods in our cluster and have seen the periodic failures disappear.

**Comment by kdillane** [comment]
This is a pretty big blocker in terms of allowing use of the istio-ca component in our cluster.  I'd be interested if this has been reported by anyone else.

**Comment by myidpt** [comment]
@kdillane I guess this is caused by the rotation of workload certs not CA cert, because by default the Istio CA self-signed certs have 1 year TTL:
https://github.com/istio/istio/blob/master/security/cmd/istio_ca/main.go#L42

So when the workload cert is rotated, the proxy will be restarted, this process takes at most minutes. Unfortunately this causes the existing connections on the workload to be terminated. This can be solved when Envoy supports dynamic cert reloading without dropping existing connections.

The other issue is that if workloads are started together, CA may rotate their certs at the same time (based on the cert TTL). We need to randomize this rotation.

A temporary solution to this is to prolong the cert rotation period:
https://github.com/istio/istio/blob/master/security/cmd/istio_ca/main.go#L120

**Comment by myidpt** [comment]
It's generally not a good idea to set the workload TTL to be too long. Because Istio CA does not have CRL so we rely on the frequent rotation of workload keys/certs to reduce the chance and impact of workload key/cert compromise.

If your workloads do not enable mTLS, with this PR https://github.com/istio/istio/pull/2761 (will take effect in V0.5), the workload will not be restarted hourly.
Of course, you can still change the workload TTL. If your workloads have enabled mTLS, you can set the TTL for workloads to be higher, through this flag on auth node agent: https://github.com/istio/istio/blob/master/security/cmd/node_agent/main.go#L49
Note that the CA has a flag to control the cap TTL for workloads:
https://github.com/istio/istio/blob/master/security/cmd/istio_ca/main.go#L125
You need to modify it if you need the TTL to be longer than default.

**Comment by wattli** [comment]
@kdillane , is your question solved?

**Comment by kdillane** [comment]
My question is answered.  However, it sounds like there is still work to fix the Envoy restart issue, correct?  Is there an open issue to solve the Envoy restart issue when mutual TLS is enabled?

**Comment by wattli** [comment]
Yes, we are actively working on the SDS API work, i.e., key/cert will be delivered via API instead of file read. In that case, we won't need envoy restart thing. https://github.com/istio/istio/issues/5891 Close this one for now.
