### ISSUE TITLE
Root Cert deployment issues

### ISSUE THREAD

**Issue by costinm** [istio/istio#21009]
From a log in one of the test clusters: 
2020-02-10T22:49:54.576246Z     error   error when inserting data to config map istio-ca-root-cert: error when updating configmap istio-ca-root-cert: Operation cannot be fulfilled on configmaps "istio-ca-root-cert": the object has been modified; please apply your changes to the latest version and try again

Not sure what caused it or how to repro, but maybe we should use the old stable code for creating
Secrets from Citadel - or the env variable.

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by lei-tang** [comment]
If there are multiple instances of istiod, each of them will write the CA cert to the configmap. When one istiod instance writes to the configmap before another instance, the second instance will see "the object has been modified; please apply your changes to the latest version and try again". Electing a leader and only the leader writes to the configmap will make the concurrent writing problem go away. Before the leader mechanism is added, the error logs do not cause real problem because one of the instance has updated the configmap for the root certificate.

**Comment by howardjohn** [comment]
@lei-tang we added leader election, only one of them will modify it at once now. Although it was recent, so maybe Costin does not have that

**Comment by howardjohn** [comment]
This is fixed by leader election
