### ISSUE TITLE
istioctl operator message improvements

### ISSUE THREAD

**Issue by esnible** [istio/istio#21116]
The following messages are confusing

```
istioctl manifest versions

Operator version is 1.6.0.

The following installation package versions are recommended for use with this version of the operator:
  1.6.0

The following installation package versions are supported for upgrade by this version of the operator:
  >=1.5.0
   <1.7
```

I believe it should say something like

```
'manifest' can upgrade Istio >= 1.5.0 to 1.6.0
'manifest' can downgrade Istio <1.7 to 1.6.0
```

It is confusing to say we have a list of installable versions when that list has exactly one element.
Apparently it is possible to use `--set installPackagePath=/tmp/nightly` to install some other version than the one that ships with `istioctl`, but let us document that possibility under `installPackagePath`, not `istioctl manifest versions`.

-------------

```
istioctl manifest versions --help
List the versions of Istio recommended for use or supported for upgrade by this version of the operator binary.
```

This text should not say "the operator binary".  We should say `istioctl` or `mesh` (if `mesh` is still a thing).

-------------

`istioctl manifest versions --help` has a parameter `--versionsURI` which is 
```
URI for operator versions to Istio versions map
```

There needs to be an example, or a link to documentation for what that means.

-------------

The output of `istioctl manifest generate --set installPackagePath=/tmp` is huge and confusing.

**Comment by esnible** [comment]
In istioctl, instead of using "the operator binary" in error messages we should make more sense.

@sdake Do you have a preference for changing "the operator binary" to "istioctl" or "manifest" or `os.Args[0]`?

**Comment by esnible** [comment]
Related: https://github.com/istio/istio/issues/20743

**Comment by ostromart** [comment]
The idea we wanted to convey here is that users should not be using arbitrary versions of istioctl to install arbitrary versions of Istio. We'd like them to use istioctl 1.6.0 to install Istio 1.6.0. The reason is twofold: 1. istioctl has version specific code and in some cases this is not selected based on the Istio chart version we are dealing with (we try to avoid it but it's not always possible) and 2. even if all logic were fully versioned, we do not test all permutations of istioctl to istio version (this becomes a very large set when upgrade enters the picture). 
I'd welcome suggestions how we can communicate this better - I assigned @elfinhe for now but if you feel like you have some ideas here @esnible please feel free to take the issue.

**Comment by elfinhe** [comment]
@maasen will be working on this.
