### ISSUE TITLE
helm install: global.jwtPolicy is ignored

### ISSUE THREAD

**Issue by dgn** [istio/istio#21264]
**Bug description**
in `manifests/` we have safeguards to change volumemounts to support clusters without TokenRequest functionality by checking whether `global.jwtPolicy!=third-party-jwt`. This is missing in `install/`. `istioctl` will set this flag automatically, which cannot do with helm, but we should at least be able to add it manually.

**Expected behavior**
helm installs also support the `global.JwtPolicy` flag

**Steps to reproduce the bug**
See #21263

**Comment by howardjohn** [comment]
This is working as intended: https://istio.io/blog/2019/trustworthy-jwt-sds/

The decision was made to only support 3p jwt token in SDS at the time. When we decided to make SDS the default we realized that would not work since not everything supports it. But that doesn't mean we need to backport this to the old helm install where SDS is off by default and Alpha

**Comment by dgn** [comment]
> This is working as intended: https://istio.io/blog/2019/trustworthy-jwt-sds/
> 
> The decision was made to only support 3p jwt token in SDS at the time. When we decided to make SDS the default we realized that would not work since not everything supports it. But that doesn't mean we need to backport this to the old helm install where SDS is off by default and Alpha

Alright, thank you. Closing this
