### ISSUE TITLE
Sticky session using consistentHash (JSESSIONID cookie) not work as expected

### ISSUE THREAD

**Issue by Jefle2005** [istio/istio#21280]
**Bug description**
i'm using bleow DestinationRule to configure session sticky based on JSESSIONID cookie. I found it actually will add a new cookie JSESSIONID but our application tomcat will set such cookie too. so situation is now we have 2 JSESSIONID in the cookie which is still okay. but in our code logic some edge case it relies on this cookie, so if there are 2 cookies with same name, we don't know which one we should take.

**so my actual question is any other way we can do alternative to use JSESSIONID cookie but using the application one instead of creating new one by istio itself?** 

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
spec:
  host: customerportal
  subsets:
  - labels:
      version: green
    name: green
  - labels:
      version: blue
    name: blue
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpCookie:
          name: JSESSIONID
          path: /cp-ui
          ttl: 0s

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[x ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by torstenwerner** [comment]
Couldn't you just use a different cookie name for istio e.g. ISTIOID?

**Comment by saturnism** [comment]
`JSESSIONID` originates from the app server (in this case, tomcat).  If we use a different session ID, e.g., `ISTIOD`, and 2 cookies have different expirations, then...
1) if `ISTIOD` expires first, then user may be routed to a backend that doesn't have the session data, because `JSESSIONDID` is still active. This can cause issues.
2) if `JSESSIONID` expires first, then the user will be routed to the same backend, but with a new session. This isn't as big of an issue.

**Comment by torstenwerner** [comment]
I believe both cookies are real session cookies by default. They expire at the same time – when you close the browser. The backend might implement an idle detection and that means the JSESSIONID based session state will be forgotten before the cookie expires (case 2). That cannot happen to the ISTIOID cookie because it is stateless.
