### ISSUE TITLE
1.5 sds: no documented way to get certificates to a non-envoy application

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#21407]
We added a sidecar to our "demo mode" prometheus installation, but we don't have any (documented) way to get this working for any other application.

Even more importantly, we don't have a way to add this to an existing prometheus install. I believe this will mean pretty much all production prometheus installs with strict mtls are not going to work

**Comment by myidpt** [comment]
I think we need to:
1) Add documentation for injecting sidecars to existing applications loading certs from files.
2) Add documentation for existing Prometheus to inject sidecars. Can we do better than giving the documentation (like automate the upgrade)? Running istioctl with a prometheus component enabled should be able to update the existing Prometheus deployment, right? @mandarjog @douglas-reid 

This is mostly about documentation.

**Comment by howardjohn** [comment]
Existing prometheus means they are not using istioctl to install prometheus. i don't think anyone in production is using the prometheus we ship with our install, its meant for demo only

**Comment by myidpt** [comment]
Got it. We should document how to do it. They have 45 days by default to make the change, which is a reasonable window.

**Comment by howardjohn** [comment]
New installs are broken as well, see the linked kiali bug

**Comment by myidpt** [comment]
Where's the kiali bug?

**Comment by howardjohn** [comment]
https://github.com/kiali/kiali/issues/2440, Kiali also needs to mount a cert. But also a new install of prometheus would be broken. Only upgrades will work for 45 days

**Comment by jmazzitelli** [comment]
I want to make sure I am clear about this Kiali issue in case it is misunderstood.

This should only show up if you install Kiali using the Kiali Operator. If you install Kiali using the istioctl installer, then it should work because it does set the secret to "optional". That is what this [Istio helm setting `kiali.security.enabled` is for](https://github.com/istio/istio/blob/59fbf81d6e3894329799890fc3d574cf85b70556/manifests/istio-telemetry/kiali/values.yaml#L81) - this controls [the secret "optional" flag in the Deployment](https://github.com/istio/istio/blob/59fbf81d6e3894329799890fc3d574cf85b70556/manifests/istio-telemetry/kiali/templates/deployment.yaml#L85-L87) and [does not specify the identity in the configmap](https://github.com/istio/istio/blob/59fbf81d6e3894329799890fc3d574cf85b70556/manifests/istio-telemetry/kiali/templates/configmap.yaml#L45-L49)

So by default, istioctl should circumvent this issue already.

So its a problem only for people that, say, want to upgrade the Kiali that comes with Istio and upgrade to a new Kiali with the Kiali Operator (outside of the istioctl installer)

**Comment by lei-tang** [comment]
https://github.com/istio/istio.io/pull/6554 is created fo this issue.

**Comment by lei-tang** [comment]
On release-1.5 branch, https://github.com/istio/istio.io/pull/6967.

**Comment by myidpt** [comment]
https://istio.io/blog/2020/proxy-cert/

**Comment by myidpt** [comment]
We still need to add a task. Lower it to P1 since we have a blog now.
