### ISSUE TITLE
TestTokenFetchFailureOne test flake

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#21497]
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/21488/unit-tests_istio/9139

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/21559/unit-tests_istio/9270

**Comment by JimmyCYJ** [comment]
Thanks for catching this. This is a test failure. The test force envoy fail to start, and when test tears down and stops envoy, it finds that envoy is killed and logs that as an error.

**Comment by howardjohn** [comment]
still failing per https://prow.istio.io/view/gcs/istio-prow/logs/unit-tests_istio_postsubmit/1704, but should probably keep into one issue: https://github.com/istio/istio/issues/21626

**Comment by JimmyCYJ** [comment]
TestTokenFetchFailureTwo fails because Envoy cannot bind a socket.
"[2020-03-09 15:23:02.780][49098][debug][init] [external/envoy/source/common/init/watcher_impl.cc:27] init manager Server destroyed
unable to bind domain socket with id=0 (see --base-id option)"

The other three tests fail because SSL handshake fails between proxy and dummy XDS server.
"Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED"

These are not in the STS path, perhaps the node is bad?

**Comment by howardjohn** [comment]
only those tests fail so I think it's specific to the tests you have added.
not sure if the issue is STS itself though
