### ISSUE TITLE
TestProxyCachedToken test failure

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#21626]
https://prow.istio.io/view/gcs/istio-prow/logs/unit-tests_istio_postsubmit/1602

**Comment by JimmyCYJ** [comment]
This is caused by a racing condition in the test. The test forces Envoy to reconnect XDS server four times, and verifies that the reconnect uses a cached token in gRPC library, not a new one. At meantime, there is a timer that checks if Envoy is ready after certain amount of time. If timeouts and Envoy is not ready, then the test gives an error log. I am working on deflake the test.

**Comment by howardjohn** [comment]
This is still not fixed: https://prow.istio.io/view/gcs/istio-prow/logs/unit-tests_istio_postsubmit/1704

**Comment by JimmyCYJ** [comment]
The failures are different compared with the ones that were fixed.

TestTokenFetchFailureTwo fails because Envoy cannot bind a socket.
"[2020-03-09 15:23:02.780][49098][debug][init] [external/envoy/source/common/init/watcher_impl.cc:27] init manager Server destroyed
unable to bind domain socket with id=0 (see --base-id option)"

The other three tests fail because SSL handshake fails between proxy and dummy XDS server.
"Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED"

These are not in the STS path, I need to figure out if they are caused by the test setup.

**Comment by howardjohn** [comment]
They are only failing on the STS tests, so while it may not be STS that is the issue I don't think its any issue with the node/CI, just these tests

**Comment by howardjohn** [comment]
Here is a fun one: https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/21825/unit-tests_istio/9902
```
token_failure_test.go:76: 
    Expected
        <int>: 1
    to be >
        <int>: 1
```

:man_shrugging:

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/22622/unit-tests_istio/11158

**Comment by JimmyCYJ** [comment]
All the failures are caused by SSL handshake between Envoy and dummy XDS server.
"Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED"
This could be a test setup issue, because during test setup tests write ca cert into the same file and load into XDS server. I will create a PR to fix that.
