### ISSUE TITLE
Istio Envoyfilter with inline Lua Script  for external_authz always returns 403

### ISSUE THREAD

**Issue by adharsh-m** [istio/istio#21637]
We are in need to customize the istio ingress gateway envoy in order to do authentication with external(external_authz) for all calls coming to microservice hosted inside our K8S cluster as Pods.

we are trying to intercept all traffic at the istio ingress gateway and do make a call to authentication service(which is completely outside of mesh/cluster) and based on its response, will take a call either to pass it to the respective microservices or reject it with appropriate httpcode.

As per Istio doc, we are trying to use the EnvoyFilter option along with lua script. 

For all the calls to Istio IG, we are trying it to redirect to the authentication server and  it is always responding an 403 error(though no credentials is needed at auth server).
We are not finding any logs on our authentication server end

Can someone help? This is blocking our  production deployment 

Below is the script we are using 

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: edge-lua-filter
spec:
  workloadLabels:
    app: istio-ingressgateway
  filters:
  - listenerMatch:
      portNumber: 80
      listenerType: GATEWAY
      listenerProtocol: HTTP
    filterName: envoy.lua
    filterType: HTTP
    filterConfig:
      inlineCode: |
        function process(request_handle, cluster, auth_host)
            request_handle:logWarn("entered process filter")
            request_handle:logWarn("[" .. cluster .. "] Processing...")
            -- Build a request for our authentication service before passing request upstream
            local authentication_request = {
                [":method"] = "GET",
                [":path"] = "/",
                [":authority"] = auth_host
            }

            local response_headers, response_body = request_handle:httpCall(
                cluster,
                authentication_request,
                "",
                10000 --ms
            )
            -- If we don't get a 204 from our Authentication service, reject the request
            if tonumber(response_headers[":status"]) ~= 401 then
                request_handle:logWarn(response_headers[":status"])
                request_handle:logWarn("[" .. cluster .. "] Failed")
                request_handle:respond(
                                {[":status"] = response_headers[":status"]},
                                response_body
                        )
            end
            -- The authentication service responds with a series of headers to Set and Unset
            -- Pass all 'Set-*' headers to upstream
            -- Remove all 'Unset-*' headers from request
            for header, value in pairs(response_headers) do
                local set_header = header:lower():match("^set%-(.+)")
                if set_header then
                    request_handle:headers():replace(set_header, value)
                else
                    local unset_header = header:lower():match("^unset%-(.+)")
                    if unset_header then
                        request_handle:headers():remove(unset_header)
                    end
                end
            end
            request_handle:logInfo("[" .. cluster .. "] Processed")
        end
        -- Called on the request path.
        function envoy_on_request(request_handle)
            process(request_handle, "outbound_.80_._.microservice.microservicens.svc.cluster.local", "{{authentication_server_domain_url}}")
        end
        -- Called on the response path.
        function envoy_on_response(response_handle)
            local headers = response_handle:headers()
            headers:add("X-Envoy-Ingress", os.getenv("HOSTNAME"))
        end
```

**Comment by sdake** [comment]
The networking wg will (likely) need more information about your system to properly debug this issue. There is a template when submitting a bug. I'm not sure why it didn't apply in this case. Filling out the template is the best way to inform the community about how to triage your bug.

**Comment by Adharsh-Muraleedharan** [comment]
@sdake Adding the issue with the Bug Template Below

**Comment by Adharsh-Muraleedharan** [comment]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
The EnvoyFilter should intercept all traffic it receives at the Ingress Gateway and route it to the external authentication server and based on the response from the authentication server either route the traffic to my microservice or reject it.

**Steps to reproduce the bug**
1. Setup a Demo Authentication server outside the Cluster.
2. Apply the Envoy Filter at the Ingress Gateway Level and use the LUA script to verify the response from the Authentication server (The Envoyfilter YAML with Lua Script is given above)
3. Hit some backend service routed through the ingress gateway. 

**ISSUE**
 The request to the Authentication server setup outside the cluster always returns a 403 error

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**istioctl version:**
client version: 1.4.2
control plane version: 1.4.2
data plane version: 1.4.2 (5 proxies)
**kubectl version**
Client Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.7-eks-1861c5", GitCommit:"1861c597586f84f1498a9f2151c78d8a6bf47814", GitTreeState:"clean", BuildDate:"2019-09-24T22:12:08Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-c0eccc", GitCommit:"c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2", GitTreeState:"clean", BuildDate:"2019-12-22T23:14:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
Istio was installed through istioctl command

istioctl manifest generate \
     --set values.gateways.istio-ingressgateway.type=NodePort \
     --set values.grafana.enabled=true \
     --set values.tracing.enabled=true \
     --set values.kiali.enabled=true \
     --set values.prometheus.enabled=true \
     --set values.kiali.dashboard.jaegerURL=http://jaeger-query:16686 \
     --set values.kiali.dashboard.grafanaURL=http://grafana:3000 > $HOME/install_istio.yml

kubectl apply -f $HOME/install_istio.yml

**Environment where bug was observed (cloud vendor, OS, etc)**

Environment : AWS EKS Cluster (version 1.14)

**Comment by Adharsh-Muraleedharan** [comment]
Let us know if you need any more info ?

**Comment by Adharsh-Muraleedharan** [comment]
It would be great if somebody can look into this? we are facing a blocker issue here !
