### ISSUE TITLE
Add requested service info to telemetry

### ISSUE THREAD

**Issue by jshaughn** [istio/istio#21820]
This is the impl task based on this [proposal for improved routing observability](https://docs.google.com/document/d/1--R1QNACYeWgPMqg5wNdKVY2vmh5FeG_CX4_yByOsMI/edit#).  After discussion in the working group option 1 was favored, see [this comment thread](https://docs.google.com/document/d/1--R1QNACYeWgPMqg5wNdKVY2vmh5FeG_CX4_yByOsMI/edit?disco=AAAADkUIpyI).

Basically, the idea is to add requested service fields to the default telemetry, to complement source and destination information.  The addition would be for V2 telemetry only.

cc @douglas-reid 
cc @bianpengyuan

**Comment by jshaughn** [comment]
I had a recent thought on this.  It could make sense to include the requested service/host information only if 1 or more VS were involved in the routing, otherwise the information could be assumed to be the same as the destination service.  This assumes that only a VS can alter the requested routing, I'm not aware of anything else.

**Comment by bianpengyuan** [comment]
So the plan is to add `requested_service_name` to the client side metrics, which is a short service name extracted from host header. Note this will not enabled by default on ingress-gateway to prevent unbound cardinality due to untrusted host header. It could be turned on by tuning envoyfilter configuration. @jshaughn Does this fit your ongoing work?

@mandarjog @douglas-reid @nrjpoddar @kyessenov fyi

**Comment by nrjpoddar** [comment]
@bianpengyuan if users configure VS to do host/Authority re-write will the metric report the before or after?

**Comment by bianpengyuan** [comment]
Yeah currently Stats filter only have OnLog callback which collects stats after request finishes. We should add decode header callback to extract original host header.

**Comment by jshaughn** [comment]
@bianpengyuan @nrjpoddar I'm not sure requested_service_name is sufficient, I think we may need the standard "trio" of requested_service_namespace, requested_service, requested_service_name.  The short name may be insufficient for being able to understand how the requested host results in the resolved destination.  I'd say that if we had to have only one field the requested_service (i.e host) may be the most valuable.

The real intent here is to understand when the requested host is re-routed (or possibly mirrored) to a different destination service due to virtual service definitions.  For me it would be perfectly fine to omit these fields completely for requests unaffected by virtual service (or put another way, when the requested service and destination service are the same).   Ultimately, using requested host information we would like to make a best effort at identifying the VS involved, although there is no real guarantee that a VS can be identified, as the metric data may be in the past but we are looking at current VS definitions.

As for ingress, if it needs to be disabled by default it's fine.  Although, if we are able to limit these fields to when VS are in play, then I think we'd also be able to trust all host header values that matched VS.

Techinally I have no idea if it's feasible to do this work in a way that involves the VS re-routing, but I wanted to just make sure I explained what we're trying to provide n the consuming side. Thanks!

**Comment by bianpengyuan** [comment]
My understanding is that it is not feasible. @nrjpoddar @kyessenov @mandarjog please correct me if I am wrong. What available inside proxy is just host header which reflects client's intend, and virtual host routing table which matches host header to the final service. There is no map from host header to the service it represents. In fact host header is not necessarily mapped to a real service.

Originally I thought short name extracted from host name might satisfy the need, but now I think it might not be. Here is the potential short name extraction logic:
1) If host header only has one part without any dot, use that as requested service name.
2) If host header has more than one part, and the second part is the same as destination namespace, use the first part as requested service name.
3) Otherwise, we don't know how to parse host header, so just copy whole host header as requested service name.

As you can see this is just a best guess and is not reliable. The extracted name might not map to a real service registered.

**Comment by bianpengyuan** [comment]
To draw a conclusion on this, I think it is not quite possible to achieve the desired state. The best effort we could do is to add host header as a label, which does not seem to fulfill kiali's use case. @jshaughn wdyt?

**Comment by jshaughn** [comment]
@bianpengyuan , this was again discussed in the WG meeting on wednesday.  There were a variety of ideas presented, including how tracing could be used and how potentially we could offer more intensive metric labeling for short periods, when debugging.  These are good topics to refine going forward but I think it can still be useful in a non-debug scenario to show as much routing as possible in a topology view, to help developers visualize what is actually happening in their mesh, and to potentially be able to link to a VS definition from topology.   So, for me, it could be still be useful to add request_host as a default label and to then see what we may be able to do with it on the consuming side.  As for ingress, any limitations for security or cardinality are fine, in general it would only be useful when there is some sort of non-default match (i.e. there is a VS host match) in the routing.

Not sure if @nrjpoddar @douglas-reid @mandarjog @kyessenov have any thumbs up, thumbs down reaction, or further comment.
