### ISSUE TITLE
Question/Feature request: "x-accel" capability

### ISSUE THREAD

**Issue by shaunc** [istio/istio#21851]
**Describe the feature request**

Nginx supports redirect based on response headers: https://www.nginx.com/resources/wiki/start/topics/examples/x-accel/

Is it possible to configure a virtual service to allow one service to specify that the response should come from another? If not, it would be a nice feature to have.

**Describe alternatives you've considered**

1) The first service can make a chained request, then stream the result. However, this unnecessarily involves the first service in streaming the second response.

2) I could use an nginx service to proxy the first service -- also unnecessary complexity.

**Additional context**

**Comment by howardjohn** [comment]
I am fairly sure this is not supported in Envoy based on some digging around in https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-redirectaction. Since Istio is built on Envoy, we are limited by the feature set exposed there. Can you file a feature request in Envoy, and if implemented there we can possible expose support? It may be possible with https://istio.io/latest/docs/concepts/wasm/ as well but I am not an expert there

**Comment by howardjohn** [comment]
This needs to be done in Envoy/WASM

**Comment by shaunc** [comment]
Understood
