### ISSUE TITLE
Add `istioctl generate-cert` to expose functions in security/tools 

### ISSUE THREAD

**Issue by irisdingbj** [istio/istio#21990]
Currently in the VM Expansions, we need generate cert/key for VM and we are using `go run ./security/tools/generate_cert -client -host spiffee://cluster.local/vm/iris -mode citadel --out-cert /root/1/cert-chain.pem --out-priv /root/1/key.pem` We need a istioctl function to let user do this instead.

@costinm @liminw @esnible What is your thoughts for this?

**Comment by howardjohn** [comment]
@costinm mentioned this as well, not sure if he had any additional ideas for this as well

**Comment by myidpt** [comment]
Sorry for the late comment. I think accessing the signing key isn't a good practice. In a system that there's only one group of admins with all the privileges, this is feasible. But it's not a good security posture that many customers may concern about, also it doesn't work for customers that use remote CAs.

A better security model is: Only system admins can access the signing key. System admins can configure K8s RBAC for the VM admins, so that VM admins can provision the K8s JWTs for a set of identities from the apiserver (via the TokenRequest API).

The VM bootstrapping certificate provisioning can still be done by istioctl. But istioctl does the following:
1) istioctl calls the apiserver to retrieve the JWT for the VM identity.
2) istioctl uses that JWT to call istiod cert signing API to get the signed certs.

Of course this approach is harder to implement, but I think that's the way we should go. It can also work in more general cases where the CA is remote (you don't have access to the signing key).

@liminw @smawson @costinm WDYT?

**Comment by esnible** [comment]
We need something for https://github.com/istio/istio/issues/24905 .  This is an important item for 1.7 not just for VM expansion, but for istioctl, as a library.

@irisdingbj Let's talk about this when you are back.

**Comment by esnible** [comment]
@irisdingbj Are you working on this?

**Comment by esnible** [comment]
@sdake The cert Makefile makes certs with the filenames needed for VMs.

We no longer need certs for _istioctl_, except for cases where the user doesn't have Kubernetes.  Is there someone who could be assigned to improve the Makefile to generate certs for istioctl?

**Comment by sdake** [comment]
The case where the user lacks Kubernetes is a virtual machine environment? If so, perhaps @myidpt can take a crack at implementing this work as he has strong opinions about how the work should be done.

I don't think the makefile is the right approach. I think direct integration into istioctl is better, even for VMs. For the VM case, as @myidpt outlined in the design he proposed in this issue, the JWT can be directly retrieved from the apiserver.

I know it is useful to talk about Istio not being in Kubernetes environments. I have yet to see a customer that demands no Kubernetes while also requiring Istio. I'm not sure any use case lacking a K8s apiserver makes any sense. Whether Istio likes it or not, we are designed into a corner whereby K8s's APIserver (and CRDS and CRs) must be present in the system.

@myidpt @costinm any thoughts?

If you disagree with my assessment, I'd like to understand the scenario or use case that you wish to solve.

Cheers,
-steve

**Comment by howardjohn** [comment]
Given current plans to use tokens this no longer seems desired. I agree with Steve

**Comment by smawson** [comment]
Yeah I think this is obsolete and can be closed.
