### ISSUE TITLE
Remove compiled in charts from istioctl

### ISSUE THREAD

**Issue by ostromart** [istio/istio#21999]
Need to run this past UX group and get their approval. Tentatively assigning to @howardjohn.
If this is done istioctl should also:
- take chart path as a mandatory parameter
- check for chart compatibility (probably add label to chart somewhere, could also use pilot version)

**Comment by dgn** [comment]
I feel like this is error-prone and degrades UX by a margin. Why do we want to do this? People will start asking (rightly so) why they can't use the charts directly if they have to point at them and keep them around anyway

**Comment by esnible** [comment]
Related: https://github.com/istio/istio/issues/20743

**Comment by dgn** [comment]
Instead of enforcing chart path parameter, could we
- add caching, ie have a stable path to download charts to, like ~/.istioctl/cache/charts/release-1.5.0-charts
- default installPackagePath to current release (or github tarball when pre-release)

this way the user isn't forced to point to a charts dir every time they run istioctl
