### ISSUE TITLE
Question: Mirroring both request and response traffic

### ISSUE THREAD

**Issue by shakefu** [istio/istio#22059]
We're looking at leveraging Istio and we would like to be able to mirror our production traffic to a side service for analysis. It looks like [from the docs](https://istio.io/docs/tasks/traffic-management/mirroring/) that inbound mirroring is quite trivial, but we'd also like to mirror the returned responses through a side service to inspect them for attributes such as HTTP status code or Headers.

Is this something currently possible in Istio through configuration, perhaps by using an intermediate egress Gateway, or would it require a customized load balancer?

**Comment by howardjohn** [comment]
Hi @shakefu . Istio is built on top of https://github.com/envoyproxy/envoy. Since envoy does not support this, Istio cannot either. If this is a requirement, I suggest you open a feature request in Envoy org. If its implemented there we *may* consider adding it to Istio.

Depending on your use case, you may consider using WASM extensibility as well: https://istio.io/latest/docs/concepts/wasm/.

Thanks!
