### ISSUE TITLE
Investigating recent perf pipeline issue: 1.5 is missing v2-both, master is missing both and baseline

### ISSUE THREAD

**Issue by carolynhu** [istio/istio#22066]
As plotted in our perf dashboard:
<img width="1039" alt="Screen Shot 2020-03-10 at 11 29 49 PM" src="https://user-images.githubusercontent.com/29208297/76388860-50e0b700-6327-11ea-8883-d6f6c7afe224.png">

As the date of 03/07, 1.5-release is missing v2-both, master is missing both and baseline modes. Need to get this fixed.

/cc @mandarjog @richardwxn

**Comment by richardwxn** [comment]
I think for the 3/7 case, the 1.5 fails in the middle for the transient error of losing connection to api server, that was why v2-both is missing.

For master, I think that is because we change the labels after we add stackdriver configs, so now it is called "*v2-stats-nullvm" for stats and "*v2-sd-full-nullvm*"/"*v2-sd-nologging-nullvm*", you can download the original csv file from the gcs bucket and you'll see.
