### ISSUE TITLE
Use ProviderID and ClusterID to differentiate service registry type vs. cluster name

### ISSUE THREAD

**Issue by ayj** [istio/istio#22093]
ServiceRegistry and ClusterID are overloaded in the source code. Sometimes it refers to the registry type (e.g. Kubernetes vs. Consul). Other times it is the registry name (e.g. which k8s cluster in a multi-cluster deployment). This is confusing and leads to special cases in the code, e.g. ClusterID is the name _unless_ its Kubernetes in which case it could be the type or the name. The serviceregistry.Instance interface has ProviderID() and ClusterID() but they are not used consistently throughout the  code.

**Comment by howardjohn** [comment]
@stevenctl I haven't been following this closely but may be applicable to what you are doing

**Comment by stevenctl** [comment]
At one point it looks like istiod would default the clusterID for the local cluster to "Kubernetes" is an example of this sort of overlap. Our multinetwork-multicluster docs actually recommend using that value (see https://github.com/istio/istio/pull/23825). In reality we do want to reference registries by clusterID, and what kind of registry by providerID.

**Comment by stevenctl** [comment]
@ayj I made a sample PR https://github.com/istio/istio/pull/23938 that I think takes care of this. It seems like the root of the issue is overloading the value of "Kubernetes" for both provider and cluster id. I couldn't find any references outside what's in this PR that compare Kubernetes with a clusterID. What do you think?

**Comment by howardjohn** [comment]
note stale?
