### ISSUE TITLE
Add other ways to configure the sampling rate for hot update

### ISSUE THREAD

**Issue by livelyRyan** [istio/istio#22204]
Currently, the sampling rate only supports the configuration of environment variables, which makes it impossible to modify the rate after pod has started. Can other configuration methods be provided to achieve hot update?

**Comment by DanielQujun** [comment]
maybe you can try envoyfilter, https://github.com/istio/istio/wiki/EnvoyFilter-Samples#tracing-and-access-logging.

TIPs:
set value to 0 will not work.

**Comment by howardjohn** [comment]
isn't it an environment variable on pilot? meaning it can be updated by restarting pilot not the application. Not ideal either though. I think @douglas-reid might be working on improving this or has more context at least

**Comment by douglas-reid** [comment]
It can be updated by restarting Pilot. But our current recommendation is to use EnvoyFilter, as @DanielQujun suggests.

We are hoping in that in the near future we will have a Telemetry-focused API to hang the concepts off of.

**Comment by livelyRyan** [comment]
Thanks @DanielQujun.

Looking forward to future updates. @douglas-reid

**Comment by dedsm** [comment]
> maybe you can try envoyfilter, https://github.com/istio/istio/wiki/EnvoyFilter-Samples#tracing-and-access-logging.
> 
> TIPs:
> set value to 0 will not work.

@DanielQujun I spent almost two days trying to figure out why my EnvoyFilter wasn't working and it was because of this, I'm setting up a serviceentry for my applications to enrich the tracing by connecting to jaeger and sending extra spans, but that causes envoy to also send the traces of the connection with jaeger, so how could I disable that?
