### ISSUE TITLE
Resolve CVEs for all components

### ISSUE THREAD

**Issue by whitleykeith** [istio/istio#22321]
**Bug description**
Currently every image in Istio has many CVEs. There are currently no critical CVEs, but there are a number of medium and low ones. There are also alot (i.e. almost 400 CVEs) in the coredns plugin.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ X ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
When I scan istio images, they return clean

**Steps to reproduce the bug**
Scan the images with your choice of container vulnerability scanners. 

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.5

**How was Istio installed?**
Istio Controller, standalone

**Environment where bug was observed (cloud vendor, OS, etc)**
Any

**Comment by howardjohn** [comment]
you may be interested in https://istio.io/docs/ops/configuration/security/harden-docker-images/

**Comment by whitleykeith** [comment]
Those look like they solve the issue for some of the CVEs, but the istio/coredns-plugin:0.2-istio-1.1 image has almost 400 CVEs and I dont see a distroless image for that one.

**Comment by sdake** [comment]
@whitleykeith you are absolutely correct distroless is the path forward.

Some features of Kubernetes are not yet available in beta form for Istio to consume. [Ephemeral containers](https://kubernetes.io/docs/concepts/workloads/pods/ephemeral-containers/#uses-for-ephemeral-containers) are needed for some aspects of Istio's correct operation including UX operations via istioctl as well as in some cases correct operation of the sidecar proxy when using distroless. Unfortunately, this feature is currently Alpha and Istio does not take a hard dependency on any alpha feature.

We have talked about adding Ephemeral container support to Istio's distroless implementation. Then operators could run with these containers if they chose. Such a change is fairly challenging to move through all of Istio in a coherent way when we are not certain that Ephemeral containers will make beta, or that the API won't change.

Therefore, [distroless is alpha](https://istio.io/about/feature-stages/#core) in Istio, and we can't make an Alpha feature the default.

As for the coredns-plugin:0.2-istio-1.1 image, you have a very fair point that this plugin is in need of integration into the Istio code base so that it follows the standard CVE procedures.

Cheers
-steve

**Comment by howardjohn** [comment]
@sdake istioctl works with distroless. Ephemeral containers are just needed if you want to run additional debug tools like netstat, tpcdump, etc. We do not have a direct dependency on ephemeral containers

**Comment by sdake** [comment]
@howardjohn - istioctl debug commands use kubectl exec internally.

**Comment by howardjohn** [comment]
`kubectl exec` works with distroless, as long as you are using binaries that are present in the image. We are not using `curl` (at least, at some point we were not) or anything else, so it should be fine

**Comment by sdake** [comment]
@howardjohn ok - well it's hard to keep track of what UX is using. The last conversation I had with @esnible had me thinking istioctl was using kubectl exec- hence the desire to expose a debug interface with a strong security model as per recent community conversations.

One other corner case people seem to run into is the desire to run LUA in the proxy. The Proxy is a full image. It could be made as a distroless image, but iirc, it isn't at the moment (unless things have changed), but proxy will continue to be a weak link in our distroless technology model until ephemeral containers are beta.

Cheers
-steve

**Comment by sdake** [comment]
@howardjohn I re-read what you wrote, and I agree, kubectl exec always works with distroless. I thought this was a more advanced discussion around our roadmap and future work, not whether basic functionality such as `kubectl exec` is directly impaired by distroless. Distroless, as you know, should work with nearly all or any kubectl commands, (including as you point out `exec`. I am a huge proponent of distroless fwiw - I convinced our friends in SAP to do the initial implementation work, and understand distroless' power in removing CVEs.

**Comment by whitleykeith** [comment]
It's good to know that distroless is the end goal. 

In regards to the coreDNS plugin image, what exactly is Istio's coredns component used for in terms of istio features? From my reading, it seems it's primarily used for exposing remote services to the mesh via ServiceEntries. Is there anything else it's used for?
