### ISSUE TITLE
global.outboundTrafficPolicy.mode: Registry_only configuration only blocks http traffic but not other tcp traffic such as mongodb

### ISSUE THREAD

**Issue by anpati1** [istio/istio#22428]
global.outboundTrafficPolicy.mode: Registry_only configuration only blocks http traffic but not other tcp traffic such as mongodb

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**All outbound traffic should be blocked including mongodb when control plane is configured for registry_only external access**

**access mesh external mongodb instance from mongodb client pod within the mesh**

**Version**
client version: 1.5.0
control plane version: 1.0.9-1 [Redhat OpenShift Service Mesh]
data plane version:  (8 proxies)

OpenShift version 4.3

**How was Istio installed?**
Using OpenShift operator hub

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS OpenShift sandbox environment

**Comment by howardjohn** [comment]
Is this Istio 1.0? 1.0.9-1?

If so this version has not been supported for a year now and this code has changed dramatically

**Comment by anpati1** [comment]
Hi, the version information I'm getting when I run istioctl version --remote -i <istio-system namespace> is control plane version: 1.0.9-1

The data plane version I'm getting is 1.1.17*

I appreciate the code has changed a lot but I'm dependent on Redhat to update their fork to reflect upstream changes. 

In the meanwhile are you able to advise if the latest versions blocks all protocols when registry_only is configured?

**Comment by howardjohn** [comment]
@anpati1 I am not explicitly aware of any changes that fix your issue since I have not seen it reported in the past and I am not aware of the root cause. I do know that even if we found the issue, we would not fix it for the version you are on. This is why I suggest you upgrade to a supported issue, and if you see the problem still then we can try to figure out the root cause. If you cannot upgrade because you are using a Redhat variant, than I suggest you file the bug there

**Comment by anpati1** [comment]
Ok. Raising a Redhat ticket. Thanks

**Comment by howardjohn** [comment]
thanks!
