### ISSUE TITLE
Logger attempts to log to /tmp

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#2244]
Log infra (most probably new) attempts to log to `/tmp` dir even when `--logtostderr` is specified.

To address this I have added a `/tmp` directory to the mixer image.
1. Need to investigate why it is writing here
2. Ensure that it is not writing too much.

```
I1219 06:18:42.619386       1 init.go:72] template Kind: apikey, &InstanceParam{Api:,ApiVersion:,ApiOperation:,ApiKey:,Timestamp:,}
log: exiting because of error: log: cannot create log: open /tmp/mixs.896499049fc4.unknownuser.log.INFO.20171219-061842.1: no such file or directory
```

**Comment by ldemailly** [comment]
subscribe

**Comment by geeknoid** [comment]
The default log output target for the new log package is stdout. There's a
command-line option to specify the output path explicitly, which can be any
file of "stderr".


On Mon, Dec 18, 2017 at 10:36 PM, Laurent Demailly <notifications@github.com

**Comment by geeknoid** [comment]
I have a PR out which should fix this.

The problem was that I removed the hack in Mixer that bridge the divide between cobra for cmd-line parsing and glog. This means that glog, still used by the k8s client libs, was not seeing the --logstderr command-line option and was proceeding to log to /tmp (its default).
