### ISSUE TITLE
How to modify and mount the istio-proxy access log name of the business container to the host？

### ISSUE THREAD

**Issue by kuaiwenwu** [istio/istio#22497]
The version of istio that our team is using now is 1.4.6 released
Now there is an urgent need: mount the istio-proxy access log in each business pod to the host machine for archiving and analysis of statistical usage. The log file name generated by the current istio version log configuration can choose not to print, You can also choose to print to the terminal, but it does not support naming by service name, so that the logs cannot be distinguished from services. How to configure the isito-proxy log that can implement each service container can customize the name to ensure that its differences do not conflict.
Or does istio currently have plans for this feature?

**Comment by howardjohn** [comment]
Access log is currently set mesh wide. If you really need to customize this, you can use https://istio.io/docs/reference/config/networking/envoy-filter/. I don't think there are plans to add per-proxy configuration, because kubernetes best practices is to log to stdout and have log exporters like fluentd or others

**Comment by howardjohn** [comment]
I am going to close this because we have a temporary workaround (EnvoyFilter) and having a proper per-service API for telemetry is being tracked in https://github.com/istio/istio/issues/12818 which has a lot of history. Thanks!
