### ISSUE TITLE
Local build for 1.4.7 fails due to istio-private/operator dependency

### ISSUE THREAD

**Issue by tmshort** [istio/istio#22518]
**Bug description**

Tag: 1.4.7
When trying to build, github.com/istio-private/operator is required. As a non-istio developer, I don't have access to this repository from github, and my builds fail.

This dependency is located in go.sum, this was added in commit 5156421ace03295
It changed istio.io/operator to github.com/istio-private/operator

**Expected behavior**

Build to succeed.

**Steps to reproduce the bug**

1. Be a non-istio developer (i.e. no access to github.com/istio-private),
2. Attempt to build istio locally

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

1.4.7

**How was Istio installed?**

It wasn't, I'm trying to build it.

**Environment where bug was observed (cloud vendor, OS, etc)**

Ubuntu 18.04

**Comment by howardjohn** [comment]
sorry about this. We ran into some last minute complications with our private build process and this was the result. We cannot change the tag now since its immutable, but as a workaround you can either remove the `replace` directive or wait a day or so and release-1.4 branch will be updated with all the changes in 1.4.7

**Comment by howardjohn** [comment]
Specifically https://github.com/istio/istio/pull/22523

**Comment by tmshort** [comment]
How about a tag 1.4.7.1 or 1.4.8?

**Comment by ericvn** [comment]
1.4.8 was released which shouldn't have the private dependency.
