### ISSUE TITLE
TestOutboundTrafficPolicy_AllowAny/TCP test flake

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#22717]
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/22632/integ-mixer-k8s-tests_istio/9220

@jacob-delgado likely related to https://github.com/istio/istio/pull/22021, seems the metric doesn't show up. Probably not action needed right now, lets just track this and see if it becomes an issue

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gcs/istio-prow/logs/integ-mixer-k8s-tests_istio_postsubmit/2009
https://prow.istio.io/view/gcs/istio-prow/logs/integ-mixer-k8s-tests_istio_postsubmit/2010

**Comment by jacob-delgado** [comment]
I had seen erratic behavior and reported it as such https://github.com/istio/istio/pull/22021#issuecomment-604770583 and https://github.com/istio/istio/pull/22021#issuecomment-604771256.

The first may be another issue (with the source not reporting tcp metrics), but erratic behavior from prometheus . Given that TCP is the only flaky test it's fine to disable it until we can get a root cause. Thanks for looking into this.

**Comment by howardjohn** [comment]
We may want to actually not use prometheus, and instead hit the sidecar /stats endpoint directly. This would additionally allow us to clear metrics between requests which I think makes it more accurate - currently we cannot validate that two requests increment the same metric accurately

**Comment by douglas-reid** [comment]
I think this is safe to close, what with the removal of Mixer, etc.
