### ISSUE TITLE
Istio Services not able to reach services in other namespaces

### ISSUE THREAD

**Issue by dhineshbabuelango** [istio/istio#22743]
Services in one particular istio enabled namespaces are able to reach services in other namespaces only if I create service entry otherwise I am getting 502 Bad Gateway Error. 

Services in other namespaces(**even if istio label enabled**) are able to communicate without creating service entry.

**Comment by howardjohn** [comment]
Dhineshbabu Elango  14 hours ago
Services in one particular istio enabled namespaces are able to reach services in other namespaces only if I create service entry otherwise I am getting 502 Bad Gateway Error. Do we need to create service entry even if we need to talk to services in other namespaces as well?






John Howard  10 hours ago
sounds like you have a Sidecar resource scoping the config?

Dhineshbabu Elango  10 hours ago
Thanks John, That was the issue.

Dhineshbabu Elango  10 hours ago
so if we intend to use, sidecar, we need to create a separate service entry to all the services in all the namespaces

John Howard  10 hours ago
that doesn't make sense

John Howard  10 hours ago
you should configure your sidecar to include the services you need to call

John Howard  10 hours ago
otherwise you are essentially removing the services then adding them back manual
:+1:
1


Dhineshbabu Elango  9 hours ago
Thanks



Closing based on above resolution ^
