### ISSUE TITLE
proto: tag has too few fields back due to broken usage of protobuf

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#22904]
The IOP proto is golang/proto and it embedds gogo/proto for meshconfig. This is not something that we should do, and leads to the above error message. This was broken in  #22854, which fixed another bug related to the same thing. I think the only resolution is to stop mixing protobuf types

**Comment by esnible** [comment]
Can we ask the gogo or apimachinery folks to fix this?  I left this comment at https://github.com/kubernetes/kubernetes/issues/86739#issuecomment-585830624 but will repeat it here.

The problem is in either the gogo/protobuf library or the apimachinery library.  It can be reproduced with this short code:

```
import (
	"github.com/gogo/protobuf/proto"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)
...
	_ = proto.GetProperties(reflect.TypeOf(metav1.Time{}))
```

Is `protobuf:"-"` a valid tag?  If so, fix https://github.com/gogo/protobuf/blob/master/proto/properties.go#L368 so that it ignores `"-"` the same way it ignores `""`.   If not, replace `"-"` with something valid.

I suspect that gogo/protobuf should ignore `-`.  If you agree, I could make a PR and see what they think of it.

**Comment by howardjohn** [comment]
> I could make a PR and see what they think of it.

The gogo library is dead, no commits in half a year. We would probably need a fork to do this

**Comment by howardjohn** [comment]
Bumping this to release blocker since it breaks `manifest generate`

**Comment by esnible** [comment]
I will take this one over; the problem is that it is logging at INFO level w/o a scope.

I will see what I can do to cause the logging to go under a scope that defaults to ERROR level.
