### ISSUE TITLE
Envoy heap grows very large, never decreases, eventually OOMKilled

### ISSUE THREAD

**Issue by PeterGrace** [istio/istio#22939]
In our environment, The envoy istio sidecar continues to grow heap memory over time, using an incredible amount of ram:

```
istio-proxy@ccb-storage-proxy-5d4986d565-l7pzd:/$ curl http://localhost:15000/memory
{
 "allocated": "69132952",
 "heap_size": "11276386304",
 "pageheap_unmapped": "3571712",
 "pageheap_free": "11155046400",
 "total_thread_cache": "24026688"
}
```

This growth will continue until the container is eventually OOMKilled.  

**Expected behavior**
Envoy would release heap memory over time, instead it grows until it can grow no more and is then OOM Killed.

**Steps to reproduce the bug**
Deploy istio in an environment with considerable amounts of gRPC traffic of various packet sizes.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
  $   kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-14T21:04:32Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.7", GitCommit:"20c697423de11d4d5d08c6832a513217ca11a6aa", GitTreeState:"clean", BuildDate:"2020-02-21T10:47:45Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```
```
  $   istioctl version --remote
client version: 1.4.1
citadel version: 1.4.6
galley version: 1.4.6
ingressgateway version: 1.4.6
kialigateway version:
kialigateway version:
pilot version: 1.4.6
policy version: 1.4.6
sidecar-injector version: 1.4.6
telemetry version: 1.4.6
data plane version: 1.4.6 (48 proxies)
```

```
{
 "version": "f777dd13e28edc4ff394e98cd82c82ca4a2bcc71/1.12.0/Clean/RELEASE/BoringSSL",
 "state": "LIVE",
 "hot_restart_version": "11.104",
 "command_line_options": {
  "base_id": "0",
  "concurrency": 2,
  "config_path": "/etc/istio/proxy/envoy-rev0.json",
  "config_yaml": "",
  "allow_unknown_static_fields": false,
  "reject_unknown_dynamic_fields": false,
  "admin_address_path": "",
  "local_address_ip_version": "v4",
  "log_level": "warning",
  "component_log_level": "misc:error",
  "log_format": "[Envoy (Epoch 0)] [%Y-%m-%d %T.%e][%t][%l][%n] %v",
  "log_path": "",
  "service_cluster": "ccb-storage-proxy.janus",
  "service_node": "sidecar~10.244.2.187~ccb-storage-proxy-5d4986d565-l7pzd.janus~janus.svc.cluster.local",
  "service_zone": "",
  "mode": "Serve",
  "max_stats": "0",
  "max_obj_name_len": "0",
  "disable_hot_restart": false,
  "enable_mutex_tracing": false,
  "restart_epoch": 0,
  "cpuset_threads": false,
  "file_flush_interval": "10s",
  "drain_time": "45s",
  "parent_shutdown_time": "60s"
 },
 "uptime_current_epoch": "350704s",
 "uptime_all_epochs": "350704s"
}
```

**How was Istio installed?**
By individual generated manifests, deployed with FluxCD.

**Environment where bug was observed (cloud vendor, OS, etc)**
Azure AKS cluster version 1.16.7, 5 nodes 32gb each.

**Comment by howardjohn** [comment]
It would be very useful to get a memory profile: https://github.com/istio/istio/wiki/Analyzing-Istio-Performance#memory-profile

Also if possible a graph of the memory usage over time might help

@lambdai assigning to you since you seem to work on these issues most but feel free to unassign if you are overloaded..

**Comment by lambdai** [comment]
@PeterGrace allocated": "69132952" << "heap_size": "11276386304", so it's not a hard leak.

Since you mentioned GRPC there are 2 KP
1. retry policy: envoy is caching the request even though GRPC is naturally not retriable. If you have a large req, or even worse, grpc streaming request, it's a nightmare if the retry is not disabled.  
2. throttling: by default envoy will cache as many as 256 MB per connection. If you have a slow app/peer envoy you will observe  envoy memory usage exploding. Use envoy filters to set the per connection buffer size to see if it helps.

If neither helps, we probably need a heap profiling to figure out what are allocated but not allocated *when the heap is growing".

**Comment by PeterGrace** [comment]
Another technician managed to work around the issue by creating an EnvoyFilter object for each workload that sets the initial stream and connection window sizes to 65kB.  With this setting, the problem appears to be resolved.  Thanks for your help.
