### ISSUE TITLE
Cannot authenticate external Postgresql server

### ISSUE THREAD

**Issue by hqms** [istio/istio#22954]
**Bug description**
My app can't connect to external postgresql server, i've tried to disable the sidecar by removing istio-injection-enabled to false, rollout the deployment, the app can connect to the server. 

The problem when the sidecar injected is only on authentication.
`psql: error: could not connect to server: FATAL:  password authentication failed for user "xxxxx"`

If I try to reach the machine whether using ping or telnet, the machine responded.

**Steps to reproduce the bug**
- enable the istio injection
- deploy a sample pod
- connect to external postgresql

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
client version: 1.5.1
control plane version: 1.5.1
data plane version: 1.5.1 (57 proxies), 1.3.5 (7 proxies), 1.0-dev (5 proxies)
```
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-gke.1", GitCommit:"aa93664bafe74f3c051e021b27a64e28ac34ab40", GitTreeState:"clean", BuildDate:"2020-03-18T22:49:35Z", GoVersion:"go1.12.17b4", Compiler:"gc", Platform:"linux/amd64"}
```
`version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}`

**How was Istio installed?**
helm template

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

**Comment by xuxant** [comment]
@hqms I faced the same issue. Can you tell me how you solved it?

**Comment by D7VK18** [comment]
Hi Team

we are adding istio to our existing cluster, we have identified our app service failed to connect with external service postgres sql db. we removed istio-injection=enabled then it working properly. 
we used telnet command to check the connectivity from the pod, it connected
error: **Dialect: postgres, error: pq: password authentication failed for user \"postgresadmin\"**
![image](https://github.com/istio/istio/assets/69137038/d61e62a0-5427-4b32-8aa5-f9588e240483)

**Comment by pankajkhatabook** [comment]
I am also facing same issue.
My service running on pod is not able to connect to AWS hosted and self hosted postgres database. getting below error:

psql: error: connection to server at "stage-platform-vault.c92u0iwsjzop.ap-south-1.rds.amazonaws.com" (172.16.74.27), port 5432 failed: FATAL:  password authentication failed for user "vault_service"

After disabling ISTIO , thing start working again.

**Comment by xuxant** [comment]
I think you need to create destination rule or service entry with mtls disabled or permissive to solve this.

**Comment by MartinKosicky** [comment]
I am using azure PostgeSQL in Cosmos and the connection string is actually a CNAME, so the istio sidecar actually sees something different. Spend whole day debuging it

**Comment by MartinKosicky** [comment]
postgresql efcore C# driver when i see wireshark it sends some garbage before tls handshake

**Comment by JustAwesomeGuy** [comment]
Hello everyone,

We had a similar problem and as this ticket appears first in the search when looking into Istio and Postgres authentication errors, i would like to share our findings on the topic:

As D7VK18 mentioned above, we have services connecting to multiple external RDS instances with ServiceEntries configured with DNS resolution. Only one of the 2 services had this error, which happened because traffic was routed to the wrong database.

Actually, this is a [documented behavior](https://istio.io/latest/docs/reference/config/networking/service-entry/#ServiceEntry-addresses) of ServiceEntries:
> If the Addresses field is empty, traffic will be identified solely based on the destination port. In such scenarios, the port on which the service is being accessed must not be shared by any other service in the mesh.

This behavior is nicely explained in [this stackoverflow post ](https://stackoverflow.com/questions/58958939/istio-serviceentry-for-multiple-external-databases-going-to-the-same-database)

In the linked post, you can see that this problem can be solved by specifying IP addresses of the external databases. That worked for us, but we didn't want to hardcode IPs in K8s environment.

We ended up using [DNS Proxying](https://istio.io/latest/docs/ops/configuration/traffic-management/dns-proxy/#external-tcp-services-without-vips) functionality, which fixed the problem without doing any changes to our ServiceEntries.
