### ISSUE TITLE
istioctl version for releases has -dirty and bogus git branch

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#2298]
It used to look like:

built from master:
```
$ ~/tmp/istio-0.2.7/bin/istioctl version
Version: 0.2.7
GitRevision: 6b145c189aad8306b13af1725123bebfbc7eefd4
GitBranch: master
User: root@f1eeb85f62ab
GolangVersion: go1.8
```

built from a branch:
```
$ ~/tmp/istio-0.2.12/bin/istioctl version
Version: 0.2.12
GitRevision: 998e0e00d375688bcb2af042fc81a60ce5264009
GitBranch: release-0.2
User: releng@0d29a2c0d15f
GolangVersion: go1.8
```

But 0.4.0:

```
$ ~/tmp/istio-0.4.0/bin/istioctl version
Version: 0.4.0
GitRevision: 24089ea97c8d244493c93b499a666ddf4010b547-dirty
GitBranch: 6401744b90b43901b2aa4a8bced33c7bd54ffc13
User: root@cc5c34bbd1ee
GolangVersion: go1.8
```

2 issues:

* shouldn't have -dirty (which means we need to remove yaml from source tree or write the new versions in a tmp dir rather than touching the source tree ones)
* GitBranch: 6401744b90b43901b2aa4a8bced33c7bd54ffc13 seems bogus

**Comment by mattdelco** [comment]
The GitBranch is from the script still expecting the 0.2 scheme where a tag is set on git and a build triggers on that tag.  The scheme doesn't work well in 0.3 and later where the tag doesn't come until later (if ever).

The dirty seems specific to Mac (and likely Windows) on 0.4.0.  The build is a moving target where people change things that affect what parts of the build get dirtied by certain scripts.  In the past I had to workaround what bazel_to_to.py and got things straightened out for 0.3.0 though something regressed in 0.4.0.  Yesterday I noticed that the addition of helm has install/updateVersion.sh update a file in-place so I wouldn't be surprised if this is what's triggering the -dirty to appear.

**Comment by mattdelco** [comment]
Currently git says the following is modified:

modified: ../broker/pkg/model/config/mock_store.go

which says it's generated from store.go.  I'll still figuring that one out but also still trying to get the build as a whole recovering again.

As for GitBranch, I'm thinking that one needs to be removed in the name of build reproducibility.  The answer from git won't necessarily remain static/constant over time (even for the same commit).  Going forwards it'll be safe to assume that in x.y.z if z is zero then it came from master, and otherwise it probably came from a branch called "release-x.y".

**Comment by ldemailly** [comment]
not sure why one would remove / change the release branch - we usually protect said branch when we create it

**Comment by ldemailly** [comment]
looks like this is fixed, thanks
