### ISSUE TITLE
istioctl: golden files need a way to regenerate

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#23042]
Please make a way to regenerate all of these config_dump test data. Its not fun to go through and manually patch all of them every time Envoy updates..

**Comment by howardjohn** [comment]
@esnible

**Comment by esnible** [comment]
Last year I investigated regenerating these files.  I couldn't figure out how to get Pilot to cough up the files.

Here is what I propose.

1. Add a test for `istioctl x authz` to the integration tests.
2. Remove the unit tests for `x describe` and `x authz`.

Will this be sufficient?  We will no longer need static test data because we will have no unit tests that use it.  The commands will still be tested during integration.

**Comment by howardjohn** [comment]
That sounds good to me. Alternatively we could possibly to a lightweight in memory pilot, then call /debug/config_dump. And have all the services mocked. There are a few pilot tests that do the same thing. Either one works for me, I am not sure if the pilot approach would be easy in practice
