### ISSUE TITLE
Support configuration of envoy filter based on istio VirtualService

### ISSUE THREAD

**Issue by cameronbraid** [istio/istio#23058]
I wish to use the envoy envoy.ext_authz filter with various unique configurations, each targeting a specific domain name.

My setup is as follows
* single ingress gateway that uses a wildcard cert *.example.com cert
* many istio VirtualService - a.example.com, b.example.com, c.example.com etc, that belong to this gateway

As far as I can tell there is no way limit a envoy filter in the ingress gateway to a virtualservice

Applying the envoy.ext_authz filter to the sidecar that the virtual service targets is not ideal as typically this service is used internally from other internal services that don't need auth, or need different auth -  applying it on the ingress gateway is the only external point of access

**Comment by rshriram** [comment]
>As far as I can tell there is no way limit a envoy filter in the ingress gateway to a virtualservice

The problem is not envoy filter in this case. the problem is the way you have your system setup. We generate an Envoy listener per Server in the Gateway object (not per virtualService). So when you have *.example.com, you get one listener doing SNI match on `*.example.com`. This listener will have N virtual hosts (a.example.com, b.example.com, etc.) matching various virtual services. All these virtual hosts are in the same HTTP Connection manager in Envoy (this is where your envoy.extAuthz filter goes). 

So to get the outcome you desire, you need to do two things: one is to inject the envoy filter for ext authz into the appropriate listener. Two, add a perFilterConfig with extAuthz wherein you can supply unique configurations for each virtual host. You can add the perFilter config to the entire virtual host or to specific routes in the virtual host like this

```
typed_per_filter_config:
  envoy.ext_authz:
    "@type": type.googleapis.com/google.protobuf.Struct
    value:
      disabled: true
```

**Comment by cameronbraid** [comment]
> the problem is the way you have your system setup

I dont understand this statement, as per the docs I have to setup my wildcard certificate like this :

`Configuring more than one gateway using the same TLS certificate will cause browsers that leverage HTTP/2 connection reuse (i.e., most browsers) to produce 404 errors when accessing a second host after a connection to another host has already been established`

see https://istio.io/docs/ops/common-problems/network-issues/#404-errors-occur-when-multiple-gateways-configured-with-same-tls-certificate

So I MUST use a single gateway - yet you say there is a problem with my setup ?

> So to get the outcome you desire, you need to do two things: one is to inject the envoy filter for ext authz into the appropriate listener

This isnt workable as it requires 

- a single auth configuration that applies to all virutal services mapped to the gateway - I want individual configurations for each virtual service
- it also requires the ext_authz filter to be enabled by default for every domain that the wildcard matches, and therefore every service that gets deployed must be aware of this and their own envoy filter to disable it.  This is not a workable solution

**Comment by abdulsalama** [comment]
Wondering what is the resolution on this? I'm also having the same exact problem as @cameronbraid. Would be really great if we can configure the ext_authz per virtual hosts.

**Comment by rshriram** [comment]
Ext authz config per virtual host in the same http connection manager is an envoy level feature. I would suggest filing the feature request in that repo.

**Comment by abdulsalama** [comment]
ok I see. @rshriram Just to make sure, you mean file the the feature request in envoy repo?
