### ISSUE TITLE
Istioctl warning when mismatch with control plane version

### ISSUE THREAD

**Issue by kramvan1** [istio/istio#23074]
**Describe the feature request**

When using istioctl against various versions of istio control plane, sometimes incorrect results will be given because of the mismatch.    Would be nice to have an upfront warning message for whenever istioctl detects a mismatch with the control plane version.

**Describe alternatives you've considered**

**Additional context**

**Comment by esnible** [comment]
I agree.  Which commands are causing you the most trouble so that we may set priorities?

Istio 1.5.x uses a newer version of Envoy and we have had trouble with `istioctl proxy-config` because of this (see https://github.com/istio/istio/issues/20714 ).  We want to fix things to be more flexible.  Agreed we should produce more warnings.

If you intend to use both Istio 1.4.x and 1.5.x what I have been doing is renaming `istioctl` to `istioctl-1.4` before installing 1.5.  This way if I need to run `istioctl proxy-config` on a cluster with Istio 1.4.x control plane I have something to fall back upon.

**Comment by kramvan1** [comment]
@esnible yup, the `proxy config` is most used.    Was also thinking that this could be something more generic that ANY sub command that calls into the cluster would provide the same warning for, just as a heads up/nagware to make sure folks know to keep the cli in sync.

**Comment by esnible** [comment]
Related: https://github.com/istio/istio/issues/18487
