### ISSUE TITLE
Consider disabling auto-commit by default

### ISSUE THREAD

**Issue by nmittler** [istio/istio#2308]
Using this issue as a forum for discussion.

IMHO there are a couple of points of concern WRT auto commit by default:

Test All the Things! (Again)
------------------------------------
Once approval has been granted, the bots kick off a full retest. If the tests all passed previously from the last commit, this seems unnecessary and time consuming. Github's merge will handle merge conflicts for us ... as long as  merge works, that should be sufficient.

Too Soon?
-------------
As we all know, there are a lot of cooks in the kitchen (at the time of this writing, there are 36 open PRs). Because we're still pre-1.0, many things are still in flux and as a result, many PRs touch multiple components. To deal with large changes, PR authors often coordinate commit order (e.g. PR 1 should go in before PR 2). If PR 2 doesn't disable auto-commit manually, it could accidentally slip in first.  Switching to manual commit by default would resolve the general problem of PRs getting in before the author is ready to commit.

I'm sure there are other reasons for switching to manual commit by default, but these are the ones that immediately spring to mind.

**Comment by geeknoid** [comment]
@rshriram

**Comment by yutongz** [comment]
> Once approval has been granted, the bots kick off a full retest. If the tests all passed previously from the last commit, this seems unnecessary and time consuming. Github's merge will handle merge conflicts for us ... as long as merge works, that should be sufficient.
you should test against latest master, which is what's going on, tide is marginally more efficient
> As we all know, there are a lot of cooks in the kitchen (at the time of this writing, there are 36 open PRs). Because we're still pre-1.0, many things are still in flux and as a result, many PRs touch multiple components. To deal with large changes, PR authors often coordinate commit order (e.g. PR 1 should go in before PR 2). If PR 2 doesn't disable auto-merge manually, it could accidentally slip in first. Switching to manual merge by default would resolve the general problem of PRs getting in before the author is ready to merge.
/hold covers this
you can /hold a PR and then /hold cancel when you're ready, but it will still make sure tests are ready before merge
if you have dependent commits you should DEFINITELY actually test the dependent PR again after the first PR is merged
.. that way you can make sure they actually work together
> Github's merge will handle merge conflicts for us ... as long as merge works, that should be sufficient.
it often isn't
sure the code merged cleanly, but that doesn't mean it behaves properly. that's the whole point of testing PRs
if you're going to trust "clean merge and tested at some point in time" == green then you should just skip testing to begin with because you're not actually gating on green tests anyhow
if you don't want a PR to merge add [WIP] in the title or put a `/hold` comment (with the prow hold plugin enabled) and just have tide block on do-not-merge labels
that's not a suitable reason to get rid of the merge robot

**Comment by yutongz** [comment]
For more information: 
http://prow.k8s.io/plugin-help.html
https://github.com/istio/test-infra/tree/master/mungegithub#do-not-merge-1

**Comment by yutongz** [comment]
To sum up:
- you do want to retest against latest commit pairs before merge ideally
- tide is smarter about this
- you can hold a PR using a label, and prow has a command to apply / remove this label
- which tide / submit-queue can be made to block on

**Comment by yutongz** [comment]
The key point of auto-merge is to save people's time from "manually update branch with master" and run tests again since there is a chance when you rerun the tests, some other commits may merged into master and you need to do the process all over again.

**Comment by yutongz** [comment]
We sent out survey in Sept to all istio-developers (not just google), and here is the responses about auto-merge system.

<img width="802" alt="wx20171221-120335 2x" src="https://user-images.githubusercontent.com/25786429/34272903-036b81b2-e647-11e7-8aad-34e211fc0ccf.png">
<img width="827" alt="wx20171221-120347 2x" src="https://user-images.githubusercontent.com/25786429/34272907-0686229e-e647-11e7-8948-9179a0d90a61.png">

**Comment by nmittler** [comment]
yutongz@ TBH, re-running the tests isn't as big of a deal for me. Nothing is perfect, however, and I'd argue that even with re-running all the tests you're still not completely safe from other commits creeping in. Manually clicking the `merge` button only differs in that the time since the last test execution (and therefore the number of possible commits since then) may be greater. Many reasonably large open source projects live with this and do fine.

More to the root of my concern ... I'd be happy if our default behavior was `/hold` and that `/hold cancel` be a manual action taken by someone to actually commit the PR.  As it stands now, someone doing `/approve`might trigger the merge without the PR author having a chance to weigh in.  Basically, I just want committing to be an active (rather than a passive) action.

**Comment by nmittler** [comment]
@yutongz also it is worth nothing that your survey in Sept involved 9 people total.  We currently have over 100 contributors.  I suspect your results would be different if taken today.

**Comment by ldemailly** [comment]
The bot is needed with mono repo so PRs can scale and be fire and forget once accepted and we don't need people to keep rebasing manually to get their PR in.
I don't think it's valuable use of human's time of people to manually merge PRs when a bot can do it properly/better.
Let's improve the bot/make it smarter as needed rather than drop it.

**Comment by jmuk** [comment]
Looks like the point of discussion is *who triggers the merge* rather than *manual vs auto merging*.

I hate manual merging, in a sense, I want enforcement of checking, since human makes mistakes. In other words, this simply means merge should be disabled if some test (or some checking) fails. But when all tests are green, and lgtm and approval are given, should it be automatically merged, or is it up to the PR author?

I honestly don't care, and I'm personally happy with current auto merging, but I understand that sometimes PR author wants to control the timing. That is also common among Google's internal tools or some other public code reviews (gerrit / rietveld) IIRC.

**Comment by andraxylia** [comment]
Auto merging was one of the requirements for the mono repo, otherwise there will be a need to constantly rebase.

**Comment by nmittler** [comment]
@andraxylia

> Auto merging was one of the requirements for the mono repo, otherwise there will be a need to constantly rebase.

Again, (as @jmuk pointed out) this discussion is not about whether the author has to manually rebase ... it's about whether the PR is automatically submitted or not.

**Comment by nmittler** [comment]
All, semantics seem to have caused some issue here.  I've reworded the PR to replace "merge" with "commit" in the hopes of clarifying that I'm not talking about manually rebasing, etc.

**Comment by douglas-reid** [comment]
Does the retest do it from a clean cache-free state?

I certainly hope so -- I've seen several examples of unexpected results from stale cached state in PR pre-submits (most recently: copying outdated, no longer generated files from bazel-genfiles over top of updated files in the current PR). That alone would be worth re-testing for me (once everything is good to go).

Auto-merging and auto-submission generally seem useful to me. There are very few times that I haven't wanted a PR in once I've received an `/lgtm`. If I could add `/hold` in the PR description itself (can I do this today? i've never tried), that'd be gravy to me (similar to having a gate around seeing "DO NOT SUBMIT" in the description). I've never quite adjusted to using github labels when creating PRs (and I don't think I'm alone here).

That being said, if it defaulted to `/hold` or `/do-not-merge` and I had to explicitly opt-in to auto-submission for PRs (maybe through a `- [x] EnableAutoSubmit` or `/autosubmit` line in the PR description), I'd be fine with that approach too. Just *please* don't make me constantly rebase manually.

The one thing we don't really have in Github is some coherent way of marking comments as "resolved", which I think would generally be a nice gate for PR submission (auto or otherwise). But that's a story for another time.

In addition to surveying developers, it might be revealing to track how many PRs are created with `/hold`s over a quarter and see if there is a more preferred default behavior. I imagine that there'd be other considerations, but it'd be nice to know what the actual behavior is, as well as to point to tangible issues caused by our default behavior (are there any auto-submit postmortems, if you will, for past failings?).

**Comment by nmittler** [comment]
> Does the retest do it from a clean cache-free state?

Good question ... @yutongz do you know the answer?

> Just please don't make me constantly rebase manually.

Yeah, I don't think anybody wants that :).  FYI Github does support the following merge types:

- **Merge:** Add all commits from the head branch to the base branch with a merge commit.
- **Squash and Merge:**  Combine all commits from the head branch into a single commit in the base branch.
- **Rebase and Merge:**  Add all commits from the head branch onto the base branch individually.

It would be good to know what our bots are doing here.  Are they squashing and merging? Squashing, rebasing, and merging? Just curious if they're doing something for us that we can't get from plain vanilla Github.

@yutongz any thoughts here?

> The one thing we don't really have in Github is some coherent way of marking comments as "resolved", which I think would generally be a nice gate for PR submission (auto or otherwise). But that's a story for another time.

Agreed - that would be nice. Seems like a missing GitHub feature in general, really.  Maybe worth having someone from dev infra look into this, if they haven't already?

> In addition to surveying developers, it might be revealing to track how many PRs are created with /holds over a quarter and see if there is a more preferred default behavior.

I'm not sure that such metrics would be all that useful, since they will rely on developers to:

1.  remember what the command is (is it `/hold`?), and ...
2.  remember to add `/hold` to every PR that they wish to manually submit.

My reason for this issue, ultimately, is that requiring developers to remember something like this is inherently doomed to failure, because we'll all forget and it will eventually lead to issues as the project continues to grow. Auto submission within Google is not something we enable by default, and I suspect for good reason.  I'm merely suggesting that we follow suit.

**Comment by yutongz** [comment]
> Does the retest do it from a clean cache-free state?

No

> Just please don't make me constantly rebase manually.

It's not about the final "merge method" (we always use "Squash and Merge" in istio). It's about update branch with latest master: 

> Idealy, you don't need to update branch (also called rebase/merge from master) before running tests because prow will merge your branch into master locally and run tests against this code. You will not see any changes happens on your branch but you can find some clue when you go to prow log. 

From https://github.com/istio/test-infra/tree/master/mungegithub#stage-two

@nmittler  I believe your issue is mainly a behavior preference. Some people like default merging and others don't. And different kind of contributors(core like google/IBM/Cisco or other random external contributors) will have different opinions. 

TBH I **don't** care about which one we are using. Either way, some part of people need to be educated and required to do a tiny extra step. Yes, you are right, google 3 don't auto-merge by default and yes you are right, we are open source not google 3. So as long as we make a decision and educate people to do the right thing, I think we are good to keep going.

**Comment by nmittler** [comment]
> Either way, some part of people need to be educated and required to do a tiny extra step

@yutongz good point.  I think the problem (at least for me) has been lack of documentation for the PR workflow and all of the machinery that we've built in (e.g. prow). Let me take an action to add some docs in that regard.

For now I think we can close this issue.  Thanks for the discussion.

**Comment by nmittler** [comment]
Re-opening for experimentation with concurrent merge.

**Comment by nmittler** [comment]
Given the new CI proposal by @hklai and the testing team, I think we can close this.
