### ISSUE TITLE
consider adding "let's encrypt" support to auto provision FQDN cert for external traffic

### ISSUE THREAD

**Issue by AceHack** [istio/istio#2310]
Would love the same support as kube-lego and nginx

**Comment by AceHack** [comment]
From the old repo:

we may consider supporting "let's encrypt" to auto provision FQDN cert to support end user traffic, or peer service that doesn't run istio proxy and doesn't support spiffe.

**Comment by ldemailly** [comment]
depends on https://github.com/envoyproxy/envoy/issues/96

**Comment by costinm** [comment]
I have a partial patch for kube-lego to use istio ingess, but have been a
bit busy. If anyone has free cycles let me know, happy to share :-)

**Comment by ldemailly** [comment]
we could also add
https://godoc.org/golang.org/x/crypto/acme/autocert
to the ingress agent ?

I need something like that and been hitting issue after issue

**Comment by munnerz** [comment]
As just commented over on the corresponding issue in the cert-manager repo (https://github.com/jetstack/cert-manager/issues/231) - I'm fairly certain we should already be compatible with the istio ingress controller.

Take a look here: https://github.com/jetstack/cert-manager/tree/master/docs to get an idea of how to run cert-manager.

You can either create Certificate resources for your ingresses for more advanced configuration, or use the `certmanager.k8s.io/cluster-issuer` or `kubernetes.io/tls-acme: "true"` annotations on Ingress resources in order to fully automate issuance of simple ACME certs.

Let me know if you run into any issues with all this. The ingress annotation support isn't well documented at the moment, but you can see a full list of options in the code here: https://github.com/jetstack/cert-manager/blob/master/cmd/ingress-shim/controller/sync.go#L16

**Comment by ldemailly** [comment]
> from https://github.com/jetstack/cert-manager/issues/231  : 

I got it to work, here is an example and I will write it up further too:
https://github.com/istio/admin-sites/pull/32/files
but it was a bit difficult (mostly because of how to make the http01 challenge pod reachable from the ingress - with/despite istio auth - feedback most welcome if there is a simpler way)

**Comment by voor** [comment]
It *is* tagged help wanted!

**Comment by Bessonov** [comment]
It's `community/help wanted`, not `help wanted`.

**Comment by Bessonov** [comment]
Activity!

**Comment by howardjohn** [comment]
https://istio.io/docs/tasks/traffic-management/ingress/ingress-certmgr/
