### ISSUE TITLE
Discovery Process reporting Pod Not Found - causing endpoints to be out of date

### ISSUE THREAD

**Issue by crhuber** [istio/istio#23118]
**Bug description**
Occasionally during a large deployment Istio Pilot will start reporting the following message hundreds of times until restarted.

>2020-04-21T11:14:21.227902Z	warn	failed to get pod platform/abc-5674bc9fb7-mxpzt from kube-apiserver: pods "abc-5674bc9fb7-mxpzt" not found

This causes all the endpoints on some sidecars to be out of date and client sidecars start sending traffic to the wrong endpoint IP addresses. The only way to resolve is to restart the Pilots and then the error message goes away and discovery happens as normal. 

istioctl proxy-status shows all sidecars as being in sync. 

During this time i also see a long spike of endpoints without ip until i restart pilot

![image](https://user-images.githubusercontent.com/5857391/79878477-be373b80-83ed-11ea-955e-ddfffcb839b1.png)
(time shown in GMT+2)

**Expected behavior**
Discovery process happens as normal and endpoints are not out of date

**Steps to reproduce the bug**

Run a large deployment of dozens of pods 

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

client version: 1.4.4
control plane version: 1.4.7
data plane version: 1.4.7 (1254 proxies), 1.4.3 (230 proxies), 1.4.0 (85 proxies)

**How was Istio installed?**
helm

**Environment where bug was observed (cloud vendor, OS, etc)**
Amazon EKS

**Comment by howardjohn** [comment]
when it logs `pods "abc-5674bc9fb7-mxpzt" not found` is it correct that the pod does not exist? Or is it trying to query a pod that does not exist?
Seems related to https://github.com/istio/istio/issues/20676 maybe but that is fixed in 1.4.7

**Comment by howardjohn** [comment]
This logs when:

* An endpoint is changed
* The IP in that endpoint does not have an associated pod in pilot's internal cache
* We directly query k8s for the pod, and it does not exist

So seems like two possibilities:
1. Your kubernetes cluster somehow has stale endpoints, so the pod is removed but the ip address is still referenced in the Endpoint
2. Pilot is somehow reading stale endpoints, but they are correct in Kubernetes. Based on pilot restart fixing things it may be this - although I am not quite sure how this would happen.

Not sure if its possible for you to look back at the endpoints to see if they were correct?

Looking into this a bit more, thats my initial thoughts though

**Comment by howardjohn** [comment]
> client sidecars start sending traffic to the wrong endpoint IP addresses

What is "wrong" in this case? I would guess that these endpoints without pods are just excluded from the list of endpoints

**Comment by crhuber** [comment]
> > client sidecars start sending traffic to the wrong endpoint IP addresses
> 
> 
> 
> What is "wrong" in this case? I would guess that these endpoints without pods are just excluded from the list of endpoints

For example: when I look on our istio-gateways and run 
`istioctl proxy-config endpoints servicename` I see some of the ip addresses it lists out are incorrect / out of date. So when traffic comes into the gateway it returns a 5xx since it cannot reach that up. However, we have multiple gateways and only some of them had wrong endpoints while others were correct.

**Comment by suchita-jain** [comment]
I am curious how you got the "endpoints with no pods" metric?

**Comment by kornholi** [comment]
We encountered this a couple days ago on GKE with Istio 1.4.9. Restarting Pilot fixed the issue at the time and we haven't seen it since.

> What is "wrong" in this case? I would guess that these endpoints without pods are just excluded from the list of endpoints

We saw traffic for one service end up at a completely different unrelated service, bypassing its VirtualService configuration. Scary from a security perspective. I assume the pod IPs were recycled while Pilot was stuck in a loop for about an hour.

**Comment by kornholi** [comment]
Saw this again a couple times in the last few weeks. Restarting Pilot always immediately fixes the issue.

At least in one case, memory usage increased continuously for a pilot stuck in the "failed to get pod" state: 

![chrome_2020-06-22_17-37-58](https://user-images.githubusercontent.com/659440/85345228-30400580-b4af-11ea-9b7e-9bddea734d3b.png)

The first "failed to get pod" message showed up at 9:58 AM and continued until 3:45 PM when the Pilot pod was restarted.

I decided to look at the logs for one of the application pods, and ended up with more questions than answers:

Application pod: skm2b
Pilot pods: s65wm (health), lnjvs (healthy), xmkzr (problem child)

- 2020-06-09 11:24:33.173 - Application pod skm2b is deleted by replicaset controller
- 2020-06-09 11:24:33.178 - Endpoint update that still contains skm2b
- 2020-06-09 11:24:33.189 - Endpoint update that still contains skm2b failed due to a conflict
- 2020-06-09 11:24:33.199 - Endpoint update without skm2b
- 2020-06-09 11:24:40.032 - Pod skm2b is deleted by the node
- 2020-06-09 11:24:40.034 - istio-pilot-s65wm info Handling event delete for pod foo-skm2b in namespace foo -> 10.24.86.30
- 2020-06-09 11:24:40.035 - istio-pilot-lnjvs info Handling event delete for pod foo-skm2b in namespace foo -> 10.24.86.30
- 2020-06-09 12:46:37.169 - istio-pilot-xmkzr info Handling event update for pod foo-skm2b in namespace foo -> 10.24.86.30
- 2020-06-09 12:48:08.970 - istio-pilot-xmkzr info Handling event update for pod foo-skm2b in namespace foo -> 10.24.86.30
- 2020-06-09 12:48:08.970 - istio-pilot-xmkzr info Handling event update for pod foo-skm2b in namespace foo -> 10.24.86.30
- 2020-06-09 12:48:32.568 - istio-pilot-xmkzr info Handling event update for pod foo-skm2b in namespace foo -> 10.24.86.30
- 2020-06-09 12:48:38.569 - istio-pilot-xmkzr warn failed to get pod foo/foo-skm2b from kube-apiserver: pods "foo-skm2b" not found
- 2020-06-09 12:48:38.569 - istio-pilot-xmkzr error Endpoint without pod 10.24.86.30 foo.foo
- ... couple hundred identical messages about skm2b ...
- 2020-06-09 14:37:06.369 - istio-pilot-xmkzr warn failed to get pod foo/foo-skm2b from kube-apiserver: pods "foo-skm2b" not found
- 2020-06-09 14:37:06.369 - istio-pilot-xmkzr error Endpoint without pod 10.24.86.30 foo.foo

Notice the ~80min gap for pilot xmkzr to process events for skm2b, and they're not even the deletions! I glanced through xmkzr logs but did not find any clues as to why it would be delayed so much.

We'll try the 1.4.4 pilot and see if the problem goes away.

**Comment by crhuber** [comment]
@kornholi We updated to Istio 1.5.4 and still occasionally see this issue

**Comment by howardjohn** [comment]
I am nearly certain this is fixed by https://github.com/istio/istio/issues/25112. Lets move the conversation there, in particular if the fixed provided there does not solve this. Thanks!
