### ISSUE TITLE
Allow bundled Prometheus to mount volumes or otherwise populate Prometheus rules

### ISSUE THREAD

**Issue by AlexDHoffer** [istio/istio#23123]
**Describe the feature request**

In line with the best practices described [here](https://istio.io/docs/ops/best-practices/observability/), for at least 1.5.x you should be invoking the bundled Prometheus and federating it for production-grade observability.

Problem is, the recording rules outlined on that page cannot be configured via the Operator. You have to add them ad-hoc to the Prometheus deployment, which is painful to do each time. Also, the service monitor example on that page has scrape configs that only work with the recording rules enabled.

It would be preferable to either (a) open up the Prometheus config in the Operator to allow for rules or (b) to just include the recording rules in with the deployment as-is.

**Describe alternatives you've considered**

Manual process:

After the Prometheus deployment finishes, mount a configmap as a volume that contains these recording rules. Then, point prometheus.yml in the deployment to this file. Finally, add a service monitor that uses the suggested scrape configs to get this data out of the federated Prometheus and into the Prometheus Operator.

**Comment by bcochofel** [comment]
Hi @AlexDHoffer , what I did to solve this issue was to remove prometheus from istio deployment and create a new one, only for scrapping metrics from istio, using prometheus operator. This new prometheus server has also servicemonitor to scrape istio, and prometheusrule with those recording rules.
My main prometheus server has the servicemonitor for the federation part.

For now, everything seens to be working fine.

Thanks,
Bruno

**Comment by douglas-reid** [comment]
I think this can be closed now. The operator stuff has been moved to `samples` and can be configured as needed, which I think matches option (a). Please reopen if you feel differently.
