### ISSUE TITLE
uninstall does not remove istio-system namespace

### ISSUE THREAD

**Issue by jwendell** [istio/istio#23189]
Since `istio-system` namespace was created by the installer (`istioctl manifest apply`) I'm expecting that following the instructions for uninstalling (`kubectl delete -f <manifest-generated-file>`) would also remove that namespace.

I also see some stuff in that namespace that were also not removed. For instance:
```sh
$ kubectl -n istio-system get cm
NAME                                   DATA   AGE
istio-ca-root-cert                     1      70m
istio-leader                           0      70m
istio-namespace-controller-election    0      70m
istio-security                         1      70m
istio-validation-controller-election   0      70m

```

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by ericvn** [comment]
Agree that this is a change in behavior from earlier releases.

**Comment by howardjohn** [comment]
This is working as intended, deleting something we don't fully own is not safe - other things may be in istio-system. we may just want to add an optional delete ns step

**Comment by jwendell** [comment]
That's the point: istio owns istio-system. I didn't create that namespace, istio did.
Anyway, if you feel that's too dangerous to remove it, I'm fine with adding this step in the docs.

**Comment by howardjohn** [comment]
We only create istio-system because people complain about needing a 1 step install. managing the namespace is an anti-pattern (as determined by tools that think about this stuff a lot more than us like helm, and my own personal opinion) - if it exists already istio will **not** manage it. We just create it one time if it doesn't exist and never touch it again.

The docs should probably ask users to create the ns themselves as well to promote best practices

**Comment by jwendell** [comment]
SGTM
