### ISSUE TITLE
'istioctl upgrade' (or install) --profile-from-cluster

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#23443]
When installing a new revision it is easy to forget to add all the `--set` options that were provided with the initial install. The result is that the new revision is different code and different config from the one in cluster.

`--profile-from-cluster` let you use the profile that was previously active and then add your modifications on top.

Alternative
Discourage users from use `--set` options and always ask them to create a new profile.

**Comment by mandarjog** [comment]
@ostromart @richardwxn

**Comment by howardjohn** [comment]
This is implemented in https://github.com/istio/istio/pull/23377

**Comment by esnible** [comment]
I propose we target 1.7 for `--profile-from-cluster`.  I want to make sure it is tested instead of putting it in at the last minute.

For 1.6, once https://github.com/istio/istio/pull/23458 merges it will be possible to do `istioctl manifest apply -f <(kubectl -n istio-system get istiooperator installed-state -o yaml)` to get this behavior.  `--force` may be necessary during an upgrade because of our policy of removing alpha-level fields (see https://github.com/istio/istio/issues/23376 for details).

**Comment by esnible** [comment]
Would it also be reasonable to have "istioctl manifest settings [--profile <profile>]" that would diff an in-cluster IstioOperator with the baked-in one, returning the differences not in diff format as `--set` values to be passed to a "manifest apply"?

Users forget which settings they chose and need something to remind them.

Related: https://github.com/istio/istio/issues/22198

**Comment by mandarjog** [comment]
Yes, I think it is useful. From a UX standpoint,  `--set` commands have an appearance of applying changes. The actual behaviour is consistent with KRN model where you only specify the final desired state.  If we believe that `--profile-from-cluster` is useful, only a user who is aware of the problem and the option will make use of it. Which means that users *can still inadvertently* replace configuration. 

If our goal is to fix that, then we should require the user specify `--use-profile-from-mesh=true|false`.  The use is then forced to make a decision. This will be a breaking change, so we need to deal with that.
@ostromart ?

**Comment by richardwxn** [comment]
I agree with what Mandar said, and we should leave it as option so user can choose if they understand what they are going to apply

**Comment by esnible** [comment]
I closed my initial PR.  Concerns were raised at the UX meeting.

If was felt that instead of a new flag to use the cluster's `installed-state` IOP instead of the the one baked into _istioctl_ what the user wanted was what _helm_ does.

- What does helm do? Helm may tell the diff.

It was felt several warnings are needed
- If the user tries to install, and they have two control planes (in the middle a control plane canary, perhaps), there should be a warning if `--revision` is not specified.
- The user should be told what settings their use of `--apply-mesh-settings` (or whatever this flag is called) are different from the built-in settings.

I have a new RFC for showing the user how they installed, I am considering delaying this Issue to 1.9 in favor of https://github.com/istio/istio/issues/23892

**Comment by esnible** [comment]
Clearing milestone because no one seems to be willing to accept this.

@ostromart , what do you think of just showing the user what the settings were rather than letting them upgrade, as I propose in https://github.com/istio/istio/pull/27737 ?

**Comment by esnible** [comment]
If desired, open a new issue for this enhancement.
