### ISSUE TITLE
Remove "istioctl proxy-status --sds"

### ISSUE THREAD

**Issue by esnible** [istio/istio#23501]
`istioctl ps <pod> --sds` no longer works.  It always outputs `failed to retrieve node agent secrets: could not find Node Agent for supplied pod <pod>`.

This is because there is no longer a node agent
https://istio.io/news/releases/1.5.x/announcing-1.5/upgrade-notes/#sds-node-agent

It is unclear if we should remove the `--sds` and `--sds-json` options from `proxy-status`, or replace the logic with something new.

cc @Monkeyanator

**Comment by Monkeyanator** [comment]
The purpose of the `--sds` and `--sds-json` flags was to diff secrets between the `nodeagent` and the Pod's sidecar, and since there's no longer a `nodeagent`, I can't see a reason to keep them. The commands were also very tightly coupled with [this debug endpoint](https://github.com/istio/istio/pull/15418) which I believe is now gone.

That being said, I've been back in school since before the `istiod` consolidation so I'm not familiar enough with the new architecture to say whether there needs to be a replacement. From what I've read we could still check for secret synchronization between the `istio-agent` and the sidecar but I'm not sure, might make sense to loop somebody in that was involved in the migration @JimmyCYJ
