### ISSUE TITLE
dns certificate support: stop creating Secrets

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#23582]
Now that we have Istiod, we have no need to persist DNS certificates to Secrets. This is outside the scope of Istio, and should be handled by systems like cert-manager. 

This issue involves removing this feature, and removing the associated doc: https://istio.io/docs/tasks/security/dns-cert/ and tests: TestDNSCertificate

cc @costinm @lei-tang

**Comment by howardjohn** [comment]
related https://github.com/istio/api/pull/1414

**Comment by costinm** [comment]
For 1.6 or 1.7 ? 

I agree we should stop creating Secrets - but customizing DNS certs - at least for control plane - is still a needed feature. 

@linsun  @nrjpoddar

**Comment by costinm** [comment]
And I would include here a proper mesh config-based API for Lin's change - right now it's an env variable, but the agreement was that most configs should go into mesh config.

**Comment by nrjpoddar** [comment]
I don't think we can just stop creating DNS certs.

There are users who want a single signing authority in their systems. When Istio is installed, since Citadel issues mesh related mTLS certs they also want CItadel to sign DNS certs for legacy & Pods which don't have sidecars.

We cannot take away this feature, I'm ok if you want to replace the config and make it better but removing the feature will cause disruption.

**Comment by howardjohn** [comment]
@nrjpoddar I don't think this feature was ever meant for external users - just for webhooks. Looking at the doc somehow it seems like it became user facing, which is a huge mistake in my opinion. I am not sure why we would want to replace cert-manager - they do a much better job.

**Comment by nrjpoddar** [comment]
This is not replacing cert-manager which is primarily for end-user facing certs.

So basically, users want to mTLS or TLS for workloads in their cluster with legacy applications. They want a single entity to issue certs for that use case. Whether accidentally (or intentionally) users are relying on this behavior now.

We should stop documenting features that are not user facing, but follow good deprecation practices with migration support if we do documenting it.

**Comment by costinm** [comment]
If they implement https://github.com/jetstack/cert-manager/issues/2894 - I would agree 
users will be better to use CertManager. 

This feature gives mesh admin control over the certificate - something not possible today 
with CertManager.

**Comment by costinm** [comment]
I don't know what 'user facing' mean - all MeshConfig is 'mesh admin' facing. 
App developers can't and shouldn't edit mesh config - so any doc that is based on MeshConfig
is not really 'user facing'. 

The intent of the API was to allow the mesh admin to have a consistent way to control the
issuance of DNS-based certificates - instead of having N env variables and custom ways to do it.
Lin's central cluster is a perfect example. 

There are other use case for Istio to issue DNS certs - and right now there is no good alternative, 
so I think the mesh config is still needed.

**Comment by costinm** [comment]
Thinking about this more - I think if we fix the Secret naming so CertManager can be used 'out of box' - we can deprecate this. Even if CertManager doesn't add the extra controls - running a namespaced Issuer is equivalent with that this feature does - but using a user-visible API that users are already familiar with and we support ( for ACME ).

So +1 to deprecate/remove from Istiod, but we need code to update the saved the private key.
