### ISSUE TITLE
When istio ingress TLS is enabled, HTTP 404's

### ISSUE THREAD

**Issue by Stono** [istio/istio#2361]
Hi, 
Adding an ingress without TLS, http:// = 200
If I then add TLS to that ingress, the https:// = 200, however http:// = 404.

This is on istio v0.4.0

**Comment by ankurcha** [comment]
Just noticed this too :-/ Any workarounds?

**Comment by ZackButcher** [comment]
I'll take a look at this tomorrow.

**Comment by ldemailly** [comment]
I have a fix/workaround for it in #2310

**Comment by ldemailly** [comment]
repeating from the mailing list:

While it's counter intuitive (if only because of #2573) the solution is actually simple:

copy your ingress section and repeat it without "tls:" section

you can see an example here: https://github.com/istio/admin-sites/pull/32/files#diff-fc47a9580959f741b273792bda3dde36

Please confirm that solves your issue and we can close it
(will document better as part of https://github.com/istio/istio.github.io/issues/868 )
