### ISSUE TITLE
Istio could supports multiple data planes?  such as MOSN

### ISSUE THREAD

**Issue by wangfakang** [istio/istio#23753]
hello  all  @howardjohn @rshriram @seflerZ @hzxuzhonghu @linsun 

Thank's Istio members for their great work on Istio, In the field of Service Mesh, Istio has become a standard control plane. So, [MOSN Istio WG](https://github.com/mosn/community/blob/master/wg-istio.md) also hopes that MOSN can be one of the standard data planes in the Istio. Currently, MOSN supports xDS, And tested pass all the sample of bookinfo in `istio-1.5.2` .

MOSN with Istio 
====
we could study `Request Routing`, `Traffic Shifting`, `Fault Injection`, `Request Timeouts` via [MOSN with Istio](https://www.katacoda.com/mosn/courses/istio/mosn-with-istio) tutorial.

MOSN Introduction
=======
MOSN is a network proxy written in Golang. It can be used as a cloud-native network data plane, providing services with the following proxy functions: multi-protocol, modular, intelligent, and secure.
MOSN can be integrated with any Service Mesh which support xDS API. It can also be used as an independent Layer 4 or Layer 7 load balancer, API Gateway, cloud-native Ingress, etc.

Github: https://github.com/mosn/mosn
Website: https://mosn.io

**Comment by nejisama** [comment]
+1

**Comment by rootsongjc** [comment]
And MOSN can go though the bookinfo sample now. It needs to work more deeply with the Istio community.

**Comment by CodingSinger** [comment]
+1, I think we need more sidecar options.

**Comment by cuber** [comment]
+1

**Comment by johnlanni** [comment]
+1

**Comment by kevin21th** [comment]
I think providing more sidecar options is good for istio users

**Comment by seflerZ** [comment]
Istio is designed to be free all to data planes. However the current code is coupled with Envoy(especially the Envoy go-control-plane packages). That's why it's hard to move from xDS v2 to v3. If you want to support multiple data planes now. There should be a refactoring coming first and I strongly suggest to have this issue discussed in network meetings.

**Comment by lidaohang** [comment]
+1  I think we need more sidecar options，such as MOSN.

**Comment by howardjohn** [comment]
if MOSN fully implements XDS what special istio support is needed?

**Comment by lic17** [comment]
+1 I think we need more sidecar options，such as MOSN.

**Comment by champly** [comment]
> if MOSN fully implements XDS what special istio support is needed?

i think first should let pilot dynamic inject sidecar，such as 
- [pilot-agent ](https://github.com/istio/istio/blob/c48c0b20f1b10c77f0af08ab8cc3fb6ec7caf8bf/pilot/cmd/pilot-agent/config.go#L165)  use annotation set binaryPath

**Comment by wangfakang** [comment]
> if MOSN fully implements XDS what special istio support is needed?

Thank you very much for your reply, we hope to achieve the following two points.

First `proxyv2` image contains the binary of `envoy` and `mosn`, and we colud choose one as the sidecar via the istioctl parameter `--set meshConfig.defaultConfig.binaryPath=/user/local/bin/envoy` or `--set meshConfig.defaultConfig.binaryPath=/user/local/bin/mosn` .

Second Is it possible to recommend `MOSN` as a data plane choice in Istio's README document.

**Comment by xhhoho** [comment]
+1, I think we need more sidecar options

**Comment by john-deng** [comment]
+1， add an option to sidecar that implemented in Go will bring a lots of benefit to the community, it easier to debug, easier to understand, extend the community participants, of cause without performance compromise.

**Comment by dgn** [comment]
This is really cool. Will definitely try out mosn at some point.

> First `proxyv2` image could contains the binary of `envoy` and `mosn`, and user colud choose one as the sidecar via the istioctl parameter `--set meshConfig.defaultConfig.binaryPath=/user/local/bin/envoy` or `--set meshConfig.defaultConfig.binaryPath=/user/local/bin/mosn` . here is a [POC](https://github.com/mosn/istio/pull/8) PR.

Generally, we're moving away from including third-party components in upstream Istio in order to improve maintainability and limit our attack surface. Apart from that I don't really see why including the binary would be necessary, as the proxy container image is already configurable using `global.proxy.image`. Interested users are already able to swap out envoy with another proxy, in fact I'm aware of at least one commercial proxy with Istio/xDS support that works that way.

**Comment by wangfakang** [comment]
> This is really cool. Will definitely try out mosn at some point.
> 
> > First `proxyv2` image could contains the binary of `envoy` and `mosn`, and user colud choose one as the sidecar via the istioctl parameter `--set meshConfig.defaultConfig.binaryPath=/user/local/bin/envoy` or `--set meshConfig.defaultConfig.binaryPath=/user/local/bin/mosn` . here is a [POC](https://github.com/mosn/istio/pull/8) PR.
> 
> Generally, we're moving away from including third-party components in upstream Istio in order to improve maintainability and limit our attack surface. Apart from that I don't really see why including the binary would be necessary, as the proxy container image is already configurable using `global.proxy.image`. Interested users are already able to swap out envoy with another proxy, in fact I'm aware of at least one commercial proxy with Istio/xDS support that works that way.

Sorry, maybe I did not express clearly. The `proxyv2` image produced by `make docker.proxyv2` only contains the `pilot-agent` and `envoy` binaries, so users can only choose `envoy` as the sidecar, so they need to modify the Istio `Makefile` file  to support `proxyv2` image integrate `mosn`, just like integrating `envoy`.

**Comment by linsun** [comment]
cc @istio/steering-committee FYI I am not sure if we want to allow users to easily configure another data plane like MOSN... istio is being perceived as complicated and I'd rather not introduce a data plane variation.  Perhaps it is interesting if we could standardize a test complaint suite to allow MOSN with istio control plane being istio compliant.

**Comment by wangfakang** [comment]
> cc @istio/steering-committee FYI I am not sure if we want to allow users to easily configure another data plane like MOSN... istio is being perceived as complicated and I'd rather not introduce a data plane variation. Perhaps it is interesting if we could standardize a test complaint suite to allow MOSN with istio control plane being istio compliant.

Yeah, I think it's a good idea. In this way, list the supported data planes in the Istio‘s document, such as Envoy, MOSN. Allow users could choose the data plane according to their own scenarios.

**Comment by howardjohn** [comment]
So my understanding is the main asks here are

* Include MOSN into the proxyv2 image
* Recommend MOSN in our official docs

Neither of these are require for Istio to simply support/work with MOSN, which it does today as far as I can tell. Rather this is more about making things "official".

My 2c is that we should continue to make Istio flexible enough to support projects like MOSN, by allowing options like configuring the proxy image for example, but I don't think we are ready to officially endorse another image. MOSN can easily build another proxy image with MOSN added (and Envoy removed, if desired, to reduce the image size), and could likely be added to http://github.com/istio-ecosystem if desired.

Adding the binary to the official proxyv2 image is not a good idea in my opinion. The majority of users will likely continue to use Envoy, so we are penalizing them with a larger binary (and attack surface) for no added benefit.

In order to be on par with Envoy, we would need:
* Full testing coverage of MOSN on par with Envoy
* Similar security policies, with regards to embargos, disclosures, etc
* Familiarity with Istio maintainers of MOSN
* A group of Istio maintainers dedicated to support updates, patches, security releases, etc 

Most importantly, we would need agreement that this is worth the cost on the project. Adding a new proxy means we need to double all of our testing efforts, we need to double (if not more) the amount of security releases we need to handle, development efforts may be slowed, etc. There is a **huge** cost here - we can hardly keep up with just supporting Envoy.

MOSN is pretty cool and its great to see another proxy working with Istio, but I simply do not see how we can feasibly support this. I would love to see it progress in https://github.com/istio-ecosystem or https://github.com/mosn/mosn

**Comment by wangfakang** [comment]
@howardjohn About the problem of test cost,  as mentioned by @linsun `Perhaps it is interesting if we could standardize a test complaint suite to allow MOSN with istio control plane being istio compliant`  can be solved, that means one test cases could run any data plane.

**Comment by howardjohn** [comment]
@wangfakang even if we could just plug MOSN into the tests today, it still has a substantial cost. Each PR undergoes ~5 hours of testing (some in parallel), so if we were to double all of those there is a large cost. Additionally there is additional test failures to debug, development is slowed if a feature is available in MOSN not envoy, etc

**Comment by linsun** [comment]
I'm not proposing adding MOSN to our tests.  I think it is interesting for community to produce istio compliance test suites and each project who are interested in claiming istio compliant can submit its test result for approval for a given istio compliant level.

**Comment by yangyongzhi7** [comment]
In my opinion, we should support multiple data planes for istio uses, as far as I know, some company which want to adopt isito to implement traffic management has need to enhance data plane's function  , they are limited by language because envoy is written in C++, It is very difficult to extend some filter function by writing in Golang with Envoy, otherwise, using another plane such as MOSN to do it probably is easy.

**Comment by howardjohn** [comment]
@yangyongzhi7 Istio+Envoy supports extensibility via WASM which can be compiled from golang if that is a requirement

**Comment by rshriram** [comment]
This is really cool! How compatible is this proxy with the existing XDS implementation in envoy? If you replace the istio-proxy with mosn, how many tests pass / fail? This might be a good test of compatibility.

Even if we dont immediately have mosn as an alternative to the envoy proxy, in our distribution, you can start by creating documentation for this (assuming there is a sufficient coverage of features that people can start testing). I dont know where to fit this in our docs (whether it is a blog or a task on "experimental third party data planes" ) [ cc @frankbu ] but we can figure it out.

nit: rather than having the data plane as one separate container, why dont you compile everything into one single binary (istiod, mosn, istio-agent) such that you can deploy the same container everywhere (istiod xds, istiod proxy)?

**Comment by rshriram** [comment]
Another question, why xds? Would you be interested in directly supporting istio APIs (networking and security) and implementing the "user intents" directly in mosn without going through another translation? Put another way, if this is modular enough, then with @costinm 's work on streaming istio configs over xds to istio-agent, you could literally receive all istio configs over xds and implement the appropriate listeners/forwarders, etc.

**Comment by wangfakang** [comment]
> This is really cool! How compatible is this proxy with the existing XDS implementation in envoy? If you replace the istio-proxy with mosn, how many tests pass / fail? This might be a good test of compatibility.
> 

Yes, it's compatible with most of istio's feature and tested pass all the sample of bookinfo. Currently,  istio's test cases are hard coded with envoy, so we are following work the [optimization of istio test framework](https://github.com/istio/istio/issues/24463), so that Istio test cases can run other data plane (such as MOSN) more conveniently.
> Even if we dont immediately have mosn as an alternative to the envoy proxy, in our distribution, you can start by creating documentation for this (assuming there is a sufficient coverage of features that people can start testing). I dont know where to fit this in our docs (whether it is a blog or a task on "experimental third party data planes" ) [ cc @frankbu ] but we can figure it out.
> 

This is a good suggestion. Does the document have special specifications?

> nit: rather than having the data plane as one separate container, why dont you compile everything into one single binary (istiod, mosn, istio-agent) such that you can deploy the same container everywhere (istiod xds, istiod proxy)?

It can be compiled into a single binary. However, Iistio's `proxyv2` is used as a complete sidecar image, so the MOSN is also  packaged into the `proxyv2` image.   Here is a sample https://github.com/istio/istio/pull/25146.

**Comment by wangfakang** [comment]
> Another question, why xds? Would you be interested in directly supporting istio APIs (networking and security) and implementing the "user intents" directly in mosn without going through another translation? Put another way, if this is modular enough, then with @costinm 's work on streaming istio configs over xds to istio-agent, you could literally receive all istio configs over xds and implement the appropriate listeners/forwarders, etc.

Data plane and istio interaction via XDS (UDPA) seems to be a common way? Is there any detailed documentation on how to use isto APIs ? I can do some study.

**Comment by rshriram** [comment]
1. about tests
We have invested a lot of effort in tooling, checks, etc. around the sidecar (both in the release and tests). So if your sidecar image (which you can replace using global.proxyv2.image=..) is API wise compatible with what we have, you should be able to test the full suite of tests.. By API wise compatibility, I meant supporting all the health check endpoints that istio-agent exposes to kubectl (this is what we also use in tests), in addition to pilot-agent commands used by istioctl. 

2. With regard to the istio apis, imagine if all we had to do was stream the set of all services, virtual services, destination rules, authz polies, etc. to the sidecar. The sidecar can receive a connection, match it to a service, find the appropriate virtual service and route to the destination specified, apply rules from the dest rules before routing to the service, etc. The advantage of this model is that user intent is directly implemented by the data plane. There is no intermediate translation from user intent (in istio APIs) to intermediary (XDS apis) [much less overhead]. Worth thinking about, depending upon the goals of your project.

**Comment by wangfakang** [comment]
> 1. about tests
>    We have invested a lot of effort in tooling, checks, etc. around the sidecar (both in the release and tests). So if your sidecar image (which you can replace using global.proxyv2.image=..) is API wise compatible with what we have, you should be able to test the full suite of tests.. By API wise compatibility, I meant supporting all the health check endpoints that istio-agent exposes to kubectl (this is what we also use in tests), in addition to pilot-agent commands used by istioctl.

It looks great, MOSN has been adapted to the pilot-agent health check and startup parameters (Istio.1.5.x version).

> 2. With regard to the istio apis, imagine if all we had to do was stream the set of all services, virtual services, destination rules, authz polies, etc. to the sidecar. The sidecar can receive a connection, match it to a service, find the appropriate virtual service and route to the destination specified, apply rules from the dest rules before routing to the service, etc. The advantage of this model is that user intent is directly implemented by the data plane. There is no intermediate translation from user intent (in istio APIs) to intermediary (XDS apis) [much less overhead]. Worth thinking about, depending upon the goals of your project.

Thanks , I see.
