### ISSUE TITLE
Wasm remote load expects pilot to retry on nack

### ISSUE THREAD

**Issue by bianpengyuan** [istio/istio#23836]
Currently when a listener update that references a remote Wasm module reaches proxy, it will kick off download at background and Nack the listener update. It expects control plane to retry on Nack, so that when the module file is downloaded, it could do synchronous config validation and reject listener update if it is not valid.

However, pilot does not retry on Nack, and listener with remote Wasm modules can only be loaded after ~half hour when pilot pushes again. To accommodate Wasm remote load, pilot should retry bounded times (<= 3) on listener/cluster/route rejections.

**Comment by howardjohn** [comment]
If nacks are expected behavior it's going to cause some problems in my opinion. Many people have alarms set up (and they should) for NACKs - general Nack == something horribly broken.

If wasm is really going to nack for this can we possibly have special logic for wasm?

**Comment by bianpengyuan** [comment]
Yeah, would be better if proxy could populate [error status](https://github.com/envoyproxy/envoy/blob/8771d31f8595531bcd040bf6f42f7a8316c5fc9d/api/envoy/service/discovery/v3/discovery.proto#L63) and let pilot behave specially on Wasm fetch failure. @jplevyak @PiotrSikora @mandarjog does this make sense to you?

**Comment by mandarjog** [comment]
We have discussed at length on if we can provide metrics on this to set appropriate alarms, but we cannot be precise.
We do have directional metrics though.

Users today expect a NACK to mean marlformed configuration, and a control plane programming error, so a 4xx. 

We want to a 5xx like error, which so that control plane will retry the request. 

Lack of nack does not mean working config. The current approach is optimistic, Put listeners in warning state and eventually (and most of the time) they will go to ready. 
If they stay in warming, tough luck.

External dependencies make this warning thing more of a problem.

This was a stop gap until we have out of band and in-band solutions. I don’t think we should pursue this further.
@jplevyak @kyessenov @PiotrSikora

**Comment by bianpengyuan** [comment]
Looks like `error_details` status code is hard coded to be [INTERNAL](https://github.com/envoyproxy/envoy/blob/ed6a1b8b60a23e6bae7f08f990d1680b26b26cde/source/common/config/grpc_mux_impl.cc#L202). One possible option is to extend EnvoyException to embed a gRPC status code and throw exception on Wasm remote cache miss with a more reasonable error code (Unavailable?) and let pilot retry on that. Alternative is to rely on message in error details, which is really unreliable and not ideal.

**Comment by howardjohn** [comment]
@mandarjog are you saying the NACK was a short term solution anyways so we should just work on the longer term plan rather than add retries?

**Comment by mandarjog** [comment]
yes.

**Comment by bianpengyuan** [comment]
Then sending a dummy listener, or cluster (seems like less expensive?) to do out of band warming? This sounds great as long as we could wrap it in a user friendly API so that we can change the underlying implementation later when async xds is ready.

**Comment by mandarjog** [comment]
I am now writing a doc, but we will have to embrace warming state with all its niceties!

**Comment by douglas-reid** [comment]
I'm gonna use this existing issue as a proxy for the 1.7 work item: Deliver alpha quality remote load capability for Wasm.

**Comment by mandarjog** [comment]
https://tinyurl.com/istio-wasm-failure-modes

**Comment by bianpengyuan** [comment]
This will no longer be needed with filter config discovery service.
