### ISSUE TITLE
Cannot install Replicated Control Planes

### ISSUE THREAD

**Issue by mbanikazemi** [istio/istio#23871]
**Bug description**
I tried `istioctl manifest apply -f manifests/examples/multicluster/values-istio-multicluster-gateways.yaml` to install multiple control planes from 1.6.0-rc.0 and get the following error:

```
...
namespace/istio-system created
secret/cacerts created
Detected that your cluster does not support third party JWT authentication. Falling back to less secure first party JWT. See https://istio.io/docs/ops/best-practices/security/#configure-third-party-service-account-tokens for details.
Error: failed to apply manifests: template: :262: function "valueOrDefault" not defined
```

Using version 1.6.0-rc.0.

```
$ istioctl version
no running Istio pods in "istio-system"
1.6.0-rc.0
```

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by irisdingbj** [comment]
Got a clean VM and tried this, same error for me.

**Comment by irisdingbj** [comment]
we should not have template in this file, `        - "{{ valueOrDefault .DeploymentMeta.Namespace \"default\" }}.global"` need a fix for it

**Comment by irisdingbj** [comment]
@ericvn what the value is expected here? can we just provide a default value here to remove this error? Thanks!

**Comment by irisdingbj** [comment]
@brian-avery @jacob-delgado FYI

**Comment by sdake** [comment]
The file itself has not been touched since the operator repo merger. I don't yet have a root cause, although it appears that the transformation system in use is no longer able to parse template content in `values.yaml` files. While this may be a regression, there are a couple of easy options:
1. just document an IOP for this that doesn't include the line `        - "{{ valueOrDefault .DeploymentMeta.Namespace \"default\" }}.global"` - This avoids a rebuild
1. Rebuild the software with a PR incoming that removes this line (this is less easy on all involved. I'd encourage extreme care in the acceptance of any backports if the release managers wish to create a new beta).

See more below:
The purpose of this line is to provide DNS discovery for services in a local cluster within the global namespace. While this would be a great capability for Istio to have, it is not a capability Istio has. RDS in 1.3 was not able to support this work, and most of the work was reverted smartly by @rshriram. Unfortunately this vestige of that failed experiment remians.

I didn't add the code, but I will submit a PR that removes this line if the release managers with to rebuild the software.

Cheers,
-steve
