### ISSUE TITLE
istioctl convert-ingress references istio-autogenerated-k8s-ingress

### ISSUE THREAD

**Issue by rvennam** [istio/istio#23989]
**Bug description**
If you convert an ingress, it generates a VS with gateway set to `istio-system/istio-autogenerated-k8s-ingress`

It would make sense to just set this to the default GW resource that gets created with the install...
`istio-system/istio-ingressgateway` in Istio 1.5.2+

If in 1.6, we aren't creating a GW resource out of the box, then we should change this name to something more obvious to the user.

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by rvennam** [comment]
cc @esnible

**Comment by esnible** [comment]
Added `area/networking` because the code is in _pilot_.

The code is _pilot/pkg/config/kube/ingress/conversion.go_ and `istio-autogenerated-k8s-ingress` is a constant defined in _pkg/config/constants/constants.go_.  _Istioctl_ itself isn’t setting that name.  Pilot /pkg sets it.  It is likely that the rest of Pilot stopped calling this method but _istioctl_ is still calling it.

**Comment by howardjohn** [comment]
@esnible agree that is what happened. Pilot not internally generates both the Gateway and VirtualService

**Comment by esnible** [comment]
@rvennam Is this still needed?
