### ISSUE TITLE
Security risk: no client certificate authentication between envoy/pilot-agent and pilot GRPC

### ISSUE THREAD

**Issue by zhaohuabing** [istio/istio#24008]
**Bug description**

There is no client certificate authentication between envoy/pilot-agent and pilotd GRPC. As a result, a malicious third-party could pretend to be a valid service and send a CSR request to the pilotd CA  to get a certificate. Then this malicious attacker can use the signed certificate to access other services in the mesh.

I found this security issue by looking into the codes, so no reproduce steps.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[* ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Mutual TLS should be enforced for envoy/pilot-agent - pilotd communication.

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
We use JWT token authentication to authenticate CSRs.

In the future **please** follow the issue template and responsibly disclose: https://istio.io/about/security-vulnerabilities/

**Comment by zhaohuabing** [comment]
Sorry I didn't realize that Istio has another reporting process for security issues. Thanks for the prompt response and the pointer to the template.

**Comment by myidpt** [comment]
I think we just considered this is as a P0 security bug rather than a vulnerability. But John is right, please start with treating it as a vulnerability.

We made some good progress over the past weeks.
Istiod can pull root certs from specified SPIFFE bundle endpoints and use them to authenticate clients: https://github.com/istio/istio/pull/24669
Istiod builds a trust bundle based client X.509 cert authentication: https://github.com/istio/istio/pull/24836

**Comment by myidpt** [comment]
Adding the reasoning for context:

Since Istio 1.6, because istiod does not have a sidecar, it implements its own code to do client-side authentication. Previously, to accommodate the use cases that istiod does not have the custom root certificate, Istiod doesn't check the client credential (CA part is not impacted though). This causes unauthorized clients to retrieve the XDS information via the secure (TLS) service, and it is an issue for mesh expansion and multi-cluster where the secure XDS service is exposed to the external.

**Comment by myidpt** [comment]
Now master has the basic fix in place. Authentication (JWT or cert) is enforced on Pilot. Need to add integ tests.
TODO: authorization on Pilot, checking which identity can access which resource.
We also need to cherrypick the fixes into V1.6.

**Comment by costinm** [comment]
TODO: also allow JWT authentication to the XDS server, as we do for the certificate generation call. This will increase consistency - and support cases where mTLS is not possible. Since the JWT can be exchanged with a cert - they should be equivalent.
