### ISSUE TITLE
istioctl: improve error handling

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#24026]
Many commands in istioctl have minimal error handling, making debugging/catching regressions very hard. For example, https://github.com/istio/istio/blob/57557d71896c829de2961b4b16b33fdb3f281f7e/istioctl/cmd/describe.go#L606. This is common throughout most of the commands

**Comment by howardjohn** [comment]
This is made worse by code paths where we are explicitly using errors to filter filters: https://github.com/istio/istio/blob/57557d71896c829de2961b4b16b33fdb3f281f7e/istioctl/cmd/describe.go#L643

**Comment by esnible** [comment]
_describe.go_ is a bit of a mess because I was asked to base it on reading the Envoy config instead of the CRs.  For this reason it may never leave experimental.

It may be that _describe.go_ needs to be pulled out of the standard integration test into its own test where it can be disabled.  I realize I am the only one who can fix it.  It would be great to throw away 100% of the code here and just ask Pilot which CRs route to the pod and I can make that request as part of the refactoring for using XDS Events instead of the debugging API.

Are the pains you are having just on the integration test for describe and authz or is there a more general problem I am missing with the istioctl error handling?

**Comment by howardjohn** [comment]
The primary concern is that I am pretty sure there are certain things that are silently failing unexpectedly did to all the xds changes, but it's very hard to tell - the integration test is actually the only reason it's not 100% broken now
