### ISSUE TITLE
[1.6] istiod keep trying to list removed CRD

### ISSUE THREAD

**Issue by uncycler** [istio/istio#24035]
**Bug description**
The upgrade note suggests removing deprecated CRDs but after doing that, istiod fills error logs with : 
`Failed to list *crd.IstioRbacV1Alpha1Serviceroles: the server could not find the requested resource (get serviceroles.rbac.istio.io)`

**Expected behavior**
istiod should not log errors for unexisting deprecated CRD.

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.6.0

**How was Istio installed?**
istioctl 

**Environment where bug was observed (cloud vendor, OS, etc)**
EKS

**Comment by yangminzhu** [comment]
We only removed the CRD for 1.7. The upgrade note should be updated to not to delete the CRD for 1.6.

1.6 doesn't support the CRD but there are some left over code still trying to read the CRD that's why you see the log in istiod. Keeping them won't allow you to actually use them, but should help avoid spamming istiod logs.

**Comment by yogeek** [comment]
Hi @yangminzhu ,

I just installed istio 1.6.13 (canary aside my current istio 1.5.4) and got the same issue :

```
kubectl logs istiod-6d664b45c6-f6dh8
[...]
error    k8s.io/client-go@v0.17.2/tools/cache/reflector.go:105: Failed to list *crd.IstioAuthenticationV1Alpha1Policies: the server could not find the requested resource
```

during the rollout of the old istiod deployment

Is it normal ?
