### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by smarkm** [istio/istio#24106]
**Bug description**
Segmentation fault when execute istioclt version `1.6.0(amd64)` on `5.3.0-40-generic #32~18.04.1-Ubuntu SMP Mon Feb 3 14:05:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`, but version `1.5.4` is ok

![image](https://user-images.githubusercontent.com/5517120/82913113-7bdebc80-9fa0-11ea-8886-ad4a811836d8.png)

**Comment by howardjohn** [comment]
Can you give the exact steps you ran? I cannot reproduce on my machine. I also tried

```
docker run -it ubuntu:18.04
apt update && apt install curl
curl -L https://github.com/istio/istio/releases/download/1.6.0/istio-1.6.0-linux-amd64.tar.gz | tar xz
./istio-1.6.0/bin/istioctl
```
which did not see the same

Long ago we saw a similar issue with this vague "Segmentation fault" message. It turned out we were running `sed` on the binary and mangling it. Is it possible you did something like that? Or its possible we are you are getting the binary from somewhere different than I am maybe

**Comment by smarkm** [comment]
Thank you @howardjohn , I got it my download is not complete
