### ISSUE TITLE
pilot: grpc stream closures result in unwatched / lost ClusterLoadAssignments in Envoy; early readiness may result in incorrect configuration

### ISSUE THREAD

**Issue by nicktrav** [istio/istio#24117]
**Bug description**

Following a closed gRPC stream to Pilot, Envoy sidecars end up in state where they have no ClusterLoadAssignments. This results in requests falling back to non-Istio (or ClusterIP-based) routing.

**Expected behavior**

When a connection to pilot is closed, the sidecar proxy should retain its current configuration.

**Steps to reproduce the bug**

We don't have a clear reproducer, but in our clusters we saw 100+ instances of this with the same pattern, all within a second of each other.

From the perspective of one Envoy sidecar, its connection to a Pilot instance is closed, and it appears to have no `ClusterLoadAssignment`s being watched:

```
[Envoy (Epoch 0)] [2020-05-26 00:11:37.919][22][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:91] gRPC config stream closed: 13,
[Envoy (Epoch 0)] [2020-05-26 00:11:38.008][22][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:91] gRPC config stream closed: 14, upstream connect error or disconnect/reset before headers. reset reason: connection failure
[Envoy (Epoch 0)] [2020-05-26 00:11:39.020][22][warning][config] [external/envoy/source/common/config/grpc_mux_impl.cc:153] Ignoring unwatched type URL type.googleapis.com/envoy.api.v2.ClusterLoadAssignment
```

The sidecar'd application is still sending requests, but at this point they all fall through to the `PassthroughCluster`.

In terms of ramifications / impacts, this issue has a noticiable impact on load balancing, as connections are established to a single upstream via K8s routing (via `ClusterIP` / K8s load balancing). As there is no request-level load balancing of requests on these connections, all requests sent from the sidecar'd application will always be sent to the same server, which can overwhelm the server (all other endpoints in the upstream cluster receive little, if any traffic).

Interestingly, reading where the logs occur in the [Envoy source code](https://github.com/envoyproxy/envoy/blob/b6f72358bf892c66d7d4603a9773b6debdb3a99d/source/common/config/grpc_mux_impl.cc#L148-L151), it apears as though we're hitting a "shouldn't happen" case, which smells like a bug.

```
      // No watches and we have resources - this should not happen. send a NACK (by not
      // updating the version).
      ENVOY_LOG(warn, "Ignoring unwatched type URL {}", type_url);
      queueDiscoveryRequest(type_url);
```

It's unclear to me if this is an Istio or Envoy issue, but I thought I'd start here. I can bug our friends over in the Envoy project if it turns out the issue is elsewhere.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
$ istioctl version --remote
client version: unknown
control plane version: 1.4.6
```

```
$ helm version --server
Server: &version.Version{SemVer:"v2.16.5", GitCommit:"89bd14c1541fa93a09492010030fd3699ca65a97", GitTreeState:"clean"}
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-13T18:06:54Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-gke.9", GitCommit:"e1af17fd873e15a48769e2c7b9851405f89e3d0d", GitTreeState:"clean", BuildDate:"2020-04-06T20:56:54Z", GoVersion:"go1.12.17b4", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

Helm.

**Environment where bug was observed (cloud vendor, OS, etc)**

GKE - `1.15.11-gke.9`

**Comment by howardjohn** [comment]
> it appears as though we're hitting a "shouldn't happen" case, which smells like a bug

It may be a bug, but I think you can also reproduce this by just sending Envoy some random type it doesn't understand. so its less of an "impossible" case than the comment suggests I think

**Comment by howardjohn** [comment]
If its just missing the CLA I would expect it to actually fail (no endpoints) or route to stale endpoints. If its going through the passthrough cluster this instead sounds like all of the config is removed? Any idea if that is the case?

**Comment by nicktrav** [comment]
> Any idea if that is the case?

It's hard to say. Unfortunately this has only bit us in one of our production clusters, and the impact is bad enough that we don't really want to poke it too much. If I see it happen again I'll try and gather the config dump.

In the meantime, I'll try and re-produce the failure mode elsewhere and come up with a concrete reproducer. 

I found it interesting that in the gRPC connection closed error, we saw the following:

```
gRPC config stream closed: 14, upstream connect error or disconnect/reset before headers. reset reason: connection failure
```

This makes it seem like Pilot's own Envoy proxy was up, but the `discovery` container was unavailable.

Compare that to the `gRPC config stream closed: 13,` which we see all the time, and seems to be benign.

**Comment by ramaraochavali** [comment]
Also please share Envoy log if you are able to reproduce- This happens if CLA  for a cluster is pushed to Envoy before its Cluster/before Envoy asks for it. Seems like dependency ordering bug.

**Comment by nicktrav** [comment]
I've made a little more progress debugging this.

It looks like we see this when a Pilot container crashes (investigating that separately). All of the Envoys that were previously connected to this instance reconnect to another Pilot instance (through a Google internal load balancer in our case).

Is it possible that an Envoy that reconnects to a different Pilot instance could get routing information that was sufficiently different from the configuration it had received from the Pilot instance that died?

Unfortunately the behavior is very non-deterministic - I _have_ been able to reproduce this in a different environment, but not reliably. Still digging ...

**Comment by nicktrav** [comment]
@howardjohn @ramaraochavali - I've now been able to reliably reproduce this issue.

It appears as though Pilot is sending back empty CLA responses immediately after it starts back up, following a crash.

I wrote a small tool that continually makes a `DiscoveryRequest` for CLAs to the same Pilot instance. I then restarted the `discovery` container in the Pod and observed the following:

```bash
-----------------------------------------------------------------------
version_info: "2020-06-02T05:07:53Z/112"
resources: <
  type_url: "type.googleapis.com/envoy.api.v2.ClusterLoadAssignment"
  value: "\n7outbound|50051||istio-ping.istio-ping.svc.cluster.local\022\212\004\n\n\n\010us-west2...snip"
>
type_url: "type.googleapis.com/envoy.api.v2.ClusterLoadAssignment"
nonce: "rPun1tlAaQQ=125a9931-9568-4464-aba4-baf079f6c759"

-----------------------------------------------------------------------
2020/06/01 22:07:55 rpc error: code = Unavailable desc = connection closed

-----------------------------------------------------------------------
version_info: "0"
resources: <
  type_url: "type.googleapis.com/envoy.api.v2.ClusterLoadAssignment"
  value: "\n7outbound|50051||istio-ping.istio-ping.svc.cluster.local" # <-- NOTE: empty
>
type_url: "type.googleapis.com/envoy.api.v2.ClusterLoadAssignment"
nonce: "cced792d-f0dd-4ae4-aa02-cdb650309dbd"

-----------------------------------------------------------------------
version_info: "0"
resources: <
  type_url: "type.googleapis.com/envoy.api.v2.ClusterLoadAssignment"
  value: "\n7outbound|50051||istio-ping.istio-ping.svc.cluster.local" # <-- NOTE: empty
>
type_url: "type.googleapis.com/envoy.api.v2.ClusterLoadAssignment"
nonce: "b1cda7ba-99a4-425f-91f5-fa529dbd6836"

-----------------------------------------------------------------------
version_info: "0"
resources: <
  type_url: "type.googleapis.com/envoy.api.v2.ClusterLoadAssignment"
  value: "\n7outbound|50051||istio-ping.istio-ping.svc.cluster.local" # <-- NOTE: empty
>
type_url: "type.googleapis.com/envoy.api.v2.ClusterLoadAssignment"
nonce: "44e5e574-4936-41c8-bb17-d6c4ec059b53"

-----------------------------------------------------------------------
version_info: "2020-06-02T05:07:57Z/0"
resources: <
  type_url: "type.googleapis.com/envoy.api.v2.ClusterLoadAssignment"
  value: "\n7outbound|50051||istio-ping.istio-ping.svc.cluster.local\022\277\001\n\r\n\013us-central1...snip"
>
type_url: "type.googleapis.com/envoy.api.v2.ClusterLoadAssignment"
nonce: "rPun1tlAaQQ=774353fe-72b4-489f-b9d9-b3510f6b98b8"

```

Pilot was first responding with the full CLA payload, which stopped briefly as the container was unavailable. However, when `discovery` came back, it started returning empty CLAs, which is when we observe the logs in the Envoys that were connected to this Pilot instance. The payloads then return to normal size within a few seconds.

Under normal conditions, on startup, a Pilot pod is not immediately added to the Service / load balancer fronting it, due to warming up of the liveness / readiness checks. However, when a container _crashes_, it is immediately restarted by the kubelet, and can handle connections from Envoys _before_ the LB controller can take the endpoint out of rotation (the controller does, eventually, based what I'm seeing the API server logs).

Pilot handling requests before it has sufficiently "warmed up" after a crash seems to be the underlying issue here.

**Comment by howardjohn** [comment]
@nicktrav awesome job on tracking this down! I can reproduce this as well and will investigate some more

**Comment by howardjohn** [comment]
script:
```
for i in {0..10000}; do
    echo request $i
    raw=$(~/kube/local/grpc/send-request.sh $i 2>&1)
    pattern="Failed to dial target host"
    if [[ $raw = $pattern* ]]; then
        echo "Not ready: $raw"
    else
        resp=$(echo $raw | jq '..|.address?.socketAddress?.address | select(. != null)' -r)
        if [[ $resp == "" ]]; then
            echo "EMPTY RESPONSE"
            sleep 10
        fi
        echo $resp
    fi
done | h "Not ready" request EMPTY
```

where send-request is 

```
WD=$(dirname "$0")
WD=$(cd "$WD"; pwd)

toJson () {
        python -c '
import sys, yaml, json
yml = list(y for y in yaml.safe_load_all(sys.stdin) if y)
if len(yml) == 1: yml = yml[0]
json.dump(yml, sys.stdout, indent=4)
'
}

request=$({ cat $WD/request.yaml; echo "- \"$1\""; } | toJson)
echo "${request}" | grpcurl -d @ -insecure localhost:15012 envoy.service.discovery.v3.AggregatedDiscoveryService/StreamAggregatedResources
```

`debug   ads     can not find the service for cluster outbound|80||alpine.default.svc.cluster.local` logged when I hit the issue.

**Comment by howardjohn** [comment]
I think the problem is there is a check for the Service informer to be synced. However, service events are handled async. So during startup, we declare service informer ready while we are still processing updates. Then the initial push, we have an empty Service list, so we end up with no endpoints

**Comment by howardjohn** [comment]
I actually don't see anything indicating that this cannot happen in a normal case with readiness probe. The probe can return ready before its fully synced, its just much less likely due to the timing

**Comment by howardjohn** [comment]
So the empty CLA is definitely an issue and I think I have a fix, will send soon. But I am not sure how that causes the `Ignoring unwatched type URL type.googleapis.com/envoy.api.v2.ClusterLoadAssignment`?

**Comment by ramaraochavali** [comment]
Are we sending empty CLA for a cluster before CDS response with that cluster has been sent?

**Comment by howardjohn** [comment]
I was wondering about that as well - we should only send CLA for things Envoy requests, so I don't think we can send endpoints when they aren't requested?

**Comment by ramaraochavali** [comment]
Yes. That is generally correct. But that error from Envoy comes in that case only - probably the cluster is removed from Envoy because of this disconnect/reconnect?
See this test case https://github.com/envoyproxy/envoy/blob/master/test/common/config/grpc_mux_impl_test.cc#L632
https://github.com/envoyproxy/envoy/issues/3355 and  https://github.com/envoyproxy/envoy/pull/3359 which added that code and test. 

I will also look in detail tomorrow

**Comment by howardjohn** [comment]
Copy+paste from slack conversation about this:


John Howard(opens in new tab)  1 day ago
In our app we have an initialization phase where we sync up all of the k8s objects (in this case, Service) with our internal model. We don't want to serve traffic until we are synced. Today we do this by looking at informer.HasSynced(). The problem is we handle add/update events asynchronously. So at startup, the informer fires off a bunch of Add events, and (correctly) declares itself synced. However, in terms of the app, we have not synced until those have completed. Is there any patterns for handling this case? I was thinking something like in the event handler if !informer.HasSynced() { run sync } else { run async } but that doesn't feel like a good solution

John Howard(opens in new tab)  1 day ago
Actually now that I look at it, even if we handle things synchronously HasSynced still returns true before they are processed

liggitt(opens in new tab)  1 day ago
one way to deal with that is to wait for informer.HasSynced() to return true, then iterate over all items and call your sync handler synchronously on them at startup (edited) 

liggitt(opens in new tab)  1 day ago
then start your asynchronous workers

John Howard(opens in new tab)  23 hours ago
Thanks! looks like that works

John Howard(opens in new tab)  23 hours ago
Would you do the iteration like
for i, s := range c.serviceInformer.GetStore().List() {
    c.onServiceEvent(s, model.EventAdd)
}
?

liggitt(opens in new tab)  23 hours ago
not super familiar with your handlers, do you have logic directly in the onServiceAdd method?

liggitt(opens in new tab)  23 hours ago
or do you use that to queue up a "syncService(foo)" call?

John Howard(opens in new tab)  23 hours ago
Our normal ones have a queue

John Howard(opens in new tab)  23 hours ago
Like
AddFunc: func(obj interface{}) {
    queue.Push(func() error {
        return c.onServiceEvent(obj, model.EventAdd)
    })
},

liggitt(opens in new tab)  23 hours ago
hmm

liggitt(opens in new tab)  23 hours ago
so your sync handlers get called 1:1 with watch events?

liggitt(opens in new tab)  23 hours ago
the obj is captured in a closure, looks like

John Howard(opens in new tab)  23 hours ago
I was mostly wondering if .GetStore().List() was the right thing to iterate over?

liggitt(opens in new tab)  23 hours ago
well... given how your handlers are wired, that would be problematic

liggitt(opens in new tab)  23 hours ago
imagine:
1. list happens, queues up add(a@1), add(b@2)
2. watches start happening, queues up update(a@3, a@4)
3. hasSynced() returns true, you iterate and call add(a@4, b@2)
4. then you start your queue worker and it sees add(a@1), update(a@3), update(a@4) after having been called with add(a@4)

liggitt(opens in new tab)  23 hours ago
normally, syncHandlers are just given the name of the object to sync and pull the object itself out of the local store (edited) 

liggitt(opens in new tab)  23 hours ago
so the sync handler is always operating on the latest observed version

liggitt(opens in new tab)  23 hours ago
and if it gets asked to handle the same version multiple times, it should be idempotent anyway

John Howard(opens in new tab)  23 hours ago
Hmm.. that is a good point. Glad I asked then. So like https://github.com/kubernetes/sample-controller/blob/a1a67935a65841952d990076df30b6649f25bf53/controller.go#L345? Then the lookup call (https://github.com/kubernetes/sample-controller/blob/a1a67935a65841952d990076df30b6649f25bf53/controller.go#L252) is cheap because its cached?

controller.go:345(opens in new tab)
<https://github.com/kubernetes/sample-controller|kubernetes/sample-controller>kubernetes/sample-controller | Added by GitHub(opens in new tab)

controller.go:252(opens in new tab)
<https://github.com/kubernetes/sample-controller|kubernetes/sample-controller>kubernetes/sample-controller | Added by GitHub(opens in new tab)

liggitt(opens in new tab)  23 hours ago
right

liggitt(opens in new tab)  23 hours ago
and if you get a NotFound error back, then you're syncing a delete

John Howard(opens in new tab)  23 hours ago
Queueing the name then looking it up makes sense for this case, but it seems like an edge case. Are there other reasons its preferred to do it this way? It seems like in most cases if the informer is already presenting us an object we might as well use it rather than grabbing the key and looking it up again?

**Comment by caitong93** [comment]
Maybe another approach: mark items when informer start to sync, stop mark when HasSynced returns true, wait marked items to be processed

``` go
var initialKeys map[string]struct{}
var stopFlag bool
var maxWaitTime time.Time
var interval time.Duration

// 1. setup handler
AddFunc: func(obj interface{}) {
  key := objectKey(obj)
  if !stopFlag {
      initialKeys[key] = struct{}{}
  }

  queue.Push(func() error {
    if len(initialKeys) > 0  {
      delete(initialKeys, key)
    }
    
    return c.onServiceEvent(obj, model.EventAdd)
  })
}

// 2. after HasSynced returns true
stopFlag = true

// 3. wait all marked items being processed
PollWait( func() (quit bool, err error) {
        if len(initialKeys) == 0 
  }, interval, maxWaitTime)

// 4. we are ready
```

WDYT ? @howardjohn @ramaraochavali

**Comment by howardjohn** [comment]
@caitong93 something similar to that seems like a pretty good idea to me

**Comment by stevenctl** [comment]
@howardjohn can we consider this fixed?

**Comment by howardjohn** [comment]
@stevenctl yes I think so - if someone can show otherwise we can reopen. Thanks for your change!
