### ISSUE TITLE
Canary deployment/Traffic routing with labels doesn't work as expected in ONLY VM setup

### ISSUE THREAD

**Issue by kidiyoor** [istio/istio#2422]
Continuation of issue:  https://github.com/istio/issues/issues/124
Ref: https://github.com/kubernetes/kubernetes/issues/57815

Short summery: Kube Service to Endpoints object mapping doesn't support selector/labeling mechanism. Hence its difficult to create 2 endpoints for a service with 2 different labels.

You can find more details here -  https://github.com/istio/issues/issues/124

**NOTE:** This is ONLY VM setup, no PODS. Customer application run on bare VM and standalone apiserver acts as both config store and service registry. Very similar to VM expansion.

**Comment by rshriram** [comment]
I think the story for only vm setup is to use consul registry and adapter.

**Comment by kidiyoor** [comment]
Yes. Consul does a very good job if used as service registry, it solves above problem.

But using apiserver as service registry is more like 'step-0'/'easy on-boarding' for istio users. Customers/Istio user might not have expertise on Consul. Using apiserver service registry will enable istio users to start playing with istio on 'VM only' with minimal setup. 

Given choice(for production) I would choose Consul as service registry for only VM setup.

**Comment by rshriram** [comment]
The point is that the minimal setup is not what you would use in production, as we have to reinvent service registration, health checking, and a whole lot of things.

Also to your argument about no expertise on Consul, Istio users who are running istio on just VMs (no kubernetes) may not have experience with Kubernetes API servers, etcd management, etc. either. 

So it boils down to what you are comfortable with, since you have to learn both.

**Comment by kidiyoor** [comment]
@gbrail @vdshah

**Comment by kyessenov** [comment]
@mandarjog

**Comment by gbrail** [comment]
So what's the proposed architecture for customers who want to either do mesh expansion or run Istio only on VMs (or Ms for that matter)?

Can all the components of Istio function fully with only Consul deployed? 
Or can we make it all work with etcd?
Or are we asking users to deploy etcd for the Istio control plane and Consul for their own services?

**Comment by mandarjog** [comment]
Core Istio components store their configuration in the K8S API server. This means minimally Istio needs K8S ApiServer and etcd which the API Server depends on.
Since Istio already supports a Consul adapter for Pilot that should be used as VM service registry.

So as @gbrail said, the customer needs to deploy both etcd and Consul.

**Comment by gbrail** [comment]
Yeah -- that's kind of a bummer for someone who has some legacy services
that they want to integrate into an Istio mesh and kick the tires. "After
you install etcd and learn how to manage its configuration, please also
configure Consul which is kind of the same thing." It just increases the
number of distributed systems that a potential Istio adopter has to absorb.

**Comment by rshriram** [comment]
On Tue, Jan 30, 2018 at 11:58 AM Greg Brail <notifications@github.com>
wrote:

> Yeah -- that's kind of a bummer for someone who has some legacy services
> that they want to integrate into an Istio mesh and kick the tires. "After
> you install etcd and learn how to manage its configuration, please also
> configure Consul which is kind of the same thing." It just increases the
> number of distributed systems that a potential Istio adopter has to absorb.


We do have a file based config as well. No etcd.

**Comment by ZackButcher** [comment]
As Shriram said, you can put config files on disk and skip using the k8s API server/etcd. We also do dynamic reload as files in the directory are changed.

**Comment by mandarjog** [comment]
Pilot and Mixer both have file system based providers, but the customer has to take care of
1. config distribution 
2. validation
3. input... No kubectl or istioctl

If the customer is ok doing all these things, then file system based provider works.

**Comment by smawson** [comment]
This problem is more general than just routing, we also have this problem with policy enforcement.

Generally speaking we need to support labeling VMs, and then getting those labels to Pilot, so that Istio fully works.

Do we already have a separate issue tracking that or should we repurpose this one for that?

**Comment by kyessenov** [comment]
I cannot find any existing issue, although this was known for awhile. @costinm probably knows details.

**Comment by rshriram** [comment]
If you deploy consul agents on the VMs, you get all this labeling stuff for free, in addition to more reliable service registration, health check, de-registration and so on. And as @kidiyoor himself said

>Given choice(for production) I would choose Consul as service registry for only VM setup.

And some folks have been playing with Consul templates, that allows them to distribute and mount their files locally, for pilot to pick up the routing rules/other stuff.

**Comment by louiscryan** [comment]
The new networking APIs more directly support this use case through ExternalService

https://github.com/istio/api/blob/master/routing/v1alpha2/external_service.proto

which effectively acts as a way to write endpoints into Istio without needing Consul.

**Comment by rshriram** [comment]
That only works if we want to integrate some k8s cluster with a bunch of VMs. And even there, manually updating an external service with VM endpoint IP is a very painful error prone process (scripts are equally brittle).

What @kidiyoor wants is to run an entire istio mesh on a set of VMs, where each VM needs to have a sidecar for inbound/outbound traffic in the mesh.

**Comment by kidiyoor** [comment]
reframing above statement - by 'multi VM setup' I meant 'multi VM control plane setup' with **multiple mixer, pilot**.

**Comment by smawson** [comment]
The right solution here seems to be to model VMs as a first class resource, rather than trying to use (abuse) the external service api. Especially since these aren't external services, they're part of the mesh.  It should be extremely simple to create a CRD representing a VM and attach labels there, and pipe that through the system just as we do with pod labels.  This also gives us a place to attach other metadata we need for VMs, for example for Istio Security.

@costinm can we prioritize solving this to make VM support work without needing to resort to "use consul" answers?

**Comment by kyessenov** [comment]
It would be interesting to research if there are existing CRDs for VM available. It might be worth looking at kubevirt (see https://kubevirt-incubator.github.io/api-reference/master/definitions.html#_v1_virtualmachine).

**Comment by rshriram** [comment]
Is there a specific technical (not strategic) reason why we are preferring a completely new solution using kube api server and such (not to mention new tools for service registration, health checks, and such) over an existing solution that is being used by the community (Consul) ?

**Comment by smawson** [comment]
What I'm trying to do is limit what is required in the minimal install of Istio, and have that be consistent across environments.

We already have a requirement for our api server, backed by etc, to be present, as a place to store and manage configuration. Rather than asking users to install and manage yet another system, I want to make Istio work with the existing set of components.

We should also be pursuing how to have our api server backed by consul instead of etcd, and then a consul-based minimal install would be possible, which would be awesome.

And of course we want to support users optionally using consul in all environments, as well as other options for service discovery and registration. But we don't want to make any of those required, we want to keep the required set of components small and consistent.

**Comment by gbrail** [comment]
Thank you Sven. I think that keeping the minimal Istio install small, even
when K8s is not used, is an important goal.

**Comment by rshriram** [comment]
I agree with the goal. What I am driving at is reinventing service registration, health tracking, de-registration/re-registration, etc. is not fruitful. And in any production installation with 1000s of VMs, (with VMs added/removed dynamically), any form of file based registration mechanism (CRDs, external services, istioctl-register etc.) is very brittle. I've done this in the past and learned the lesson the hard way. The list of things you have to do to accommodate all corner cases is endless.

I guess your proposal for CRDs is stemming from the assumption that a cluster of VMs is static or that we can scrape this info *reliably* from the likes of chef/puppet? Even with static clusters, there is infrastructure instability issues to consider. The fact that we don't offer active health checking makes any manual registration solutions even more brittle. 

Service registration, health check is an integral part of the application deployment/management. Without that or with a flakey implementation, Istio/any other mesh is likely to yield less benefit. And since we are discussing about getting into this field, my proposal is to reuse a well tested community solution. Yes, its going to add more components to install. The solution is to either look for alternative backends for our API objects like file backend. 

One possible alternative here is to ask people to deploy a small k8s cluster (aka manage etcd) and deploy the Consul server inside the k8s cluster as part of istio control plane install for VMs (they don't have to worry about it). This has the benefit of eliminating consul server management headache, while still providing end users with some reliable service registration system (consul agent on every app VM, that takes care of all the registration stuff).

**Comment by louiscryan** [comment]
I think we are arguing about deployment best-practices out of context. We need to support both use-cases as folks are going to use whatever tool they damn well want to manage their VMs and we need to accommodate. If I were managing 10K VMs I would personally be inclined to use Consul but we know there are plenty of folks at that scale who don't and would appreciate some support in Istio.

@smawson - I think ExternalService is a reasonable short-term approach, API name aside its a mechanism to write an entry into the service registry for a service that is 'part of the mesh'. Happy to rename to better align. The other use-cases around workload identity etc deserve a more thorough discussion.

**Comment by smawson** [comment]
@louiscryan  - I'm fine with ExternalService as a short-term fix, but longer term it doesn't model what we want to model correctly.

We want to model the workloads, and use service = workload-label-selector, so we have a consistent model across the entire mesh of what a workload is, and what a service is. ExternalService is to allow us to model things outside the mesh, where we don't know anything about the workloads behind them. So I think we need both. But for in-mesh we should support using the standard API model and not require something different depending on the environment.

The right way to do this is to just model the workloads directly. It isn't that hard, as Kuat points out others have already done this (although kubevirt is actually orchestrating VMs, so has a lot more metadata than we need).

@rshriram - I'm not proposing we invent anything new here beyond supporting VM workloads directly in our API as we do with pods. I don't think registering/deregistering those VMs is particularly tricky, especially since we already are running an agent on each of the VMs. And we're already doing this registration as part of VM expansion anyway, I'm just proposing a slight change in how the registration happens.

I also agree with Louis that for a large deployment, Consul may end up being a great fit, and we absolutely want to support it. But we're already way too big of an install, we need to figure out how to fit Istio into small clusters, and not optimize only for large clusters.

Running our control plane inside k8s instead of directly on VMs is an option we support, but I don't want to tie these issues together, we should be able to separate them. It sounds like you're almost advocating for defaulting to Consul as part of the general Istio install, which is a whole other discussion. It may be possible if we can drop etcd and they have a similar footprint. Definitely worth exploring.

But even if we end up doing that, there is *still* a lot of benefit in representing VMs directly as resources in our config store, for the same reason we represent pods and containers. So I think that's a fine discussion to have, but ultimately shouldn't delay us fixing the immediate problem of needing labels on VMs.

**Comment by rshriram** [comment]
> @rshriram - I'm not proposing we invent anything new here beyond supporting VM workloads directly in our API as we do with pods. I don't think registering/deregistering those VMs is particularly tricky, especially since we already are running an agent on each of the VMs. And we're already doing this registration as part of VM expansion anyway, I'm just proposing a slight change in how the registration happens.

Three points:
1. By using a registration system, we get features like labels, and other metadata natively. We don't have to model them at all.

2. Its not just registering and deregistering a VM. The moment you introduce a registration agent, you are going to have requests for liveliness check, readiness check, health check with scripts/api calls, auto recovery post network partition, etc. Been through all that stuff with the WebSphere people (the kind you are most likely to find in On prem workloads). These may not appear hard on surface, but it takes a long time to get these in solid shape, iron out all  the issues, and be able to confidently say we handle these. My point is that we have ready made tools that have been well tested (not just scale) for this purpose.

3. Whether it is 10 VMs or 100 VMs, they are all ephemeral at some level (they come and go, IPs change due to dhcp and stuff), and defining liveliness/readiness probes etc. gets trickier even in the simplest of cases where VMs are relatively static (few hours to days). Its just not a *reliable* mechanism for automation (reliable, not necessarily scalable).

> It sounds like you're almost advocating for defaulting to Consul as part of the general Istio install, which is a whole other discussion. It may be possible if we can drop etcd and they have a similar footprint. Definitely worth exploring.

Consul registration agents for VMs install. Given that its in Go, I would go as far as saying that we could simply import that entire code as a library and incorporate that into our node level agent. Essentially, its just one binary running Consul registration code plus our istio ca agent. Keeps our VM level footprint low, and users dont care whether its consul or istio version of consul. As far as they are concerned, the registration system works without hassle from their point of view, while we get all the metadata we need. 

Its a different story in the control plane, and it depends on how we package the control plane.

**Comment by ldemailly** [comment]
subscribe

**Comment by ldemailly** [comment]
Not resolved, not stale

**Comment by kidiyoor** [comment]
not stale
