### ISSUE TITLE
Automate Repo Updates

### ISSUE THREAD

**Issue by brian-avery** [istio/istio#24586]
Currently, CNI and Envoy must both have their SHAs updated manually. This will likely soon include go-control-plane as well. These updates are easy to lose track of and it could be a significant amount of time between when an update is merged in a repo and when Istio actually picks it up. This is even more painful in Envoy where tests must be completed each step of the way and these tests can take over an hour to run. 

This issue will cover the process of automatically updating the SHAs for: 
* Envoy
  + istio/proxy when istio/envoy changes
  + istio/istio when istio/proxy changes
* CNI
  + istio/istio when istio/cni changes

**Comment by jwendell** [comment]
JFYI, CNI is now part of istio/istio. It's still standalone for branches <= 1.6, though.

**Comment by ericvn** [comment]
Envoy moves to istio/envoy when branches are cut(?) so can add that as a post cut item.
Proxy is done.

**Comment by ericvn** [comment]
Should we do istio/envoy to istio/proxy for 1.7?

**Comment by brian-avery** [comment]
Addressed for Envoy and API, CNI no longer needed.

**Comment by ericvn** [comment]
Summary:

master:
  envoy has periodic task (168h) looking for envoy updates causing proxy to use a new sha
  proxy update causes update of proxy sha in istio/istio
  cni not needed

release-1.8
  envoy updates causes update of envoy sha in istio/proxy
  proxy update causes update of proxy sha in istio/istio
  cni not needed

release-1.7
  envoy updates are not automatically made in istio/proxy
  proxy update causes update of proxy sha in istio/istio
  cni not needed

release-1.6
  envoy updates are not automatically made in istio/proxy
  proxy updates are not automatically made in istio/istio
  cni updates are not automatically made in istio/istio

We can verify the automation job for the proxy update works correctly in release 1.8 and copy to 1.7 so 1.7 automation is complete. release-1.6 is near EOL so maybe no additional changes are needed there.

Note: We need to make it part of the release branching to add the envoy update since it's periodic in master and not copied to the new branches.

**Comment by howardjohn** [comment]
I think this is done?

**Comment by ericvn** [comment]
With the exception of https://github.com/istio/istio/issues/28403, I think this is done. Will take a look at the issue to verify.

**Comment by ericvn** [comment]
https://github.com/istio/proxy/pull/3194 should contain a fix to the periodic envoy updates to istio/proxy in the main/master branch. That should be that last item to close this issue.
