### ISSUE TITLE
Istioctl analyze IST0108 invalid?

### ISSUE THREAD

**Issue by Stono** [istio/istio#24632]
**Bug description**
We get the following:
```
Warn [IST0108] (Pod solr-1.search-solr) Unknown annotation: traffic.sidecar.istio.io/includeOutboundPorts
```

However this was added here: https://github.com/istio/istio/issues/21845

[ ] Configuration Infrastructure
[x] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[x] Developer Infrastructure

**Expected behavior**
Not to get a warn for a valid annotation

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.5.4

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by esnible** [comment]
This annotation is on our 1.7 docs page, but not on 1.6

- https://preliminary.istio.io/latest/docs/reference/config/annotations/
- https://istio.io/latest/docs/reference/config/annotations/

This is fixed in Master.  Istio analysis picks up the list of annotations from _istio.io/api/annotation/annotations.yaml_ and _annotations.gen.go_, so it automatically picked it up when https://github.com/istio/api/pull/1447 merged and then istio/istio/go.mod picked up the new api version.

If you think 1.6 supports but doesn't document `includeOutboundPorts` we could back port something to release-1.6.  Otherwise please close this Issue.

**Comment by Stono** [comment]
Hey, we don't actually use this feature anywhere - I was exploring a potential solution to a problem and remembered asking for it ages ago.  But looking at the PR yes it was merged into master at the end of may.

Cheers for clarifying.
Karl
