### ISSUE TITLE
Port CNI installer from shell to golang

### ISSUE THREAD

**Issue by jwendell** [istio/istio#24775]

**Comment by stewartbutler** [comment]
Few notes for things I had in mind for this:

- We should probably use some inotify-like event based file watcher (fsnotify? maybe something from galley or istiod?) instead of the while loop for monitoring installation status
- We should have a webserver that exposes a /healthz and /readyz endpoint
  - /healthz indicates that the installer binary is running
  - /readyz indicates that the installer binary has installed the configuration, and that CNI is ready to start processing pods. We can use this in CNI race condition mitigations.
- The installation logic should be a library package, so down the line we can integrate all the different CNI binaries into a single executable (e.g. have a single binary that spawns goroutines to run the installer, repair controller, a future logs exporter, etc). This is probably already what you had in mind, but I wanted to call it out explicitly.
- The heredoc in the shell script should probably be replaced by a go template that is copied into the container, which could be overwritten by a configmap

**Comment by rlenglet** [comment]
@jwendell Are you actively working on this? @bcheung is cleaning up and fixing the `install-cni.sh` script, and would like to do the Golang rewrite while he's on top of the current implementation. Are you OK to reassign this to him? Thanks!

**Comment by jwendell** [comment]
Yes, I am working on this.

**Comment by rlenglet** [comment]
@jwendell that's great! Please sync up with @bcheung, who is doing significant fixes to the install script. Please make sure to pick up his fixes once he sends out his PR.
