### ISSUE TITLE
The istioctl kube-inject -f is empty

### ISSUE THREAD

**Issue by liwjGhostcloud** [istio/istio#2489]
the question 1:
when i try  istio-0.4.0
1.istioctl kube-inject -f samples/bookinfo/kube/bookinfo.yaml > book.yaml
2.vi book.yaml 
the book.yaml is empty and my kubernetes verison is 1.8 
question 2:
then i use `kubectl apply -f samples/bookinfo/kube/bookinfo.yaml`
i find the `echo $(kubectl get deployment sleep -o jsonpath='{.metadata.annotations.sidecar\.istio\.io\/status}')` is empty ,the InitializerConfiguration is not effective?

**Comment by ayj** [comment]
Have you deployed the initializer to your cluster per https://istio.io/docs/setup/kubernetes/sidecar-injection.html#automatic-sidecar-injection?

The initializer logs and full output of the sleep deployment would be helpful to debug.

**Comment by liwjGhostcloud** [comment]
i find where i`m wrong. but my cluster use `Webhook` to authorization .how can i use initializer  in another way?

**Comment by ayj** [comment]
Initializers requires https://kubernetes.io/docs/admin/extensible-admission-controllers/#initializers (k8s >= 1.7.x plus [alpha features](https://kubernetes.io/docs/admin/extensible-admission-controllers/#enable-initializers-alpha-feature). 

> the book.yaml is empty and my kubernetes verison is 1.8

Empty `kube-inject` is likely due to missing istio configmap. There was a bug which dropped the error message which should be fixed by https://github.com/istio/istio/pull/2334.

**Comment by ayj** [comment]
Possible dup of https://github.com/istio/istio/issues/2338

**Comment by liwjGhostcloud** [comment]
ok , i will try it again ,when i find another problem i will ask u again, thanks @ayj
