### ISSUE TITLE
istio helm release is not consistent with istio release version

### ISSUE THREAD

**Issue by linsun** [istio/istio#2516]
It is much desired to have the istio helm release consistent with the istio release version so that confusions among users as to which helm release maps to which istio release can be much reduced.  Currently our 0.4 releases istio binary ships helm istio release of 0.3, so is the current master.   We need to be able to update the istio helm release and its dependencies in chart.yaml files and dependencies.yaml.

**Comment by sdake** [comment]
@linsun,

At present, the only way to achieve a complete helm package is to run `updateVersions.sh` which writes `values.yaml`.  The file `values.yaml` contains among other things all image tags that are used by default.  Without values.yaml (i.e. a fresh git clone - helm install will not work).

The only file that needs to be generated is `values.yaml` and it needs to be generated during the release process.  I'm not up to speed on how the release process works, however, all templates now have this issue, as all pre-rendered templates have been removed from the repository in master.  This was a conscious decision several PRs ago related to the template work but requires coordination with the release team to create a release that includes rendered information.  Perhaps you can point the right people at this issue tracker?

git status shows these files as untracked after an updateVersions.sh after a fresh git clone.

```
STDAKE-M-26T1:istio sdake$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	install/consul/istio.yaml
	install/eureka/istio.yaml
	install/kubernetes/helm/istio/values.yaml
	install/kubernetes/istio-auth.yaml
	install/kubernetes/istio-ca-plugin-certs.yaml
	install/kubernetes/istio-initializer.yaml
	install/kubernetes/istio-one-namespace-auth.yaml
	install/kubernetes/istio-one-namespace.yaml
	install/kubernetes/istio.yaml
	samples/bookinfo/consul/bookinfo.sidecars.yaml
	samples/bookinfo/eureka/bookinfo.sidecars.yaml
```

Cheers
-steve

**Comment by linsun** [comment]
@sdake if you download 0.4 binary, you can see values.yaml is already generated.  And that file doesn't really have much version info.  Yes, I'm opening this issue so I can work with release team to get the other version sensitive contents properly updated during the release.

cc @sebastienvas @yutongz @hklai

**Comment by sdake** [comment]
@linsun in version 0.4, we shipped values.yaml in the repo.  In version 0.5 (the next version iiuc), the values.yaml will need to be generated as it is no longer in the repository(along with the other generated templates).

**Comment by linsun** [comment]
Ah I missed that caveat, thank you for clarifying that @sdake

**Comment by mattdelco** [comment]
Since version 0.3.0 the release builds have been running updateVersion.sh (with the current/latest version \#) prior to generating the install tars (this is handled by release/update_and_create_archives.sh).  This is why the generated files that were in the repo were at version 0.2 (and why the stale istio.RELEASE says 0.3).

So, if you're just concerned about values.yaml then this should already be handled today.  If the other files should be also be updated (e.g., for consistency/completeness/reduced confusion/etc.) then I suppose someone will need to expand updateVersion.sh to also update those other files (though in that case I'd also wonder why the initial helm commit only had updateVersion.sh update the 1 file).

**Comment by yusuoh** [comment]
Is the version field in the chart.yaml file also updated correctly by every new release? When users use 'helm ls' to check the version info, will it show the same version with the release?

**Comment by sdake** [comment]
@yusuoh no it isn't.  Currently it is listed as 0.3.0: https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/Chart.yaml#L2.  How I've seen this handled in the past on fast moving projects is a manual update of the version field in the aforementioned file, followed by a commit of that file prior to a branch and tag operation.

Cheers
-steve

**Comment by mattdelco** [comment]
The only helm file that's updated is values.yaml.  None of the Chart.yaml nor the requirements.yaml are updated since these were checked in as static files rather than as a template updated by updateVersion.sh (only values.yaml was set up to be updated, and that one was originally set up to be updated in-place rather than derived from a template).  I don't have the  background to know if that was an oversight or intentionally done for other reasons (e.g., point to a known-stable release).

**Comment by yusuoh** [comment]
How is that version field in Chart file being used by Helm? I think Helm has stored version history internally for every upgrade and rollback, so maybe it is only an informational? Can we treat that value as the version of Chart files but not the version of Istio?

**Comment by linsun** [comment]
Think this is resolved in 0.5 by manually updating the versions.  we probably should look for an automated way going forward.

**Comment by sdake** [comment]
I don't think this is automated in the helm chart release process.  I see many helm subcharts with 0.5.0 present.  @sebastienvas any chance you can find someone to automate the changing of the charts/subcharts (or point me where it should be done during the release process, and I'll add some automation if I can figure it out).

Thanks
-steve

**Comment by linsun** [comment]
It is still not, let's use this to track the automation needed for it.  so far, it is been a PR for each release.

**Comment by rkpagadala** [comment]
@linsun @sdake the best place to fix this is in the make target istio-archive
