### ISSUE TITLE
Abort faults are not accurate due to the default retry policy

### ISSUE THREAD

**Issue by jwendell** [istio/istio#25160]
By default Istio sets a 2 retries policy. This interferes with the settings in fault.abort.

If user sets a fault rate of, say 50%, in practice it has no effect because the retry setting will request the service again.

Some solutions:
- Document this behavior
- Remove this automatic retry policy
- Or have it automatically applied only if there's no abort fault set.

**Comment by thinkin** [comment]
what does"automatic retry policy" mean?

**Comment by jramcast** [comment]
> what does"automatic retry policy" mean?

I guess @jwendell refers to [the default retry behavior for HTTP requests is to retry twice before returning the error](https://istio.io/latest/docs/concepts/traffic-management/#retries).

I only experienced this behavior when traffic flows through multiple services. For example: we have service serviceA and serviceB. ServiceA acts as an api gateway that calls serviceB. In case of error in serviceB, serviceA propagates the error, which means that aborted requests in serviceB will also be aborted by serviceA. 

Then, we tell serviceB to abort 50% of requests. If we make requests directly to serviceB, the percentage of aborted requests will be ~50%. So far so good. 

Now, we send traffic to serviceA. Every aborted request in serviceB will make serviceA to also abort the request. However, in this case, we won't see a ~50% of aborts, but a much lower percentage. This is because serviceA retries each request twice by default. So I wonder... is this the intended behavior?

**Comment by howardjohn** [comment]
@jwendell that is interesting since we cannot actually define retry and abort in the same VS: https://github.com/istio/istio/issues/13705. is the default retry policy different in some way?
