### ISSUE TITLE
what is gateway bind and defaultEndpoint  for？

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#25171]
**Bug description**
```
[root@master01 gateway]# kubectl explain Gateway.spec.servers
KIND:     Gateway
VERSION:  networking.istio.io/v1beta1

RESOURCE: servers <[]Object>

DESCRIPTION:
     A list of server specifications.

FIELDS:
   bind <string>

   defaultEndpoint      <string>

   hosts        <[]string>
     One or more hosts exposed by this gateway.

   port <Object>

   tls  <Object>
     Set of TLS related options that govern the server's behavior.
```
here ,how to config bind, and defaultEndpoint      ,any demos

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by esnible** [comment]
@13567436138 These fields exist in https://github.com/istio/api/blob/master/networking/v1beta1/gateway.proto but are marked `$hide_from_docs` which means they are either deprecated or not yet implemented.  Please do not use them.

@jasonwzm These fields arrived in https://github.com/istio/api/pull/1192 .  Do you know how to run the generator?  Would it be reasonable to give any `$hide_from_docs` fields something such as `description: deprecated` in _kubernetes/customresourcedefinitions.gen.yaml_ and _manifests/charts/base/crds/crd-all.gen.yaml_ so that `kubectl explain` users get a warning not to use the field rather than just not knowing if we have neglected to document it?

@jasonwzm On that same pull, same files, same `kubectl explain`, there is no `description` for `port` although there is one in https://istio.io/latest/docs/reference/config/networking/gateway/#Server and `kubectl explain Gateway.spec.servers.port` shows a description for all of port's children.  Could there be a problem with Istio's build in crafting a description for all of the fields?
