### ISSUE TITLE
Feature: Istio multicluster support FQDN other that *.global

### ISSUE THREAD

**Issue by zufardhiyaulhaq** [istio/istio#25324]
**Describe the feature request**
Enable Istio multicluster installation to support FQDN other that *.global (I am willing to do this).

**Describe alternatives you've considered**
- modifying Istiocoredns, adding EnvoyFilter, DestinationRule, & Gateway object to support custom FQDN to communicate between multiple clusters (tested).
- Add documentation on Istio docs to do this (I am willing to do this)

[X] Configuration Infrastructure
[X] Docs
[X] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
The new position for multicluster does not recommend or document using `*.global` at all and has taken new guidelines, so I do not think we will imeplemt this. Please take a look at https://preliminary.istio.io/latest/docs/setup/install/multicluster/. Thanks!

**Comment by kirecek** [comment]
This is can be done tho.

**Comment by kirecek** [comment]
Maybe it's not official, but it's possible to achieve this.

1.)  It's not possible to modify coredns configmap and coredns sidecar is deprecated anyway. The solution is to enable resolution in proxy instead of using coredns  `.Values.meshConfig.defaultConfig.proxyMetadata.ISTIO_META_DNS_CAPTURE: "true"`.
2.) set [.Values.global.multiCluster.globalDomainSuffix](https://github.com/istio/istio/pull/27427) to your desired domain.
