### ISSUE TITLE
Limit Istio to only perform stuff on a given certain set of namespaces

### ISSUE THREAD

**Issue by antonioberben** [istio/istio#25382]
In previous versions a user was able to label namespaces to let Istio (istiod) know to not "touch" those namespaces.

In a concrete example is `istio-ca-root-cert` being deployed in every namespace.

https://github.com/istio/istio/blob/10b00462d6274dcff6b63042a95ea0bb3b432e41/security/pkg/k8s/controller/workloadsecret.go#L52

The scenario is that our k8s provider makes `kube-system` namespace protectected by admin policies. Therefore, `istiod` keeps trying to deploy the certs in that namespaces, failing and retrying endlessly.

@howardjohn suggested me to bring this topic to the attention @lei-tang and @myidpt .

Thank you guys for your help.

[ X ] Configuration Infrastructure
[ X ] Docs
[ X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ X ] Security
[ ] Test and Release
[ X ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by lei-tang** [comment]
Since I will be OOO starting next week, the issue is assigned to @myidpt for triage.

**Comment by pzelensky** [comment]
We've got into the issue that's also related to this inability to set the list of namespaces managed with istio (not just as a list of namespaces, but using regular expressions for example).
In our case we 200+ namespaces in the cluster with 2k+ pods. The single namespace that is running spark jobs those are not having istio sidecars (there's any label on the namespace). Due to activity in that namespace istiod is creating new configs for envoys and sends them constantly to all sidecars. Actually it's just sending the same config. This makes istiod to consume all CPU (in our case it skyrocketed to 50+) and huge bandwidth.
This happened to disregard the fact that annotations `networking.istio.io/exportTo` set for all services in the namespace to '.' (only this namespace).
