### ISSUE TITLE
Multiple VM test very flaky

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#25391]
https://github.com/istio/istio/pull/25341

https://prow.istio.io/view/gcs/istio-prow/logs/integ-pilot-k8s-tests_istio_postsubmit/2938
https://prow.istio.io/view/gcs/istio-prow/logs/integ-pilot-k8s-tests_istio_postsubmit/2936

**Comment by ZhengzheYang** [comment]
I will take a look!

**Comment by ZhengzheYang** [comment]
https://prow.istio.io/view/gcs/istio-prow/logs/integ-pilot-k8s-tests_istio_postsubmit/2948 This also fails sometimes? I think it might be the related dns issue? #25242 Like this PR, if DNS capture is enabled for all, multiple tests would fail. Since DNS capture is enabled for all VMs, they might fail as well. Reverting #25341 seems reasonable here, though.

**Comment by rshriram** [comment]
```
TestVmOSPost/dns:_vmA_to_vmB_using_image_app_sidecar_debian_9: vm_test.go:183: retry.UntilSuccessOrFail: timeout while waiting (last error: failed calling vm-a->'http://vm-3:8090/': rpc error: code = Unknown desc = Get "http://vm-3.virtual-machine-2-55143.svc.cluster.local:8090": dial tcp: lookup vm-3.virtual-machine-2-55143.svc.cluster.local on 172.18.0.1:53: read udp 10.244.0.87:41658->172.18.0.1:53: read: connection refused)
```

hmm.. this seems like the DNS listener was not ready?

**Comment by tbarrella** [comment]
This one was failing a lot too https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/26028/integ-pilot-k8s-tests_istio/17422

**Comment by howardjohn** [comment]
Seems to no longer be flaky
