### ISSUE TITLE
regression: cannot set controlPlaneAuthPolicy=NONE

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#25503]
As a result of #25411 its now impossible to set  controlPlaneAuthPolicy=NONE. If you set it in the yaml, it is ignored, because of how the marshalling works where setting a default enum is the same as not setting it.

We can revert this or figure out a way to get around the issue

Easy reproducer:

```diff
diff --git a/pilot/cmd/pilot-agent/config_test.go b/pilot/cmd/pilot-agent/config_test.go
index e5f0dd961a..c7ded1ce96 100644
--- a/pilot/cmd/pilot-agent/config_test.go
+++ b/pilot/cmd/pilot-agent/config_test.go
@@ -30,10 +30,12 @@ func TestGetMeshConfig(t *testing.T) {
        meshOverride := `
 defaultConfig:
   discoveryAddress: foo:123
+  controlPlaneAuthPolicy: NONE
   proxyMetadata:
     SOME: setting
   drainDuration: 1s`
        proxyOverride := `discoveryAddress: foo:123
+controlPlaneAuthPolicy: NONE
 proxyMetadata:
   SOME: setting
 drainDuration: 1s`
@@ -42,6 +44,7 @@ drainDuration: 1s`
                m.DiscoveryAddress = "foo:123"
                m.ProxyMetadata = map[string]string{"SOME": "setting"}
                m.DrainDuration = types.DurationProto(time.Second)
+               m.ControlPlaneAuthPolicy = meshconfig.AuthenticationPolicy_NONE
                return m
        }()
        cases := []struct {
```

**Comment by shamsher31** [comment]
> how the marshalling works where setting a default enum is the same as not setting it.

Not sure why is this behavior, but I'm unclear here because other enum values work fine. eg:

The first element (0) in the enum. 
https://github.com/istio/istio/blob/89c86aff8e721494de3f44b84865a6ede0dae398/pkg/config/mesh/mesh.go#L88

Second element(1) in the enum
https://github.com/istio/istio/blob/89c86aff8e721494de3f44b84865a6ede0dae398/pkg/config/mesh/mesh.go#L103

Forth element (3) in the enum.
https://github.com/istio/istio/blob/89c86aff8e721494de3f44b84865a6ede0dae398/pkg/config/mesh/mesh.go#L97

All have underlying type as `int32`. 

I think there might be some other reason this is not working as expected.

**Comment by JimmyCYJ** [comment]
@shamsher31 Is there an ETA for this issue? We are building 1.7 release this week.

**Comment by costinm** [comment]
How about: 
- deprecate 'controlPlaneAuthPolicy' - the semantic no longer match what it was intended for.
- document the default ( matching code): port 15010 is by default plain text, 15012 is mTLS with DNS certs signed by google, 443 mTLS with DNS certs signed by a platform-trusted 
- add an explicit setting ( can be env variable since it'll likely be mostly for testing) for forcing the behavior - for example ISTIOD_ROOT_CERT - empty for plain text, root bundle otherwise.

Except for tests, we should strongly recommend as best practice using the default ports.

**Comment by costinm** [comment]
Note that 'controlPlane' auth policy is in general not right  - CA may have a different root CA and transport than istiod for example, may use JWT. 

In context of 'central istiod' and the integration with other CAs and services - each component will need its own auth 
policy.

**Comment by costinm** [comment]
One proposal if we can still make api changes: we have discoveryAddress, we can add 'discoveryCACertificates'. 
If discoveryCACertificates is empty (or port==15010), the connection will be plain text.
Otherwise, it should be the ./var/run/secrets/istio... if Istiod runs with its own self-signed certificates ( port 15012), or 
/etc/certs/rootcacerts for cases where istiod is behind a real cert. 

I would make the last as default really, since this is the best long-time experience ( no more patching webhooks needed, friendly for managed cases, etc).
