### ISSUE TITLE
Logging policy id for allowed/denied requests

### ISSUE THREAD

**Issue by rinormaloku** [istio/istio#25618]
**Describe the feature request**
When multiple Authorization Policies are applied to a workload it's very difficult to know which policy denied the request. Currently, by increasing logging level for envoy proxy, with the command below:
```
istioctl proxy-config log `kubectl select pod` \
     --level rbac:trace,http:trace,filter:trace
```
We get some informative logs that the request was rejected, but this has very limited usability.
```
[timestamp]	debug	envoy rbac	[external/envoy/source/extensions/filters/http/rbac/rbac_filter.cc:117] enforced denied
```

Feature Request: Display the name of the policy that rejected the request in the logs. To simplify troubleshooting authorization policies.

**Describe alternatives you've considered**
Currently, there are no alternatives

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by yangminzhu** [comment]
This is something we wanted but didn't find the time to do it so far, super glad that community can help on this. As discussed in the slack, I think @rinormaloku will take this and implement in Envoy.

In Envoy, the current log is printed here https://github.com/envoyproxy/envoy/blob/master/source/extensions/filters/http/rbac/rbac_filter.cc#L117 and I think you just need to update the engine->allowed() to also return the name of the policies making the deny decision when action is DENY. (It's less useful for ALLOW action because it basically means none of the rules are matched)

In Istio, we're already encoding the name and namespace of the Istio AuthorizationPolicy as the rule name of the Envoy RBAC config so that you shouldn't need any changes there.

Last, once you updated the code in Envoy, we will need to sync it back to the envoy-wasm repo and also update the sha in the proxy and istio repo to pick-up the changes you made.

**Comment by rinormaloku** [comment]
Hi @yangminzhu 

I made some changes and want to test those. 
But needed some help how does the syncing back to the envoy-wasm repository work? (for now, I am just copying the same changes over to envoy-wasm and building there)

**Comment by rinormaloku** [comment]
Hi @yangminzhu 

The change is merged in the Envoy proxy repo. 

Is there any process that I need to follow to merge this back into envoy-wasm and then into istio-pilot, or it will be done while other changes are merged from the envoy repo?

**Comment by howardjohn** [comment]
https://github.com/envoyproxy/envoy/pull/12682 envoy binary is automatically pulled in on a weekly basis. Thanks!
