### ISSUE TITLE
Server Identity is not verified if caCertificates are not set when TLS mode is SIMPLE or MUTUAL

### ISSUE THREAD

**Issue by nschhina** [istio/istio#25652]
Currently, with SIMPLE or MUTUAL TLS set, if users don't pass in CaCertificates to verify server identity during TLS handshake to upstream server, no verification is performed by the client. This is documented in API as well as istio.io but a misconfiguration may still bypass the TLS handshake. We should validate the existence of CaCertificates in DestinationRule with TLS when the mode is set to SIMPLE/MUTUAL.

**Comment by nschhina** [comment]
cc: @JimmyCYJ  @myidpt

**Comment by howardjohn** [comment]
We probably cannot just make it required, its a breaking change. But we can have docs all show usage, have an analyzer, etc.

One thing we may want to consider. Putting `caCertificates: /etc/ssl/certs/ca-certificates.crt` kind of sucks. It would be nice to automagically use the system certs if its not specified. If a user wants to have no validation, we can add a new field `InsecureSkipVerify` or similar. This still has the issue of a breaking change but its a less bad one, and we can have a transition release before changing the behavior if we want to give users more time to adapt.

**Comment by myidpt** [comment]
I agree not making it a breaking change. But we can improve docs, add validators to prevent new configs with the issue and implement an analyzer for 1.6 and 1.5 (if 1.5 has analyzer), so that when users upgrade minor versions, they will get notified if the existing config is problematic.

Automatically using the system certs doesn't sound quite right to me. Since this is implicitly changing Envoy config and enlarging the root of trust. Also, though we are using the same images for the sidecars, the CA bundles can have different locations between distros: https://golang.org/src/crypto/x509/root_linux.go. It doesn't sound flexible to hard code the CA cert file location.

**Comment by howardjohn** [comment]
> CA bundles can have different locations between distros 

That is part of the complexity that would be nice to avoid. Its actually not really possible to properly define a Destinationrule with system certs today, because my pods/VMs may all have different location for the certs.

I am not sure why system certs is wrong. This is the default of many http clients (curl, golang). Its clearly better than no verification, which we do today

**Comment by myidpt** [comment]
Yes, it is better than no verification. But we will fix it by blocking DRs without caCertificate defined, via the validator.
For security, will security-sensitive companies choose not to trust the system roots? I'm having concerns. Maybe that's not a big issue since this only happens when users don't define a caCertificate. I'm still open to both choices given the tradeoffs. We can discuss in the WG meeting.

**Comment by nschhina** [comment]
It is a breaking change but only for new DR deployments. And it only breaks insecure instances which imo is not that undesirable. 

I purpose we do this as a two phase change: 
1. Validator will start blocking any such DR starting Release 1.7
2. Analyzer will report this as an error and we can cherrypick that to 1.6 and 1.5(if analyzer exists in 1.5)

**Comment by howardjohn** [comment]
@nschhina the idea is good in theory but in practice its challenging. There is no real way to apply to "new DR"s. For example, if I take my existing code and apply to a new cluster, everything breaks. If I edit 1 unrelated field, suddenly its invalid. Overall changing validation is always a breaking change IMO.

**Comment by nschhina** [comment]
That's what I'm saying but I'd argue- breaking something suddenly that fixes a security vulnerability isn't very undesirable :) Also 1.7 release a good opportunity since we can add this to release notes so people are aware

**Comment by ramaraochavali** [comment]
I agree with @howardjohn - changing validation/enforcing a new validation is a backward incompatible change.

**Comment by rshriram** [comment]
I think the fix is to add an API field that says performCertificateVerification, which if set to true will require a valid path to ca certs. Changing the semantics of a well established API is not correct, specifically when we have explicitly documented semantics that state that it is possible to do TLS without CA verification should the user desire so.

**Comment by nschhina** [comment]
@rshriram we discussed this during security wg meeting yesterday, you can take a look at meeting notes. We concluded to start using system CA certs as fallback as a `opt-in` feature. cc: @costinm  @howardjohn  @costinm

**Comment by rshriram** [comment]
I dont think this falls in security. Destination rule is a networking API, not security API. And this is for traffic to external services, not istio internal services. So, it would be good to discuss this in the Istio networking working group before making any such "opt-in" features.

**Comment by rshriram** [comment]
Here is a compendium of publicly documented examples by our own end users that shows destination rule being used without any CA certs because mounting certs in sidecars is a nightmare.

https://github.com/istio/istio/issues/25450
https://github.com/istio/istio/issues/21914
https://github.com/istio/istio/issues/20154 [```I can't create new certs in istio-proxy container since it is read-only file system.```]
https://github.com/istio/istio/issues/19262
https://stackoverflow.com/questions/56055431/how-to-configure-tls-origination-in-istio

I can go on and on but hopefully you got the point

**Comment by nrjpoddar** [comment]
I don't think the first issue #25450 has anything to do with this.

We can add an API option like @rshriram is suggesting but I would like to either change the "default" in upcoming release 1.7 to use system CA or in 1.8 after giving users time to migrate if needed.

We can bring it up with TOC if we can't reach consensus.

**Comment by nschhina** [comment]
I was under the impression that this was already discussed in networking wg meeting. @costinm  and @howardjohn  were both present from networking in security wg meeting too, but I understand if you think we're missing a full fledged discussion in networking wg meeting. This is not something that should be delayed as 1.7 release is right around the corner, I agree we can escalate to ToC if there's a disagreement to this approach tomorrow. Adding another API field is just an extension to what I already have in my open PRs.

**Comment by nschhina** [comment]
Also it's not like only a small subset of people think this is a security issue- Product Security did a full review of this vulnerability and it scored CVSS 4.9. Recommended steps by product security included disallowing this slowly over time giving people time to migrate.

**Comment by nschhina** [comment]
https://github.com/istio/istio/issues/24667 with a target of 1.8 release will remove any concern people have with mounting secrets to their sidecars anyways

**Comment by nrjpoddar** [comment]
> I was under the impression that this was already discussed in networking wg meeting. @costinm and @howardjohn were both present from networking in security wg meeting too, but I understand if you think we're missing a full fledged discussion in networking wg meeting. This is not something that should be delayed as 1.7 release is right around the corner, I agree we can escalate to ToC if there's a disagreement to this approach tomorrow. Adding another API field is just an extension to what I already have in my open PRs.

I don't think it was discussed in Networking WG but I'm glad John and Costin were made aware of this.

**Comment by duderino** [comment]
@nschhina @myidpt when the release notes get written for this, can you include CVSS 4.9 in the release notes?  That's below our threshold for a security release, but I'd still like to be fully transparent and not present this as a plain bug fix or feature

**Comment by costinm** [comment]
One update: the location of the CA bundle is not really an issue for older versions, since it is a file we include in the image in a well-known location. In future it may be - but we are already planning to move from full paths to 'credential names'.

So my suggestion is to go with the simplest possible solution for 1.7, 1.6, etc:
- add an Istiod config ( env variable - can be set in values.yaml as meta ) like DR_DEFAULT_CA_ROOT
- Pilot will generate config based on the default - but it's opt-in
- recommend users set this - after confirming their DR don't rely on the old behavior.
- we can define a special value "OFF" or "INSECURE" to use instead of the actual file name to indicate user doesn't want to check.

This is not a breaking change - users need to 'opt-in' and they can still handle DR that need the old behavior.

Note that the root CA is not sufficient - SAN check must also be handled.

For 1.8 - yes, we should add an explicit field to the API, and have the default set using a name instead of full path. 
We already use some keys in SDS - we should document them part of the API.

**Comment by rshriram** [comment]
fwiw, we discussed this in detail in the product security wg. Setting defaults like described here was not the recommended solution. Different (popular) tools take different approaches. Envoy has an explicit field for setting ca certs with explicitly documented model of opting into doing tls verification - we are following the envoy conventions here. Secondly, this is an intensely subjective view of things - only some subset of people perceive as vulnerability based on the fact that the docs are "not being read by people". One could apply this argument to everything within Istio :). 

We cannot set the root cert bundle to the thing that is present in the istio-proxy image. We are not actively managing the bundle with all the public certs (tracking revocations, etc.), essentially telling the enterprise user to trust certificates coming directly from some OSS project. We dont give people an easy way to mount the root cert bundles into istio proxy either (the container image is read only).

Finally, even with all the proposed esoteric hacks like env vars, it is still opt-in and the same argument applies ("people dont read docs"). So the status quo does not change. It simply benefits some vendors who know about these options so that they can set some global defaults - to me, this is a bad idea as the vendor now just lost the ability to do TLS without verification (if its happening within the enterprise for some one-off reason). The next thing we know, there is a proposal in dest rule to override the global defaults for CA certs set in some obscure env var, and more docs that "people dont read". :)

**Comment by nschhina** [comment]
This was discussed in networking wg meeting today. Posting notes below:

tl;dr: DR API has caCertificates field. If its not set, we do not verify the server identity. Docs in reference, but not in high level tasks, etc. Most other tools default to secure. Opt in fallback to system certs if not provided
Currently "impossible" to use system certs, as they may be different path on VM/pods, and we specify exact path
Old versions: opt into fallback with env var
New versions: opt out of fallback with InsecureSkipVerify in DR API
Nothing set -> verify with system certs
caCerts set -> verify with caCerts
InsecureSkipVerify -> no verify
Global override is temporary for transition, not permanent api
Open question: do we need to support multiple platforms, or is having cert path hardcoded ok? Short term, long term?
Open question: is InsecureSkipVerify boolean or do we need future proof for different verification types

**Comment by nrjpoddar** [comment]
@nschhina thanks for the summary. You should add notes around "verify" includes verifying SAN by default even if `subjectAltNames` is empty.

**Comment by incfly** [comment]
Talked with @JimmyCYJ . It seems like @nrjpoddar would take over the remaining work, to resolve the API design issues.

/cc @JimmyCYJ

**Comment by nitgeek** [comment]
What happens if we are using SDS? In my scenario, I am able to establish a successful egress connection with Mutual TLS by setting credentialName in the DestinationRule. But istioctl analyze still shows me error that  

> Error [IST0129] (DestinationRule xyz.istio-system) DestinationRule istio-system/xyz in namespace istio-system has TLS mode set to MUTUAL but no caCertificates are set to validate server identity for host: xyz.com at port number:443

But since the handshake is working fine, is there an action we need to take for this error or can this be ignored?

I checked istio.io and found below for credentialName in DestinationRule:
NOTE: This field is currently applicable only at gateways. Sidecars will continue to use the certificate paths.

Could it be that the Gateway is working fine and this error is for other sidecars?

**Comment by williamaronli** [comment]
any update for the caCertificates? @nrjpoddar

**Comment by nrjpoddar** [comment]
Unassigning as wasn’t aware this was assigned to me.

**Comment by aryan-ibm** [comment]
> I don't think the first issue #25450 has anything to do with this.
> 
> We can add an API option like @rshriram is suggesting but I would like to either change the "default" in upcoming release 1.7 to use system CA or in 1.8 after giving users time to migrate if needed.
> 
> We can bring it up with TOC if we can't reach consensus.



> @nschhina thanks for the summary. You should add notes around "verify" includes verifying SAN by default even if `subjectAltNames` is empty.

@nrjpoddar  For mode:Simple also its ignoring SAN from destination rule.

**Comment by jacob-delgado** [comment]
@Kmoneal has been working on this issue with me. We are hoping to show the progress he's been making on this soon.

**Comment by jacob-delgado** [comment]
> > I don't think the first issue #25450 has anything to do with this.
> > We can add an API option like @rshriram is suggesting but I would like to either change the "default" in upcoming release 1.7 to use system CA or in 1.8 after giving users time to migrate if needed.
> > We can bring it up with TOC if we can't reach consensus.
> 
> > @nschhina thanks for the summary. You should add notes around "verify" includes verifying SAN by default even if `subjectAltNames` is empty.
> 
> @nrjpoddar For mode:Simple also its ignoring SAN from destination rule.

This is among the test cases that we are currently evaluating. There are other things, such as making sure egress gateways work as intended, and how ServiceEntry resources also interact with the system. We hope to provide more analysis to get feedback from others in the community.

**Comment by arcivanov** [comment]
I'm going to copy the questions I raised https://github.com/istio/istio/pull/32938#issuecomment-847758969 here:

In re certificate validation there is **always** a question of validation depth as well as other validation parameters. How is this going to be addressed?

1. Are all certificates in the chain required to undergo validation? If the actual chain contains `CA/Intermediate CA/Cert` but caCertificate misses `Intermediate CA` how will the feature behave?
2. How often System CAs Trust is updated? What is the source?
3. Are certs validated via OCPS?
4. Are certs validated via Public CT Logs?

This issue is extremely pressing for exposing public services for VS routing with mesh-external SE and a DR with TLS SIMPLE. The certificates in question in this scenario are not controlled by the user and maintaining the public trust is an enormous administrative burden, considering public sites can switch CAs at any time and for any reason. Finally, the public site you don't control is the only scenario reasonably susceptible to cert-based MTM attack as if you control all the sites involved and the DNS, the MTM is rather diminished.

This is starting to smell like a CVE-level feature lapse...

**Comment by arcivanov** [comment]
Just to provide a further insight on the level of complexity, here's the list of tunables from NGINX (https://nginx.org/en/docs/http/ngx_http_ssl_module.html, https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_ssl_certificate) that all deal with incoming connections only:

1. TLS/SSL protocols.
2. TLS/SSL ciphers.
3. CLR.
4. OSCP stapling and verifiation.
5. DH params and EC curve params.
6. Verification depth.
7. TLS 1.3 early data.
8. Session caching and tickets and their encryption which may or may not cause PFS breakage and require ticket rotation.

**Comment by ngtuna** [comment]
I hit this issue too. My istio-ingressgateway refused to talk to upstream service which is out of mesh via TLS SIMPLE mode. Here is my setting for the upstream:

```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: ***
  namespace: istio-system
spec:
  host: "***"
  trafficPolicy:
    tls:
      credentialName: "wildcard-tls"
      mode: SIMPLE
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: ***
  namespace: istio-system
spec:
  hosts:
    - "***" // same host with above DR
  location: MESH_EXTERNAL
  ports:
    - number: 443
      name: https
      protocol: TLS
  resolution: DNS
```

Istioctl analyze complains:

```
Error [IST0128] (DestinationRule ***) DestinationRule *** in namespace istio-system has TLS mode set to SIMPLE but no caCertificates are set to validate server identity for host:***
```

**Comment by ngtuna** [comment]
Side question: is it required to have dedicated egressgateway to reach outside-of-mesh upstream?

**Comment by chadlwilson** [comment]
> Side question: is it required to have dedicated egressgateway to reach outside-of-mesh upstream?

@ngtuna This is probably a better question for the Istio Slack or discuss.istio.io rather than some random Github issue, however it's not _required_ to use an egressgateway. It's just that depending on the mitigations in the rest of your setup, forcing traffic out via an egressgateway can give additional security guarantees on top of what is possible if you allow direct sidecar egress TLS origination. https://istio.io/latest/docs/ops/best-practices/security/#securing-egress-traffic

Also, if it is a server protected with a cert from a regular public CA, you can verify the certs by using the built-in certs in the proxy, i.e with
```yaml
# snip
  trafficPolicy:
    tls:
      mode: SIMPLE
      caCertificates: /etc/ssl/certs/ca-certificates.crt
```

**Comment by arcivanov** [comment]
> ```yaml
> # snip
>   trafficPolicy:
>     tls:
>       mode: SIMPLE
>       caCertificates: /etc/ssl/certs/ca-certificates.crt
> ```

Is this actually available? How often is the trust refreshed?

**Comment by arcivanov** [comment]
Answering my own question, yes they are present in 1.8.x and in 1.10.x.

**Comment by chadlwilson** [comment]
> > ```yaml
> > # snip
> >   trafficPolicy:
> >     tls:
> >       mode: SIMPLE
> >       caCertificates: /etc/ssl/certs/ca-certificates.crt
> > ```
> 
> Is this actually available? How often is the trust refreshed?

@arcivanov Totally reasonable question. Based on my research, trust as refreshed as often as the Istio images are rebuilt **and** upstream Debian `ca-certificates` packages are updated.

* **non-distroless** images `apt-get install ca-certificates && update-ca-certificates` in https://github.com/istio/istio/blob/ada8c49dd6ead37321fcd736575ec363d24a0eda/docker/Dockerfile.base#L10-L12 (run **every image build** off latest `ubuntu:focal`). At time of writing, this would be [`20210119~20.04.1`](https://packages.ubuntu.com/focal-updates/ca-certificates) based off the Debian `bullseye` package; presumably.
* **distroless** images from `gcr.io/distroless/base` which is unpackaing certs from upstream debian 10 (`buster`) package in https://github.com/istio/distroless/blob/e13e2e0b9d1c5ee4887241514b350803e7a5b70c/base/base.bzl#L14-L17 Note that there is a comment about "we should run update-ca-certificates" in the upstream Google distroless code. At time of writing, I believe this would be [`20200601~deb10u2`](https://packages.debian.org/buster-updates/ca-certificates), so older.

After doing a diff of the CA certificates included in `proxyv2:1.9.6` and comparing non-distroless vs. distroless, it seems at first glance that the differences are just the **distroless** images not reflecting more recent changes to root CAs, probably due to the package version, so missing things [like this](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/NSS_3.54_release_notes). I have raised this for discussion at https://github.com/GoogleContainerTools/distroless/issues/753 but I am sure the process is complex, messy and deep, given it's at the heart of trust on the Internet. Debian 11 will be properly out soonish, so when distroless updates I suppose the discrepancy will be further reduced.

Obviously this does not constitute security advice to the masses, however my feeling is that if you are updating regularly; you will be pulling CA certs for both images; but seemingly more recent on **non**-distroless images due to their Ubuntu Focal base, rather than Debian 10. Depending on your risk profile, this might be adequate - or at the very least better than you having to maintain your own, especially if your system needs to allow relatively wide TLS egress to servers on the Internet which may use various CAs to sign.

**Comment by ryantking** [comment]
@Kmoneal @jacob-delgado Alright pushing this back to 1.12?

**Comment by Kmoneal** [comment]
> @Kmoneal @jacob-delgado Alright pushing this back to 1.12?

That's okay with me

**Comment by jacob-delgado** [comment]
Closed by https://github.com/istio/istio/pull/33472
