### ISSUE TITLE
Wasm Telemetry 1.7: provide latency/cpu/memory data

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#25768]
Wasm telemetry is enabled in 1.7 builds to get test and stability mileage.

Provide latency, stability, cpu and memory data of this experiment.
Based on the results we will continue the new defaults or switch back to null vm.

Add release notes based on the outcome.

**Comment by bianpengyuan** [comment]
Seems like this issue is only about gather data for Wasm telemetry v2 vs Nullvm? I believe the data is already gathered and we decided to not ship it as default by 1.7 due to elevated memory (increased by 50%). I will close this, we can create a new issue to track performance optimization for Wasm extensions.
