### ISSUE TITLE
Upgrade alpha CNI dependency

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#25847]
```
github.com/containernetworking/cni v0.7.0-alpha1
```

is current version used. We should probably be on a stable version. I tried to upgrade but got all sorts of failures

cc @stewartbutler @bcheung

**Comment by bcheung** [comment]
I can take a look

**Comment by howardjohn** [comment]
I should mention this is pretty low priority, just something I noticed. Ideally we aren't depending on alpha versions

**Comment by bcheung** [comment]
I upgraded `github.com/containernetworking/cni` to `v0.7.0` and fixed an error due to [this change](https://github.com/containernetworking/cni/pull/578). All tests pass, but I checked the releases and noticed that all versions following `v0.7.0-alpha1` use CNI spec `v4.0.0` which replaces the `GET` command with `CHECK`: https://github.com/containernetworking/cni/pull/579 

It seems like Istio CNI still uses CNI spec `v0.3.1` but the `GET` command isn't implemented at all: https://github.com/istio/istio/blob/d110604aabdd4204829005634652928c92aabc3b/cni/cmd/istio-cni/main.go#L262-L266

Would this be a safe upgrade?

Also, upgrading to `github.com/containernetworking/cni v0.7.1` may also require upgrading `github.com/containernetworking/plugins v0.7.3` (which is the current version) to [`v0.8.0`](https://github.com/containernetworking/plugins/releases/tag/v0.8.0) or later to support CNI spec `v4.0.0`.

**Comment by stewartbutler** [comment]
Oh, very interesting -- the mechanics of CHECK may remove the need for the cni validation init container. We'll need to experiment with this a bit. If we implement a CHECK call that properly checks the pod internal iptables and terminates the pod if unhealthy, that may remove the need for the repair container (See https://github.com/containernetworking/cni/blob/spec-v0.4.0/SPEC.md). It may even fix the race condition entirely, depending on how k8s reacts to chained CNI plugins. I'd need more time to investigate than I can devote now, but it just moved way up in priority for me.

@howardjohn The change to CNI spec `v4.0.0` is going to be a big enough change that I think it may require a decent chunk of rewriting of CNI. Would you object to us deferring this until 1.8 (or 1.9 depending on time budget)? We definitely need to adopt this and do some experimentation, but I don't want to distract from the other efforts to move CNI to beta in 1.7. 

@bcheung As stated, I'd prefer to defer this. It looks like the side effects of the upgrade may be a lot more complicated than they seem at first glance. Good catch on calling it out.

**Comment by howardjohn** [comment]
@stewartbutler no concerns here, I merely saw we were using an alpha version which "feels" wrong - but not actually causing issues. I didn't realize the extent of the changes.

**Comment by howardjohn** [comment]
@stewartbutler the CHECK calls seems optional and called at any time during the lifecycle. Did you see anywhere that guarantees the 

* CHECK will be called regularly
* CHECK will evict a failing pod

Its sort of implied but I didn't see anything explicit?

**Comment by howardjohn** [comment]
not stale

**Comment by howardjohn** [comment]
not stale

**Comment by howardjohn** [comment]
not stale

**Comment by bianpengyuan** [comment]
Check is called immediately after add, so it is not going to help with the race.
