### ISSUE TITLE
"make" should work and not put linux binaries on a mac's path

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#2594]
make produces and install into my ~/go/bin linux executables while I'm on a mac - this is completely useless and unexpected (I end up with an "istioctl" I can't execute...)

(if some weird hack is needed in circle ci, use "make circleci" for circleci but don't put the wrong architecture binaries in my path)

**Comment by ldemailly** [comment]
cc @hklai

**Comment by ldemailly** [comment]
https://github.com/istio/istio/blob/master/bin/gobuild.sh#L32 should stay unset and it would just work

**Comment by hklai** [comment]
cc @mattdelco We were just talking about this yesterday.

**Comment by mattdelco** [comment]
I'm assuming this was done with the docker images in mind and someone would point out that it can be overridden (I'm not sure on why := or ?= wan't used).  The release build needs to cross-compile istioctl for 3 platforms and this doesn't work well with a single bin/ directory.  I'm used to arch-specific bin directories in builds and I've asked for opinions about whether it'd be alright to do multiple bin/ directories (e.g., bin/$GOOS, or bin-$GOOS/).  A possible concession is to try to allow the native OS to get "bin/".  So  far nobody's offered their opinion or preference.

**Comment by ldemailly** [comment]
why not leave the env var unset by default (so no cross compiling by default) and 
then build can just invoke it 3 times with 3 GOOS= set to different settings 
(and a different OUT / $1 too)

**Comment by ZackButcher** [comment]
I like `bin/$GOOS` with the native OS binaries going to `$GOPATH/bin`.

However, the default `make` command shouldn't build for all three platforms, it should build for the native OS only. CI can be changed to use specific make targets for each OS much more easily than developers can remember to do `make $GOOS`.

**Comment by ldemailly** [comment]
ps see above but ./bin/ should not be used as it's full of source files
all output from build should go to some single prefixed directory like `./build-out/` by default (and in theory that destination/staging directory should be configurable as I should be able to build from source mounted as readonly fs)

**Comment by mattdelco** [comment]
by bin/ I was generically referring to something like ISTIO_BIN in the Makefile, which from the base of istio source is something like ../../../bin/.

I do keep readonly source in mind (and which istio was better suited for it).  A use case I've used in the past is mounting source from one system to another (to cope with lack of cross-compilation support), though that use case is also what gives me hesitation to let native OS binaries go to /bin because the native OS can change for a mounted tree.

The build might be a bad example.  It builds on linux and the only thing that cross-compiles is for istioctl, and that one gets built using different names so that'd be a potential way to avoid different arch directories.

A better example is perhaps being on a Mac and trying to build everything.  On the one hand make needs to build Mac versions of the go executables for you to run natively, but then to build the docker images it might need to build the go images for linux (though honestly I'm unsure about whether on Mac the docker images are for Mac or Linux [and if the "FROM ubuntu" images get built okay on Mac or just break]).

**Comment by mattdelco** [comment]
PR #2831 helps with this though I don't know if it's sufficient to close this issue

**Comment by sakshigoel12** [comment]
@hklai please assign this issue if it is still a P0

**Comment by hklai** [comment]
I think this has already been resolved and I have no problem building on both mac and linux.
