### ISSUE TITLE
Configure timeout per WASM filter

### ISSUE THREAD

**Issue by marcusschiesser** [istio/istio#26103]
**Describe the feature request**

Envoy allows specifying a [timeout for listeners](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/listener.proto). Similar, it would be good if we could specify a timeout for each WASM filter individually (not just for the whole filter chain at once).

There are filters that should never timeout (e.g. if a policy must be enforced) and some filters are optional (e.g. additional telemetry filters) - these can have a lower timeout value.

Should it be not possible to completely disable the timeout, then at least it should be possible to specify whether to not continue the filter chain if a policy filter times out. (Similar to the `continue_on_listener_filters_timeout` setting from Envoy). 

**Describe alternatives you've considered**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by bianpengyuan** [comment]
I think any async operation (basically callout or file read) in Envoy filter could and should have a timeout configured. Besides async operation all other filter logic should be non-blocking, thus I cannot think of a case this filter level timeout is necessary. Do you have an example use case?

This applies not only Wasm filters, but also generally other filters. Also if you think this is really valid use case, this should be an issue filed in Envoy instead of Istio.

**Comment by marcusschiesser** [comment]
@bianpengyuan A good use case might be Istio's own [metadata](https://github.com/istio/proxy/tree/4bf5d18e2eca27ab4742c6e30b8093665bbcd297/extensions/metadata_exchange) filter. As far as I tested, if this filter is not running, then Kiali doesn't report the endpoints correctly (internal traffic is coming from `Passthrough Cluster`). So it would be good to ensure that this filter is always called with an individual timeout of `0`.

**Comment by bianpengyuan** [comment]
Not sure I follow. Metadata exchange is non-blocking, and the current behavior is already that every filter has no timeout (which is what you mean by setting timeout 0 means I guess?). To make this FR valid, there needs to be some use case that a filter must set to have limited time to process the requests, and I cannot find any.

**Comment by marcusschiesser** [comment]
Looks to me like it's possible to configure Envoy's `listener_filters_timeout` via Istio's [ProtocolDetectionTimeout](https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig), see:
https://github.com/istio/istio/blob/370f75e8c57487d0c77205b59966726d0548642a/pilot/pkg/networking/core/v1alpha3/listener.go#L2177

Istio seems to send a value of `"listenerFiltersTimeout": "0.100s"` to Envoy per default. 

From what I observe, this leads to that Metadata exchange is not called under heavy load which can be prevented by setting `ProtocolDetectionTimeout` to `0`. But we might want to always call Metadata exchange, as it prevents the above mentioned bug in Kiali whereas for some other filters (having async operations as you mentioned) we want to configure a timeout.

Hence, I think it's a good idea to configure the timeout individually per filter instead for the whole filter chain.

**Comment by bianpengyuan** [comment]
No, this has nothing to do with metadata exchange. Take a look at https://github.com/istio/istio/issues/24379, it has more context in it.

Basically what happens is that with 1.6 we added proto detection timeout at outbound listener to work around this issue: https://github.com/istio/istio/issues/16458. So for an outbound listener, we have a HTTP filter chain which has HTTP metadata exchange, and a backup Passthrough filter chain when protocol detection times out. As you observed, the default outbound timeout was set to 0.1s, which is too short and would cause some http request misclassified as TCP connection by the listener if client is too slow or under heavy load. To avoid this, you'd either increase detection timeout to infinity (like what you did with setting it to 0) if you don't have traffic using server first protocol in your cluster, or disable proto sniffing if you don't have same port used by TCP and HTTP service.

in 1.7 and next 1.6 release, the default listener timeout has been raised to 5s, and long term fix in order to set listener protocol detection timeout to infinity will be introduced by 1.8.

**Comment by marcusschiesser** [comment]
> in 1.7 and next 1.6 release, the default listener timeout has been raised to 5s, and long term fix in order to set listener protocol detection timeout to infinity will be introduced by 1.8.

Will this also affect custom WASM filters? From what I observed if I set `ProtocolDetectionTimeout` to `0` my custom WASM filters are also always called and they never time out.

This was actually the intent of my feature request. I have some filters that I want to make sure that they are called and some filters where it's ok if they are not be called. So setting individual timeouts per filter sounds like a good idea to me.

**Comment by bianpengyuan** [comment]
`ProtocolDetectionTimeout` only affects **listener filters**  (tls inspector, http inspector). It is meaningful for listener filters, because they could block connections. However, http/network filter, which Wasm filter belongs to, should never block connection or request indefinitely, thus there is really no value to add timeout for them.

Anyway, if this is still a needed feature for you with valid use case, please consider open an issue in envoyproxy/envoy repo. After envoy adds this feature, Istio will pick it up and then you can configure it accordingly with Istio API. I am going to close this issue as this should be categorized as an Envoy FR. thanks!

**Comment by marcusschiesser** [comment]
@bianpengyuan Thanks for explaining this in detail. What I don't understand then is why my WASM filter (very simple one just adding a request header) is under load sometimes not called, but if I set `ProtocolDetectionTimeout` to `0` it will be always called. Seems to me that `ProtocolDetectionTimeout` also affects HTTP filters.

**Comment by bianpengyuan** [comment]
There are two filter chains, HTTP filter chain and TCP network filter chain. You filter was part of HTTP filter chain, but not on TCP network filter chain. `ProtocolDetectionTimeout` controls timeout of http inspector, which is listener filter and happens before any filters on those two chain. It sniffs the traffic and makes decision on whether incoming stream is a http request or a TCP connection.

The default protodetectiontimeout was 0.1 sec (we recently raise it to 5s). When under load, it could take more than 0.1s for bytes to be received by the proxy, when a timeout happens, the inspector will treat the incoming connection as a TCP connection and process it with TCP network filter chain. Thus your filter is bypassed.

**Comment by marcusschiesser** [comment]
@bianpengyuan thanks a lot, great explanation. Now everything is clear. I guess then with raising the timeout to 5s our problem will be solved. We will then force it to 5s for older Istio 1.6 versions too.
