### ISSUE TITLE
tools/certs '*** No rule to make target `clean'.  Stop.'

### ISSUE THREAD

**Issue by esnible** [istio/istio#26541]
The certs Makefile should be location independent.

The _tools/certs/Makefile_ does `@make clean`.  It is supposed to be a call into the clean target of the current Makefile.

This uses the Makefile in the current directory.  It means the Makefile cannot be run using `make --makefile $ISTIO_DIR/tools/certs/Makefile <target>`

I suspect this is an easy fix, replacing `@make clean` with `@make --makefile $(realpath $(firstword $(MAKEFILE_LIST))) clean` **or** perhaps `clean` can be a dependency of the step the needs to clean.

**Comment by bmuscede** [comment]
@johnma14  It looks like this issue was fixed from PR #27186. Instead of using a `@make clean` inside the *tools/certs/Makefile*, we now have a direct call to `rm -rf` which is independent of `clean`.

There was also an issue with the `help` target, but that was also fixed in the PR mentioned above.

**Comment by johnma14** [comment]
@bmuscede thank you for verifying this. I will go ahead and close this as fixed for now.
