### ISSUE TITLE
How to connect different Envoy filters to a specific gateway?

### ISSUE THREAD

**Issue by ceastman-ibm** [istio/istio#26584]
**Describe the feature request**
Allow the following envoy filter to be applied to a specific gateway. I have two gateways defined, the gateways are defined with certain hostnames and ssl secrets each. I need to be able to have a different envoy filter applied to the individual gateway.

**Describe alternatives you've considered**

apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: envoy-filter-{{ $.Release.Namespace }}
  namespace: istio-system
  labels:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
    heritage: tiller
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          sni: hostname.com
          filter:
            name: "envoy.http_connection_manager"
    patch:
      operation: INSERT_BEFORE
      value: # lua filter specification
        name: envoy.lua
        config:
          inlineCode: |
            function encodeChar(chr)
              return string.format("%%%X",string.byte(chr))
            end

            function encodeString(str)
              local output, t = string.gsub(str,"[^%w]",encodeChar)
              return output
            end

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**
istioctl version
client version: 1.6.8
control plane version: 1.6.8
data plane version: 1.6.7 (393 proxies), 1.6.8 (156 proxies)

kubectl version 
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.7", GitCommit:"b4455102ef392bf7d594ef96b97a4caa79d729d9", GitTreeState:"clean", BuildDate:"2020-06-17T11:39:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9+IKS", GitCommit:"dbe4e8a5c169e0a6a8a9b7b183561fa61e161985", GitTreeState:"clean", BuildDate:"2020-07-16T01:30:57Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

IBM cloud managed istio

**Comment by esnible** [comment]
EnvoyFilters have a `workloadSelector` to target specific pods.  In your case you have two Istio `Gateway` resources on the same pod so that won't help.

I suspect you can get the behavior you want using [`.configPatches[].match`](https://istio.io/latest/docs/reference/config/networking/envoy-filter/#EnvoyFilter-EnvoyConfigObjectMatch) to target a particular `route`.  I haven't attempted this ... to construct the `match` requires a detailed understanding of the internal structure of Envoy configuration.

I suspect you aren't the only user who wants such a feature.  It would be good for the Istio team to work up a tutorial showing how to do this.  I will tag this issue as `docs` and `UX` to track this idea.

**Comment by razvanim-uipath** [comment]
Is there any update on this feature request?

**Comment by dbg-raghulkrishna** [comment]
any update on this?

**Comment by kevinlmadison** [comment]
hey I found this issue while trying to solve the same problem, I think this is what we're looking for:
https://istio.io/latest/docs/reference/config/networking/envoy-filter/#EnvoyFilter-RouteConfigurationMatch
