### ISSUE TITLE
ingressgateway OOM with outbound config

### ISSUE THREAD

**Issue by liuzheng** [istio/istio#26687]
**Bug description**
with thounds outbound configs insert, the ingressgateway OOM, when I check the /config_dump, lots **outbound**!

[ ] Docs
[ ] Installation
[X] Networking
[X] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
NO outbound config in the ingressgateway, that is for egressgateway.

**Steps to reproduce the bug**
same like https://github.com/istio/istio/issues/26060

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
client version: 1.7.0-rc.3
control plane version: 1.7.0-rc.3
data plane version: 1.7.0-rc.3 (1 proxies), 1.7.0-rc.1 (1 proxies)

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:35:15Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-17T11:33:59Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by hzxuzhonghu** [comment]
Currently pilot push all clusters and endpoints to gateways (checking the release-1.7 ).  But I remember @vikaschoudhary16 has done some optimization by reducing unrelated services.

**Comment by hzxuzhonghu** [comment]
Can you enable this env `PILOT_FILTER_GATEWAY_CLUSTER_CONFIG` and test again?

**Comment by hzxuzhonghu** [comment]
#20124

**Comment by liuzheng** [comment]
yes, set `PILOT_FILTER_GATEWAY_CLUSTER_CONFIG="true"` in istiod will fix it, but I think it must be set by default.

**Comment by hzxuzhonghu** [comment]
There are some concerns if you read through the comments

**Comment by liuzheng** [comment]
In my option, each `istio/proxyv2` container have `--serviceCluster` args, why not use this to distinguish each containers' role?

**Comment by rglyons** [comment]
hello!

I am still seeing this issue in my environment, even when `PILOT_FILTER_GATEWAY_CLUSTER_CONFIG="true"` is set in the istiod env. The ingressgateway pods in the istio-system reach their resource limit of 1Gi and then die with OOMKilled.

Here's the istiod env - 
```
    Environment:
      REVISION:                                     default
      JWT_POLICY:                                   third-party-jwt
      PILOT_CERT_PROVIDER:                          istiod
      POD_NAME:                                     istiod-77955b5b9c-88p8j (v1:metadata.name)
      POD_NAMESPACE:                                istio-system (v1:metadata.namespace)
      SERVICE_ACCOUNT:                               (v1:spec.serviceAccountName)
      PILOT_FILTER_GATEWAY_CLUSTER_CONFIG:          true                    # <-- proposed solution
      PILOT_TRACE_SAMPLING:                         1
      PILOT_ENABLE_PROTOCOL_SNIFFING_FOR_OUTBOUND:  true
      PILOT_ENABLE_PROTOCOL_SNIFFING_FOR_INBOUND:   true
      INJECTION_WEBHOOK_CONFIG_NAME:                istio-sidecar-injector
      ISTIOD_ADDR:                                  istiod.istio-system.svc:15012
      PILOT_ENABLE_ANALYSIS:                        false
      CLUSTER_ID:                                   Kubernetes
      CENTRAL_ISTIOD:                               false
```

and the istiod image -
```
Image:         docker.io/istio/pilot:1.6.12
```

There are ~3000 pods on the k8s cluster that have sidecars, and thus the outbound config that is pushed to the ingressgateway is huge. It doesn't seem like this env setting is resolving the issue. Have I missed some step(s)?

I also tried applying a Sidecar with a workloadSelector to the ingressgateway, but this didn't seem to resolve the OOMKilled issue either.

Thanks in advance!

**Comment by liuzheng** [comment]
@rglyons 
Could you pls show me your `VirtualService`, `Sidecar`, `ServiceEntry` example.

**Comment by rglyons** [comment]
@liuzheng there are about 3000 VirtualServices on the cluster across 500+ namespaces, and each namespace has a Sidecar that limits the cluster size to only what's relevant to that namespace. I don't think those VirtualServices/Sidecars are relevant to the ingressgateway, since it doesn't forward traffic to any of them, but please correct me if I am wrong in that assumption.

Only a few of these 3000 VirtualServices are relevant to  the ingressgateway. I am running a multi-cluster mesh, and therefore I need to run the ingressgateway in `sni-dnat` mode, but there are only a few services on the cluster that the ingress needs to forward traffic to.

Is there a way to limit the cluster that's pushed to the ingressgateway to _only_ those few services that the ingressgateway needs to forward traffic to? This is already being done for `standard` ingressgateways, but `sni-dnat` gateways end up receiving the entire cluster from istiod/pilot [here](https://sourcegraph.com/github.com/istio/istio@release-1.6.11-patch/-/blob/pilot/pkg/networking/core/v1alpha3/cluster.go#L126).

I tried applying a Sidecar like this
```yaml
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: ingressgateway
  namespace: istio-system
spec:
  egress:
    - hosts:
        - istio-system/*
        - svcA/*
        - svcB/*
  workloadSelector:
    labels:
      app: istio-ingressgateway
      istio: ingressgateway
```
to the ingressgateway, but found [this line of code](https://sourcegraph.com/github.com/istio/istio@release-1.6.11-patch/-/blob/pilot/pkg/model/context.go#L655) that seemingly ignores any Sidecar config for ingressgateways.

**Comment by liuzheng** [comment]
@rglyons have you see this https://github.com/istio/istio/issues/26060 , your version may have the bug, please try to upgrade.

**Comment by rglyons** [comment]
@liuzheng that memory optimization may relieve some of the pressure, but the problem of pushing the entire istio cluster to the ingressgateway when it is operating in SNI mode still exists. There will always be some upper bound for memory usage when using SNI mode.

As I understand it, the ingressgateway only needs to know about a sub-cluster, namely the backend services that expect ingress traffic from the ingressgateway. Doesn't this mean that the ingressgateway can respect a Sidecar config, instead of always ingesting the entire istio service cluster? This would vastly reduce the memory usage by the ingressgateway while allowing us to still use SNI mode.

The only other alternative that I seem to have is to use standard mode on my ingressgateway and abandon the multi-cluster mesh setup that requires SNI mode to be used.

**Comment by liuzheng** [comment]
@rglyons you are right, this is just a workaround.
when actually have so many configs, it still OOM.
all white/black list based system have that issue.
I think we couldn't fix it perfect, just find the workaround.
