### ISSUE TITLE
Connection to nats.io failing when upgrading to 1.7.0

### ISSUE THREAD

**Issue by dave08** [istio/istio#26749]
**Bug description**

I upgraded from 1.6.8 to 1.7.0 and suddenly started seeing some pods that need to register with an instance of nats.io (which doesn't have a sidecar yet), and they fail... are there any changes that might explain this, or maybe I didn't upgrade properly (those failing pods restarted tons of times, so they were already restarted together with their envoy proxy...).

Nats' service didn't have a name to specify the protocol and it seems like Istio couldn't detect it. It seems to also happen with Postgresql db connection (through pgbouncer).

[ ] Docs
[X] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

The microservice should be able to register with nats.

**Steps to reproduce the bug**

I think ever since the upgrade to 1.7.0 from 1.6.8, after having restarted all the pods in an auto injection setup on one namespace, and Nats doesn't have a sidecar and is in another namespace w/o injection.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

client version: 1.7.0
mixer version: 1.6.8-5bf4ade4e4ba40977a1bcacc07740631fb56a099
pilot version: 1.7.0
data plane version: 1.7.0 (11 proxies)

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-16T14:19:25Z", GoVersion:"go1.13.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9", GitCommit:"4fb7ed12476d57b8437ada90b4f93b17ffaeed99", GitTreeState:"clean", BuildDate:"2020-07-15T16:10:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**

Using istioctl manifest generate and kubectl apply

**Environment where bug was observed (cloud vendor, OS, etc)**

Digital Ocean Kubernetes cluster

**Comment by howardjohn** [comment]
Aha, figured it out. I was super confused why this changed from 1.6.8 to 1.7.0. The reason is https://github.com/istio/istio/pull/25954 is merged to the 1.6 branch but will not be released until 1.6.9. cc @bianpengyuan 

@dave08 the reason this fails is we do protocol detection to figure out the protocol: https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/#automatic-protocol-selection.

Nats and postgresql are server first protocols, meaning the client does not send the first bytes, so we cannot sniff them. Instead, we have a timeout, which will ensure that after Xs of failed sniffing we fallback to TCP. This timeout was too low and impacting the correctness of HTTP traffic, so it was raised. In 1.8 we are going to remove it while making some additional changes to improve the UX around this.

The correct way to fix this is to explicitly declare the protocols as TCP

**Comment by dave08** [comment]
Thanks for looking into this @howardjohn ! But some deployments really can't have their protocol names tweaked... That's the problem with Helm abstractions! But I can throw in an annotation... maybe this could be configured with an annotation too?

**Comment by howardjohn** [comment]
Closing this as working as expected. We have no plans to add annotation for this, as k8s added a first class AppProtocol exactly for this - docs are in the link above. Thanks @dave08
