### ISSUE TITLE
Operator API: make `istiod` an alias for `pilot`

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#27013]
Anywhere we use `pilot` (ie in components and values) we should have an alias for `istiod` to reduce confusion while not breaking compatibility.

cc @ostromart I have heard this brought up a few times

**Comment by shamsher31** [comment]
There are a lot of reported issue due to this confusion eg: https://github.com/istio/istio.io/issues/7469

I worked on a couple of PRs to use `istiod`
https://github.com/istio/istio/pull/25313, https://github.com/istio/istio.io/pull/7481, https://github.com/istio/istio.io/pull/7356, https://github.com/istio/istio.io/pull/7354
