### ISSUE TITLE
How critical envoy/istio-proxy metrics in service mesh

### ISSUE THREAD

**Issue by dinesh4747** [istio/istio#27029]
This issue is more of a guidance - We are running heavily istio mesh on all our container workloads in production and with envoy being a primary component in routing traffic for application container and sends data to other mesh pods like mixer... etc

If the answer is yes then we need our metrics system to be scaled as equivalent to scraping all the application containers and other mesh pods?

Question here whether it's highly critical and mandate to have envoy Prometheus metrics and what is the major advantage off it ?

**Comment by bianpengyuan** [comment]
To make sure I understand, are you asking about istio standard metrics (e.g. istio_requests_total, etc) generated by istio proxy with telemetry v2, or are you actually talking about envoy native stats?

Your mention of mixer makes me think that you are not using telemetry v2 and actually asking about Envoy native stats.

**Comment by dinesh4747** [comment]
@bianpengyuan - Yes we are still using mixer and yet to move to telemetry-v2 

And yes I was referring to envoy native metrics ? And whether it's really critical to have and in which way it helps

**Comment by bianpengyuan** [comment]
Envoy stats is mostly useful to track and debug low level Envoy issue, such as connectivity, or connection lifecycle issue etc, and by default only a small subset of Envoy stats is exposed due to performance overhead from Envoy stats system, and you will need add annotation now to expose more stats: https://istio.io/latest/docs/ops/configuration/telemetry/envoy-stats/.

So most of time it won't be as useful as standard metrics, and it definitely not critical for any features or any integration with other system like kiali. However, please note telemetry v2 has migrated away from Mixer and generate istio metrics directly in istio proxy, so you probably need to scale your monitoring system anyway in the future if you are going to upgrade to a version without Mixer (1.8+).

**Comment by bianpengyuan** [comment]
@dinesh4747 I think the question has been answered here. Let me know if you have further questions. Also please consider visiting https://discuss.istio.io for questions on using Istio in the future. Thanks!
