### ISSUE TITLE
Istioctl x remove-from-mesh should not add the no-inject annotation after uninjecting a deployment

### ISSUE THREAD

**Issue by tariq1890** [istio/istio#27135]
**Bug description**

We are trying to use Istioctl x add-to-mesh and remove-from-mesh in scenarios where auto-injection is disabled. The current logic in remove-from-mesh does not take that into account. To replicate this issue, do the following

i) `istioctl x add deploy <foo_deploy> `
ii) `istioctl x rm deploy <foo_deploy>`
iii) Not try `istioctl x add deploy <foo_deploy>`  again; it fails as the no-inject annotation was added

cc @esnible 

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by esnible** [comment]
Do we want this?

This works well with the auto-injector.  By adding the annotation, the pods get restarted without a sidecar.

I like the existing behavior.  What is your scenario requiring this to change?

**Comment by tariq1890** [comment]
We want to be able to inject and uninject. 

The current flow is a bit awkward tbh. you add and then remove only to find yourself never being able to add again

**Comment by esnible** [comment]
`remove-from-mesh` is for making sure a deployment is not part of the mesh.
We have `istioctl x kube-uninject` which removes the injected stuff.  I never use it, so I can't tell how well it does its job.
Typically I keep the simple .yaml around, and `istioctl kube-inject` into a temporary file.  I don't modify my originals, because I want to be able to change Istio settings and regenerate.

**Comment by esnible** [comment]
Should we get rid of `add-to-mesh`/`remove-from-mesh`?  My original intention was to merely toggle the annotation, to let troubleshooters see which Deployments were failing when the sidecar was attached, instead of using `kubectl patch` with a complicated JSON patch.  It may be that these commands are too close to `kube-inject`/`kube-uninject` to be documentable?

We can also try to make them refuse to work in namespaces that aren't set up for injection.

Thoughts?

**Comment by tariq1890** [comment]
Sure. I am ok with it being removed. We are not looking to use those feature as of now
