### ISSUE TITLE
istioctl proxy-config log should have an argument to accept label selectors

### ISSUE THREAD

**Issue by tariq1890** [istio/istio#27490]
**Describe the feature request**

I use `istioctl proxy-config log <pod-name.ns> --level debug` to set envoy logging levels to specific pods. Remembering pod names or fetching them though kubectl get pods is a bit inconvenient. It would be nice to set the logging level of all pods corresponding to a particular label selector. This would greatly improve the UX

**Describe alternatives you've considered**

Currently I am using kubectl get pods jsonpath and `xargs`ing that to `istioctl proxy-config log`

`istioctl` 

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
I think you can use services or deployment now. Like `istioctl pc l deployment/httpbin.default`. Is that sufficient?

@esnible 

This is just in master btw

**Comment by esnible** [comment]
@tariq1890 John is correct, we have `istioctl pc deployment/httpbin` and it is in master.  (However there is a bug in the version in master, we are trying to get the fixed merged ... currently the namespace must be explicit).

**Comment by tariq1890** [comment]
I don't think adding a subcommand for `deployment` or `service`  is ideal. What if we want to enable debug log for pods that belong to a `DaemonSet`, `ReplicaSet` or a `Job`. 

I believe having a label selector would cover all of these use cases

**Comment by esnible** [comment]
@tariq1890 The new feature in 1.8 is the use of the _kubectl_ libraries to enable <type>/<name>.  It will work with DaemonSet, ReplicaSet, and Job.

What is missing in 1.8 is that we have currently implemented this so that a pod is picked "at random" if there is more than one match.  For `istioctl proxy-config log` it makes sense to set the log level for **ALL** matching pods.

_istioctl_ does accept a `--selector <selector>` for some commands, e.g. `istioctl dashboard envoy`.  There is no reason not to make some/all of the `istioctl proxy-config` commands take the same `--selector` argument if it will help.  I don't have the cycles.  If you work on this yourself I will review/approve it.
