### ISSUE TITLE
Add proxy telemetry, logging, tracing

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#2750]

**Comment by rshriram** [comment]
Is there some place where there is detailed information about the issue?

**Comment by douglas-reid** [comment]
@rshriram there is not. this is tracking the feature to match the other tracking sheet of features, which itself lacks concrete definition.

My proposed definition:
- We have a fully-supported mechanism for collecting proxy-generated metrics (statsd to prometheus, or otherwise)
- We have a fully-supported mechanism for collecting proxy-generated access logs (perhaps just via kubectl logs, fluentd, and similar)
- We have a fully-supported mechanism for configuring and collecting proxy-generated trace data (including sampling)

I'd love to hear your (and others) input on what exactly this should entail. We can discuss the details on each of the sub-issues.

For 1.0, this feature is targeted for Beta, which means we need (more) testing and much more extensive documentation, among other criteria.

**Comment by kyessenov** [comment]
In this issue and others, are we monitoring Envoy, or are we monitoring
apps using Envoy, or are we monitoring Pilot using Envoy?

**Comment by douglas-reid** [comment]
@kyessenov there are separate issues for Pilot monitoring. as i understand it, this issue is about configuring and collecting proxy-generated telemetry. from that telemetry, we hopefully can improve monitoring of the apps being proxied and the proxies themselves.

**Comment by andraxylia** [comment]
Right, pilot monitoring is #2175 , it's almost done.
