### ISSUE TITLE
Debuggability: Pilot & Envoy introspection from a web browser

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#2751]
It would be nice to be able to view pilot & Envoy debugging info from a web browser, ideally with some hyperlinks.

The fix can build on top of bin/istio-proxy-cfg and on top pf pilot metrics collection, or do something novel.

Related:
#1323
#2175
#2750

**Comment by sakshigoel12** [comment]
@andraxylia can you help assign an owner for this issue

**Comment by andraxylia** [comment]
There have been quite some progress on this front, I will need to do an analysis and see if anything else can be done. I assign this to myself.

**Comment by ostromart** [comment]
https://github.com/istio/istio/issues/5307 looks to be relevant to this.

**Comment by esnible** [comment]
I have a prototype visualization tool at https://github.com/esnible/envizistion

The tool expects a port-forward and combines the results of the 15000/config_dump, /stats, /certs, and /clusters from Envoy.  It tries to remove listeners and routes that are not in use.

That tool is mostly Javascript and could be easily put into `istioctl` if there is interest.

Because the tool is completely static files it should be possible to run a little server on the sidecar to serve them instead of putting the code into istioctl.

**Comment by howardjohn** [comment]
There are many implementations of this as mentioned above, as well as our official `istioctl describe` and `istioctl analyze`
