### ISSUE TITLE
track external Istiod promotion WIs to beta

### ISSUE THREAD

**Issue by linsun** [istio/istio#27669]
Low priority ones are not part of the beta criteria:

**Process**:

- [ ] supportability review

**Features/Fixes**:

- [x] enable CRD flag (M) @irisdingbj 
  - [x] https://github.com/istio/istio/pull/27115
  - [x] https://github.com/istio/istio/pull/28346
- [x] proper API for istiod custom host (M) @linsun --> not needed when connection is terminated at gw.
- [ ] Simplify external istiod config (M) @linsun https://github.com/istio/istio/issues/28708
- [ ] Optional: external istiod secret reload (L) @irisdingbj 
- [ ] Optional: vm integration (L)

**E2E Testing**:

- [x] external istiod single cluster install test and simple istio functionality test (H) @irisdingbj 
- [ ] external istiod multicluster install test and simple istio functionality test (M) - Depends on multicluster beta graduation
- [ ] external istiod single cluster no loss of function on istioctl commands (H) @esnible 

**Docs**:

Each task here also includes providing an automated test for the document on istio.io.

- [x] external istiod install documentation (H) @linsun 
- [ ] external istiod multicluster install documentation (H) @linsun

**Comment by linsun** [comment]
cc @ostromart @irisdingbj @esnible @sdake @costinm @nmittler @stevenctl

**Comment by nmittler** [comment]
@linsun can you clarify why external istiod is on this list at all? I thought we had agreed that external istiod (i.e. config cluster) would not be part of multicluster beta (i.e. istio 1.8)?

**Comment by nmittler** [comment]
@linsun I've reworked this significantly.  This seemed to be missing a lot of items from https://docs.google.com/document/d/1eskMB7OUwSvL_keTsQa3BWRmHAmGkWwUWsKCfBLk1V4/edit#.

**Comment by nmittler** [comment]
@linsun why is VM integration part of this? VMs are a different team.

**Comment by linsun** [comment]
@nmittler regarding your q for vm integration... it was only listed as (low priority) because during external istiod beta promotion doc review, @costinm indicated he is interested in working on this.

**Comment by esnible** [comment]
My concern with "no loss of function on istioctl commands" is `proxy-status`.  When _istioctl_ connects to istiod it gets a random pod.

Most or all of the fix for this **must** be done on the server side.  There is no approved design for this and the [issue](https://github.com/istio/istio/issues/24703) has been stuck for a long time without concensus.

**Comment by linsun** [comment]
Thanks @esnible!  On the bright side, I don't use proxy-status very often these days.  So istioctl ps currently works with external istiod if I configure xds-server or endpoint, does it connect to a random external istiod vs each of the istiod?  Any major issue with connecting to a random istiod in the past (even for in cluster istiod)?  I haven't heard much complaint about it.

Also, Is #24703 same as the new troubleshooting API?

**Comment by esnible** [comment]
_istioctl_ can be told to use the XDS version of `proxy-status`.  It doesn't look up the XDS endpoint so it fails if the user is doing an external control plane canary.  It doesn't consult all the Istiods so it may fail if there are >1 istiod pod.

Work can be done on the client if we need to support external control plane canary.  I can do that work.
My current idea for the server is a work-around.  Cloud providers can redirect traffic on the control plane cluster so that traffic from _istioctl_ goes to a "facade" microservice instead of real istiod.  This facade microservice would invoke all the Istiod pods and combine the results.  This work could be contributed to the Istio Ecosystem if there was interest in making `proxy-status` work with external high available >1 pod istiod.

**Comment by linsun** [comment]
We don't know if we need external istiod canary atm.  We do know we will recommend users to use revision upgrade to upgrade from in cluster istiod to external istiod.  (see https://github.com/istio/istio/issues/29304).

@esnible do you see any other issue if we don't need external istiod canary?  

cc @rvennam for input.
