### ISSUE TITLE
Enhance `istioctl idc log` error messages

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#27732]
I was trying out the new logging command and had some feedback. Overall, works great!

----

```
$ ik idc log --level debug
Error: pattern debug did not match
```

In this case, I would expect this to be valid actually, to match `pc log`. A non scoped reference will update all scopes. In `--log_output_level` you can also do `all:debug` (see https://github.com/istio/pkg/blob/master/log/config.go#L237-L244) which isn't supported either. Might need a change in controlz logic, but that would allow doing it without ~20 calls to controlz if we want)

----

```
$ ik idc log --level foo:debug
Error: failed updating Scope foo: cannot update resource foo, got status 400 Bad Request
```

This is pretty good, may be useful to list all the valid scopes though. Basically just put `ik idc log` output?

---

```
$ ik idc log --level foo
Error: pattern foo did not match
```

Same comment as above, can we list valid inputs here?

cc @esnible @piotrkpc

**Comment by esnible** [comment]
Questions about 'istioctl istiod-config'

- Should it go under experimental?
- Currently if there is >1 Istiod pod it logs <timestamp> warn more than 1 pods fits selector: app=istiod; will use pod: istiod-9f9cb4674-cqglh. For setting levels should it set all the matching pods?
- Should it support deployment/istiod instead of just a pod name if the optional argument is passed in?

**Comment by piotrkpc** [comment]
I can work on this. Could you assign this to me? Would it be possible that I could assign myself to some issues?

**Comment by esnible** [comment]
Not stale.  Assigned to @piotrkpc .  I do not have the authority to let him assign himself to issues.

**Comment by esnible** [comment]
@piotrkpc Are you working on this?  Should I target Istio 1.10 for this?
