### ISSUE TITLE
Perf cluster monitoring not properly configured

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#27782]
We install grafana from samples/ which is pointing to a prometheus at `prometheus:9000`. The script installs it at `istio-prometheus.istio-prometheus:9000`.

The script also installs some ServiceMonitor for istio monitoring, but its missing k8s monitoring which we used to have

cc @carolynhu @richardwxn

**Comment by howardjohn** [comment]
the latter is probably simple to fix - just apply `addons/servicemonitors.yaml` in the script?

**Comment by richardwxn** [comment]
I removed the line to apply addon/servicemonitors by accident in last PR, put it back in my latest PR: https://github.com/istio/tools/pull/1241

**Comment by poussa** [comment]
The prometheus service monitors are still not correctly deployed. When you run the [setup_istio.sh](https://github.com/istio/tools/blob/master/perf/istio-install/setup_istio.sh) you get:

```bash
error: the namespace from the provided object "istio-prometheus" does not match the namespace "istio-system". You must pass '--namespace=istio-prometheus' to perform this operation.
```

From [here](https://github.com/istio/tools/blob/77233e3257ce943feecc0ff3ab951405ea288855/perf/istio-install/setup_istio.sh#L114) since the `kubelet-state-metrics` object has already a namespace `istio-prometheus` and the script is trying to deploy it to `istio-system` namespace. Thus the service monitor `kubelet-state-metrics` is not deployed.

**Comment by poussa** [comment]
But even with the above patch the prometheus do not have the cAdvisor metrics ;(

**Comment by poussa** [comment]
One of the issues, at least in my on-prem cluster, is that the kubelet /metrics/cadvisor does not allow http, only https scheme. In the [PR1241](https://github.com/istio/tools/pull/1241l) the scheme was changed from https to http. Why was that?

/cc @richardwxn

**Comment by poussa** [comment]
I found the answer to the (my own) question above. In my on-pem cluster which I create with kubespray, the kubelet was not listening the http port for metrics. Once I enabled the kubespray var `kube_read_only_port: 10255` (kubelet config readOnlyPort) the metrics show up correctly in Prometheus.

**Comment by poussa** [comment]
on my part, we can close this.
