### ISSUE TITLE
installed-state isn't updated correctly

### ISSUE THREAD

**Issue by jaronoff97** [istio/istio#27973]
When we installed the istio operator in to our cluster, `installed-state` was created next to our istio operator `control-plane`. As we updated out istio operator installation, `installed-state` has remained the same without any of the updates. A few days ago, our operator pod was evicted causing a reconciliation loop. Because of order of operations, `installed-state` was reconciled _after_ our `controlplane` installation. Below is a screenshot of the result of that:

![Screen Shot 2020-10-14 at 8 59 16 PM](https://user-images.githubusercontent.com/10070047/96061040-28421200-0e60-11eb-9ece-f88bfee9d677.png)

The pod count decreased back down to the default max of 10 (our metrics setup is currently doubling metrics), and we lost metrics for some time because of the new replicaset rollout. We also saw a massive spike 5XX served.

[ ] Docs
[X] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
`installed-state` is updated after an update to an `istio-operator`

**Steps to reproduce the bug**

* Install an operator with the CRD
* update the operator CRD
* restart the operator pod

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
```
client version: 1.6.4
external-ingressgateway version:
pilot version: 1.6.4
data plane version: 1.6.4 (35 proxies)
```

**How was Istio installed?**
Via the operator as described here: https://istio.io/latest/docs/setup/install/operator/

**Environment where bug was observed (cloud vendor, OS, etc)**
EKS

**Comment by howardjohn** [comment]
cc @richardwxn @ostromart

**Comment by richardwxn** [comment]
@jaronoff97 If I understand correctly, you had installed Istio using `istioctl install` first, then `installed-state` CR was created in the cluster, then you ran `istioctl operator init` command to use operator. Regarding the step you mentioned `As we updated out istio operator installation,`, I assumed you created another IstioOperator CR for installation, right?

@ostromart I think we probably need to add annotation/label to the installed-state so that would not be reconciled by the operator pod, instead that should just server the purpose of recording state.

**Comment by jaronoff97** [comment]
@richardwxn these were the commands i used to install istio, installed-state (i believe) was created after we applied the `custom_manifest.yaml`:
```
istioctl operator init
k create ns istio-system
k apply -f custom_manifest.yaml
istioctl manifest apply -f custom_manifest.yaml
```

At some point we updated our `custom_manifest.yaml` to increase the pod count and the HPA for the ingressgateway, and the `installed-state` CR was not updated with that.

**Comment by richardwxn** [comment]
I am wondering why you need to run `istioctl manifest apply` after you have already deployed the operator and the CR? Actually that's not needed because the operator would reconcile the CR to install Istio, they are different paths for installation actually: 1. https://istio.io/latest/docs/setup/install/istioctl/ 2. https://istio.io/latest/docs/setup/install/operator/

And `install-state` CR is used to record the installation history using `istioctl manfiest apply`, unless you run `istioctl manifest apply` again, the install-state CR would not be updated.

**Comment by jaronoff97** [comment]
> I am wondering why you need to run istioctl manifest apply after you have already deployed the operator and the CR?
The reason I had to do that initially is because of a bug in our previous istio version that didn't apply the addons correctly so Kiali never got installed. 

> the install-state CR would not be updated.
I would expect that `k apply -f ...` to update the istio configuration should update the installed-state given the state has changed. If the change to make sure that installed-state doesn't get reconciled is a simple label on the installed-state CR, and a check at the beginning of the reconcile loop to not reconcile a resource with that label, I can look into making a PR.

**Comment by richardwxn** [comment]
> The reason I had to do that initially is because of a bug in our previous istio version that didn't apply the addons correctly so Kiali never got installed.

I see, so you ran `istioctl manifest apply` again mainly for applying the manifest for Kiali

>  If the change to make sure that installed-state doesn't get reconciled is a simple label on the installed-state CR, and a check at the beginning of the reconcile loop to not reconcile a resource with that label, I can look into making a PR.

Yep that would be the change needed. Feel free to send us for review once you have the PR ready, appreciate your contribution!

**Comment by richardwxn** [comment]
changed to p1, as this is more like a user experience improvement issue

**Comment by richardwxn** [comment]
This issue was addressed in: https://github.com/istio/istio/pull/29378
