### ISSUE TITLE
Deprecate upstream Istio Helm chart

### ISSUE THREAD

**Issue by lachie83** [istio/istio#2837]
It looks like a decision has been made to host the Istio helm chart in the Istio repo itself. Was there any attempt to consult me on this decision (as the maintainer of the upstream chart in the official charts repo) and I would have liked to contribute on the upstream chart?

I'm going to propose deprecating the upstream chart in favor for this one. https://github.com/kubernetes/charts/tree/master/incubator/istio

I might be able to point the upstream charts repo at this chart if that's of interest.

/cc @linsun @luisyonaldo

**Comment by linsun** [comment]
> I might be able to point the upstream charts repo at this chart if that's of interest.

+1 to what you said.   yes, that is certainly of interest, thank you for offering that @lachie83 and started the helm chart for istio in the first place!

**Comment by lachie83** [comment]
Thanks @linsun. Can you comment on if there was any attempt to contact me about this move/rework? I'm currently feeling a little offended as I wasn't made aware. Honestly - I'm happy with the outcome and would have liked it in the Istio repo in the first place but I needed to prove that there was value first which I did in the upstream charts repo.

**Comment by luisyonaldo** [comment]
I saw both charts and asked here if the chart on incubator was supported by istio developers. They told me that no, later on I just started to contribute here since the chart was on a really early stage and we modified it a lot to put istio on our current k8s cluster.

I recently did a refactor of the chart. Still have a lot of places where it can be improved. Feel free to contribute. Also, ping me if you see something wrong.

Idea is to add some test after chart is stable and then host it on a helm repo.

**Comment by linsun** [comment]
@lachie83 I sincerely apologize if we didn't make you aware in the first place.  I recall when the initial chart was worked on in istio repo, we voted that we wanted to host the chart in istio and gave pointer to your chart as the starting point to base on.  The chart may not look closely like what you had but your initial work helped us greatly to shape things.  Please give us comments on the chart so we can work together to produce the highest quality chart with best practice.

**Comment by lachie83** [comment]
Thanks for your comments on the matter @linsun @luisyonaldo. I'm still happy to contribute and review. Do you feel you have feature parity with the upstream chart? Where could I be of most use on this work right now? Shall I just look at Helm issues in the queue?

**Comment by lachie83** [comment]
Deprecation issues - https://github.com/kubernetes/charts/issues/3451

**Comment by lachie83** [comment]
PR - https://github.com/kubernetes/charts/pull/3452

**Comment by linsun** [comment]
Thank you @lachie83 for your help!  You can check the latest in master and let us know if some feature is missing.

**Comment by sdake** [comment]
@lachie83 a few things are missing from the istio/istio Helm chart:

* addons
* a CI check
* translation of Helm charts to native manifests

I apologize you were not consulted during the transition of the Helm charts source to Istio master.  Someone dropped the ball there (probably me).  The rationale for why Helm charts were merged into master is the work @ZackButcher has proposed.  I'm not sure if there is active development on this functionality yet, however, parts of this work are in the code base.

The general gist is that the Helm chart will become the single source of truth for all things related to Istio installation.  Some folks would prefer to use regular manifests instead for some use cases.  istioctl supports a feature called "genconfig".  The idea of the genconfig operation is that operators can generate raw Kubernetes manifests from the Helm charts (IOW genconfig works as a translator from Helm to raw manifests).  I'm not quite sure how to implement this - would appreciate your expertise in this area.  This then allows us to remove most of updateVersion.sh (I suspect).

@costinm can provide more details on requirements here.

**Comment by luisyonaldo** [comment]
I'm working on addons right now. The chart still need a bit more work, small stuff like move all port definitions to a variable so it can be easily configurable.

The most tedious point in my opinion is generate all manifest using the chart, for this all possible configurations need to be supported by the chart. I'm my opinion they are mostly cover, but for this I need to go one by one manifest and see if helm can generate that output.

It would be good if updateVersion.sh can be removed, right now subcharts should be move out of `/charts` folder and threat then as a separate chart.

@lachie83 let me know what do you think about current configuration and how it can be improved

**Comment by costinm** [comment]
Sorry, I didn't even realize you were not aware/involved in the move !

In terms of requirements: the main one is to replace the e2e and
integration tests (using the old sed-based templates) with
istioctl using the helm charts. And to make sure the helm charts got all
the changes from the release templates, before
we deprecate/remove them.

The main reason for the move (from my perspective) is that we want the
configs integrated with the testing infra and
to use the as the source of truth, instead of maintaining 2 (or 3 if we
include pilot's integration templates)

**Comment by costinm** [comment]
We don't need to test all possible combinations - and we need to be very
careful about what we allow to be configurable.

We also need to clearly document what configurations are tested and
supported - and which one are 'modify on your own risk'.
For example changing the names of services, and some of the ports is very
likely to break stuff in mesh expansion.

**Comment by luisyonaldo** [comment]
Right now the name of the services should not matter (it is dynamically changed everywhere), the ports right now are not configurables because of that. I need to make sure all subcharts use same port value, which mean defining ports as global, or needing to define the port in multiple places. Like: `proxy.port` and `mixer.proxy.port`

**Comment by luisyonaldo** [comment]
https://github.com/istio/istio/pull/2965

**Comment by GregHanson** [comment]
resolved by #2965
