### ISSUE TITLE
Tracing series is breaked by nginx?

### ISSUE THREAD

**Issue by xiaozhongliu** [istio/istio#28397]
**Bug description**
My api (k8s-demo-bff) is proxied directly by the nginx-hosted frontend app (k8s-demo) like this: https://k8s-demo.me/k8s-demo-bff/ with the following frontend nginx config:
```
    location /k8s-demo-bff/ {
        proxy_http_version 1.1;
        proxy_pass_request_headers on;
        proxy_pass http://k8s-demo-bff/;
    }
```
It seems the istio tracing headers cannot be passed through successfully:
![image](https://user-images.githubusercontent.com/17674404/97564034-e9df5200-1a1e-11eb-909a-65d0019f04ef.png)

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Tracing series should not be breaked, they should have the same trace ID.

**Steps to reproduce the bug**
No need to provide.

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
```sh
~ istioctl version --remote
1.6.8
~ kubectl version --short
Client Version: v1.19.2
Server Version: v1.16.9-aliyun.1
```

**How was Istio installed?**
Aliyun ASM product

**Environment where bug was observed (cloud vendor, OS, etc)**
Aliyun
Centos7

**Comment by douglas-reid** [comment]
Do you have a way of validating that all of the required headers are passed through successfully?  I would expect `proxy_pass_request_headers      on;` to work, but it seems like somehow not all of the headers are making it through.

Since this _appears_ to be something related to the nginx app and not Istio, I'm going to close this issue. Please re-open if you have more data to support an Istio issue.
