### ISSUE TITLE
Add presubmit test for canary upgrade

### ISSUE THREAD

**Issue by bianpengyuan** [istio/istio#28411]
Not sure if there is already a presubmit check or not for canary upgrade, but https://github.com/istio/istio/issues/28189 suggests it unlikely exists. We should add a smoke test to prevent this kind of issue. cc @ostromart @sdake

**Comment by richardwxn** [comment]
It seems to be hard to add presubmit test between different versions, specifically between different minor releases. That's why we define upgrade/downgrade test(canary or rolling upgrade, the canary one was recently added) as periodic job running on a real gke clusters. But the problem with that is it does not get enough attention and it is not stable enough. Are you currently maintaining that? @carolynhu

**Comment by carolynhu** [comment]
right, this is under maintaining https://github.com/istio/tools/tree/master/upgrade_downgrade
