### ISSUE TITLE
First class telemetry filter config

### ISSUE THREAD

**Issue by bianpengyuan** [istio/istio#28410]
Proposal: https://docs.google.com/document/d/1f_emnIfPX3i_rLFzNYmUQvsKxuUknXWv_qJZ3RYBn9U/edit#

Work items:

- [x] Implement HTTP metadata exchange in istiod
- [x] Implement TCP metadata exchange in istiod
- [ ] Implement Prometheus filter in istiod
- [ ] Implement Stackdriver filter in istiod
- [ ] Implement Access log policy filter in istiod

**Comment by howardjohn** [comment]
When we do this we should consider what does and doesn't make sense as a plug-in. In my opinion the old plugin logic was very complex and led to many bugs and hard to understand behavior. It's slightly better now but still wrong - plugins take in more info than they require which leads to a lot of missing/fake data passed at various call sites

**Comment by carolynhu** [comment]
> When we do this we should consider what does and doesn't make sense as a plug-in. In my opinion the old plugin logic was very complex and led to many bugs and hard to understand behavior. It's slightly better now but still wrong - plugins take in more info than they require which leads to a lot of missing/fake data passed at various call sites

I will try to clean up those existing tedious, error-prone or fake data. Yes, I agree, the existing plugin codebase for AuthN/Z is pretty complex, and probably I would make it simplified while i'm working on this project.

**Comment by bianpengyuan** [comment]
> we should consider what does and doesn't make sense as a plug-in. In my opinion the old plugin logic was very complex and led to many bugs and hard to understand behavior.

Is plugin logic intrinsically complicated, or writing them as a plugin make them unnecessarily complicated? If it is the former, wouldn't it be more problematic if they are implemented in core?

**Comment by howardjohn** [comment]
@bianpengyuan part of the problem was that it was a huge leaky abstraction. The plugin params took in like 15 fields, so call sites would only pass some subset to them because they knew the function they called happened to only use those fields.

This has been trimmed a bit (part of it was post-mixer cleanup) but it's not great.

There is also some awkward parts like OnInboundFilterChain. I am pretty sure that would be more clear written a different way (maybe plugin concept is fine, but a different entry point?) for example.

Anyhow, I am not sure that plugin is wrong - I am just not sure it's right either, so we should look into changing it if it makes sense.

cc @yangminzhu if you have any input here

**Comment by carolynhu** [comment]
I made some progress there by implementing the httpmx plugin and tested the code, it works. I did not use that much complex logic used in the AuthN, I just constructed a httpmx filter via the Wasm API . I think the workflow there is correct, but definitely it can be simplified. Since I think some logic in building filterchain and building listeners part might be overlapping or unnecessary. So I vote the first, `plugin logic is intrinsically complicated` but can be simplified.

**Comment by howardjohn** [comment]
To more directly answer, the plugin logic is probably pretty complex but it's "essential complexity". I am more concerned about the accidental complexity of the plugin interface.

If we want the minimal change it would probably be reasonable to split the Plugin params so each method can take in different, smaller scoped, inputs.

**Comment by carolynhu** [comment]
> To more directly answer, the plugin logic is probably pretty complex but it's "essential complexity". I am more concerned about the accidental complexity of the plugin interface.
> 
> If we want the minimal change it would probably be reasonable to split the Plugin params so each method can take in different, smaller scoped, inputs.

Yes, I think we can do that depend on the usages of the plugin, which kind of filters we want to build and insert in the envoy config_dump. But that definitely need a little bit redesign. Not sure if @yangminzhu want to put effort there.

**Comment by kyessenov** [comment]
If we'd do it again, we'd probably structure it as an xDS proxy without actual wire bits. I think it might help to think in those terms. We could provide additional decorators by some sort of `map[proto.Message]InputInfos` associated with it.
