### ISSUE TITLE
istioctl upgrade fails for 1.6.x to 1.7.x demo profile

### ISSUE THREAD

**Issue by ostromart** [istio/istio#28595]
```
./istio-1.6.8/bin/istioctl install --set profile=demo
./istio-1.7.1/bin/istioctl upgrade --set profile=demo

Control Plane - egressgateway pod - istio-egressgateway-6d98c888ff-6lbmq - version: 1.6.8
Control Plane - ingressgateway pod - istio-ingressgateway-6bff4c6896-xxt9v - version: 1.6.8
Control Plane - pilot pod - istiod-587bbdc654-dt8tj - version: 1.6.8

2020-11-04T22:39:02.727883Z	warn	found 4 CRD of unsupported v1alpha1 security policy: [clusterrbacconfigs.rbac.istio.io rbacconfigs.rbac.istio.io servicerolebindings.rbac.istio.io serviceroles.rbac.istio.io]. The v1alpha1 security policy is no longer supported starting 1.6. It's strongly recommended to delete the CRD of the v1alpha1 security policy to avoid applying any of the v1alpha1 security policy in the unsupported version
Upgrade version check passed: 1.6.8 -> 1.7.1.

2020-11-04T22:39:07.703818Z	info	Error: failed to generate Istio configs from file [] for the current version: 1.6.8, error: json merge error (unable to find api field in struct externalComponentSpec for the json field "kiali") for base object: 
{"apiVersion":"install.istio.io/v1alpha1","kind":"IstioOperator","metadata":{"na
... etc
```

The reason appears to be that externalComponents were removed in 1.7 and the upgrade command compares the base profiles (in this case demo). At some point it probably tries to unmarshal into the new version schema and any missing fields cause it to fail. 
It should be reporting that those fields are no longer available in the target schema instead.

**Comment by msvticket** [comment]
Is there any known workaround?

**Comment by shamsher31** [comment]
> Is there any known workaround?

You can try Canary Upgrades.
https://istio.io/latest/docs/setup/upgrade/canary/

**Comment by SeanWallace** [comment]
> Is there any known workaround?

What I did to work around it was change the profile to `default`. Turns out the `demo` profile really doesn't mean much these days ([1.8](https://istio.io/latest/docs/setup/additional-setup/config-profiles/) vs [1.6](https://istio.io/v1.6/docs/setup/additional-setup/config-profiles/)) with the only thing you're not getting by default being the egress gateway which you can easily add on.

**Comment by carolynhu** [comment]
After my investigating, the root cause for this is that in 1.7 we removed addComponents for kiali, tracing and grafana, https://github.com/istio/istio/blob/1.7.1/operator/pkg/util/merge_iop.go#L73 But in 1.6.8 we have them in both `default` and `demo` profile. In here https://github.com/istio/istio/blob/1.7.1/operator/pkg/util/merge_iop.go#L276 we are trying to do a merge based on 1.7's operator spec, which throws the error.

**Comment by carolynhu** [comment]
@ostromart should we just make the error message much meaningful, like what you suggested `It should be reporting that those fields are no longer available in the target schema instead.` or should we think a way of overcoming this? My current solution is the previous one.

**Comment by carolynhu** [comment]
> Is there any known workaround?

um, a workaround would be use `./istio-1.7.1/bin/istioctl install` instead
