### ISSUE TITLE
Move distributionEventQueue to a proper queue

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#28592]
https://github.com/istio/istio/blob/96dc4165768648dcd9cc72a3a09183202a28acf3/pilot/pkg/status/reporter.go#L68

Currently this always uses fixed 5mb of memory and may actually fill up and drop events. Should use a dynamic queue size

**Comment by kailun-qin** [comment]
A dynamic queue size will make `distributionEventQueue` lose the backpressure, which may not be a good practice. Generally, we should not simply queue the events forever if consumers sufficiently behind and the unawareness to users/developers makes it worse.
Further, since the event queue is dynamic (or even unlimited), a naively written thread-safe dynamic queue can behave poorly under load (due to the extra handling of data races etc.), which may eventually lead to crashes.

Considering the risk and cost here may outweigh the benefits of getting a dynamic queue, should we take alternatives like dropping stale events in the queue etc.? Any ideas? @howardjohn
