### ISSUE TITLE
add support for remote_jwks in Request Authentication

### ISSUE THREAD

**Issue by ramaraochavali** [istio/istio#28742]
Currently when https://github.com/istio/api/blob/master/security/v1beta1/jwt.proto#L93 is specified, Istio fetches the public key by it self. Would it be possible to support remote_jwks https://github.com/envoyproxy/envoy/blob/fe74d85d7d916eb975342e8298f2dc76279c1978/generated_api_shadow/envoy/extensions/filters/http/jwt_authn/v3/config.proto#L47 if the jwksUri is a mesh service by itself so that we can configure the cluster?

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by ramaraochavali** [comment]
@yangminzhu What do you think? Is there any other way to configure remote_jwks for now?

**Comment by ramaraochavali** [comment]
@yangminzhu ^^  - What do you think? Is it reasonable to add the above behaviour?

**Comment by incfly** [comment]
Aha, nice! Thanks for bringing up this!

I have seen at least two occurrences of this use case: a.k.a the JWKS issuer is within the service mesh itself. We find that since it's istiod fetches the public key, when the JWKS service enables the mTLS, Istiod would be unable to access that, since it only talks in HTTPs or HTTP.

I'm wondering what's the motivation you see to use this `RemoteJwks`? Is it also due to mTLS or something else?

Anyhow, this `RemoteJWKS` seems a cleaner solution at least for mTLS issue. My understanding is that: when we detect the JWKS URI is within the mesh(matching the pattern of *.svc.cluster.local or matches some service entry), Istiod can configure to use RemoteJWKS, the cluster is some service within the mesh. Therefore whatever DestinationRule/Auto mTLS settings we use, will be automatically enforced for Envoy to fetch JWKS.

The only downside or uncertainty is how stable this Remote JWKS will be, any caching or retries?

**Comment by ramaraochavali** [comment]
> I'm wondering what's the motivation you see to use this RemoteJwks? Is it also due to mTLS or something else?

Yes. mTLS is the main motivation

> My understanding is that: when we detect the JWKS URI is within the mesh(matching the pattern of *.svc.cluster.local or matches some service entry), Istiod can configure to use RemoteJWKS, the cluster is some service within the mesh. Therefore whatever DestinationRule/Auto mTLS settings we use, will be automatically enforced for Envoy to fetch JWKS.

Yes. That is what I was also thinking.  Let Istiod detect and configure RemoteJWKS and DR/Auto mTLS will take care of mTLS settings.


> The only downside or uncertainty is how stable this Remote JWKS will be, any caching or retries?

While we have not used it in production yet, we have configured using an Envoy filter and in test envs it seems to work fine.  Regarding retries, since it is a mesh cluster, it should honour the retries specified in DR. It has caching support https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/jwt_authn_filter#remote-jwks-config-example

**Comment by incfly** [comment]
Good to know.

I used to  trying solve this problem from a different angle: let Istiod talks mTLS when send the request to the JWKS issuer within the mesh.. I had a doc in https://docs.google.com/document/d/1w0uZO_foPc4S0nIjcby8HrhPfUohqMa8RD3ViwxHmD0/edit

But actually I think the `RemoteJWKS` is better and has the good benefit of simplicity. Istiod does not need to introduce the logic above. Let's do that and protect it under a feature flag.

**Comment by yangminzhu** [comment]
sorry for the late reply, I agree with both of you @ramaraochavali and @incfly , this change makes sense to me. Just make sure it is under a flag and disabled by default.

cc @qiwzhang to comment on the the performance implications of  `RemoteJWKS`.

**Comment by ramaraochavali** [comment]
@incfly @yangminzhu great. Added basic implementation here https://github.com/istio/istio/pull/29704. If we are good with that, I will add tests.
