### ISSUE TITLE
If a node terminates ungracefully, sidecars route to bad pods

### ISSUE THREAD

**Issue by rittneje** [istio/istio#28865]
**Bug description**

We are running a 1.14 cluster with Istio 1.5.10 on AWS EKS. When nodes are terminated in an ungraceful manner, we noticed that a large percentage of requests to the cluster started failing. As per https://github.com/istio/istio/issues/13840 I disabled HTTP/2 in istiod, and that fixed the immediate problem of pods not being created. However, requests continued to fail at random for the same 15 minute window. Specifically, they fail due to "Connection reset by peer". This happens when the node on which the pod with the sidecar is running terminates in an ungraceful manner. I am not sure if the sidecars have the same bug surrounding TCP half-closed connections.

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Comment by rittneje** [comment]
From further testing, it seems this issue is actually the sidecars themselves. If the node on which a pod with a sidecar is running terminates, requests to the service in question will fail for 15 minutes.

**Comment by infa-sanaik** [comment]
We are facing a similar issue related to ingress gateway. When one worker node went down, and two other nodes were running 5 istio gateway pods, clients still got timeouts during SSL handshakes even though we have 3 AWS ELB nodes in each region with cross-zone load balancing enabled. Gateway is configured for mTLS.
It seems that node controller's default timeout is 40s before it takes a node and pods on it out of service.

**Comment by kunalekawde** [comment]
I have similar issue at ingress, a test tool connects to application service via ingress, executes traffic calls and then terminates it self. Then when it tries to initiate the connection, it fails. The TCP handshake fails and there are half closed connections at istio-proxy.

**Comment by rittneje** [comment]
@howardjohn Is there someone that can investigate this issue?

**Comment by howardjohn** [comment]
https://github.com/istio/istio/issues/13840 is about sidecar injection failing, is this issue about that or actually pod <-> pod failures?

Do you have any more info about the failures like access logs, etc? are the failures to/from nodes that are terminated?

**Comment by howardjohn** [comment]
Ah, missed some details in the original. If the node terminates, it will SIGTERM all the process AFAIK. Its likely caused by https://github.com/istio/istio/issues/11130, where the proxy shuts down before the user container

**Comment by rittneje** [comment]
@howardjohn This issue is about pod-to-pod traffic. It appears to be unrelated to #13840, which is simply about new pods not being created. This happens when the node is terminated in an ungraceful manner, meaning that SIGTERM is never sent.

Imagine the following setup:
2 nodes
2 services (A and B)
Service A has one pod, service B has two pods.

Node 1
-------
- service A pod 1
- service B pod 1

Node 2
-------
- service B pod 2


In this example, all three pods have sidecars that are routing between each other with mTLS.
Node 2 is terminated ungracefully, so no `kubectl drain` and no SIGTERM.
Now my service A pod tries to send a message to service B.
For the next 15 minutes, 50% of requests will fail due to timeout, presumably because the sidecar is sill trying to route to service B pod 2 even though it is gone.
With the exact same setup _without_ any sidecars, this 15 minute downtime does not occur.

**Comment by howardjohn** [comment]
@rittneje during this 15 minutes, what does `kubectl get endpoints` show for service B? Does it have both pod 1 and pod 2? If it does, then I expect it would also be broken without Istio? If it does only have pod 1, then maybe it is a bug in Istiod.

**Comment by rittneje** [comment]
@howardjohn Sorry for the long delay. `kubectl get endpoints` does NOT show an entry for the deleted node. It gives the correct answer immediately after the node is taken down, no 15 minute delay.

**Comment by howardjohn** [comment]
I see, thanks @rittneje . Hopefully this can be reproduced, I am not sure I will be able to do the same ungraceful termination on GKE/Kind as you did on EKS, but will try it out

**Comment by howardjohn** [comment]
I attempted to reproduce it. I saw a small downtime of ~30s, then the endpoints were updated and immediately things went back to working. I would suggest if you can reproduce this to get additionally information from `kubectl get endpoints -w` with timestamps, istiod logs, and the contents of `curl localhost:15000/clusters` from the client pod during this time.

**Comment by howardjohn** [comment]
Any more info?

**Comment by rittneje** [comment]
Sorry, reproducing this issue requires me to take our test account for some time, and I have been busy with other work.

**Comment by mehyedes** [comment]
Hi @howardjohn 
We are facing the exact same issue but with GKE (see my [comment](https://github.com/istio/istio/issues/7136#issuecomment-860611284) ) and I can reproduce it at will.

We use [preemtible nodes](https://cloud.google.com/kubernetes-engine/docs/how-to/preemptible-vms#kubernetes_preemptible_nodes) for our workloads, and whenever a node gets preempted, we see a lot of failing requests and that lasts around 15min. This issue seems to be only affecting gRPC services.

For the sake of clarity, this issue does not occur when performing a rolling-update for a deployment, or when killing a pod, but only when a node is preempted.

We have tried tweaking the destination rule configuration, and the preStop hook to force Envoy to drain the listeners as suggested in https://github.com/istio/istio/issues/7136 but it doesn't seem to be working at all.

Below is our request flow:
```
         +----------------+          +------------------+      +-----------------+
         |                |          |                  |      |                 |
         |                |          |                  |      |                 |
---------> ingress-gateway+----------> HTTP service     +---X---> gRPC service    |
         |                |          |                  |      |                 |
         |                |          |                  |      |                 |
         +----------------+          +------------------+      +-----------------+
```
When it happens, we see that the requests are failing on the "HTTP service" level, with 408 status codes.

Below are some screenshots from the HTTP service dashboard:

![Screenshot 2021-06-11 at 17 27 34](https://user-images.githubusercontent.com/7854083/122059913-64fa4a80-cded-11eb-91be-9a7b6b6d8fe4.png)
![Screenshot 2021-06-11 at 17 27 52](https://user-images.githubusercontent.com/7854083/122059917-662b7780-cded-11eb-987c-2b6cc2ae803c.png)

And when checking the metrics for the gRPC service during the same time period, we see that these requests are not even being routed to the gRPC service pods. This points to the requests being routed to the deleted pods, maybe trying to use the old TCP connection.

### Reproducing the issue
I am just sending a request to get the health of the gRPC service here
```
curl  https://api.redacted.com/status/health\?service\=grpc-service
{"status":"OK"}%
```
I use the `gcloud` command below to simulate a preemption for a specific cluster node:
```
gcloud compute instances simulate-maintenance-event ...
```
I have 2 replicas of the gRPC service, below you can see the endpoints:
```
NAME                   ENDPOINTS                          AGE
grpc-service   10.15.1.15:5000,10.15.1.199:5000   102d
```
And only 1 replica of the HTTP service. Below is the output of the `istioctl proxy-config` command:
```
istioctl proxy-config endpoints http-pod --cluster "outbound|5000|v1|grpc-service.ns.svc.cluster.local"
ENDPOINT             STATUS      OUTLIER CHECK     CLUSTER
10.15.1.15:5000      HEALTHY     OK                outbound|5000|v1|grpc-service.ns.svc.cluster.local
10.15.1.199:5000     HEALTHY     OK                outbound|5000|v1|grpc-service.ns.svc.cluster.local
```

#### Simulating node preemption
Here, I am going to simulate the preemption of one of the nodes running the gRPC service pods.

This time, all of the requests sent by curl are failing. Even after the new endpoint was added to eh k8s endpoints:
```
curl  https://api.redacted.com/status/health\?service\=grpc-service
{"code":"request_timeout","details":[],"message":"The request has timed out."}
```
The endpoints are updated quite fast, but that did not prevent the issue from occurring.

Below is the output for `kubectl get ep`
```
k -n apps-staging get ep core-content-staging -w
NAME                   ENDPOINTS                          AGE
grpc-service   10.15.1.15:5000,10.15.1.199:5000   102d
grpc-service   10.15.1.15:5000                    102d
grpc-service   10.15.1.15:5000                    102d
grpc-service   10.15.0.134:5000,10.15.1.15:5000   102d
```
for the `istioctl proxy-config command`
```
ENDPOINT             STATUS      OUTLIER CHECK     CLUSTER
10.15.1.15:5000      HEALTHY     OK                outbound|5000|v1|core-content-staging.apps-staging.svc.cluster.local
10.15.1.199:5000     HEALTHY     OK                outbound|5000|v1|core-content-staging.apps-staging.svc.cluster.local

ENDPOINT            STATUS      OUTLIER CHECK     CLUSTER
10.15.1.15:5000     HEALTHY     OK                outbound|5000|v1|core-content-staging.apps-staging.svc.cluster.local

ENDPOINT             STATUS      OUTLIER CHECK     CLUSTER
10.15.0.134:5000     HEALTHY     OK                outbound|5000|v1|core-content-staging.apps-staging.svc.cluster.local
10.15.1.15:5000      HEALTHY     OK                outbound|5000|v1|core-content-staging.apps-staging.svc.cluster.local
```
Below are the logs from the `istio-proxy` container of the HTTP service pod:
```
[2021-06-15T13:49:11.149Z] "GET /status/health?service=grpc-service HTTP/2" 408 - via_upstream - "-" 0 78 1004 1003 "10.14.0.56" "curl/7.64.1" "76e17e28-03f9-4b27-99b7-aca1e6b42b5e" "api.redacted.com" "127.0.0.1:3000" inbound|3000|| 127.0.0.1:41928 10.15.2.13:3000 10.14.0.56:0 outbound_.3000_.v1_.http-service.ns.svc.cluster.local default
[2021-06-15T13:49:12.162Z] "- - -" 0 - - - "-" 1560 3928 9 - "-" "-" "-" "-" "34.120.195.249:443" PassthroughCluster 10.15.2.13:58358 34.120.195.249:443 10.15.2.13:58356 - -
[2021-06-15T13:50:44.321Z] "GET /status/health?service=grpc-service HTTP/2" 408 - via_upstream - "-" 0 78 1004 1004 "10.14.0.15" "curl/7.64.1" "4679dc33-0ae7-933a-b356-7283af06e8e4" "api.redacted.com" "127.0.0.1:3000" inbound|3000|| 127.0.0.1:44072 10.15.2.13:3000 10.14.0.15:0 outbound_.3000_.v1_.http-service.ns.svc.cluster.local default
```
As for the new gRPC service pod, it is not receiving any traffic at all. This is the last log line from the istio-proxy container:
```
{"level":"info","time":"2021-06-15T13:46:56.395111Z","msg":"Envoy proxy is ready"}
```
I noticed these log messages on the other (surviving) grpc-service istio-proxy container though:
```
{"level":"warning","time":"2021-06-15T13:45:25.750788Z","scope":"envoy config","msg":"StreamAggregatedResources gRPC config stream closed: 0, "}
{"level":"warning","time":"2021-06-15T13:45:25.865083Z","scope":"envoy config","msg":"StreamAggregatedResources gRPC config stream closed: 14, connection error: desc = "transport: Error while dialing dial tcp 10.16.15.208:15012: connect: connection refused""}
{"level":"info","time":"2021-06-15T13:45:26.848565Z","scope":"xdsproxy","msg":"connected to upstream XDS server: istiod.istio-system.svc:15012"}
```
I am not sure if these are related though.


Please let me know if you need any more info. As I mentioned above, I am able to reproduce this at will. 

Much appreciated.

**Comment by mehyedes** [comment]
For anyone else ending up here, check my [comment](https://github.com/istio/istio/issues/33466#issuecomment-863859552) explaining this issue and how you can fix it.
