### ISSUE TITLE
Multicluster install: failed calling webhook "validation.istio.io"

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#29004]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28998/integ-telemetry-mc-k8s-tests_istio/1329089529902010368

I have seen this a couple other times as well.

I think for MC @irisdingbj recently change it to "fail close" out of the box, maybe we have an ordering issue with applying the control planes in parallel @stevenctl ?

**Comment by howardjohn** [comment]
https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/28925/integ-telemetry-mc-k8s-tests_istio/1329112652944773120/build-log.txt

**Comment by howardjohn** [comment]
https://storage.googleapis.com/istio-prow/logs/integ-security-multicluster-tests_istio_postsubmit/1329360717203116032/build-log.txt

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/29050/integ-security-multicluster-tests_istio/1329457389685968896

**Comment by stevenctl** [comment]
```
2020-11-19T16:49:26.939241Z	error	Patch webhook failed: mutatingwebhookconfigurations.admissionregistration.k8s.io "istio-sidecar-injector" not found
```

I remember seeing that we setup webhook patch in every primary cluster for every other cluster, regardless if the other clusters are primary or remote. This means for each remote cluster we will have multiple pilots trying to do this patch. We will also be performing this patch from one primary cluster on another primary cluster's behalf... 

We should:
1. detect if the cluster specified by remote secret is running the control-plane. if it is, don't bother setting up the patch/namespace controllers
2. leader protect these things for multi-cluster mode (adding that in #28768)

Not sure these are what causes the issue here.. I'm still fuzzy how our new istiod-less remote install process is supposed to work... I'd really like to have a doc explaining how a real user would do that to easily compare against of test code.

**Comment by stevenctl** [comment]
cc @irisdingbj ^
