### ISSUE TITLE
Remove TESTONLY artifacts, and make istioctl work out of the box for pre-releases

### ISSUE THREAD

**Issue by hklai** [istio/istio#2904]
Having two sets of tar balls and istioctl directories is problematic. 
More context: https://groups.google.com/forum/#!topic/istio-dev/qo13rpC2FiA

1. It is confusing and people often picks up the wrong one.
2. The artifacts that we are releasing does not work out of the box.
3. People are testing different artifacts that the one we are releasing.

Instead, can we just push pre-releases also to docker hub, and make pre-release istioctl work out of the box?

**Comment by hklai** [comment]
cc @ldemailly

**Comment by mattdelco** [comment]
The pipeline approach for artifacts doesn't work well with how Istio bakes in URL references (usually to GCS-hosted content) and docker hub references.  URL redirects as an indirection layer could mitigate some of this, but this won't address docker hub references and I'm not aware of a redirection mechanism for that.

Otherwise, the main approach I can think of offhand is to have the build directly output to the final location, and we never copy/republish artifacts.  E.g., a daily build goes to istio-prerelease on GCS and istio-release on GCR, while a monthly release goes to istio-release on GCS and docker.io (with no prior or intermediate stops).

A possible lower-effort alternative is to just having something delete the non-testonly tars for a daily build (optionally rename the testonly tars to not have the prefix).  I'm less sure about what to do with a monthly release.  That workflow could be kept as-is, or the testonly tars could be deleted (or try to make a change to not generate them at all).  A deciding factor might be whether a rebuild for a monthly release is going to be tested as all before its published.

**Comment by hklai** [comment]
"Otherwise, the main approach I can think of offhand is to have the build directly output to the final location, and we never copy/republish artifacts. E.g., a daily build goes to istio-prerelease on GCS and istio-release on GCR, while a monthly release goes to istio-release on GCS and docker.io (with no prior or intermediate stops)."

As discussed before, I do think this makes more sense. No need to copy things around.

**Comment by ldemailly** [comment]
I would just have the TESTING one and not the other and stick to gcr.io ?

**Comment by ldemailly** [comment]
(only once a month we rebuild and push to docker.io)

**Comment by hklai** [comment]
any reason not to push to docker hub anyway, since that is what monthly release is doing. And that people can test the artifacts closer to the one being released.

**Comment by mattdelco** [comment]
By "push to docker hub anyway" I'm not clear on if you have in mind to use docker hub instead of or in addition to GCR.  While it is possible to push to both I'm not sure how practical or worthwhile that is given that certain build artifacts can only point to 1 location.

I think docker hub pushes are slower.  Some people have mentioned that people look at the docker hub for the latest version and thus we should be more cautious about pushing less-official releases there.  An option is to push to another location on docker hub, but I can't speculate on the tradeoffs on GCR vs. "unofficial docker hub" (except for the speed part).

**Comment by ldemailly** [comment]
what matt said

**Comment by hklai** [comment]
> By "push to docker hub anyway" I'm not clear on if you have in mind to use docker hub instead of or in addition to GCR. While it is possible to push to both I'm not sure how practical or worthwhile that is given that certain build artifacts can only point to 1 location.

Just do exactly the same as official releases, which I believe we push to both GCR and Docker Hub, right? And pushing to a location other than the official release location is fine with me.

Having said that, I don't mind as much if we only use GCR in pre-releases, but that is another difference between pre-releases and the actual releases. We said the version string was the only difference but now hub is also different. However, if that is easier and the material difference is small, we can stick with GCR only for pre-releases. Either way, we should get rid of the TESTONLY artifacts.

**Comment by ldemailly** [comment]
> Either way, we should get rid of the TESTONLY artifacts.

We should get rid of the non functional artifacts. Currently the TESTONLY is actually the working one so we don't want to lose the working one.

**Comment by hklai** [comment]
Well, it should probably be read as replacing the non functional one with
the functional one, and remove the need for the TESTONLY prefix.

On Mon, Jan 29, 2018 at 10:29 AM, Laurent Demailly <notifications@github.com

**Comment by ldemailly** [comment]
I added https://github.com/istio/istio/wiki/Daily-builds as I keep getting asked about the dailies

**Comment by hklai** [comment]
TESONLY is gone from the latest daily release. http://gcsweb.istio.io/gcs/istio-prerelease/daily-build/0.6.0-pre20180226-23-04-36/.
Thanks!

However, it still has two sets of istioctl. One in istioctl directory, and one in istioctl-stage directory. I think one of them is still pointing to dockerhub instead of gcr by default. Could that be fixed as well?

**Comment by mattdelco** [comment]
There's also still two sets of tars (one under docker.io/ and another under gcr.io/).  The change mostly simplified what people see at the top-level of a build, and thus people would only get into trouble if they go snooping in the subdirectories.

**Comment by hklai** [comment]
Let's clean them all up once and for all.

**Comment by ldemailly** [comment]
can we put some pressure to get a newer daily - isn't it a code yellow or orange if there are no dailies for a week ?

**Comment by ldemailly** [comment]
agreed. we should probably have some kind of alarm (team rally I mean) on not being able to make a daily for more than X days (maybe X == 4 ?) and not able to make a weekly ?
(I think it's sort of part of the oncall duties but there are so many...)
