### ISSUE TITLE
Istio 1.8 release notes missing few important features

### ISSUE THREAD

**Issue by martin2176** [istio/istio#29061]
Reading through release notes for new features in 1.8, I find three important features are missing in Rel notes.

1. Multicluster endpoint discovery feature. Istiod can in 1.8 discover endpoints in local and remote clusters . From my pov, this is a very very useful feature . 
2. Dedicated East west gateway in multicluster deployments. new in 1.8?
3. New parameters meshID,clusterName, network etc for multicluster mesh installations ?

I think documenting these new features are very important for someone who is looking at 1.8 trying to find out what has changed.

**Comment by stevenctl** [comment]
> 1. Multicluster endpoint discovery feature. Istiod can in 1.8 discover endpoints in local and remote clusters . From my pov, this is a very very useful feature .

This isn't really new – we've had this functionality since at least 1.6.

> 2. Dedicated East west gateway in multicluster deployments. new in 1.8?

This definitely deserves a note. 

> 3. New parameters meshID,clusterName, network etc for multicluster mesh installations ?

This isn't really new either. We've always required these as inputs in our multicluster install – I guess they do need to be specified both in istio install and eastwest gateway install.

**Comment by nmittler** [comment]
Agreed ... the east-west gateway is really the only new thing here.

**Comment by martin2176** [comment]
I didnt come across this automatic multicluster service discovery in pre 1.8 releases. I used to create ServiceEntry as MESH_INTERNAL to add a service in a replicated control plane multicluster mesh as documented here --> 
https://istio.io/v1.7/docs/setup/install/multicluster/gateways/

After I installed 1.8, I could see the the experimental feature remote service discovery by allowing Istio CP to discover services in a remote kube-api by running istioctl x create-remote-secret
So you are saying this experimental feature was there even pre 1.8 release?

**Comment by nmittler** [comment]
Yes it's likely been working since ~1.6, but hasn't been formally documented until 1.8. Docs were initially targeted for 1.7, but they didn't make it in time for the release.

If your clusters are on the same network (i.e. direct reachability between pods) then it should just work. If they're on different networks (i.e. access via gateways), you'll likely want to use a dedicated east-west gateway (1.8 ships with a sample used by the docs). This gateway is configured to keep outbound traffic local to its network, which avoids requests ping-ponging between networks.

**Comment by howardjohn** [comment]
This is documented in https://istio.io/latest/docs/setup/install/multicluster/ now
