### ISSUE TITLE
Many APIs have changed from v1 to v1beta1 in 1.8 release

### ISSUE THREAD

**Issue by Stono** [istio/istio#29120]
**Bug description**
For example - in `1.7.5`, `peerauthentications.security.istio.io` was `apiextensions.k8s.io/v1`, however in 1.8, it is `apiextensions.k8s.io/v1beta1` same applies to many others.

Is this expected?  I don't see anything about it in the change notes or release notes.

[x] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[x] Developer Infrastructure
[x] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
1.8.0

**How was Istio installed?**
istioctl generate manifest 

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
This was intentional. Basically, right after 1.7 released we got a lot of feedback that dropping Kubernetes 1.15 support was a bad idea (which moving to v1 does). So we switched back to the older one, but we didn't do it in the 1.7 branch since we didn't want such a potentially large change to impact users on patch upgrades.

Did this cause any issues, or just looked wrong?

**Comment by Stono** [comment]
I don't _think_ so.  However I haven't even attempted to deploy it yet - I'm still at the "git diff istioctl output and see what looks wrong".  Happy to close the issue if it's expected and will raise separate issues if we encounter specific problems as a result of the change?

**Comment by howardjohn** [comment]
SGTM. This shouldn't cause issues, and we did a fair bit of testing so I am hopefully it just "looks wrong".
