### ISSUE TITLE
brew version of istioctl says 1.8.0 but gives version 1.8.0-dev

### ISSUE THREAD

**Issue by Crayeth** [istio/istio#29142]
**Bug description**
Brew version of istioctl is mistakenly 1.8.0-dev instead of 1.8.0

**Affected product area (please put an X in all that apply)**
[X] Installation
[X] Test and Release
[X] User Experience
[X] Upgrade

**Expected behavior**
brew version 1.8.0 of istioctl should contain istioctl version 1.8.0 and be able to install 1.8.0

**Steps to reproduce the bug**
brew install istioctl, then run istioctl commands.

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
```
% brew upgrade istioctl
Warning: istioctl 1.8.0 already installed
% istioctl version
no running Istio pods in "istio-system"
1.8-dev
```
**How was Istio installed?**
brew - istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**
MacOS 10.15.7 (19H15)

**Comment by Monkeyanator** [comment]
From what I can tell this is because brew is building `istioctl` from source without setting `VERSION=1.8.0` before running the build ([like our release builder does](https://github.com/istio/release-builder/blob/master/release/build.sh#L40)). Don't know much about homebrew but I think this can be solved by just adding `ENV["VERSION"] = version.to_s` [here](https://github.com/Homebrew/homebrew-core/blob/master/Formula/istioctl.rb#L21) (and then rebuilding the corresponding `bottles`). I'll give it a try and update.

Also note that I don't believe we officially maintain the homebrew formula for `istioctl` and the [officially released](https://github.com/istio/istio/releases/tag/1.8.0) 1.8.0 `istioctl` does not have this issue.

**Comment by Crayeth** [comment]
> From what I can tell this is because brew is building `istioctl` from source without setting `VERSION=1.8.0` before running the build ([like our release builder does](https://github.com/istio/release-builder/blob/master/release/build.sh#L40)). Don't know much about homebrew but I think this can be solved by just adding `ENV["VERSION"] = version.to_s` [here](https://github.com/Homebrew/homebrew-core/blob/master/Formula/istioctl.rb#L21) (and then rebuilding the corresponding `bottles`). I'll give it a try and update.
> 
> Also note that I don't believe we officially maintain the homebrew formula for `istioctl` and the [officially released](https://github.com/istio/istio/releases/tag/1.8.0) 1.8.0 `istioctl` does not have this issue.

ah right i had no idea it did that, i thought it was like helm. I never had it with any of the previous versions but ill give it a try.

**Comment by howardjohn** [comment]
cc @istio/release-managers-1-8

**Comment by Monkeyanator** [comment]
Should be fixed now on latest homebrew. Doing `brew uninstall --force istioctl; brew update; brew install istioctl;` gives me `istioctl` with `istioctl version` -> `1.8.0`.

**Comment by howardjohn** [comment]
Thanks @Monkeyanator !
