### ISSUE TITLE
Istio Operator deployment should have a nodeSelector with the appropriate os and architecture

### ISSUE THREAD

**Issue by backjo** [istio/istio#29269]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
When running the Istio Operator on a k8s cluster with multiple operating systems (Linux, Windows) and multiple architectures (AMD64, ARM64), the Istio Operator deployment can schedule on any node. If it schedules on an ARM or Windows node, it will fail to run. 

[ ] Docs
[X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Istio Operator should have a nodeSelector to limit it to nodes that it is compatible with (or allow users to specify a nodeSelector on the cli) 
**Steps to reproduce the bug**
Try installing the Istio operator on a k8s cluster with multiple operating systems or CPU architectures. 
**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by Type1J** [comment]
I added
```yaml
       nodeSelector:                                                             
         kubernetes.io/os: linux                                                 
         kubernetes.io/arch: amd64  
```
at the same level as `containers` in the pods `template` area to `istio-1.8.0/manifests/charts/istio-control/istio-discovery/templates/deployment.yaml` and a few other deployments before installing with the Terraform Helm provider.

I'm not sure if arm64 is or will be supported soon, but `kubernetes.io/arch: amd64` could be taken out to let it schedule on an arm64 node instead of amd64.

Both of these should probably be a Helm values (in `values.yaml`) unless all CPUs for both Windows and Linux are supported (unlikely).

A Windows node doesn't have a taint, and there isn't a Windows taint as far as I know, so when someone adds a Windows node to their cluster, then deploys Istio, Istio pods get scheduled on the Windows nodes, which cause them to fail, since the image is only available for Linux.

As stated above, the `amd64` selector is likely necessary as well, but many cloud providers offer `arm64` VMs, and therefore nodes will eventually be `arm64` as well, which may cause Istio to fail, but, since it's still Linux, that could be fixed by pushing an `arm64` image with the same name and tag. The same could be said for Windows (`amd64` and `arm64`), but I'm guessing that might require some tweaking. Until the new images are pushed, we'll need these `nodeSelector`s added to the deployments.

**Comment by jellebens** [comment]
https://github.com/istio/istio/issues/26583

**Comment by morvencao** [comment]
For istio deployment, you can customize node selector or nodeAffinity by the k8s settings api, see: https://github.com/istio/istio/tree/master/operator#new-api-customization
For istio operator itself, currently the `istioctl operator init` and istio-operator chart doesn't contains the flag, but you can use `istioctl operator dump` to get the istio-operator manifests and customize it before applying into the cluster.

**Comment by Type1J** [comment]
I haven't tried this solution, yet, but it seems that Windows nodes can have a taint to prevent existing Linux containers from scheduling on them: https://kubernetes.io/docs/setup/production-environment/windows/user-guide-windows-containers/#taints-and-tolerations

**Comment by jellebens** [comment]
> I haven't tried this solution, yet, but it seems that Windows nodes can have a taint to prevent existing Linux containers from scheduling on them: https://kubernetes.io/docs/setup/production-environment/windows/user-guide-windows-containers/#taints-and-tolerations

This is how I fixed it. I tainted the windows nodes so no linux workloads get scheduled and I added tolerations on the windows workloads. but its a workaround and not a fix :)

**Comment by VIjayHP** [comment]
@jellebens Does Istio (any version) has published it's docker images which supports Multi Architecture ( x86, ppc64le etc..) ?

**Comment by Type1J** [comment]
@andreamaruccia, I'm not sure why you thumbs-downed a link to official documentation. I have since implemented this solution that had many existing Linux images that needed a few Windows images. Please explain.

**Comment by morvencao** [comment]
@VIjayHP AFAIK, istio doesn't provide ppc64le artifact, but you can build it from envoy and istio source code on ppc64le machine.

**Comment by Type1J** [comment]
@andreamaruccia I'm not sure if I understand the thumbs-down. Istio doesn't yet support Windows, and while Istio, and new deployments, should include a `nodeSelector`, existing `.yaml` files need to work without modification, and using a taint for that is exactly what that mechanism is designed to do, and it only requires tolerations to be added to new Windows deployments. To what is the thumbs-down in reference?

**Comment by matheusfm** [comment]
I’m interested in working on this issue.
I agree the operator helm chart should have parameters to allow users to specify the node selection requirements: `nodeSelector`, `tolerations` and `affinity`. The operator chart would keep it simple.

**Comment by Type1J** [comment]
#31262 is blocked for lack of attention from an Istio team member, and this issue has gone stale. Now that many PRs are integrated for Envoy on Windows, this issue should be examined as part of an "Istio on Windows" effort. We know that there must be at least 1 Linux node, but in many cases, a few projects are Windows only, and that blocks us from using Istio to manage all traffic (we can only mamage the Linux part, and have to treat Windows as external to the mesh).

**Comment by Type1J** [comment]
Ok, I guess a taint on Windows nodes is the only solution. When is Istio going to support Windows?
