### ISSUE TITLE
[Testing] Support real stackdriver

### ISSUE THREAD

**Issue by nmittler** [istio/istio#29284]
We currently have a fake SD test component and a selection of tests that use it. We should add support for real SD as well. To do this, we'll want an abstraction to the SD component so that tests don't care if they're using real/fake SD. The choice can be controlled by a flag (i.e. either all SD tests run against the real or fake SD ... no mix/match in the same job).

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[x] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by nmittler** [comment]
fyi @douglas-reid @mandarjog since we've talked about this in the past.

**Comment by bianpengyuan** [comment]
not stale.

**Comment by nmittler** [comment]
@bianpengyuan @douglas-reid is this still something on your roadmap?

**Comment by bianpengyuan** [comment]
@nmittler yes, will get back on this once I have more time.

**Comment by nmittler** [comment]
@mandarjog @douglas-reid @bianpengyuan any updates here? Are we prioritizing this work?

**Comment by bianpengyuan** [comment]
Still on my todo list. Need to refresh my memory on this but I think the test can pass now, it is just to enable it at postsubmit.

**Comment by nmittler** [comment]
@bianpengyuan ah great ... so this is essentially fixed?

**Comment by bianpengyuan** [comment]
> @bianpengyuan ah great ... so this is essentially fixed?

Well, I did a quick check yesterday and looks like test was broken, likely because of some new changes: https://github.com/istio/istio/pull/36497. Will need some work to fix that.

**Comment by douglas-reid** [comment]
Was there more work here?

**Comment by bianpengyuan** [comment]
Looks like prow pods now actually lacks permission to report to stackdriver (test failure: https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/38281/integ-telemetry_istio/1512123541196115968 from https://github.com/istio/istio/pull/38281) Things left to do in this issue:

1. Figure out why prow cannot make direct telemetry report to stackdriver. This is likely due to shift to workload identity, and SD report permission needs to be bind to prow service account.
2. Adjust query duration to not rely on timing. Basically address this comment: https://github.com/istio/istio/pull/36497#discussion_r772617563. We should use log name to distinguish logs from different cases.
3. Enable test with real stackdriver at postsubmit like https://github.com/istio/test-infra/pull/3718.

**Comment by andrewmash** [comment]
@douglas-reid is working on this.
