### ISSUE TITLE
Update base images to debian10/focal

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#29326]
I think the main block is iptables. Maybe we can do:

```
# update-alternatives --set iptables /usr/sbin/iptables-legacy
# update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
# update-alternatives --set arptables /usr/sbin/arptables-legacy
# update-alternatives --set ebtables /usr/sbin/ebtables-legacy
```
(from https://wiki.debian.org/nftables).

One concern I have, I do not know how to do this for the distroless version. Should be feasible though

**Comment by daixiang0** [comment]
@howardjohn i would like to update it, now we use debian9 distroless as base image and build as `gcr.io/istio-release/iptables`, while I can not find dockerfile for it:
```
pilot/docker/Dockerfile.proxyv2:13:FROM gcr.io/istio-release/iptables:d71c854a55d9661ea1c45ee4391335a67030a617 as distroless
```

**Comment by howardjohn** [comment]
documentation for where iptables comes from is in https://github.com/istio/istio/pull/29122

**Comment by howardjohn** [comment]
I would focus on the non-distroless first, the hard part is iptables

**Comment by MinchoVelev** [comment]
Hi everyone!
It has been 3 months since the issue was opened.
Currently there are 21 vulnerabilities in glibc 2.24-11+deb9u4 (version used by the proxy distroless image) detected by protecode, you can find the list below. 
Is there a place where I can check your assessment of those vulnerabilities and if it is a concern for Istio?
In the current state Istio 1.9 is unusable for our service.

When can we expect a newer version of glibc to be included in the distroless based image? The non-distroless based image has more than 600 vulnerabilities, so it's not an option. 


Component | Version | Latest version | CVE | CVSS3 | CVE publication date | Object | Object full path | Object SHA1 | Distribution package | Vulnerability URL
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
glibc | 2.24-11+deb9u4 | 2.33 | CVE-2019-9169 | 9.8 | 2019-02-26T02:29:00Z | libc-2.24.so | proxyv2-distroless.tar.gz:89e8b10fa9ecbf2ee00debde2fc4d403e1f8f4ac276956ffd84d657cac9a03da/layer.tar:lib/x86_64-linux-gnu/libc-2.24.so | 81a6361b56ed07f58021f6a4795a58d565253956 | debian | http://nvd.nist.gov/vuln/detail/CVE-2019-9169
glibc | 2.24-11+deb9u4 | 2.33 | CVE-2018-6551 | 9.8 | 2018-02-02T14:29:00Z | libc-2.24.so | proxyv2-distroless.tar.gz:89e8b10fa9ecbf2ee00debde2fc4d403e1f8f4ac276956ffd84d657cac9a03da/layer.tar:lib/x86_64-linux-gnu/libc-2.24.so | 81a6361b56ed07f58021f6a4795a58d565253956 | debian | http://nvd.nist.gov/vuln/detail/CVE-2018-6551
glibc | 2.24-11+deb9u4 | 2.33 | CVE-2018-6485 | 9.8 | 2018-02-01T14:29:00Z | libc-2.24.so | proxyv2-distroless.tar.gz:89e8b10fa9ecbf2ee00debde2fc4d403e1f8f4ac276956ffd84d657cac9a03da/layer.tar:lib/x86_64-linux-gnu/libc-2.24.so | 81a6361b56ed07f58021f6a4795a58d565253956 | debian | http://nvd.nist.gov/vuln/detail/CVE-2018-6485
glibc | 2.24-11+deb9u4 | 2.33 | CVE-2018-1000001 | 7.8 | 2018-01-31T14:29:00Z | libc-2.24.so | proxyv2-distroless.tar.gz:89e8b10fa9ecbf2ee00debde2fc4d403e1f8f4ac276956ffd84d657cac9a03da/layer.tar:lib/x86_64-linux-gnu/libc-2.24.so | 81a6361b56ed07f58021f6a4795a58d565253956 | debian | http://nvd.nist.gov/vuln/detail/CVE-2018-1000001
glibc | 2.24-11+deb9u4 | 2.33 | CVE-2019-25013 | 5.9 | 2021-01-04T18:15:00Z | libc-2.24.so | proxyv2-distroless.tar.gz:89e8b10fa9ecbf2ee00debde2fc4d403e1f8f4ac276956ffd84d657cac9a03da/layer.tar:lib/x86_64-linux-gnu/libc-2.24.so | 81a6361b56ed07f58021f6a4795a58d565253956 | debian | http://nvd.nist.gov/vuln/detail/CVE-2019-25013
glibc | 2.24-11+deb9u4 | 2.33 | CVE-2020-6096 | 8.1 | 2020-04-01T22:15:00Z | libc-2.24.so | proxyv2-distroless.tar.gz:89e8b10fa9ecbf2ee00debde2fc4d403e1f8f4ac276956ffd84d657cac9a03da/layer.tar:lib/x86_64-linux-gnu/libc-2.24.so | 81a6361b56ed07f58021f6a4795a58d565253956 | debian | http://nvd.nist.gov/vuln/detail/CVE-2020-6096
glibc | 2.24-11+deb9u4 | 2.33 | CVE-2020-1751 | 7.0 | 2020-04-17T19:15:00Z | libc-2.24.so | proxyv2-distroless.tar.gz:89e8b10fa9ecbf2ee00debde2fc4d403e1f8f4ac276956ffd84d657cac9a03da/layer.tar:lib/x86_64-linux-gnu/libc-2.24.so | 81a6361b56ed07f58021f6a4795a58d565253956 | debian | http://nvd.nist.gov/vuln/detail/CVE-2020-1751
glibc | 2.24-11+deb9u4 | 2.33 | CVE-2021-3326 | 7.5 | 2021-01-27T20:15:00Z | libc-2.24.so | proxyv2-distroless.tar.gz:89e8b10fa9ecbf2ee00debde2fc4d403e1f8f4ac276956ffd84d657cac9a03da/layer.tar:lib/x86_64-linux-gnu/libc-2.24.so | 81a6361b56ed07f58021f6a4795a58d565253956 | debian | http://nvd.nist.gov/vuln/detail/CVE-2021-3326
glibc | 2.24-11+deb9u4 | 2.33 | CVE-2019-9192 | 7.5 | 2019-02-26T18:29:00Z | libc-2.24.so | proxyv2-distroless.tar.gz:89e8b10fa9ecbf2ee00debde2fc4d403e1f8f4ac276956ffd84d657cac9a03da/layer.tar:lib/x86_64-linux-gnu/libc-2.24.so | 81a6361b56ed07f58021f6a4795a58d565253956 | debian | http://nvd.nist.gov/vuln/detail/CVE-2019-9192
glibc | 2.24-11+deb9u4 | 2.33 | CVE-2018-20796 | 7.5 | 2019-02-26T02:29:00Z | libc-2.24.so | proxyv2-distroless.tar.gz:89e8b10fa9ecbf2ee00debde2fc4d403e1f8f4ac276956ffd84d657cac9a03da/layer.tar:lib/x86_64-linux-gnu/libc-2.24.so | 81a6361b56ed07f58021f6a4795a58d565253956 | debian | http://nvd.nist.gov/vuln/detail/CVE-2018-20796
glibc | 2.24-11+deb9u4 | 2.33 | CVE-2009-5155 | 7.5 | 2019-02-26T02:29:00Z | libc-2.24.so | proxyv2-distroless.tar.gz:89e8b10fa9ecbf2ee00debde2fc4d403e1f8f4ac276956ffd84d657cac9a03da/layer.tar:lib/x86_64-linux-gnu/libc-2.24.so | 81a6361b56ed07f58021f6a4795a58d565253956 | debian | http://nvd.nist.gov/vuln/detail/CVE-2009-5155
glibc | 2.24-11+deb9u4 | 2.33 | CVE-2010-3192 | 0.0 | 2010-10-14T05:58:00Z | libc-2.24.so | proxyv2-distroless.tar.gz:89e8b10fa9ecbf2ee00debde2fc4d403e1f8f4ac276956ffd84d657cac9a03da/layer.tar:lib/x86_64-linux-gnu/libc-2.24.so | 81a6361b56ed07f58021f6a4795a58d565253956 | debian | http://nvd.nist.gov/vuln/detail/CVE-2010-3192
glibc | 2.24-11+deb9u4 | 2.33 | CVE-2019-6488 | 7.8 | 2019-01-18T19:29:00Z | libc-2.24.so | proxyv2-distroless.tar.gz:89e8b10fa9ecbf2ee00debde2fc4d403e1f8f4ac276956ffd84d657cac9a03da/layer.tar:lib/x86_64-linux-gnu/libc-2.24.so | 81a6361b56ed07f58021f6a4795a58d565253956 | debian | http://nvd.nist.gov/vuln/detail/CVE-2019-6488
glibc | 2.24-11+deb9u4 | 2.33 | CVE-2016-10739 | 5.3 | 2019-01-21T19:29:00Z | libc-2.24.so | proxyv2-distroless.tar.gz:89e8b10fa9ecbf2ee00debde2fc4d403e1f8f4ac276956ffd84d657cac9a03da/layer.tar:lib/x86_64-linux-gnu/libc-2.24.so | 81a6361b56ed07f58021f6a4795a58d565253956 | debian | http://nvd.nist.gov/vuln/detail/CVE-2016-10739
glibc | 2.24-11+deb9u4 | 2.33 | CVE-2017-12132 | 5.9 | 2017-08-01T16:29:00Z | libc-2.24.so | proxyv2-distroless.tar.gz:89e8b10fa9ecbf2ee00debde2fc4d403e1f8f4ac276956ffd84d657cac9a03da/layer.tar:lib/x86_64-linux-gnu/libc-2.24.so | 81a6361b56ed07f58021f6a4795a58d565253956 | debian | http://nvd.nist.gov/vuln/detail/CVE-2017-12132
glibc | 2.24-11+deb9u4 | 2.33 | CVE-2016-10228 | 5.9 | 2017-03-02T01:59:00Z | libc-2.24.so | proxyv2-distroless.tar.gz:89e8b10fa9ecbf2ee00debde2fc4d403e1f8f4ac276956ffd84d657cac9a03da/layer.tar:lib/x86_64-linux-gnu/libc-2.24.so | 81a6361b56ed07f58021f6a4795a58d565253956 | debian | http://nvd.nist.gov/vuln/detail/CVE-2016-10228
glibc | 2.24-11+deb9u4 | 2.33 | CVE-2015-8985 | 5.9 | 2017-03-20T16:59:00Z | libc-2.24.so | proxyv2-distroless.tar.gz:89e8b10fa9ecbf2ee00debde2fc4d403e1f8f4ac276956ffd84d657cac9a03da/layer.tar:lib/x86_64-linux-gnu/libc-2.24.so | 81a6361b56ed07f58021f6a4795a58d565253956 | debian | http://nvd.nist.gov/vuln/detail/CVE-2015-8985
glibc | 2.24-11+deb9u4 | 2.33 | CVE-2020-1752 | 7.0 | 2020-04-30T17:15:00Z | libc-2.24.so | proxyv2-distroless.tar.gz:89e8b10fa9ecbf2ee00debde2fc4d403e1f8f4ac276956ffd84d657cac9a03da/layer.tar:lib/x86_64-linux-gnu/libc-2.24.so | 81a6361b56ed07f58021f6a4795a58d565253956 | debian | http://nvd.nist.gov/vuln/detail/CVE-2020-1752
glibc | 2.24-11+deb9u4 | 2.33 | CVE-2020-10029 | 5.5 | 2020-03-04T15:15:00Z | libc-2.24.so | proxyv2-distroless.tar.gz:89e8b10fa9ecbf2ee00debde2fc4d403e1f8f4ac276956ffd84d657cac9a03da/layer.tar:lib/x86_64-linux-gnu/libc-2.24.so | 81a6361b56ed07f58021f6a4795a58d565253956 | debian | http://nvd.nist.gov/vuln/detail/CVE-2020-10029
glibc | 2.24-11+deb9u4 | 2.33 | CVE-2019-7309 | 5.5 | 2019-02-03T02:29:00Z | libc-2.24.so | proxyv2-distroless.tar.gz:89e8b10fa9ecbf2ee00debde2fc4d403e1f8f4ac276956ffd84d657cac9a03da/layer.tar:lib/x86_64-linux-gnu/libc-2.24.so | 81a6361b56ed07f58021f6a4795a58d565253956 | debian | http://nvd.nist.gov/vuln/detail/CVE-2019-7309
glibc | 2.24-11+deb9u4 | 2.33 | CVE-2019-19126 | 3.3 | 2019-11-19T22:15:00Z | libc-2.24.so | proxyv2-distroless.tar.gz:89e8b10fa9ecbf2ee00debde2fc4d403e1f8f4ac276956ffd84d657cac9a03da/layer.tar:lib/x86_64-linux-gnu/libc-2.24.so | 81a6361b56ed07f58021f6a4795a58d565253956 | debian | http://nvd.nist.gov/vuln/detail/CVE-2019-19126

**Comment by steakunderscore** [comment]
This is still an outstanding issue

**Comment by howardjohn** [comment]
It is on our roadmap to update this.

**Comment by MinchoVelev** [comment]
@howardjohn 
Could you tell us some time estimate, for when is it planned?

**Comment by psingarakannan** [comment]
@howardjohn
We are waiting for the patch. Let us know when can we get the patch.
