### ISSUE TITLE
Decouple DNS and AutoAllocated address

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#29324]
Currently we have two closely related features:

1) Resolving DNS, substituting for kube-dns for VMS
2) Resolving DNS, to handle ServiceEntry, local caching, etc

These are controlled by the same setting.

Since (2) has a bunch of bugs (see https://github.com/istio/istio/pull/29260), I think it may make sense to split these two options. This would allow VMs to resolve Kubernetes addresses, which shouldn't cause issues, while allowing us to experiment with (2) safely.

cc @stevenctl @hzxuzhonghu

**Comment by hzxuzhonghu** [comment]
Currently Istio allocates ip address to hostnames defined in ServiceEntry which does not have addresses. I think we should not allocate if the resolution is DNS, otherwise, it will influence access to the defined host with a different port which is not specified.

When it comes to ServiceEntry includes k8s service FQDN, no ip allocated for it. But in this case istio may have two same services, for vm, this may lead to dns resolve failure depends on which service takes precedence.  (Maybe we can handle this race) 

It is absolutely not a good practice to define a K8S service within a SE

**Comment by howardjohn** [comment]
> . I think we should not allocate if the resolution is DNS, otherwise, it will influence access to the defined host with a different port which is not specified.

I  not sure why this applies only to resolution DNS, doesn't it apply for all cases?

**Comment by hzxuzhonghu** [comment]
For SE which has STATIC resolution, we should continue allocating ip for the hostname, which maybe a virtual one.
