### ISSUE TITLE
Fix and test multicluster with .global stub domain

### ISSUE THREAD

**Issue by nmittler** [istio/istio#29335]
As of Istio 1.8, we no longer recommend using the [`.global` stub domain](https://istio.io/v1.6/docs/setup/install/multicluster/gateways/) for multi-primary configurations.

It was never well tested and has been in some state of broken since 1.6, as shown in bug reports:

- https://github.com/istio/istio/issues/29308
- https://github.com/istio/istio/issues/27321
- https://github.com/istio/istio/issues/26990

We should add some minimal testing and get it working again to ease users migration story from earlier (alpha) versions of multicluster.

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[x] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by kenthua** [comment]
Use Case: StatefulSet replicas (redis & cockroachdb) - multi-cluster / multi-network

* Works in 1.6 & 1.7
* ServiceEntry with `.global` host was used to refer to individual replicas in the other cluster.
* In 1.8 while pinging the host x.global resolves to a 240.x IP as set in the service entry.  Traffic doesn't appear to be flowing
* If `.global` is going away, thoughts on how this use case may be approached withe new `.svc.cluster.local` path?

**Comment by howardjohn** [comment]
@nmittler is this still desired?

**Comment by nmittler** [comment]
@howardjohn yeah, but it's not a blocker for 1.9. Removed the milestone

**Comment by stevenctl** [comment]
Think we will do this in 1.9.x? Or is it 1.10

**Comment by nmittler** [comment]
Not entirely sure if we have bandwidth ... it would be good to get in 1.9.x. I suspect 1.10 at the earliest

**Comment by brian-avery** [comment]
@nmittler are we pushing this off for 1.11?

**Comment by nmittler** [comment]
@brian-avery Yes, I've updated the milestone.

**Comment by nmittler** [comment]
@stevenctl I'm assigning to you so we don't forget about this. Feel free to prioritize or re-assign.

**Comment by ryantking** [comment]
@nmittler @stevenctl Are we pushing this to 1.11?

**Comment by stevenctl** [comment]
Either pushing or dropping in favor of something else.

**Comment by rytswd** [comment]
Sorry to jump in, but I'm curious how this `.global`-like communication support will be treated going forward. With the remote secret and Kubernetes API server integration since v1.8, multicluster is much easier to configure and mostly automatic, but that also means it doesn't provide the granular control of exposed services. I personally have this use case of connecting from one cluster to the other, but only for a limited number of services. I managed to get this to work with ServiceEntry defined for both source and target clusters for services I need (more details in https://github.com/istio/istio/issues/32848#issuecomment-898006638). The `.global`-like setup is also useful when you want to specifically hit the service in a remote cluster (`.global`-like, as I understand any custom domain can be used). AFAIK, the new multicluster setup using `istioctl x create-remote-secret` cannot achieve this. Please let me know if there is a better way!

Although it is quite cumbersome to define many ServiceEntry resources in multiple clusters, it is still great to have such an option available. I understand this is not the most standard setup, and am not sure how this plays with other multicluster related efforts and changes such as Kubernetes MCS, but possibly worth having a dedicated section in the documentation. If there is anything I can help with, I'd be more than happy to!

**Comment by stevenctl** [comment]
For granular control, we still have the [clusterLocal option in mesh config](https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig-ServiceSettings-Settings) although it's not the best API. 

We're also adding some new locality load balancing configuration options, which again isn't the _best_ form of policy for this since it only sets priority and doesn't completely restrict using the different endpoints. https://github.com/istio/api/pull/2043

I think MCS is at the root of how we tackle this problem, but we need our own stable API for it that works with the newer multi-cluster model.

**Comment by rytswd** [comment]
Thanks for the details, those are interesting, but indeed do not provide the granular control I'm after.

Although I understand there will be further changes with MCS and other API updates, using ServiceEntry + DestinationRule + Gateway resources to get the granular multicluster control is stable from Istio API point of view, and potentially worth adding documentation for? Even with the new multicluster model Istio introduces in the future, I imagine the above resources will keep their backward compatibility, and having doc test for such use case may be helpful for migration when the new model is ready?

If that sounds like a possibility, I can work on creating a new dedicated doc with test steps to see how that works with other doc. I've never worked on the doc test, but the steps look to be well documented so I can give it a try 👍

**Comment by nmittler** [comment]
@stevenctl @howardjohn IIRC this is no longer feasible since a number of other changes have widened the gap with getting the stub domain working properly. I believe with workarounds such as https://github.com/istio/istio/issues/29335#issuecomment-950967806 the need for the stub domain is significantly reduced. Can we just close this?
