### ISSUE TITLE
make docker fails in a clean environment without manually generated keys

### ISSUE THREAD

**Issue by sdake** [istio/istio#2936]
make docker fails in a clean environment.

Simple solution is to run:
```
security/bin/gen-keys.sh
```

Since this mucks with security, I have not yet had a proper chance to evaluate the impact of adding this 1 liner to he documentation (or the make system).

**Comment by mattdelco** [comment]
My pending PR https://github.com/istio/istio/pull/2831 should help address this.  In the week that it's been pending someone committed a set of keys--that was done ~5 days ago and this issue was filed ~2 days ago so I'm not sure if you were in a stale tree or if there's some other issue.

Regardless, the PR I mentioned should handle the running of the gen-keys.sh and made the checked-in certs irrelevant.  A TBD is whether to then make another PR to switch to those certs, or instead just delete them and stick with generating certs.

**Comment by mattdelco** [comment]
For now addressed by PR #2831
