### ISSUE TITLE
Improve MC test documention

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#29610]
We should have some documentation (or tooling improvements) to make it easier to run multicluster tests locally. Users can do `prow/integ-suite-kind.sh --topology MULTICLUSTER_SINGLE_NETWORK test.integration.multicluster.kube.presubmit` but this cleans up the clusters on failure, builds images, etc.

It would be nice to just have a way to run `setup-multicluster` which outputs a bunch of kubeconfig files (for debugging the clusters directly) and the flags to pass to `go test` to get the tests to use the clusters.

Additionally, it would be useful to have a diagram of the cluster toplogy.

cc @irisdingbj @nmittler @stevenctl

**Comment by stevenctl** [comment]
https://gist.github.com/stevenctl/583c19a974dbed28acef84a7101e0de8

**Comment by stevenctl** [comment]
Btw, having a bunch of issues with this on Mac (I don't usually bother with multicluster kind on mac because of this):

- We make the kubeconfig files use docker network IPs, `kubectl` run outside of docker will fail because there is no docker0 interface on mac. 
- The `date` command as part of `trace` uses GNU `date` which breaks on OSX. 
- Sometimes I see `unbound variable` issues that don't occur in CI.. still investigating that one.

**Comment by howardjohn** [comment]
I have been able to get it working with `go test -p 1 -v -count=1 -tags=integ ./tests/integration/security/filebased_tls_origination/... -run TestEgressGatewayTls -timeout 30m --istio.test.ci --istio.test.pullpolicy=IfNotPresent --istio.test.work_dir=/tmp/kubeconfig --istio.test.hub=gcr.io/istio-testing --istio.test.tag=latest --istio.test.kube.config=/tmp/tmp.W0ADIvLwOJ/cluster1,/tmp/tmp.W0ADIvLwOJ/cluster2,/tmp/tmp.W0ADIvLwOJ/cluster3,/tmp/tmp.W0ADIvLwOJ/cluster4,/tmp/tmp.W0ADIvLwOJ/cluster5 --istio.test.kube.networkTopology=0:test-network-0,1:test-network-0,2:test-network-0,3:test-network-1,4:test-network-1 --istio.test.kube.configTopology=0:0,1:0,2:2,3:3,4:0 --istio.test.kube.controlPlaneTopology=0:0,1:0,2:2,3:3,4:0`

Not simple, but it does work. We can probably do some cleanup so that once we spin up the clusters we easily have all the MC specific flags specified

**Comment by stevenctl** [comment]
I've updated https://github.com/istio/istio/wiki/Istio-Test-Framework to reflect the current state of the framework. 

@howardjohn You've been able to spin up the KinD containers for multicluster on Mac using our script?  Even if I remove calls to `trace` to prevent the date issue, I still have issues because the test framework tries to use the `172.x.x.x` docker network addresses we put in the kubeconfig files, and mac doesn't have the docker bridge.

**Comment by howardjohn** [comment]
I have not, I don't have a mac

**Comment by brian-avery** [comment]
Hey @stevenctl any update here? It's marked as a P0 for 1.9. Thanks!

**Comment by stevenctl** [comment]
I'm not sure if that's an accurate prioritization. I've updated the docs quite a bit, I'll let someone else sign-off on the quality there. I think for now we can downgrade this to p1.

**Comment by zhlsunshine** [comment]
Hi @stevenctl, shall we move this issue to 1.12? or should this issue be closed?
