### ISSUE TITLE
segfault in CI: TestMutualTlsOrigination in SDS codepath

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#30199]
Test log: https://prow.istio.io/view/gs/istio-prow/logs/integ-k8s-116_istio_postsubmit/1351710519169388544

Crashes:
* https://storage.googleapis.com/istio-prow/logs/integ-k8s-116_istio_postsubmit/1351710519169388544/artifacts/security-sds-tls-origination-f2/_suite_context/istio-state-595615428/cluster-0/istio-eastwestgateway-6b97959dc5-9btr2_istio-proxy.previous.log
* https://storage.googleapis.com/istio-prow/logs/integ-k8s-116_istio_postsubmit/1351710519169388544/artifacts/security-sds-tls-origination-f2/_suite_context/istio-state-595615428/cluster-0/istio-ingressgateway-69f6f5677-fpdld_istio-proxy.previous.log

Marking a release blocker until proven otherwise (ie not a regression or something that can be triggered)

**Comment by howardjohn** [comment]
@tbarrella interested in picking this up?

**Comment by incfly** [comment]
/cc @Monkeyanator who has context on this test itself.

though the actual problem is about the Envoy segfault.

**Comment by lambdai** [comment]
It's a known and long lasting race condition that host may destroyed on worker thread. I was not pushing hard and improve my fix on envoy upstream. 

Meanwhile @Monkeyanator is it possible to close the tls connection first in the test case? If the connection is gracefully closed before SDS, it's highly likely the envoy bug won't hit. That's why these failures in production are rare.

We can do it in parallel.

**Comment by Monkeyanator** [comment]
I can take a look for sure, although I don't think I have much context on this particular test. Now that I'm looking at it, is there a reason not to get rid of the `security/sds_egress` suite (which I did write a while back)? Looks like it's been skipped for a while now and tests for the same thing as this test except in an outdated way

**Comment by howardjohn** [comment]
>  is there a reason not to get rid of the security/sds_egress suite (which
I did write a while back)? Looks like it's been skipped for a while now and
tests for the same thing as this test except in an outdated way

We should probably fix it if its useful - if not we can remove. I think
this is not in the skipped test though

**Comment by incfly** [comment]
@JimmyCYJ Now looking more closely I think `TestMutualTlsOrigination` is added by @nschhina . https://github.com/istio/istio/pull/25520/files

--- 

@Monkeyanator seems like I mistake the `sds_tls_origination` (the test causing the failure, `TestSdsEgressGatewayIstioMutual`) with `sds_egress` (yours, skipped now). Sorry, My bad. `sds_egress` was skipped because of flakiness because  I think it has something to do with the way we apply configuration and then wait in the test.
https://github.com/istio/istio/issues/17933

--- 

@lambdai do you mean this is the same as https://github.com/envoyproxy/envoy/issues/13209? This time the stack trace seems different though? If so, What makes you convince the root cause is the same?

**Comment by lambdai** [comment]
@incfly The idea is that there are several conditions trigger this bug, starting with the host destroyed on worker threads as you discovered first.

It can be avoided by not destroying SDS api, or delegate the subscription operations to master thread, or delay the the XDS stream destroy.

**Comment by lambdai** [comment]
Confirmed with @howardjohn, set to P2 since it's not regression and the test case is failing rarely.
And no extra efforts at istio code, leave it to envoy.
