### ISSUE TITLE
quota should not overshoot by 20% over an average period

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#3028]
#3020

**Comment by qiwzhang** [comment]
There are some error margin in current quota prefetch algorithm.   It is from latency between client and server.   The margin is big, also %30, for small rate limit window, such as per second.   For big window,  such as per minute, margin can be small as 1%, 2%

Workaround is to define bigger rate limit window,  at least 10 second.  
For example, if you want 1k qps,   you define 10k with 10s window.

**Comment by mandarjog** [comment]
There is a problem with `10k / 10s`: It means that we will actually allow ~ `10k` in the 1st second.
If your intent was to allow `1k` qps this translation has made it worse.

**Comment by douglas-reid** [comment]
I think this needs attention.

From offline conversation:

> The main algorithm allows for overage in Mixer client prefetch, so 100 rps could allow up to 130 rps. However, when running on multicore machines, the prefetch buckets are segregated by thread. When running under very low load, we may hit minQuotafetch (perhaps 1). If every thread fetches 1 token from mixer, then one of the threads may not get any tokens. If traffic happens to hit this thread, we will get 429.
This way we will have a lower limit than advertised. 

> For higher values of rate limits, current model works ok. However when we are testing very low rate limits we hit boundary conditions.

@geeknoid @kyessenov @mandarjog

**Comment by qiwzhang** [comment]
#2 is already there. It has a predict_window of 1 second.  it counts how many requests in the window and prefetch that amount. 

I will look into #1, to make it prefetch bucket multi thread.

**Comment by qiwzhang** [comment]
Hmm,  since quota is part of Check call, it is not easy to separate Check cache with quota prefetch.   If we want to use one quota prefetch for all worker threads,  we have to make Check cache for all worker threads too.

This is not easy for Envoy.  Each worker thread has its own grpc transport.  They could not be shared.

It also means using mutex to protect the cache.   Envoy doesn't like mutex in general.

**Comment by geeknoid** [comment]
Yes, having a shared check cache is highly desirable for the same reason.

I realize that sharing between threads can lead to contention, but there
are substantial upsides in reducing the number of blocking RPC calls and
improve quota usage.

**Comment by kyessenov** [comment]
Partitioning the cache can improve performance as long as it respects the locality. The problem is that the cache right now is partitioned by workers (inconsistent with key locality), rather than by destination/source (which is much more likely to be consistent with policies). So we can avoid some of the contention, if there are several caches grouped by some primary attributes.

**Comment by geeknoid** [comment]
Given that the cache access rate is limited to the request rate arriving at
the proxy, it puts an upper limit on potential contention:

- The critical region for a typical cache write should usually be a few
dozen instructions. So that's a few nanoseconds, compared to a request rate
of say ~10000 QPS or 10 microsecond per request.

- Of course, cache reads can be non-blocking and executed in parallel.

I think a naive implementation should deliver virtually contention-free
behavior in the real world. If contention becomes an issue, then sharding
the cache is always an option as Kuat mentions. You can also quantize
insertions into the cache in order to minimize the occurrence of blocking
writes, depending on how the cache data is laid out.

**Comment by douglas-reid** [comment]
I'm going to close this issue. All work on rate-limiting has switched to direct envoy integrations (example: #22068). There is no further work scheduled for Mixer rate-limiting, and I do not believe this issue will be resolved. It has been almost 2 years without further updates, and Mixer is being fully removed after the next release.
