### ISSUE TITLE
Memory leak in istio-proxy

### ISSUE THREAD

**Issue by nikkout** [istio/istio#30504]
[cpu.zip](https://github.com/istio/istio/files/5894320/cpu.zip)

(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
Istio-proxy is consuming increasing amount of memory for an application with high HTTP traffic (7000 qps). Cpu utilization remains at 100% after traffic ends and memory increases continuously. Connection remain hanging in Close_wait state. 

[ ] Docs
[ ] Installation
[X] Networking
[X] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Istio-proxy's memory shouldn't increase continuously. Cpu usage should decrease after traffic is ended and connections should close 

**Steps to reproduce the bug**
I have uploaded the cpu profile taken from the envoy with the profiler tool.
Also the following logs appear in the sidecar logs repeatedly
2021-01-29T10:18:18.203791Z    trace    envoy http2    [C1039] sent frame type=3
2021-01-29T10:18:18.203794Z    debug    envoy http2    [C1039] sent reset code=0
2021-01-29T10:18:18.203797Z    trace    envoy http2    [C1039] about to send frame type=3, flags=0
2021-01-29T10:18:18.203800Z    trace    envoy http2    [C1039] send data: bytes=13
2021-01-29T10:18:18.203803Z    trace    envoy connection    [C1039] writing 13 bytes, end_stream false
2021-01-29T10:18:18.203791Z    trace    envoy http2    [C1039] sent frame type=3
2021-01-29T10:18:18.203794Z    debug    envoy http2    [C1039] sent reset code=0
2021-01-29T10:18:18.203797Z    trace    envoy http2    [C1039] about to send frame type=3, flags=0
2021-01-29T10:18:18.203800Z    trace    envoy http2    [C1039] send data: bytes=13
2021-01-29T10:18:18.203803Z    trace    envoy connection    [C1039] writing 13 bytes, end_stream false 

**Version**
control plane version: 1.7.4
data plane version: 1.7.4 (3 proxies)

Client Version: v1.18.9
Server Version: v1.18.9

v3.3.3+g5972293

**How was Istio installed?**
helm install

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
Do you have any graph of the memory usage? how high does it go and how quickly?

**Comment by nikkout** [comment]
Unfortunately I don't have a graph. The memory increases a few hundreds kilobytes per second with 7000 qps. Also it has reached up to 25 gb after many hours under full load. In case there are resource limits, typically at 1gb of memory the envoy is killed with OOM several times during traffic, causing the container to restart. The memory doesn't stopped increasing even after the traffic was stopped.

**Comment by howardjohn** [comment]
Got it, so massive leak then if its hitting 25gb. Is this consistently reproducible? And is it reproducible with all traffic or only some specific pattern (http2, some specific app, etc)?

If its reproducible, it may be worthwhile to try temporarily disabling telemetry (`kubectl delete envoyfilter -n istio-system --all`) and/or upgrading to Istio 1.8 or 1.9rc to see if other of those are impacting, just to narrow the scope

Heap dump may also be more useful than CPU (see https://github.com/istio/istio/wiki/Analyzing-Istio-Performance#data-plane)

cc @lambdai

**Comment by nikkout** [comment]
It is reproducible, I will try to capture a heap dump as well. Until now I have observed this leak only with a specific app and http traffic. I will also try to reproduce it with 1.8.

**Comment by crowfrog** [comment]
one correction: it's HTTP2 traffic

**Comment by nikkout** [comment]
I captured the heap dump, also any envoy filters had been removed.
[heap.zip](https://github.com/istio/istio/files/5903720/heap.zip)

**Comment by howardjohn** [comment]
cc @tbarrella as well may be interested ^

**Comment by nikkout** [comment]
I tested with istio 1.6.8 and 1.8.2 and the issue is still there. Even if the application fails to close the connection because of the heavy traffic, shouldn't envoy sidecar be able to handle it?

**Comment by itsmurugappan** [comment]
experiencing similar issue in istio 1.7.7.  We dont have lot of service running , still the proxy seems to be using 1.5 GB

**Comment by hobbytp** [comment]
I decode the cpu&memory profile files. From both cpu profile and heap profiles, seems the issue caused by resetStream? 
[profile-heap.pdf](https://github.com/istio/istio/files/6066464/profile-heap.pdf)
[profile-cpu.pdf](https://github.com/istio/istio/files/6066467/profile-cpu.pdf)

**Comment by alitoufighi** [comment]
We may have faced a similar issue. Having one of our services not released since about one week ago, we noticed an OOMKilled status for an `istio-proxy` sidecar container (having 1GB memory limit). Looking at the memory usage for `istio-proxy` on this service showed the following:
![image](https://user-images.githubusercontent.com/30089812/110170112-f03b6b80-7e0e-11eb-8e24-3208bed693f0.png)

As it is shown, the increase in the amount of memory for previous releases was there too, but a restart has covered the issue.

I don't know if there is something special with that service which causes this rate of increase, but any suggestions to find the root cause are welcomed.

This is a summary of what happened to the `istio-proxy` in one of its pods in the recent week:
![image](https://user-images.githubusercontent.com/30089812/110172137-f121cc80-7e11-11eb-90d8-3948fc68c0b5.png)

Since the CPU usage also increased, I suspect that the issue is the same.

I can confirm that this issue is not specific to this service and persists for our other services as well, but with a lower slope. For example:
![image](https://user-images.githubusercontent.com/30089812/110171266-bec39f80-7e10-11eb-806d-11f75ec14b48.png)


As it constantly keeps growing, I can provide any useful profilings or logs. I will try the ones mentioned in the previous comments and share the results. By the way, our Istio version is `1.8.0`.

**Comment by bianpengyuan** [comment]
FWIW, there is a known leak which has been fixed at 1.8.1 and 1.7.7. So versions before those could leak because of that reason: https://github.com/istio/istio/issues/24720

**Comment by alitoufighi** [comment]
Ah, well, I'm happy that there is already a fix for it. I'll try upgrading Istio soon, and report back it has solved ours as well.

**Comment by crowfrog** [comment]
hi @alitoufighi & @bianpengyuan ,

I think the issue you talk about should be different as this one.
In this ticket, the protocol is HTTP2 and without connection recreating. And the cpu is hunging in 100% when receive stream 0 reset.

**Comment by bianpengyuan** [comment]
> I think the issue you talk about should be different as this one.
In this ticket, the protocol is HTTP2 and without connection recreating. And the cpu is hunging in 100% when receive stream 0 reset.

Yeah, the issue posted original is clearly a different one from #24720. I was not saying this is dup. I added that comment only because some cases like https://github.com/istio/istio/issues/30504#issuecomment-791682373 might be because of that issue, especially versions < 1.8.1 and < 1.7.7.

**Comment by vincent-chan-mox** [comment]
istio v1.9.5 
<img width="978" alt="Screenshot 2021-05-25 at 12 11 16 PM" src="https://user-images.githubusercontent.com/70120829/119438875-c3cf2580-bd53-11eb-802c-f18f90048fad.png">

**Comment by devkoriel** [comment]
This is happening again with istio v1.9.4.
Anyone found some clue?

**Comment by chadlwilson** [comment]
@devkoriel @shydefoo @marcosmoreas88 Since this has been closed now, and is possibly a vague dumping ground for a number of different possible leaks across versions, perhaps you can look at #33181 / #31904 and see if you have a related issue with `1.9.x` that I discovered. It looks like in our case there are leaks somehow proportional to the number of ADS reconnections, which in my case were triggered by a misconfigured `DestinationRule`.
