### ISSUE TITLE
Upgrade sudo package version in istio components images.

### ISSUE THREAD

**Issue by abhioncbr** [istio/istio#30620]
**Describe the feature request**
Recently several articles a bug published related to the [Sudo vulnerability allows privilege escalation to root](https://www.securityweek.com/sudo-vulnerability-allows-privilege-escalation-root). 
Sudo before 1.9.5p2 has a Heap-based Buffer Overflow, allowing privilege escalation to root via "sudoedit -s" and a command-line argument that ends with a single backslash character

**Please update the `sudo` package for all the istio components images.**

**Describe alternatives you've considered**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
We routinely update the base image when we build releases and have tests to ensure we have update to resolve any known CVEs, such as this one. So this will be fixed in the next release. I don't think this is a real threat to Istio as we don't allow root (with or without sudo) anyways.

If you are concerned in the meantime, feel free to try out https://istio.io/latest/docs/ops/configuration/security/harden-docker-images/ Thanks!
