### ISSUE TITLE
IST0102 false positives

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#30874]
On a default install, we now see `Info [IST0102] (Namespace istio-system) The namespace is not enabled for Istio injection. Run 'kubectl label namespace istio-system istio-injection=enabled' to enable it, or 'kubectl label namespace istio-system istio-injection=disabled' to explicitly mark it as not needing injection.`

This suggestion is not good. The injection label has three states, each with different behavior (enabled, disabled, unset, ): https://preliminary.istio.io/latest/docs/setup/additional-setup/sidecar-injection/#controlling-the-injection-policy

This gives misleading advice and adds additional noise to the default installation

**Comment by shamsher31** [comment]
Should we add info on how to unset `istio-injection` like the following?
```
Info [IST0102] (Namespace istio-system) The namespace is not enabled for Istio injection.
Run 'kubectl label namespace istio-system istio-injection=enabled' to enable it,
or 'kubectl label namespace istio-system istio-injection=disabled' to explicitly mark it as not needing injection.
You can also unset `istio-injection` by running `kubectl label namespace istio-system istio-injection-`.
```

Do we really want to display [IST0102] for the `istio-system` namespace, is it required?

**Comment by howardjohn** [comment]
following "You can also unset `istio-injection` by running" doesn't actually make the message go away.

I think there are a few properties analyzers should have
* default install gives no messages
* all analyzers can be removed by following the actions suggested

**Comment by shamsher31** [comment]
cc: @esnible any thoughts on this?

**Comment by esnible** [comment]
At first I couldn't see this problem because my istio-system was labelled.  I had done `istioctl x uninstall --purge`, but the _istio-system_ namespace isn't removed by purge!?!

I can reproduce this by deleting _istio-syste_, doing `istioctl install`, then `istioctl analyze --namespace istio-system`.

Currently we never report this message for
- _kube-system_
- _kube-public_
- _kube-node-lease_
- _local-path-storage_

I will add istio-system to that list.  Any requests for other namespaces, such as _external-istiod_?

**Comment by howardjohn** [comment]
Istio-system is better than nothing, but in reality if we want to avoid false positives the check should be removed entirely. Its perfectly valid to have a namespace unlabeled - it just means that we configure it on a per-pod basis rather than per-namespace basis.

**Comment by esnible** [comment]
No namespaces need to be labeled, that is why this is an `Info`.

We originally did this because users didn't know why their pods weren't getting Istio behavior.
We discussed disabling this for any namespace ending in `-system` and couldn't get agreement on that.  (I wanted no -system namespaces checked).

**Comment by howardjohn** [comment]
Yes but at the time no label and istio-injection=disable had the same behavior, so it was always better to be explicit vs implicit. In 1.9, they do not - no label means "defer to the pod label" and injection=disable means "never inject"

**Comment by howardjohn** [comment]
I also understand that in *most* cases someone not labeling the namespace is because they don't know what they are doing, which makes it a bit tricky unfortunately. Its a useful check in most cases...

**Comment by esnible** [comment]
@howardjohn I didn't follow the change in the meaning of the label.  OK, here are the possibilities

- Namespace has istio.io/rev or istio-injection
  - no IST0102
- Namespace has no label, but is a "system namespace":
  - no IST0102
- Namespaces has pods, **all** pods have istio.io/rev or istio-injection label
   - We don't want IST0102
- Namespace has pods, **some** pods have istio.io/rev or istio-injection label
   - **Anyone have any opinions?**
- Namespace has pods, **no** pods have istio.io/rev or istio-injection label
  - We want IST0102
