### ISSUE TITLE
Add tests to make sure release won't be easily broken

### ISSUE THREAD

**Issue by hklai** [istio/istio#3105]
Release tests are currently broken.

From @mattdelco, "the tests complain that there wasn't a specific sha to test against, which was because the manifest.xml isn't present, which is because the build failed, which is because someone modified the archive creation script."

We should add some unit tests to cover the things that the release process cares about, and prevent people from merging things that can break the release process. And these tests need to be clear about what is broken, and what in the release process needs to be fixed.

Without these, we will only be seeing release failures late and we have to reactively fix the pipeline.

**Comment by kyessenov** [comment]
Why don't we consolidate release/build tool, and make a review by
release/test team mandatory using CODEOWNERS?

**Comment by hklai** [comment]
Yes I like that idea. =)

**Comment by mattdelco** [comment]
While we're quoting me lets also include this other quote:

a way to get greater consistency between CI and CB is to:

1) add a "make sidecar.deb docker.save istio-archive" for the istio repo to CI
or
2) add the items from #1 to the "artifacts" target in the istio repo.

#2 is probably cleaner and avoids the need to keep greenbuilds in sync with istio (or makes it easier to keep the "artifacts" target consistent with cloud_builder.sh [or perhaps just have cloud_builder.sh use the artifacts target). I saw mostly "chicken" about changing the artifacts target since I don't know who else uses it (nor why) and I was trying to limit the scope of how disruptive my large PR would be.
