### ISSUE TITLE
Istio Multi Cluster Installation successful but Verification failed

### ISSUE THREAD

**Issue by nsprash** [istio/istio#31240]
Hi,

I have installed Istio multi cluster as per the official link suggested and installation was successful but verification was failing as it was not able toggle between the services running on multiple clusters.

Followed Installation Steps : https://istio.io/latest/docs/setup/install/multicluster/
Verification link: https://istio.io/latest/docs/setup/install/multicluster/verify/

**Comment by stevenctl** [comment]
Can you try out https://preliminary.istio.io/latest/docs/ops/diagnostic-tools/multicluster/?

Also, can you provide some information about what environment you're running in? 


**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

**Comment by nsprash** [comment]
Hi @stevenctl 

Please find the details as you've asked for it.

[centos@k8smaster ~]$ istioctl version --remote
client version: 1.9.1
control plane version: 1.9.1
data plane version: 1.9.1 (3 proxies)
[centos@k8smaster ~]$
[centos@k8smaster ~]$ kubectl version --short
Client Version: v1.18.14
Server Version: v1.18.16
[centos@k8smaster ~]$
[centos@k8smaster ~]$
[centos@k8smaster ~]$ helm version --short
Client: v2.17.0+ga690bad
Server: v2.17.0+ga690bad
[centos@k8smaster ~]$

I've used installed Istio by following below steps: 
https://istio.io/latest/docs/setup/getting-started/

I'm using bare metal VM's created on Openstack Server.

**Comment by howardjohn** [comment]
@nsprash please give details on what you did, logs, etc. Otherwise there isn't much we can do here.

**Comment by howardjohn** [comment]
We don't have enough information to debug this any more. Please reopen if you can provide some. Thanks!
