### ISSUE TITLE
Support updating mesh config with istioctl command

### ISSUE THREAD

**Issue by yangminzhu** [istio/istio#31387]
**Describe the feature request**
We often need to tweak some fields in the meshconfig for various needs, for example, enabling/updating the access log format, configuring the extension provider, and etc.

Currently we usually ask the user to run `kubectl edit configmap istio` and manually edit the configmap. This is really a pain process, the user needs to be careful about the indent and also not accidentally changing other parts. What's worse, this process cannot be used with CI/CD or other automatic pipeline.

It would be much easier if the istioctl can support such use cases with a simple sub command, for example:

```
istioctl experimental meshconfig merge -f mesh-config-patch.yaml
```

Internally the `meshconfig merge` command can just use the `proto.Merge` for the merge behavior, it won't support all operations but should be good enough for most cases. It should also support the `--revision` flag for meshconfig with non-default name.

cc @istio/wg-user-experience-maintainers for comments.

**Describe alternatives you've considered**
Use `yq` with some shell commands to serialize and modify the meshconfig. The drawback is that `yq` is not a standard program on every system and needs to be installed separately, it also requires the user to learn the `yq` syntax even for simple modifications.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by esnible** [comment]
I like this idea.  I put it on the agenda to discuss at next week's UX working group.

In the past when I have proposed _istioctl_ commands that modify mesh config I have heard that we want _istioctl install_ to be how the mesh config gets modified.  I am curious to see if attitudes have changed.

**Comment by costinm** [comment]
Please, don't. 

Current MeshConfig is 'owned' by the installer of the revision ( istioctl or helm ), any change by user will be overridden. That's how the installer works, and there is no way to prevent that AFAIK.

Last Env WG we discussed the other problem with MeshConfig - if you have multiple revisions it is hard to have settings that apply to all revisions, you need to effectively re-install (reapply) each of them. 

The proposal was to change the code loading MeshConfig and instead of reading istio-REVISION, to also read one or 
more 'fragments', and merge. This will allow proper CI/CD systems to be used. For example config maps with name prefix
'istiod-user-' can be merged. Of course, this behavior will only apply to 1.10+.

The installer should NEVER create such configs - they will be owned by user CI/CD.

The main risk is that a change in the common mesh config can break ALL istio revisions, since it is global. 
This is common with other 'default' settings (DestinationRule, etc) - and we can use the common solution, which
is that we can still use the 'istio.io/rev' annotation to 'bind' the config to a revision. So user can still canary 
the config change, and if canary works apply it to other revisions.

Edit in general is not the right way to operate - so we should not 'promote' it with a dedicated command in 
istioctl. 

In addition, there is an issue of 'separation of concerns' - MeshConfig has many settings, and it is desirable to 
have for example a separate CR with the default log settings, another one with the default proxy config, one 
for authz, etc. This is aligned with the planned 'graduation' of MeshConfig features into proper APIs - we are 
already working on having telemetry separated to a proper CRD. 

The change is super localized - only one function is used to load MeshConfig, we already have code 
to merge ( there is a 'default mesh config' hard-coded ).

**Comment by costinm** [comment]
https://github.com/istio/istio/issues/31400

**Comment by howardjohn** [comment]
> Edit in general is not the right way to operate - so we should not 'promote' it with a dedicated command in istioctl

:+1:

**Comment by yangminzhu** [comment]
@esnible @costinm @howardjohn 

I had this idea only for making it a bit easier to modify the meshconfig for **convenience** because there are a lot places on istio.io asking users to run `kubectl edit configmap istio` to update the content manually.

I don't understand how this will block Env WG's plans for changing the meshconfig or making it harder in any ways.

Also I don't think it should be considered to `promote editing meshconfig in istioctl`. It's just like `istioctl dashboard prometheus` that allows opening the prometheus dashboard conveniently but I don't think anyone would consider it the right way to operate prometheus in production.

**Comment by esnible** [comment]
@yangminzhu In the current istio.io, I see only two places we ask the user to edit the configmap:
- https://preliminary.istio.io/latest/blog/2021/better-external-authz/ (written by you)
- https://preliminary.istio.io/latest/docs/tasks/security/authorization/authz-custom/

My understanding is that users aren't supposed to do that.  @costinm told me they should do `istioctl install` to change settings.  Is my understanding correct?

I believe users want to see and make changes quickly.  However, some changes require istiod and/or pods to restart, so we can't offer the ability to make changes to the mesh config.  I still would like the ability for data-plane users to see the mesh config.  I want something like an [_istioctl describe mesh_](https://docs.google.com/document/d/1_Y_tOZst7gtvqFbM6SnYHXsbbJMRD7XRPdcVsPedWag/edit#heading=h.px1wwffuiak4) for that.

**Comment by yangminzhu** [comment]
@esnible If the user knows everything they need in the meshconfig, of course they won't need to edit the meshconfig after the installation.

But this issue is not trying to change that, this issue is trying to help a different use case when the user needs to tweak the meshconfig after the installation because the meshconfig includes many dynamic configurations. One example is the extension provider in the ext-authz where you want to customize how to talk to the extension provider later.

Some more examples, the following tasks involve updating meshconfig. I don't think most users would just use these values configured once in the initial installation, they often need to modify these values after the installation, for example, change the logging format to include/exclude some information, change the trace sampling rate temporarily for debugging (and change back after):
https://istio.io/latest/docs/tasks/observability/logs/access-log/#enable-envoy-s-access-logging
https://istio.io/latest/docs/tasks/observability/distributed-tracing/configurability/#using-meshconfig-for-trace-settings

**Comment by howardjohn** [comment]
`kubectl patch` or equivalent (`kubectl edit`, etc) should never ever be used in a real production environment - users should be using gitops or similar declarative configuration management. So its really a matter of if we want to make our docs recommend best practices, or make them simpler.

**Comment by esnible** [comment]
@yangminzhu I agree with you.  Let's work toward a solution.

I tried the following

``` bash
cat > /tmp/external-auth.yaml <<EOF
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    extensionProviders:
    - name: "opa.local"
      envoyExtAuthzGrpc:
        service: "local-opa-grpc.local"
        port: "9191"
EOF
istioctl install -f /tmp/external-auth.yaml
```

I realize it looks weird to do `istioctl install` just to update a single configmap.  But there is a bigger problem.  Many users SHOULD have permission to update the meshconfig, but not to install.  I am not sure how to handle those people.  See next comment.

**Comment by esnible** [comment]
@howardjohn @costinm See previous comment for situation.

Suppose we have a user who has a declarative model of their OPA authorization.  Suppose the OPA server has changed and they need to use a different OPA server.  This is a pure data plane thing, and they have RBAC permission to edit the ConfigMap on their cluster.

How should they make the change in their OPA config?  Let's assume their control plane is managed by their vendor and they **can't** do `istioctl install`.  Perhaps the user is not a human, but a service account authorized pipeline script.

**Comment by esnible** [comment]
@yangminzhu After reading your blog I feel like users would like to do something with more hand-holding, either using a new Istio CRD for "EnvoyAuthzExtensionProvider".  I think that would be the best way, rather than using MeshConfig.  Are you working on CRDs?

If we plan to continue to go through the MeshConfig, the user might want commands like `istioctl x authz extensions list` and `istioctl x authz extensions add <yamlfile>` rather than generic `istioctl experimental meshconfig merge`.

``` bash
$ istioctl x authz extensions list
PROVIDER SERVICE             PORT
opa.local local-opa-grpc.local 9191
my-custom-ext-authz-service ext-authz.istio-system.svc.cluster.local 9000
keycloak                    keycloak.default.svc.cluster.local.      8080 path_prefix=/openid-connect/token
```

**Comment by howardjohn** [comment]
It doesn't really matter how they install it - if they have external
control plane maybe they have a plain configmap yaml, if they use helm they
have a values.yaml, otherwise they have an IstioOperator yaml.

Regardless, there is some yaml file on a disk somewhere - for prod, likely
a git repo with gitops. The recommended flow, regardless of method, is
modifying that yaml and reapplying. I don't think imperative commands are
ever a good option, aside from demos, regardless of install type.

**Comment by batistein** [comment]
What is the current status? 
We have also the use case that we are using multiple IstioOperator CRs for creating multiple environments. Since we switch to the amazing extAuthz feature of istio we have the problem that the meshConfig is overridden every time a new IstioOperator CR is created... Right now we are using the workaround to specify all extensionProviders in every IstioOperator CR. But I don't think that this should be the natural way. I would do a PR to the istio operator for handling this merge but as I understand from this discussion, it would be better to move the whole extensionProvider to an own CRD?

**Comment by howardjohn** [comment]
You should configure it in the IstioOperator spec. under spec.meshConfig
