### ISSUE TITLE
TestDescribe flake

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#31505]
https://prow.istio.io/view/gs/istio-prow/logs/integ-k8s-116_istio_postsubmit/1371955227472695296

I've seen it fail other times as well

**Comment by esnible** [comment]
The message indicated it timed out after 1 attempt.  The first attempt failed because the DestinationRule info did not appear in the output.  The timeout period is 5 seconds.

I am surprised that it only managed one iteration in 5 seconds.  I am tempted to merely increase the timeout to 10 seconds....

**Comment by howardjohn** [comment]
SGTM

**Comment by howardjohn** [comment]
Well, the actual attempt may be hanging for some reason, maybe that needs a timeout?
