### ISSUE TITLE
Breaking changes to metrics 

### ISSUE THREAD

**Issue by tdinucci** [istio/istio#31516]
**Describe the feature request**

We are hoping to upgrade from Istio 1.4 to a more recent version.  It looks like there have been changes to certain metrics, most notably `istio_request_duration_seconds` has become `istio_request_duration_milliseconds`.

While this may not seem like a big deal, it is for us due to many engineering teams having custom alerts and/or dashboards which reference the old metric.  On top of this, simply turning one metric off and another on will make it difficult for our engineers to time their changes due to our alerts being defined at a global level and Istio changes will be rolled out slowly across all of our k8s clusters.  This will mean that there will be a period where some clusters report the old metric and others the new one, leading to global alerts firing.

What was the reasoning behind making such a breaking change?  The old metric was recorded in fractions of a second so I don't believe the new metric will be much more accurate.

Is it possible to add a feature flag to Istio so that your users can opt-out of the new style of metrics?

**Describe alternatives you've considered**

We have considered creating recording rules and relabeling histogram buckets so that we can retain some consistency as far as our users are concerned.  This is far from ideal though and will dramatically increase the resources required to run our Prometheus instances.  It will also be difficult (maybe impossible) to shoehorn the new time-series into the same set of buckets used by the old one.

If there are other alternatives I would love to hear.

[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by bianpengyuan** [comment]
The old metric name is generated by Mixer, and the new metric name is generated by Istio proxy, which was renamed due to some implementation limitation: https://istio.io/latest/faq/metrics-and-logs/#telemetry-v1-vs-v2.

Mixer telemetry reporting is still available until Istio 1.7, so you can disable telemetry v2 and enable Mixer explicitly: https://istio.io/v1.7/docs/tasks/observability/mixer/metrics/collecting-metrics/. Meanwhile, to ease the pain of alert/dashboard migration, you can add combined seconds and milliseconds metric name into prom query, for example here is a query we used in sample prometheus deployment:

```
(histogram_quantile(0.50, sum(rate(istio_request_duration_milliseconds_bucket{reporter="source"}[1m])) by (le, destination_workload, destination_workload_namespace)) / 1000) or histogram_quantile(0.50, sum(rate(istio_request_duration_seconds_bucket{reporter="source"}[1m])) by (le, destination_workload, destination_workload_namespace))
```

Sorry for the inconvenience!

**Comment by tdinucci** [comment]
Thanks for the feedback @bianpengyuan

**Comment by bianpengyuan** [comment]
Closing as this is answered. Please reopen if you have more comments. Thanks!
