### ISSUE TITLE
Passthrough traffic with auto mtls doesn't handle workloads scaling causing TestReachability/automtls-passthrough failures

### ISSUE THREAD

**Issue by bianpengyuan** [istio/istio#31534]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31531/integ-ipv6-k8s-tests_istio/1372292143661453312

cc @howardjohn

**Comment by howardjohn** [comment]
This is a real bug

**Comment by howardjohn** [comment]
The problem is EDS changes do not trigger this code: https://github.com/istio/istio/blob/79d56525633f13084241c6da2e3f948098242ce9/pilot/pkg/model/push_context.go#L1813.

So we start with 0 instances, and TLS is disabled. Then we scale to 1 instance, but don't update CDS, so we have no TLS configured.
If we made 0 instances enable mTLS, then it would still be broken, since we could scale to 1 instance without a sidecar.

I don't know a great way to resolve this. Any thoughts @hzxuzhonghu @incfly 

Note: this is not a regression, its a new test that catches an existing bug that has been around for a while.

**Comment by hzxuzhonghu** [comment]
Similar to https://github.com/istio/istio/issues/29405

**Comment by incfly** [comment]
Yeah. Seems we'll have to trigger a CDS push/updates in this case right? If no pods instances, we don't even know the service account associated with the server pods. Would not be able to set the SAN verification fields correctly.

**Comment by howardjohn** [comment]
Good point about the SANs.. not sure how it works for. non passthrough but doesn't here. need to look into it more

**Comment by hzxuzhonghu** [comment]
I am concerned about the istiod load though. After all app scale-up down is so common.

**Comment by howardjohn** [comment]
Yeah we definitely cannot push cds on all endpoint changes. But maybe just
when the cds will actually change. we already have similar logic for the
SANs changing I think? It just doesn't work here for some reason
