### ISSUE TITLE
Does http1MaxPendingRequests misnamed ?

### ISSUE THREAD

**Issue by masquee** [istio/istio#31548]
1、Why `http1MaxPendingRequests` has a `http1` prefix?  In Envoy its called `max-pending-requests`.

2、Why `http2MaxRequests ` has a `http2` prefix? In Envoy its called `max-requests`.

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by ramaraochavali** [comment]
Because when it was implemented originally `MaxPendingRequests` applied to http1 only and  `MaxRequests` applied to http2 only in Envoy. So to be more explicit Istio has named them like that.

 But this PR https://github.com/envoyproxy/envoy/pull/9668 in Envoy changed that behaviour. Please see the doc changes. We did not go back and rename the fields to avoid deprecation etc.

**Comment by masquee** [comment]
@ramaraochavali Maybe update istio doc to explain this?

**Comment by ramaraochavali** [comment]
Sure. I thought the existing description is clear `Maximum number of pending HTTP requests to a destination` - Do you think we should make it more explicit by saying it applies to both http1 and http2?

**Comment by masquee** [comment]
@ramaraochavali I thought the question is that the name `http1MaxPendingRequests`  and `http2MaxRequests ` is even more clear, so the description should provide more information to explain it.
