### ISSUE TITLE
AWS Certificate tests failing with go 1.10 

### ISSUE THREAD

**Issue by costinm** [istio/istio#3177]
TestAwsGetInstanceIdentityDocument and TestGetGetAgentCredential are failing.

Will exclude them in aws_test.go until this bug is fixed.

Example failure: https://circleci.com/gh/istio/istio/26218

=== RUN   TestAwsGetInstanceIdentityDocument
--- FAIL: TestAwsGetInstanceIdentityDocument (0.00s)
	aws_test.go:120: Good Identity: Unexpected Error: failed to verify PKCS7 signature: x509: signature algorithm specifies an RSA public key, but have public key of type *dsa.PublicKey

=== RUN   TestGetGetAgentCredential
--- FAIL: TestGetGetAgentCredential (0.00s)
	aws_test.go:223: Good Identity: Unexpected Error: failed to get EC2 instance identity document: failed to verify PKCS7 signature: x509: signature algorithm specifies an RSA public key, but have public key of type *dsa.PublicKey

**Comment by wattli** [comment]
@crazytan , can you help to take a look please? Thanks. @wattli

**Comment by crazytan** [comment]
No problem, I'll look into it.

**Comment by crazytan** [comment]
It's due to a bug in our dependency: https://github.com/fullsailor/pkcs7/blob/master/pkcs7.go#L257: the AWS signature algorithm is SHA1 with DSA but the package is verifying it as SHA1 with RSA. Looks like go1.10 is more strict in crypto/x509.

I can submit a PR to the original repo, but it looks like it's not actively maintained. Your call @wattli

**Comment by wattli** [comment]
Thanks for the investigation and I would suggest to fix the test first.

**Comment by crazytan** [comment]
Sure
