### ISSUE TITLE
nodeAgentTest runs for too long and causes presubmit failure

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#3181]
https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_istio/3120/istio-presubmit/4161/

I0205 19:35:39.736] *** Test killed with quit: ran too long (10m0s).
I0205 19:35:39.736] FAIL	istio.io/istio/security/tests/integration/nodeAgentTest	600.150s
E0205 19:35:39.778] Build failed

**Comment by andraxylia** [comment]
#3186 disables this test, please re-enable when the underlying cause is discovered and fixed.

**Comment by diemtvu** [comment]
@wattli

**Comment by cmluciano** [comment]
@mangchiandjjoe Are you still working on this issue? cc @wattli

**Comment by incfly** [comment]
Summarize my findings:
1. The test is flaky because the [key/cert are always generated](https://github.com/istio/istio/blob/master/tools/istio-docker.mk#L53) in build process. NodeAgent docker images `ADD generated_key_cert`. And somehow when tests run in parallel, the key cert generation may run multiple times, override the key cert, causing test to fail.
1. Some flags are outdated, and we should redirect the node-agent's output into a /var/log file for debugging.

The way to fix the 1) could be always use pre-generated key/cert.

**Comment by wattli** [comment]
I believe this is fixed by @mangchiandjjoe
