### ISSUE TITLE
bug-report: analyzer should run with -A

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#31918]
Running `istioctl analyze -n foo` is not very useful, since it breaks all cross-namespace references. Instead, we should just run `istioctl analyze -A` one time.

**Comment by zhlsunshine** [comment]
@howardjohn ,  I do not set all namespaces as enabled for Istio injection in my cluster, so I get below error message when I use `istioctl analyze -A` :
`$ istioctl analyze -A
Info [IST0102] (Namespace calico-system) The namespace is not enabled for Istio injection. Run 'kubectl label namespace calico-system istio-injection=enabled' to enable it, or 'kubectl label namespace calico-system istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace istio-system) The namespace is not enabled for Istio injection. Run 'kubectl label namespace istio-system istio-injection=enabled' to enable it, or 'kubectl label namespace istio-system istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0118] (Service calico-typha.calico-system) Port name calico-typha (port: 5473, targetPort: calico-typha) doesn't follow the naming convention of Istio port.`

So I think that analyzing all namespaces should be for all istio injection enabled namespaces, am I correct? If yes, I think above error message should not be printed out because I have some istio injection enabled namespaces.

**Comment by howardjohn** [comment]
Those are intended, its telling the user to explicitly opt-out of injection. I agree its a bit verbose (https://github.com/istio/istio/issues/30874), but its also at Info level.

**Comment by zhlsunshine** [comment]
I think this issue can be closed because the PR has been merged
