### ISSUE TITLE
Some ideas about istio configuration distribution status

### ISSUE THREAD

**Issue by shirleylb** [istio/istio#31995]
**Describe the feature request**
When istio pilot distributes the configuration changes to the envoy, users want to know when their service is ready and whether the changes take effect. They don't care about the process too much. Istio should provide feedback on the given configuration changes.

I have read the doc of Istio Configuration Distribution Status on the istio drive. It mentions that the ultimate goal is to take the latest nonce from a particular proxy and ask questions about which Istio Config has been distributed to the proxy. 

However, the Nonce value is being set to a randomly generated UID. The value is meaningless so that It's hard to correlate Nonce value to configuration state. At the same time, I've noticed that pilot will create a new version every full push time. And the version is composed of timestamp and the version number. Why not provide an API to expose the version information to the users? If users can get the VersionAcked value, they can compare the VersionAcked with the VersionSent. If the versionAcked is equal to or newer than the VersionSent, users will know their changes take effect.

What do you think of this idea? Let me know if you have any suggestions.

**Describe alternatives you've considered**
Some other details need to be considered.
1. When users make any change, they need to know the VersionSent value.
2. Nowadays, if the update is not a full push, the version won't be updated. In this case, we don't know whether the unchanged version contains the update. So pilot needs to change the timestamp or add marks to the version when the push is not a full push.
3. The time delay of the VersionAcked is not reliable Because the envoy may not report the VersionAcked in time. 

[X ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
Hey @shirleylb , I think this is all implementation details? The user shouldn't need to understand any Istio concepts like ACK, nonce, or version. Instead, they use `istioctl wait` and/or the status writing to see when a resource is updated. Everything else should be under the hood.

**Comment by shirleylb** [comment]
Hi @howardjohn，I did say a lot of implementation details. Here is a scenario that we need to support. When a resource needs to be deleted by another system, it cannot be deleted right now. Because this change is not yet known by all the envoys and the traffic is not yet removed from that resource. Other systems should wait until all the envoys know this change and update, which is for the graceful shutdown. It seems that `istioctl wait` for delete is not yet implemented. I'm not sure whether the status writing has already solved this problem. Actually, my idea to provide an API to expose the version information can be changed to expose the status. Could you provide more information about status writing or other suggestions to solve this problem?

**Comment by zhlsunshine** [comment]
Hi @howardjohn & @shirleylb, I think it has not been implemented yet in `istioctl wait`, as you can execute the command of `istioctl experimental wait` and you will get output as below: 

`$ istioctl experimental wait --for=delete --threshold=.99 --timeout=20s virtualservice bookinfo.default
Error: wait for delete is not yet implemented
`

**Comment by zhlsunshine** [comment]
Hi @therealmitchconnors,  FYI,  do you think we should implement **delete** of `istioctl wait` ? At least I think current command description is incorrect which indicates that it can support both `distribution` and `delete`.
And @shirleylb,  I have a question about `another system` you mentioned, how does `another system` delete the resource?
I think `another system` may need to call an API to delete the resource and sync with the API that all the envoys already know such deletion. Because it's unnecessary for istiod to keep all deleted resources and version information.

**Comment by shirleylb** [comment]
Hi @zhlsunshine, if istiod provides an API to expose the distribution status, another system will call it periodically and delete resources until all the envoys know the deletion. So I expect istiod can keep the deleted resources and their status at least for a while and can notify other systems through the API.

**Comment by zhlsunshine** [comment]
@shirleylb one questions: is it necessary for istiod to keep the deleted resource if users know exactly which resource they want to delete?  I mean the user may check the resource themself in all envoys(of course I think there should be an API for this)

**Comment by shirleylb** [comment]
@zhlsunshine My concern is that the response of the API relies on the cache of istiod. If istiod does not keep the deleted resource, how can users check this resource in all envoys through the API? So I think istiod should keep the deleted resource name and its status like `Deleted`. Maybe you think not keeping the deleted resource and getting the response like `NOT FOUND` can be considered as `Deleted` status.

**Comment by zhlsunshine** [comment]
@shirleylb yes, I mean if you want to delete a resource, such as a virtualservice, then you may know its details info, and you can execute command like `istioctl experimental wait --for=delete` with necessary details info of the resource, and this command can help you to check that if the resource is removed from all envoys or not.

And @therealmitchconnors  it will be very appreciated if any idea from you.

**Comment by therealmitchconnors** [comment]
@shirleylb you are correct that `wait --for delete` is not yet implemented.  If you need to be alerted when a delete operation is distributed, I recommend looking into how 'istioctl x wait' works for non-delete operations, and start there.  In particular, the nonce used by pilot is not random, but is a hash of the istio resources present when the corresponding xds message was generated.  

To implement `--for delete`, I think you could use the same debug endpoint as the regular wait command, but wait for all proxies to report having no version for the given resource.  I suppose technically if a resource were created and then very quickly deleted, this logic could break, as some proxies may have no version due to not yet having received the create operation, while others might have no version of the resource due to having received the delete, but this is an extreme edge case.

I'd be happy to sit down with you to discuss this further.  The UX WG meetings are on the Istio Community Calendar, and we'd be happy to hear about how our commands are being used and enhanced.

**Comment by therealmitchconnors** [comment]
@shirleylb you can find User Experience working group meetings [here](https://calendar.google.com/calendar/u/0/embed?src=4uhe8fi8sf1e3tvmvh6vrq2dog@group.calendar.google.com&ctz=America/Los_Angeles).  Our next meeting is happening Wednesday 4/21 at 19:00 Pacific time.  

Regarding the `/debug/config_distribution` endpoint, this API shows the latest version of the config which has been acknowledged by a given envoy proxy.  I think with some creativity we can use it to determine when a delete operation was acknowledged as well.

**Comment by shirleylb** [comment]
@therealmitchconnors I will try to attend the meeting if I have time.   

In addition, I took a look at codes. I don't think this API shows the latest version of the config which has been acknowledged by a given envoy proxy. It just shows the latest version of the config which has been detected by the pilot and is going to be pushed to the envoy proxy.
https://github.com/istio/istio/blob/2e212514f0f55b1246f0f68245388aeeb7682551/pilot/pkg/status/reporter.go#L217-L220
