### ISSUE TITLE
Exclude high cardinality cluster.xds-grpc metrics from Envoy metrics

### ISSUE THREAD

**Issue by nrjpoddar** [istio/istio#32313]
**Describe the feature request**
Istio by default configures all cluster.xds-grpc prefixed metrics which includes various latency related metrics which can high cardinality in a large cluster. These metrics are:

* `envoy_cluster_upstream_cx_length_ms_bucket`
* `envoy_cluster_upstream_cx_connect_ms_bucket`
* `envoy_server_initialization_time_ms_bucket`

These metrics are not very useful in debugging xDS related issues so I think it should be safe to remove them for everyone or have an option to disable them if a user chooses to do so.

**Describe alternatives you've considered**
Current proxy config at mesh level or per-pod annotations only allow adding to the default set of Istio metrics but don't support excluding certain metrics or labels.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**
[Slack thread](https://istio.slack.com/archives/C382V8Q92/p1618844046025900) with more details which may or may not be accessible at a later date.
Envoy [open issue](https://github.com/envoyproxy/envoy/issues/8771) related to excluding metrics.

**Comment by nrjpoddar** [comment]
cc @douglas-reid @mandarjog @bianpengyuan

**Comment by howardjohn** [comment]
Possibly naive question: why is adding 3 histograms an issue? Is Prometheus scalability really so constrained that all pods in the cluster simply adding 3 metrics has a major impact? Or are we doing something worse than just adding 3 histograms?

I don't mean this as a slight at Prometheus in any way, it just seems like a non-Istio specific issue and was wondering if I was missing something or if its really that easy to shoot yourself in the foot?

**Comment by bianpengyuan** [comment]
> Possibly naive question: why is adding 3 histograms an issue? Is Prometheus scalability really so constrained that all pods in the cluster simply adding 3 metrics has a major impact? Or are we doing something worse than just adding 3 histograms?
> 
> I don't mean this as a slight at Prometheus in any way, it just seems like a non-Istio specific issue and was wondering if I was missing something or if its really that easy to shoot yourself in the foot?

+1. Istio standard metric labels have way more variability and thus much higher cardinality. These three histogram should be uniform at all proxy with `cluster_name="xds-grpc"` label and exactly the same buckets. Prom should be able to deal with this easily. Not sure if this is a real issue that has been observed at prom?

**Comment by douglas-reid** [comment]
I think the issue is pointing out that, in general, there are a number of time-series that we are generating that are not being used. And, at scale, that can be expensive. We may be well-served by not generating them.

While users can filter these server-side currently, it may be of interest to keep envoys from storing/keeping the metrics and to save on the serialization/processing from pulling them into Prom.

I've seen cases where histograms end up using ~10x storage compared to gauges / counters. And the default bucket-ization for Envoy may not be optimized for these measurements resulting in waste. I doubt these metrics are breaking Prom's back, but if they aren't being used, should we be generating them?

**Comment by nrjpoddar** [comment]
@howardjohn & @bianpengyuan the issue is that with every pod meta labels added and large number of buckets this is quite wasteful irrespective of what Prometheus can handle. For Istio generated metrics users have an option of remove certain tags/labels IIRC but there's no such option for these metrics. What I see in large deployments is Prometheus reporting on large cardinality in its status for all Istio & Envoy related histogram metrics (latency and bytes). For Istio generated one, you have an option to remove labels which you cannot for Envoy ones.

@douglas-reid 100% agree with your assessment.

Note that from Prometheus point of view we can always drop metrics or labels via relabel or metric relabel config but this just feels wasteful to me from what Istio is doing out-of-box.

**Comment by howardjohn** [comment]
Doesn't every pod get the pod meta labels added? It's not just Envoy - I
don't think envoy even knows about them and it is added by prometheus
itself?

**Comment by nrjpoddar** [comment]
Yes John. But those labels add to cardinality is what I meant. Even without that this metric is pretty expensive to keep.

**Comment by bianpengyuan** [comment]
Would be great if we can get some quantitive measurement on what percentage of prom time series are contributed by these histograms, before we make decision on excluding them by default or adding the exclusion option. Since this is the first time that this is complained, I am a bit skeptical on the actual cost of them.

**Comment by emaildanwilson** [comment]
I think you'd be better off adding the option in Istio to remove the metric and comparing prometheus usage before and after because when the metric is dropped using a relabel rule  prometheus still has to read all the data in order to drop it. This still literally kills prometheus on large clusters unless you completely disable metric scraping.

It would be really nice to just have a config array of all the metrics which are enabled, then folks can choose which ones to remove.

**Comment by douglas-reid** [comment]
@nrjpoddar we should find some time to look at this again. i'm not sure the Telemetry API has a place to hang this, but maybe there are other ways to approach. 

we've got a fair amount of cruft, in the form of legacy envoy metrics with incorrect regexes leading to unusable metrics, the issue mentioned here, etc. would be nice to have some form of detailed specification, perhaps controlled by the agent ?

**Comment by antoniocascais** [comment]
Any news regarding this issue?

The `envoy_cluster_upstream_cx_length_ms_bucket` and `envoy_cluster_upstream_cx_connect_ms_bucket` metrics are the most expensive ones that we have right now. Do we really need all the 20+ buckets that they have? Also, do we need all the labels? We have like 20+ labels for these metrics, adds up quite a lot to cardinality. 

I know we can drop them on Prometheus side, but like it was said above in this thread is quite a waste of resources.

![image](https://user-images.githubusercontent.com/28305187/199693899-f045602f-aa69-4123-b7ac-bf1d16cff8ae.png)

**Comment by unitrade** [comment]
#45405
