### ISSUE TITLE
Statefulset DNS: investigate same name in multiple clusters

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#32393]
Looking at the code https://github.com/istio/istio/blob/bd3c271d7eea4567dfbd0355015d0f9918fb2d03/pilot/pkg/networking/core/v1alpha3/name_table.go#L88, it seems like if we have multiple clusters we pick an arbitrary one if there is the same name in multiple clusters. We should probably return the cluster-local one in conflict

@ramaraochavali @hzxuzhonghu  WDYT?

**Comment by ramaraochavali** [comment]
Yes. That makes sense to me.

**Comment by Shikugawa** [comment]
@howardjohn I'm new to pilot contribution so that I can be misunderstood about this feature. Specifically, does it mean that if we have,

| Hostname | Subdomain | IPAddr | NSDomain |
| ------------- | ------------- | ------------- | ------------- |
| pod1 | x | 1.2.3.4 | testns.svc.cluster.local |
| pod2 | x | 5.6.7.8 | testns.svc.cluster.local |
| pod2 | x | 10.10.10.10 | testns.svc.cluster2.com

then name table should be

```
{
  "pod1.x.testns.svc.cluster.local": {
    "IPAddr": [1.2.3.4]
  },
  "pod2.x.testns.svc.cluster.local": {
    "IPAddr": [5.6.7.8] // It can be 10.10.10.10 in current impl
  },
  "x.testns.svc.cluster.local": {
    "IPAddr": [1.2.3.4, 5.6.7.8]
  },
}
```

Is my consideration right?

**Comment by hzxuzhonghu** [comment]
@howardjohn What do you mean? Doesn't it has already checked the clusterID?https://github.com/istio/istio/blob/bd3c271d7eea4567dfbd0355015d0f9918fb2d03/pilot/pkg/networking/core/v1alpha3/name_table.go#L101

**Comment by howardjohn** [comment]
That is for the service name. But we add the pod unconditionally. So if I have `mysql-0` in two clusters, I will get a random one

**Comment by hzxuzhonghu** [comment]
In line 82, 
>		if instance.Endpoint.SubDomain != "" && instance.Endpoint.Network == node.Metadata.Network {

We have also checked the network

**Comment by howardjohn** [comment]
We do check network, i am wondering if we should pick the local cluster as well though, IFF its in both clusters?
