### ISSUE TITLE
SecurityContext.RunAsUser is forbidden when deploying BookInfo sample app on K8

### ISSUE THREAD

**Issue by wjimenez5271** [istio/istio#324]
I'm trying to deploy the sample BookInfo app on K8. I followed the istio installation instructions here: https://istio.io/docs/tasks/installing-istio.html, using the alpha version of rbac, and opting for the version without auth (`install/kubernetes/istio.yaml`). All the istio services come up without issues, including grafana and prometheus, but for the BookInfo apps the pods report the following error: 

```
Error creating: pods "" is forbidden: SecurityContext.RunAsUser is forbidden
```

And fail to deploy. Here are my version details: 

```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-08T02:50:34Z", GoVersion:"go1.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.4-rancher1", GitCommit:"6ed2b64b2e1df9637661077d877a0483c58a6ae5", GitTreeState:"clean", BuildDate:"2017-03-17T16:58:04Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by ayj** [comment]
What kubernetes environment are you testing in? This could possibly be due to [SecurityContextDeny admission controller ](https://github.com/kubernetes/kubernetes/pull/21004) which is [no longer recommended for version >= 1.2.0](https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/admin/admission-controllers.md#is-there-a-recommended-set-of-plug-ins-to-use)?

**Comment by wjimenez5271** [comment]
This is running on a deploy of K8 using Rancher on Digital Ocean. It looks like the SecurityContextDeny is enabled so I am going to try again without it.

**Comment by juanchoc** [comment]
I'm having the same issue (also with Rancher on IBM Softlayer.
Does anyone know how to remove the SecurityContextDeny plugin?

**Comment by juanchoc** [comment]
Effectively, according to the docker compose file used by Rancher on its Kubernetes template (see [https://github.com/rancher/rancher-catalog/blob/master/templates/kubernetes/11/docker-compose.yml](url)), it is starting the api server with `--admission-control=NamespaceLifecycle,LimitRanger,SecurityContextDeny,ResourceQuota,ServiceAccount`.
In order to remove the SecurityContextDeny plugin, from the Rancher web interface I had to do the following:

1. Open the Kubernetes -> Infrastructure Stacks view.
2. Expand the Kubernetes stack.
3. Open the actions menu (the '...' button on the right) on the Kubernetes pod, and click on Upgrade.
4. Modify the command shown so that the admision control flag matches the recommended value for K8s 1.5.x
`--admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota`
5. Hit upgrade and wait.
6. Once completed, tap on the Finish Upgrade button (see the '...' button next to the Kubernetes pod.

Now everything is working as expected.

**Comment by wjimenez5271** [comment]
I think we can close this issue as it is not a problem with Istio.

**Comment by alexcouper** [comment]
I am having this issue, running on EC2: 

https://stackoverflow.com/questions/44723147/kubernetes-isnt-allowing-me-to-create-a-pod-with-securitycontext-runasuser
