### ISSUE TITLE
Authenticate API Server for Sidecar Injector webhook

### ISSUE THREAD

**Issue by ramaraochavali** [istio/istio#32611]
Implement api server authentication (possibly using role in cert) when responding to pod injection requests as explained in https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#authenticate-apiservers.

Currently we do not validate client certs and hence api server.

**Comment by ramaraochavali** [comment]
@costinm @howardjohn What do you think? You must have thought about this case?

**Comment by howardjohn** [comment]
Absolutely have thought of it, but the current way of configuring webhooks is pretty invasive which is unfortunate. Its probably not too hard to implement in Istiod side, but probably won't be used widely. I think less than 1% of users would be able to configure it since you need to modify the cluster resources which cannot be done in managed k8s (at least gke0. https://github.com/kubernetes/enhancements/pull/2512 proposes a way that would work for ~all clusters which would be nice.

It is also possible to put it behind a gateway which can of course handle this
