### ISSUE TITLE
Automater: detect blocked PRs

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#32785]
Currently some PRs are stuck. This may be test flakes or real breakages. We should have some way to manage this - github issues, slack notifications, auto /retest, etc are all ideas

**Comment by ericvn** [comment]
After watching these jobs and helping them along, I see a few items causing blockage:

1. First is a flakey test failing. The fix is to rerun the test, which will hopefully pass and the PR merges.
2. The PR may also show rebasing needed. We can maybe update the jobs to try and prevent some of this. I suspect some jobs are doing the same thing, like update_deps, and then it's a first one wins. There are two rebase needed issues:
  - All the changes in the PR are already merged. Then it's imply a close the PR.
  - Some of the changes are merged.
  - I think if the Automator logic would close any active PRs IF there are no changes found, that will solve the first issue. The logic already updates the existing PR if there are changes, so hopefully pretty easy to remove the PR if there are none.
  - We need a way to rerun the failed automator jobs. This rerun, combined with the prior change to close PRs with no changes should either close the PR or update it with changes to unblock the rebase.
