### ISSUE TITLE
config.route.v3.RouteAction.HashPolicy.Cookie passive cookie

### ISSUE THREAD

**Issue by dex4er** [istio/istio#32942]
https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto.html#envoy-v3-api-msg-config-route-v3-routeaction-hashpolicy-cookie tells that envoy supports 2 modes for session cookie: 

1. Passive. Envoy takes a cookie that’s present in the cookies header and hashes on its value.
2. Generated. Envoy generates and sets a cookie with an expiration (TTL) on the first request from the client in its response to the client, based on the endpoint the request gets sent to.

Unfortunately Istio's LoadBalancerSettings.ConsistentHashLB.HTTPCookie.ttl parameter is required:

https://istio.io/latest/docs/reference/config/networking/destination-rule/#LoadBalancerSettings-ConsistentHashLB-HTTPCookie

Please make it optional as it seems now Envoy supports it (at least documenation explicitely implies it).

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by dex4er** [comment]
I think it is reated to #25621 but it looks like now it is supported by Envoy.

**Comment by isanchos** [comment]
Good day, 
I would like to describe issue I faced with 
our backend generates and uses JSESSIONID cookie to identify user session. 
Istio DestinationRule loadBalancer is configured to use JSESSIONID
loadBalancer:
      consistentHash:
        httpCookie:
          name: JSESSIONID
          ttl: 1800s
With the first client request istio genearte cookie and backend generate cookie. 
as result two different JSESSIONIDs is present in request. it is couse backend to fail because istio generated cookie id is not present in the backend session map.

Expected that istio will not generate its own cookie and uses cookie  provided by backend for balancing

**Comment by fmulero** [comment]
Is there any workaround? Using an external session cookie to keep the session affinity is very common and most of the load balancer allow it.
In our case we are facing a lot of problems due to this limitation because a lot of java clients of our applications only expects the JSESSIONID cookie and ignore any other cookie used to keep the session affinity

**Comment by howardjohn** [comment]
I am not sure how a passive cookie helps in JSESSIONID case

Today:
Request 1: client request (no JSESSIONID) -> envoy (generate JSESSIONID 1) pick endpoint based on JSESSIONID 1 -> server X (respond with JSESSIONID 2)
Request 2: client request (now has JSESSIONID 2) -> envoy pick based on  JSESSIONID 2 -> server Y

Passive:
Request 1: client request (no JSESSIONID) -> envoy pick endpoint randomly -> server X (respond with JSESSIONID 2)
Request 2: client request (now has JSESSIONID 2) -> envoy pick based on  JSESSIONID 2 -> server Y

?

**Comment by dex4er** [comment]
@howardjohn 

It helps when you have multiple domains in cookie then you share the session between different domains.

**Comment by howardjohn** [comment]
That still doesn't seem to help the issue that request 1 and request 2 are not sent to the same server if the session id is generated by the server?
