### ISSUE TITLE
Deprecate or test MeshNetworks

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#32961]
I think (not 100% sure, looking into it) we broke MeshNetworks in 1.10. We should either formally deprecate this and warn on usage, or make sure its tested.

cc @stevenctl

**Comment by tobiashenkel** [comment]
I have a use case where I currently rely on MeshNetworks. If this can be solved with auto distovery I'd be happy to learn how to do it differently. The scenario is that I have multiple clusters in aws and onprem. Due to network constraints the onprem clusters can access the eastwest gateway only via a tunnel so the onprem clusters must resolve the gateway to other ip addresses than the aws clusters.

To solve this I currently generate individual MeshNetworks for each cluster with the correct ip addresses. As I've understood the auto discovery via the service currently cannot use DNS (which would be a workable solution if it works).

**Comment by stevenctl** [comment]
> To solve this I currently generate individual MeshNetworks for each cluster with the correct ip addresses.

You should be able to do the same thing by setting `externalIPs` on the eastwest gateway's Service. It's not well tested though.

**Comment by tobiashenkel** [comment]
> > To solve this I currently generate individual MeshNetworks for each cluster with the correct ip addresses.
> 
> You should be able to do the same thing by setting `externalIPs` on the eastwest gateway's Service. It's not well tested though.

But then all remote clusters would resolve the eastwest gateway to the same ip address right? What I'm trying to resolve is the following scenario. Let's say we have clusters A and B in aws and cluster C onprem. The eastwest gateway of A is accessible from within cluster B via x.x.x.x and from cluster C via y.y.y.y (through a tunnel). Adding both to the service results in a permanently inaccessible endpoint.

**Comment by stevenctl** [comment]
I see. Thanks for the clarification, seems like a pretty valid usecase to keep meshNetwork supported for.

**Comment by stevenctl** [comment]
We have strong unit tests for this now.
