### ISSUE TITLE
provide CRD json schemas

### ISSUE THREAD

**Issue by Morriz** [istio/istio#33535]
**Describe the feature request**

Please provide json schemas in the CRDs so that we may statically analyse templates for correctness.

Maybe these schemas are published somewhere else? (But if so, then why not in the CRDs?)

Am I not looking well in all the corners?

Missing so far:
```
kind: IstioOperator
```

I looked into the 1.10 branch but found nothing...

**Comment by howardjohn** [comment]
These are provided for all types except IstioOperator. I think we exceed the size limit on that one size the api is so large

**Comment by Morriz** [comment]
Ha, will ik make it in somehow later then?

**Comment by warwick-mitchell1** [comment]
I think this issue is causing me problems when I try to deploy Istio using Terraform. I'm trying to use the new TF k8s resources `kubernetes_manifest` but it's throwing a warning concerning the lack of Schema. 
This causes Terraform to force a recreation of the Istio CRD and thus recreation of the Istio install when there is any sort of update as it can't validate any of the fields.

```
 Warning: This custom resource does not have an associated OpenAPI schema.

   with module.istio.kubernetes_manifest.istio,
   on modules/istio/istio.tf line 12, in resource "kubernetes_manifest" "istio":
   12: resource "kubernetes_manifest" "istio" {

 We could not find an OpenAPI schema for this custom resource. Updates to this resource will cause a forced replacement.
```

Is there any easy way to generate a schema I could throw in to test. When you say it exceeded size limit, which limit is this?

**Comment by juicemia** [comment]
Can we get this reopened? This is definitely an issue for anybody managing an Istio installation via Terraform.

**Comment by InfoSec812** [comment]
It also precludes using `kubectl explain` effectively along with many other helpful tools.

**Comment by howardjohn** [comment]
> It also precludes using `kubectl explain` effectively along with many other helpful tools.

It would but we added this years ago...? I use it daily so I'm sure it's there. Maybe you can provide more details if you are having issues, in a new issue.

Unless it's IstioOperator which does not and will not have it

**Comment by InfoSec812** [comment]
Yes, I am referring to the Operator CRD
