### ISSUE TITLE
High istiod/discovery memory usage since upgrade to 1.10

### ISSUE THREAD

**Issue by Stono** [istio/istio#33569]
**Bug description**
We recently upgraded from `1.9.5` to `1.10.1`, and we are finding the memory usage of istiod much higher and quite unstable, as can be seen from the graph here:

![Screenshot 2021-06-22 at 11 05 13](https://user-images.githubusercontent.com/1486729/122906143-bf455f00-d349-11eb-818f-7b756a1fecfe.png)

This is in mb, so we're seeing 35%ish swings on the average.  The average has gone from `400mb` to `1.3gb`, and we're peaking as high as `1.7gb`.

Zooming in to the lower time frames, and a single pod we see:
![Screenshot 2021-06-22 at 11 09 09](https://user-images.githubusercontent.com/1486729/122906681-514d6780-d34a-11eb-9a19-170b0d958232.png)

07:00 is roughly the time of day our cluster starts taking deployments from developers, so i'd say this memory usage is related to config pushes, but the times don't really marry with the istiod logs: 

[logs.log.tar.gz](https://github.com/istio/istio/files/6693294/logs.log.tar.gz)

[ ] Docs
[ ] Installation
[ ] Networking
[x] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Memory to be stable, and memory increases in istiod to be acknowledged as expected in release notes if they are indeed expected.

**Steps to reproduce the bug**
Unsure, obviously we have a big deployment with a lot of configuration, and welcome anyone to live debug with me.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
1.10.1

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
If you could get a memory profile it would be helpful: https://github.com/istio/istio/wiki/Analyzing-Istio-Performance#memory.

**Comment by howardjohn** [comment]
The only change that stands out to me is go 1.16 upgrade which has changes to how memory is managed/reported: https://golang.org/doc/go1.16#runtime

**Comment by Stono** [comment]
[pprof.pilot-discovery.alloc_objects.alloc_space.inuse_objects.inuse_space.002.pb.gz](https://github.com/istio/@howardjohn o/files/6695405/pprof.pilot-discovery.alloc_objects.alloc_space.inuse_objects.inuse_space.002.pb.gz)

Here you go @howardjohn

**Comment by Stono** [comment]
Here you go @howardjohn 

[Uploading pprof.pilot-discovery.alloc_objects.alloc_space.inuse_objects.inuse_space.002.pb.gz…]()

**Comment by Stono** [comment]
Here you go @howardjohn 

[pprof.pilot-discovery.alloc_objects.alloc_space.inuse_objects.inuse_space.002.pb.gz](https://github.com/istio/istio/files/6695416/pprof.pilot-discovery.alloc_objects.alloc_space.inuse_objects.inuse_space.002.pb.gz)

**Comment by Stono** [comment]
Been working with @howardjohn on slack on this and tested out a variety of things, one thing we've discovered is that using an `istiod` image built against `1.15` golang seems to solve the problem, here you can see how memory is lower, and spiky after switching and forcing lots of full pushes (by editing the istiod configmap):

![Screenshot 2021-06-23 at 16 47 23](https://user-images.githubusercontent.com/1486729/123128481-17ac5780-d443-11eb-915c-6b2b271af6b3.png)

Johns suspicions came from https://github.com/golang/go/issues/44554, albeit the environmental workaround in there `GODEBUG=madvdontneed=0` doesn't resolve it.

**Comment by Stono** [comment]
@howardjohn - i'm assuming, but could you confirm that istio-proxy is also targeting 1.16 golang now?  I ask because our operations teams have been dealing with numerous high memory alerts for proxies since the 1.10 upgrade.

**Comment by howardjohn** [comment]
Yes, everything is 1.16 now

**Comment by Stono** [comment]
Hey, just wondering if there's any progression with this?  Are you using anything specifically 1.16?  Wondering if a rollback to 1.15 until the memory profile is understood makes sense?

I ask because i need to know if i need to go and adjust our expectations/alerts around proxy and control plane memory usage

**Comment by howardjohn** [comment]
My suspicion is still that this is a metric reporting discrepancy, rather than a real regression in memory usage. But we need to prove that. Until we do that it would be preferred to not revert, as we do depend on 1.16 for some features now, our dependencies (ie k8s) are using it so it has the most testing, and it has been shown to have concrete performance benefits in many other areas. We should leave the option open of course, but i am hoping it does not come to that

One thing I have noticed:

![2021-30-06_17-42-53](https://user-images.githubusercontent.com/623453/124048192-9c125380-d9ca-11eb-8e10-04880b552281.png)

All memory stats are ~the same between versions *except* the one you are looking at (working_set_bytes). With 1.16 (v10 on the graph), it is identical to container_memory_usage_bytes

**Comment by howardjohn** [comment]
working_set_bytes is https://github.com/google/cadvisor/blob/50b23f4ed9bc53cf068316b67bee04c4145f1e73/container/libcontainer/handler.go#L862
`Usage-total_inactive_file`

Which for different versions is seen as:
```
v10: 447827968-0
v9: 690978816-574328832
```

So golang 1.16 is actually using less memory total, but is reporting none of it as inactive.

Interestingly, here is the two after disconnecting all proxies:
![2021-30-06_18-04-38](https://user-images.githubusercontent.com/623453/124049593-abdf6700-d9cd-11eb-8a1e-d6da5995b805.png)
The go 1.15 pod never actually returns the memory to the OS

**Comment by howardjohn** [comment]
From https://github.com/kubernetes-sigs/metrics-server/pull/359 it seems like looking at rss may be more appropriate. I have seen suggestions of the opposite (https://blog.freshtracks.io/a-deep-dive-into-kubernetes-metrics-part-3-container-resource-metrics-361c5ee46e66, https://faun.pub/how-much-is-too-much-the-linux-oomkiller-and-used-memory-d32186f29c9d) but those seem to be prior to that PR.

However, looking at `kubectl top` it does seem to be working_set, not RSS, that is reported. I believe that PR is in v0.4.0 metric server, while GKE (v1.20.6) has v0.3.6, which doesn't have that PR.

If I am reading this right:
![2021-30-06_19-19-35](https://user-images.githubusercontent.com/623453/124055087-201f0800-d9d8-11eb-8daa-2bbe55b76d47.png)
The OOMKill happens when rss/memory_usage exceeds limit (2GB here); working_set is still far below.

**Comment by Stono** [comment]
They all report pretty much the same for me...
<img width="1107" alt="Screenshot 2021-07-09 at 08 49 50" src="https://user-images.githubusercontent.com/1486729/125043283-b0bdae00-e092-11eb-8216-11bf05762e02.png">

**Comment by fktkrt** [comment]
Same here after upgrading a tiny cluster from 1.9.3 to 1.10.3.
![image](https://user-images.githubusercontent.com/11597065/126838505-df0993f7-cd11-45e7-b71b-453468648d7c.png)

Although, RSS (red) is somewhat closer to the previous usage than the rest of them.

**Comment by jacob-delgado** [comment]
It's been a while since I've done some memory profiling, but RSS and not working set is what I used to use to monitor my applications. Memory can be given back to the OS from the app, but the OS may not recognize it until it requests additional memory (for it or another app) or until it does some memory cleanup. At least with the JVM this can be pretty difficult at times.

However, from https://faun.pub/how-much-is-too-much-the-linux-oomkiller-and-used-memory-d32186f29c9d it looks like OOM Killer is using working set. Monitoring containerized applications seems to be different. Is there a way we could do some profiling of istiod?
