### ISSUE TITLE
Test/document multi-cloud with CoreDNS

### ISSUE THREAD

**Issue by costinm** [istio/istio#3361]
Once https://github.com/coredns/coredns/issues/1483 is fixed, we need to test it with istio and document
the process.

CoreDNS will be able to pull from multiple k8s clusters, and could be used as an alternative to exposing
the kubeDNS via internal load balancer, and will match the behavior of pilot fetching from multiple clusters.

**Comment by johnbelamaric** [comment]
We implemented the `kubernetai` external plugin:

https://github.com/coredns/kubernetai

This allows you to connect to many different K8s api servers and serve DNS for all of them. Please take a look and provide any feedback!

**Comment by gyliu513** [comment]
@johnbelamaric does there are any detailed document for https://github.com/coredns/kubernetai ? Also I found that this project did not have update for months. What is the status of this project?

FYI @morvencao

**Comment by johnbelamaric** [comment]
@gyliu513 it works identically to the Kubernetes plugin, except that you can list it multiple times to configure different cluster API endpoints. We built it specifically for Istio although others may find it useful too - I think this issue was intended to have the Istio team try it out and see if it meets your needs.

It hasn't been updated recently because it hasn't needed it, it should work just fine. If changes are needed we can make them.

Note that in order to use it, you need to build a custom build of CoreDNS - it's not built in by default. @chrisohaver is on the CoreDNS slack (CNCF) if you need more help, too.

**Comment by gyliu513** [comment]
@johnbelamaric @chrisohaver does there are any detailed document for how to do the test? I would love to have a try for this in Istio.

**Comment by gyliu513** [comment]
Thanks @chrisohaver , will have a try for this and may still need your help if there are any issues.

**Comment by gdoctor** [comment]
@chrisohaver I edited the plugin.cfg to add kubernetai, and built my image using the provided coreDNS Dockerfile. However, when I try to run the image inside my cluster (actually locally too), I get a constant stream of 'standard_init_linux.go:190: exec user process caused "exec format error"'. Do you know how to resolve this? It seems that the Dockerfile coreDNS provides us, and the Dockerfile they are actually using are different.

**Comment by chrisohaver** [comment]
@gdoctor, Are you building the binary for the correct target OS?

**Comment by gyliu513** [comment]
@gdoctor FYI, you can create a document for this. Thanks.

**Comment by gdoctor** [comment]
Okay so here is the design I am am currently running, and I would like some feedback if possible. This solution assumes that you have setup pod to pod networking across clusters already as per the multi-cluster instructions, and that each cluster has a unique subdomain defined (although you may be able to get around this one).

I setup cross cluster service discovery using coredns and kubernetai. Now I was able to discover service and pod IPs _across_ clusters using DNS names like below:
ServiceIP:
istio-proxy@my_host_at_yyy:/$ host istio-pilot.istio-system.svc.cluster.xxx.local
istio-pilot.istio-system.svc.cluster.xxx.local has address 10.96.101.104
PodIP:
istio-proxy@my_host_at_yyy:/$ host 192-168-1-33.istio-system.pod.cluster.xxx.local
192-168-1-33.istio-system.pod.cluster.xxx.local has address 192.168.1.33

Obviously this isn't very useful since pod IPs (and DNS A records) can easily change, and service IPs are not routable between clusters. To get around this, I decided to setup an "istio-admin-ingressgateway" _headless_ service to complement the default istio-ingressgateway. This will help me get around the changing Pod IPs, since headless services modify the DNS A records to a new, much more usable/stable format of "serviceName.namespace.cluster.yyy.local".

istio-proxy@my_host_at_yyy:/$ host istio-admin-ingressgateway.istio-system.svc.cluster.xxx.local
istio-admin-ingressgateway.istio-system.svc.cluster.rtp.local has address 192.168.4.45

I intend for the admin-ingress controller to only be used for cross cluster communication between the various cluster components, such as Pilot, Citadel, etc. So after I setup the admin-ingress, I tied a Gateway and VirtualService object to the admin-ingress to handle the routing beyond the ingress controller. Now I have a stable DNS name (istio-admin-ingressgateway.istio-system.svc.cluster.rtp.local in my above example) that I can use in my istio-remote.yaml to connect to my pilot, policy, telemetry, statsd, etc. pods via their port numbers! Pilot for example would be istio-admin-ingressgateway.istio-system.svc.cluster.rtp.local:15010

This gets around some of the flaws I personally see with #6896 as referenced in #5535, which I believe will require you to open a bunch of NodePorts, and also expand the NodePort range to include all the administrative port numbers (unless I am missing something..). It is also better than integrating Consul just to mimic this behavior. Plus this solution requires provisioning no load balancers. What do you think? @gyliu513 @chrisohaver @baodongli @costinm

I realize this is a CoreDNS-Istio spefic thread btw, and would be happy to document more on that portion if my above solution appears to be a viable HA Istio Multi-Cluster setup.

**Comment by gyliu513** [comment]
@gdoctor can you please edit your comment a bit by using md for some command as follows?

```
Your command and output here
```

FYI @morvencao

**Comment by chrisohaver** [comment]
> Okay so here is the design

Very nice.  Thanks for the write up! 

> Assumes [...] each cluster has a unique subdomain defined (although you may be able to get around this one).

I think you can, by using the `fallthrough` option in each `kubernetai` plugin, you can order the `kubernetai` stanzas in order of precedence, all with the same zone.  When serving a query in that zone, coredns will try the plugins in order listed, e.g. local first, then if nothing is found the next 
cluster, etc.
