### ISSUE TITLE
Istio upgrade error

### ISSUE THREAD

**Issue by vowne** [istio/istio#33656]
When we tried to do canary model upgrade, we are getting below error.

` ./istioctl8 install --set revision=1-8 --set profile=default -f /home/admin/upgrade/iop.yml`

> Error: failed to get profile and enabled components: failed to read profile: unknown field "telemetry" in v1alpha1.IstioComponentSetSpec:

Where the /home/admin/upgrade/iop.yml is the exported iop installed-state yaml file from the existing istio version 1.73

`kubectl -n istio-system get iop installed-state-install -o yaml > /home/admin/upgrade/iop.yml`

**Comment by vowne** [comment]
After this,  I removed the components telemetry and policy copletely form the exported iops-installedstate yaml file and again tried to execute the new controlplane creation command for the canary upgrade. But this time the error is strange.

.`/istioctl8 install --set revision=1-8 --set profile=default -f /home/admin/upgrade/iop__nopol_notelim.yml`

> Error: failed to get profile and enabled components: failed to read profile: json: cannot unmarshal string into Go value of type map[string]json.RawMessage:

**Comment by vowne** [comment]
Any guidance on this?.. We are stuck with this error and couldnt find any solution from the Istio community related to this

**Comment by chadlwilson** [comment]
Seems like you are probably better to seek help on discuss.istio.io or the Istio Slack rather than Github for queries like this.

Anyway, it's not really possible to precisely comment without knowing which line the error is on and the contents of your operator YAML, but the error implies one of the values you have in your `IstioOperator` resource used to be a simple string, but is now a dictionary/map.

By using `istioctl dump profile default` on both versions and diffing them you may discover other differences/removed configuration between the two versions which will not work if you directly apply a `1.7` resource to a `1.8` installer. if that's not it, perhaps check any differences from your manifest to the default [against the `1.8` documentation](https://istio.io/v1.8/docs/reference/config/istio.operator.v1alpha1/).
