### ISSUE TITLE
TestBadRemoteSecret causes future tests to fail once secrets are removed

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#33708]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/33701/integ-pilot-multicluster-tests_istio/1409935357113274368
test fails at 18:10:00. Its missing endpoints for some service
istiod logs show the cluster update at same time: https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/33701/integ-pilot-multicluster-tests_istio/1409935357113274368/artifacts/pilot-de882957a19240769ee1a3c93/TestTraffic/services/case_2_service_port_match_in_cluster_cross-network-primary/_test_context/istio-state096177769/primary/istiod-8ccfbd58c-k2gk2_discovery.log
It looks like a single push (from debounce) is handling removal of the clusters and the addition of the new service

I am fairly sure I have seen this before, but couldn't find an issue...

cc @stevenctl

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gs/istio-prow/pr-logs/directory/integ-pilot-multicluster-tests_istio/1404861847785443328
https://prow.istio.io/view/gs/istio-prow/pr-logs/directory/integ-pilot-multicluster-tests_istio/1404503012868624384

**Comment by howardjohn** [comment]
Did we ever root cause this? I feel like we have still seen it, although its rare

**Comment by howardjohn** [comment]
Possible recent occurances: https://prow.istio.io/view/gs/istio-prow/pr-logs/directory/integ-pilot-multicluster-tests_istio/1430996327751225344

**Comment by stevenctl** [comment]
Ah, sorry about that. I'll keep looking into it.

**Comment by stevenctl** [comment]
I have a better idea of what's happening, but not quite root cause.

<pre><code>

<b>2021-06-29T18:09:45.094570Z</b>	info	Adding cluster no-permissions from secret istio-system/istio-remote-secret-no-permissions
...
<b>2021-06-29T18:10:00.114489Z</b>	error	Adding cluster_id from secret=no-permissions: istio-system/istio-remote-secret-no-permissions failed creating config configStore for cluster no-permissions: context deadline exceeded
2021-06-29T18:09:48.385662Z	info	Processing delete: istio-system/istio-remote-secret-no-permissions
2021-06-29T18:09:48.385713Z	info	Deleting cluster_id=no-permissions configured by secret=istio-system/istio-remote-secret-no-permissions
</pre></code>

The queue in `secretcontroller` gets blocked by the `addCallback` and doesn't begin processing the delete till much later. 
This explains why the issues aren't contained to the window for `TestBadRemoteSecret`, but this still shouldn't affect the main service registries. 

The primary cluster is probably not configuring the inbound for `b-alt-2` for whatever reason. From `a` in `cross-network-primary`

```
outbound|80||b-alt-2.echo-1-8933.svc.cluster.local::172.18.255.156:15443::cx_connect_fail::10
```

**Comment by stevenctl** [comment]
Trying to replicate this by:


0. From an injected `sleep` pod `while true; do curl helloworld:5000/hello; sleep 3; done`
1. Running only 1 istiod with a large debounce (30s, 60s max)
2. Pushing the bad remote secret and waiting 60s+ 
3. Deleting the secret and applying `$iSTIO/samples/helloworld/helloworld.yaml`

Looking at pilot logs, we start to get pushes immediately after the new proxies connect, then some time later we get the debounced push from the service/secrets. 

Pretty much as soon as we push the new helloworld pods the sleep pod gets traffic, so nothing is misconfigured. 

 Any better ideas on how to replicate?

**Comment by howardjohn** [comment]
I tried a lot a while back, I could never reproduce it either...
