### ISSUE TITLE
Propose unifying k8s leader election 

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#33783]
Currently, each module has its own leader election, which is a waste of resources. Leader election can be reused, which means if a istiod acquires leadership, each module acquires the leadership, under the protection, they can do works that have races.

**Comment by hzxuzhonghu** [comment]
cc @howardjohn

**Comment by howardjohn** [comment]
the reason it is split is because different versions of istio may run in the same cluster and have different capabilities. I think it would be hard to change this for the same reason since the old istiod would use the old configmap and the new one would use the new configmap so they would both become leader?

**Comment by hzxuzhonghu** [comment]
Seems the leader identity we are using is a constant, regardless of version info. Need to investigate
