### ISSUE TITLE
Cluster-wide deployment for k8s

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#338]

**Comment by uschen** [comment]
ETA for this?

**Comment by Stono** [comment]
Also very interested in this; we have multiple namespaces within our cluster :)

**Comment by andraxylia** [comment]
This is scheduled for the next release (hint: we use the "milestone" in github).

**Comment by Stono** [comment]
Cool.
At that point it'll be a viable candidate for inclusion in a standard
reference microservice architecture I'm working on!

Thanks

On 12 Jun 2017 8:23 pm, "Andra Cismaru" <notifications@github.com> wrote:

This is scheduled for the next release (hint: we use the "milestone" in
github).

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/istio/istio/issues/338#issuecomment-307893200>, or mute
the thread

**Comment by sroze** [comment]
What are the blockers/limitations to overcome in order to have this feature working? Anything the community can help with?

**Comment by sakshigoel12** [comment]
Please update this epic and all P0 issues, and call out anything that won't be complete by EOW (except docs and testing).
