### ISSUE TITLE
Metrics report error grpc_response_status code 

### ISSUE THREAD

**Issue by fatedier** [istio/istio#34659]
**Bug description**
Service with customized grpc status code such as 100 will export error grpc_response_status code.

```
istio_requests_total{..., grpc_response_status="4294967295", ...}
```

It seems the value is the max of uint32.

GRPC codes in trace and access log are all ok.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Report real grpc status code.

**Steps to reproduce the bug**
1. Send grpc request to service and return custom grpc code 100.
2. Get metrics by curling port 15090 of that pod.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
istio v1.9.7
k8s1.16

**How was Istio installed?**
Helm chart

**Environment where the bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
cc @bianpengyuan

**Comment by bianpengyuan** [comment]
Looks like envoy could [return -1](https://github.com/envoyproxy/envoy/blob/0fae6970ddaf93f024908ba304bbd2b34e997a51/envoy/grpc/status.h#L53 ) when using customized status code: https://github.com/envoyproxy/envoy/blob/0fae6970ddaf93f024908ba304bbd2b34e997a51/source/common/grpc/common.cc#L58

@kyessenov Does [int64 celvalue](https://github.com/envoyproxy/envoy/blob/95038feabf260c3937465951d5da603d31ea3bd4/source/extensions/filters/common/expr/context.cc#L161) handle negative value? I think for this case we probably should fill in -1 for customized response code due to the cardinality concern and document this, and provide a cel expr to get custom grpc status code if posible.

**Comment by fatedier** [comment]
@bianpengyuan I can get correct value from enovy accesslog by `%GRPC_STATUS%` and trace log from `opencensus`.

It still looks strange if we record customized status code as -1 in metrics since it's not consistent with others.

**Comment by bianpengyuan** [comment]
Not sure how envoy deals with grpc status code in stats tag, but feels dangerous to allow random ones. @kyessenov probably would know better

**Comment by kyessenov** [comment]
CEL is not the issue here, it's typed as `int` so should handle the negatives. The issue is in envoy using `uint64` to parse the code https://github.com/envoyproxy/envoy/blob/0fae6970ddaf93f024908ba304bbd2b34e997a51/source/common/grpc/common.cc#L60.

I agree with @bianpengyuan , using negative status codes is not recommended as it may cause some security issue because the code does not expect it.

**Comment by bianpengyuan** [comment]
Ah looks like you can set `allow_user_defined` when getting grpc status: https://github.com/envoyproxy/envoy/blob/0fae6970ddaf93f024908ba304bbd2b34e997a51/source/common/grpc/common.h#L77

@kyessenov should we make cel wrapper allow to return user defined grpc status code and let filter decided what to do with it?

**Comment by fatedier** [comment]
> CEL is not the issue here, it's typed as `int` so should handle the negatives. The issue is in envoy using `uint64` to parse the code https://github.com/envoyproxy/envoy/blob/0fae6970ddaf93f024908ba304bbd2b34e997a51/source/common/grpc/common.cc#L60.
> 
> I agree with @bianpengyuan , using negative status codes is not recommended as it may cause some security issue because the code does not expect it.

I don't use negative status code in my grpc service. Any code greater than 16 may be convert to negative number?
