### ISSUE TITLE
istioctl 1.11.0 build issue

### ISSUE THREAD

**Issue by chenrui333** [istio/istio#34705]
**Bug description**

istioctl 1.11.0 build issue when running `make istioctl istioctl.completion`

And error is below:

```
==> make istioctl istioctl.completion
make: *** No rule to make target `/private/tmp/istioctl-20210813-16296-1l75wdb/out/darwin_amd64/istioctl', needed by `/private/tmp/istioctl-20210813-16296-1l75wdb/out/darwin_amd64/release/istioctl.bash'.  Stop.
make: *** Waiting for unfinished jobs....
ISTIO_OUT=/private/tmp/istioctl-20210813-16296-1l75wdb/out/darwin_amd64 ISTIO_BIN=/Users/brew/Library/Caches/Homebrew/go_mod_cache/bin GOOS_LOCAL=darwin bin/retry.sh SSL_ERROR_SYSCALL bin/init.sh
Skipping envoy debug. Set DEBUG_IMAGE to download.
```

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

- macOS build passed

**Steps to reproduce the bug**

- git checkout the `1.11.0` tag
- setup couple env vars (like `TARGET_ARCH`)
- run `make istioctl istioctl.completion`

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

macOS

**Additional details**

This is the regression upgrade build from 1.10.3 to 1.11.0

relates to https://github.com/Homebrew/homebrew-core/pull/83195

**Comment by howardjohn** [comment]
cc @ericvn since I thought you had some PRs here recently

**Comment by ericvn** [comment]
I have not had any issues with doing the build on my Mac on both `master` and `release-1.11`, and verified by checking out the 1.11.0 label as well. Looking at the brew script, I notice `ENV["BUILD_WITH_CONTAINER"] = "0"`, which is causing the build to be done differently than normal, so tried adding that to my environment. Build still works.

The message implies that Make cannot figure out how to make `.../out/darwin_amd64/istioctl' which is needed by the `out/darwin_amd64/release/istioctl.bash`. This does agree with the BUILD_WITH_CONTAINER=0 since it need's the darwin `istioctl` build to generate the completion. More investigation continuing.

**Comment by ericvn** [comment]
I'm still not able to recreate the failure (with BUILD_WITH_CONTAINER set to 0 or 1).

https://github.com/istio/istio/pull/34093 did change the dependency from `istioctl` to `${LOCAL_OUT}/istioctl` which is needed when things are run in a build_container. Since the message is implying that there is no rule for `${LOCAL_OUT}/istioctl`, it could be the cause. Trying to trace back the value of LOCAL_OUT through the Makefiles and script, things should be setup correctly.

**Comment by ericvn** [comment]
OK. I am now able to recreate the problem. I notice that `-j6` is added as a `make` MAKEFLAGS which allows additional threads, and that uncovers the issue noted here.

**Comment by ericvn** [comment]
https://github.com/istio/istio/pull/34093 had an issue where during the container build the completion targets would fail as the linux version, because we are in the container, of `istioctl` was not getting built:
```
/work/out/linux_amd64/istioctl completion bash > /work/out/darwin_amd64/release/istioctl.bash
/bin/bash: /work/out/linux_amd64/istioctl: No such file or directory
make[1]: *** [Makefile.core.mk:436: /work/out/darwin_amd64/release/istioctl.bash] Error 127
```
The solution for that problem was to change the dependency to match the executable that was being run, so `istioctl`=>`${LOCAL_OUT}/istioctl` which caused the linux `istioctl` to be built and used to create the completion files. I'm not sure how this worked before the changes, and it may not have when run on a Mac.

That solution manifests itself when run in a non BUILD_CONTAINER environment when using multiple `make` threads as noted here.

A solution for this issue is to only use a single thread in the non BUILD_CONTAINER environment which requires no changes here. 
Another solution is to create a new target  `${LOCAL_OUT}/istioctl` which does the build (same as `istioctl`). This allows the threads to see both targets and things build normally.
