### ISSUE TITLE
istioctl analyze IST0137 ignoring namespaces?

### ISSUE THREAD

**Issue by dsbos** [istio/istio#34830]
**Bug description**

Is `istioctl analyze`'s logic for `IST0137` checks ignoring namespaces incorrectly?

When I run `istioctl analyze --all-namespaces` on my cluster/mesh, I get warnings like this:

```
Warning [IST0137] (Deployment redacted-service.ns1) This deployment redacted-service is associated with multiple services [ns1/redacted-service ns2/redacted-service] using targetPort "api" but different ports: [8082 8085].
Warning [IST0137] (Deployment redacted-service.ns2) This deployment redacted-service is associated with multiple services [ns2/redacted-service ns1/redacted-service] using targetPort "api" but different ports: [8085 8082].
```

I do have two services with identical Deployment names, identical Deployment labels, identical Service names, and identical  Service selectors. However, they are in separate K8s namespaces, and don't seem to be interfering with each other.

K8s label selectors are scoped to the namespace of the referring object (at least for Service), right? (I can't find any clear specification of that in K8s docs, but they do _seem_ to confirm that.)

Assuming so, it seems that `istioctl analyze`'s logic for `IST0137` checks doesn't "know" that a Service's label selector is scoped to the referring object's namespace.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

That `istio analyze` wouldn't "think" that labels matched across namespace and that the above case was something to warn about.

**Steps to reproduce the bug**

Create working Deployments and Services consistent with description above.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
client version: 1.10.3
control plane version: 1.9.7
data plane version: 1.9.7 (89 proxies), 1.8.3 (1 proxies)
```

**How was Istio installed?**

Via `istioctl manifest generate` and then applying generated K8s manifests via Argo CD.

**Environment where the bug was observed (cloud vendor, OS, etc)**

In EKS cluster.

**Comment by qodirovshohijahon** [comment]
@hanxiaop 
@istio-policy-bot 
@dsbos 
Hi
I am facing 
Warning [IST0137] (Deployment sample-bookinfo/sample-bookinfo-argocd-server) This deployment sample-bookinfo-argocd-server is associated with multiple services [sample-bookinfo/sample-bookinfo-argocd-server sample-bookinfo/sample-bookinfo-argocd-server] using targetPort "8080" but different ports: [80 443].

Warning [IST0137] (Deployment sample-petclinic/sample-petclinic-argocd-server) This deployment sample-petclinic-argocd-server is associated with multiple services [sample-petclinic/sample-petclinic-argocd-server sample-petclinic/sample-petclinic-argocd-server] using targetPort "8080" but different ports: [80 443].
This waring is caused by the ports on the argocd server
 
It is possible to remove this warning according to the doc, but argo-cd is installed via Helm and deployment/service (argo-cd server deployment and service) cannot be controlled.

istioctl version: 1.20.0
version: 1.18.5

These warnings disappear in version 1.20.0, but I want to fix it without waiting for the upgrade.
