### ISSUE TITLE
Upgrade from 1.9.8 to 1.10.4 fails on Windows

### ISSUE THREAD

**Issue by kekbur** [istio/istio#34914]
### Bug Description

Attempting to upgrade from 1.9.8 to 1.10.4 on Windows by running `istioctl upgrade` yields to following error output:

```2021-08-28T11:25:38.209349Z     info    proto: tag has too few fields: "-"
Control Plane - istio-ingressgateway pod - istio-ingressgateway-6578b7b4f-gq5sf - version: 1.9.8
Control Plane - istiod pod - istiod-76bb986d5b-7mmbw - version: 1.9.8

Upgrade version check passed: 1.9.8 -> 1.10.4.

2021-08-28T11:25:42.952104Z     info    Error: failed to generate Istio configs from file [] for the current version: 1.9.8, error: opening tar archive for reading: wrapping
file reader: gzip: invalid header

Error: failed to generate Istio configs from file [] for the current version: 1.9.8, error: opening tar archive for reading: wrapping file reader: gzip: invalid header
```

From what I can tell the error is due to the following call chain:
[upgrade.go upgrade()](https://github.com/istio/istio/blob/0650c083a792d157837ec80ff59f34762fdfeab3/operator/cmd/mesh/upgrade.go#L211) -> [shared.go GenIOPFromProfile()](https://github.com/istio/istio/blob/0650c083a792d157837ec80ff59f34762fdfeab3/operator/pkg/manifest/shared.go#L138) -> [shared.go rewriteURLToLocalInstallPath](https://github.com/istio/istio/blob/0650c083a792d157837ec80ff59f34762fdfeab3/operator/pkg/manifest/shared.go#L358) -> [shared.go fetchExtractInstallPackageHTTP](https://github.com/istio/istio/blob/0650c083a792d157837ec80ff59f34762fdfeab3/operator/pkg/manifest/shared.go#L341) -> [urlfetcher.go Fetch](https://github.com/istio/istio/blob/0650c083a792d157837ec80ff59f34762fdfeab3/operator/pkg/helm/urlfetcher.go#L89) which calls tgz.Extract on the downloaded zip file, which fails.

The upgrade succeeds on Linux, because the downloaded release file is a tgz archive.

### Version

```prose
PS C:\> istioctl version
client version: 1.10.4
control plane version: 1.9.8
data plane version: 1.9.8 (47 proxies)
PS C:\> kubectl version --short
Client Version: v1.20.0
Server Version: v1.19.13-eks-8df270
```

### Affected product area

- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [X] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by samoersnaes** [comment]
My team is also experiencing the same exact error. We deploy using Windows everywhere, and we were hoping that the issue would have already been fixed in a patch release. This bug is preventing us from upgrading Istio, so I hope adding a +1 to the issue will bring more attention to it. We tend to stay close to new Istio releases, but we are now two minor versions behind thanks to this bug.

By the way, I combed through other open issues and found another issue that could be related: https://github.com/istio/istio/issues/35067

Upgade error:

```
PS C:\> istioctl upgrade
Upgrade version check passed: 1.9.8 -> 1.10.4.

2021-09-30T07:43:17.360489Z     info    Error: failed to generate Istio configs from file [] for the current version: 1.9.8, error: opening tar archive for reading: wrapping file reader: gzip: invalid header

Error: failed to generate Istio configs from file [] for the current version: 1.9.8, error: opening tar archive for reading: wrapping file reader: gzip: invalid header
```

Istio and k8s versions:

```
PS C:\> istioctl version
client version: 1.10.4
control plane version: 1.9.8
data plane version: 1.9.8 (137 proxies)

PS C:\> kubectl version --short
Client Version: v1.22.1
Server Version: v1.21.2
```

**Comment by wsy-cloud** [comment]
Same for our team for upgrades from 1.10.2.

When running `Istioctl` 1.11.3 on Windows, to upgrade Istio from 1.10.2 to 1.11.4 in the K8s cluster, I got an error:

```
Upgrade version check passed: 1.10.2 -> 1.11.3.

2021-10-19T07:42:51.252252Z     info    Error: failed to generate Istio configs from file [C:\Repos\[...]\istio-config.yaml] for the current version: 1.10.2, error: create gzip reader: gzip: invalid header
```

Same when trying to upgrade to 1.11.4 that has been just released.

Then I wanted to try to upgrade in smaller increments, so first from 1.10.2 to 1.10.3. This time I got the following error:

`Error: failed to generate Istio configs from file [C:\Repos\[...]\istio-config.yaml] for the current version: 1.10.2, error: failed to fetch URL https://github.com/istio/istio/releases/download/1.10.2/istio-1.10.2-windows.zip : 404 Not Found`

So `Istioctl` tried to download the installation package for the source version 1.10.2, but it requested the file `istio-1.10.2-windows.zip`, which does not exist, and the correct file name of the installation package is `istio-1.10.2-win.zip` (i.e. requested "**windows**" vs. existing "**win**"). I figured out that this particular [issue](https://github.com/istio/istio/issues/34081) has been fixed in 1.10.4, by [this PR](https://github.com/istio/istio/pull/34163). So when I tried to upgrade to this 1.10.4, I indeed didn't get the abovementioned 404, but instead, I got a variant of the already mentioned error:

```
Upgrade version check passed: 1.10.2 -> 1.10.4.

Error: failed to generate Istio configs from file [C:\Repos\[...]\istio-config.yaml] for the current version: 1.10.2, error: opening tar archive for reading: wrapping file reader: gzip: invalid header
```
I may suspect that due to recent changes to the functionality of downloading the Windows installation package for the source version of the upgrade, some bug got sneaked in, and the mentioned _gzip reader_ cannot access the file.

The upgrade 1.10.2 -> 1.11.4 has finally run without any problems only when **executed on Linux** (Windows Subsystem for Linux - WSL), and not on plain Windows.

**Comment by emilwangaa** [comment]
I've been digging a bit to try and figure out the root cause of this and I think I might been on to something.

In 1.9 when doing an upgrade the releaseURLPathTemplate was always based on the osx tar release (https://github.com/istio/istio/blob/1.9.9/operator/cmd/mesh/upgrade.go#L63): 

```go
// releaseURLPathTemplate is used to construct a download URL for a tar at a given version. The osx tar is
// used because it's stable between 1.5->1.6 and only the profiles are used, not binaries.
releaseURLPathTemplate = "https://github.com/istio/istio/releases/download/%s/istio-%s-osx.tar.gz"
```
That seems to be okay because it only needs the profiles and not the binaries.

In 1.10 this was changed to this (https://github.com/istio/istio/blob/1.10.0/operator/cmd/mesh/upgrade.go#L63):
```go
// releaseURLPathTemplate is used to construct a download URL for a tar at a given version.
releaseURLPathTemplate = "https://github.com/istio/istio/releases/download/%s/istio-%s-%s"
```
And then this platformBasedTar function (https://github.com/istio/istio/blob/1.10.0/operator/cmd/mesh/upgrade.go#L269)
```go
func platformBasedTar() (tarExtension string) {
	defaultExtension := "osx.tar.gz"
	switch runtime.GOOS {
	case "linux":
		tarExtension = runtime.GOOS + "-" + runtime.GOARCH + ".tar.gz"
	case "windows":
		tarExtension = runtime.GOOS + ".zip"
	case "darwin":
		tarExtension = defaultExtension
	default:
		tarExtension = defaultExtension
	}
	return tarExtension
}
```
So it has changed from downloading a .tar.gz file to a .zip file and eventually ends up trying to untar a zip file which doesn't work.

I wonder if simply changing the switch case for windows to defaultExtension will actually just works?

@howardjohn do you have any suggestions or feedback on this? I'll happily create a PR for the above if it might be a viable solution?

**Comment by jellebens** [comment]
same issue here when upgrading to from 1.9.9 to 1.11.4

**Comment by jellebens** [comment]
still the case in 1.12

**Comment by emilwangaa** [comment]
@kekbur can you reopen this issue? As @jellebens mentions it is still a problem for 1.12 so going to submit a PR to fix this but would like not to create a new issue.

**Comment by kekbur** [comment]
@emilwangaa It seems that I can't reopen this issue. At least I can't see the button anywhere.

**Comment by Anoojak** [comment]
HI can you please reopen the issue we are facing issues when we are trying to upgrade from 1.9 to 1.10 of istio

Error: failed to generate Istio configs from file [dev.yaml] for the current version: 1.9.4, error: opening tar archive for reading: wrapping file reader: gzip: invalid header
