### ISSUE TITLE
e2e simple not run by prow pre submit anymore

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#3509]
e2e simple is a fast and reliable "new gen"(from oct) test that has high signal,
unlike bookinfo
it was run until a couple days/weeks ago - I strongly argue it should be run
it can be run in parallel and will finish faster than bookinfo

**Comment by ldemailly** [comment]
can we run both (in parallel) ?

**Comment by ldemailly** [comment]
ps: mixer test isn't flacky - there are bugs in the code

**Comment by hklai** [comment]
There were flaky and I filed a couple issues that were fixed. =)

Are we going to make these prow tests required now?

I can look into running both.



On Feb 14, 2018 7:00 PM, "Laurent Demailly" <notifications@github.com>
wrote:

ps: mixer test isn't flacky - there are bugs in the code

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/istio/istio/issues/3509#issuecomment-365813062>, or mute
the thread

**Comment by costinm** [comment]
Simple is run in circle - and is quite reliable and fast, I think we can
add that to required.

**Comment by costinm** [comment]
I think the agreement was to add tests to required if it completes in ~20
min and has a history
of stability.

I am +1 on adding the e2e test in circleci to required, but let's not
reopen the discussion on
 prow. If the tests are failing in prow - please file bugs and follow up,
there is no need to block
non-google engineers on that.

**Comment by hklai** [comment]
Well I heard different things in the sync meeting on Monday, and people
wanted to include prow tests.

I do agree we need to collect more data about prow test stability however.

**Comment by ldemailly** [comment]
in the meantime bugs sneak in
but for now, given it's not blocking anyway - can it please show the e2esimple and mixer test results (I think I fixed the mixer within 24h, probably before the test was removed... in the future maybe let's aim to fix rather than remove tests)

**Comment by hklai** [comment]
OK presubmit now runs both simple and bookInfo tests.
