### ISSUE TITLE
merge/unify the 2 iptables scripts and support selectable inbound/outbound interception 

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#3514]
see for instance #3059

**Comment by nmittler** [comment]
@ldemailly @PiotrSikora #3469 was created to address the same problem of supporting sidecars on ingresses.  We should close one.

**Comment by ldemailly** [comment]
@nmittler Doing it long term through pilot and configuration of the agent or envoy is good to have (and would give inbound telemetry and mixer rules possibly)

The iptables solution is more a quick fix/workaround - so the two issues aren't exclusive and can/should proceed in parallel
(cc @costinm with whom we discussed this too)

**Comment by nmittler** [comment]
@ldemailly sgtm, thanks.  Would you mind if I took this issue ... it would be a good way to learn more about the internals

**Comment by ldemailly** [comment]
run with it!

**Comment by nmittler** [comment]
@ldemailly thanks!  ... and get some sleep! :)

**Comment by nmittler** [comment]
@ldemailly @costinm for the case where we have a sidecar on ingress, the suggestion from #3059 was to remove the line:

https://github.com/istio/istio/blob/1f22391d8e6aba7926276c10e4b64a9a0db4c721/pilot/docker/prepare_proxy.sh#L55

What would happen if an in-mesh service were to try hitting the ingress?

**Comment by ldemailly** [comment]
I put you up for the related https://github.com/istio/proxy/issues/1129

**Comment by ldemailly** [comment]
> What would happen if an in-mesh service were to try hitting the ingress?

it would not work with mtls (it's mentioned in the thread as one of the downside) - on the flip side, why would an in mesh service use the INgress ?

**Comment by nmittler** [comment]
> it's mentioned in the thread as one of the downside

Which thread are you referring to? Do you have a link?

**Comment by nmittler** [comment]
Oh I see, I think you're referring to https://github.com/istio/istio/issues/3059#issuecomment-365794988

**Comment by Stono** [comment]
This is correct and it's absolutely fine, as @ldemailly said this is an INgress, for non-mesh traffic to enter.

In our use case its:  
Client -> https -> INgress -> [nginx -> istio-proxy] -> [istio-proxy -> backend-service1 -> istio-proxy] -> [istio-proxy -> backend-service2]

**Comment by nmittler** [comment]
@Stono yup, that's the plan ... we're going to try to cook something up for 0.7.0. Stay tuned.

**Comment by Stono** [comment]
Brill, if I can help with testing in any way just let me know.

**Comment by nmittler** [comment]
@costinm @ldemailly @ZackButcher 

Just chatted with Zack... Up to this point, I had been treating this issue as a step toward #3469, but I'm not sure it's needed.

Rather than doing iptables magic at ingress, we could just deploy nginx with an `istio-proxy` sidecar, but no `proxy-init` init container (i.e. no iptables). The nginx deployment would then just have to forward all traffic to `localhost:15001`.

A nice artifact of this is that `proxy-init` stays pure - always NATing, since it's just for mesh nodes, not ingress.

WDYT?

**Comment by costinm** [comment]
It won't work - port 15001 depends on iptables intercepting traffic, it uses original_dst. 
But nice try :-)

**Comment by costinm** [comment]
One hack for #3469  would be to not intercept port 80 and 443 (the VM script has this option, we can add it in the other) - it will work as long as services in mesh don't use 80 or 443.

We also have few 'egress' related bugs that can be helped by excluding ports from interception, in 
particular 443.

I think we can push this back to 0.8 (P2 in 0.7)- but we still want to do it before 1.0, and sooner
is better.

**Comment by ldemailly** [comment]
we should really do the unification in 0.7 if at all possible (1 iptable script across all istio repos) - that's the release where it will get a chance to get good testing

**Comment by nmittler** [comment]
@costinm 

> It won't work - port 15001 depends on iptables intercepting traffic, it uses original_dst.
But nice try :-)

IIRC, the issue was that the sidecar was intercepting traffic on the inbound side, before it got to nginx. If we removed the NAT manually, nginx seems to correctly preserve the original IP.

With that said, it would seem that if we were to remove iptables altogether and configure nginx on port 80, forwarding all traffic to port 15001, it should still maintain the original IP. Or am I missing something?

**Comment by nmittler** [comment]
Also, this idea was suggested by @rshriram here: https://github.com/istio/istio/pull/3562#issuecomment-366360751

**Comment by linsun** [comment]
I actually got this working late last year by providing my own pilot agent and use it to build my own proxy image.... so I have nginx forward traffic to envoy with nginx and envoy both in 1 pod... envoy isn't capturing all traffic on the pod, rather it is listening on port 15001.  

Sorry It is not clean to me what user scenario you are trying to solve as I'd like to understand if we are sharing similar user scenarios.

**Comment by linsun** [comment]
reading more on chat history... @Stono that is exactly my scenario too... Client -> https -> INgress -> [nginx -> istio-proxy] -> [istio-proxy -> backend-service1  cc @dcberg @ijsnellf

**Comment by nmittler** [comment]
@linsun thanks! The original problem is described in #3059. Basically the desire was to use nginx for ingress, but have a sidecar attached so that it could use mTLS within the mesh.

The problem we ran into with the default injection is that the iptables will route both inbound and outbound traffic through Envoy. This means that an inbound request would look like this:

ingress->`[Envoy->nginx->Envoy]`->`[Envoy->Service]`

(where the surrounding [] denotes pod boundaries)

**Comment by linsun** [comment]
@nmittler thanks!  yes, in that case, you would not want envoy to capture the inbound and outbound traffic... I used the istio proxy configuration similar as istio ingress in my POC, without the proxy init container.

**Comment by nmittler** [comment]
@linsun makes sense ... should be essentially the same result.  I'm going to try to get this in for 0.7.0 (see #3469

**Comment by PiotrSikora** [comment]
@nmittler what @costinm meant is that if you replace iptables interception with simple forwarding, then istio-proxy sidecar won't know where you want to connect and how should it route traffic, because normally that information is inferred from the original (pre-iptables) destination address, but that's going to be useless and always static (i.e. 127.0.0.1:15001) if you simply forward traffic there.

**Comment by linsun** [comment]
@PiotrSikora agreed, that is the missing piece that needs to be sorted out. In my POC, as a user, I still configure ingress with istio which essentially taught that istio-proxy sidecar (next to nginx) where to route first.  we should do that as step 1 imho.  step 2 is to based on the nginx ingress configure, we auto configure the istio-proxy on which service to forward to next.

**Comment by nmittler** [comment]
@PiotrSikora can't nginx just be configured with `proxy_pass` to retain the original URL?

**Comment by ZackButcher** [comment]
@PiotrSikora doesn't the [PROXY protocol](https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt) address this? Both NGINX and Envoy support it, seems like we can just enable it in bootstrap config for this deployment topology.

**Comment by PiotrSikora** [comment]
@nmittler it could, but then you'd need to do host-based routing in the sidecar to take advantage of that, which is not what we do right now (AFAIK). Also, this would require some changes to nginx.conf, which goes against the promise of transparent / drop-in onboarding into service mesh.

@ZackButcher both can accept connections with PROXY protocol, and NGINX can emit PROXY protocol when proxying TCP traffic, but neither can emit PROXY protocol when proxying HTTP traffic, so that's not going to work for us.

**Comment by Stono** [comment]
FYI GCP LoadBalancers don't support proxy_protocol :-)
Thanks for looking at this all!

**Comment by nmittler** [comment]
@stono 

> FYI GCP LoadBalancers don't support proxy_protocol :-)

I don't think they would need to, since all traffic would be pod-local.  But yeah, I think an iptables solution is going to be the way forward ... at least for now.

**Comment by andrew-dinunzio** [comment]
Is this issue related to Egresses not communicating with the Mixer for metrics? See [this thread](https://groups.google.com/d/msg/istio-users/yQVEZs9fPNw/RUEf_cSWBwAJ).

If so, are there any known workarounds to be able to scrape metrics and tracing info from egress traffic until this is resolved?
