### ISSUE TITLE
istio-sidecar-injector should reload configuration when configmap changes

### ISSUE THREAD

**Issue by Stono** [istio/istio#3515]
Hey, 
It'd be nice if the sidecar injector monitored the `istio-inject` configmap for changes and live reloaded.

At the moment, if I modify that configmap I have to manually delete the pod.

Ta
Karl

**Comment by sakshigoel12** [comment]
@ayj can you take a look?

**Comment by rshriram** [comment]
@loewenstein  is looking at this. These changes are a bit more involved. Cc @douglas-reid

**Comment by Stono** [comment]
To be clear, this isn't a huge problem.  I can work around it by doing https://github.com/kubernetes/helm/blob/master/docs/charts_tips_and_tricks.md#automatically-roll-deployments-when-configmaps-or-secrets-change

I'm trying to make the continuous integration and deployment of istio as automated as possible :-)

**Comment by ayj** [comment]
Do you see this problem with master / 0.5.1?

**Comment by Stono** [comment]
Hey, yes I'm on 0.5.1, should it be live reloading the configmap?

**Comment by ayj** [comment]
This should be fixed in master. See
https://github.com/istio/istio/pull/2944

**Comment by loewenstein** [comment]
@Stono is this issue only about the sidecar injector webhook picking up `istio-sidecar` changes for any new sidecar injection? (In contrast to config changes that would be applied to already running sidecar proxies) If yes I suppose @ayj is right and this should be fixed by #2944 

What @rshriram is referring to is the idea that at least certain configuration changes should be picked up by all Istio components. E.g. if you start using Istio without mTLS but want to enable it later on, or start without mixer and enable it later.

**Comment by Stono** [comment]
Hola, so just to be clear this was the use case:

  - Deploy injector config
  - Deploy injector
  - Deploy App 1
  - Change injector config
  - *expect injector to reload the template*
  - Deploy App 2 - *expect injected with updated template*

**Comment by ayj** [comment]
@Stono - #2944 should address your use case. Closing this issue for now, but please reopen if the problem persists with 0.6 (or master).
