### ISSUE TITLE
Handle 1.12 contrib-image changes

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#35336]
> https://www.envoyproxy.io/docs/envoy/latest/start/install#install-contrib

In 1.20 envoy (1.12 Istio), some filters are removed from the core image. I believe this will impact our build, as we inherit this.

MySQL filter is used by Istio, albeit in alpha behind an env var flag.

We should consider how to handle this... some ideas:
* Add them all back (as EnvoyFilter could use them)
* Add only mysql back, since its the only 'first class' one
* Keep them removed (and possibly even remove others), and remove first class mysql support
   * Possibly remove the other perma-alpha protocol filters as well

cc  @zhaohuabing @kyessenov

**Comment by zhaohuabing** [comment]
If Envoy project thinks some filters are not mature enough to be included in the official imagine, maybe we should follow this policy as well. Could it possible that Istio proxy also provides two images: one only has official extensions and one includes the filters in the Envoy contrib directory? Then users can choose what images to use based on their use cases.

Another relevant but not direct issue about third-party protocols support is that Istio requires envoy filter proto go API to be compiled with its core repo. Otherwise validation webhook will complain it doesn't know the proto. So when I try to support a new protocol to Istio via EnvoyFilter, I have to modify Istio source code as well, like this:https://github.com/aeraki-framework/istio/blob/270b62b9eff7dfb6439204c0d6be2ed876d82264/pkg/config/xds/filter_types.gen.go#L368

Can we eliminate this dependency somehow?

**Comment by poussa** [comment]
I would vote for Istio proxy project to build two images (official and contrib). In order to move from contrib to official, the Envoy project requires users of the feature. If Istio proxy produces both images it makes much easier for the users to try out the contrib images, thus gaining the required users.

**Comment by durd07** [comment]
I also would vote for Istio project to build two images(official and contrib). There will be more and more envoy extensions contribute to contrib in the future. In order to support them in Istio, we can now only change the file `filter_types.gen.go`(maybe better solution in the future) but no more changes.

**Comment by lambdai** [comment]
envoy.filters.network: ..., envoy.filters.network.kafka_broker, envoy.filters.network.kafka_mesh, envoy.filters.network.local_ratelimit, envoy.filters.network.metadata_exchange, envoy.filters.network.mongo_proxy, envoy.filters.network.mysql_proxy,


envoy.filters.http: ..., istio.alpn, istio_authn, match-wrapper

**Comment by lambdai** [comment]
1.12 issue is resolved. 

ALPN filter will be deprecated with tunnel solution, but not now. Let's discuss in dedicated thread
