### ISSUE TITLE
something weird with ALS

### ISSUE THREAD

**Issue by zirain** [istio/istio#35365]
### Bug Description

Here's an simple [ALS server demo](https://github.com/zirain/als/blob/2c43f4d42983c0fb1c12a24b077199e497678652/cmd/main.go#L28)

right now I want to unmarshal `wasm.upstream_peer`\`wasm.downstream_peer` with fbs

why must the offset should be setted to 3, otherwise there will be panic as follow:
![image](https://user-images.githubusercontent.com/4354057/134789817-858f264f-9768-49a1-b551-6c976bd7ad65.png)

`node := Common.GetRootAsFlatNode(upstream.GetValue(), 3)`

there is a bug? or flatbuffer cross language issue?

### Version

```prose
istioctl version
client version: 1.8.4
control plane version: 1.8-dev-433b6f166412ae46ab54db5cba659011e1e03fd1
data plane version: 1.8-dev (10 proxies)


kubectl version --short
Client Version: v1.17.11
Server Version: v1.17.17-r0-CCE21.3.1.B003-17.37.2
```

**Comment by bianpengyuan** [comment]
I don't know much at flatbuffer. @kyessenov is the expert and probably knows about your issue. But fwiw, you are developing based on an implementation detail which can be changed anytime (we may even move away from Wasm/flatbuffer sometime in the future). Before investing more effort into this path, I would suggest considering some other ways such as resolve metadata at your logging service based on pod ip etc, instead of relying on Istio's metadata exchange.

**Comment by zirain** [comment]
> I don't know much at flatbuffer. @kyessenov is the expert and probably knows about your issue. But fwiw, you are developing based on an implementation detail which can be changed anytime (we may even move away from Wasm/flatbuffer sometime in the future). Before investing more effort into this path, I would suggest considering some other ways such as resolve metadata at your logging service based on pod ip etc, instead of relying on Istio's metadata exchange.

what's is the future plan of metadata exchange?

**Comment by bianpengyuan** [comment]
> what's is the future plan of metadata exchange?

There is no plan yet, but there definitely can be changes which could break your implementation.
