### ISSUE TITLE
standard istio duration metric uses milliseconds instead of seconds as unit

### ISSUE THREAD

**Issue by juanhotencoding** [istio/istio#35445]
### Bug Description

For the prometheus based metrics best practice naming convention is to use seconds instead of milliseconds https://prometheus.io/docs/practices/naming/ it looks like this changed in 1.9 when all other version used seconds.

### Version

```prose
1.9
```

**Comment by douglas-reid** [comment]
That switch, iirc, was because of the shift to envoy-based generation of metrics. The information reported from Envoy uses different units. So, the naming switch was intentional.

FWIW, I don't see anything in the best practices guide that makes `seconds` a convention. In particular, it states: `should have a suffix describing the unit, in plural form`, as well as `do not mix seconds with milliseconds`. I believe that these changes are inline with those guidelines.

Do you read the guide differently?

**Comment by ellisda** [comment]
FYI - the prometheus naming convention says `should use base units (e.g. seconds, bytes, meters - not milliseconds ...` just above the part you linked about `in plural form`.

I can understand that envoy may take a different approach where it tallies these metrics, but ideally these would be converted to SI base units when they get exposed as prometheus metrics.

**Comment by douglas-reid** [comment]
@ellisda I definitely read too quickly. Thanks. 

There have been a few PRs that cover the units and the naming:
- https://github.com/istio/proxy/pull/2701
- https://github.com/istio/proxy/pull/2409

I _believe_ the original issue was that Envoy did not provide customization of the bucketization schemes, which meant that there was a clear loss in resolution when reporting seconds (v. milliseconds). 

Now that envoy provides metric-specific histogram bucketing (https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/metrics/v3/stats.proto.html?highlight=stats#config-metrics-v3-histogrambucketsettings), there may be an opportunity to change back.

This would have to be weighed against the cost for maintaining both options, etc., to support backwards compatibility, etc. We _may_ be stuck with less-than-ideal naming.

@mandarjog @bianpengyuan thoughts? other recollections about the issues here?

**Comment by bianpengyuan** [comment]
It is unfortunate, but I feel unless there is some real integration problem that blocks usage of Istio metrics, we should avoid maintaining two styles.
