### ISSUE TITLE
All TCP outbound traffic drooped with CODE NR during istio upgrade

### ISSUE THREAD

**Issue by softcane** [istio/istio#35502]
### Bug Description

We are experiencing an intermediate issue while upgrading istio from _1.7.8_ to _1.8.6_. During the upgrade, all _outbound TCP_ traffic originated where _1.7.8_ are drooped if the respective sidecar proxy connects to the _istiod 1.8.6_.

The connection works fine when the control plane and proxy are both 1.7.8 or 1.8.6.

Access Log
` "- - -" 0 NR "-" "-" 0 0 0 - "-" "-" "-" "-" "-" - - 10.2.1.166:6369 172.23.122.25:48660 - -`

_The 1.7.8 proxy configured by 1.8.6 istiod has filter chain matches that look like bellow. The match config included   "transportProtocol": "raw_buffer" which I think is the source of the issue._

```
{
  "transportProtocol": "raw_buffer",
  "applicationProtocols": [
    "http/1.0",
    "http/1.1",
    "h2c"
  ]
}
```

It's not clear what's the root cause but looks like code _`NR`_ indicates a filter mismatch case.

Any suggestion?

### Version

```prose
$istioctl version
client version: 1.8.6
control plane version: 1.8.6
data plane version: 1.7.8 (198 proxies)
```

**Comment by howardjohn** [comment]
@softcane sorry you are seeing issues. Unfortunately, istio 1.7 and 1.8 are EOL, so even if we did discover a bug here we could not patch it. I would recommend looking into https://istio.io/latest/docs/setup/upgrade/canary/, which is the recommended way to upgrade and makes this type of error nearly impossible (its likely due to version skew between proxy and control plane - with canary upgrade there is no skew).
