### ISSUE TITLE
5 day gap in daily builds

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#3609]
couple of issues:
a) where do I look to find out why dailies aren't happening / failing
b) on-call should get an email if we miss more than 1 daily
( was going to add c) what do I need to fix / how do I get a fresh daily but one just showed up )

**Comment by hklai** [comment]
1. See go/istio-release-pipelines (google only for now, and we are working on making this accessible to the community).

2. alerts are sent to isito-engprod@ for now, but we can cc oncall as well.

**Comment by mattdelco** [comment]
The slightly more public option (assuming it's a test failure rather than a build failure) is to look at prow.istio.io and filter on istio-release-robot as the author.  If there's a monthly release going on then you might have to look at the the corresponding PR to see which build date/version was attempted.

**Comment by cmluciano** [comment]
@hklai Is https://prow.istio.io/?author=istio-release-robot sufficient? I'm not sure if this is useful to add to the on-call or test docs.

**Comment by hklai** [comment]
There is a big overlap between release tests and post submit tests, which oncall already covers.

(At the moment, the same tests apparently are failing in both. https://prow.istio.io/?repo=istio%2Fistio&type=postsubmit)

Since there isn't much oncall can do with daily release, I don't think it is useful to an it to the oncall doc for now.
