### ISSUE TITLE
Upgrading Operator to 1.12.0 results in two dueling operators

### ISSUE THREAD

**Issue by therealmitchconnors** [istio/istio#36207]
### Bug Description

If you install the istio operator using helm from version < 1.12.0, then upgrade to 1.12.0 using helm, by default the namespace of the operator changes from istio-operator to default, which may cause two operators to run for the same revision concurrently.

To demonstrate this, run: 

```
helm template --include-crds istio-1.11.4/manifests/charts/istio-operator/ > op-1.11.4.yaml
helm template --include-crds istio-1.12.0/manifests/charts/istio-operator/ > op-1.12.0.yaml
diff op-1.12.0.yaml op-1.11.4.yaml
```

I have not been able to verify if this affects other mechanisms for installing the operator, such as `istioctl`, or to explore the implications of running multiple concurrent operators.

### Version

```prose
1.12.0, and any prior supported version

helm version --short
v3.5.3+g041ce5a
```
```


### Additional Information

_No response_

**Comment by dgn** [comment]
This change is causing the change in behaviour: https://github.com/istio/istio/commit/d51c30180cc057a0e161ce8b349a274a6c202f22#diff-05d941404f07b3f1c5be7bea6f19619a7ff3ce41a12a63f929b39358c6adc4e7

I guess the idea was that the user has to create the namespace themselves instead of it being created by the chart. It can be fixed by adding `--namespace istio-operator` to the `helm` call. I guess we should make a note about that somewhere
