### ISSUE TITLE
Istio can't seem to track traffic from Kong across namespaces

### ISSUE THREAD

**Issue by emoyly** [istio/istio#36833]
### Bug Description

I have this setup where my Kong gateway lives in the Kong namespace, and my application lives in another. Currently I'm not using any virtual services or anything fancy like that, i just am using it all with the regular Kubernetes DNS and Ingress rules, and having Istio injection enabled. 
But if i apply any rules limiting traffic to my application namespace, to say only come from the Kong namespace, the Kong traffic is still rejected. 
Looking at Kiali, the Kong traffic appears out of an "unknown" node.
![chrome_Rbgu4hRsKr](https://user-images.githubusercontent.com/24597604/149430870-99bd1acd-dada-45bf-b0c2-480d9609992c.png)

This is a development and testing cluster, so I am aware that a lot of this is very suboptimal and weird. But I wouldn't think that would make Istio just unable to see where traffic is coming from?

### Version

```prose
$ istioctl version
client version: 1.12.0
control plane version: 1.12.0
data plane version: 1.12.0 (18 proxies)

$ kubectl version --short
Client Version: v1.22.2
Server Version: v1.22.2
```

### Additional Information

[bug-report.tar.gz](https://github.com/istio/istio/files/7866774/bug-report.tar.gz)

**Comment by bianpengyuan** [comment]
Unfortunately this is a known limitation to the telemetry. The server side sidecar cannot get what client workload is if client is not injected with a sidecar.

**Comment by emoyly** [comment]
Both my application and the Kong gateway has the istio sidecar injected

**Comment by bianpengyuan** [comment]
> But if i apply any rules limiting traffic to my application namespace, to say only come from the Kong namespace, the Kong traffic is still rejected.

Could you expand a bit on what does this mean? What did you apply? What do you mena traffic is rejected? Was there any actual errors you observed or just kiali is not displaying kong workload properly?

And in your case, traffic from kong gateway is all flowing to the `authbackend`?

**Comment by emoyly** [comment]
Ah yea sorry, i see that didn't make a whole lot of sense without context.
We tried adding the following policy

```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  namespace: strairecloud
  name: internalcomms-allowlist
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces:
          - kong
          - strairecloud
```

And this just made everything respond with an access denied error. We're suspecting that that is because Istio cannot trace the traffic from Kong, as Kiali shows it as unknown traffic

**Comment by douglas-reid** [comment]
I think there might be multiple issues:

(1) There is the telemetry issue, where some traffic is showing up as "unknown". This typically happens when peer metadata for the client is not exchanged with the server.

When looking at the stats for the authbackend proxy, I see requests to `authbackend.strairecloud.svc.cluster.local` from `unknown`.  However, when check the stats from the Kong gateway, I see no outgoing requests to that same service. Instead, I see services like: `grafana.strairecloud.com`, `iam.strairecloud.com`, `k8sdash.strairecloud.com`, `kiali.strairecloud.com`, `pfsense.strairecloud.com`, and `pve.strairecloud.com`. I also see TCP connections to `redis-replicas.strairecloud.svc.cluster.local`.

This would seem to imply that the `unknown` traffic isn't from the Kong gateway.  If it is from the Kong gateway, it does not appear to be passing through the proxy (which could explain things).

(2) Security policy issues. These should be independent of Telemetry function. However, if there is a core communication issue, they could likewise be impacted.
