### ISSUE TITLE
go-junit-report: report junit failures for TestMain issues

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#36972]
A very common issue I see when debugging integration tests is for TestMain (install) to fail. The junit report has no logs, so users look at the prow highlighted errors, which have irrelevant warnings/errors.

it would be great to get Testmain logging. I think we can hack this into the test framework.

For example:
```

func TestMain(m *testing.M) {
	fmt.Println("=== RUN TestMain")
	fmt.Println("printmain")
	exitCode := m.Run()
	fmt.Println("--- FAIL: TestMain (0.00s)")
	os.Exit(exitCode)
}
``` 

Seems to trick go-junit-report into getting our TestMain info into the report

cc @chizhg

**Comment by chizhg** [comment]
There is another inconsistent behavior I recently found for `TestMain`: 
if the test package only contains `TestMain`, or all tests are skipped, `go-junit-report` will not include `TestMain` in the junit result if it passes, but will include it if it fails.

This is a different issue but just wanna track them together since they are both related to `TestMain`.
