### ISSUE TITLE
Transform objects in shared informers

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#37092]
https://github.com/kubernetes/kubernetes/pull/107507 has possibly huge impacts for us to allow us to transform objects 1x at the lowest level. This can reduce memory usage and redundant conversions

**Comment by dddddai** [comment]
I think we can work on this now as https://github.com/istio/istio/pull/38721 is merged, and I [took a try](https://github.com/dddddai/istio/commit/0ceaf1e0c55719f8cfa8b337763f3f274b537fad), but I found it's a little bit risky because we have to find out all necessary fields where we could possibly miss something

Do you think it's fair enough to transform objects like this?

**Comment by howardjohn** [comment]
Yeah TBH even though this was my idea I am a bit skeptical its worth the cost. Its something to keep in mind, but may be better suited for objects that we only need a tiny subset but are very large. For example, if we just needed the list of versions for CRDs or something (hypothetical - we don't have that use case).

**Comment by dddddai** [comment]
How about stripping unnecessary fields(like `metadata.managedFields` for all resources, it's large and I don't think we ever use it) rather than retaining necessary ones? I think it's much easier and could save memory with few code changes
