### ISSUE TITLE
Use ECDS for Istio Filters

### ISSUE THREAD

**Issue by sschepens** [istio/istio#37172]
Currently Istio enables a bunch of filters and some more for features like AuthorizationPolicy, RequestAuthorization, etc.

This Filters are configured "statically" through LDS, this means that we have to update (and drain) the listener in order to update RBAC policies for example.

ECDS allows for configuring Filter configurations in a different DiscoveryService, to allow updating them without updating Listeners.

I see this was [discussed](https://github.com/istio/istio/issues/25484) more than a year ago, but seems that no conclusion was made. Since then, Istio now supports ECDS, but only for WASM filters.

**Comment by bianpengyuan** [comment]
FWIW, ECDS itself is still pretty new and can take some time to improve and prove that it is ready at production quality for stable feature like RBAC (e.g. with Wasm we recently found a crash due to ECDS update, and ECDS misses lots of utils such as config dump, and istioctl tool integration etc). Hopefully Wasm adoption could help to drive this forward

**Comment by shonecyx** [comment]
Shall we revisit this and is there plan to support this?  It's going to address the data plane impact during envoyfilter change. @howardjohn
