### ISSUE TITLE
Istiodless istioctl ps command broken when more than one remote istiod

### ISSUE THREAD

**Issue by frankbu** [istio/istio#37217]
### Bug Description

The `istioctl ps` command needs to aggregate the results from ALL istiod instances. In the non-remote istiod case, `istioctl` does this by sending requests to all the istiod pods in the cluster.

This is not possible when we have an external control plane because all `istioctl` has is the discovery endpoint which delegates requests to only ONE of the istiod instances. As a result `istioctl ps` only returns a partial answer whenever there is more than one istiod serving requests remotely.

We will need some kind of "aggregate status" API that istioctl can call where the target instance calls other instances and aggregate the result before returning, or something like that?

### Version

```prose
every version
```

**Comment by esnible** [comment]
cc: @therealmitchconnors 

This problem was the central design issue of the UX WG in 2019.  It was never solved.

Users were given a `ps` command, which they expect to list all pods.  Solutions discussed

1. Remove `ps`, perhaps it is too powerful
2. The Istiod XDS debug API should have an option for one Istiod to fan out the query to its peers and combine the result before replying
3. Cloud operators wishing to support `ps` should install a proxy that fans out `ps` and combines the result, and install that in front of the Istiod API offered to CLI users
4. Istiods should record their clients in some kind of ConfigMap.  When responding to the XDS API for PS, they should return the combined config maps of all the Istiod, rather than just a result based on internal data structures.

The networking WG felt 2 and 4 introduced too much complexity/risk to Istiod.
3 works, and cloud providers could do it on their own.  The code is trivial, but no one wanted to own this work.
