### ISSUE TITLE
[Testing] Make all networking tests support multiple clusters

### ISSUE THREAD

**Issue by nmittler** [istio/istio#37305]
### Bug Description

This is just for the pilot tests.

There are a ton of tests that are currently skipped when running in multicluster mode. We need to identify and fix any tests that are skipped when using multiple clusters.

Some things to search for:

- `RequireSingleCluster`, `RequireMultiPrimary` ... both should be removed.
- `.IsMulticluster()` identifies some call sites that are multicluster-specific

### Version

```prose
NA
```

**Comment by nmittler** [comment]
@stevenctl any update?

**Comment by stevenctl** [comment]
Networking tests still using RequireSingleCluster are both testing different install approaches (operator, helm). They would each involve re-implementing the logic for installing cacerts, pushing secrets, etc.

Things that have RequireMultiPrimary:

* endpointslice suite (this actually tests Endpoints mode in newer k8s versions since EndpointSlice became the default)
  * looks like the RequireMultiPrimary was added as part of an MCS PR. Trying to change that now.. https://github.com/istio/istio/pull/39409
* CNI suite... I don't really have the details about _why_ this was disabled. 
* MCS suite.. also don't have the details
* Revisions tests: attempted to enable here https://github.com/istio/istio/pull/39410
