### ISSUE TITLE
Running multiple services on the same virtual machine

### ISSUE THREAD

**Issue by zoltanmms** [istio/istio#37345]
**Describe the feature request**

Support running multiple services on the same virtual machine, maintaining Tetrate's [add-on support](https://docs.tetrate.io/service-bridge/1.4.x/en-us/setup/onboarding-vms) for dockerized VM sidecars.

**Describe alternatives you've considered**

WorkloadEntry CRDs appear to be unique per VM IP. By default we're not able to provide our VMs with multiple public IP addresses and even if we could there's the risk that further assumptions are made down the line about the 1-to-1 relationship.

The only viable alternative, then, is to split deployment onto separate VMs which would come at additional resource and operational cost.

**Affected product area (please put an X in all that apply)**

[x] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[x] Virtual Machine
[ ] Multi Control Plane

**Additional context**

We plan to use VM workloads as a possible first step towards cloud integration whereby we only need deploy a sidecar next to otherwise untouched existing workload to make it part of the mesh. We've got a vast number of applications that need migrating in this way, a subset of those have multiple services deployed on the same host. This improvement would help us migrate these without any additional hassle.

A related limitation we have is no root privileges on the VMs. Stock Istio doesn't support anything else but Tetrate makes provisions to run the Sidecar from a container. It would be useful to implement the multi-service-one-vm functionality in such a way that Tetrate's support for dockerized sidecars is retained.

**Comment by bianpengyuan** [comment]
Curious why do you think service and worloadentry/VM are 1:1? I think you can have multiple services select the same workload entry?

**Comment by howardjohn** [comment]
cc @yskopets

**Comment by yskopets** [comment]
@zoltanmms Thank you for providing the feedback!

It's really helpful to understand what are the pain points for the users.

**Comment by yskopets** [comment]
@bianpengyuan The 1:1 relationship between `WorkloadEntry` and VM is a constraint of the current implementation rather than constraint of the `WorkloadEntry` API.

If I understand @zoltanmms correctly, there are multiple applications collocated on the same VM.

Each application has to be represented by a separate `WorkloadEntry` (because they have different sets of labels), but `WorkloadEntry.Address` has to be the same.

It is an implementation detail that Istio was using `ip -> WorkloadEntry` mappings internally. Because if this, only 1 `WorkloadEntry` for a given IP address was taken into account and others ignored.

Last week we solved this problem in `serviceregistry/kube` (see #37129).

And I will be working on `serviceregistry/serviceentry` next.
