### ISSUE TITLE
_anonymous_match_nothing_

### ISSUE THREAD

**Issue by jonassteinberg1** [istio/istio#37364]
### Bug Description

I have two authorization policies.  One is:

```
# wide open
spec:
  rules:
  - {}
```

and the other is actually useful.  When I `istioctl x authz check $POD` _before_ removing the (erroneous) wide open policy istioctl returns:

```
wide-open-policy
policy-that-is-supposed-to-be-here
```

When I remove the wide open policy `istioctl x authz check $POD` istioctl returns:

```
ACTION   AuthorizationPolicy                    RULES
ALLOW    _anonymous_match_nothing_              1
ALLOW    policy-that-is-supposed-to-be-here   1
```

What is the significance of `anonymous_match_nothing`?  Is it saying something equivalent to DENY ALL or is it saying "I'm just here, but I'm not mitigating anything" effectively doing nothing?

And why isn't this documented anywhere?  I see it in source code, but it is quite confusing.

Thanks!

### Version

```prose
client version: 1.11.3
control plane version: 1.7.2
data plane version: 1.7.2 (59 proxies)
```
```


### Additional Information

_No response_

**Comment by howardjohn** [comment]
I think its basically a bug in `istioctl`. If there is empty rule, we end up sending envoy something like `{}`. If there is a rule we have `{name: foo, rule: blah}`. So istioctl no longer has access to the original name

**Comment by howardjohn** [comment]
cc @yangminzhu

**Comment by yangminzhu** [comment]
The `_anonymous_match_nothing_` is referring to the rbac config without any rules that effectively reject all requests ("allow nothing"). This is a result of having authorization HTTP policies on TCP filter chains because the TCP filter chain cannot support HTTP attributes, hence we fallback to generate an empty rule to deny all traffic.

This could be improved to generate a more explicit deny-all rule in this case so that it can have a proper name.

**Comment by jonassteinberg1** [comment]
@yangminzhu the RBAC config I posted above has _an empty rule_ and this signifies ALLOW ALL according to my understanding?

**Comment by yangminzhu** [comment]
> And here's the istioctl output after I remove the first which shouldn't be there:
ACTION   AuthorizationPolicy                    RULES
ALLOW    _anonymous_match_nothing_              1
ALLOW    app.app-services    1

This is because you only have 1 policy after you removed the first one, and the second one includes HTTP fields (e.g. methods, paths) that cannot be applied to TCP filter chains, the `_anonymous_match_nothing_` is only generated on the TCP filter chain to enforce the ALLOW action (deny by default).

When you have the first allow-all policy, it can be generated for both TCP and HTTP filter chain so that we do not need to generate the _anonymous_match_nothing_ anymore.

**Comment by jonassteinberg1** [comment]
@yangminzhu Mmkay.  That's a fairly nuanced context, thank you for supplying insight there.  In my defense: I actually read about precisely what you're describing in this istio forum post [here](https://discuss.istio.io/t/correct-way-to-require-a-jwt-to-access-a-workload-from-ingress/8728), but the gist of the post was that actually the _enforcing_ HTTP fields being used in TCP filter chains isn't actually on, i.e. this isn't really enforced.  So I guess _it is_?  Does this mean then that any blocks from my auth pol above that have these HTTP methods on TCP filter chains aren't working?
