### ISSUE TITLE
extend `/debug/config_dump`

### ISSUE THREAD

**Issue by zirain** [istio/istio#37504]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

extend `/debug/config_dump` support all config generated by istio

**Describe alternatives you've considered**

`/deug/config_dump` can dump `bootstarp` `clusters` `listeners` `scoped_routes` `routes` `secrets`, same as envoy does

should we dump `nds` `ecds` and other xDS together?

@howardjohn @costinm WDYT?

**Comment by howardjohn** [comment]
I would keep config_dump mirroring Envoy by default. Then add a query param `types=xyz`, that can take arbitrary params which are passed to `s.Generators[xyz]`. For convenience we can allow short names (eg `nds`) for known types (reverse of `GetShortType`). Can allow multiple like `types=nds,ecds`

That should give us basically anything we could ever want and is future proof. We will need some special logic possibly for some types (redact secrets?) but otherwise should work out

**Comment by zirain** [comment]
> That should give us basically anything we could ever want and is future proof. We will need some special logic possibly for some types (redact secrets?) but otherwise should work out

I'm not sure what's the special logic, can you share more details?

**Comment by costinm** [comment]
Special logic would be to filter out some data.

Agree, we can extend via query param.

**Comment by zirain** [comment]
fixed by https://github.com/istio/istio/pull/41109
