### ISSUE TITLE
Revert 128-bit trace-id header

### ISSUE THREAD

**Issue by sta-szek** [istio/istio#37517]
**Describe the feature request**
I would like to have it configurable: https://github.com/istio/istio/issues/10732
So we can switch back to 64-bit tracing.
In our case 128-bit is not supported by all components and we have issue that traces are not stored properly.

Can we make it configurable?

Also, what was motivation for @objectiser "Agree we should switch to 128bit."  (https://github.com/istio/istio/issues/10732#issuecomment-451391219)
Do I understand properly that you changed it everywhere just because of some GCP does not support 64-bit?

**Comment by bianpengyuan** [comment]
We made the switch not only because of gcp, but all major tracing provider started to support 128 bit back then, I think that's why @objectiser (who did not work for google and was a core contributor to many tracing systems) agreed to make the switch.

To make it 64 bit, you can use https://github.com/istio/istio/tree/master/samples/custom-bootstrap to override the default config.

**Comment by sta-szek** [comment]
cool, i didnt know the custom boostrap feature! it will be good enough for us!
thanks!

**Comment by bianpengyuan** [comment]
Closing since this is answered. Thanks!
