### ISSUE TITLE
External istiod installation overriding local injector webhook

### ISSUE THREAD

**Issue by frankbu** [istio/istio#37674]
### Bug Description

The [external control plane installation instructions](https://istio.io/latest/docs/setup/install/external-controlplane/) start by installing Istio on the external control plane cluster using the default profile. This istiod will be used to control an ingress gateway that will provide access to the (yet to be installed) external control plane. After [this installation step](https://istio.io/latest/docs/setup/install/external-controlplane/#set-up-a-gateway-in-the-external-cluster) there are two mutatingwebhookconfigurations on the external cluster:

1.  `istio-revision-tag-default`
2. `istio-sidecar-injector` (this one seems to be disabled with `istio.io/deactivated: never-match` ???)

Injection is working fine using the `istio-revision-tag-default` webhook at this point.

Later in the instructions we [install istiod again](https://istio.io/latest/docs/setup/install/external-controlplane/#set-up-the-control-plane-in-the-external-cluster) on the same cluster, but in a different namespace, `external-istiod`. This istiod is the external control plane that is configured with remote keys to manage a remote config cluster. The IOP for this install includes `operatorManageWebhooks: true` because it is not supposed to manage local webhooks.

However, as of Istio 1.12, the second install seems to be creating a new webhook on the local configuration, `istio-revision-tag-default-external-istiod` and also seems to be deleting the correct local webhook, `istio-revision-tag-default`.
At this point injection is broken on the local cluster, because it's pointing to the wrong istiod.

It seems that there is code that is doing all this management that should not be if `operatorManageWebhooks: true`?
https://github.com/istio/istio/blob/393f88cd255f1c0caea6fac5d21aaf0d3e412aad/operator/cmd/mesh/install.go#L195

### Version

```prose
1.12+
```

**Comment by howardjohn** [comment]
cc @Monkeyanator

**Comment by frankbu** [comment]
Note that this is only broken if the external control plane is installed using `istioctl install ...`. A workaround is to use `istioctl manifest generate ... | kubectl apply`.

**Comment by Monkeyanator** [comment]
What breaks here is that we're doing two separate non-revisioned Istio installations in the same cluster. The code doing the default tag management does not take this into account.

To give some background, the code doing default tag management does something like:

1. Check if there's a previous Istio installation (checks for mutating webhook with `app=sidecar-injector`)
2. Assume that if the installation has revision `""` that **the revision should be made the default revision**. This will remove other webhooks with `istio.io/tag=default`
3. If there's no previous installation or our revision is "" make this revision the default
4. When generating the default tag, if there are other webhooks with `istio.io/rev=default` we must **deactivate them** so we don't get duplicate selectors (hence the awful `istio.io/deactived: never-match` hack). We can't remove them because then the user then couldn't move the tag back to that revision (webhook is the only place we keep information about injection URL)

Altogether I think that explains what's causing the issue. Some immediate thoughts:

1. Yes we should respect `operatorManageWebhooks` during the installation and not do the management if set. I'll open a PR for this
1. The installation logic here is gross and we should look at improving

cc @costinm on the part about supporting multiple `istiod` installations with the same revision in different namespaces.

**Comment by frankbu** [comment]
no stale

**Comment by natehouk** [comment]
I have this exact problem, injection is not working because I have two webhooks:

```
$ kubectl get mutatingwebhookconfiguration istio-sidecar-injector -o yaml | grep "namespaceSelector:" -A5
  namespaceSelector:
    matchLabels:
      istio.io/deactivated: never-match
  objectSelector:
    matchLabels:
      istio.io/deactivated: never-match
--
  namespaceSelector:
    matchLabels:
      istio.io/deactivated: never-match
  objectSelector:
    matchLabels:
      istio.io/deactivated: never-match
--
  namespaceSelector:
    matchLabels:
      istio.io/deactivated: never-match
  objectSelector:
    matchLabels:
      istio.io/deactivated: never-match
--
  namespaceSelector:
    matchLabels:
      istio.io/deactivated: never-match
  objectSelector:
    matchLabels:
      istio.io/deactivated: never-match
$ kubectl get mutatingwebhookconfiguration
NAME                         WEBHOOKS   AGE
cert-manager-webhook         1          6d11h
istio-revision-tag-default   4          21s
istio-sidecar-injector       4          33s
$ kubectl get mutatingwebhookconfiguration istio-revision-tag-default -o yaml | grep "namespaceSelector:" -A5
  namespaceSelector:
    matchExpressions:
    - key: istio.io/rev
      operator: In
      values:
      - default
--
  namespaceSelector:
    matchExpressions:
    - key: istio.io/rev
      operator: DoesNotExist
    - key: istio-injection
      operator: DoesNotExist
--
  namespaceSelector:
    matchExpressions:
    - key: istio-injection
      operator: In
      values:
      - enabled
--
  namespaceSelector:
    matchExpressions:
    - key: istio-injection
      operator: DoesNotExist
    - key: istio.io/rev
      operator: DoesNotExist
$
```

How do I fix this? I have tried doing a istio uninstall --purge and reinstalling, but we end up with just the same situation.

**Comment by natehouk** [comment]
I fixed it by deleting the default revision and reinstalling with a tagged revision.

**Comment by howardjohn** [comment]
2 webhooks is expected, the first one never applies

**Comment by adamSplendex** [comment]
This is still occuring with 1.17 

So we do not have sidecar-injector as a service / pod - only a webhook? 
` 
kubectl get svc --namespace=istio-system | grep sidecar-injector
`

**Comment by iamshreeram** [comment]
This issue still happening in version 1.22. Any updates on when it will be fixed? 

@natehouk , could you kindly explain how you addressed this issue?

**Comment by natehouk** [comment]
I don't recall anything more than what I wrote above:

> I fixed it by deleting the default revision and reinstalling with a tagged revision.
