### ISSUE TITLE
Jwksuri cannot be refreshed in real time

### ISSUE THREAD

**Issue by biutefo** [istio/istio#37710]
Hello，dev！
I want to know how istio's jwtrule works.
spec:
  selector:
    matchLabels:
      app: httpbin
  jwtRules:
  - issuer: "testing@secure.istio.io"
    jwksUri: "https://raw.githubusercontent.com/istio/istio/release-1.13/security/tools/jwt/samples/jwks.json"
The results I configured in jwksuri can be changed dynamically. When I modify the database value to change the interface return value, the istio runtime configuration does not refresh dynamically.

Question: does jwksuri have a cache? What is the caching strategy?
Feature:Every time when use JWk, istio will pull the latest jwks from jwksuri again.

**Comment by rsalmond** [comment]
> Question: does jwksuri have a cache?
Yes it does.

> What is the caching strategy?

Cache duration is configured by env var `PILOT_JWT_PUB_KEY_REFRESH_INTERVAL` and defaults to 20 mins. docs: https://istio.io/latest/docs/reference/commands/pilot-agent/

**Comment by Stono** [comment]
Just throwing it out there that I got hit by this today due to an incident where we accidentally deleted a realm in keycloak.

We were able to recover the realm very fast but new keys were issued, which then left us stumped.

We went digging into the envoy config and found the old keys in there.

Would be nice to have some way to at least force update these on demand?
