### ISSUE TITLE
Cluster names for alpha 2 should be based on Endpoint subset name

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#3782]
Currently cluster names are generated based on service name + concatenation of labels piped with the protocol. We must change the cluster name to be _proto.EndpointSubsetName.ServiceName, in a DNS format.

The Endpoint Subset name is configured by the user in the Destination Rule:
https://github.com/istio/api/blob/master/routing/v1alpha2/destination_rule.proto#L147

Later, Envoy could be configured to fall back on DNS.

**Comment by costinm** [comment]
Tentative target for 0.8 - conditional on dropping alpha1 in 0.8, otherwise 0.9

**Comment by baodongli** [comment]
Trying to understand the issue before changing anything. A couple of questions:
- why MUST it be using a DNS format? Looking at [Envoy Cluster](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/cds.proto#), there is no such requirement.
- "Later, Envoy could be configured to fall back on DNS", how is this **fallback on DNS** related to the cluster name being DNS format? And how the fallback could be configured? I saw [envoy subset fallback policy](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/cds.proto#envoy-api-enum-cluster-lbsubsetconfig-lbsubsetfallbackpolicy). Not sure if the issue is related to that.

thanks.

**Comment by ZackButcher** [comment]
It's not required that cluster names be DNS friendly, it just makes things read more naturally for the operator: a route refers to cluster `"my-subset.my-service-name"` rather than `"my-service-name|label1=foo,label2=bar,label3=baz"`. In the current case, the operator has to look up the destination rule to see that subset `my-subset` is defined as `my-service-name` with exactly the labels `label1: foo`, `label2: bar`, `label3: baz`.

DNS based fallback should be a separate issue, it's not inherently related to subset cluster naming.

**Comment by baodongli** [comment]
That makes sense. 

The code for cluster creation and naming is the same between alpha1 and alpha2 (or now networking/alpha3). I'd like to confirm that this naming change should be restricted to alpha2 onwards as the issue title suggests, and alpha1's naming should remain the same.

**Comment by baodongli** [comment]
After looking at the code a bit closely, and seeing new PRs (slated to support alpha2, or rather now alpha3, and envoy v2) that use various parts of the cluster name to search service registries, I think it doesn't seem to be possible to make this naming change now. In this [Followup on EDS](https://github.com/istio/istio/pull/4036/files#diff-6713acfe7b9e389e7dcd429d08bee859R167), hostnames, ports and labels extracted from the cluster name are used to search for service instances in the service registries. An subset name may not be used as part of the cluster name unless the system also stores service/subset information that can be used to get labels pertaining to the service/subnet name. Or, EDS has been prebuilt and the cluster name is simply a key to locate and return the record.

Let me know if you think otherwise.

**Comment by kyessenov** [comment]
Richard, the dynamic lookup table from (service FQDN, subset name) to labels is a new requirement for v1alpha3 config. Technically, we could use subset name as the cluster name, but IMHO it's a not a technically sound solution, since Envoy's subset LB can already perform label subsetting. I suggest we stick with custom names for now (out.<service>.<port>.<labels>) until we can switch over to subset LB after v2 lands. Introducing a third way (<subset>.<service>) is not a step in the right direction.

**Comment by baodongli** [comment]
@kyessenov This is Robert (or Baodong). Yes, I think that it makes sense to use the envoy LB subsetting that can simplify pilot a little bit in terms of cluster processing and in the same time get rid of a certain amount of traffic between sidecars and Pilot.

**Comment by kyessenov** [comment]
Apologies @baodongli , we've never met in person.

**Comment by baodongli** [comment]
@kyessenov No Problem.

**Comment by rshriram** [comment]
Solved by #4411
