### ISSUE TITLE
annotation are no more working after upgradation istio from v1.4 to v1.11

### ISSUE THREAD

**Issue by sudmis** [istio/istio#37831]
### Bug Description

  below  annotation are no more working after upgradation istio from v1.4 to v1.11

                  sidecar.istio.io/proxyInitCPULimit: 
                      sidecar.istio.io/proxyInitMemoryLimit: 

### Version

```prose
Istio version - v1.11.2


Client Version: v1.21.2
Server Version: v1.21.2

helm version - v3.2.4+g0ad800e
```

**Comment by howardjohn** [comment]
Why do you want to configure these?

**Comment by howardjohn** [comment]
At some point it was decided that it doesn't make sense to have different config for the init container and the sidecar so curious what the use case is

**Comment by mmazurek-msft** [comment]
In case of exclusive cpu assignment it doesn't make much sense to assign e.g. 2 vCPUs to the work which is to be done by the init container. Also when using exclusive CPUs we've already seen problems where CPUs allocated to init container were freed incorrectly while still being used by other containers.  Therefore it makes quite a lot of sense to have separate settings for both init and istio containers.

**Comment by sudmis** [comment]
@howardjohn thanks for your response. Recently we have upgraded istio from 1.4 to 1.11. We used to have different limit configuration for init-container and proxy, which we configured using annotation. 

Can you please let me know the release since when this change has happened? 
And is there still an option to configure cpu and memory limits for istio-validation container?

**Comment by howardjohn** [comment]
init container never runs concurrently with the app containers so the scheduler chose the max of them - not the sum.

If there is a bug in that it's unfortunate but should be fixed in k8s.. there isn't any first class apis to configure this in Istio today short of directly modifying the injection template

**Comment by howardjohn** [comment]
the reason we did it is because init container with low limit was taking
10s of seconds to run when it normally runs almost instantly. when the init
container runs the scheduler has already reserver resources for the main
containers, so why artificial limit the init container? if we already
reserver a cpu might as well use it.

I am still not sure I understand a concrete use case. You are free to fork
off the chart and make any changes you like for your own uses,but to add a
first class API we would need to understand a bit more concretely
