### ISSUE TITLE
mention need for -c flag in istioctl

### ISSUE THREAD

**Issue by rshriram** [istio/istio#38]
When using istioctl against a cluster that is not minikube, the user has to specify the -c flag or set the KUBECONFIG environment variable (support for this needs to be added - see https://github.com/istio/manager/issues/308). Otherwise, istioctl hangs indefinitely.

**Comment by esnible** [comment]
The hanging indefinitely might be a bug.  It has been bothering me.  The cause is _istio/manager/platform/kube/client.go_:203 trying to contact https://<host>:8443/apis/istio.io/v1alpha1/istioconfigs and getting "network is unreachable" and silently retrying.  We should probably report an error every 10 attempts or time out if we don't think the configuration is correct.  However, the bug should not be opened here, but in _istio/manager_.

**Comment by frankbu** [comment]
If I'm not mistaken, this issue is just about the doc. In bookinfo.md, we need to add a setup section that mentions the need to configure istioctl's kubeconfig, if necessary.

**Comment by davetropeano** [comment]
I am using an armada cluster and `KUBECONFIG` is defined (you can't use `kubectl` without it), but `istioctl` still needs the `-c` flag defined otherwise there is a hang. So specifically,

`istioctl list route-rule -c $KUBECONFIG` works
`istioctl list route-rule` hangs even though `$KUBECONFIG` is defined

**Comment by esnible** [comment]
@davetropeano Are you sure you have the latest istioctl and that you have `export`ed KUBECONFIG?

Even with Minikube, I am never sure if I will get a server a 192.168.99.100, .101, or .102.  In testing locally with builds I did myself I can see the behavior you describe if KUBECONFIG has been set but not exported.  But if I export it the behavior is as expected.

(It is likely that similar problems might happen if $KUBECONFIG contains whitespace in addition to a filename.)

**Comment by davetropeano** [comment]
@esnible 100% sure that I have a KUBECONFIG environment variable... using armada there is no way to NOT have the env variable defined and use `kubectl`. 

As for whether I have the latest `istioctl`... I have the binary that comes from the main branch when you clone `istio/istio` which is likely not the latest.

**Comment by esnible** [comment]
That is going to be old.  Can you run `go build` to create a recent binary?  You will need Go 1.8 as of today.

**Comment by rshriram** [comment]
Fixed with new istioctl binary
