### ISSUE TITLE
static IP for Gateway (GKE)

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#3800]
Annotation

    kubernetes.io/ingress.global-static-ip-name: fortio-prod-ip

doesn't work, maybe because our ingress doesn't run as a NodePort

https://cloud.google.com/kubernetes-engine/docs/tutorials/configuring-domain-name-static-ip#step_2b_using_an_ingress

in general we should find a way to keep the ingress IP in sync with the DNS entry for the domain

**Comment by ldemailly** [comment]
similar to #1024

**Comment by andraxylia** [comment]
We should add this to Gateway, similar to what Ingress has:
https://github.com/kelseyhightower/ingress-with-static-ip

**Comment by ostromart** [comment]
Per our chat, it is possible to set the load balancer IP in a LoadBalancer service (search for loadBalancerIP on https://kubernetes.io/docs/concepts/services-networking/service/).
This can be set to a regional static IP but not global static IP - this is limited in Arcus and there's no plan to support global. 
The missing part is that you have to use the actual IP address instead of a nice label like you can with an Ingress (kubernetes.io/ingress.global-static-ip-name: my-static-ip).

**Comment by volatilemolotov** [comment]
@ostromart is there a reason not to support Global ip from GCE, it makes sense for some deployments.

**Comment by volatilemolotov** [comment]
Yes that explains it, forgot that global are L7. 

Thanks for clarifing that

**Comment by howardjohn** [comment]
This is supported with helm options mentioned above

**Comment by ArgTang** [comment]
@howardjohn since helm is deprecated, it would be good to bring this up again

**Comment by steveoh** [comment]
I am having a hard time using a static ip. Has this been sorted out since it was last discussed?
