### ISSUE TITLE
Automating sidecar-injector certificate generation 

### ISSUE THREAD

**Issue by costinm** [istio/istio#3821]
The webhook injector needs a keypair and a certificate. We now use a shell script, but it doesn't work
well with helm and doesn't have good UX.

One option would be to automate the keypair and cert request - istio-ca seems to be the best place to
put this feature, since it already has code for this. The main trick is to make the k8s request for signing,
and add whatever RBAC permissions are needed to approve.

As a side benefit, the code can be used for other use cases where we need a k8s certificate.

Alternative is to place it in istioctl, and create a separate service to generate the k8s cert and run it 
from helm (or single-click installers, k8s addon and other cases where automated install is needed)

**Comment by ayj** [comment]
The shell scripts generates a key/cert, creates a k8s CSR and posts it to api-server, approves the CSR (requires admin), waits for certificate controller to create the signed cert, and creates the corresponding k8s secret that is consumed by the webhook. It's not clear which of these steps (all of them?) you'd like to change/enhance. Changing key/cert gen step alone doesn't seem like it'd have a big impact on better UX 
for this workflow.

**Comment by ayj** [comment]
@costinm, can you clarify what enhancements you'd like to see re: UX?

**Comment by yusuoh** [comment]
cc @yusuoh

**Comment by yusuoh** [comment]
I think we'd better do all those steps in CA. It will simplify the installation. cc @ostromart

**Comment by ayj** [comment]
The CA shouldn't be responsible for generating webhook configuration files, e.g. which namespace an admission controller applies to, fail open/close policy, resources subject to injection.

**Comment by wattli** [comment]
+1 for what @ayj says, CA stands for Cert Authority, and should only be used for cert/key related stuff. Why can't we just use some scripts to do this work?

**Comment by yusuoh** [comment]
@ayj I meant all those steps mentioned in your previous comment, i.e. secrets generation and signing. Agree that it should not touch the webhook configuration part.

**Comment by costinm** [comment]
The config is separate from the cert. 

The goal is to be able to automate the installation of istio - with helm or 'single click' or pre-installed with kubernetes. There is no user running extra scripts here - they use 
'kubeadmin ... --addons istio' or helm install istio - and expect it to work.

Helm and single click have some 'one time' jobs to do additional initialization steps, we can do the same here. But it needs to be something that can be run in the cluster and fully automated.

I think CA is the right place because it fits with what CA does - generates certificates. I would
avoid granting secret write permissions to other istio components, and we are only talking 
about cert generation here.

**Comment by Stono** [comment]
Hey folks, 
If the goal here is UX, from a helm chart perspective perhaps having something like `.values.webhookEnabled: true`, which in turn creates the sidecar deployment, with a [pre-install hook](https://github.com/kubernetes/helm/blob/master/docs/charts_hooks.md) to do the cert gen + secret setup perhaps?

**Comment by yusuoh** [comment]
We'd better have a general solution that does not depend on Helm.

**Comment by ayj** [comment]
The [pre-install hook](https://github.com/kubernetes/helm/blob/master/docs/charts_hooks.md) looks like a great option for `tiller` based helm installs. We also need a non-tiller solution. 

One solution is to add cert/key gen and CSR signing/approval into istioctl, either as part of `gen-deploy` or a separate subcommand, and output the resulting webhook secret and registration yaml with the rest of the Istio yaml files. The admin could tweak the install files, if necessary, before install or simply `kubectl apply` the output. Depending on Istio CA in this workflow mixes deployment and installation artifact creation, e.g. we need to deploy Istio CA before we generate webhook install files. Using k8s CA avoids this problem.

**Comment by costinm** [comment]
Agreed, the solution should not depend on helm - but it can't depend on
scripts run manually
 by the user either. Given how 'one-click' is implemented, I think the best
option is to have the
 code that generates the cert moved to a container - either part of Istio
CA, or a separate
'one time' - like we seem to do with mixer setup.

It should work for helm, one-click-type installs as well as the k8s addon.

IMHO the Istio CA is the best bet since it can also deal with any renewal,
and is the place
where we generate certs. Having ability to generate K8S-signed certs for
istio - and possibly
for apps - is an extra bonus for future. I believe we discussed long time
ago that it would
be nice to be able to generate Istio certs signed by K8S, without storing
istio-CA private
keys in a secret ( k8s certs are not visible as secrets ).

**Comment by yusuoh** [comment]
I can help on this one, as I plan to convert the script into some Go library for e2e test. Once we have the lib, we can call it from CA or other places.

**Comment by costinm** [comment]
Great, thanks - I believe pilot tests already have some go code for this,
so maybe just move it to the
pkg directory ? Istioctl can also use this.

**Comment by yusuoh** [comment]
Sgtm. I will take a look.

**Comment by yusuoh** [comment]
I noticed that in the e2e test, we used a self-signed CA for webhook.
https://github.com/istio/istio/blob/master/tests/e2e/tests/pilot/util/environment.go#L693

So maybe we can simply reuse Istio CA to sign the cert and generate TLS config instead of using K8S's one which involves manual intervention?

**Comment by costinm** [comment]
If Istio CA can be used - of course we should use it, it handles cert
rotations and is much simpler to setup.

It seems the remaining problem will be creating the webhook resource with
the istioCA certificate hooked in.

**Comment by yusuoh** [comment]
K8S API server export its CA bundle to some configmap. Maybe we should do the same thing with Istio CA.

**Comment by wattli** [comment]
Currently istio CA's root is in K8s secret, which is some info you can get as well

**Comment by yusuoh** [comment]
So I tested the self-signed CA with sidecar-injector and it works well. I think we need to add the following logic:
1. Istio CA generates and maintains certificate for webhooks and store them as secrets.
2. The webhook service watches the secret and update the TLS configuration on its server side. It also updates the K8S webhook config and fill in the Istio CA cert.

By doing that, we can remove the scripts and make the installation automatic. @ayj Please let me know whether it makes sense.

**Comment by ayj** [comment]
> Istio CA generates and maintains certificate for webhooks and store them as secrets.

How is this configured? Do we need to pass some flags to Istio CA to tell it what certs need to be generated (service and namespace) and where they need to be stored?

> The webhook service watches the secret and update the TLS configuration on its server side. It also updates the K8S webhook config and fill in the Istio CA cert.

Who is responsible for creating the initial webhook registration?

**Comment by yusuoh** [comment]
Yes. The information about each webhook needs be passed to Istio CA through flags. Those are basically the argument of the current cert generation script (service, namespace, secret name).

The webhook service itself should be responsible for self-registering. I think it is the same approach with what pilot validation webhook is doing now.

**Comment by JoelSpeed** [comment]
I don't know if this is helpful or not or even applicable here, but, I've been building a Mutating Webhook recently and am facing the same issue of bootstrapping the certificates and the webhook CA Bundle Patching.

I decided to use the K8s CSR Api and have built a tool that I now deploy as a job in cluster alongside my webhook as I initially install it, https://github.com/JoelSpeed/webhook-certificate-generator

The tool has an auto approve option (with the relevant RBAC rules) that allows a zero touch installation, you can also provide the name of a webhook to patch. Since a cluster admin would have to deploy this tool anyway, they can just ensure that the service account token is secure and then there's no risk of privilege escalation. I appreciate some people may still be hesitant with this approach though.

The Kubernetes CSRs expire after about an hour, so for renewing the certificates, you can just run the script again, generate a new CSR and auto-approve again. It could be a K8s cronjob running once a week or so.

I just wanted to reply to what @yusuoh said about certificate approval, the auto-approval of CSRs for `kubelet`s looks to work in the same way `kubectl` does. `kubelet` seems to do a subjectaccessreview to check if it is allowed to approve it's CSR then patches the CSR if it is. I don't think doing the same would be hijacking the process.

**Comment by yusuoh** [comment]
@JoelSpeed Thanks for sharing your work. I think you are right about the CSR approval. It is mainly about promoting the privileges of the job to have the write permission to the CSR. There was some k8s doc that mentioned kubectl modifies the CSR status directly but I guess they might have changed the implementation. 

I am curious how you handle the cert rotation. I mean even if we can periodically renew the cert and patch the webhook config, we still need some logic in the server side to use thew certificate in its TLS settings. Or maybe you probably simply restart the webhook service to reload the cert?

**Comment by ayj** [comment]
Thanks for the info @JoelSpeed - it's quite helpful! Have you seen any issues yet with including an empty `caBundle` in the registration? I would have expected that to fail, but that doesn't seem to be the case.

> renew the cert and patch the webhook config

We only need to patch the webhook registration if the CA itself is renewed. For cert rotation, only the webhook needs to (re)load the latest key/cert and update tls server settings.

**Comment by JoelSpeed** [comment]
@yusuoh I don't think they've changed the way it works, I think that's just how it works everywhere, sending a patch with the new status.

Cert rotation hasn't been a huge concern for me at the moment, still in the POC stage. My plan was to run the certificate generator process periodically to ensure that the certificate is renewed regularly (changing the job in my repo to a cronjob). Reloading the certificates is harder, I don't know if the api machinery I'm building watches the TLS cert for changes, but that seems like a reasonable thing for it to do.

@ayj The only problem I've had was mistakenly overwriting the `mutatingwebhookconfiguration` after the patching job had run. I had to re-run the job. (Although I'll admit I was expecting the 3 way-merge of `kubectl` to ignore the changed field)

My webhook affects deployments and configmaps as they're created so if this were to ever happen, someone would notice when they try to update their config. I see that being a much bigger problem for the sidecar injector since it injects straight into Pods on create right? That would stop new pods from starting so maybe this isn't suitable for the sidecar-injector right now?

**Comment by sdake** [comment]
Should we wait on this work to merge https://github.com/istio/istio/pull/3935 or merge 3935 and revert later?

Cheers
-steve
