### ISSUE TITLE
Global OutlierDetection setting

### ISSUE THREAD

**Issue by davtex** [istio/istio#38242]
**Describe the feature request**
I would like to be able to be  able to define OutlierDetection in global mesh config, same way as I can configure localityLBSetting.

I have a multi-network multicluster in place and I would like to run it in active-standby mode, primarily to cut down extra latency caused by going cross-cluster. This is achievable by enabling localityLBSetting and properly configuring topology labels. For some (I imagine good) reason localityLB does not work without OutlierDetection configured. Now the problem is that AFAIK this can only be done by configuring individual DestinationRule for every single service in the cluster. Problem is that I think this is counter-intuitive and it can be easily forgotten e.g. when introducing new service by someone that is not that familiar with Istio. This can be a problem especially when application are stateful or there is a DB replication lag between locations. Problem caused by such situation (6 services with working localityLB, 1 without working localityLB) can be difficult to troubleshoot.

**Describe alternatives you've considered**
1. Alternative would be allowing localityLB even without outlier detection and rely on readiness probes only
2. Alternative would be somehow configuring OutlierDetection on namespace level (via DestinationRule/Sidecar)

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[x] Multi Cluster
[ ] Virtual Machine
[x] Multi Control Plane

**Additional context**

**Comment by GregHanson** [comment]
@davtex there is a design doc out for moving TrafficPolicy to MeshConfig [here](https://docs.google.com/document/d/1TkIiovpPLwd-JQ_zKA1Fhy5MVGW3dQKtNwOlFTCKb_Y/edit#)

**Comment by hzxuzhonghu** [comment]
cc @istio/wg-environments-maintainers 
Personally, I do not like to use meshconfiguration to hold all global configurations. It is not a user-friendly API and now it contains everything.  It should be treated as an install option, however now we wrongly use it as a declarative API.  

Come back to the issue, could we define a global DR, not sure if we are lack of dr merging of outlier detection.

**Comment by GregHanson** [comment]
@hzxuzhonghu the merging logic exists today and is behind a feature flag currently ([PR #30066](https://github.com/istio/istio/pull/30066)). The design doc I linked to above discusses some pros and cons of both MeshConfig and DestinationRule implementations.  

- MeshConfig already stores client configurations settings (DefaultHttpRetry) since a global VirtualService does not work with the current spec. MeshConfig also already has ConnectTimeout, TcpKeepalive, and LocalityLbSettings - > which are DestinationRule.TrafficPolicy settings already
- with a global DestinationRule, we would ideally add the default global rule to our install charts so one is created by default so users are aware of what default values we are using (rather than hardcoding defaults like what is done for [circuit breaking](https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/v1alpha3/cluster.go#L58) currently).  Now user have to look at MeshConfig and a DestinationRule object in order to see default client settings.
- To my knowledge, global DestinationRule was never intended to support top level DestinationRule fields such as `hosts`, `exportTo` and `subsets` which I think would ultimately lead to bad user experience from users

**Comment by GregHanson** [comment]
after presenting the design doc for Global TrafficPolicy in MeshConfig to the Work Group call on 4/6 (agenda [here](https://docs.google.com/document/d/1wsa06GGiq1LEGwhkiPP0FKIZJqdAiue-VeBonWAzAyk/edit#heading=h.o8pz6aqnzzgk)) the proposed implementation will be re-written to conform with the Kubernetes Gateway API.  Design doc will be updated

**Comment by davtex** [comment]
Thanks for pointing out the feature flag, I used it and I was able to configure exactly what I wanted. Looking forward to how this will be handled in the future.
