### ISSUE TITLE
Make sure injector handles other non-Istio webhooks injecting init-containers

### ISSUE THREAD

**Issue by Monkeyanator** [istio/istio#38354]
### Bug Description

Imagine we have another mutating webhook configuration (not Istio) that injects an init-container into pod spec. If Istio injects first, and then the other non-Istio injector injects second, it's possible for our init-container not to be last, and therefore cause networking issues in later init-containers.

One solution is to force an ordering on the mutating webhook configurations. The dumb approach here: the ordering is supposed to be lexical (implementation detail, not API guarantee AFAIK) so we can prefix our webhooks with `zzz` or something (have not tested).

The "correct" approach should be to use `reinvocationPolicy` to make sure our webhook gets run again after the other injector places its init-container. This isn't guaranteed to work if the other webhook is attempting to make its our init-container last as well but it's better than the current state.

I don't think this should require changes to our injection logic based on https://github.com/istio/istio/blob/master/pkg/kube/inject/webhook.go#L598 but I'll need to confirm and we should add tests for this exact case if `reinvocationPolicy` is changed. How much confidence do we have that the injector is idempotent and can run multiple times without breaking?

### Version

```prose
General issue.
```

**Comment by howardjohn** [comment]
We have a test in pkg/kube/inject that asserts idempotency

**Comment by mjhoffman65** [comment]
Is there currently a way to set the `invocationPolicy` to `IfNeeded` on Istio's `MutatingWebhookConfiguration`?  Looking through the code, it looks like the `invocationPolicy` isn't configurable.

My use case is very similar to the original poster's.  I have an additional mutation webhook that injects an OPA container.  If this injection occurs after Istio, the readiness and liveness probes fail due to the Istio probe rewrite not picking up the injected OPA container's probes.  For example, the `ISTIO_KUBE_APP_PROBERS` environment variable is not set correctly.

I was able to work around this by prefixing the OPA `MutatingWebhookConfiguration` with a `00-`, but a better fix is to tell Istio to re-evaluate since I don't believe the lexical webhook ordering is guaranteed moving forward.
