### ISSUE TITLE
TestAuthorization_Audit does not check logs

### ISSUE THREAD

**Issue by nmittler** [istio/istio#38418]
### Bug Description

While working on https://github.com/istio/istio/pull/37914, it appears that the audit test doesn't really test the AUDIT function properly. To test auditing, the logs would have to be checked to confirm that a given request either was or was not logged.

### Version

```prose
master (head)
```

**Comment by yangminzhu** [comment]
See the comment: `TestAuthorization_Audit tests that the AUDIT action does not impact allowing or denying a request`, TestAuthorization_Audit explicitly does not cover the logging part.

The logging part is checked in the telemetry test: https://github.com/istio/istio/blob/1ade7ec2e569c2302d90a5f6b2bd86872e2314ad/tests/integration/telemetry/stackdriver/stackdriver_filter_audit_test.go.

**Comment by nmittler** [comment]
> See the comment: TestAuthorization_Audit tests that the AUDIT action does not impact allowing or denying a request, TestAuthorization_Audit explicitly does not cover the logging part.

@yangminzhu then the audit test serves no purpose AFAICT. Should it just be removed?

**Comment by yangminzhu** [comment]
No, the test is to check the audit action does NOT impact the allow/deny behavior, it applies different combinations of the audit action and makes sure it does NOT change the final access control decision.

**Comment by nmittler** [comment]
@yangminzhu a negative test is effectively useless. You might as well test that it also doesn't re-route traffic ... or pour you a cup of tea. Since you already are testing the audit function with telemetry tests (do you have a link, BTW?), I strongly suggest we get rid of this test since it's not actually testing the function it's supposed to be testing.

**Comment by yangminzhu** [comment]
@nmittler It is a negative test but I do not think it's useless. It covers corner cases when combining audit actions with other actions (allow/deny) with different workload selectors and paths. The test makes sure the AUDIT action won't negatively impact (break) the ALLOW/DENY actions.

This is important because the AUDIT and  ALLOW/DENY actions **shares a significant amount of common code path/state/logic** to generate the **Envoy config using the same RBAC filter**. A bug in the common code path for RBAC filter generation could cause very different behaviors, for example, An AUDIT action might cause the RBAC config to be generated in a way such that the ALLOW action to always allow (never denies). 

We do NOT need such negative tests for authorization policy and re-routing traffic because they do not share much common code path/state/logic in terms of the Envoy config generation (re-routing does not use RBAC filter at all).

Please see the telemetry test link in above comment, it tests a much simple case (there is only AUDIT action, no other actions) and checks the stackdriver log to verify the audit result.

**Comment by nmittler** [comment]
@yangminzhu understand ... however, do we have unit tests for this? This seems like the sort of thing better tested thoroughly by unit tests rather than an e2e test.

 > Please see the telemetry test link in above comment, it tests a much simple case (there is only AUDIT action, no other actions) and checks the stackdriver log to verify the audit result.

If that test is too simple to fully test AUDIT, should we just expand that one, rather than having 2 separate audit tests?

**Comment by nmittler** [comment]
Re-opening, since I don't think the central issue here is resolved.

**Comment by yangminzhu** [comment]
We do have unit tests but it is not enough, it does not cover the runtime behavior so we still need the real e2e tests.

The 2 tests are checking different aspects of the AUDIT action so they are not duplicate. We put one test in the telemetry test suite to reuse the common code and support for the stackdriver logging backend, and I think it's better to split the tests like this because the AUDIT feature supports different logging backend, stackdriver is just one example of supported backend.

The authz test suite checks the basic AUDIT feature is working and the extra telemetry test checks the logging part is working with the stackdriver backend. In the sure, if we support another logging backend, we can just add it as a new test in the telemetry test suite without duplicating the basic AUDIT feature test.

**Comment by nmittler** [comment]
@yangminzhu could you point me to the logic that is covered by these e2e tests but is not covered by either unit tests or the telemetry e2e tests?

**Comment by yangminzhu** [comment]
@nmittler 
it's for the end-to-end and runtime behavior coverage, make sure the config is distributed to Envoy correctly and the RBAC filter also enforces it correctly by sending real request.

Without the end-to-end and runtime coverage, we could convert almost all e2e tests to unit tests by just checking the Envoy generated config statically. The risk is even if we are generating the right Envoy config, it might not work due to a lot reasons (e.g. generated but not distributed correctly to Envoy or Envoy not enforcing it correctly).

**Comment by nmittler** [comment]
@yangminzhu just coming back to this ...

> We put one test in the telemetry test suite to reuse the common code and support for the stackdriver logging backend, and I think it's better to split the tests like this because the AUDIT feature supports different logging backend, stackdriver is just one example of supported backend.

Are you saying that telemetry only tests against SD today?

@douglas-reid do you have any insight into the current audit testing in the telemetry tests?

**Comment by douglas-reid** [comment]
@nmittler The current audit tests are SD-only, afaict. they involve setting a policy with three different audit rules and validating log entries are generated. The amount of shared stackdriver code is minimal, and looks to only use exported functions from the package.

e2e telemetry tests are funky, in that, ultimately, they are a testing a bunch of other features by their very nature -- so deciding what goes belongs within them is a bit of an art. However, it _feels_ difficult for me to separate `AUDIT` into a non-telemetry and a telemetry component. What is `AUDIT` if it doesn't generate an observable artifact?

I think we should probably refactor the Audit tests. I understand the idea behind the split. However, it would make sense, to me at least, to have them live alongside the security tests and have the audit behavior checked there -- especially if audit logs can go to more than just Google Cloud Logging. I guess that's because I'd rather not have the only test for the full Auditing behavior live in the `telemetry/` test hierarchy. 

The feature for the existing Audit telemetry test is currently: `observability.telemetry.stackdriver`. That _feels_ wrong because if something about Audit policy behavior is broken, it will only show up as "stackdriver" being broken.  The feature itself feels like it should be something like: `security.authorization.audit` -- with gcp cloud logging as the implementation detail of the test. If there are other exports (like `stderr`), it seems like those should be added as well.

**Comment by nmittler** [comment]
@douglas-reid 

> That feels wrong because if something about Audit policy behavior is broken, it will only show up as "stackdriver" being broken. The feature itself feels like it should be something like: security.authorization.audit -- with gcp cloud logging as the implementation detail of the test. If there are other exports (like stderr), it seems like those should be added as well.

+1 ... that sounds right to me. I had asked a while (years?) back to have a telemetry/logs abstraction so that tests could be written that were agnostic to the particular implementation. Is any/all of that abstraction in place? If not, maybe we should prioritize that work?

**Comment by yangminzhu** [comment]
> The feature for the existing Audit telemetry test is currently: observability.telemetry.stackdriver. That feels wrong because if something about Audit policy behavior is broken, it will only show up as "stackdriver" being broken.

yeah I think we can update the test name to be more accurate like `security.authorization.audit`.

@liwenhao0810 please take a look, I think one way is to move the [stackdriver_filter_audit_test.go](https://github.com/istio/istio/blob/1ade7ec2e569c2302d90a5f6b2bd86872e2314ad/tests/integration/telemetry/stackdriver/stackdriver_filter_audit_test.go) to the security folder and consolidate with the `TestAuthorization_Audit`.

**Comment by nmittler** [comment]
@yangminzhu +1 to merging the tests. Honestly I don't care where it lives, just so long as there's only one test that does everything.

@liwenhao0810 will you be working on this?

**Comment by liwenhao0810** [comment]
After looking at comments history, agreed with to merge and have the test in the security to fully test the functionalities.
I can take a look and see what I could help with on this.
