### ISSUE TITLE
IST0151 on default install

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#38676]
with a fresh install:
```
Warning [IST0151] (EnvoyFilter istio-system/stats-filter-1.11) This envoy filter does not have a priority and has a relative patch operation set which can cause the envoyFilter not to be applied. Using the INSERT_FIRST option or setting the priority may help in ensuring the envoyFilter is applied correctly
```

A freshly installed Istio with no customizations shouldn't have warnings

**Comment by howardjohn** [comment]
cc @AndreaM12345

**Comment by AndreaM12345** [comment]
hmm I think its because istio installs some envoyFilters by default that references the istio.stats.  

In the past use of relative patch operations seems to cause issues during upgrades (https://github.com/istio/istio/issues/37415)  

However understand it is confusing to users who didn't apply these envoyFilters to see these warnings.  

Wondering if I can add a priority to the default envoyFilters (istio-system/stats-filter-x.xx and istio-system/tcp-stats-filter-x.xx) of -1 which would ensure it gets processed before any envoyFilters that don't have a priority set 

Would that be an acceptable change?

**Comment by howardjohn** [comment]
I think setting priority is the right course of actions probably. No option on what it should be yet (-1,etc) - would have to think about it

**Comment by lei-tang** [comment]
@AndreaM12345 This issue is a blocking issue (https://github.com/orgs/istio/projects/6) for Istio 1.14 release. We plan to release Istio 1.14 on May 24. Do you have an ETA for resolving this issue?

**Comment by AndreaM12345** [comment]
will put up a PR for it tommorrow

**Comment by lei-tang** [comment]
@AndreaM12345 Thank you!
