### ISSUE TITLE
Istio-Gateway should support two certificates for the same domain (RSA & EC)

### ISSUE THREAD

**Issue by Crazyigor1987** [istio/istio#38946]
**Describe the feature request**
We have a requirement to run two certificates on our cloud environment with the same hostnames. One RSA and the other with the modern Eliptic Curve procedures.  The Istio ingress gateway should be able to load both certificates and decide through the client request which encryption method to use.

**Describe alternatives you've considered**
I have seen alternatives at Envoy in the form of DownStreamTLSContext. [As described here](https://github.com/envoyproxy/envoy/issues/1319). However, it would be desirable to control this via the gateway.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by shankgan** [comment]
Does envoy support discovery of multiple TLS certificates for the downstream TLS context via SDS - https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/base.proto#envoy-v3-api-msg-config-core-v3-datasource? Would be good to enumerate the advantages and reasons for this in an RFC in the team drive - https://groups.google.com/g/istio-team-drive-access, particularly since this requires some Istio SDS API refactoring to support it.

**Comment by dragondam** [comment]
@Crazyigor1987 Do you have any solution for that?

**Comment by Crazyigor1987** [comment]
@dragondam  
Nope. We agreed with our customer to use RSA Certificates for now. Sure hope that one day istio will support it.
