### ISSUE TITLE
install eastwest gateway error

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#39282]
### Bug Description

Events:
  Type     Reason     Age                 From               Message
  ----     ------     ----                ----               -------
  Normal   Scheduled  110s                default-scheduler  Successfully assigned istio-system/istio-eastwestgateway-7c6689f8b-lznc2 to 192.168.229.156
  Normal   Pulling    53s (x2 over 109s)  kubelet            Pulling image "auto"
  Warning  Failed     16s (x2 over 68s)   kubelet            Failed to pull image "auto": rpc error: code = Unknown desc = Error response from daemon: pull access denied for auto, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
  Warning  Failed     16s (x2 over 68s)   kubelet            Error: ErrImagePull
  Normal   BackOff    3s (x2 over 67s)    kubelet            Back-off pulling image "auto"
  Warning  Failed     3s (x2 over 67s)    kubelet            Error: ImagePullBackOff

/root/istio-1.13.3/samples/multicluster/gen-eastwest-gateway.sh --mesh mesh1 --cluster cluster3 --network network3 |  istioctl  install -y -f -

### Version

```prose
[root@localhost ~]# istioctl version
client version: 1.13.3
control plane version: 1.13.3
data plane version: 1.13.3 (8 proxies)

[root@localhost ~]# kubectl version --short
Client Version: v1.23.1
Server Version: v1.23.1
```

**Comment by litong01** [comment]
@13567436138 from the error, feels like that the injection failed, so that the generated manifest by installer uses image`auto` instead of the correct image name and tag. Normally this is due to the istio-ca-root-cert configmap not being placed in the right namespace, but the root cause of that could vary. it is a bit difficult to debug your case without knowing how the istio was installed. If you provide details on how you setup istio and in what kind environment such as if it is a single cluster or multiple cluster or even external control plane, it may be a bit easier to figure out the issue.
