### ISSUE TITLE
Download istioctl no longer works

### ISSUE THREAD

**Issue by linsun** [istio/istio#39301]
### Bug Description

```
curl -L https://istio.io/downloadIstioctl | sh -

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    95  100    95    0     0    928      0 --:--:-- --:--:-- --:--:--  1010
100  4622  100  4622    0     0  16327      0 --:--:-- --:--:-- --:--:-- 16327

 Downloading istioctl-1.14.0 from https://github.com/istio/istio/releases/download/1.14.0/istioctl-1.14.0-osx.tar.gz ...
istioctl-1.14.0-osx.tar.gz download complete!

Add the istioctl to your path with:
  export PATH=$PATH:$HOME/.istioctl/bin

Begin the Istio pre-installation check by running:
	 istioctl x precheck

Need more information? Visit https://istio.io/docs/reference/commands/istioctl/
 ~/istio-1.14-demo/ export PATH=$PATH:$HOME/.istioctl/bin
 ~/istio-1.14-demo/ istioctl version
client version: 1.13.3
control plane version: 1.14.0
```

Based on instruction from: https://istio.io/latest/docs/ops/diagnostic-tools/istioctl/#install-hahahugoshortcode-s2-hbhb

### Version

```prose
1.14.0
```

### Additional Information

n/a

**Comment by dhawton** [comment]
I wasn't able to reproduce this. If you run `~/.istioctl/bin/istioctl version` do you see the expected 1.14.0 version? What do you see if you run `which istioctl`?

**Comment by ericvn** [comment]
Lin,

I suspect that there is another version of istioctl in your PATH before this is run. We may be incorrectly adding istioctl after one already in the path using `export PATH=$PATH:$HOME/.istioctl/bin`.

If you do a `which istioctl`, I suspect you will see an instance of the executable that was already on your path. A `which -a istioctl` would list the one in the .istioctl directory, but it being further down the PATH order.

I think that changing the export to be `export PATH=$HOME/.istioctl/bin:$PATH` would fix the issue since the new istioctl will be first on the path.
