### ISSUE TITLE
WasmPlugin to scope to specific routes

### ISSUE THREAD

**Issue by ramaraochavali** [istio/istio#39345]
It seems WASMPlugin currently is not scoped to inbound/outbound or even a port. When we define a WASMPlugin with a workload selector, the WASM config is applied to all listeners both inbound and outbound.

Is there a way to control this and scope to specific routes/listeners?

**Comment by ramaraochavali** [comment]
@bianpengyuan any thoughts?

**Comment by zirain** [comment]
prefer to reuse match in `EnvoyFilter` cc @ingwonsong @douglas-reid

**Comment by ramaraochavali** [comment]
Yes. That is what I was thinking - we should reuse applicable matches in Envoy filter and do this.

**Comment by mathetake** [comment]
Also routes can be obtained via :path header so this could be implemented inside the Wasm plugin

**Comment by zirain** [comment]
`EnvoyFilter` selector route by `route_name`, but it's optional, we may need a better way?

**Comment by ingwonsong** [comment]
I took a look and re-thought.

Using `match` of `EnvoryFilter` itself seems to be conflict with the current design of WasmPlugin.

In `WasmPlugin`, there is a notion of `phase`, which determines where the wasm plugin should be inserted into.
I think that `phase` is an abstraction as an effort to simplify (and restrict) the configuration.

If we use `match` of `EnvoyFilter` to insert the wasm plugin as an http filter (without `phase`), we need to include the match expression below:
```
          filter:
            name: "envoy.filters.network.http_connection_manager"
            subFilter:
              name: "envoy.filters.http.router"
```

As we can see, `phase` is much more handy than `match` of `EnvoyFilter` because `phase` does not require to know `"envoy.filters.network.http_connection_manager"` or the other http filters to define the location where the injection happen.

Therefore, I would like to suggest to create new match expressions which is similar with EnvoyFilter, but well-fitted to `WasmPlugin` instead of re-use `EnvoyFilter`.

WDYT?

**Comment by zirain** [comment]
> Therefore, I would like to suggest to create new match expressions which is similar with EnvoyFilter, but well-fitted to WasmPlugin instead of re-use EnvoyFilter.

+1 `match` in `EnvoyFilter` right now can not handler route selector without name, the new design should cover this scenario.

**Comment by zirain** [comment]
linked same requirements in `Telemetry`, https://github.com/istio/istio/issues/38271

**Comment by ingwonsong** [comment]
@zirain AFAIK, there is no `per-route` Wasm filter in Envoy. 

Could you explain little bit more about `route` selector stuff you mentioned?

**Comment by zirain** [comment]
> Is there a way to control this and scope to specific routes/listeners?

this's the original request from @ramaraochavali

**Comment by ramaraochavali** [comment]
@ingwonsong There is a way to match listener/virtual host and route configuration in Envoy Filter API https://github.com/istio/api/blob/master/networking/v1alpha3/envoy_filter.proto#L434

What @zirain is referring to is this https://github.com/istio/api/blob/master/networking/v1alpha3/envoy_filter.proto#L550 matching.

> Therefore, I would like to suggest to create new match expressions which is similar with EnvoyFilter, but well-fitted to WasmPlugin instead of re-use EnvoyFilter.

I am not suggesting we reuse the exact matching that Envoy Filter has (If it works, that is great). But we need to build conceptually similar thing here.

**Comment by douglas-reid** [comment]
This was an area of Telemetry API that was left off of the first implementation, but included in the original proposals. We slowly started adding back additional bits like `WorkloadMode` (which would be equivalent to `context` proposed above), but I think a more holistic view of selection via something like `targetRef` may end up being more flexible / future-proof. For instance, do we need to consider possible integrations with the Gateway API and policy attachment via `targetRef`?

**Comment by ramaraochavali** [comment]
targetRef might not fully solve or can resolve it to specific routes/listeners etc.

> Consequently, in addition to workloadSelector, the selector (or matcher) may look like below:

context: SIDECAR_INBOUND | SIDECAR_OUTBOUND | SIDECAR_BOTH | GATEWAY | ANY(default)
port_number or port_name: port number or port name. Empty string(default) means "any"
listener_name: the specific listener's name . Empty string(default) means "any"
WDYT?

This seems like a good direction

**Comment by ingwonsong** [comment]
Reusing `WorkloadMode` and `Port` (or possibly `PortSelector`) sounds good to me.

BTW, do we need to have `per-route` matching? If we want to integrate WasmPlugin with Gateway API and Policy Attachment, I think `per-route` Wasm filter is needed. 

In case of Lua, it is already supported. https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/lua_filter#per-route-configuration

**Comment by kyessenov** [comment]
@ingwonsong Yes, there is a reason why instantiate only one module per proxy. Modules have high overhead, so they are re-used as much as possible. So it doesn't quite make sense to me to have different modules for routes and filters. You can already look up route name inside Wasm with `route_name`. Do you just want some arbitrary config blob for `route_name` instead of `route_name`?

**Comment by ingwonsong** [comment]
@kyessenov Thanks for clarifying it.
Regarding Gateway API and policy attachment, I just imagined Wasm attachment as a kind of policy.
Will look at it.

**Comment by ingwonsong** [comment]
@dgn @ramaraochavali @kyessenov @zirain @douglas-reid I made a draft doc for expanding WasmPlugin API regarding this topic. https://docs.google.com/document/d/1qknaZqXItogEmROVnQD61144pEW1X47bEQraI5D52uY/edit?resourcekey=0-wHAgrakvVaMcnBm40bKuSg#
Could you take a look into it and give some comments or thoughts?

**Comment by eduardosanzb** [comment]
Hello; I'm still confused how the `TrafficSelector` helps to scope the WasmPlugin for specific routes?
