### ISSUE TITLE
Pod reports readiness probe failing on container “istio-proxy”

### ISSUE THREAD

**Issue by sabikm9876** [istio/istio#39447]
Our Production pods are getting restarted 2x a week and we don’t know what’s causing it. We are seeing the following diagnostics when we research the issue. ’ -Pod reports readiness probe failing on container “istio-proxy”:

Line 918: Jun 01 00:31:49 aks-agentpool3-23355474-vmss000003 kubelet[3484]: I0601 00:31:49.747275 3484 prober.go:116] “Probe failed” probeType=“Readiness” pod=“acq-prod2/tokenization-dep-v1-5b468c7d88-xfcwg” podUID=37201ae8-662c-4e00-9bb0-f7f477d4e61e containerName=“istio-proxy” probeResult=failure output=“Get [http://xxxxxxxxx/:xxxxxx/healthz/ready]([https://nam02.safelinks.protection.outlook.com/?url=http%3A%2F%2F172.21.0.78%3A15021%2Fhealthz%2Fready%2F&data=05|01|CAPORRAS%40microsoftsupport.com|ffa5c119cfb64f6f40f808da47be5210|b4c546a47dac46a6a7dded822a11efd3|0|0|637901180000274007|Unknown|TWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D|3000|||&sdata=P5OYhOByhmWHgI4O3cT8Ra%2F3lByibYq8gtMXM8seZF0%3D&reserved=0](https://nam02.safelinks.protection.outlook.com/?url=http%3A%2F%2F172.21.0.78%3A15021%2Fhealthz%2Fready%2F&data=05%7C01%7CCAPORRAS%40microsoftsupport.com%7Cffa5c119cfb64f6f40f808da47be5210%7Cb4c546a47dac46a6a7dded822a11efd3%7C0%7C0%7C637901180000274007%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=P5OYhOByhmWHgI4O3cT8Ra%2F3lByibYq8gtMXM8seZF0%3D&reserved=0)): dial tcp xxxxxxxxx:xxxxx: connect: connection refused”’. Has someone experienced this before and what is the reason or root cause? We are running ISTI) version 1.13.1 with AKS version 1.22.

**Comment by zhlsunshine** [comment]
Hi @sabikm9876  2 questions:
1. Did you specify the probe readiness parameters when deploying your application or just use the default values?
2. Could you please provide the log for istio-proxy as John said?
Thanks!

**Comment by zhlsunshine** [comment]
Hi @sabikm9876, this issue may have some relates with this [PR#39497](https://github.com/istio/istio/pull/39497), you can try it out if necessary.

**Comment by sabikm9876** [comment]
Hi zhlsunshine, First of all Thank You very much for your response. Answers to your questions above #1 we are using the default and have not specified 'probe readiness parameters' when deploying. I will attach the logs for the Istio-proxy
[hipaaformtrackingistioprxy061422.docx](https://github.com/istio/istio/files/8951409/hipaaformtrackingistioprxy061422.docx). Regards,
.

**Comment by howardjohn** [comment]
The proxy is ready per the log:

```
2022-06-01T00:36:01.722738Z info Readiness succeeded in 1m2.857765165s
2022-06-01T00:36:01.723043Z info Envoy proxy is ready
```

**Comment by poinsetta789** [comment]
Hi zhlsunshine, You have helped us in the past on another issue and was hoping I could reach out to you on another issue similar. When we started with ISTIO 2 years ago, we were able to use the external IP of the 'ingress-gateway' as the IP we point to to connect to all of our AKS cluster pods where all of our microservices are running. Sometime ago, it no longer works and we now have to point our APIM gateway to the individual IP for each pod. We also used to use KIALI which allows us to manage the weighted load balancing with this '1' external IP. Since we lost the ability to use '1' IP to point to, we also have challenges with using HPA and liveness probe. We are in process of deploying the HPA for all of our pods and cannot because of this limitation. Can anyone help us with this problem. How are other customers of ISTIO able to connect to multiple pods without having having to point to individual pod's IP? We need to have the 'IP persistence'. Everytime our pod goes down we have to update the IP in the API Gateway. Please help. Any help would greatly help us tremendously!! We are currently using AKS cluster version 1.22.6 and ISTIO 1.13. We are about to upgrade to 1.23 AKS and ISTIO 1.15.
