### ISSUE TITLE
Kong Ingress controller is unable to route requests to the app

### ISSUE THREAD

**Issue by ralls0** [istio/istio#39460]
### Bug Description

I'm running Istio service mesh on OpenShift (by means of the Red Hat OpenShift Service Mesh operator) and Kong as API gateway and ingress controller for my OpenShift cluster.
In particular, I'm trying to follow [this tutorial](https://docs.konghq.com/kubernetes-ingress-controller/2.0.x/guides/getting-started-istio/), but when I try to contact the Kong-Ingress through its EXTERNAL-IP I get an `Operation timed out` error. I have run the same configuration without Istio, and in this case, I can reach the page. Is it possible to use Kong instead of Istio ingress gateway or am I missing something here?

### Version

```prose
$ istioctl version
client version: 1.13.2
control plane version: OSSM_2.1.3
data plane version: 1.9.9 (10 proxies)

$ oc version 
Client Version: 4.10.0-202202160843.p0.gf93da17.assembly.stream-f93da17
Server Version: 4.8.39
```

**Comment by howardjohn** [comment]
IIRC the Kong implementation with Istio you linked is broken. I mentioned this to the Kong team a while back but didn't get any traction. Kong is sending requests to direct pod IPs.

This would be fixed by https://github.com/istio/istio/issues/36596 or by changes on kong side. I'd just moving this bug to Kong sid or track 36596 (its a long ways off though). Cheers
