### ISSUE TITLE
Update documentation related to deploying CNI plugin

### ISSUE THREAD

**Issue by elijah-roberts** [istio/istio#39527]
**Describe the feature request**
Update documentation, and values file to have pattern for enabling CNI 

**Describe alternatives you've considered**
None
**Affected product area (please put an X in all that apply)**

[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

The docs for the istiod helm chart do not indicate how to fully enable istio-cni with 

```
istio_cni:
  enable: true
```

This should be added as an example to the values file, and a note added to the documentation.

**Comment by howardjohn** [comment]
This is documented via https://istio.io/latest/docs/setup/additional-setup/cni/ and https://artifacthub.io/packages/helm/istio-official/cni. More docs are always welcome as PRs but I don't think we have a pressing need that needs to be tracked as an issue. Thanks

**Comment by aek-arm** [comment]
Hi @howardjohn, I hope this message finds you well. I came across this issue with the CNI documentation in the Istio documentation and I was wondering if it might be worth addressing. I would be happy to contribute a pull request, but I am having trouble understanding the CNI architecture without reviewing all the source code involved.

Currently, I am trying to identify why CNI installed via helm is not working, while it does work when installed via istioctl. Upon comparing the yaml files generated by ```istioctl bugreport```, I noticed a difference in the "sidecar-injector" configmap, where istioctl has a setting for "istio_cni" that is not present in the helm chart installation using base, cni, and istiod.

Unfortunately, the CNI helmchart documentation is limited and the additional setup information only briefly mentions istiooperator but not helm. This makes troubleshooting a bit challenging, especially since the documentation on this topic is not very helpful.

It seems that the webhooks are set up differently between helm and istioctl, but again, the documentation is not very clear. Any guidance or help you can provide would be greatly appreciated. Thank you!
