### ISSUE TITLE
questions regarding the wiki page "Using the Code Base"

### ISSUE THREAD

**Issue by eitansuez** [istio/istio#39579]
on the wiki page ["Using the Code Base"](https://github.com/istio/istio/wiki/Using-the-Code-Base)..

1. why are we doing an "istioctl install" _before_ building and pushing the images?
2. doesn't the "istioctl install" command require the flags `--set hub=` and `--set tag=` to actually fetch the images that one built and pushed?

also it would be nice to have instructions that work on apple silicon, if it's not too much trouble.  thanks!

**Comment by ericvn** [comment]
I agree the ordering as specified in your #1 is wrong. Also, missing the --set's.

I updated the wiki page for those items, also adding an item on the env variables (copied from the Linux page, wasn't on the Mac page).

As for working on Apple silicon, we would need someone to provide that data. I only have a Mac Intel at the moment. I would expect that most of the commands would actually be the same. For example, I use Docker Desktop and if I use its Kubernetes environment, I can do a `make docker` and then run istioctl install and it installs Istio. Since the K8s env can see the built images, I don't need to push them. I would expect the same to work on Apple silicon, but unfortunately, I can't verify. You would need to be on a very recent commit as the ARM support was only very recently added.

**Comment by ericvn** [comment]
Since I can't do anymore with the wiki, I will close this issue. If you have some additional thoughts/feedback for running on Apple silicon, please add it here and reopen the issue.

**Comment by eitansuez** [comment]
super. thanks!  i'll run through the updated instructions and provide feedback if necessary.

**Comment by eitansuez** [comment]
this command looks incorrect:
```
go run ./istioctl/cmd/istioctl install uninstall --purge
```
shouldn't it read:
```
go run ./istioctl/cmd/istioctl x uninstall --purge
```

also the sentence "you can deleted you installed istio.." -> "you can delete your installed istio.."
