### ISSUE TITLE
TestTunnelingOutboundTraffic test flake

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#39586]
https://prow.istio.io/view/gs/istio-prow/logs/integ-pilot-multicluster_istio_postsubmit/1540064995352514560

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gs/istio-prow/logs/integ-pilot_istio_postsubmit/1540104022755643392 another example

**Comment by jewertow** [comment]
I took a look at config dumps and everything seems to be configured properly. At the moment I have no idea what's wrong, because I never observed similar problem running those tests locally. So first I will configure access logging in the external-forward-proxy to be able to understand what happens in proxy listeners when tests fail.

**Comment by howardjohn** [comment]
Seems to be stabilized
