### ISSUE TITLE
mixer object pool setup should be configurable and configured low for most tests

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#3970]
b) in #3948

**Comment by ozevren** [comment]
This is already configurable. When writing the tests, all the test author using the library do is specify this.

If the server is cleaned up correctly, (which is not the case for the main bug that started all this), then yes, goroutines are leaked. The correct way to solve this issue is not to lower the pool size, but to actually fix the test.

**Comment by ldemailly** [comment]
cool, can you point me to the doc (or source/config,...) on how to configure it ?

**Comment by ozevren** [comment]
https://github.com/istio/istio/blob/81a970355e58704a9f29befb548f937e6ba895e4/mixer/cmd/mixs/cmd/server.go#L50

**Comment by ldemailly** [comment]
ic, thanks:
```
      --adapterWorkerPoolSize int         Max number of goroutines in the adapter worker pool (default 1024)
      --apiWorkerPoolSize int             Max number of goroutines in the API worker pool (default 1024)
```
it's even here: https://istio.io/docs/reference/commands/mixs.html#mixs server

so we just need to change it in some test
