### ISSUE TITLE
Add (or write) a prometheus query builder for Istio

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#3986]
Istio uses prometheus as the default metrics sink.
Istio relies on prometheus for many verification tests.

The prometheus API is textual and error prone to use.
Either write or look for 
* A prometheus query library that is fluent style.
* A prometheus query library that has a query builder

**Comment by douglas-reid** [comment]
Thinking out loud:

```
m := promql.NewMetric("istio_request_count")
        .WithDimensions("source_service", "foo")
        .Rate(1 * time.Minute)
        .Sum("destination_service)
q := m.QueryString()
```

I think that is along the lines of what is being asked for...

**Comment by loewenstein** [comment]
Should we consider resembling the original query language more closely instead of a fluent style like the example above? E.g.

```
q := Sum(
       Rate(
         Metric("my-metric")
           .Filter("source_service", "foo")
           .Range(5 * time.Minute)
     )) 
```

On a second thought, maybe even more radical. Should we instead just parse the textual queries to verify they are valid promql queries?

I just did a very quick search for `sum(` and `=~` to get a feeling where prometheus queries are in the Istio code base. Turns out a fair amount of queries is in json files, i.e. dashboard definitions, where a builder wouldn't help at all. What we could instead do with these and all other usage sites is running the strings through the parser provided by the prometheus repo itself (see https://github.com/prometheus/prometheus/blob/7e376dfc8901baaa5efd4d7c2ab92ba46d041d7e/promql/parse.go#L55)

WDYT?

**Comment by douglas-reid** [comment]
@loewenstein parsing for validity is certainly a good idea. For things like the dashboards, the e2e dashboard tests should be doing their own validation, but having validation of the queries in other tests would be fantastic.

Beyond parsing however, I believe the intent here was also to make the queries more understandable / approachable to the non-prometheus-savvy folk. Having some sort of query builder would go a long way to addressing that aspect of this request.

**Comment by loewenstein** [comment]
@douglas-reid I also take that as a "don't resemble the promql, fluent/builder would be easier to understand", is that about right?

I tend to disagree, especially as we will have a mixed experience group probably. I.e. some people that are already used to promql will actually have a harder time reading a fluent api.

**Comment by douglas-reid** [comment]
@loewenstein i didn't mean to imply anything about the style, sorry. I tend to like fluent apis, but don't have a strong opinion here.
