### ISSUE TITLE
【Install Istio with an External Control Plane】Test External Control Plane Error creating: Internal error occurred: failed calling webhook "namespace.sidecar-injector.istio.io"  context deadline exceeded

### ISSUE THREAD

**Issue by tanjunchen** [istio/istio#39905]
According to [https://istio.io/latest/docs/setup/install/external-controlplane/](https://istio.io/latest/docs/setup/install/external-controlplane/)，after performing all steps, the pods of the the sample namespace deployed in remote cluster  not ready.
```
chentanjun@xxx  
kubectl --context="${CTX_REMOTE_CLUSTER}" -n sample get pod
No resources found in sample namespace.

chentanjun@xxx
kubectl --context="${CTX_REMOTE_CLUSTER}" -n sample get rs
NAME                       DESIRED   CURRENT   READY   AGE
helloworld-v1-776f57d5f6   1         0         0       11m
sleep-557747455f           1         0         0       11m

chentanjun@xxx
kubectl --context="${CTX_REMOTE_CLUSTER}" -n sample describe rs helloworld-v1-776f57d5f6
 Warning  FailedCreate  6m59s (x15 over 11m)  replicaset-controller  Error creating: Internal error occurred: failed calling webhook "namespace.sidecar-injector.istio.io": Post "https://120.48.114.233:15017/inject/:ENV:cluster=daily-test02:ENV:net=network1?timeout=10s": context deadline exceeded
  Warning  FailedCreate  4m5s (x2 over 9m32s)  replicaset-controller  Error creating: Internal error occurred: failed calling webhook "namespace.sidecar-injector.istio.io": Post "https://120.48.114.233:15017/inject/:ENV:cluster=daily-test02:ENV:net=network1?timeout=10s": dial tcp 120.48.114.233:15017: i/o timeout
```

In this blog, I have some question about it:
```
$ export EXTERNAL_ISTIOD_ADDR=<your external istiod host>
$ export SSL_SECRET_NAME=<your external istiod secret>
```
1. For EXTERNAL_ISTIOD_ADDR, What is this EXTERNAL_ISTIOD_ADDR? Have a more detailed explanation or case(demo)?
2. For SSL_SECRET_NAME, Is there any demo or case for it?
3. The relation of **cacerts** for istiod and SSL_SECRET_NAME Secret.
4. for external-istiod.yaml , Why INJECTION_WEBHOOK_CONFIG_NAME and VALIDATION_WEBHOOK_CONFIG_NAME is  empty?

help for env:
```
version: k8s 1.20.8
istio 1.13.2
```

**Comment by frankbu** [comment]
These instructions are expecting that you are exposing the external cluster gateway using a hostname with properly signed DNS certs. So, you would set the env variables something like this:
```
export EXTERNAL_ISTIOD_ADDR="myhost.example.com"
export SSL_SECRET_NAME="myhost-example-credential"
```
You can see in step 5 of [this section](https://istio.io/latest/docs/setup/install/external-controlplane/#set-up-the-control-plane-in-the-external-cluster) how the env vars are used to configure the gateway. (FYI: you can read more about how to configure a secure gateway here: https://istio.io/latest/docs/tasks/traffic-management/ingress/secure-ingress/#configure-a-tls-ingress-gateway-for-a-single-host)

INJECTION_WEBHOOK_CONFIG_NAME and VALIDATION_WEBHOOK_CONFIG_NAME are empty to disable istiod webhook patching because we're managing the webhook in the remote cluster ourselves.

**Comment by tanjunchen** [comment]
@frankbu  BTW, Can we provide access to the ingress-gateway under istio-system namespace without using the DNS domain? such as IP address for ingress-gateway and change gateway config to PASSTHROUGH. 
Another question is why does proxyMetadata need to be changed in external-istiod iop?

**Comment by tanjunchen** [comment]
@frankbu  BTW, Can we provide access to the ingress-gateway under istio-system namespace without using the DNS domain? such as IP address for ingress-gateway and change gateway config to PASSTHROUGH. 
Another question is why does proxyMetadata need to be changed in external-istiod iop?

**Comment by whirlwinder** [comment]
I am kinda getting a similar error with an External control plane setup. When I try to deploy the sample application on the remote cluster, I get the following error (Openshift 4.10 setup):

 Error creating: Internal error occurred: failed calling webhook "namespace.sidecar-injector.istio.io": failed to call webhook: Post "https://external-FQDN:15017/inject/:ENV:cluster=remote-cluster1:ENV:net=network1?timeout=10s": EOF
 
 I've set the configuration following the secrets and creating an external route on Openshift with these values.
$ export EXTERNAL_ISTIOD_ADDR=<your external istiod host>
$ export SSL_SECRET_NAME=<your external istiod secret>

Checked mutatingwebhookconfiguration and the cert on the istio-system and external-istiod - md5sums match

Any chance you can give me a hint at what could I check as the EOF error doesn't provide much detail? Thanks

**Comment by frankbu** [comment]
@whirlwinder Do you know if the request is getting through to istiod or if the connection itself is failing? Are there any messages in the ingress gateway or external istiod logs? 

Btw. take a look at the recently updated external control plane doc here: https://preliminary.istio.io/latest/docs/setup/install/external-controlplane/. It includes a more detailed instructions, including how to more easily set up an external control plane deployment for experimenting/testing.

**Comment by whirlwinder** [comment]
Thanks for the heads-up. @frankbu It was really a connectivity issue as our network was misconfigured - i.e. wrong ports. The guide is really helpful and works like a charm.

If I may ask for more information regarding the self-signed certificates and the external control plane setup because I was unable to find information regarding it. Our organization has a CA which is self-signed and the root and intermediate certs used are not signed by any of the global trusted CAs - such as Verisign, Sectigo, Godaddy, etc. What is the 
 correct approach in this scenario - does this approach apply in this case:

https://istio.io/latest/docs/tasks/security/cert-management/plugin-ca-cert/

Meaning we have to add the CAs keys to istio as cacerts cacerts - private, public, chain. And also if our intermediate CA is self-signed would the Istiod accept it in order to later sign the certs that will be generated by it -  I think that in order to be an intermediate CA you'd need to match some very strict requirements and not sure how the istio treats such CAs.
