### ISSUE TITLE
Gateway conformance: support HTTPRouteInvalidNonExistentBackendRef

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#39919]
Currently HTTPRouteInvalidNonExistentBackendRef is skipped. This is because we need to implement support for detecting it _and_ we need https://github.com/envoyproxy/envoy/issues/21930 merged

**Comment by dddddai** [comment]
IIUC if a BackendRef is invalid(not necessarily nonexistent, maybe [not allowed by a ReferenceGrant](https://github.com/kubernetes-sigs/gateway-api/blob/cea484e38e078a2c1997d8c7a62f410a1540f519/apis/v1beta1/httproute_types.go#L211-L212)), we will generate the VS as-is, but return 500 when traffic goes to the invalid BackendRef, right?

If so the current code would not work as expected, because it would just stop generating the VS and return
https://github.com/istio/istio/blob/dd72869a66522ce0c9a8d8819e3e1756cb26f53e/pilot/pkg/config/kube/gateway/conversion.go#L858-L863
https://github.com/istio/istio/blob/dd72869a66522ce0c9a8d8819e3e1756cb26f53e/pilot/pkg/config/kube/gateway/conversion.go#L379-L382

So I think we should refactor this a little bit to meet the gateway-api requirements?
