### ISSUE TITLE
In 'Install Istio with an External Control Plane', when accessing the helloworld application several times through the ingress gateway, only version v1 is now being called.

### ISSUE THREAD

**Issue by suwliang3** [istio/istio#39943]
### Bug Description

By using [https://preliminary.istio.io/latest/docs/setup/install/external-controlplane/#adding-clusters](url)，only version v1 is now being called When accessing the helloworld application several times through the ingress gateway after adding clusters to the mesh.
```
[root@]#  for i in {1..10}; do curl -s "http://${GATEWAY_URL}/hello"; done
Hello version: v1, instance: helloworld-v1-776f57d5f6-87r4r
Hello version: v1, instance: helloworld-v1-776f57d5f6-87r4r
Hello version: v1, instance: helloworld-v1-776f57d5f6-87r4r
Hello version: v1, instance: helloworld-v1-776f57d5f6-87r4r
Hello version: v1, instance: helloworld-v1-776f57d5f6-87r4r
Hello version: v1, instance: helloworld-v1-776f57d5f6-87r4r
```
In  [https://preliminary.istio.io/latest/docs/setup/install/external-controlplane/#adding-clusters](url), we only expose service in the first remote cluster.`kubectl --context="${CTX_REMOTE_CLUSTER}" apply -n external-istiod -f \
    [samples/multicluster/expose-services.yaml]`(https://raw.githubusercontent.com/istio/istio/master/samples/multicluster/expose-services.yaml)
Is there a problem here?

### Version

```prose
client version: 1.12.6
control plane version: 1.12.6
data plane version: 1.12.6 (1 proxies)

Client Version: v1.21.5
Server Version: v1.21.5
```

**Comment by suwliang3** [comment]
@frankbu Can you help me to resolve the problem please?
@morvencao Have you encountered the same problem as me?

**Comment by morvencao** [comment]
If you following the guide: [https://preliminary.istio.io/latest/docs/setup/install/external-controlplane/#adding-clusters](https://preliminary.istio.io/latest/docs/setup/install/external-controlplane/#adding-clusters) then you need to install latest istio version to get the fix: https://github.com/istio/istio/pull/39406

**Comment by litong01** [comment]
@suwliang3 I've tested with latest master branch, and 1.12.5 release of Istio, following the instruction, you should be able to access the app hitting both versions. I've created scripts to do this kind of deployment and test, you probably can take a look here https://github.com/litong01/multicluster-istio/blob/main/do-3-clusters-metallb.sh, notice that the script is based on the latest feature, but if you will be using 1.12.5, you only need to change the line https://github.com/litong01/multicluster-istio/blob/main/do-3-clusters-metallb.sh to place the remote secret into config cluster which will be CLUSTER2_NAME instead of CLUSTER1_NAME. Then you should be able to create workload in both config and remote cluster, and access to helloworld.sample:5000 should hit multiple versions of the service. Let me know if you have any questions
