### ISSUE TITLE
Sidecar injection downtime during istioctl install/upgrade

### ISSUE THREAD

**Issue by cnvergence** [istio/istio#40134]
### Bug Description

We encountered [downtime](https://github.com/kyma-incubator/reconciler/issues/1138) when istioctl upgrade was run and deployment got rolled out at the same time.
This is only happening when no revision is set and I believe this part is causing this [issue](https://github.com/istio/istio/blob/master/operator/cmd/mesh/install.go#L199-L201)
The only workaround for default revision installations is to restart pods again.

### Steps to reproduce
- install  latest Istio with default profile and no revision 
```
istioctl install
This will install the Istio 1.14.0 default profile with ["Istio core" "Istiod" "Ingress gateways"] components into the cluster. Proceed? (y/N) y
✔ Istio core installed
✔ Istiod installed
✔ Ingress gateways installed
✔ Installation complete                                                               
Making this installation the default for injection and validation.
```
- create namespace httpbin and label it
```
k create ns httpbin
k label namespace httpbin istio-injection=enabled
```
- deploy httpbin to that namespace 
```
kubectl apply -f https://raw.githubusercontent.com/istio/istio/master/samples/httpbin/httpbin.yaml -n httpbin
```
- check that the httpbin pod has two containers, one is the istio sidecar
```
k get pods
NAME                       READY   STATUS    RESTARTS   AGE
httpbin-847f64cc8d-c9bqd   2/2     Running   0          6s
```
- rerun istioctl install and in parallel do a rollout restart of a deployment httpbin
```
istioctl install 
This will install the Istio 1.14.0 default profile with ["Istio core" "Istiod" "Ingress gateways"] components into the cluster. Proceed? (y/N) y
✔ Istio core installed
✔ Istiod installed
✔ Ingress gateways installed
✔ Installation complete                                                              
 Making this installation the default for injection and validation.
```
```
k rollout restart deployment httpbin
```
- the httpbin pod will restart without a sidecar
```
 k get pods
NAME                       READY   STATUS        RESTARTS   AGE
httpbin-7657d6bc8b-crms5   1/1     Running       0          4s
httpbin-847f64cc8d-c9bqd   2/2     Terminating   0          2m9s
```

### Version

```prose
client version: 1.14.0
control plane version: 1.14.0
data plane version: 1.14.0 (2 proxies)
```

**Comment by litong01** [comment]
@cnvergence karol, I think this actually is expected (not necessarily) behavior, when you run `istioctl install`, the sidecar injector webhook actually will be updated (actually 3 time in one install), when it gets installed first, its failurePolicy will be set to Ignore, then it will be updated to Fail, before it gets updated to `Fail`, the rollout restart deployment would not do the sidecar injection. So according to our code, there is this small window, that sidecar injection would not work since at the time that the istiod service may not be available. I am not entire sure why it was done that way, I would think that the installer should only do one time install/update to the sidecar injection webhook configuration, but it was not done that way, my guess is that if it is enabled too soon, then the installation process will fail installing other components. Seems to me this is really a compromise for the installer. At present, seems to me that the best way is not to do upgrade istio and workload at the same time?

**Comment by cnvergence** [comment]
Seems to be resolved by this PR https://github.com/istio/istio/pull/41164
