### ISSUE TITLE
Test failure: TestTunnelingOutboundTraffic

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#40812]
https://prow.istio.io/view/gs/istio-prow/logs/integ-assertion_istio_postsubmit/1566819394019921920

```

{Failed      tunneling_test.go:356: retry.UntilSuccessOrFail: timeout while waiting after 3 attempts (last error: tunnelingConfig was not removed from istio-proxy configuration in istio-egressgateway/istio-system)}

```

**Comment by hzxuzhonghu** [comment]
@jewertow

**Comment by jewertow** [comment]
This error means that removal of the destination rule used in this test was not processed by istiod on time. To be honest it's very difficult to determine why that happened and it look like a totally random failure. I also don't think that we should change timeout for this check, because it's 10 seconds for now and in normal case it should be enough.

I also looked at all failed tests from last 2 weeks and there were 31 failures in total. 7 of those were because of failed tunneling_test. I verified all of them and 6 remaining failures are:
- 4 times:
```
{Failed      tunneling_test.go:234: failed to create config map external-forward-proxy-config: configmaps "external-forward-proxy-config" already exists}
```
This is a simple [bug](https://github.com/istio/istio/blob/master/tests/integration/pilot/tunneling_test.go#L234) in the test. I will fix it.

- 1 time:
```
{Failed      tunneling_test.go:329: retry.UntilSuccessOrFail: timeout while waiting after 119 attempts (last error: pods app=external-forward-proxy are not ready: 1 error occurred:
        
        )}
```
I checked logs and there was timeout on pulling image of forward proxy, so it's not our fault.
- 1 time:
```
{Failed      tunneling_test.go:139: retry.UntilSuccessOrFail: timeout while waiting after 11 attempts (last error: failed to find expected log: remoteAddr=10.244.0.81 method=GET url=/HTTP1/TLS/gateway/tls/passthrough/HTTP-request in logs of external)}
```
This error means that request was not tunneled and arrived directly from client pod. I checked config dumps and there is no `tunneling_config` in tcp_proxy in egress gateway, so it seems that the destination rule was not processed on time by istiod or by istio-proxy. It's only 1 of 32 cases in this test, so I wouldn't say that it's a serious problem.

Taking into account that I can quickly fix the most frequent failure, we have 3 failures of tunneling_test.go in 2 weeks. I think that it's not good and not bad, because there are also other tests that fail regularly in postsubmit jobs due to random network issues.

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gs/istio-prow/logs/integ-assertion_istio_postsubmit/1567739220867420160 was another one after https://github.com/istio/istio/pull/40852

**Comment by jewertow** [comment]
I checked logs and behavior of istio-proxy looks very strange and totally unexpected.

First of all, configuration of [sidecar](https://storage.googleapis.com/istio-prow/logs/integ-assertion_istio_postsubmit/1567739220867420160/artifacts/pilot-dedef83a90f84de0b86b61bb6/TestTunnelingOutboundTraffic/HTTP1/noTLS/sidecar/HTTP-request/_test_context/echo-2-21391-state3664776359/primary-0/a-v1-7d6d5654b5-6q98d_proxy-config.json) looks correct - it contains a listener of type TcpProxy with proper address, tunneling configuration and cluster:
```
"name": "10.96.169.226_86",
"version_info": "2022-09-08T05:07:29Z/13",
"cluster": "outbound|3128|external-svc-tcp|external-forward-proxy.external-1-90470.svc.cluster.local",
"tunneling_config": { "hostname": "external.external-1-90470:86" }
```
but sidecar [logs](https://storage.googleapis.com/istio-prow/logs/integ-assertion_istio_postsubmit/1567739220867420160/artifacts/pilot-dedef83a90f84de0b86b61bb6/TestTunnelingOutboundTraffic/HTTP1/noTLS/sidecar/HTTP-request/_test_context/echo-2-21391-state3664776359/primary-0/a-v1-7d6d5654b5-6q98d_istio-proxy.log) show that traffic is redirected to incorrect cluster:
```
[2022-09-08T05:21:59.165Z] "- - -" 0 - - - "-" 175 487 71 - "-" "-" "-" "-" "10.244.0.45:18086" outbound|86||external.external-1-90470.svc.cluster.local 10.244.0.42:46250 10.96.169.226:86 10.244.0.42:46460 - -
...
[2022-09-08T05:22:09.326Z] "- - -" 0 - - - "-" 175 487 53 - "-" "-" "-" "-" "10.244.0.45:18086" outbound|86||external.external-1-90470.svc.cluster.local 10.244.0.42:48734 10.96.169.226:86 10.244.0.42:48944 - -
```
Cluster `outbound|86||external.external-1-90470.svc.cluster.local` exists in [sidecar configuration](https://storage.googleapis.com/istio-prow/logs/integ-assertion_istio_postsubmit/1567739220867420160/artifacts/pilot-dedef83a90f84de0b86b61bb6/TestTunnelingOutboundTraffic/HTTP1/noTLS/sidecar/HTTP-request/_test_context/echo-2-21391-state3664776359/primary-0/a-v1-7d6d5654b5-6q98d_proxy-config.json), but is not used by any listener, so how is it possible that sidecar redirects traffic there? Did you ever encounter a similar problem?

**Comment by howardjohn** [comment]
Huh... that is odd. I have not seen that. my best guess is we hit an unfortunate timing between the requests and config dump where the old listener was draining and was removed before the config dump captured it... that seems unlikely though, but I don't have any better ideas..

**Comment by jewertow** [comment]
> my best guess is we hit an unfortunate timing

I was also considering such a case, but then it should occur rarely. Unfortunately it happens regularly, so I doubt that this is the case.

If this is a random runtime issue of istio-proxy, I could try to fix this problem by using different clients in subsequent iterations.
```
ctx.NewSubTest(testName).Run(func(ctx framework.TestContext) {
	// requests will fail until istio-proxy gets the Envoy configuration from istiod, so retries are necessary
	retry.UntilSuccessOrFail(ctx, func() error {
		client := apps.A[0]
		target := apps.External.All[0]
		if err := testConnectivity(client, target, spec.protocol, spec.portName, testName); err != nil {
			return err
		}
		if err := verifyThatRequestWasTunneled(target, externalForwardProxyIP, testName); err != nil {
			return err
		}
		return nil
	}, retry.Timeout(10*time.Second))
})
```
Currently the client is always `apps.A`, but I could try to use `apps.B` in the attempt n+1 and `apps.C` in the attempt n+2. So then different proxies would be used, probably without runtime misconfigurations. It doesn't matter in this test what the client is, but whether the request came from forward proxy instead of from the client.
If this test will still fail, I will revert this change, because of debugging complexity and will think about another solution.
What do you think?

**Comment by howardjohn** [comment]
Seems like a reasonable attempt to help debug this, but I wouldn't want to keep it long term as it would seem like masking a real bug?

**Comment by jewertow** [comment]
Yeah... But in my opinion it's not a problem with the test itself. As you can see, istio-proxy has correct configuration, but behaves incorrectly as it would have a different configuration. Like it didn't apply it in runtime yet...? I have a limited knowledge about Envoy internals, so it's not easy to me to determine what really happens inside Envoy listeners in runtime.

**Comment by howardjohn** [comment]
There is certainly a bug in the system somewhere. Even if it's in Envoy
internals, that is still something we want to detect - not hide. A user
won't care if the config is right, just that the end user behavior is
correct.

**Comment by jewertow** [comment]
Ok, I will investigate this problem deeper, but I need more time, because I have to look at Envoy implementation details, read more documentation, search issues and so on... I will try to come back with an update in a week or two.

**Comment by jewertow** [comment]
@howardjohn I reviewed failed jobs from October and November and I didn't find any job that failed due to `TestTunnelingOutboundTraffic`. I read change log of Envoy 1.24 and I didn't see any bug fix that directly addresses this problem, but there were some changes related to cluster manager, router and tunneling, so maybe it was fixed indirectly...
Anyway, I didn't find any answer what caused those anomalies in the proxy, but the problem does not occur recently, so could we close this issue for now?

**Comment by howardjohn** [comment]
Sounds good, thanks
