### ISSUE TITLE
istio envoy proxy not working if request came from non sidecar pods in same namespace

### ISSUE THREAD

**Issue by hunnykalra** [istio/istio#41264]
### Bug Description

I am new istio service mesh, can anyone help me here 
Question :- 
I have two application one nginx(on which side car injection is not enabled) and ui(react application on which side car injection is enabled) in same namespace. When request redirect to ui application form nginx than virtual services and destination rule logic applied on ui application doesn't work . it redirecting request randomly to any pods related to deployment object of ui. i have applied rule on header based on virtual services but these seems to be have no effect 

### Version

```prose
isito version - 1.14.2
Kuberenetes version - 1.20.7
```

**Comment by GregHanson** [comment]
@hunnykalra HTTP routing is going to be applied at the client, so if the nginx application is not injected with a sidecar, any VirtualService based routing will NOT be applied to the traffic.  You can either inject a sidecar into the nginx app, or configure your nginx app to call the istio ingress gateway where you can define a Gateway and VirtualService to configure routing to your UI application (steps [here](https://istio.io/latest/docs/tasks/traffic-management/ingress/ingress-control/))

**Comment by hunnykalra** [comment]
@GregHanson  if i applied  sidecar  into nginx app  than routing of traffic worked fine as expected but when redeploy nginx than for few seconds(10-15 sec) i received 502 badgateway request on nginx , it seems like request is going to terminated nginx pods 
My application architecture :- 
 aws alb -> ingress gateway -> nginx(side car enabled) ->  ui(side car enabled )

**Comment by GregHanson** [comment]
@hunnykalra normally you see a 503 in the case of traffic getting directed to an unready/stale endpoint.  502 might be because of how your NGINX client is configured for inbound connections when there is an istio proxy sidecar intercepting the inbound traffic ([example](https://stackoverflow.com/questions/60576252/nginx-bad-gateway-502-when-accessing-istio-envoy-deployed-on-kubernetes)).  It may also be a misconfiguration of the port/protocol in your K8S Service spec which Istio relies on to configure traffic capture at the sidecar ([istio docs](https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/)).

You can try and increase the envoy log level (different and independent of access logs) on your ingress gateway to try and capture the error the ingress gateway envoy proxy is hitting during the request:
```
istioctl pc log <istio-ingressgateway-pod> -n istio-system --level trace
## send a few failed requests, then reset the level back to warning
istioctl pc log <istio-ingressgateway-pod> -n istio-system --reset
```
Search the logs for the 502 response and trace the request backwards from there.  `--level trace` will generate a lot of logs, and there will be some noise from pod health checks.  If an access log is generated on the NGINX sidecar proxy (enable if they are not), you can try the same debug technique used on the ingress gateway above.  NOTE: envoy access logs will not generate an entry if there is not a port/protocol match on the inbound connection
