### ISSUE TITLE
release: missing debug version of the debian package (for VMs)

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#4133]
We produce the xenial compatible debian with prod settings by default (which is good)

To mirror the _debug of our other artefacts we should probably have a _debug for the debian package too

(this is relatively lowpri anyway given that for raw hw/VM support it's likely a customer would need to build from source for their specific OS/Architecture combo anyway, or vendors would do that for them - but still)

(cc @louiscryan from the chat we had)

**Comment by mattdelco** [comment]
At some point it'd be worthwhile to hash out whether istio is going to have a model of release build vs debug build, or continue down the path of having one build type that tends to produce both (though only of certain images/artifacts).  I'm guessing that the tendency towards one build type has been due to simplicity, but also because the current model of using image:sha for docker images means that a release build and debug build at the same commit will push to the same place (hence the tendency to use image_debug:sha for debug images, which means that a release vs. debug build starts to differ in more ways than simply what flags were passed to the compiler).

**Comment by ldemailly** [comment]
not stale
