### ISSUE TITLE
1.13 --> 1.14 user gw upgrade issues when autoscaleEnabled is true and .k8s.replicaCount is nonzero

### ISSUE THREAD

**Issue by infa-ddeore** [istio/istio#41481]
### Bug Description

1.13 user gateway is deployed by using `istioctl` with `autoscaleEnabled` is true and `.k8s.replicaCount` as 4, four gw pods are created and hpa takes care of gw scaling as per scaling rules

1.14 istioctl creates deployment without replicas when `autoscaleEnabled` is `true`, this is as per [the changes](https://istio.io/latest/news/releases/1.14.x/announcing-1.14/change-notes/#installation) but this behaviour involves downtime. As soon as 1.14 deployment objects are applied, replicas are removed, that makes replicas as default 1, k8 terminates three 1.13 pods at a same time which causes downtime because only 1 gateway keeps running for few seconds until 1.14 pods start

### Version

```prose
$ istioctl version
client version: 1.14.1
istiod version: 1.13.5
istiod version: 1.14.1
data plane version: 1.14.3 (4 proxies)

$ k version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.24.3
Kustomize Version: v4.5.4
Server Version: v1.21.11
```

### Additional Information

**how to reproduce:**

download [gateway-config.zip](https://github.com/istio/istio/files/9806958/gateway-config.zip) which has 1.13 and 1.14 gateway override files.

deploy 1.13 user gw (adjust revision and discoveryAddress to match correct control plane):

```
$ ~/tmp/istio-1.13.2/bin/istioctl manifest generate -f gw_1.13.yaml | k apply -f -

# deploys 4 pods as expected with hpa

$ k get po,hpa
NAME                           READY   STATUS    RESTARTS   AGE
pod/test-gw-564644b76b-9sgks   1/1     Running   0          23s
pod/test-gw-564644b76b-fr4kl   1/1     Running   0          23s
pod/test-gw-564644b76b-ns5rf   1/1     Running   0          23s
pod/test-gw-564644b76b-qvfrb   1/1     Running   0          23s

NAME                                          REFERENCE            TARGETS         MINPODS   MAXPODS   REPLICAS   AGE
horizontalpodautoscaler.autoscaling/test-gw   Deployment/test-gw   <unknown>/80%   4         5         4          23s
```

upgrade user gw to 1.14 (adjust revision and discoveryAddress to match correct control plane):

```
$ ~/tmp/istio-1.14.3/bin/istioctl manifest generate -f gw_1.14.yaml | k apply -f -
k get pocomponents.ingressGateways[name=test-gw].k8s.replicaCount should not be set when values.gateways.istio-ingressgateway.autoscaleEnabled is true
serviceaccount/test-gw-service-account configured
deployment.apps/test-gw configured
Warning: policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
poddisruptionbudget.policy/test-gw configured
role.rbac.authorization.k8s.io/test-gw-sds configured
rolebinding.rbac.authorization.k8s.io/test-gw-sds configured
horizontalpodautoscaler.autoscaling/test-gw configured
service/test-gw configured

##### >>>>>>> replicas became 1 so 3 out of old 4 pods start terminating at same time
$ k get po
NAME                       READY   STATUS              RESTARTS   AGE
test-gw-564644b76b-9sgks   1/1     Terminating         0          62s
test-gw-564644b76b-fr4kl   1/1     Terminating         0          62s
test-gw-564644b76b-ns5rf   1/1     Running             0          62s
test-gw-564644b76b-qvfrb   1/1     Terminating         0          62s
test-gw-6657f58f7-w4g6x    0/1     ContainerCreating   0          0s
```

### hpa increases 1.14 replicas to 4 as per the config
$ k get po
NAME                      READY   STATUS    RESTARTS   AGE
test-gw-6657f58f7-hklnr   1/1     Running   0          86s
test-gw-6657f58f7-p2kwv   1/1     Running   0          86s
test-gw-6657f58f7-sgstj   1/1     Running   0          86s
test-gw-6657f58f7-w4g6x   1/1     Running   0          99s

**Comment by AlfredoFausto** [comment]
The reason of the changes was introduced to reset replicaCount when autoscaling is enabled. This change makes sense because we don't want the ReplicaSet controller and HPA controller to be fighting each other which align with how Kubernetes should work
You can find documentation that explicitly explain this behavior here: [Horizontal Pod Autoscaling](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#migrating-deployments-and-statefulsets-to-horizontal-autoscaling)

So, what means that to you who uses replicaCount? You must migrate your deployment from using replicas to HPA controller
Here is how you should do it:

Edit the current deployment which has revision 1.13.5 This is a manual process to prevent the object at the server side be updated.
Run the following command:

```kubectl apply edit-last-applied deployment/test-gw```

Remove the replicas field and save it at this point the pods are still unchanged
On your gw-operator file with revision 1.14.1 remove the replicasCount field and then upgrade the gateway deployment

```istioctl manifest generate -f gw_1.14.yaml | k apply -f -```

Since the current deployment is already managed by the HPA controller this will allow you to upgrade the pods with the desire behavior and all the gw-pods will be running until the new ones are ready

This is a single migration task for any new release in the future there is no need to perform these steps, but the replicasCount should not be added to the manifest anymore
