### ISSUE TITLE
pod transitions: RUNNING->UNKNOWN->RUNNING

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#4170]
If a pod gets transiently reported as unknown by k8s we shouldn't drop it during that time (imo, as by doing so we turn a possible transient k8s issue into a missing endpoint)

https://github.com/istio/istio/pull/4145#discussion_r173610476

**Comment by rshriram** [comment]
We have not seen any issues in the wild arising from this. Can you please create an reproducible test case for this? If not I will close this

**Comment by ldemailly** [comment]
you can simulate it with a mock api call

I don’t think we should not handle a rare case on the basis of not having seen them.

**Comment by rshriram** [comment]
Once again, please provide a reproducible code that we can run and clearly demonstrate the problem. Otherwise, its hard to quantify work..

**Comment by ZackButcher** [comment]
Envoy's lame ducking, plus circuit breaking, should cover errors that arise as a result of this happening, right? Endpoints being transiently unavailable is just a part of operating in a dynamic environment. IMO keeping `UNKNOWN` pods around is fine (they may be able to serve, after all) given that Envoy's built in resiliency features should help mitigate problems due to `UNKNOWN` pods that cannot serve requests.

**Comment by ZackButcher** [comment]
@costinm what're your thoughts here? Worth changing the cache in pilots and the endpoints we push, or can we just trust in lame ducking/CB?

**Comment by ldemailly** [comment]
my point was istio shouldn't lower the availability - ie should not drop unknown pods which may actually be reachable, and indeed the source envoy can figure out on its own if the endpoint is reachable or not
