### ISSUE TITLE
Add documentation for Istio support for gRPC's proxyless service mesh features

### ISSUE THREAD

**Issue by alfredkrohmer** [istio/istio#42009]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

This blog post is one of (or the) only examples I can find for Istio support for gRPC's proxyless service mesh features:
https://istio.io/latest/blog/2021/proxyless-grpc/

I can't find anything in the official documentation at: https://istio.io/latest/docs/

Documentation for this feature should be improved.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by MSAdministrator** [comment]
Same

**Comment by keithmattix** [comment]
Not stale

**Comment by costinm** [comment]
Since we are discussing this in separate issue: AFAIK the plan is to support the Gateway API surface only. The main problem with moving proxyless forward and documenting it was the fast set of Istio APIs and behaviors that don't work
with proxyless gRPC. 

For Gateway API surface - the gRPC team is supporting all features (AFAIK) in their code - they also support them with
TD (google's control plane).

I expect - and will be pushing for - the gRPC team to own the documentation on how to use gRPC with the Gateway API - 
as they implement the data plane and have their own compliance tests across multiple languages - and may have 
some vendor extensions and support different set of optional policies. 

On Istio side - we should document any differences/gaps/extra features or policies that Istio may support - but 
I don't think we should have our own 'main' docs for proxyless gRPC. 

I personally don't see any scenario where Istio API surface will work for proxyless gRPC ( with docs explaining
which field and behavior is same or different compared to Istio), and since the gRPC team is focusing in compat 
with the Gateway API - their data plane and efforts will be aligned with that API.
