### ISSUE TITLE
Prototype sandwiching Envoy and zTunnel

### ISSUE THREAD

**Issue by stevenctl** [istio/istio#42033]
Start with running a zTunnel inside the same container as an Envoy proxy to handle HBONE termination and initialization.

This may be a viable path forward for implementing Waypoints.

The prototype need not be solid, but should move us towards having a design

**Comment by kyessenov** [comment]
Waypoints don't need Ambient, and the only way to implement HBONE in Envoy is essentially run two proxies connected with a user-space socket. So this sounds like a win-win to me. We can eliminate a lot of complexity and challenges from Envoys if all HBONE concerns are factored out.

**Comment by kyessenov** [comment]
> @hzxuzhonghu Waypoints don't need Ambient, and the only way to implement H/QBONE in Envoy is essentially run two proxies connected with a user-space socket. So this sounds like a win-win to me. We can eliminate a lot of complexity and challenges from Envoys if all HBONE concerns are factored out.

**Comment by kyessenov** [comment]
This needs a design, but the gist after discussion with Costin is essentially what ambient was before HBONE:

* envoy server receives PP2 with TLV record 64 set to SPIFFE URI SAN, see for example https://github.com/istio/proxy/pull/4222
* envoy client sends PP2 with TLV records set for VIP and service name. The latter needs for destination rules applied in the chain since envoy can't see peer cert.

**Comment by hzxuzhonghu** [comment]
Thanks for your clarification @kyessenov， catching up now

**Comment by linsun** [comment]
A couple of options mentioned in various previous ambient meetings:

1. Simple approach: ztunnel co-located with waypoint proxy on the same pod (or even container). There is no concern of security between the two. Proxy Protocol (credit to @ejj) could be potentially used to pass metadata from the ztunnel connection to waypoint proxy connection on localhost.

2. ztunnel co-located on the node could be used if there is one. This approach could save running ztunnel in the pod, however, there is concern of ztunnel to waypoint proxy traffic is plain text. Think option 1 should be explored first as even with this option 2, we will still need option 1  when there is no co-located ztunnel on the node. With this approach, ztunnel on the waypoint proxy pod won't be activated when there is co-located ztunnel on the node.

Not only reusing ztunnel gets the waypoint proxy the HBONE termination and initialization, it will also get us the L4 policy enforcement at waypoint proxy.

cc @stevenctl @howardjohn @louiscryan @dhawton @EItanya @shashankram @hzxuzhonghu @kyessenov

**Comment by hzxuzhonghu** [comment]
option 1 should be simpler and the communication performance within a pod can be higher than within a host.

**Comment by kyessenov** [comment]
@linun @hzxuzhonghu We have a prototype already for PROXY PROTOCOL sandwich mainline Istio https://github.com/istio/proxy/pull/4222. I think sidecar-to-sidecar is quite reasonable, because the communication would be plaintext and it's an easy argument why that is secure.

@howardjohn I don't understand the argument about mutating the requests. Can you elaborate?

**Comment by kyessenov** [comment]
There are drawbacks with both sockopts and MDS. sockopts are limited by the kernel buffers (so it's not sufficient in all cases). MDS adds a latency and a failure mode since it's on-demand. IMHO I'd agree with @hzxuzhonghu that:
1. in-pod is simpler and faster, wire-protocol is better over extra discovery, PROXY better than h2 due to simper connection management.
2. There's no need to support a single mode. MDS can be fairly easily supported in addition.

**Comment by linsun** [comment]
@kyessenov thanks for sharing you already have a prototype. Would it be possible to have you discuss about it in next Wed's ambient community call? Or if you have a readme for others to try it?

I think everyone agrees option 1 (ztunnel co-located w/ waypoint proxy in the same pod) is the simplest approach we should start with.

**Comment by howardjohn** [comment]
> I think everyone agrees option 1 (ztunnel co-located w/ waypoint proxy in the same pod) is the simplest approach we should start with.

For short term or in general? I am not convinced its better than node

**Comment by kyessenov** [comment]
@linsun Sure, but John is right, I don't think it's hard to prototype, but it would be throw-away before agreeing on the mode.
@howardjohn We might be referring to slightly different things by ztunnel. I am strictly referring to the termination capability of ztunnel, no LB or pooling or policy.

**Comment by howardjohn** [comment]
I think I meant the same. I was referring in https://github.com/istio/istio/issues/42033#issuecomment-1343328133 to the difference between running two binaries in the waypoint (ztunnel+envoy) vs using the existing ztunnel running on the node. I think where the ztunnel runs and what behavior it does are somewhat separate problems, and I agree with you that it would just terminate+encap (mostly - we could consider it doing L4 RBAC, although its probably easier to just have Envoy do that).

The benefit of using a node ztunnel is:
* Its already there, so its ~free
* Less load on control plane for the same reason as ^
* It validates that ztunnel is actually a viable model and forces us to make it so. Waypoint becomes just another application. If waypoint struggles to work in this environment, it _might_ signal that user applications will as well

I think most of the downsides of it also apply to user applications, which was kind of my last point. Shared fate, possible security risks, etc are all things that happen to users as well.

At an extreme position, I'd ask: if waypoint needs a 'ztunnel sidecar', why are we shipping 'ztunnel daemonset' to users instead of 'ztunnel sidecars'? They aren't _exactly_ the same (upgrades, for example, are a big motivation that doesn't really apply to waypoints), but its a reasonable thought exercise at least.

I am not strictly against ztunnel sidecar, but I wouldn't say "everyone agrees we should do it".

**Comment by kyessenov** [comment]
> * It validates that ztunnel is actually a viable model and forces us to make it so. Waypoint becomes just another application. If waypoint struggles to work in this environment, it _might_ signal that user applications will as well

@howardjohn There is a difference between user app and waypoints: We need additional metadata about connections beyond payload to enforce L7 policy and telemetry. There's no requirement that general user applications need that capability.  It's perfectly reasonable to assume if the user application needs this capability then it needs to do some extra work (like terminate MASQUE or HBONE). User applications should not have to be able to terminate HBONE to work with ztunnels.

> At an extreme position, I'd ask: if waypoint needs a 'ztunnel sidecar', why are we shipping 'ztunnel daemonset' to users instead of 'ztunnel sidecars'? They aren't _exactly_ the same (upgrades, for example, are a big motivation that doesn't really apply to waypoints), but its a reasonable thought exercise at least.

Ztunnel sidecar is not ztunnel daemonset (as I said, no policy, LB, etc). But it's a fair model to run ztunnel as a sidecar instead of Envoy just for L4 stuff, it's just wasteful.

**Comment by howardjohn** [comment]
I think the main disconnect may be that I generally think that user applications _should_ have that ability. Sorry if I didn't make that clear.

Today with sidecars, users _sometimes_ get that info. If they are using HTTP the get XFCC, etc - I suppose the cert is really the main piece, we don't expose the telemetry bits. Moving towards ztunnel, we lose that because its no longer L7. But we also lose some of the ability to trust the traffic _actually went through Envoy_.

With sidecars, there were some tricks to verify this (listener on localhost or UDS), or at least more visibility - the app or operator can easily look to see envoy is running and trust that mTLS is happening. This, again, is lost with ztunnel.

This to me all points to a need for an application to lookup "For this connection, give me <info> about it". At the very least, that would be "was it encrypted" and "what is the identity of the peer".

Without this, we are mostly telling users "All your traffic is encrypted! Just take my word for it, there is no way to check". And also we lose some value add of being able to build peer-aware applications.

**Comment by kyessenov** [comment]
> This to me all points to a need for an application to lookup "For this connection, give me about it". At the very least, that would be "was it encrypted" and "what is the identity of the peer".
> 
> Without this, we are mostly telling users "All your traffic is encrypted! Just take my word for it, there is no way to check". And also we lose some value add of being able to build peer-aware applications.

Unless there is some trust around the connection, having an endpoint that reports this info does not really make it trust-worthy (one can still say whatever if we hijack this request). I think this is an important concern in favor of TLS to the user application for this info (e.g. HBONE or MASQUE) so that the recipient can verify the other side is peer or ztunnel.

Assuming that user applications have to support MASQUE to get this info, we can still benefit from sandwiched tunnel as a protocol implementation (and private protocol to Envoy).

**Comment by linsun** [comment]
> > I think everyone agrees option 1 (ztunnel co-located w/ waypoint proxy in the same pod) is the simplest approach we should start with.
> 
> For short term or in general? I am not convinced its better than node

Sorry I meant for short term to start with. I agree that we need more discussion on if the node ztunnel is better approach. My main worry was not all nodes have ztunnel. I recall someone just put a PR in to opt in(or out) nodes for istio cni.

**Comment by howardjohn** [comment]
We can easily scope waypoints to only run on nodes with ztunnels.

Disabling ztunnel on specific nodes is a super advanced case that users
will need to be VERY careful of, since if they get it wrong they will get
broken pods.

**Comment by costinm** [comment]
Kuat: there are levels of security. With Sidecar - we do mTLS, but app must trust the injector and envoy, there is no way to verify envoy encrypted or not. With proxyless - the app doesn't trust envoy, but injector and control plane may still not enable encryption if XDS is used. 

At the same time, for many users IPSec/Wireguard/platform encryption is good enough - and they do not provide any signal that the connection is encrypted except the CIDR range for the encrypted netwrok/VPC.

Ambient/ztunnel are based on trusting the host - users who don't trust the host may use Sidecars to have the encryption in the pod, or have their native TLS in the app - but probably will only  get an illusion of extra security if the host is compromised. 

For a properly installed ztunnel - all nodes in the K8S node CIDR range will have ztunnel and provide an MDS server. If there is no MDS - probably ztunnel is missing so user may rely on other methods to detect if the VPC provides a different form of encryption ( IPSec, etc). And that may be fine for some workloads - not all customers and workloads are required
to use mTLS. 

When communicating outside of the k8s CIDR or VPC, for multi-cluster, etc - things are more complicated on detecting if low-level network security is enabled.  But I don't think we need to over-complicate ztunnel - users who must can still 
use sidecars.

**Comment by kyessenov** [comment]
We have no evidence to suggest that Envoy HBONE part is causing issues at the moment. So while it's an interesting concept to have a "sidecar-for-sidecar", I think it's a better use of resources to focus on a pure Envoy Waypoint implementation. Doing complicated designs (and inventing new protocols) around sandwiching with ztunnel is a premature optimization. Uniform HBONE use between sidecars, waypoints, and ztunnels is a massive advantage that we need to preserver in the interest of portability and architectural simplicity.

**Comment by SkyfireFrancisZ** [comment]
@ejj, please plan to communicate the decision to the Ambient WG at large.

**Comment by ejj** [comment]
Overall I agree with Kuat's comments, I think at this point is a premature optimization at the moment.  In particular, I agree that it is a very good think for Ambient Mesh in the long term, if Envoy has a solid HBONE implementation, this will make it easier for us to integrate with third party services outside of the mesh. All of that said, there's a bit of nuance here that I'd like to add.

In the experimental branch, the Envoy xDS for the waypoint was way too complicated for a number of reasons.  Why exactly is somewhat debated, but it seems to me to be due to a combination of complexity in the behavior of the waypoint, coupled with some inflexibility in the HBONE implementation.

Over the past couple of weeks, there's been a large shift in thinking about waypoint implementation sparked by [John's suggestion we use producer waypoints](https://docs.google.com/document/d/1QdpTl0y2snASOPo8GEKapuwDD-Mfoy2zz8hPVbgRexA/edit).  For the purposes of this document, the key effect of that proposal is a dramatic simplification in the Envoy xDS used by waypoints.   As a result of this simplification, it seems likely (though not yet proven) that the xDS will reach a size, complexity, and performance that's acceptable for alpha.

Given that context, in my opinion, I don't think we're quite ready to fully close this issue, but instead should deprioritize it.  It's certainly not a prerequisite for an alpha launch or upstreaming at this point.

To get to the point that we fully close the issue, I would like to see a couple of things happen:
- Producer waypoints are merged and we have a sense of how the xDS looks.
- Someone does an analysis that suggests what, if any, low hanging fruit there may be to improve that xDS further and how much work would be involved.
- Someone does an analysis that evaluates wether zTunnel sandwiching can credibly do a massively better job than those improvements on a reasonably timeline. 

In my opinion, before alpha, we should focus on getting producer waypoints merged and confirming that they're acceptable for the alpha release.   This bug should be re-opened but put on the backlog as a low priority item until that point. I highly suspect that we won't end up doing this for reasons stated above.

**Comment by louiscryan** [comment]
I'm fine with the above from @ejj 

I do think we need to continue to work on our interface with user-space. The gRPC team has expressed interest in interop with ztunnel for authn and since they implement their own authz they would like to extract identity from the network peer in a secure and reliable manner.

We clearly need HBONE In Envoy regardless because of sidecar but in the long run the sandwich may prove to be a more adaptable solution. This does not need to resolve for Alpha but we should be cognizant of any debt we accumulate that would make switching to a sandwich at a later point problematic. 

We should be able to benchmark both relatively easily so we should commit to doing that at a minimum.

**Comment by stevenctl** [comment]
FWIW this ended up being done in 

#49097 and https://github.com/istio/ztunnel/pull/789
