### ISSUE TITLE
permissions on docker images depend on umask of the person doing the build

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#4217]
when envoy is being copied around the permissions it ends up with in the docker image
depend on the umask of the user, if the umask is restrictive, it doesn't get world executable and then fails to start

we shouldn't rely on personal setting when creating the images; all executables should be 755 (owned by root or sys)

ditto for debian

found by @diemtvu

**Comment by ldemailly** [comment]
cc @jwendell

**Comment by diemtvu** [comment]
Some more context: This happens when I run e2e_pilot test, from my local (after build docker and updateVersion, then run command like `go test -v -timeout 20m ./tests/e2e/tests/pilot -hub=xxx -tag=yyy`

I've tried to change umask for the envoy binary under ~/go/out/linux_amd64/release, (as well as ~go/out/linux_amd64/release/docker_scratch/proxy, just in case), but it doesn't change anything. Umask for envoy on container still missing executable for all.

k exec a-597d8fd574-jmc29 -n istio-test-app-mnx75 -c istio-proxy -- ls -l /usr/local/bin

-rwxr-x--- 8 root root 251144560 Mar 12 21:39 envoy
-rwxr-x--- 7 root root  19611888 Mar 12 21:39 pilot-agent

**Comment by ldemailly** [comment]
A quick fix for that one issue is to add
RUN chmod 755 /usr/local/bin/envoy
in the Dockerfile for proxy*

There is probably some way to fix it more globally / must be a docker faq
