### ISSUE TITLE
Waypoint proxy upgrade plan

### ISSUE THREAD

**Issue by linsun** [istio/istio#42299]
**Describe the feature request**

We need a plan for waypoint proxy upgrade. Do we support both in place and revision based upgrade, similar as sidecars? Can we achieve no down time with which upgrade plan(s)?

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ x] Ambient
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by therealmitchconnors** [comment]
In addition to designing an upgrade process, we need to fix the existing code, which does not upgrade waypoints after they are created, because only their service account is reconciled, not the template.  https://github.com/istio/istio/blob/7563911813f1d446f33fed7fd1fdf1a51c315f8d/pilot/pkg/ambient/controller/waypoint_controller.go#L272

**Comment by howardjohn** [comment]
This is now implemented, waypoints will be updated if the injection template is changed. Doc is https://docs.google.com/document/d/1nQuf43sMvPyqNI8MKNTzi13pUn_WDqLULT55z5s2duY/edit#.

There may be followups, not 100% sure. If so @therealmitchconnors can you open a new issue?
