### ISSUE TITLE
Need a doc on what features of sidecars will not be in ambient sidecarless

### ISSUE THREAD

**Issue by linsun** [istio/istio#42298]
**Describe the feature request**

Need a doc to list all things in sidecars and which ones won't be in ambient, hopefully this is a very small list.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ x ] Ambient
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by costinm** [comment]
I don't think it can or should be a short list.

Almost all alpha features, ProxyConfig, MeshConfig, anything that assumes envoy or per-pod config is problematic.

I think we need the opposite - a very small list of initial features we support, mostly from the beta or stable API.

At least for L4 / ztunnel it should be as small as possible.

This is our opportunity to clean up the APIs that are rarely used or create problems, as well as all behaviors not compatible with k8s which create adoption pain.

**Comment by kyessenov** [comment]
@costinm I generally agree with you, but we have a choice to make: do we continue to support sidecars with the existing APIs indefinitely, or do we transition these API uses to the waypoint model?

**Comment by costinm** [comment]
On Sat, Dec 10, 2022 at 6:49 PM Kuat ***@***.***> wrote:

> @costinm <https://github.com/costinm> I generally agree with you, but we
> have a choice to make: do we continue to support sidecars with the existing
> APIs indefinitely, or do we transition these API uses to the waypoint model?
>
I don't think we have a choice here - we MUST continue to support sidecar
and the existing API for sidecars.
And we also most support the waypoint model. Just like we support K8S and
VMs or multiple
CAs.

It is not an exclusive choice - we hope 9x% of users workloads will be able
to move to the simpler,
more efficient - but also less flexible and less powerful ambient model.
But we know that some
workloads and sophisticated users may still need sidecars - not only for
backwards compat
but also for client overrides, client load balancing ( proxyless gRPC won't
have sidecar
but will act as if it had one), etc.

It would be very bad to drop the sidecars - it will mean all the use cases
that are perfectly fit for
sidecars ( and a bad fit for ambient ) will have to be forced into ambient,
destroying the main
benefits it has ( simple, performant, cheam, easy to manage ).

IMO the worst will be to attempt to make ambient support APIs and use cases
that are fit
to work with a sidecar. It might be possible (in theory), but would destroy
a lot of the value and
benefits of ambient.

A clean, simple, efficient API subset in ambient for 9x% of uses with the
super-flexible and broad
API for sidecars would be best for everyone.

**Comment by kyessenov** [comment]
Thanks for making the position clear.  Yes, as long as Ambient is an experiment and does not handle 100% use cases, sidecars must be fully supported. In my ideal, Waypoint implements GAMMA and default Istio policy/telemetry _only_ as an MVP.

**Comment by costinm** [comment]
I think Waypoint should implement at the very least GAMMA and default
policy -  plus any 'beta' or above API that fits the waypoint model and
doesn't require a high cost, i.e.
excluding 'client overrides' or APIs using workload selectors on the
destination. Large parts of DestinationRule and VirtualService are fine.

Ambient doesn't need to handle 100% of the use cases and API surface, or
try to be a one-size-fits-all solution ( with all the complexity and cost
that comes with that) - we already
have sidecars for that. Handling the 10% of the use API that is used by 9x%
of users/workloads - with lower cost, simpler, etc - would be absolutely
great
and allow us to move it to 'beta' and 'prod' level much faster.

For telemetry: it needs to be a subset ( server-only metrics for example ),
but we should also re-evaluate where we stand with other telemetry standards
like OTel as well as how to deal with the high-cardinality metrics. We
can't make any backwards incompatible changes to sidecars - but I think we
can
fix some of the big issues we found with ambient.

We are trying to get stats on the most common API usage patterns -  it will
also help focus the testing and productionisation.

**Comment by linsun** [comment]
@costinm @kyessenov thanks for sharing your thoughts. Note ambient supports both sidecar and sidecarless, and I agree that sidecars will continue to be around and can interop with sidecarless.  The goal of this doc is to give us & users good guidance of what feature won't be in ambient sidecarless so they should plan to use sidecars instead.

I agree with what Costin mentioned about "client overrides", those won't work with producer only waypoint.

I don't agree with supporting only 10% of the APIs today.  Certainly some of the APIs today may not be needed, such as Sidecar resource.  ProxyConfig may still be useful to confirm waypoint proxy, similar as EnvoyFilters. MeshConfig will be useful to configure istiod (e.g. ambientMode) at the minimum or even some data plane config options such as enable hbone.

**Comment by costinm** [comment]
It depends on how we define API. We have a HUGE API surface - from things specific to injection, install, etc - and a large number is not fully covered by tests.  I would be much happier with the 10% of this that is most commonly used - with a higher level of testing and confidence instead of 90% superficial support and at a high cost.  Since we are not removing
sidecars - there is not a lot of pressure or rationale to support arcane APIs and things that are better fit for a client-side 
proxy or rely on injection.

If we are talking about the 'beta or v1' API surface - I agree, we should attempt to support as much as possible, and
document very clearly the parts we don't support and why.  Sidecar, client overrides, VirtualService/DR in random namespaces - as well as the John's list of things that are not matching K8S behavior or has wrong behavior are candidates to not support. 

Since using ambient API is opt-in and we are not actually breaking anything ( sidecar is still available ) - we have an opportunity to fix the behaviors that prevent transparent adoption - with the goal to have ambient on by default 
in the entire cluster ( something very hard to do with sidecars ). 

I am only talking about v1 of ambient - in time we may obviously add more of the API surface as well as add more 
APIs. 

For an extreme example, we should be able to release ztunnel v1 with only the L4 authz policy we discussed and working with 1.16 - and nothing else. Small API surface will allow far more extensive testing and hopefully get us to a point where it is enabled by default for all namespaces - so we secure the entire cluster with no change in behavior ( we may need to discuss NetworkPolicy - verify it is not broken or implement it ). 

Since Waypoint are gateways, we are starting with a clear set of APIs that already works - instead of attempting to 
implement or support some of the APIs that have a high cost ( like client overrides, etc ), it may be better to start
with the smaller API surface for v1 - and keep focused on low overhead, very high scale, broad use, leaving the 
rarely used/expensive/hard-to-scale features and APIs for the sidecar.

**Comment by kyessenov** [comment]
@costinm I'd add that _not implementing_ some APIs would be considered a security violation: if waypoints can be opted-in by Istio for sidecarless workloads and not enforce L7 policy, that's a loop hole to bypass Istio L7 policy. We do need some clarity how we view waypoints - are they an alternative to sidecars in Istio (so must support out-of-the-box policy&auth), or are they a feature of ztunnels to apply new L7 policies (for which we can define a new APIs).

**Comment by costinm** [comment]
> @costinm I'd add that _not implementing_ some APIs would be considered a security violation: if waypoints can be opted-in by Istio for sidecarless workloads and not enforce L7 policy, that's a loop hole to bypass Istio L7 policy. We do need some clarity how we view waypoints - are they an alternative to sidecars in Istio (so must support out-of-the-box policy&auth), or are they a feature of ztunnels to apply new L7 policies (for which we can define a new APIs).

I think waypoints are a feature of ambient and implement ambient APIs, just like sidecars implement the full Istio API.

But I agree - security APIs (authz in particular) are top of the support list, and they are v1. 

That doesn't mean 'permissive' mode can be supported ( doesn't make sense with new protocol, which is mtls only). And the discussed changes on L4 only in absence of waypoints.

A workload may not use any Istio, may use sidecar or may use ambient, and this should be clear and opt in based on the label.

**Comment by kyessenov** [comment]
Has anyone started the doc on APIs for Waypoint already? This has huge implications given [the current waypoint xDS is not scalable](https://github.com/istio/istio/issues/42308). Overly complicated xDS results in poor-performing Envoy and operational complexity, both are public points of criticism of the Istio project. I think we should seriously attempt to reduce complexity in xDS by designing the Waypoint  API support carefully with the goal of simpler translation to xDS.

**Comment by howardjohn** [comment]
I am working on a doc for ^

**Comment by linsun** [comment]
@kyessenov are you referring to internal APIs from istiod to waypoint proxy?  @howardjohn - is this the doc you are working on? Just to avoid duplicated effort.

**Comment by kyessenov** [comment]
@linsun The internal APIs are regular xDS, no?  I was referring to the high level APIs. The current approach of combining sidecar xDS into one big xDS to preserve the exact semantics is explosive which is a scalability risk.

**Comment by linsun** [comment]
@kyessenov I'm confused. For high level APIs, we have Istio's existing APIs which we can take a subset and say which ones are supported for waypoint. We also have GAMMA.

Do we need another high level APIs?

**Comment by kyessenov** [comment]
@linsun You're exactly right. By new APIs I'm referring to GAMMA and defining a subset of existing APIs that work well for Waypoints. I'm definitely not asking for yet another set of user APIs.

I'm not worried about GAMMA. Envoy gateway implements it, so we know it'll work for Waypoints by just slapping encap/decap listeners for HBONE.

I'm worried about DestinationRule, EnvoyFilter, Wasm, Telemetry, and Authn/z. The last two seem like table-stakes so we should focus on those. Telemetry is still de-facto alpha so we have a lot of leeway, but authz is de-facto stable. 

One specific issue with authz is destination workload selectors. Because multiple pods share the same waypoint, an authz policy may discriminate against pods within an upstream pool. That's a core reason for chaining two HTTP passes in Waypoint (doubling the latency and handicapping Envoy). This is described in #42497 . One approach is to say, we don't allow that and apply authz policies uniformly per upstream pool. 

It's not clear to me why one would want subsets to have non-uniform authz (a client would be forced to retry until it finds an endpoint that works, so the policy doesn't really achieve much), but our sidecar authz API allows that. I'm proposing we don't include this feature into Waypoint version of authz.

**Comment by howardjohn** [comment]
> a client would be forced to retry until it finds an endpoint that works, so the policy doesn't really achieve much

A much more common case, I suspect, is having multiple different services which have different policies. Rather than 1 service selecting multiple pods with different policies

**Comment by SkyfireFrancisZ** [comment]
Lin and John plan to merge what they have, and present to the community ETA 1/11.

**Comment by SkyfireFrancisZ** [comment]
Doc needed by Wed 1/11 Ambient WG meeting

**Comment by costinm** [comment]
Agree that having a policy depend on which endpoint is selected is not a
good fit and very unlikely to be acceptable for other Gamma vendors. It is
a model well suited for sidecars, but it's unreasonable to expect a
different topology - which by design attempts to optimize - must be
required to implement an API designed for a very different topology.

We made this mistake when moving from the access-log style telemetry in
mixer to prometheus style - first works for high cardinality, later
doesn't.

**Comment by SkyfireFrancisZ** [comment]
https://docs.google.com/document/d/1Lk1I1qB-XwVWFP0sVcIN5JMJZHjuF3j8lGWtUeDK6pY/edit#heading=h.nluvz4y67j4c

**Comment by SkyfireFrancisZ** [comment]
addressing comments

**Comment by SkyfireFrancisZ** [comment]
Justin will follow up with John wrt these open topics:
- How to model Istio L4 network policy authz
- L7 network policy semantics

**Comment by SkyfireFrancisZ** [comment]
still in progress.

**Comment by keithmattix** [comment]
Feels like the doc exists in the form of [Ambient APIs](https://docs.google.com/document/d/1Lk1I1qB-XwVWFP0sVcIN5JMJZHjuF3j8lGWtUeDK6pY/edit#) doc. Can we close this or do we need another, clearer form for this info?

**Comment by linsun** [comment]
Close this for now, and  we should open individual docs for gaps.
