### ISSUE TITLE
Support Wasm for waypoint proxy

### ISSUE THREAD

**Issue by linsun** [istio/istio#42337]
Today sidecars have Istio WasmPlugin resource to deploy user extension to the sidecars. Users will need similar extension for them using Wasm for waypoint proxy.

Note: Wasm support would *NOT* be considered for ztunnel

**Comment by zirain** [comment]
`Istio WasmDeployment` do you mean `WasmPlugin`?

**Comment by kyessenov** [comment]
I think the only work here is to support binding of WasmPlugin to waypoints in xDS generator (don't even think we need extra API).

@linsun What additional work are you thinking of?

**Comment by linsun** [comment]
> > `Istio WasmDeployment`
> 
> do you mean `WasmPlugin`?

Yes WasmPlugin resource, sorry about the name confusion, i have updated the desp.

**Comment by linsun** [comment]
@kyessenov yep, i suspect there are work related to xDS generation for waypoint related to WasmPlugin, plus create some testing for it.

**Comment by YachikaRalhan** [comment]
Hey @linsun, I would like to contribute here, can you please provide me with some more details if you have or any entry point from where I can start

**Comment by linsun** [comment]
Thanks @YachikaRalhan!!

**Comment by GregHanson** [comment]
cc @Kaushal28

**Comment by Kaushal28** [comment]
Hey @linsun, I was working on this issue and found that Wasm plugins are working as expected in ambient mode with waypoint proxy. As mentioned in [#42223](https://github.com/istio/istio/issues/42223) the only difference is in the `matchLabels`. To configure Wasm plugin for sample `helloworld` service, we need to use the following `matchLabels` selector:

``` yaml
selector:
    matchLabels:
      istio.io/gateway-name: helloworld   # this selector is different from corresponding sidecar config.
```
Because `istio.io/gateway-name=helloworld` is one of the labels of the waypoint pod.

I verified working of Wasm plugin on my local by the following means:

1. `ECDS` configuration request and response are flowing from Envoy <-> XDS Proxy <-> Istiod when Wasm plugin is created/deleted. Following are `istiod` logs when Wasm plugin is newly created:

```
2023-02-22T05:54:11.646097Z	info	ads	Push debounce stable[23] 1 for config WasmPlugin/default/rl: 100.239529ms since last change, 100.23927ms since last push, full=true
2023-02-22T05:54:11.646366Z	info	ads	XDS: Pushing:2023-02-22T05:54:11Z/22 Services:10 ConnectedEndpoints:5 Version:2023-02-22T05:54:11Z/22
2023-02-22T05:54:11.646718Z	info	delta	LDS: PUSH for node:istio-ingressgateway-6bb4777888-stk8l.istio-system resources:1 removed:0 size:515B
2023-02-22T05:54:11.648446Z	info	ads	LDS: PUSH for node:helloworld-istio-waypoint-9fbbc57fd-r845g.default resources:4 size:12.4kB
2023-02-22T05:54:11.655478Z	info	ads	ECDS: PUSH request for node:helloworld-istio-waypoint-9fbbc57fd-r845g.default resources:1 size:238B

```

2. I also verified the listener's config_dump for `helloworld` waypoint after creation and deletion of Wasm plugin using `istioctl pc listener deploy/helloworld-istio-waypoint -o json`. When Wasm plugin is newly created, I was able to view corresponding HTTP filters. These filters also get removed when Wasm plugin is deleted.

```json
...
{
    "name": "default.rl",
    "configDiscovery": {
        "configSource": {
            "ads": {},
            "initialFetchTimeout": "0s",
            "resourceApiVersion": "V3"
        },
        "typeUrls": [
            "type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm",
            "type.googleapis.com/envoy.extensions.filters.http.rbac.v3.RBAC"
        ]
    }
}
...
```

I also tried to verify the behaviour of Wasm plugin in the latest `master` branch but because of this existing issue mentioned in [this slack thread](https://istio.slack.com/archives/C049TCZMPCP/p1677003981699369), I am not able to make requests between pods when waypoint is deployed for them (getting `no healthy upstream`). But I think it should also work as all the configurations are now correct.

Ss I believe no code change is required for this issue. Let me know if I am missing anything here. Thanks!

**Comment by Kaushal28** [comment]
I have now also verified the behaviour of the sample Wasm plugin in a new namespace (in default namespace, I was getting `no healthy upstream` as mentioned on the above comment. Refer: #43544). The plugin is working correctly as expected. Let me know if any further verification/changes are required on this issue.

**Comment by Kaushal28** [comment]
Hey @linsun, Could you please review my findings above? Any suggestions/feedback would be really helpful. Thanks.

**Comment by linsun** [comment]
Sorry about the delay in replying! I think your analysis makes sense to me, and there is a sematics change in WasmPlugin resource to bind to the waypoint, similar as L7 Authz policy.

If there is no test - could you add some tests for this?

cc @kyessenov for any input?

**Comment by jcchavezs** [comment]
What is the status on this? Will this remain closed due to inactivity?

**Comment by linsun** [comment]
Reopen - Think this is still an issue

**Comment by linsun** [comment]
For reference, earlier testing discovered https://github.com/istio/istio/issues/47227, which @howardjohn fixed.

**Comment by linsun** [comment]
@Kaushal28 are you planning to add some tests for this if you are still working on this?

**Comment by kfaseela** [comment]
@Kaushal28 is it okay if I assign this to someone else who is ready to do the integration tests? Let me know if you are still working on this

**Comment by adilmp1** [comment]
@linsun I'm ready to work on this and will review the test coverage.

**Comment by kfaseela** [comment]
@adilmp1 I have assigned the issue to you

**Comment by adilmp1** [comment]
#51014

**Comment by adilmp1** [comment]
https://github.com/istio/istio/issues/51014

**Comment by adilmp1** [comment]
[Service specific Wasmplugin does not work in ambient mode #51014](https://github.com/istio/istio/issues/51014)

**Comment by adilmp1** [comment]
Service specific Wasmplugin does not work in ambient mode #51014

**Comment by adilmp1** [comment]
Service specific Wasmplugin does not work in ambient mode #51014

**Comment by kfaseela** [comment]
Hello Lin, @adilmp1 has added required documentation and integration tests for this task. Most of the things work, except the case of service specific wasmplugin with imageSecrets. https://github.com/istio/istio/issues/51288 has been created to track this, @howardjohn thinks it is not straight forward to fix. Shall we now close this issue and track the pending issue alone?
