### ISSUE TITLE
 Upgrade from 1.9.8 to 1.10.4 fails on Windows 

### ISSUE THREAD

**Issue by Anoojak** [istio/istio#42523]
### Bug Description

Attempting to upgrade from 1.9.8 to 1.10.4 on Windows by running istioctl upgrade yields to following error output:

Error: failed to generate Istio configs from file [dev.yaml] for the current version: 1.9.4, error: opening tar archive for reading: wrapping file reader: gzip: invalid header 

Error: failed to generate Istio configs from file [] for the current version: 1.9.8, error: opening tar archive for reading: wrapping file reader: gzip: invalid header

Can you please work on this issue on priority as it is blocked our upgradation

### Version

```prose
kubectl version --short
Client Version: v1.21.0
Server Version: v1.21.14-eks-fb459a0
istioctl version
1.9.4
```

**Comment by ericvn** [comment]
Istio 1.10 has long been out of support and looking at the upgrade code in the 1.10 release it been changed a lot (such that if the problem was recreated in the current supported releases, I don't know that a cherry-pick would be simple (automatic would fail)).

I don't have a Windows machine to try the current version, but that would be something to verify. As noted in the other issue, this could just be trying to untag a zip file failing, and the code may need to be updated on Windows.

**Comment by howardjohn** [comment]
Even if we found the issue we wouldn't fix it since it's EOL. I would recommend upgrading from a different machine
