### ISSUE TITLE
add tests to verify optimized images

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#426]
while testing for perf and building from source I noticed that using
bazel build -c opt  for mixer and proxy gives 2x the throughput so we should probably do that
(and more tweaks as needed) for released builds (yet not strip symbols so debugging isn't impossible)

see also https://github.com/istio/istio/pull/403

**Comment by sakshigoel12** [comment]
Figuring it out is P0 to 0.2 

Focus: TBD

**Comment by ldemailly** [comment]
Email thread: https://groups.google.com/forum/#!topic/istio-core/M9Yn3BvrpBw

**Comment by sebastienvas** [comment]
I ll enable the possibility of creating optimized build on auth, pilot and mixer. We'll start by using debug and we ll move to optimized as we get stable.

**Comment by sebastienvas** [comment]
cc @rvkubiak

**Comment by ldemailly** [comment]
it would be really good to produce both set of images (for perf testing for instance even if not released)

**Comment by sebastienvas** [comment]
This require a lot of changes as we need a way to use different names for each set of images, and also update kube-inject to know which image to pick. in the meantime, for perf testing, user can build their own image and push them to their own registry.

**Comment by ayj** [comment]
kube-inject changes possibly addressed by issue https://github.com/istio/pilot/issues/1062

**Comment by ldemailly** [comment]
the highest priority are:
- [ ] proxy images as that's where most of the performance gain is (c++ opt)
- [ ] istioctl kube-inject (and the new auto inject) - so pilot - have a way to select the proxy image such as the default `istioctl kube-inject` does either proxy_debug or proxy_opt depending if itself is a opt or debug release

**Comment by sebastienvas** [comment]
proxy is already -c opt , and proxy_debug is -c deb as defined https://github.com/istio/proxy/blob/master/tools/bazel.rc#L49.

I am not sure who is doing item 2 - So assigning this to Laurent

**Comment by ldemailly** [comment]
I see
```
build:release -c opt
```
so assuming :release is what we use for the proxy image, yes, it's done but where is the -c dbg part ?


also, are we deciding the images will all be `foo` and `foo_debug` ? Consistently?

**Comment by sebastienvas** [comment]
https://github.com/istio/proxy/blob/master/script/release-binary#L51

**Comment by Brian-Xincheng-Zhang** [comment]
I think this is not gating .2 release. If engprod has other important things to work on, then this can be de-prioritized. 
We probably should limit # of P0 requests from each dev eng to EngProd, so that EngProd team can serve all dev engs fairly.

**Comment by linsun** [comment]
moving to 0.3, not a stop ship for 0.2

**Comment by ldemailly** [comment]
for the record I did the code in kube-inject to switch between debug and opt images in istioctl kube-inject https://github.com/istio/pilot/pull/1202

**Comment by mattdelco** [comment]
Is there anything in particular that needs to be done to further (or properly) optimize the images?  I don' t think I could look back at the bazel build for ideas because during a release build it wasn't uncommon to see bazel complain about not recognizing "opt" (since it hadn't been proper configured/defined in all of the repos).

Stated differently, is the main task left to provide an option for a debug vs. release istio build?  Things might be a little confusing for docker images that already provide a debug image but afaik the debug images differ in ways that aren't related to how go was told to build.

There could also be some messiness with how some automated or test processes (unrelated to a release build) push to istio-artifacts based on the commit sha.  If care isn't taken then debug and release images could push to the same hub & tag.

**Comment by ayj** [comment]
@ldemailly - is this issue still valid?

**Comment by ldemailly** [comment]
Yes with the build changes we still have to verify that we indeed have correct debug vs perf/prod oriented images, lately there has been a push to add more stuff to the prod images
