### ISSUE TITLE
Istio-ingress performance regression on build istio-0.7.0-pre20180313-17-58

### ISSUE THREAD

**Issue by jnativio** [istio/istio#4266]
The regression patrol detected a big drop in throughput with latest build (0.7.0-pre20180313-17-58). Results can be seen here --> http://ibmcloud-perf.istio.io/regpatrol/0.7.0-pre20180313-17-58/
It seems that the Ingress component is responsible for the performance drop. It used way more CPU than in previous builds and saturated the worker where it is running. I tried with the Ingress image of previous build and that did not happen.

Kube version:
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.3-2+9b8d20508e1aa2", GitCommit:"9b8d20508e1aa2616fac62922b4ba0a166248dce", GitTreeState:"clean", BuildDate:"2018-02-21T08:10:11Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

**Comment by kyessenov** [comment]
I have suspicion this is related to @costinm 's change - can you validate that EDS server is not DoSing the proxy here.

**Comment by kidiyoor** [comment]
@jnativio cannot reach - http://ibmcloud-perf.istio.io/regpatrol/0.7.0-pre20180313-17-58

**Comment by jnativio** [comment]
@kidiyoor  Pls try a different browser.

**Comment by PiotrSikora** [comment]
@rkpagadala @hklai it looks that we started shipping debug version of Istio Proxy:

```
$ curl https://storage.googleapis.com/istio-prerelease/daily-build/0.7.0-pre20180309-09-15-15/docker/proxy.tar.gz | docker load
$ docker run --rm -it --entrypoint /usr/local/bin/envoy istio/proxy:0.7.0-pre20180309-09-15-15 --version

/usr/local/bin/envoy  version: 0/1.6.0-dev//RELEASE
```

```
curl https://storage.googleapis.com/istio-prerelease/daily-build/0.7.0-pre20180313-17-58/docker/proxy.tar.gz | docker load
$ docker run --rm -it --entrypoint /usr/local/bin/envoy istio/proxy:0.7.0-pre20180313-17-58 --version

/usr/local/bin/envoy  version: 0/1.6.0-dev//DEBUG
```

I suspect that https://github.com/istio/istio/commit/3988402a2c7a1c6aa94407d71fa227581662271a broke this, but I don't see anything obviously wrong there.

Also, it's worth noting that revisions listed in manifests [[1]] [[2]] used for daily builds are completely bogus and have no relation to those in `istio.deps`. Is there any reason why correct revisions are not extracted from `istio.deps`? This will backfire sooner rather than later.

[1]: https://storage.googleapis.com/istio-prerelease/daily-build/0.7.0-pre20180309-09-15-15/manifest.xml
[2]: https://storage.googleapis.com/istio-prerelease/daily-build/0.7.0-pre20180313-17-58/manifest.xml

**Comment by rkpagadala** [comment]
@PiotrSikora Working on this.

**Comment by ldemailly** [comment]
subscribe

**Comment by hklai** [comment]
@rkpagadala  should have a fix soon.

And we will be adding tests to release qualification to prevent problems like this going forward.
