### ISSUE TITLE
xds: control plane should auto-detect Envoy extensions

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#42748]
Google and other vendors have proprietary builds of Envoy that can be used in-place of the OSS build. These builds may miss some Istio extensions (stats or authn) and/or Envoy contrib extensions. 

Istio control plane only uses the version string to enable/disable Envoy extensions. This is rudimentary since a single missing extension breaks the entire configuration update. It would be better if Istio would omit optional features from xDS (e.g. stats) but continue making progress on xDS updates, with appropriate warnings about the missing functionality. Envoy supplies a manifest of included extensions in the node info that is sufficient for auto-detection.

cc @ramaraochavali

**Comment by howardjohn** [comment]
Makes sense, but one concern is dropping something like authz, etc transparently. Maybe the client can allowlist some extensions it is ok missing, or something a bit more automatic to achieve the same goal?

**Comment by kyessenov** [comment]
You mean the server? Yes, I think the server should have a list of a few mandatory extensions (like RBAC) and then provide a good error message if the client doesn't have any one of them.  For others, features should be auto-disabled.  EnvoyFilter will be a difficult one to handle.

**Comment by hzxuzhonghu** [comment]
For OSS, I think we should only have one envoy build. Supporting customization is too complex, users could also develop their own extensions, not to mention the big number of extensions.

**Comment by kyessenov** [comment]
@hzxuzhonghu Are you suggesting that vendors must also fork the control plane to support custom envoy builds? I think that's what's currently happening but OSS could do better to minimize the forking necessary.

**Comment by hzxuzhonghu** [comment]
>Are you suggesting that vendors must also fork the control plane to support custom envoy builds?

Yes, I think so unless envoy can natively  report what it supports.

**Comment by howardjohn** [comment]
Envoy already reports it in the xds request

**Comment by hzxuzhonghu** [comment]
Node.Extensions right? It looks great, so we can respect this value instead of redesign in pilot-agent

**Comment by costinm** [comment]
It doesn't look so great - it's a lot of data to send/parse on each connection at startup, all of it wasted since no sane install will have some mix of envoys builds besides version.

A build ID is more than sufficient - it can be "1.15-redhat", and we can make the 'enable filter if version match' to be more flexible and be customisable - but I don't think as a design the envoy reporting full list of filters on every single connection
is best.  

The other approach would be for envoy to ignore filters it doesn't support and report back in the NACK what was ignored. There is no difference I see between Istio ignoring the filters if envoy reports they are not supported and envoy doing the same. John's concern - auth-related filter missing - can still be addressed with an extra step, of processing the NACK and pushing a different config that disables that specific route/listener/filter, i.e. same code we would need if we got the list of filters on each connection and found auth missing. But that's also unnecessary complicated in practice - we add too much complexity for 'what if a meteor will fall'.

**Comment by howardjohn** [comment]
I generally agree it was a bit problematic to include it in Envoy, since the list is massive. Given its already there though, and we already parse it (via protobuf), I don't mind using it much? 

Envoy supporting a bool `ignoreIfNotPresent` as you mentioned would also work (although you could argue that is also inefficient, since we need to push a filter that is ignored). Although I am not sure about the NACKing part - if its ignored why do we need to do? Processing NACKs would be complex IMO.

> You mean the server?

I actually did mean the client... but maybe that is niche. I was thinking of a particular case where we have someone using Envoy without metadata exchange and authn, but they also know that they are using Istio APIs in a way those don't matter. I agree server would probably be more common case.

**Comment by kyessenov** [comment]
@costinm As John says, we already parse it because Golang doesn't allow skipping fields during parsing AFAIR. The delta is a lookup in the proto  Extensions array for the known extension names.

This is a request from Google CloudESF that adds several OSS modules to each ASM version. I confirmed they only support gateways, so no mixing 

Vendor-specific Build ID is pushing complexity to the vendors. We still have to add a bunch of OSS flags like `PILOT_ENABLE_METADATA_EXCHANGE` for each extension (istio_alpn, postgres, istio_authn, etc), and then vendors need to properly configure their build. We also have to do condition with  `IstioVersionGt16` xDS generation, which can be done instead with a more systematic `EnvoyHasExtension`.

**Comment by howardjohn** [comment]
https://github.com/envoyproxy/envoy/blob/fe0d55e71f82726b130dde9d5747dbc69a3614ed/api/envoy/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#L1094 is_optional already exists fwiw

**Comment by hzxuzhonghu** [comment]
Yes, it also exists in `FilterConfig`, looks we donot use it
