### ISSUE TITLE
istio-operator doesn't honour the istio version defined in IstioOperator

### ISSUE THREAD

**Issue by qudongfang** [istio/istio#43071]
### Bug Description

I want to upgrade `istio-operator` version(both the image tag and helm chart) and keep the Istio on the `version/tag` defined in the `IstioOperator`.

I ran into an issue with `istio-sidecar-injector` got _**updated unexpectedly**_.

1. we're using `istio-operator` to manage the istio deployment, and we're on `1.14.x` at the moment
2. first step of upgrading, I upgraded the `istio-operator` and its helm chart version to `1.15.4` without changing the `IstioOperator`(step by step)
3. and then I found that the `configmaps/istio-sidecar-injector` changed to the content of `charts/istio-control/istio-discovery`  version `1.15.4`

### Version

```prose
➜  ~ istioctl version
client version: 1.16.0
control plane version: 1.14.3
data plane version: 1.14.0 (9 proxies), 1.14.3 (152 proxies)
➜  ~ kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.25.4
Kustomize Version: v4.5.7
Server Version: v1.23.14-eks-ffeb93d
WARNING: version difference between client (1.25) and server (1.23) exceeds the supported minor version skew of +/-1
```
```


### Additional Information

_No response_

**Comment by howardjohn** [comment]
The operator and istiod version are tightly coupled, it's not like most other operators. One of the many reasons why the operator is not recommended

**Comment by qudongfang** [comment]
> The operator and istiod version are tightly coupled, it's not like most other operators. One of the many reasons why the operator is not recommended

Thanks for the information @howardjohn.

Can we migrate to helm charts without breaking stuff since we're already on the istio-operator? Any suggestions?

**Comment by johnmanjiro13** [comment]
I migrated from istio-operator to helm with a below process. But I'm not sure if this is officially correct.
Below, istio-operator is a pod of the controller and IstioOperator is custom resources defined as `kind: IstioOperator`.

1. Prepare values.yaml files for istio helm charts (istio-base and istiod or more).
  a. These values.yaml files depend on the IstioOperator's setting.
  b. istio-operator uses helm charts inside.
2. Reduce replicas of istio-operator to 0.
  a. This operation stops istio-operator's reconcillation.
  b. We can delete IstioOperators without deleting related resources (e.g. istiod) but we'll do later.
3. Add a label and annotations to resources which already exist for helm to recognize them.
  a. label `app.kubernetes.io/managed-by=Helm`.
  b. annotate `meta.helm.sh/release-name=<release_name>` and `meta.helm.sh/release-namespace=<release_namespace>`.
  c. We must identify which resources are included in which chart.
4. Run `helm install`
5. Delete IstioOperator resources.
  a. We need to delete `finalizers` from them because of no istio-operator.
  b. Check no resources related to istio are deleted.
7. Run `istioctl operator remove`
  a. Removing resources related to istio-operator.
