### ISSUE TITLE
Waypoint: missing XFCC

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#43186]
On HTTP requests through a waypoint, we are missing the XFCC header. Both the inbound-pod and inbound-vip HCMs have the config to forward it

**Comment by kyessenov** [comment]
Do you mean at tunnel level or application level? I think it's costly to inject at the tunnel level since L7 proxies will have to create two upstream connections for two downstreams, severely reducing the pooling efficiency.

Is this again an issue caused by the identity delegation (server ztunnel cannot tell the original source principal)?

**Comment by kyessenov** [comment]
Limitations of "tunnel metadata" architecture are documented for https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/other_features/ip_transparency.html#proxy-protocol,  the problem is the same.

**Comment by howardjohn** [comment]
This is application level, at tunnel level I think we have XFCC (not certain, maybe not). We may not actually want that (per https://github.com/istio/api/pull/2240 and discussion we had), but we should probably be explicit about that.

**Comment by kyessenov** [comment]
I'd start by documenting what XFCC is for in Istio. I don't even recall when we started sending it for sidecars, so like any other "accidental" feature, we have to respect its existence.
