### ISSUE TITLE
Istio-base helm chart does not apply CRDs with correct app, chart, and release labels

### ISSUE THREAD

**Issue by EmmanuelVissuzaine** [istio/istio#43204]
### Bug Description

Hi,

Deploying istio/base chart via Helm (with base.enableCRDTemplates set to "true") make CRDs be applied by following manifests :
https://github.com/istio/istio/blob/master/manifests/charts/base/crds/

Issue is that when you want to redeploy those CRDs (when some of them have new features, in my case EnvoyFilter getting "priority" spec, included in istiod since 1.14) via Helm, I got an error saying that they don't belong to my release, because not having correct keys:

`Error: rendered manifests contain a resource that already exists. Unable to continue with update: CustomResourceDefinition "wasmplugins.extensions.istio.io" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "istio-base"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "istio-system"`

The only one solution I found was to delete each CRD by hand, in order to be able to redeploy them and get the latest versions.

Please change/add missing and wrong keys in order to be able to manage them with the istio/base chart as expected.

### Version

```prose
$ kubectl version --short
Client Version: v1.21.2
Server Version: v1.23.14-gke.401

$ helm version --short
v3.5.4
```

**Comment by EmmanuelVissuzaine** [comment]
Seems to be linked to previous installation of istio-pilot that modified annotations.

**Comment by bleggett** [comment]
Removing CRDs by hand is the documented flow ATM: https://istio.io/latest/docs/setup/install/helm/#optional-deleting-crds-installed-by-istio

This is because we explicitly add a [`"helm.sh/resource-policy": keep`](https://helm.sh/docs/howto/charts_tips_and_tricks/#tell-helm-not-to-uninstall-a-resource) tag to every CRD, so they will not be removed, because removing CRDs is potentially risky/tricky.

There is [no support for upgrading CRDs automatically via Helm](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#some-caveats-and-explanations), at this time.

So for now, manual CRD deletion is documented approach.

**Comment by linsun** [comment]
Note: Helm doesn't officially support CRD update: :-(

https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#some-caveats-and-explanations

**Comment by bleggett** [comment]
If we want to manually do our own CRD upgrades (because we are manintaining local conventions for Istio that make it safe for us to do so specifically, when it is not generically safe for Helm to do so) we need to properly do "Method 2" here: https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-2-separate-charts


1. Template all Istio CRDs as regular Helm resources (effectively always do `enableCRDTemplates`) in `base`
2. Drop `helm.sh/resource-policy: keep` (it's pointless if we have a separate CRD chart and are self-managing)
3. Properly apply the same labels/annotations to the CRD resources that we do to other Helm resources already.

**Comment by cb-troydai** [comment]
For most users, the `base.enableCRDTemplates` is not a well known settings. So when they deploy Istio through helm for the first them, they do so following the official document. The official document doesn't set that flag. Without the flag the CRD is still deployed, but without the annotations that mark the CRDs with corresponding helm release name, namespace, and managed-by label.

Contrarily, if the user install the Istio through helm with this `base.enableCRDTemplates` set to `true` from the very beginning, this is not going to be a problem. That is because helm will manage the resources rendered in template. The future upgrade will succeed.

**Comment by bleggett** [comment]
> For most users, the `base.enableCRDTemplates` is not a well known settings. So when they deploy Istio through helm for the first time, they do so following the official document. The official document doesn't set that flag. Without the flag the CRD is still deployed, but without the annotations that mark the CRDs with corresponding helm release name, namespace, and managed-by label.


Yes, that's why we should always template and drop `helm.sh/resource-policy: keep` - it's what prevents CRDs from being properly annotated here.

**Comment by linsun** [comment]
> If we want to manually do our own CRD upgrades/"self-manage" CRD upgrades (because we are manintaining local conventions for Istio that make it safe for us to do so specifically, when it is not generically safe for Helm to do so) we need to properly do "Method 2" here: https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-2-separate-charts
> 
>     1. Template all Istio CRDs as regular Helm resources (effectively always do `enableCRDTemplates` and remove it as an option) in `base`
> 
>     2. Drop `helm.sh/resource-policy: keep` (it's pointless if we have a separate CRD chart and are self-managing)
> 
>     3. Properly apply the same labels/annotations to the CRD resources [that we do to other Helm-managed resources already](https://github.com/istio/istio/pull/52463).

Update from today's meeting where @bleggett brought up the topic. The team is good with 1 and 3. For 2, we prefer to keep it so that CRDs don't get accidentally removed during uninstall of the base.

cc @cb-troydai

**Comment by linsun** [comment]
Hi @bleggett assign to you since you mentioned earlier you'd be interested... let me know if not :) Thanks!

**Comment by bakayolo** [comment]
If you get this error while upgrading Istio like me (with terraform helm_release)

```
#!/bin/bash

# Variables
RELEASE_NAME="istio-base"
RELEASE_NAMESPACE="istio-system"

# List of CRDs
CRDS=(
  "authorizationpolicies.security.istio.io"
  "destinationrules.networking.istio.io"
  "envoyfilters.networking.istio.io"
  "gateways.networking.istio.io"
  "istiooperators.install.istio.io"
  "peerauthentications.security.istio.io"
  "proxyconfigs.networking.istio.io"
  "requestauthentications.security.istio.io"
  "serviceentries.networking.istio.io"
  "sidecars.networking.istio.io"
  "telemetries.telemetry.istio.io"
  "virtualservices.networking.istio.io"
  "wasmplugins.extensions.istio.io"
  "workloadentries.networking.istio.io"
  "workloadgroups.networking.istio.io"
)

# Patch each CRD
for CRD in "${CRDS[@]}"; do
  echo "Patching $CRD..."
  kubectl patch crd "$CRD" -p "{\"metadata\":{\"labels\":{\"app.kubernetes.io/managed-by\":\"Helm\"},\"annotations\":{\"meta.helm.sh/release-name\":\"$RELEASE_NAME\",\"meta.helm.sh/release-namespace\":\"$RELEASE_NAMESPACE\"}}}"
done

echo "All CRDs patched successfully!"
```

Then re-plan-apply.

**Comment by bleggett** [comment]
> If you get this error while upgrading Istio like me (with terraform helm_release)
> 
> ```
> #!/bin/bash
> 
> # Variables
> RELEASE_NAME="istio-base"
> RELEASE_NAMESPACE="istio-system"
> 
> # List of CRDs
> CRDS=(
>   "authorizationpolicies.security.istio.io"
>   "destinationrules.networking.istio.io"
>   "envoyfilters.networking.istio.io"
>   "gateways.networking.istio.io"
>   "istiooperators.install.istio.io"
>   "peerauthentications.security.istio.io"
>   "proxyconfigs.networking.istio.io"
>   "requestauthentications.security.istio.io"
>   "serviceentries.networking.istio.io"
>   "sidecars.networking.istio.io"
>   "telemetries.telemetry.istio.io"
>   "virtualservices.networking.istio.io"
>   "wasmplugins.extensions.istio.io"
>   "workloadentries.networking.istio.io"
>   "workloadgroups.networking.istio.io"
> )
> 
> # Patch each CRD
> for CRD in "${CRDS[@]}"; do
>   echo "Patching $CRD..."
>   kubectl patch crd "$CRD" -p "{\"metadata\":{\"labels\":{\"app.kubernetes.io/managed-by\":\"Helm\"},\"annotations\":{\"meta.helm.sh/release-name\":\"$RELEASE_NAME\",\"meta.helm.sh/release-namespace\":\"$RELEASE_NAMESPACE\"}}}"
> done
> 
> echo "All CRDs patched successfully!"
> ```
> 
> Then re-plan-apply.

We have a similar snippet in our [Helm upgrade docs](https://istio.io/latest/docs/setup/upgrade/helm/#canary-upgrade-recommended) now.
