### ISSUE TITLE
the rule has no usefulness when its service is accessed by other service which has no istio sidecar?

### ISSUE THREAD

**Issue by tanshungang** [istio/istio#4322]

**Comment by xiaolanz** [comment]
Can you clarify the question?

**Comment by tanshungang** [comment]
For example, I have set a http-fault routerule for the server “details”, and its fault http status code is 503. And then, I call its api from my VM, curl http://****/details/0, and details responses a right information, its response-code is 200, I think it should be 503 but not 200.  But when i call it from pod like 'productpage-**', its response-code is 503, it is right.

**Comment by ZackButcher** [comment]
This is due to how Istio implements these style behaviors: HTTP fault injection is performed by the client side Envoy, since it's untenable for the server side Envoys to know the fault settings of every single caller (it's much more tractable for the client to know the fault setting of all of the services it's calling). Unfortunately we won't be able to fix this.
