### ISSUE TITLE
 Original source ip address of client

### ISSUE THREAD

**Issue by triptesh1212** [istio/istio#43397]
### Bug Description

We are trying to understand this behavior of "preserving the original source ip address of client".

We have referred the following wiki:
https://istio.io/latest/docs/tasks/security/authorization/authz-ingress/#source-ip-address-of-the-original-client

We have the following test setup:

(1) one kubernetes cluster having two nodes node1 and node2

(2) istio ingress-gateway pod running on node1

(3) httpbin pod running on node2

(4) gateway and virtual-service has been created to route traffic from istio-ingressgateway service to httpbin pod

We have the following flow :

    external traffic -> istio ingress-gateway service (load balancer) -> istio ingress-gateway pod -> httpbin service -> httpbin pod

We have been testing with Azure and GCP (Network Load Balancer)

We have set externalTrafficPolicy to local

We are firing the following call :

    curl --connect-to httpbin.example.com:80:<istio_ingress_gateway_external_ip>:80 http://httpbin.example.com/get?show_env=1

Now from the response, we are getting "X-Forwarded-For" header which contains the source ip address (which is different from node ip address)

We have the following queries:

(1) According to ISTIO wiki, if istio ingress-gateway pod is not running on every node, then the traffic will be dropped. In our test setup there is no istio ingress-gateway pod on node2, but it is not dropping the traffic.

(2) Setting 'externalTrafficPolicy to local', it should prevent sending traffic to other nodes. In our test setup, we observe that the traffic is sent to node2.

Can anyone please help us if we are missing something, or the istio wiki needs to be further explained ? 

Thanks,
Triptesh

### Version

```prose
istioctl version
client version: 1.16.1
control plane version: 1.16.1
data plane version: 1.16.1 (2 proxies)

kubectl version --short
Client Version: v1.21.0
Server Version: v1.25.5
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by bleggett** [comment]
I think the docs are outdated/wrong.

`kube-proxy` itself may only be sending packets to the Istio `ingress-gateway` pod running on node1 but either CNI or the gateway itself must be secondarily forwarding traffic to another node subsequent to that.

**Comment by triptesh1212** [comment]
We are not using any PROXY protocol. All configurations are default. 
We have only changed the `externalTrafficPolicy=local`

**Comment by subhankarc** [comment]
Hi @bleggett  Can this is confirmed as a documentation issue and can the same be updated ?

**Comment by bleggett** [comment]
Looking at this again - the docs aren't wrong, they're just slightly nonspecific and could be reworded for clarity.

- Having a single ingress gateway on a single node is still not ideal in all cases - your NLB is forwarding to exactly _one_ gateway on _one_ node and there is no internal loadbalancing of gateway traffic across nodes, which is a SPOF/potentially creates a bottleneck.
- You do not strictly NEED one gateway on each node to preserve client IP with `externalTrafficPolicy=local`
- A side effect of `externalTrafficPolicy=local` is that you are losing internal gateway loadbalacing _unless_ you run an ingress gateway on each node.

This is what the current doc means by `However, you must run an ingress gateway pod on every node. If you don’t, then any node that receives traffic and doesn’t have an ingress gateway will drop the traffic.`


`However, you must run an ingress gateway pod on every node. If you don’t, then any node that receives ingress traffic and doesn’t have an ingress gateway will drop the traffic, due to externalTrafficPolicy=local and kube-proxy not having a local gateway instance to forward to. This creates bottlenecking for ingress traffic, which in most cases would be unsuitable for a production deployment.`

**Comment by bleggett** [comment]
https://github.com/istio/istio/issues/43397

**Comment by subhankarc** [comment]
Hi @bleggett 

If there are two nodes and one of them has an ingress gateway pod, then traffic will always be forwarded to that node, and the load balancing will be affected, but traffic wo n’t be dropped, is that understanding correct ?

**Comment by bleggett** [comment]
> Hi @bleggett
> 
> If there are two nodes and one of them has an ingress gateway pod, then traffic will always be forwarded to that node, and the load balancing will be affected, but traffic wo n’t be dropped, is that understanding correct ?

If you have

- Node 1 with ingress gateway
- Node 2 without ingress gateway
- NLB
- `externalTrafficPolicy=local`

1. NLB -> Node 1 gateway will work. Node 1 gateway -> Node 2 will work.
1. NLB -> Node 2 gateway traffic will be dropped.

So effectively Node 1 will be handling ALL your incoming NLB traffic, rather than both Node 1 and Node 2 handling it.

**Comment by subhankarc** [comment]
Understood, so there will be impact on load balancing and possible bottlenecks on the node 1, but requests would not be dropped, if there are not much traffic/load. 

In that case, can we reword “ If you don’t, then any node that receives NLB ingress traffic and doesn’t have an ingress gateway to handle it will drop the traffic”. 

This gave an impression to me that traffic would go to node gateway and would be dropped. Actually, node2 would not get traffic only, I understand.

**Comment by bleggett** [comment]
> Understood, so there will be impact on load balancing and possible bottlenecks on the node 1, but requests would not be dropped, if there are not much traffic/load.
> 
> In that case, can we reword “ If you don’t, then any node that receives NLB ingress traffic and doesn’t have an ingress gateway to handle it will drop the traffic”.
> 
> This gave an impression to me that traffic would go to node gateway and would be dropped. Actually, node2 would not get traffic only, I understand.

Your understanding is correct.

I agree, it gave that impression - reword should help.
