### ISSUE TITLE
Standardize on Helm templates for yaml generation

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#4340]
At present istio has two ways to generate istio.yaml and other artifacts. 

1. `UpdateVersion.sh` and home grown templates
2. Helm 2.7.2

Standardize on `helm template` command as the only way of producing istio artifacts.
`helm` is only used as a templating system.

- [x] Ensure that helm and non-helm yamls are equivalent.
- [x] Use helm generated yamls in all tests
- [ ] Remove `updateVersion`

**Comment by mandarjog** [comment]
first 2 steps done via #4001

**Comment by sbezverk** [comment]
+1 for generating install artifacts in the go code than consuming already generated yaml and using different yaml files example as in here:
https://github.com/istio/istio/blob/de9f2dee56ed14bfbd56ae2a28296c92c25ac583/tests/e2e/framework/kubernetes.go#L40

```
	nonAuthInstallFile          = "istio.yaml"
	authInstallFile             = "istio-auth.yaml"
	nonAuthInstallFileNamespace = "istio-one-namespace.yaml"
	authInstallFileNamespace    = "istio-one-namespace-auth.yaml"
```
All these can be generated from a single template but feeding different values. I have experimented using helm api in go code and it looks ok to me.

**Comment by costinm** [comment]
I don't want to make the test setup even more complicated - having a separate step to generate the config also allows more flexibility.  I would simplify the test - to use only 'istio-test.yaml' file, since we no longer run both auth and no-auth in the same job/cluster.

Also having a shared environment, even with more components than needed for a specific test, ends up faster, since a single cluster setup (matching real user deployment) can be reused, and tests can be run against a pre-installed istio (with skip-setup).

I would go the opposite direction - and just remove the istio setup from the test, making skip-setup the only option and having the istio install done before the test.s

**Comment by ayj** [comment]
> ...  remove the istio setup from the test, making skip-setup the only option and having the istio install done before the test.

My understanding is that we wanted developers to be able to "express test environment requirements and constraints in integration/e2e tests", e.g. isolation, versions, features (see [here](https://docs.google.com/document/d/13f9K0X4hKLb6_6gunqZ2d0H2BOY4Fh16XfhtqipPMx4/edit#bookmark=id.s7cljx3whssf)) 

cc @hklai from Istio testing SWAT team 

Real user's may disable optional features at the component level, e.g. sidecar-injector, config validation. We probably ought to test the same.

 > ...  since a single cluster setup (matching real user deployment) can be *reused*, and tests can be run against a pre-installed istio (with skip-setup).

We've had a lot issues in the past with reusing/sharing clusters across top-level tests, e.g. quota limits, stale global config state.

**Comment by costinm** [comment]
Not blocking for 1.0.

**Comment by sdake** [comment]
We have different objectives for our helm work.  We still need to delete updateVersions.sh (1 AUD to the individual that ultimately deletes udpateVersion.sh from the repo.. 👍 

As such moving to P2+

**Comment by howardjohn** [comment]
@sdake feel free to send the 1 AUD :slightly_smiling_face: https://github.com/istio/istio/pull/18028
