### ISSUE TITLE
Merge proxy into main repo

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#43447]
This is a proposal to merge istio/proxy into the main repo. 

PROs:
* shared ownership, we have a decline in the contributions to istio/proxy and issues spanning envoy are not getting enough attention;
* faster development, we can avoid the two-step commit process for envoy changes;
* majority of istio/proxy code should be either eventually upstreamed or spawned into wasm-specific repositories;
* Istio can benefit from faster tests - relying on k8s to run basic datapath testing does not give us enough confidence at scale; testing without containers can scale much higher.

CONs:
* cherry pick disruption;
* large CI tests - that can be guarded by a basic git diff on the proxy directory;
* bazelification - this is purely aesthetics, there is no need to look at bazel files if not developing proxy.

**Comment by kyessenov** [comment]
cc @ericvn (thanks for the diligent retesting of tsan failures ;) )

**Comment by howardjohn** [comment]
@kyessenov do you have concerns with all istio tests running against any change to proxy?

The inverse (only run proxy tests if proxy/ change can be done fairly simply), but that will increase the tests run on any proxy change. This may be a good thing since we get more test coverage, though.

If we do this, we should consider moving ztunnel as well. Doesn't have to be decoupled. Ztunnel is a bit worse since ztunnel CI is <10 minutes, so the overhead of istio tests (slowest is ~40min - which is bad) is high. For proxy I think the tests are slow there so the extra tests may not be too bad (?).

If we do it, I would imagine:

```
proxy/ - has all proxy dumped here
ztunnel/ - has all of ztunnel dumped here
... rest of istio code remains ...
```

CI jobs can use `run_if_change: proxy/` and `run_if_change: ztunnel/` for proxy/ztunnel specific jobs.

We may still want 2 different build-tools jobs (although we could consider just having a gigantic shared one). We could do this in a few ways:

* Main folder uses normal image, proxy users set env var manually to use proxy image. Main Makefile.core.mk can import proxy/makefile.
* Main folder uses normal, proxy users have their own copy of all the Make infra under proxy/. Must be in proxy/ folder to do any proxy operations
* something else - probably lot of ways to do it

Overall I have no concerns with this - as long as proxy maintainers want it, of course

**Comment by howardjohn** [comment]
Oh totally forgot about that. That may be an issue. Prow dependencies support is basically non-existent. We can do some hacks but its not great.

Even if we did have a DAG execution, always building proxy as step 0 for istio tests would at a lot of time to most PRs. If we somehow would use a precompiled one if proxy/ folder is unchanged it could work, although that is a bit odd (for example, PR 1 changes proxy and merges. In postsubmit it is building proxy. Now PR 2 starts testing... does it wait for postsubmit to finish building...?)

**Comment by keithmattix** [comment]
I haven't been here long, but FWIW I'm concerned about istio/istio having an even higher barrier to entry spanning 3 main languages and toolchains: Go, C++, and Rust (if ztunnel moves - I agree with John that it should move if proxy does). The new developer onboarding experience for Istio is already a bit intimidating; I worry this would exacerbate that. There are definitely benefits, but I wanted to call out the onboarding DX here

**Comment by kyessenov** [comment]
@keithmattix We certainly shouldn't make knowledge of C++ a pre-requisite for new developers, and I think if we merge, the CI will simply skip proxy tests without any changes there. On the other hand, it would be beneficial to the project if contributors had more hands-on experience with the core technology instead of treating it as a black box, and Envoy is certainly a big part of Istio.

**Comment by keithmattix** [comment]
>  it would be beneficial to the project if contributors had more hands-on experience with the core technology instead of treating it as a black box, and Envoy is certainly a big part of Istio.

I definitely don't disagree with this point. I'm thinking more of the toolchain than anything else

**Comment by costinm** [comment]
I think ztunnel release/testing should be as decoupled as possible. It was a huge mistake to tie proxy and istiod - resulting in many upgrade problems because the tests assumed they are in sync.

**Comment by costinm** [comment]
This is in particular critical for ambient - since waypoints and control planes may be operated independently from ztunnel, and the data plane may be implemented in different ways. Protocol and API stability is very important.

**Comment by bleggett** [comment]
Also don't think `ztunnel` should move into the main repo.

If working on changes across two repos is hard:

- We have a CI gap
- We have a build/deploy/test gap

A monorepo will not solve those problems.

**Comment by kyessenov** [comment]
I am not proposing anything about `ztunnel`. This is just about Envoy L7 stuff. Let's not mix the two discussions.

**Comment by dhawton** [comment]
Overall I'm not a fan of the merge. It would make the istio repo even more complex for newcomers as Keith pointed out. The structure as it is now is a barrier of entry as it is and I think adding istio/proxy and another language and toolset would just make it even more complicated. This is a huge con, imho.

With ```shared ownership, we have a decline in the contributions to istio/proxy and issues spanning envoy are not getting enough attention;``` I don't see how changing the repo the code is in would change the contributions. Maybe there's another way to gain focus on the issues that need attention that affect istio/proxy?
