### ISSUE TITLE
Replace httpGet with exec during Kube-inject

### ISSUE THREAD

**Issue by wattli** [istio/istio#4345]
This will solve the http prober issue with mTLS enabled.

**Comment by ayj** [comment]
cc @yusuoh

**Comment by wattli** [comment]
and we should only do this when auth is enabled.

**Comment by incfly** [comment]
@wattli What command we should use to send http request locally? The workload container image may not have `curl`, could be built by a "FROM SCRATCH" Dockerfile.

**Comment by wattli** [comment]
@incfly , the traffic should be sent from proxy. And we could install curl in proxy image: https://github.com/istio/istio/blob/master/pilot/docker/Dockerfile.proxy

**Comment by incfly** [comment]
Thanks, yeah, realized that we should make dependency util program into container we control.

Taken a look at [Docker.proxy](https://github.com/istio/istio/blob/master/pilot/docker/Dockerfile.proxy), it seems that we try to keep its Dockerfile minimal. I'm not sure add `ADD apt-get update && apt-get install -y curl` is a good idea? @ldemailly, @costinm 

Should I instead write a simple http binary tool and bake that into istio-proxy Docker image? Or is there off-shelf http ping program? Note we need to support all probing options provided [k8s http liveness prober](https://github.com/istio/vendor-istio/blob/d199109652458002879661af268e36f57f184b2b/k8s.io/api/core/v1/types.go#L1916).

**Comment by ldemailly** [comment]
it's fine/good to add curl to the proxy (non debug) image

if you wanted a go version you could use `fortio curl ...` but curl itself is about the same size and is (for now ;-) more trusted

**Comment by ldemailly** [comment]
btw I just made a http client only version of fortio:

docker run istio/fortio.fcurl:0.8.1-pre1

it's a 2mb docker image (https://hub.docker.com/r/istio/fortio.fcurl/tags/), smaller than curl (3mb compressed https://hub.docker.com/r/appropriate/curl/tags/) 
(for future ref)

**Comment by incfly** [comment]
I did some prototype like this:

User app defines a healthz handler and returns ok for first 120s, and then starts to return 500. In the yaml file, user app has httpGet handler specified.

As the proposal suggested, I remove app container's httpGet and add `curl -i localhost/healthz | grep "HTTP.*200" `  in the exec liveness probe for istio-proxy container.

With that modified pod deployed, what I saw is:

1. The first 120s the pod is okay
1. The envoy container starts to restart repeatedly because liveness health check fail.
1. The user app container is never restarted.

I then realize a problem: the command liveness health check is specified in envoy container, so kubelet will restart only envoy container, letting user app container hanging there even the healthz fails... so it doesn't do what user wants, restarting their own container. :(

**Comment by ldemailly** [comment]
> add curl -i localhost/healthz | grep "HTTP.*200"

that's just `curl -f localhost/healthz` no need to grep for 200

**Comment by rshriram** [comment]
I guess that makes this solution pointless. That was a good catch about the container restart.

**Comment by incfly** [comment]
I'll close this given our new plan is to support TLS multiplexing, #5059
