### ISSUE TITLE
CNI upgrades will cause networking interruptions for ambient

### ISSUE THREAD

**Issue by bleggett** [istio/istio#43642]
### Bug Description

Right now, if you _upgrade_ the Istio CNI daemonset in an ambient cluster

1. The old daemonset will shut down
2. The node-level ambient redirection rules will be removed on DS termination as a cleanup step
3. The new daemonset will be spawned
4. The new daemonset will set up node-level redirect rules as a startup step

This means that between 2) and 4) there will be a period where redirection will not happen, and if it was happening it will be interrupted.

Preventing _new_ workloads from being scheduled while the CNI is not ready is an existing issue, and we can use e.g. https://github.com/istio/istio/issues/40303 to avoid race conditions with newly-spawned user workloads during this interval.

However, this **doesn't** solve network interruption for _existing_ workloads during this upgrade - which is a new, ambient specific problem, as ambient has new reliance on node-level networking rules.

This is not a great experience and needs to be fixed.

Problems:

1. There can be only one set of node-level rules in play  at a time - we cannot create parallel rules at the node level that are "owned" by different versions of Istio CNI.
2. This is generally a problem for the eBPF impl too - same problem, but in kernelspace instead of userspace.

Realistically, I can only see a few options here:

1. Node-level cleanup (and by definition CNI deployment/lifecycle mgmt) is externalized from the CNI deployment _entirely_ (possibly into a CRD controller as mentioned in: https://github.com/istio/istio/issues/40303). Conceptually this is messy but it may be the only option that allows us to both maintain node-level rules during CNI upgrades as well as properly clean up those rules on Istio uninstall.
2. Clean up _none_ of the node-level networking when the CNI daemonset is removed - which means `istioctl uninstall` will simply leave them there for the node operator to deal with. This seems bad as well, and assumes that leaving orphaned Istio-specific netrules on the node when Istio is gone will not also disrupt normal node networking - which it very well could.
3. Do some sort of finagling of the CNI upgrade process where we upgrade one node at a time so only one node will be "down" at a given time during the upgrade process, and document that, which AFAIK would also require a CRD and would definitely not be seamless.
4. Try to do something cute where a CNI daemonset (which is running a server that is watching and reacting to pod creation events) can "detect" when a successor CNI daemonset is created, and if that is the case, skip its own node-level cleanup on termination, assuming that the successor CNI daemonset will take care of it on uninstall if it needs to. I am still not sure this could be done with gaurantees of no interruption - if you have 2 CNIs running SxS and they are both in detect-and-repair mode they could conceivably _fight_ over the node-level rules for at least a short interval.

### Version

```prose
N/A
```

**Comment by bleggett** [comment]
CC @costinm because he brought up the "CNI CRD" idea in https://github.com/istio/istio/pull/43578#issuecomment-1443786950 and this might be where that starts to make sense.

**Comment by costinm** [comment]
I assume same or harder problem for ztunnel.


My proposal to use a CRD is mostly about API surface, but it also implies redirection/interception will be treated as  'reconciled' and not 'owned' by the daemon set.
We can use a configmap short term, instead of the helm values.

That means no cleanup on uninstall - but cleanup if the CRD disables interception. 

The next step ( probably should move thos to a doc) would be to have the crd/configmap control the redirection port and IP - so ztunnel can be safely rolled out.

For ztunnel we coud deploy using A/B rollouts - deploy a second ztunnel daemon set ( or install from start 2 and rollout the inactive one) and use CNI to shift interception to the new one after it's ready. That was one of the reasons for suggesting a CRD model. 

I think we could do same with CNI ( A/B ) so there is no downtime. Config will also determine the active one.

@howardjohn - not sure if there are other/better upgrade plans ?

**Comment by howardjohn** [comment]
Even if you have a CRD, if CNI is force deleted then CRD is removed, there will be nothing watching the CRD to cleanup the nodes?

Works well if you have the main CNI (cilium etc) (which cannot go away) implement it though?

For ztunnel we already do deploy a second instance and use CNI to shift. The shift is immediately to 100% right now but I think that is fine

**Comment by costinm** [comment]
If you "CNI force delete" - expect things to break. To turn off/disable
Istio - you first set the CRD to disable interception, then you delete.

Yes, it would be ideal if at some point Cilium, etc ( the 'native' CNI )
would take over this CRD and actuate it, and maybe the CRD
is adopted upstream in k8s. Until this happens - Istio CNI can still be
upgraded and turned off, but with care. Note that the 'native'
CNI upgrade path is also tricky - most likely requires node restart. That's
why it's best to keep CNI as small and stable as possible.

Any docs on the upgrade for ztunnel using CNI ? Sorry, missed or forgot the
PRs - how is the shift happening ?

**Comment by bleggett** [comment]
> Any docs on the upgrade for ztunnel using CNI ? Sorry, missed or forgot the PRs - how is the shift happening ?

Right now it isn't really handled per-say - the CNI currently managing the node detects if the active ztunnel changes, and if it does, it tears down the old redirect rules and reestablishes them for the new ztunnel instance.

**Comment by bleggett** [comment]
My only concern with a CRD is that _if_ we do a CRD, the CRD controller itself will have to take over some of the CNI responsibilities and touch the node networking stack - and now we have effectively metastasized node network munging across the CRD controller and CNI, which is messy.

**Comment by costinm** [comment]
That's equivalent to what I was suggesting. I mentioned having A/B because
it makes sure the alloc happens ( I don't know what happens on a node that
is fully allocated, if it allows a surge ).
So ztunnel can be upgraded without downtime - if the switch in redirection
is done carefully.

For CRD controller - I meant that Istio-CNI would be the equivalent of the
CRD controller, not a separate component. AFAIK many other CNI
implementations watch APIserver.
It seems a better approach than having to deal with annotations on pods and
helm install settings - from API perspective, but it also means that the
capture 'intent' will be expressed in the CRD, and not by the fact a
daemonset is installed/removed ( so at startup istio-CNI will make sure the
capture matches the config,
at shutdown will leave it as is).

**Comment by bleggett** [comment]
> For CRD controller - I meant that Istio-CNI would be the equivalent of the CRD controller, not a separate component. 

If we do that, we still have the upgrade problem for the CNI component itself, right? Where there's still one set of node netconfig rules that can be active at any one time? It's just a CRD controller instead of a daemonset.

**Comment by dgn** [comment]
In Maistra, we have some CNI customizations that basically allow you to install multiple DaemonSets to handle running different CNI versions in a single cluster at the same time. Every workload can basically 'select' the CNI implementation through selecting the correct network value. I was going to suggest moving these changes upstream anyway because it enables canary deployments of istio-cni - but I see now it could even help with ambient. Is there interest in this approach?

**Comment by howardjohn** [comment]
I am not sure that helps much with ambient; the issue with ambient is we are mutating host networking rules. So we can't have 2 at once because there is no way to 'namespace' them.

**Comment by bleggett** [comment]
> Since ztunnel acts as a default gateway for ambient pods, has anyone considered using [VRRP](https://en.wikipedia.org/wiki/Virtual_Router_Redundancy_Protocol) to handle the HA use case? The rules can be written for the VRRP VIP address so updates are not required when the passive ztunnel pod takes over for the active one.

Not been suggested yet, good call - may or may not work for eBPF tho since eBPF necessarily bypasses most normal kernel routing logic.

**Comment by keithmattix** [comment]
Not stale

**Comment by bleggett** [comment]
As per https://docs.google.com/document/d/1SMlwliEnthgq7r2PjpLl1kCq3t8rAMbgu6r_lDAXJ0w/edit#heading=h.uph0clj4a3t4. on June 14th the consensus was that

1. Networking interruptions for both ztunnel and CNI upgrades are acceptable.
2. The way we recommend people deal with this is via node cordons.

So closing this as wontfix.
