### ISSUE TITLE
ambient: consider customization to redirection

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#43700]
Currently, ambient redirection is all or nothing. We may consider customizations, such as per-port or per direction (only outbound/only inbound, etc).

cc @costinm @kyessenov

**Comment by costinm** [comment]
I think 'capture' and 'redirection' are a property of the low-level network
and CNI layer. Istio-cni already define some annotations - which we should
probably move to a
CRD and promote to beta at some point - but I don't think we can avoid
supporting at least a subset of the CNI customizations.

I was not aware that istio-cni no longer checks and apply the
annotations in ambient mode - can you point me to the code ? I thought the
interception
control moved back to istio-cni, I no longer see the script in ztunnel init
- but I didn't see the logic ignoring the annotations for ambient ( long
time since I've looked at CNI code, it turned a bit more complex than the
old scripts...)

**Comment by bleggett** [comment]
I can see an argument for per-port redirection.

Per-direction customization seems like a really complex potential footgun - what would be a valid scenario for that?

**Comment by howardjohn** [comment]
> Per-direction customization seems like a really complex potential footgun - what would be a valid scenario for that?

Most obvious case I can think of is I run Nginx LB. Disable incoming redirection (nginx will handle user TLS), but enable outbound (so it is in the mesh)

**Comment by costinm** [comment]
Typical use cases are:
- an app that natively implements mesh ( proxyless / native implementations
).
- an app that hits a bug or can't tolerate the latency ( we want ztunnel to
be fully transparent - but we are not perfect )

For port range ( or all-port ) exclude - there are some modern protocols
that use dynamic ports ( like the ancient FTP ),
so you can't exclude individual port.

Parity with NetworkPolicy is probably the minimum bar ( and same syntax
would be nice for users too ).

**Comment by costinm** [comment]
Yes, Nginx LB for inbound - squid for outbound ( disable outbound capture
).

**Comment by bleggett** [comment]
> > Per-direction customization seems like a really complex potential footgun - what would be a valid scenario for that?
> 
> Most obvious case I can think of is I run Nginx LB. Disable incoming redirection (nginx will handle user TLS), but enable outbound (so it is in the mesh)

Wouldn't that just be a Gateway at that point, and not a "Normal Workload"?

> - an app that natively implements mesh ( proxyless / native implementations
).
> - an app that hits a bug or can't tolerate the latency ( we want ztunnel to
be fully transparent - but we are not perfect )

Agree with that, but in that case simply excluding from redirection entirely while still adding it to the mesh would work just as well as selective inbound/outbound toggles.


> For port range ( or all-port ) exclude - there are some modern protocols that use dynamic ports ( like the ancient FTP ), so you can't exclude individual port.

That also seems to me to be something that would be better solved with all-or-nothing, then.

**Comment by howardjohn** [comment]
> > > Per-direction customization seems like a really complex potential footgun - what would be a valid scenario for that?
> > 
> > 
> > Most obvious case I can think of is I run Nginx LB. Disable incoming redirection (nginx will handle user TLS), but enable outbound (so it is in the mesh)
> 
> Wouldn't that just be a Gateway at that point, and not a "Normal Workload"?

Yes, you can make the Gateway not mesh-aware though and delegate the encryption to ztunnel. Linkerd just had a blog about this: https://linkerd.io/2023/02/21/linkerd-and-ingress/. A bit like sandwiching - its not a priority for _our own gateway_ since we just do HBONE in envoy, but Nginx probably won't do HBONE

**Comment by kyessenov** [comment]
I'd be OK with all-or-nothing like we do for internal gateways - it's indeed simpler. The main issue is coupling with the destination policy. It works for waypoints because we require that backends are HBONE enabled (directly or indirectly via ztunnel).

Maybe that's the right overall position? If a client wants to use HBONE directly and be part of the mesh, it must assume the rest of the mesh is also HBONE? That way we no longer require per-pod policies (which are actuated by ztunnel).

**Comment by bleggett** [comment]
> > > > Per-direction customization seems like a really complex potential footgun - what would be a valid scenario for that?
> > > 
> > > 
> > > Most obvious case I can think of is I run Nginx LB. Disable incoming redirection (nginx will handle user TLS), but enable outbound (so it is in the mesh)
> > 
> > 
> > Wouldn't that just be a Gateway at that point, and not a "Normal Workload"?
> 
> Yes, you can make the Gateway not mesh-aware though and delegate the encryption to ztunnel. Linkerd just had a blog about this: https://linkerd.io/2023/02/21/linkerd-and-ingress/. A bit like sandwiching - its not a priority for _our own gateway_ since we just do HBONE in envoy, but Nginx probably won't do HBONE

At that point I would rather just special-case gatewayClasses or whatever in the CNI, rather than offer this to generic workloads.

**Comment by costinm** [comment]
On Thu, Mar 2, 2023 at 8:38 AM Ben Leggett ***@***.***> wrote:

> Per-direction customization seems like a really complex potential footgun
> - what would be a valid scenario for that?
>
> Most obvious case I can think of is I run Nginx LB. Disable incoming
> redirection (nginx will handle user TLS), but enable outbound (so it is in
> the mesh)
>
> Wouldn't that just be a Gateway at that point, and not a "Normal Workload"?
>
That's the choice of the NGinx developers - they may support Gateway, or
keep it as a regular pod. Not under our control - but if they run in a
cluster with
ztunnel and istio-cni - we should support them.



>
>    - an app that natively implements mesh ( proxyless / native
>    implementations
>    ).
>    - an app that hits a bug or can't tolerate the latency ( we want
>    ztunnel to
>    be fully transparent - but we are not perfect )
>
> Agree with that, but in that case simply excluding from redirection
> entirely while still adding it to the mesh would work just as well as
> selective inbound/outbound toggles.
>
Not sure what 'adding to the mesh' means in this context - but there are
cases where you want to use ztunnel/sidecar for some things but not others.

We can try to find usage numbers for the port-control annotations - but
I've seen quite a few customers using them.



> For port range ( or all-port ) exclude - there are some modern protocols
> that use dynamic ports ( like the ancient FTP ), so you can't exclude
> individual port.
>
> That also seems to me to be something that would be better solved with
> all-or-nothing, then.
>
>
>
All-or-nothing is a bit extreme. A proxyless gRPC app supports mesh
semantics natively - for gRPC - but may still use TCP and HTTP ( to connect
to a database or accept http requests ).

To reverse your question: any reason for Istio-CNI to stop supporting
features it had since ~Istio 0.1 that are used and don't affect ambient ?

**Comment by bleggett** [comment]
> To reverse your question: any reason for Istio-CNI to stop supporting features it had since ~Istio 0.1 that are used and don't affect ambient ?

None, other than the fact that more formalized gateway classes and the lack of sidecar injection means these features are less important to support as generic options going forward.

**Comment by costinm** [comment]
I think we may be talking about 2 different things.  This is not about
ztunnel IMO - no change to ztunnel needed for this.

I am only talking about istio-cni - and respecting the annotations ( and
future CRDs ) that we already have. If someone removed
the annotation support in istio-CNI - we should have some strong reasons.

**Comment by costinm** [comment]
I would agree with you for gateways.

But as I mentioned, proxyless / native implementations are far more
important use cases. And even for gateways - we can't force users to
implement
gateway classes or gateway, and the specs are very vague about how to
handle multiple implementations in the same cluster. I'm not saying it's
a bad idea for gateway use cases to be more formalized - but we have the
other use cases too.

**Comment by bleggett** [comment]
> That's the choice of the NGinx developers - they may support Gateway, or keep it as a regular pod. Not under our control - but if they run in a cluster with ztunnel and istio-cni - we should support them.

My main problem is that it feels wrong to have a global footgun option in place just to support ad-hoc gateways, versus

> Not sure what 'adding to the mesh' means in this context - but there are
cases where you want to use ztunnel/sidecar for some things but not others.

Yes - that's what I mean - if you want to be e.g. a valid source/dest workload in the mesh but you want to skip all CNI redirection (and therefore ztunnel) - that's fine, if you are ok giving up with ztunnel and redirection gives you "for free". We should support that. What I don't really see the need for is supporting _partial_ CNI direction for U/D on top of that.

> We can try to find usage numbers for the port-control annotations - but
I've seen quite a few customers using them. 

I have no problem with port annotations. Just with the idea that we allow any workload in the mesh to selectively enable up/down redirect exclusion, versus the options of 1) all or nothing 2) port-based exclusions.

**Comment by howardjohn** [comment]
Port annotations (in their current impl) do allow you to enable up/down redirect exclusion, as you can do `includeInboundPorts: *` etc

**Comment by bleggett** [comment]
> Port annotations (in their current impl) do allow you to enable up/down redirect exclusion, as you can do `includeInboundPorts: *` etc

Right - and that's fine I think, you just use the port exclusion with a wildcard - I just don't want to add another annotation for "inbound/outbound redir"

**Comment by costinm** [comment]
Agreed, my proposal is to just support the current annotations ( or at
least a subset ). We do want this interception to be implementable at lower
level,
so it may be ok to remove some flexibility if eBPF or other native CNI
implementations have troubles.

The discussion about a CRD ( ProxyConfig or a new one ) is more about the
usual process to promote to beta and not depend on pod changes/annotations
but have a proper API ,the content/behavior should be identical to the
feature we have.

Let's separate the discussion of "CNI not regressing between Sidecar-based
and Ambient" - i.e. continuing to support the interception controls it has,
versus
implementing something similar in ztunnel. I don't see why we would need
the last - but I'm not against it if someone has use cases that can't be
satisfied
with CNI-level control we already have.

**Comment by GregHanson** [comment]
> my proposal is to just support the current annotations ( or at
least a subset )

@costinm just to confirm, are these the [annotations](https://istio.io/latest/docs/reference/config/annotations/) you're referring too?  Or were there more on your mind?

 - `traffic.sidecar.istio.io/excludeInboundPorts`
 - `traffic.sidecar.istio.io/excludeOutboundIPRanges`
 - `traffic.sidecar.istio.io/excludeOutboundPorts`
 - `traffic.sidecar.istio.io/includeInboundPorts`
 - `traffic.sidecar.istio.io/includeOutboundIPRanges`
 - `traffic.sidecar.istio.io/includeOutboundPorts`

**Comment by linsun** [comment]
I agree with supporting the existing include/exclude annotations as the first step, most common ones folks use are ports related.

**Comment by bleggett** [comment]
Not stale

**Comment by bleggett** [comment]
`exclude/includePorts` is as far as I can tell == PeerAuthentication `portLevelMtls.mode<PORT>: DISABLE`, as far as ambient goes.

Are we planning to support both mechanisms? They seem redundant.

Either we let people exclude ports (or a range of ports) to continue supporting PERMISSIVE in some fashion, or we effectively require STRICT and a gateway to get traffic in. I don't see any other options, but I might be missing something.

**Comment by keithmattix** [comment]
> DISABLE in ambient does not actually disable capture, it is ignored/deprecated

Currently, DISABLE is equivalent to permissive in Ambient rather than ignored

**Comment by keithmattix** [comment]
Well, PeerAuthentication's Ambient support does include port level granularity for STRICT and PERMISSIVE today. But both require 100% traffic capture which I think is more of what you're wanting to discuss @bleggett?

**Comment by bleggett** [comment]
Kinda.

- If we allow mTLS exclusions at all, it feels both safer and more explicit to only allow that via one mechanism, on a port-by-port (with ranges) allowlist basis. e.g. -> "mTLS is always required for all pods and no config can change that, and the only way around that is allowlisting explicit ports on specific pods"

- If we do that, then there's not much practical air between "do not capture this port" and "allow random non-mTLS traffic to this port" in ambient.

Supporting all 3 of PERMISSIVE, per-port PERMISSIVE, and port capture exclusions in ambient seems like too many knobs. We get stuck with the first two options because we lack the last option.

**Comment by keithmattix** [comment]
The advantage of the first two is plaintext telemetry though

**Comment by howardjohn** [comment]
>  If we do that, then there's not much practical air between "do not capture this port" and "allow random non-mTLS non-mesh/non-gateway'd traffic to this port" in ambient.
> The advantage of the first two is plaintext telemetry though

Its far beyond that. Its impossible to implement our APIs without capturing traffic.

We cannot enforce authz policies or 'must go through waypoint'.

Not capturing traffic is not an option.

**Comment by bleggett** [comment]
> Not capturing traffic is not an option.

Then we can close this issue.

> The advantage of the first two is plaintext telemetry though

Yep, the question is if we allow bypassing our security model to generate plaintext telemetry/policy enforcement, at what point do we say "your telemetry and policy options are limited beyond this point, because you are bypassing our security model".

An obvious spot for that cutoff is "Higher than L4 policy".

**Comment by kyessenov** [comment]
Rather than saying the plaintext, I'd recommend referring to delegated network security. It might be plaintext at Ambient level, but encrypted at the lower level of the stack, which should be a supported mode of operation. mTLS-based identity is only one way to enforce identity.

**Comment by howardjohn** [comment]
If we cannot get the identity from it, it doesn't really matter if its
encrypted or not from Istio's POV IMO.

**Comment by bleggett** [comment]
Okay - so 

1. We are not customizing redirection/capture.

2. We will let people use PeerAuthentication to control identity requirements on inbound capture.

For ambient, since back compat with sidecar APIs is not a requirement, have we considered supporting ONE OF 

- PeerAuth STRICT/PERMISSIVE for every port (blanket)
- portLevelMtls STRICT/PERMISSIVE (selective)

Having both in Ambient and layering them seems like creating a secondary footgun for the footgun, in terms of API surface - it might be better to simply respect only `portLevelMtls` in Ambient, and no longer allow people to blanket-PERMISSIVE.

**Comment by bleggett** [comment]
[Aug 16 ambient takeaways](https://docs.google.com/document/d/1SMlwliEnthgq7r2PjpLl1kCq3t8rAMbgu6r_lDAXJ0w/edit#heading=h.fuo9e2xriflh):
- We are not customizing redirection/capture for beta, at the very least. Maybe never.
- Since we are defaulting to PERMISSIVE in Istio, we need both global PERMISSIVE and portLevelMtls in ambient. If we defaulted to STRICT, we could get away with just `portLevelMtls`. But we do not, and do not intend to.

**Comment by costinm** [comment]
It is not quite equivalent - yes, both allow plain text to get to the pod.
But in one case it is directly from the source,
in the other it is routed through ztunnel - and may or may not interfere
with CNI processing of the packet ( NetworkPolicy, etc),
or have the same perf. I know ztunnel is super fast - but copying all the
bytes back and forth is never free.

Technically user can just disable ambient and run ztunnel as a sidecar -
where all the capture options are available, so
maybe it's not so bad.

**Comment by costinm** [comment]
On Tue, Aug 15, 2023 at 5:58 PM John Howard ***@***.***>
wrote:

> If we cannot get the identity from it, it doesn't really matter if its
> encrypted or not from Istio's POV IMO.


But it matters from user POV - because they may use NetworkPolicy.

We have had those controls since Istio v0.4 or so - I'm not sure how
suddenly we can't implement
our APIs if we support the same API that Sidecars had, that explicitly
disables the application of
 Istio APIs for specific ports ( which is what the annotations did ).  That
is the user intent when using
exclude - please don't apply Istio APIs or provide telemetry or anything, I
know what I'm doing (
example use proxyless gRPC which has telemetry and everything else ).

It seems a very extreme position - but I guess proxyless is experimental
and users can still  disable
interception completely if we refuse to allow just a port to be excluded.




>
>

**Comment by GregHanson** [comment]
not stale
