### ISSUE TITLE
Remove Istio Ingress Gateway from Ambient Profile

### ISSUE THREAD

**Issue by danehans** [istio/istio#44030]
**Describe the feature request**
Since Istio intends on making [Kubernetes Gateway API](https://gateway-api.sigs.k8s.io/) the default API for traffic management in the [future](https://istio.io/latest/blog/2022/gateway-api-beta/), the ambient profile should use a [Kubernetes Gateway](https://gateway-api.sigs.k8s.io/api-types/gateway/) instead of Istio ingress gateways. A Kubernetes Gateway can be created by the ambient profile that exposes the same protocols and ports as an Istio ingress gateway. Users would then create an HTTPRoute to route traffic through the Gateway to one or more Ambient mesh services.
 
**Describe alternatives you've considered**
- Continue using Istio classic APIs for the ambient profile. Since Ambient is experimental, this is a great time to promote the use of Kubernetes Gateway API for traffic management.
- Have the ambient profile create both an Istio ingress gateway and a Kubernetes Gateway. Having two different Gateways may cause confusion with users. Additionally, most users will continue to use the Istio ingress gateway due to familiarity.

**Affected product area (please put an X in all that apply)**

[X] Ambient
[X] Docs
[X] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

Current profile:
```
istioctl install --set profile=ambient
This will install the Istio 1.18.0 ambient profile with ["Istio core" "Istiod" "CNI" "Ztunnel" "Ingress gateways"] components into the cluster. Proceed? (y/N) y
...
```

Proposed profile:
```
istioctl install --set profile=ambient
This will install the Istio 1.18.0 ambient profile with ["Istio core" "Istiod" "CNI" "Ztunnel" "Kubernetes gateway"] components into the cluster. Proceed? (y/N) y
...
```

A new type, i.e. KubeGatewaySpec, will need to be defined similar to [GatewaySpec](https://istio.io/latest/docs/reference/config/istio.operator.v1alpha1/#GatewaySpec) and added as field `kubernetesGateways` to [IstioComponentSetSpec](https://istio.io/latest/docs/reference/config/istio.operator.v1alpha1/#IstioComponentSetSpec) .

**Comment by howardjohn** [comment]
We should not have a Kubernetes Gateway in the IstioOperator. Instead we should set ingressgw.enabled=false, and have users create a k8s Gateway  resource. This is already the best practice (https://istio.io/latest/docs/setup/additional-setup/gateway/)

**Comment by danehans** [comment]
Based on ^ feedback, I have updated this issue to "Remove Istio Ingress Gateway from Ambient Profile".

**Comment by howardjohn** [comment]
Removing the GW != using k8s gateway API. https://istio.io/latest/docs/setup/additional-setup/gateway/ has been the recommended approach for over a year now on installing gateways; istioctl install coupled w/ control plane install has been considered an anti-pattern we keep for backwards compat.

**Comment by frankbu** [comment]
Ideally we should have different instruction for install (depending on whether the user wants gateway-api or classic gateway) but if we change the default to not include istio-ingressgateway, we MUST have 2 sets of instructions because classic instruction will be broken by default. If we don't change the default, then both sets of instructions continue to work, just the gateway-api instructions have an unused istio-ingressgateway installed, which is not ideal.

That said, I thought that ambient is only a temporary profile. See https://github.com/istio/istio.io/pull/12932#discussion_r1153248162

**Comment by linsun** [comment]
> Ideally we should have different instruction for install (depending on whether the user wants gateway-api or classic gateway) but if we change the default to not include istio-ingressgateway, we MUST have 2 sets of instructions because classic instruction will be broken by default. If we don't change the default, then both sets of instructions continue to work, just the gateway-api instructions have an unused istio-ingressgateway installed, which is not ideal.
> 
> That said, I thought that ambient is only a temporary profile. See [istio/istio.io#12932 (comment)](https://github.com/istio/istio.io/pull/12932#discussion_r1153248162)

That was my concern too, think we wrote at the same time :)

**Comment by howardjohn** [comment]
I think all the points mentioned are valid. I personally still weight removing it higher, as I think ambient is a unique opportunity to favor best practices over backwards compat, but ok with reconsidering later.

**Comment by frankbu** [comment]
I sympathize with @howardjohn's comment that ambient is a unique opportunity to favor best practices over backwards compat. Not installing ingressgateway along with istiod is considered a best practice, even if you aren't using Gateway API, so making `ambient` profile be the new `minimal` profile in ambient world, seems like a pretty good idea. The longer we wait, the harder it will be to change it as more and more docs copy/paste the install instruction that assumes the ingressgateway is always there. I think that maybe it is a good idea to make this switch now, since all we really need to do is add a tabset for install in the ambient getting started doc which adds ingressgw.enabled=true in the classic tab.

**Comment by linsun** [comment]
Thanks @frankbu and @howardjohn! I think most of my concerns are much reduced with the understanding of this is not forcing users to use new Gateway API and we will still have the installation of ingress gateway (as a tab) for get started ambient doc. 

And the reason why we can't change our default profile to reflect the best practice is because we don't want to break users already running Istio in production.
