### ISSUE TITLE
remote repo adapters should not copy mixer_codegen.sh

### ISSUE THREAD

**Issue by guptasu** [istio/istio#4404]
It seems adapters in remote repository need to copy `mixer_codegen.sh`; there is apparently some document generation issue. This is fragile and cause problems when istio proper changes the script in a breaking way, and external adapters have no idea what hit them.

FYI @theganyo

**Comment by theganyo** [comment]
Basically, there just needs to be a robust solution for adapters to be able to build against Istio as a vendored dependency. 

We've been relying on our own lightly edited version of `mixer_codegen.sh` so we could avoid some assumed paths in the script (around ROOT and GOPATH) that prevented our direct use of the script in vendor. As of now, however, we're no longer able to build our adapter at all.

**Comment by douglas-reid** [comment]
How does relate to the codegen script in `istio/contrib/bin` ?  That should be simpler and easier to use.

Why would third-party adapters be trying to use the vendored copy of `mixer_codegen.sh`?  And is the issue docgen stuff?  If so, should that be separated out?

**Comment by theganyo** [comment]
The prototypical example is here: https://github.com/istio/contrib.

**Comment by robbrit** [comment]
So we are now able to build our adapter again. The flow is like this:

1. Run dep ensure.
2. Run go generate, which ties into the codegen script. This ends up adding new dependencies and tries to use those dependencies, which fails because they aren't there.
3. Run dep ensure again, it will now fetch the new dependencies.
4. Run go generate again. Hopefully no new dependencies are added, or we have to repeat these steps until go generate succeeds.
