### ISSUE TITLE
 how to get real client IP for Services with  ingress gateway Type=NodePort  and externalTrafficPolicy = cluster

### ISSUE THREAD

**Issue by koalaxiu7** [istio/istio#44148]
### Bug Description

 how to get real client IP for Services with  ingress gateway Type=NodePort  and externalTrafficPolicy = cluster

### Version

```prose
istioctl version:
client version 1.9.5
control plane version: 1.12.0
data plane version: 1.12.0
kubectl version --short:
Client Version: v1.20.5
Server Version: v1.20.5
```

**Comment by koalaxiu7** [comment]
don't want to change externalTrafficPolicy = cluster to externalTrafficPolicy = local

**Comment by cnvergence** [comment]
Hey @koalaxiu7, when using L7 external load balancer you can get real client IP using X-Forwarded-For header, please take a look at these [docs](https://istio.io/latest/docs/tasks/security/authorization/authz-ingress/#source-ip-address-of-the-original-client).

**Comment by sharoncr1** [comment]
@cnvergence I'm using L7 LoadBalancer, I mean AWS ALB. 

I enabled Istio proxy debug logs and I'm seeing x-forwarded-for header being set to '14.140.240.6,172.24.9.231' where the first IP is the actual client IP and second one is network interface IP of that LoadBalancer.

AWS gives us three choices to configure it's x-forwarded-for header as follows : 

**X-Forward-For header**
Enables you to append, preserve, or remove the X-Forward-For header in the HTTP request before the Application Load Balancer sends the request to the target.
Append
Preserve
Remove

Currently it''s set to Append and I get two IPs as I stated. When I use preserve, I'm getting only ALB interface IP.. 

Any idea why?

I need to use the actual client IP on the Authorization policy for the `from.source.remoteIpBlocks` field. But proxy is failing to match them when I just give `14.140.240.6` since the header value is '14.140.240.6,172.24.9.231'. Is there any way to make this work?

**Comment by cnvergence** [comment]
Have you set the numTrustedProxies setting?
https://istio.io/latest/docs/ops/configuration/traffic-management/network-topologies/#configuring-x-forwarded-for-headers

**Comment by sharoncr1** [comment]
@cnvergence Yes if you were asking me... And I can see that setting is applied during the startup of the istio-proxy container on my pod and I believe that's why that header is atleast reaching the proxy.

**Comment by cnvergence** [comment]
The append setting on your ALB should be fine, in the headers you should receive the actual client IP in the `X-Envoy-External-Address` header.
Maybe adjust `numTrustedProxies` setting to a different number and restart Istio ingress gateway deployment.

**Comment by makarov-roman** [comment]
Indeed, after applying `numTrustedProxies = 1` I see the real IP in `X-Envoy-External-Address`, but does it mean that it works as intended? Shouldn't we see the same IP in `remoteIP` to be able to use from.remoteIpBlocks rule? Otherwise we have to do something like:
```yml
  rules:
  - when:
    - key: request.headers[X-Envoy-External-Address]
      values: []
```
which is less obvious and looks just like workaround.
