### ISSUE TITLE
release-notes should have a way to approve just release notes

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#44378]
With our current scheme, maintainer approve "release notes" without reviewing the rest of the PR. In some occasions, this has led to accidental merging of un-reviewed PRs.

We should have a way to avoid this that doesn't rely on maintainers never making a mistake

cc @ericvn

**Comment by ericvn** [comment]
I have thought of this before as well, and purposely try and not approve a release note where I know another review, say UX/environments/netowrking has to approve as well.

I wonder if we remove T&R from releasenotes/notes. This leave RMs as the approvers. Do we need to expand that list?

**Comment by ericvn** [comment]
Thinking more about my earlier comment, I don't think that solves the issue. I guess the thought is that a maintainer, who was also a release manager, is approving the release notes without reviewing the rest of the PR for which they are a maintainer. Using myself as an example, I am a Doc and T&R maintainer as well as a past release manager. If there is a PR which has some test updates as well as a release note, I need to be cognizant that when I am approving one, I am also approving the other. I know there was some discussion on not just selecting `approve` without adding some comments, so in some cases I do leave an approval comment on the release notes, and maybe the test and release maintainer part of the PR. So maybe this is simply my bad for not always calling out both (or three) portions of the approval (although I really am approving for all). That I can work on.

I'm assuming that I'm not the only one that falls into the multi-group camp, so how can we fix this beyond education? Short of being able to selectively approve from the various roles on has, I'm not sure we can.

**Comment by howardjohn** [comment]
What if we just had no owners (see last example in 
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#example-of-a-codeowners-file)?

Then there is no need for anyone to review release notes only, just it's part of the normal review of all maintainers. They all get edited a bit in the end anyways so I think quality will be fine

**Comment by ericvn** [comment]
My concern with no ownership is that the release notes will need more editing. Moving to no approvals moves the editing until the time of release, which may make it harder for the RM to remember/figure out any changes needed and it would have to be done over multiple branches possibly (maybe the RM would look at another patch release and just use the text from an earlier edit/review). It may cause more work for the doc team (what little there is) as well. My original hope would be that there should be no editing required at release, but it seems that the release notes are getting approved and still needing editing, so that hope is dashed.

Based on the above, we could remove the approval of the text.
