### ISSUE TITLE
TestMixerInternalFail postsubmit failed.

### ISSUE THREAD

**Issue by xiaolanz** [istio/istio#4444]
Test istio.io/istio/mixer/test/client/mixer_internal_fail.TestMixerInternalFail has failed 1 times since it last passed at commit/731ec547f. It started failing between commit/731ec547f (Wed Mar 21 16:03 PDT) and commit/fa01443e6 (Wed Mar 21 16:03 PDT).
Test Overall has failed 1 times since it last passed at commit/731ec547f. It started failing between commit/731ec547f (Wed Mar 21 16:03 PDT) and commit/fa01443e6 (Wed Mar 21 16:03 PDT).

**Comment by xiaolanz** [comment]
problem cl? #4426 or #4343

**Comment by ldemailly** [comment]
failed how ? can you put the link to the failed build ?

**Comment by JimmyCYJ** [comment]
I think it is https://k8s-gubernator.appspot.com/build/istio-prow/istio-postsubmit/1277/

**Comment by ldemailly** [comment]
[2018-03-21 23:26:35.569][8887][debug][main] external/envoy/source/server/server.cc:164] Unable to initialize config as v2, will retry as v1: Unable to parse JSON as proto (INVALID_ARGUMENT:cluster_manager: Cannot find field.): 


@yutongz I thought that didn't go in ? or is it not from your test ?

**Comment by ldemailly** [comment]
ah so is it
```
mixer_internal_fail_test.go:59: Failed in request Fail-Close: Get http://localhost:20049/echo: dial tcp [::1]:20049: connect: connection refused
mixer_internal_fail_test.go:63: Status code 500 is expected, got 0.
```
then?

**Comment by JimmyCYJ** [comment]
This is a flaky test (according to https://prow.istio.io/?repo=istio%2Fistio&job=istio-postsubmit). It starts Envoy and verify Mixer filter config works as expected, then the test changes Mixer filter config and restarts Envoy to load that config. We does not change port numbers for Envoy, so after rebooting Envoy, the test sends request to the same port. I think Envoy fails to bind the ports, that is why TCP connection establishment fails. 

The error message indicates that AdminPort is already in use and Envoy fails to bind to it.
"[2018-03-21 23:26:36.566][8942][critical][main] external/envoy/source/server/server.cc:71] error initializing configuration '/tmp/config.conf.20053': cannot bind '0.0.0.0:20053': Address already in use"

Maybe we can split the test into two, so that we don't need to restart Envoy and reuse the same set of ports.

**Comment by JimmyCYJ** [comment]
Another option is, we select a new set of ports for Envoy to bind, so that we can still restart Envoy in this test as well as other Mixer client tests.

**Comment by ldemailly** [comment]
> I think Envoy fails to bind the ports

why is that ?

**Comment by JimmyCYJ** [comment]
The test failure shows that Envoy binds to port 20053, which is admin port. After finishing some test steps, we change the config and restart Envoy, we use the same set of ports for Envoy to bind, but the port is not freed, so Envoy fails to bind. I think it takes time for the kernel to release all these ports. 
PR# [4465](https://github.com/istio/istio/pull/4465), changed test setup, now when we restart Enovy, we test if current set of ports are released, if yes, we reuse current set of ports; otherwise, we select a new set of ports for Enovy to bind.

**Comment by ldemailly** [comment]
unless we have linger options or not exit properly ports shouldnt stay busy but I guess it's good to check
