### ISSUE TITLE
Possible upgrade problem in 0.7

### ISSUE THREAD

**Issue by costinm** [istio/istio#4452]
In one of my tests I've seen pilot looping with:

018-03-21T23:06:09.651169Z    info    Work item failed (waiting till full synchronization), repeating after delay 1s
2018-03-21T23:06:10.214547Z    error    istio.io/istio/pilot/pkg/config/kube/crd/controller.go:175: Failed to list *crd.Policy: the server could not find the requested resource (get policies.authentication.istio.io)

Deleting the CRD manually solved the problem - but users expect to be able to upgrade istio, and 
this can be automated.

Needs to be verified - and cherry picked into 0.7 if it happens, the behavior is pretty bad.

**Comment by costinm** [comment]
https://github.com/istio/istio/issues/1880 may have some related discussion.

**Comment by diemtvu** [comment]
This is related to https://github.com/istio/istio/issues/4471. The fix is rolling back the version number, so customers won't have problem when moving from .6 to .7.

Early testers / devels who build and use binary from head may need to remove authn policy CRD on their test clusters manually once.

`kubectl delete crd policies.authentication.istio.io`

**Comment by hklai** [comment]
@yusuoh PTAL and see if we can add more coverage to the upgrade test.
