### ISSUE TITLE
[Experiment] Add North-South UDP Protocol Support on Istio Ingress Gateway

### ISSUE THREAD

**Issue by Xunzhuo** [istio/istio#44558]
**Describe the feature request**

Add basic UDP protocol support on Istio Ingress Gateway for north-south traffic management.

**Describe alternatives you've considered**

For many reasons, istio does not support udp for a long time, but I think we need basic udp traffic management in north-south side. At least, I think we need to support routing udp traffic to target backend svc.

I tried to use EnvoyFilter to dynamically add/update/delete udp listener/proxy in istio-ingressgateway. Adding/Removing udp listener is easy, but there is one big problem is that I think we did not discovery udp services/endpoints, I have tested to create a couple of udp services, but cannot find the endpoints in istio discovery endpoints data. So I need to list/watch svc/endpoints in clusters, and dynamically add/remove endpoints in EnvoyFilter which patches Cluster config of istio-ingressgateway.

**Affected product area (please put an X in all that apply)**

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [x] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
Given Istio's general limited UDP support, can you help explain why you want to use it compared to other existing UDP ingresses?

**Comment by Xunzhuo** [comment]
Background is that we are one of the [platform providers](https://istio.io/latest/docs/setup/platform-setup/tencent-cloud-mesh/) for istio, and we are using istio as the north-sourth/west-east full traffic management solution. Unlike individual team, bringing another ingresses/gateways component though can solve it, like the envoy-gateway I am maintaining, but this will increase much cost of operation, as we need to introduce a new component just for udp traffic and need to operate.
@howardjohn

**Comment by SAMZONG** [comment]
@Xunzhuo I'm so interested in this idea, but providing more powerful comparisons as a reference for operation.

**Comment by NiftyliuS** [comment]
I am very confused about Istio partial support for udp
@Xunzhuo You could try using ServiceEntry and "fake" the udp or just expose the UDP port directly through another load balancers since i assume you already have a load balancer ready...

I am trying to setup a custom DNS server for use internally but alas the only valid option aside from using envoy filters to redirect the UDP directly to the service is to simply dedicate a UDP load balancer are run the Service itself in LoadBalancer mode...

What confuses me is why Gateway supports UDP but virtual service does not... For the love of me i cant figure out how to route traffic from ingressgateway to the service directly ( even if it means bypassing istio - as they only route it at the moment )
@howardjohn maybe you have some insights?

P.S: here is an envoy that should work in theory
`apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: udp-route
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
    - applyTo: LISTENER
      patch:
        operation: MERGE
        value:
          name: "0.0.0.0_53"
          udp_listener_config:
            udp_listener_name: raw_udp_listener
            stat_prefix: udp
  - applyTo: CLUSTER
    patch:
      operation: ADD
      value:
        name: "raw_udp_cluster"
        connect_timeout: "10s"
        type: STATIC
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: "raw_udp_cluster"
          endpoints:
            - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: dnsmasq.ovpn.svc.cluster.local
                      port_value: 53`

**Comment by howardjohn** [comment]
There is no UDP support in istio at all. This is tracked in https://github.com/istio/istio/issues/1430.

**Comment by lightoyou** [comment]
> address: dnsmasq.ovpn.svc.cluster.local


I have just followed the [blog](https://www.zhaohuabing.com/istio-guide/docs/tricks/udp-listener/]. However, DNS notation doesn't seem to work. 

You need to use the services internal  fix IP.... I can confirm that this is a big problem to not support discovery.

Given that [EnvoyGateway](https://gateway.envoyproxy.io/v0.3.0/user/udp-routing/) supports UDP, I don't know why a project as big as Istio isn't able to provide UDP support. It's really sad since it's a game changer.

**Comment by samzong** [comment]
> > address: dnsmasq.ovpn.svc.cluster.local
> 
> I have just followed the [blog]([https://www.zhaohuabing.com/istio-guide/docs/tricks/udp-listener/]](https://www.zhaohuabing.com/istio-guide/docs/tricks/udp-listener/%5D). However, DNS notation doesn't seem to work.
> 
> You need to use the services internal fix IP.... I can confirm that this is a big problem to not support discovery.
> 
> Given that [EnvoyGateway](https://gateway.envoyproxy.io/v0.3.0/user/udp-routing/) supports UDP, I don't know why a project as big as Istio isn't able to provide UDP support. It's really sad since it's a game changer.

Hi, @lightoyou 

Can you give me some usage scenarios for UDP? I also have similar needs and am currently exploring. If you have more usage scenarios, I look forward to your reply.

**Comment by lightoyou** [comment]
Hi Samzong,

My scenarios are "limited", I would like to expose game servers/a public DNS server and be able to benefit from the telemetry offered by Istio.

I would like to use Istio as a Mesh service and profit of the Gateway.  I don't want to install another Gateway that supports UDP...
In addition, projects such as Knative, which supports the Istio gateway by default, are being considered for downscaling to zero some service.


Regards.
