### ISSUE TITLE
Support more options against http request  in Route Rule besides http header

### ISSUE THREAD

**Issue by morvencao** [istio/istio#4460]
`Istio` now has support selecting rule based on HTTP headers. 
For example, we can define a rule that apply to an incoming request if it includes a “cookie” header that contains the certain substring.

But in many case, developers need make a content-based routing rule which depends on http body or request payload... 
Although we got a workaround to add respective http header, but that needs extra effort when integrating applications with `Istio`.

So maybe adding more options against http request in Route Rule will be a good choice. 

/cc @todkap @gyliu513

**Comment by ZackButcher** [comment]
The general rule is that Istio does not operate on the bodies of requests. There are a lot of reasons for this:

- it helps protect PII data inside of requests
- it keeps logic more general (by working on metadata, rather than directly on data, which depends on the app's business logic)
- from an operational perspective it's expensive to ship the entire request over the wire compared to sending just metadata about the request
- it defeats caching in Mixer and in Envoys, harming the performance of the system

The solution to get this style behavior is to:
1. Implement a customer filter in Envoy which extracts data from the body and attaches it to a header
1. Implement a proxy that extracts data from the request body and attaches it to a header before forwarding the request on
1. Update the existing Envoy Mixer filter to extract additional attributes/values from the request body and attach them as attributes

I do not think that we will update Istio to allow decisions based on request body in general.

/cc @louiscryan @rshriram @frankbu @geeknoid for opinions here.

**Comment by kyessenov** [comment]
Re 3: We deliberately decided not to parse request bodies in Mixer. There
is a proposal for a mediation engine as a replacement. That is option 2,
but directed through Mixer. Option 1 using a custom lua filter, for
example, is always on option, provided it fits your performance
requirements.

**Comment by geeknoid** [comment]
​Two points to raise on this topic:

- We are actively looking at allowing Mixer to influence routing decisions
by issuing preconditions checks in the client sidecar. Orthogonally, for
API management, we may introduce an attribute that delivers the first N
bytes of a request to Mixer (say 256 bytes), making this payload available
to adapters. This means that a small portion of the payload could be used
to influence routing. This is per discussions in the API management
community.

- Also as part of API management, we will likely introduce at some point a
first class notion of "mediation engine". An ME gets to see and modify full
payload along the way. An ME is a distinct service, it's not built into
sidecars throughout the mesh. So there will be a network hop to talk to
such things. Of course, until we have specific support for this notion,
it's readily possible to achieve the same thing by composing services
together by hand.

And sorry, we don't have dates for either of these features. They're on the
longer-term plan, but implementing these hasn't been scheduled yet.

Thanks.
​

**Comment by jwalcorn** [comment]
Has anything further happened in this space?  Such as that first point in the last comment from June 18th?  If not, any outlook?  Thanks!

**Comment by kyessenov** [comment]
@jwalcorn Re: point 1, see https://github.com/istio/istio/pull/9088
