### ISSUE TITLE
TestGatewayHostnames/resolution_recovered flake

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#44776]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/44551/unit-tests-arm64_istio/1654324796432846848

**Comment by dddddai** [comment]
I suspect it's because the timeout is too low
https://github.com/istio/istio/blob/79f86336def89f22222bd00a77e8126a278299ef/pilot/pkg/model/network_test.go#L39

https://github.com/istio/istio/blob/79f86336def89f22222bd00a77e8126a278299ef/pilot/pkg/model/network_test.go#L116
Does this happen frequently in prow?

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/44681/unit-tests_istio/1654509021794668544 as well fyi

**Comment by hanxiaop** [comment]
First time seeing this in release-1.18 branch https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/44461/unit-tests-arm64_istio_release-1.18/1654748324340699136

**Comment by dddddai** [comment]
Let me fix this

**Comment by hanxiaop** [comment]
It seems like this has been fixed. I didn't see the same test failure after https://github.com/istio/istio/pull/44792 was merged.
