### ISSUE TITLE
istio.alpn fliter

### ISSUE THREAD

**Issue by liuqi-sun** [istio/istio#45542]
Is there documentation for istio.alpn fliter? What's this for?

**Comment by ksubrmnn** [comment]
ALPN is a TLS extension that allows the client and server to mutually agree upon a protocol for communication during the TLS handshake. You can find more information on ALPN as a general concept [here](https://www.keycdn.com/support/alpn)

I don't see any information in the docs about the istio.alpn filter, but I have created an issue to track it [here](https://github.com/istio/istio.io/issues/13418)

The custom Istio ALPN filter is responsible for rewriting the the regular protocol headers (e.g. http1.1, h2, etc.) to istio prefixed headers (e.g. istio-h2). When the server sees an "istio" prefixed protocol header, it expects a client certificate. If the client certificate is not present, the server drops the request since it is expecting Istio-managed mTLS.

**Comment by howardjohn** [comment]
Covered in https://github.com/istio/istio.io/issues/13418

**Comment by liuqi-sun** [comment]
> ALPN is a TLS extension that allows the client and server to mutually agree upon a protocol for communication during the TLS handshake. You can find more information on ALPN as a general concept [here](https://www.keycdn.com/support/alpn)
> 
> I don't see any information in the docs about the istio.alpn filter, but I have created an issue to track it [here](https://github.com/istio/istio.io/issues/13418)
> 
> The custom Istio ALPN filter is responsible for rewriting the the regular protocol headers (e.g. http1.1, h2, etc.) to istio prefixed headers (e.g. istio-h2). When the server sees an "istio" prefixed protocol header, it expects a client certificate. If the client certificate is not present, the server drops the request since it is expecting Istio-managed mTLS.

Thank you very much
