### ISSUE TITLE
Make Circleci Test Result Available on Testgrid

### ISSUE THREAD

**Issue by hklai** [istio/istio#4578]
Post submit test results from Prow are available in testgrid (https://k8s-testgrid.appspot.com/istio). It is very useful as per test case breakdown is visualized. 

Since many developers rely on circleci as well, it will be valuable to make circleci publish test results to testgrid as well.

**Comment by hklai** [comment]
Mostly done.

Remaining items:
1. Create a wiki page about testgrid setup.
2. Reevaluate the circle/prow jobs and add the missing jobs to the istio testgrid page.
3. Fix the hardcoded links to k8s in testgrid.

**Comment by hklai** [comment]
@chxchx 

Please fix testgrid as:
1. Some test jobs are out of sync.
2. Some job failed in parsing test log (https://k8s-gubernator.appspot.com/build/istio-circleci/presubmit/test/124574)

**Comment by chxchx** [comment]
The job list has been in sync in already.

Offhand, the parsing error seems to be due to go-junit-report outputting `<testcase classname="trace" name="TestValidate/[1]_10%!"(MISSING) time="0.000"></testcase>` in the junit.xml. This only seems to happen for circleci, since the same line for prow test is `<testcase classname="trace" name="TestValidate/[1]_10%" time="0.000"/>`.

The specific test case is located here https://github.com/istio/istio/blame/master/mixer/adapter/stackdriver/trace/trace_test.go#L360.

Initailly, I thought this problem is due to go-junit-report versions. Circle CI uses a base image built 5 days ago https://github.com/istio/istio/blame/master/.circleci/config.yml#L7 and according to the Dockerfile the image always uses the latest go-junit-report. Prow uses a base image built 2 months ago https://github.com/istio/test-infra/blame/master/prow/config.yaml#L359.

However, I have removed the go-junit-report source and binary from my machine and reinstall the latest, dump [the log](https://circleci.com/gh/istio/istio/124574) from the same job aforementioned, and start the parsing locally, but then I was unable to reproduce the same `!"(MISSING) ` issue.

I am out of ideas. Any circleci experts we could bring in for help?

**Comment by hklai** [comment]
Both post submit and daily are out of sync for sure, as the new jobs are yet not showing up. 

Also, we probably should figure out how we handing branching in testgrid, as tests are diverging in different branches.

**Comment by costinm** [comment]
grep -v "(MISSING)" for now - to get it moving...

**Comment by costinm** [comment]
I mean - remove the offending line, you can also use sed s/(MISSING)//

Also grep for MISSING in the junit code.

**Comment by chxchx** [comment]
Or maybe update the test case from `{"10%", &config.Params_Trace{SampleProbability: 0.1}, false},` to `{"10percent", &config.Params_Trace{SampleProbability: 0.1}, false},`, so we don't use special characters?

**Comment by hklai** [comment]
It will be best to fix the post processing job to handle these more gracefully instead of chasing the tests. and the same can probably happen to other tests.

**Comment by hklai** [comment]
Reopen as the % fix is not complete and there are some other pending items.

**Comment by hklai** [comment]
@chxchx 
https://k8s-testgrid.appspot.com/istio-presubmits#presubmit does not show any rows as well.
And what is the difference between that and https://k8s-testgrid.appspot.com/istio-presubmits#unit-tests-presubmit?

Can we drop the -presubmit suffixes on https://k8s-testgrid.appspot.com/istio-presubmits#unit-tests-presubmit as they are already implied from the tab?

**Comment by chxchx** [comment]
https://github.com/istio/istio/blob/master/prow/istio-presubmit.sh builds and pushes docker images and then run the integration tests.

https://github.com/istio/istio/blob/master/prow/istio-unit-tests.sh runs all unit tests and runs after presubmit.sh has finished. 

I made a PR to generate junit report for presubmit.sh https://github.com/istio/istio/pull/6750

I will removed the `-presubmit` suffix in another PR.

**Comment by hklai** [comment]
@chxchx 
Thanks. I think we are still missing the circle cloudfoundry test in presubmit. Please add and check if there is anything else missing (and that existing pages all work).

It looks like we need to remove those integration tests as they no longer run.
https://github.com/istio/istio/pull/6752/files

**Comment by hklai** [comment]
Consider done.
