### ISSUE TITLE
tools/gen_istio_image_list.sh is broken

### ISSUE THREAD

**Issue by rittneje** [istio/istio#46008]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

The tools/gen_istio_image_list.sh script is broken.

First, the regex it uses to check the version number that is supplied is wrong. It only allows a single digit for each component, and thus is unusable for any version >= 1.10.0. The proper regex is `^[0-9]+\.[0-9]+\.[0-9]+`.

https://github.com/istio/istio/blob/18c73bb98e3fa7cafb120eccbc86d5f667b4ca18/tools/gen_istio_image_list.sh#L142

Even after fixing that issue, the script does not function. I tried running `./tools/gen_istio_image_list.sh --version 1.16.5` but it did not output anything.

Running the script without any parameters, which is supposed to use the latest version, does not work either.

### Version

```Text
n/a
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by Douglas235** [comment]
That's really a question. Can I have a try?

**Comment by bkrugery** [comment]
So far, this is broken and here's why:

Line 67 - bad regex - needs to be corrected.  
```
    TAGS="$(curl --silent 'https://api.github.com/repos/istio/istio/tags' | grep -o '"name": "[0-9]\+\.[0-9]\+\.[0-9]\+"' | tr -d '"' )"
```

Worse yet:
Starting at 1.14.0 - the format of https://github.com/istio/istio/blob/release-1.14/tools/istio-docker.mk  has changed. 

This one is still okay, but won't help. https://github.com/istio/istio/blob/release-1.13.5-patch/tools/istio-docker.mk

Debug output is showing this:
```
?= docker.pilot docker.proxyv2 docker.app docker.app_sidecar_ubuntu_xenial \
?= docker.pilot docker.proxyv2 docker.app docker.app_sidecar_ubuntu_xenial docker.app_sidecar_ubuntu_bionic docker.app_sidecar_ubuntu_focal docker.app_sidecar_debian_9 \
?= docker.pilot docker.proxyv2 docker.app docker.app_sidecar_ubuntu_xenial docker.app_sidecar_ubuntu_bionic docker.app_sidecar_ubuntu_focal docker.app_sidecar_debian_9 docker.app_sidecar_debian_10 docker.app_sidecar_centos_8 docker.app_sidecar_centos_7 \
```

I am still trying to debug this to get a sane list so this can be built to ship in an airgapped network without parsing templates through. 

:/

@howardjohn - The build logic changed - is there a way we can generate a list of dependencies for containers we can just pull from docker.io rather than having to clone the whole repo or rebuild everything ?

**Comment by bkrugery** [comment]
I think I will have an incoming patch here that should work with everything 1.13.9 and below and 1.14.0 and above. 
I'll need some feedback (or someone can patch it) to let me know if certain things aren't needed..
