### ISSUE TITLE
Istio metrics returns grpc_response_status "2" (UNKNOWN) instead of actual response status code while using GRPC-WEB libraries

### ISSUE THREAD

**Issue by TomWizen** [istio/istio#46138]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When a client uses GRPC-WEB library reaches a destination_service via ingress gateway, the metrics do not show the actual response status code received and instead raises the count of response_status_code "2". 

The query im using is: `sum(rate(istio_requests_total{destination_canonical_service="[[service_name]]", request_protocol="grpc"}[2m])) by (grpc_response_status)`

It is only happening with GRPC-WEB. when I tested it with `grpcurl` the metric worked as expected. 

Information:
Client - angular using nice-grpc-web@3.1.0 (also tried with grpc-web@1.4.2)
Server - nodejs 16.x using nice-grpc@1.2.2(happens on scala/rust as well)

Would appreciate your help.

### Version

```Text
client version: 1.16.1
control plane version: 1.16.2
data plane version: 1.16.2 (20 proxies)
Client Version: v1.26.1
Kustomize Version: v4.5.7
Server Version: v1.23.8
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by howardjohn** [comment]
maybe related to https://github.com/envoyproxy/envoy/issues/27201?

**Comment by howardjohn** [comment]
But maybe not, that seems scoped to logs. But sounds similar

**Comment by TomWizen** [comment]
Hey, thank you for your response.
I have checked the access logs and added the GRPC_STATUS_NUMBER, still I only see response status (2). 
Also tried it with proxyv2:1.18.2 (envoy - 1.26.4-dev) and got the same result.

any other suggestions or insights?

**Comment by thiagomata** [comment]
please reopen

**Comment by smosca-coralogix** [comment]
This seems to happen because the [grpc-web filter clears out the trailers](https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/http/grpc_web/grpc_web_filter.cc#L353-L354), which would then be used by the [istio stats filter](https://github.com/istio/proxy/blob/master/source/extensions/filters/http/istio_stats/istio_stats.cc#L796-L799) to produce the metric tag. The response status gets defaulted to 0 in [another grpc utility](https://github.com/envoyproxy/envoy/blob/92bec5e9ee987d833f33d93f8ab3c6a7d03ad75c/source/common/grpc/status.cc#L6).

In terms of solutions, the only technically correct solution I think is to parse the trailers again from the response body, since another filter might change it after the trailer is cleared from the http response, but this might incur some major performance overhead unless we already buffer the response body somewhere else.

Or maybe there is a way to delay the clearing of the trailers until after the stats are produced? I'd be open to create a PR, but I'm definitely not an expert on envoy internals, so suggestions are definitely welcome!

**Comment by loeffel-io** [comment]
what is the state here, does this land in some release? also seeing 500s for grpc-web traffic, while with grpcurl seeing 200s
