### ISSUE TITLE
L4 Telemetry in Ambient Profile: destination_service_name value is unknown

### ISSUE THREAD

**Issue by josunect** [istio/istio#46169]
**Describe the feature request**

destination_service_name value is unknown in the telemetry generated in L4 when running Ambient profile. This is preventing the Service nodes to be shown in the Kiali graph.

Ex. 

`istio_tcp_sent_bytes_total{reporter="source",source_workload_namespace="bookinfo",source_cluster="Kubernetes"}`

`istio_tcp_sent_bytes_total{app="ztunnel", connection_security_policy="mutual_tls", controller_revision_hash="f457db478", destination_app="details", destination_canonical_revision="v1", destination_canonical_service="details", destination_cluster="Kubernetes", destination_principal="spiffe://cluster.local/ns/bookinfo/sa/bookinfo-details", destination_service="unknown", destination_service_name="unknown", destination_service_namespace="unknown", destination_version="v1", destination_workload="details-v1", destination_workload_namespace="bookinfo", instance="10.244.2.4:15020", job="kubernetes-pods", namespace="istio-system", pod="ztunnel-t2w9m", pod_template_generation="1", reporter="source", request_protocol="tcp", response_flags="-", sidecar_istio_io_inject="false", source_app="productpage", source_canonical_revision="v1", source_canonical_service="productpage", source_cluster="Kubernetes", source_principal="spiffe://cluster.local/ns/bookinfo/sa/bookinfo-productpage", source_version="v1", source_workload="productpage-v1", source_workload_namespace="bookinfo"}`

![image](https://github.com/istio/istio/assets/49480155/94d2eb62-0ce7-47ba-8ff1-2dde4b3b2700)

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[X] Ambient
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

Tested in kind with Istio 1.19-dev and Kiali

**Comment by linsun** [comment]
@ymesika any comment? I recall this used to work.

**Comment by jmazzitelli** [comment]
The issue seems to be only raw TCP traffic is where the problem is happening. We are seeing good L4 telemetry for HTTP traffic. But surprisingly, we see no L4 telemetry for raw TCP traffic.

See my replication procedures to see this issue: https://github.com/kiali/kiali/issues/6415#issuecomment-1652362180

Here's the Prometheus telemetry that doesn't look right: https://github.com/kiali/kiali/issues/6415#issuecomment-1652401524

Specifically:
```
destination_service="unknown"
destination_service_name="unknown"
destination_service_namespace="unknown"
```

**Comment by ymesika** [comment]
This is not surprising because currently the Ztunnel is not setting the labels you mentioned (or to be more accurate always set them to `unknown`). So all metrics that are scraped from the Ztunnels (L4 metrics) those labels will not be set.

If you have add a waypoint to the deployment then it will provide those labels for the HTTP traffic (like the sidecars today).

What's actually surprising me is that you've mentioned:
> We are seeing good L4 telemetry for HTTP traffic.
because if by "good" you mean the labels are set with correct values then I guess it's Kiali (?) that sets the missing destination service labels on the L4 metrics with the labels from the L7 metrics. I'm not entirely sure how it can happen today only for HTTP traffic because Ztunnel doesn't "know" about HTTP/TCP and just emits the L4 metrics.
Do you have an example of such metrics?

**Comment by josunect** [comment]
> 

What I can see is that the HTTP traffic is also missing the destination_service_name (See the metrics from the description, this is from bookinfo and it is HTTP traffic). 

But I can see that the destination_canonical_service is reported. So, I wonder, it is not possible for ztunnel to set the destination_service_name and destination_service_namespace fields?

**Comment by ymesika** [comment]
Currently in ztunnel `destination_canonical_service` == `destination_app`.
I need to check whether with current destination information we have in ztunnel any service labels can also be set.

**Comment by jmazzitelli** [comment]
> Do you have an example of such metrics?

see https://github.com/kiali/kiali/issues/6415#issuecomment-1651918670

That's all the telemetry I have for this small test. And you can see what Kiali graph looks like with this - noticed the green HTTP edge: https://github.com/kiali/kiali/issues/6415

BTW: AFAIK, Kiali never adds or takes away labels - it takes what Prometheus gives.

**Comment by josunect** [comment]
> 

No, there are no waypoint proxies here.

**Comment by jshaughn** [comment]
Hi @ymesika,  I think you can ignore what's above regarding the HTTP edge in https://github.com/kiali/kiali/issues/6415.  That's not an Ambient namespace, the edge was generated with sidecars.

As for the reported L4 telemetry issue, we did see a difference in the ztunnel telemetry for raw TCP request vs an HTTP request.  Maybe the difference is due to a different reason,  but the difference was there.  All of the L4 telemetry is missing `destination_service_name`.  Raw TCP was also missing `destination_service` and `destination_service_namespace`.

The difficulty at the moment is knowing whether the missing information (as compared to the non-ambient telemetry) is a bug or a "to-do", in the Ambient telemetry, or if it's "the way it will be with Ambient".   Consumers of telemetry, like Kiali, will be affected by differences.  Certain information is critical to visualization, like these destination fields.   For Kiali, or other tooling/graphs/etc that Istio users have developed, it will be hard to support Ambient without knowing what Ambient telemetry will provide.

**Comment by ymesika** [comment]
@josunect I'm not sure 1.19.0-alpha include the recent changes around those labels.
I ran the bookinfo locally and is seems like `destination_service` is set correctly on both source and destination reporters.

**Comment by josunect** [comment]
> @josunect I'm not sure 1.19.0-alpha include the recent changes around those labels. I ran the bookinfo locally and is seems like `destination_service` is set correctly on both source and destination reporters.

Thank you @ymesika . I will check again when 1.19 is released.

**Comment by jmazzitelli** [comment]
@josunect , to test with the latest (and not have to wait for an alpha release, you can grab the latest istio 1.19 build from the last commit of the 1.19 branch by downloading using the Kiali team's hack script (this is NOT the alpha release; the Istio project has automation where a new Istio distribution is built and published after each commit).

` hack/istio/download-istio.sh -div 1.19-dev`

That will download the istio tarball for that latest 1.19 build. There is a -o option to store it in a custom location.

This script is found here: https://github.com/kiali/kiali/blob/master/hack/istio/download-istio.sh

To then install that 1.19 dev build, you can use [our other hack script](https://github.com/kiali/kiali/blob/master/hack/istio/install-istio-via-istioctl.sh), telling it to use the scripts default hub (these dev builds pull their images from a development image repository, not the usual gcr.io location):

`hack/istio/install-istio-via-istioctl.sh -ih default`

(pass in `--config-profile ambient`, too, if you want to install with ambient)

**Comment by josunect** [comment]
> @josunect , to test with the latest (and not have to wait for an alpha release), you can grab the latest istio 1.19 build from the last commit of the 1.19 branch by downloading using the Kiali team's hack script (this is NOT the alpha release; the Istio project has automation where a new Istio distribution is built and published after each commit).
> 
> ` hack/istio/download-istio.sh -div 1.19-dev`
> 
> That will download the istio tarball for that latest 1.19 build. There is a -o option to store it in a custom location.
> 
> This script is found here: https://github.com/kiali/kiali/blob/master/hack/istio/download-istio.sh
> 
> To then install that 1.19 dev build, you can use [our other hack script](https://github.com/kiali/kiali/blob/master/hack/istio/install-istio-via-istioctl.sh), telling it to use the scripts default hub (these dev builds pull their images from a development image repository, not the usual gcr.io location):
> 
> `hack/istio/install-istio-via-istioctl.sh -ih default`
> 
> (pass in `--config-profile ambient`, too, if you want to install with ambient)

Thanks, @jmazzitelli ! I've found the script very useful, and this is what I was using. Now it downloads istio-1.19-alpha._hash_

**Comment by josunect** [comment]
I was testing Kiali with Istio 1.19 and it looks like the telemetry graph still has duplicated edges: 

![image](https://github.com/istio/istio/assets/49480155/3337a9ab-7fcc-4c3d-9183-8d9f1cf64558)

The query for `istio_tcp_received_bytes_total{reporter="destination",destination_workload_namespace="default"}` returns `unknown` for `destination_service` and `destination_service_name`: 

![image](https://github.com/istio/istio/assets/49480155/10a9dfca-a321-4a13-b971-f0f6dafef428)


It can be reproducible following the steps in: https://istio.io/latest/docs/ops/ambient/getting-started/

**Comment by jshaughn** [comment]
Shall we open a new issue or should this one be re-opened?
