### ISSUE TITLE
Report telemetry from client proxy

### ISSUE THREAD

**Issue by bianpengyuan** [istio/istio#4647]
To track works for telemetry report from downstream proxy. This includes both in-mesh client report and egress traffic report.

cc @douglas-reid @mandarjog

**Comment by mandarjog** [comment]
Bian, we already report telemetry on egress.

**Comment by mandarjog** [comment]
We need to add a Boolean or enum attribute to denote client or serverside reports.

**Comment by douglas-reid** [comment]
We want to make sure that we can report for an TCP pass-thru traffic as well -- whatever is involved. As @mandarjog notes, having an attribute like `context.mode` or something with `client` and `server` values will be important.

Part of this work will also likely include refactoring our default metrics to better present a client/server dichotomy, as well as updating dashboards to show incoming/outgoing requests per service (depending of course on our chosen path for workload/service association).

A couple of e2e tests that we will need likely include:
- Fault Injection and Circuit-Breaking reporting
- Ingress Report()ing for non-mesh services
- Differences between client and server side latencies

**Comment by kyessenov** [comment]
I think we need to have a dimension for the _reporter_ that matches values in the space of `source` or `destination` IDs. Then maybe you can query `reporter == source` condition. It leaves an option for a reporter that is a middle proxy. Envoy has a notion of a _node_ that is consistently and pervasively used:
https://github.com/envoyproxy/data-plane-api/blob/master/envoy/api/v2/core/base.proto#L40

We only use id and cluster fields in istio.

For TCP, it might be difficult to establish correlation since there is no unique request ID. A connection from a source is hard to correlate to a connection on the destination. Probably cumulative metrics, like total bytes sent or received are generally meaningful for under-specified protocols.

**Comment by douglas-reid** [comment]
I like the idea of a `context.reporter` or `telemetry.reporter` attribute.

There was some work on TCP connection IDs that @JimmyCYJ was working on awhile back (https://github.com/istio/proxy/pull/1166). For raw TCP, bytes tx/rx are all we report on today.

**Comment by jmazzitelli** [comment]
I just wanted to note in this github issue a related problem that hopefully will be fixed when this issue is addressed: see https://groups.google.com/forum/#!topic/istio-users/B13_XatU8s8

**Comment by douglas-reid** [comment]
Why did we close this issue?  I don't believe we consider the work fully done.

**Comment by douglas-reid** [comment]
@kyessenov can you provide a small summary of your work to-date on this issue here?

**Comment by kyessenov** [comment]
All proxies report telemetry. The quality of reported data is not always on par with the server-side telemetry.  There are cases of "unknown" or missing destination service. There are a few follow-up PRs in flight to improve on the data.

**Comment by kyessenov** [comment]
https://github.com/istio/istio/pull/6310 should get rid of the hack of deriving destination service attributes.

**Comment by jmazzitelli** [comment]
Do we know if client-side reporting of telemetry is available in the 1.0 work yet (e.g. in the https://github.com/istio/istio/tree/release-1.0.0-snapshot.0 branch)?

**Comment by kyessenov** [comment]
The next snapshot to be shipped today-ish should have this feature enabled, and displayed on dashboards. There are some caveats that we are going to document.

**Comment by kyessenov** [comment]
Should be done. Regressions/bugs should be tracked independently from this issue at this point.
