### ISSUE TITLE
CA certs regression

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#46600]
Since https://github.com/istio/istio/pull/45291 we change the cert logic. This can break if we have cases where old versions start after new versions.

Can reproduce with

```
istioctl-master install --revision=new
istioctl-1.19 install --revision=old
```

```
2023-08-18T20:53:55.257635Z     info    initializing mesh handlers
2023-08-18T20:53:55.257695Z     info    model   reloading network gateways
2023-08-18T20:53:55.257704Z     info    creating CA and initializing public key
2023-08-18T20:53:55.257720Z     info    Using istiod file format for signing ca files
2023-08-18T20:53:55.257734Z     info    Use local CA certificate
2023-08-18T20:53:55.257814Z     error   failed to create discovery service: failed to create CA: failed to create an istiod CA: failed to create CA KeyCertBundle (cannot verify the cert with the provided root chain and cert pool with error: x509: certificate signed by unknown authority)
Error: failed to create discovery service: failed to create CA: failed to create an istiod CA: failed to create CA KeyCertBundle (cannot verify the cert with the provided root chain and cert pool with error: x509: certificate signed by unknown authority)
```

TBH I am not really sure when someone is installing old version after new since I think it works in the other direction.  but we should look into it at least

**Comment by jaellio** [comment]
On it.

**Comment by jaellio** [comment]
I believe I have identified the issue. First I'll walk through what secrets/ca certs are created in the scenario described above.

When installing istio based on master (in this case I'll refer to it as istio v1.20), a `cacerts` k8s secret is created and populated with a self-signed certificate generated by istio. As a result of #45291, a `cecerts` secret is created instead of a secret named `istio-ca-secret`. This behavior is as expected.

When installing istio v1.19 after install v1.20 as the older revision an error occurs as described above and istiod fails to become ready. Istiod v1.19 sees the `cacerts` secret as a [pluggin certificate](https://github.com/istio/istio/blob/release-1.19/pilot/pkg/bootstrap/istio_ca.go#L461). This is acceptable behavior so long as we are comfortable forgoing the automatic rotation process supported by istio generated self-signed certificates (see [selfsignedcarootcertrotator](https://github.com/istio/istio/blob/experimental-ambient/security/pkg/pki/ca/selfsignedcarootcertrotator.go)). Istiod attempts to [verify the key cert bundle from the file](https://github.com/istio/istio/blob/experimental-ambient/security/pkg/pki/util/keycertbundle.go#L70) (since `cacerts` is volume mounted to istiod). The `cacerts` secret will be similar to the following:

```yaml
apiVersion: v1
data:
  ca-cert.pem: <ca cert>
  ca-key.pem: <private key>
  cert-chain.pem: ""
  istio-generated: ""
  key.pem: ""
  root-cert.pem: ""
kind: Secret
metadata:
  creationTimestamp: "2023-08-22T20:49:54Z"
  name: cacerts
  namespace: istio-system
  resourceVersion: "633"
  uid: 05154879-9879-424f-8110-64b0c1784477
type: istio.io/ca-root
```
Note that the `root-cert.pem` key exists, but is not set. The file will exist but it will be empty. This is the expected data for a self-signed, istio-generated ca cert secret. However, when istiod attempts to `VerifyAndSetAll` the `rootCertBytes` will be `nil`. As a result, [`Verify`](https://github.com/istio/istio/blob/experimental-ambient/security/pkg/pki/util/keycertbundle.go#L284) will fail since it appears the cert doesn't have a root and is signed by an unknown authority. The `nil` `rootCertBytes` is [handled elsewhere in the code](https://github.com/istio/istio/blob/experimental-ambient/security/pkg/pki/ca/selfsignedcarootcertrotator.go#L190) by [copying the contents](https://github.com/istio/istio/blob/master/security/pkg/pki/util/generate_csr.go#L115) of `ca-cert.pem` before attempting to verify the certificate bundle. 

I have verified this is the cause of the error by manually editing the `cacerts` secret and copying the value of `ca-cert.pem` to the value of `root-cert.pem`. I then restarted istiod and it started successfully. 

There are a couple of ways we could fix this regression:
1. Update v1.19 to handle a nil `rootCertBytes` when verifying a pluggin cert.
2. Update master to automatically set the contents of `root-cert.pem` to the value of `ca-cert.pem` when building the `cacerts` secret.
3. Do both 1 and 2.

**Comment by hzxuzhonghu** [comment]
detailed analyze，i would vote 2
