### ISSUE TITLE
AKS disable automounting API credentials - Istiod and istio-ingressgateway

### ISSUE THREAD

**Issue by harsimrit** [istio/istio#46884]
We have deployed Istio 1.19.0 to our AKS cluster. As part of the security scanning by MS defender, we have a security non compliance to disable automounting API credentials for all the pods running on the cluster. The remediation from the MS defender is to set the automountServiceAccountToken to false.

Istio was installed using istioctl.

For the application pods we have been able to set the automountServiceAccountToken flags to false but we are unable to do the same for istio and istio-ingressgateway. It seems the IstioOperator manifest does not suport this flag  under KubernetesResourcesSpec.

My question(s) are
1. Is it possible to set this flag? if yes than how can we set the flag?  
2. If this is not supported in the current release, is there any plan to enable this?

**Comment by cnvergence** [comment]
I don't think setting this flag is supported, you can check setting this configuration: https://istio.io/latest/docs/ops/best-practices/security/#configure-third-party-service-account-tokens to make it work with third party tokens

**Comment by howardjohn** [comment]
Istiod cannot possibly run with this setting... that is how we access the API server.

I am quite confident that its not a "compliance" issue to have this set, otherwise you couldn't run _any_ controller in your cluster. Its likely a recommendation.

Istio-ingress doesn't need this so I wouldn't mind a change there.

**Comment by hzxuzhonghu** [comment]
istio-ingressgateway need it too, it uses the token to connect to istiod

**Comment by howardjohn** [comment]
@hzxuzhonghu it mounts a custom one though, so I think we do not need the auto-mounted one. Should double check though

**Comment by harsimrit** [comment]
Thank you for taking the time to look at this. The issue is that the security expectation is that all pods should have the auto mounting of service account token disabled but if the particular service account needs the token, then it should be projected to a volume. We also use MS workload identity which uses the service account token to generate a Azure Active Directory token for use later and it projects this token to the volume dir.  I was hoping that there is a way to do the same for istiod and istio-ingressway where the service account token can be projected on the  volume dir instead of being auto mounted. This would allow the introduction of the automountServiceAccountToken flag to KubernetesResourcesSpec

**Comment by keithmattix** [comment]
To @howardjohn's earlier point, istiod _must_ have an automounted token because it's the controller that projects SA tokens on the other workloads (specifically sidecar pods and gateways). That security expectation theoretically wouldn't allow _any_ Kubernetes controllers (cert-manager, cross plane, etc). I will note, however that istiod should be considered a privileged workload in your security model and only cluster admins should be able to install/configure it
