### ISSUE TITLE
Istio Sidecar causes handleRequestError/Z_BUF_ERROR errors on EKS applications

### ISSUE THREAD

**Issue by dgdevops** [istio/istio#47125]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hello Everyone,
After upgrading to Istio v1.14.6 our NodeJS based applications (using zlib) with Istio Sidecar (`proxyv2:1.14.6`) report `Z_BUF_ERROR` errors on their console. 

Examples are below:
`{"startTime":"2023-09-25T06:02:45.771Z","categoryName":"clientRequest.js","level":"ERROR","RID":"OMITTED","settings":{"url":"http://OMITTED.svc.cluster.local:8098/OMITTED","method":"PUT","timeout":50000,"encoding":null,"headers":{"Cache-Control":"no-cache","Pragma":"no-cache","Content-Type":"text/html","X-OMITTED-Meta-CorrelationId":"OMITTED"},"translateToAllLocales":false,"body":"<span></span>"},"error":"Z_BUF_ERROR"}`

`{"startTime":"2023-09-26T19:13:44.111Z","categoryName":"riak.js","level":"ERROR","url":"http://OMITTED.svc.cluster.local:8098/OMITTED","error":"Z_BUF_ERROR","fx":"handleRequestError"}`

The errors occur right after the workload is restarted with the new sidecar image (`proxyv2:1.14.6`), downgrading the sidecar back to `proxyv2:1.13.9` and restarting the workloads solves the issue immediately, no more errors on the console. We have tested multiple version of Istio sidecar starting from `1.14.0-alpha.0` to `1.15.0`, the `Z_BUF_ERROR` is experienced with all these versions. In addition to that the Istio sidecar version `1.17.0` was also tested and we have the same issue and errors.

The error occurs with the connection to one of our internal NoSQL instances on TCP port `8098`, in case this port is excluded on the sidecar using the `traffic.sidecar.istio.io/excludeOutboundPorts` annotation the error is no longer present. This makes us believe that some traffic management/handling related change was introduced to the Istio sidecar from version `1.14.0` that potentially causes our connections to get truncated. The `tcpdump` performed on the sidecar container shows neither HTTP problems nor TCP errors.

We have reviewed the Istio (1.14) & Envoy (1.22) change logs but could not pinpoint the root cause of the issue yet.
Do you have any suggestion what sidecar change that was introduced in version 1.14 could be causing the issue?

Any suggestion or troubleshooting tip is appreciated

### Version

```Text
$ istioctl version                                                                                                                                  
client version: 1.19.0
control plane version: 1.14.6
data plane version: 1.14.6 (4 proxies)

$ kubectl version --short                                                                                                                           
Client Version: v1.23.6
Server Version: v1.24.16-eks-2d98532
```

**Comment by dgdevops** [comment]
Hello @howardjohn,
Do you have any idea what change from version 1.14 could trigger the error?

**Comment by hzxuzhonghu** [comment]
Guess this is related to max connection buffer size or something, not sue what changed on 1.14

BTW, what is `Z_BUF_ERROR `

**Comment by dgdevops** [comment]
Hello @hzxuzhonghu,
Thank you for your response.
Based on my research the `Z_BUF_ERROR` indicates that the output buffer is full, it can also be caused by a corrupted download (potentially because of the full buffer). I have adjusted the sidecar log level to debug but I see no indication of an error.

**Comment by sandeeplamb** [comment]
here are more debug logs 
`
{"preview":false,"result":{"log":"2023-10-09T13:32:57.901369601Z stderr F {\"level\":\"debug\",\"time\":\"2023-10-09T13:32:57.901317Z\",\"scope\":\"envoy router\",\"msg\":\"[C2869][S14900529670936466081] router decoding headers:\\n':authority', 'SERVICE_ENDPOINT:8098'\\n':path', '/buckets/internal_ep/keys/%2Ffragments%2Fhome%2Fhighlights%2Fen-gb%3FtargetDevice%3Ddesktop'\\n':method', 'PUT'\\n':scheme', 'http'\\n'cache-control', 'no-cache'\\n'pragma', 'no-cache'\\n'content-type', 'text/html'\\n'x-riak-meta-correlationid', 'scheduler-homePage-1696858371505, scheduler-virtual-1696858371505'\\n'accept-encoding', 'gzip, deflate'\\n'content-length', '13'\\n'x-forwarded-proto', 'http'\\n'x-request-id', '16346074-590e-90fb-85b5-d7f25079db03'\\n'x-envoy-decorator-operation', 'SERVICE_ENDPOINT:8098/*'\\n'x-envoy-peer-metadata', 'CERT_DATA=='\\n'x-envoy-peer-metadata-id', 'sidecar~PRIVATE_IP~svc-en-gb-67cfb6bcc6-tbprh.int_SVC_1~int_SVC_1.svc.cluster.local'\\n'x-envoy-expected-rq-timeout-ms', '5000'\\n'x-envoy-attempt-count', '1'\\n\"}"}}
{"preview":false,"result":{"log":"2023-10-09T13:32:57.90135359Z stderr F {\"level\":\"debug\",\"time\":\"2023-10-09T13:32:57.901293Z\",\"scope\":\"envoy router\",\"msg\":\"[C2869][S14900529670936466081] cluster 'outbound|8098||SERVICE_ENDPOINT' match for URL '/buckets/internal_ep/keys/%2Ffragments%2Fhome%2Fhighlights%2Fen-gb%3FtargetDevice%3Ddesktop'\"}"}}
{"preview":false,"result":{"log":"2023-10-09T13:32:57.90128176Z stderr F {\"level\":\"debug\",\"time\":\"2023-10-09T13:32:57.901226Z\",\"scope\":\"envoy connection\",\"msg\":\"[C2869] current connecting state: false\"}"}}
{"preview":false,"result":{"log":"2023-10-09T13:32:57.90126913Z stderr F {\"level\":\"debug\",\"time\":\"2023-10-09T13:32:57.901200Z\",\"scope\":\"envoy http\",\"msg\":\"[C2869][S14900529670936466081] request headers complete (end_stream=false):\\n':authority', 'int-svc.on-prem.svc.cluster.local:8098'\\n':path', '/buckets/internal_ep/keys/%2Ffragments%2Fhome%2Fhighlights%2Fen-gb%3FtargetDevice%3Ddesktop'\\n':method', 'PUT'\\n'cache-control', 'no-cache'\\n'pragma', 'no-cache'\\n'content-type', 'text/html'\\n'x-riak-meta-correlationid', 'scheduler-homePage-1696858371505, scheduler-virtual-1696858371505'\\n'accept-encoding', 'gzip, deflate'\\n'content-length', '13'\\n'connection', 'close'\\n\"}"}}
{"preview":false,"result":{"log":"2023-10-09T13:32:57.901205819Z stderr F {\"level\":\"debug\",\"time\":\"2023-10-09T13:32:57.901159Z\",\"scope\":\"envoy http\",\"msg\":\"[C2869] new stream\"}"}}
{"preview":false,"result":{"log":"2023-10-09T13:32:57.900481401Z stderr F {\"level\":\"debug\",\"time\":\"2023-10-09T13:32:57.900409Z\",\"scope\":\"envoy conn_handler\",\"msg\":\"[C2869] new connection from PRIVATE_IP:53148\"}"}}
{"preview":false,"result":{"log":"2023-10-09T13:32:57.915723514Z stderr F {\"level\":\"debug\",\"time\":\"2023-10-09T13:32:57.915659Z\",\"scope\":\"envoy conn_handler\",\"msg\":\"[C2869] adding to cleanup list\"}"}}
{"preview":false,"result":{"log":"2023-10-09T13:32:57.915719424Z stderr F {\"level\":\"debug\",\"time\":\"2023-10-09T13:32:57.915641Z\",\"scope\":\"envoy connection\",\"msg\":\"[C2869] closing socket: 1\"}"}}
{"preview":false,"result":{"log":"2023-10-09T13:32:57.915710694Z stderr F {\"level\":\"debug\",\"time\":\"2023-10-09T13:32:57.915625Z\",\"scope\":\"envoy connection\",\"msg\":\"[C2869] write flush complete\"}"}}
{"preview":false,"result":{"log":"2023-10-09T13:32:57.915613423Z stderr F {\"level\":\"debug\",\"time\":\"2023-10-09T13:32:57.915549Z\",\"scope\":\"envoy connection\",\"msg\":\"[C2869] setting delayed close timer with timeout 1000 ms\"}"}}
{"preview":false,"result":{"log":"2023-10-09T13:32:57.915609523Z stderr F {\"level\":\"debug\",\"time\":\"2023-10-09T13:32:57.915544Z\",\"scope\":\"envoy connection\",\"msg\":\"[C2869] closing data_to_write=205 type=0\"}"}}
{"preview":false,"result":{"log":"2023-10-09T13:32:57.915472272Z stderr F {\"level\":\"debug\",\"time\":\"2023-10-09T13:32:57.915426Z\",\"scope\":\"envoy http\",\"msg\":\"[C2869][S14900529670936466081] encoding headers via codec (end_stream=true):\\n':status', '204'\\n'vary', 'Accept-Encoding'\\n'server', 'envoy'\\n'date', 'Mon, 09 Oct 2023 13:32:57 GMT'\\n'content-type', 'text/html'\\n'content-encoding', 'gzip'\\n'x-envoy-upstream-service-time', '13'\\n'connection', 'close'\\n\"}"}}
{"preview":false,"result":{"log":"2023-10-09T13:32:57.915459922Z stderr F {\"level\":\"debug\",\"time\":\"2023-10-09T13:32:57.915405Z\",\"scope\":\"envoy http\",\"msg\":\"[C2869][S14900529670936466081] closing connection due to connection close header\"}"}}
{"preview":false,"result":{"log":"2023-10-09T13:32:57.915450452Z stderr F {\"level\":\"debug\",\"time\":\"2023-10-09T13:32:57.915369Z\",\"scope\":\"envoy router\",\"msg\":\"[C2869][S14900529670936466081] upstream headers complete: end_stream=true\"}"}}
`

**Comment by dgdevops** [comment]
Based on @hzxuzhonghu's recommendation we have tried adding the `Accept-Encoding` header to our VirtualService using `headers.request.set.Accept-Encoding: '*'` and it is confirmed to be working fine.
Adding the reference ticket to this one: https://github.com/istio/istio/issues/39706
Thank you for your help @hzxuzhonghu
