### ISSUE TITLE
Add support for preStop in gateway chart

### ISSUE THREAD

**Issue by saitama-gh** [istio/istio#47265]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
A way to add a preStop configuration to the Istio Gateway deployment.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by hanxiaop** [comment]
Why do you need this in the chart? Have you tried https://istio.io/latest/docs/setup/additional-setup/customize-installation-helm/?

**Comment by howardjohn** [comment]
Why do you want it in the first place?

**Comment by clayvan** [comment]
@howardjohn 
I would imagine for the same reason people are using the Istio Operator's patch configuration to set this.
https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2131#issuecomment-1097290120

I know the history of this chart was to not add "too many" kubernetes resource spec properties as helm templated values and rather point users to using Kustomize on top, but I think there's a healthy balance needed as more and more users are migrating from Istio Operator to the helm charts.

PreStop, configuration of probes, terminationgraceperiods, etc are all used heavily by ingress controllers charts to ensure zero downtime deployments and should be first class for any ingress controller chart (gateway in this case).

Example of what I'm trying to achieve:
ALB target group health check using ASG instances + istio gateway nodeport service. The most aggressive ALB TG health check you can set is
```
      unhealthy_threshold = 2
      healthy_threshold   = 2
      interval            = 5
```
From my understanding that means the fastest time for a new gateway pod to appear in the ALB TG will be 10 seconds.
However an Istio gateway pod can pass ReadinessProbe within a few seconds, which means during a rolling restart of the deployment, the next replica is allowed to begin its termination. Theoretically all gateway pods could be replaced by the time the first pod gets added to the ALB TG.

Forget a rolling restart, any `kubectl delete pod` on an ingress gateway will cause a 5xx without a preStop as ALB's can't be updated in time. It's why AWS's ingress controller has pod readinessgates https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.1/deploy/pod_readiness_gate/

With preStop, we could add a 20 second `sleep` which would allow the TG to drain the terminated gateway AND register the new replica before moving onto the next replica.

Hopefully I'm misunderstanding something, but please let me know if I can provide more information.

EDIT:
actually while I was typing this, I tried to achieve zero downtime deployment using a combination of
- injecting my own preStop hook
- using environment variable `MINIMUM_DRAIN_DURATION`
- Setting this config mesh wide: drainDuration, parentShutdownDuration, terminationDrainDuration

None of which allowed me to get a successful zero downtime.

The 5xx's happen when the ALB TG removes one of the old gateway pods, but that Pod is still running in a Terminating state waiting for connections to drain.

This is confusing to me and now I'm even more sure I'm missing something.

**Comment by howardjohn** [comment]
`terminationDrainDuration` is the field I would expect users to set. But if none of those three are working it may be an ALB level issue; not super experienced with AWS so its a bit unclear to me.

**Comment by clayvan** [comment]
@howardjohn 
So came back with more learnings as to why I don't think this is specific to AWS ALB's:
- My preStop attempt to sleep wasn't working because I'm using the distroless container (more specifically the tetrate fips build).
- Specifically this comment https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2131#issuecomment-1480287893 is what made me think that `MINIMUM_DRAIN_DURATION` would be what I want. However this does not achieve the same thing as the preStop, so I think that comment was a bit misleading.
- You mention `terminationDrainDuration` but even that is more to do with the time envoy is allowed to let connections drain.

I'm already using `EXIT_ON_ZERO_ACTIVE_CONNECTIONS` and `terminationGracePeriodSeconds` to achieve up to X minutes of graceful terminations and confirm this works.

The problem I'm facing now is that there is X number of seconds between the cloud load balancer seeing the nodePort fail a readiness check, and the time Envoy starts rejecting new connections.

I believe that's what preStop achieves, the pod will be marked as Terminating, but the envoy proxy will still be accepting new connections as it hasn't been issued the SIGTERM yet.

In fact, I switched my proxies to not use distroless so I have access to `sleep` and sure enough I get 0 downtime.

So I do agree whole-heartedly that preStop is the only way for istio gateways currently to achieve 0 downtime and it should be added to the helm chart, as the edge LB will always need X time to de-register an endpoint before the Envoy proxy should be sent the SIGTERM and stop accepting connections.

That being said, preStop won't work for my use case of the distroless container, so I think it makes more sense to have an Istio pilot-agent configuration. Something like `terminationDelay: 30s` that will take the SIGTERM and accept new connections for the configuration's duration.

At this point, I'm massively scope-creeping on this Issue request and I would like to take this conversation to wherever you feel is most appropriate.

**Comment by hzxuzhonghu** [comment]
>The problem I'm facing now is that there is X number of seconds between the cloud load balancer seeing the nodePort fail a readiness check, and the time Envoy starts rejecting new connections.

I am sure we do drain listeners immediately when the container receives SIGTERM, rather than that after X seconds it start rejecting new connections

**Comment by den-is** [comment]
Istio setup in my organization requires this feature too.
I've created PR which should do this https://github.com/istio/istio/pull/48956

**Comment by akamac** [comment]
The same use case for me. I used to have preStop hook configured for Nginx Ingress + AWS ALB for zero downtime ingress updates.
