### ISSUE TITLE
LEAST_REQUEST is RANDOM

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#47804]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

It appears LEAST_REQUEST is not working in Istio Envoys because the stats for computing the active requests per cluster are disabled.

### Version

```Text
All versions
```

**Comment by kyessenov** [comment]
CC @zirain @tonya11en @howardjohn (per offline discussions)

**Comment by tonya11en** [comment]
For posterity, this explains the reaosning:
https://github.com/istio/istio/issues/46554#issuecomment-1804363707

**Comment by incfly** [comment]
We also recently encountered this issue. For others: using destination rule to [disable](https://github.com/istio/istio/issues/46569#issuecomment-1739105813) `locality settings` fixed the issue.
```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
[...]
  trafficPolicy:
    loadBalancer:
      localityLbSetting:
        enabled: false
[...]
```

Per my understanding, this is because Envoy consider the Priority, then locality, and only then using load balancer algorithm on per locality endpoints, as [documented](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/locality_weight)

In our case, we have 3 pods each pod in one AZ. So effectively least request lb becomes round robin.

Meanwhile the dependency on cluster should not be an issue, as I see https://github.com/envoyproxy/envoy/issues/7652#issuecomment-520562531 it has been fixed a while ago.

@howardjohn  @kyessenov @ramaraochavali  I found it would be confusing/hard to investigate. If the analysis above looks right to you, I want to make some documentation change on our DestinationRule API. So users would know the need to turn off locality settings if needed. WDTY?

**Comment by ramaraochavali** [comment]
Sorry for the delay

> In our case, we have 3 pods each pod in one AZ. So effectively least request lb becomes round robin.

This is confusing to me. Why would it be round robin? Do you mean random based on client locality?

**Comment by incfly** [comment]
> Why would it be round robin? Do you mean random based on client locality?

@ramaraochavali  Sure, let me clarify: 

1. an Istio gateway pod has its own availability/locality, say it's us-west-2a
2. upstream service is a 3 pod k8s stateful set service, in us-west-2a, us-west-2b, us-west2-c respectively.
3. When `trafficPolicy. loadBalancer.enabled` is set to false(default), gateway pod would first look at its local endpoint. Because it has highest priority.  least request load balancer is only applied after priority and locality is selected. https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/locality_weight 
> Pick [priority level](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/priority#arch-overview-load-balancing-priority-levels).
> Pick locality (as described in this section) within priority level from (1).
> Pick endpoint using cluster specified load balancer within locality from (2).
4. doing least request lb within one pod is no-op. -> effectively round-robin.

So if we have 6 pods, 2 per AZ, the LR lb is load balancing within 2 pods, not among 6 pods. So I think it's worth mentioning in api/doc.
