### ISSUE TITLE
Local pre-submit tests

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#480]
Pre-submit tests in Istio Pilot trigger istio/istio tests that are difficult to execute locally. We need to provide a way to trigger istio/istio tests from within istio/pilot with a shell script or simple instructions.

**Comment by Brian-Xincheng-Zhang** [comment]
Diem Wu will help (he hasn't registered in github yet)

**Comment by sebastienvas** [comment]
I think this is resolved now. You can run prow/pilot-e2e-smoketest.sh from
pilot repo.

On Aug 17, 2017 4:09 PM, "Brian-Xincheng-Zhang" <notifications@github.com>
wrote:

Diem Wu will help (he hasn't registered in github yet)

—
You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub
<https://github.com/istio/istio/issues/480#issuecomment-323218073>, or mute
the thread
