### ISSUE TITLE
Webhooks broken if install is aborted in middle

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#48112]
```
$ istioctl install
✔ Istio core installed
- Processing resources for Istiod. Waiting for Deployment/istio-system/istiod                                                                                                                                      
^C
$ istioctl install
Error: failed to install manifests: errors occurred during operation: creating default tag would conflict:
Error [IST0139] (MutatingWebhookConfiguration istio-sidecar-injector) Webhook overlaps with others: [istio-revision-tag-default/namespace.sidecar-injector.istio.io]. This may cause injection to occur twice.
Error [IST0139] (MutatingWebhookConfiguration istio-sidecar-injector) Webhook overlaps with others: [istio-revision-tag-default/object.sidecar-injector.istio.io]. This may cause injection to occur twice.
Error [IST0139] (MutatingWebhookConfiguration istio-sidecar-injector) Webhook overlaps with others: [istio-revision-tag-default/rev.namespace.sidecar-injector.istio.io]. This may cause injection to occur twice.
Error [IST0139] (MutatingWebhookConfiguration istio-sidecar-injector) Webhook overlaps with others: [istio-revision-tag-default/rev.object.sidecar-injector.istio.io]. This may cause injection to occur twice.
```

**Comment by hanxiaop** [comment]
This is due to the default webhook being deactivated after successful installation, and then the new installation re-applies it without `ProcessDefaultWebhook` again after successfully installation, which leads to conflicting webhooks (with the tag webhook). How about we clean the tag webhook in this case, since the installation with istioctl hasn't been successful yet?

**Comment by hanxiaop** [comment]
> How about we clean the tag webhook in this case, since the installation with istioctl hasn't been successful yet?

However, the post-process logic only works when the installation has failed, not when it is interrupted. Maybe moving the webhook analyzer after the installation is completed could be another solution, which can still warn users about the webhook issue, and do not prevent users from installing again.

**Comment by hanxiaop** [comment]
> detect this ahead of time and go straight to webhook 2?

This sounds good to me. I can work on it since I think I had a similar PR that was trying to solve this issue https://github.com/istio/istio/pull/44865/files#diff-525ae81754807c29a4ae13370ad8e74c7948b57128c60967939feeeea4c8184fR550. However, the idea of generating a deactivated version of webhook 1 seems a bit hacky compared to directly analyzing webhook 2. I'll try to split it into a separate PR and revise it with better logic.

**Comment by cnvergence** [comment]
that long-lived PR should also fix that, we can prepare some upgrade test for it with unsuccessful installation

**Comment by hanxiaop** [comment]
> hey folks, this means that this issue is still valid #43932
> that long-lived PR should also fix that, we can prepare some upgrade test for it with unsuccessful installation

This should be a similar situation as the default webhook was not correctly being deactivated. I'll check your PR
