### ISSUE TITLE
Add back schema validation in the istio/enhancements repo

### ISSUE THREAD

**Issue by ericvn** [istio/istio#48211]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

Currently, there is an optional test, validate-features, to validate schema in the istio/enhancements repo which now fails since the schema validation was removed from istio/tools in https://github.com/istio/tools/pull/2533. Another test that used this tool, the release notes, was updated in https://github.com/istio/tools/pull/2531 to do the validation directly.

We should add the validation back, so the validate-features test will actually test schemas. 

**Describe alternatives you've considered**

I don't think we want to add the tool back in istio/tools, but we could maybe do something similar to what was done in release-notes.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[x] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by mike-weiner** [comment]
**Quick summary**: 
In https://github.com/istio/tools/pull/2531, the `schema-validator` binary (`cmd/schema-validator/validate.go`) still existed in the `istio/tools` repo, but a new package was created (`pkg/schemavalidation`) so other tools could pull in the schema validation logic. This is what happened with the (`gen-release-notes`) binary - it now does the schema validation inline without needing the schema validation binary itself. 

In https://github.com/istio/tools/pull/2533, the `schema-validator` binary was removed completely. That didn't break `gem-release-notes` since it was updated in https://github.com/istio/tools/pull/2531 to use the new `schemavalidation` package right inside the `gen-release-notes` binary. In https://github.com/istio/test-infra/pull/4830, the `scripts/validate_schema.sh` script was removed and this broke the `istio/enhancements` repo since it [still looks for](https://github.com/istio/test-infra/blob/master/prow/config/jobs/enhancements.yaml#L11) this script.

**Potential solutions**: 

1. Add the `schema-validator` binary back to `istio/tools` and `scripts/validate_schema.sh` back to `istio/test-infra`.
2. I thought that maybe the `istio/enhancements` repo might have another PR test that we could change to use the `schemavalidation` package to do the validation inline (just like `gen-release-notes`), but it doesn't look like there are any other jobs.

It looks like `istio/enhancements` is the only repo that still expects this `scripts/validate_schema.sh` script: https://github.com/search?q=org%3Aistio%20validate_schema.sh&type=code

@ericvn - You mentioned above that `we could maybe do something similar to what was done in release-notes` - what did you have in mind? Since `istio/enhancements` does not have any other jobs...it seems like adding the schema-validator binary & bash script back to their respective repos would be an equivalent option.

**Comment by craigbox** [comment]
hit this in https://github.com/istio/enhancements/pull/186.
