### ISSUE TITLE
Ambient upgrade docs

### ISSUE THREAD

**Issue by linsun** [istio/istio#48387]
[P0] Users can upgrade from Alpha to the next version, with proper documentation to guide users. Small window of downtime is acceptable.
[P1] automated testing on doc page.

Priority is L4 first.

It would be great if we can have some automated tests for this, as we'll need this work for every single build to claim beta. :)

**Comment by zengyuxing007** [comment]
From the existing architecture of Ambient, upgrading the ztunnel component will cause existing pods on the node to lose their connections, leading to a partial loss of traffic.

I would like to know if there is a way for us to mitigate this issue， thanks ~

**Comment by bleggett** [comment]
> From the existing architecture of Ambient, upgrading the ztunnel component will cause existing pods on the node to lose their connections, leading to a partial loss of traffic.
> 
> I would like to know if there is a way for us to mitigate this issue， thanks ~

We discussed this topic in the [June 14th Ambient contributor meeting](https://docs.google.com/document/d/1SMlwliEnthgq7r2PjpLl1kCq3t8rAMbgu6r_lDAXJ0w/edit#heading=h.uph0clj4a3t4) - while other options were discussed, the community decision was to document and advise node cordoning as the only mechanism for upgrading ztunnel in production.

**Comment by zengyuxing007** [comment]
Perhaps we could consider an in-kernel implementation as an optional alternative to address the current drawbacks of ztunnel.

**Comment by linsun** [comment]
@zengyuxing007 yep what @bleggett said was what was discussed in upstream dev meetings. If you have a different proposal using in-kernel impl, i would suggest you write up a design doc and present it in one of our weekly ambient upstream dev meetings, which we could consider post beta.  Thanks!

**Comment by bleggett** [comment]
> If ztunnel crashed, it could lead to impaired traffic for all pods on the node, resulting in an unacceptably large blast radius, which would be difficult to tolerate in a production environment where Istio ambient is being utilized.

Yep, that's previously been discussed as a drawback of ambient. If you're worried about that, sidecars are still available and fully resilient, at the cost of resource usage.

> Perhaps we could consider an in-kernel implementation as an optional alternative to address the current drawbacks of ztunnel.

Yep, but even with in-kernel, you would still have to make the tradeoff between single-point-of-failure for the entire node, or duplicating proxy functionality for every pod.

This has also been discussed - there are nontrivial challenges to replicating all necessary functionality of a secure L4 node proxy in eBPF kernelspace, which is why ztunnel exists in the first place.

**Comment by zengyuxing007** [comment]
> there are nontrivial challenges to replicating all necessary functionality of a secure L4 node proxy in eBPF kernelspace in a safe and useful way

Thanks for your reply~   @linsun @bleggett 

There is indeed some debate around this topic, and the key point may lie in the implementation of zero trust （L4 LB and dns proxy can be implemented  easily using eBPF). 
Istio achieves this by utilizing mTLS  or HBONE  protocols. We might consider that implementing such features at the kernel level could be challenging. However, an alternative approach might involve using IPsec + eBPF(tc), which separates authentication and encryption, thereby enabling us to implement these security measures at a lower network layer.

At the L4 level, there is basically no difference between AuthorizationPolicy and NetworkPolicy. All common user functions can be covered by NetworkPolicy (podSelector and  namespaceSelector).   We can also simply get the servicename or some information like SPIFFE SVID of the podIp via bpf map, not necessarily via TLS (X.509).

Btw, in China, zero trust is not an immediate need, probably only little financial business will have a need because of compliance.  If mTLS is not enabled, do we still need ztunnel?   

So, I think we might be able to offer a non-ztunnel implementation of L4 for a large percentage of users. And it can provide higher stability and performance. In terms of stability, the implementation in the kernel does not take up user resources, will not cause abnormalities due to node resources, its sla is basically consistent with the node's life cycle, the node hangs, the user will not blame istio problems.

In addition, there is no need like the user process (ztunnel) to maintain the tcp connection, so it won't be upgraded to cause tcp be drained or be closed. We only need to consider how to implement graceful upgrade in the control plane.

**Comment by bleggett** [comment]
> > there are nontrivial challenges to replicating all necessary functionality of a secure L4 node proxy in eBPF kernelspace in a safe and useful way
> 
> Thanks for your reply~ @linsun @bleggett
> 
> There is indeed some debate around this topic, and the key point may lie in the implementation of zero trust （L4 LB and dns proxy can be implemented easily using eBPF). 

Yep, that's certainly part of it, but not all of it. Istio does more than just that, and has cross-cluster/cross-node scalability concerns that eBPF can't really help with.

> Istio achieves this by utilizing mTLS or HBONE protocols. We might consider that implementing such features at the kernel level could be challenging. However, an alternative approach might involve using IPsec + eBPF(tc), which separates authentication and encryption, thereby enabling us to implement these security measures at a lower network layer.

Yes, this is the tack Cilium has taken. It is also arguably why they have (so far) struggled to actually produce a conformant mTLS implementation - TLS 1.3 by design cryptographically ties authentication and encryption together at the protocol level, for very good security reasons. FIPS compliance, IIRC, in fact requires this.
 
 There are tradeoffs with both approaches. We chose to lean on TLS 1.3 at the protocol level, as it is a very strong, very well-tested and audited protocol that solves for security holes that can arise when authentication and encryption are decoupled.
 
 But even aside from that - rather than asking how we could move into the kernel, a better question to ask is "what moving into the kernel actually gains us", in terms of measurable benefits. Given the complexity of solving the above for our current requirements and featureset, our current contention is "practically, very little".

> Btw, in China, zero trust is not an immediate need, probably only little financial business will have a need because of compliance. If mTLS is not enabled, do we still need ztunnel?

Yes, I think it's a similar story in the US - Istio as a project wants to have strong zero-trust fundamentals in place, however, as a matter of first principles and defaults.

> So, I think we might be able to offer a non-ztunnel implementation of L4 for a large percentage of users. And it can provide higher stability and performance. In terms of stability, the implementation in the kernel does not take up user resources, will not cause abnormalities due to node resources, its sla is basically consistent with the node's life cycle, the node hangs, the user will not blame istio problems.

One of the core values of Istio is standards-compliant mTLS that can pass external audits and be FIPS compliant, so offering something that drops those is not currently something that fits our value proposition.

> In addition, there is no need like the user process (ztunnel) to maintain the tcp connection, so it won't be upgraded to cause tcp be drained or be closed. We only need to consider how to implement graceful upgrade in the control plane.

Until you need to upgrade the eBPF progs, at which point you have the same problem.

**Comment by zengyuxing007** [comment]
>There are tradeoffs with both approaches, and both have their merits. Istio chose to lean on TLS 1.3 at the protocol level, as it is a globally-used, very strong, very well-tested and very well-audited protocol that solves for security holes that can arise when authentication and encryption are decoupled.

I understand that these are trade-offs, i.e. what is the first priority for istio, whether it is security, stability or performance.
If it's zero trust, I think it's a little off. Because there aren't many users who have a need for this.  
Different users may focus on different needs, but stability is certainly very important.  
Adopting eBPF down to the kernel certainly solves the stability problem of user-state processes. It would also better if ztunnel was deployed as a multicopy instance or had a fallback mechanism.


>But even aside from that - rather than asking how we could move into the kernel, a better question to ask is "what moving into the kernel actually gains us", in terms of measurable benefits.

I have tested both (eBPF implement and ztunnel , Two different L3/L4 implementations) for stability and performance. Under the premise of relatively consistent functionality, we can get higher stability and performance.  

First of all, why will be more stable, eBPF is essentially a L3 implementation, do not have to maintain the state of the tcp connection, naturally, there is no tcp connection is disconnected and other issues, the business process does not feel its tcp connections be closed.  In addition, there is no user space process in the data plane, it will not be killed because of node resources or other reasons, the data plane upgrade is basically atomized, of course, the control plane needs to pay attention to the configuration of the graceful switching, the overall implementation is not more complex than the implementation of the ztunnel.

Another reason why performance is higher. mTLS requires 2 or 3 RTT for a new connection and the eBPF L3 implement is zero RTT. most notably, the eBPF implement there is no user-state and kernel-state switching.  Performance comparisons can be a bit controversial, based on the same benchmark, I compared the before and after implementations. 140% improvement in L4 QPS, 230% improvement in L7 QPS. (The main reason for the increase in L7 is that ztunnel's current upstream connection pool is single-ip and single-connection, which may be related to ztunnel's current connection pooling implementation strategy)  

Of course, the eBPF implementation has its drawbacks. There is no silver bullet. Less friendly for lower kernel versions.
But versions always evolve forward, and to summarize, we might be able to use the eBPF data plane as an optional option.

> Until you need to upgrade the eBPF progs, at which point you have the same problem. We want to use eBPF where it usefully removes a problem. If you have a problem and you just move it into the kernel, now you have a kernel problem :D

There are some issues to be aware of during the landing process, but in general it is much simpler. The main issue to be considered is how to upgrade the configuration gracefully.

>EDIT: I'd also refer to @howardjohn's blog on this topic, as he did a better job of laying out the above: https://blog.howardjohn.info/posts/wireguard-tls/

 I've read this blog by howardjohn before. It is related to the wireguard implementation. Maybe it has something to do with the fact that wireguard doesn't have USO turned on. IPsec doesn't have this problem.
