### ISSUE TITLE
The customConfigFile and proxy.v2 flags condition is not clear

### ISSUE THREAD

**Issue by crystaldust** [istio/istio#4841]
The code is here:
https://github.com/istio/istio/blob/cc84e301acc1fbf101349085a6b3b5098958f891/pilot/pkg/proxy/envoy/v1/watcher.go#L356

When `CustomConfigFile` is specified, then the `bootstrap.WriteBootstrap` logic(under `else if proxy.v2` branch) will never be reached. But within the `bootstrap.WriteBootstrap` logic, the `CustomConfigFile` arg is also used as conditions, it's used as the custom config template file path. So this part of logic will never be reached.

By the current logic with 3 if branches:
- branch1: **CustomConfigFile** is not empty => take the file specified by CustomConfigFile as envoy config file
- branch2: **CustomConfigFile** is empty and proxy.v2 is true => Since `CustomConfigFile` is empty,  the default template file `/var/lib/istio/envoy/envoy_bootstrap_tmpl.json` will be applied. **We can't specify our custom template file, unless we use env var 'ISTIO_BOOTSTRAP'**
- branch3: **CustomConfigFile** is empty and proxy.v2 is false => Write config to '/etc/istio/proxy/rev-0.json' and take it as envoy config file

**Comment by crystaldust** [comment]
I'm not quite sure of the context, maybe we can put the branches like this:
```golang
if proxy.v2 { // proxy.v2 is true
	// Call the bootstrap.WriteBootstrap logic
} else if len(proxy.config.CustomConfigFile) > 0 {
	// proxy.v2 is false, and CustomConfigFile is set
	// use the CustomConfigFile as config file
} else { 
	// proxy.v2 is false, and CustomConfigFile is not set
	// Write config to '/etc/istio/proxy/rev-0.json' and take it as envoy config file
}
```
It won't affect the original logic and the whole `bootstrap.WriteBootstrap` logic gets the chance to execute.
Any thought on this?

**Comment by rshriram** [comment]
@costinm ^^^

**Comment by costinm** [comment]
Yes, customconfigfile was used only for v1 - due to mixer/pilot config.

This got fixed yesterday - so we can start removing all the v1-related bootstrap. Or at least stop using it.

Note that for v2 the default template is replaced using an env variable: ISTIO_BOOTSTRAP
To avoid confusion and risk I would not reuse the customconfigfile, and I think env variables 
are more flexible and easier to use for this kind of customization.

The main blocking issue preventing the deprecation of the v1 bootstrap is the watcher - it's going
to go away once node agent  and SDS is finished.

**Comment by costinm** [comment]
In other words: branch 1 and 3 are for deprecated / likely dead code. Not removing it yet - post 0.8.

Branch 2 is the one that should be alive - with the env variable to override.

**Comment by costinm** [comment]
Added 1.0 as milestone to get rid of the v1 code and switch to SDS.
