### ISSUE TITLE
Trouble with multiple services with the same name in different namespaces

### ISSUE THREAD

**Issue by diemtvu** [istio/istio#4845]
As shortname is used for (one of) virtual_host domains, it causes `Duplicate entry of domain`

```log
external/envoy/source/common/config/grpc_mux_impl.cc:188] gRPC config for type.googleapis.com/envoy.api.v2.Listener update rejected: Only unique values for domains are permitted. Duplicate entry of domain sleep
```

**Comment by rshriram** [comment]
I thikn this is caused by the alt vhosts we generate (sleep, sleep.foo, sleep.foo.svc, etc.) - thanks to @ZackButcher for catching that.
Need to dedup the vhost.domains before we ship it.

**Comment by diemtvu** [comment]
Step to reproduce:

```bash
kubectl apply -f <(istioctl kube-inject --debug -f samples/httpbin/httpbin.yaml)
kubectl create namespace legacy
kubectl apply -f samples/httpbin/httpbin.yaml -n legacy
```

LDS going to have 2 virtual hosts with `httpbin` domain in both.

```json
"virtual_hosts": [
                    {
                      "domains": [
                        "httpbin.default.svc.cluster.local",
                        "httpbin.default.svc.cluster.local:8000",
                        "httpbin.default.svc.cluster",
                        "httpbin.default.svc.cluster:8000",
                        "httpbin.default.svc",
                        "httpbin.default.svc:8000",
                        "httpbin.default",
                        "httpbin.default:8000",
                        "httpbin",
                        "httpbin:8000",
                        "10.23.247.176",
                        "10.23.247.176:8000"
                      ],
                      "name": "httpbin.default.svc.cluster.local:8000",
                      "routes": [
                        {
                          ...
                        }
                      ]
                    },
                    {
                      "domains": [
                        "httpbin.legacy.svc.cluster.local",
                        "httpbin.legacy.svc.cluster.local:8000",
                        "httpbin.legacy.svc.cluster",
                        "httpbin.legacy.svc.cluster:8000",
                        "httpbin.legacy.svc",
                        "httpbin.legacy.svc:8000",
                        "httpbin.legacy",
                        "httpbin.legacy:8000",
                        "httpbin",
                        "httpbin:8000",
                        "10.23.250.66",
                        "10.23.250.66:8000"
                      ],
                },
```

**Comment by ZackButcher** [comment]
A little more context on the specific issue and how we're hitting it: today we push RDS info inside of the Listener (LDS) config. As part of that, we need routes to match on hostnames, and for ergonomic reasons we allow users to use short names or FQDNs. The shortnames overlap and cause issues.

An example to show what I mean: suppose we have service `foo` in namespace `default`; in k8s its FQDN is `foo.default.svc.cluster.local`. Suppose we have a second service `foo` in namespace `bar`; in k8s its FQDN is `foo.bar.svc.cluster.local`.

Today when we push RDS info the all Envoys in the mesh, we construct a list of acceptable names for `foo`; this looks like:
- `foo`, `foo.default`, `foo.default.svc.cluster.local`
- `foo`, `foo.bar`, `foo.bar.svc.cluster.local`

This error is because the two `foo` entries overlap with each other (i.e. its ambiguous which Route applies when the app uses a shortname).

To fix this, the route configuration that we produce needs to know the namespace of the sidecar its sending config to is in, so we can send the correct names:
- For a sidecar in namespace `default`, we should be pushing the names `{foo, foo.default, foo.default.svc.cluster.local}` and `{foo.bar, foo.bar.svc.cluster.local}`
- For a sidecar in namespace `bar` we should be pushing the names `{foo.default, foo.default.svc.cluster.local}` and `{foo, foo.bar, foo.bar.svc.cluster.local}`

**Comment by rshriram** [comment]
working on a fix
