### ISSUE TITLE
inpod iptable rules has not been removed when uninstall Istio

### ISSUE THREAD

**Issue by irisdingbj** [istio/istio#49067]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

1. install ambient profile
2. register httpbin pod into ambient
3. uninstall istio
4. the related iptable rules still exist. -- the related sockets removed correctly. 

### Version

```Text
master branch
```

**Comment by ilrudie** [comment]
cc @bleggett

**Comment by bleggett** [comment]
Yep, the recommended way to do this is (and which we need to add to the docs) is to unlabel namespaces/pods first (which should remove the redirection and iptables rules).

We do not, on CNI agent shutdown, walk thru all currently-captured pods and unhook them.

This is actually a bit tricky, because it impinges on CNI upgrade - if you are upgrading CNI, which is not part of the datapath, there's no reason for that upgrade to affect the datapath or redirection, and you wouldn't _want_ to unhook all currently-active pods.

If you are _fully uninstalling_ Istio and CNI, then yes, you might want to unhook all currently-captured pods.

The problem is, the CNI can't currently tell the difference between those two scenarios. We had the same problem with the old model.

Linking this to https://github.com/istio/istio/issues/49009

**Comment by zengyuxing007** [comment]
The previous bad parts of sidecar mode should not be left as a legacy.

We can use istioctl to differentiate whether to remove or uninstall, or default to uninstall, and the upgrade will have a flag saved under a CR like IstioStatus.
Is it ok to keep a list of current pods under mesh in Istio-cni and remove iptables under the business pod before the istio-cni pod is deleted?

**Comment by bleggett** [comment]
> The previous bad parts of sidecar mode should not be left as a legacy.

Agree, I think we can do better.

> We can use istioctl to differentiate whether to upgrade or uninstall, or default to uninstall, and the upgrade will have a flag saved under a CR like IstioStatus. 

Whatever we did do would have to work with vanilla Helm upgrades.

> Is it ok to keep a list of current pods under mesh in Istio-cni and remove iptables under the business pod before the istio-cni pod is deleted?

We need a semaphore of some kind - it doesn't have to be a pod list.

On uninstall if the semaphore is unset -> `istio-cni` is deleted, and first unhooks everything (disrupting traffic in captured pods)
On upgrade, if the semaphore is set -> `istio-cni` is deleted, and unhooks nothing, so that no traffic is disrupted. New `istio-cni` starts up, builds SoTW, maybe triggers some sort of repair checks on the previous pods in case we need to update iptables rules or something.

**Comment by zengyuxing007** [comment]
> > The previous bad parts of sidecar mode should not be left as a legacy.
> 
> Agree, I think we can do better.
> 
> > We can use istioctl to differentiate whether to upgrade or uninstall, or default to uninstall, and the upgrade will have a flag saved under a CR like IstioStatus.
> 
> Whatever we did do would have to work with vanilla Helm upgrades.
> 
> > Is it ok to keep a list of current pods under mesh in Istio-cni and remove iptables under the business pod before the istio-cni pod is deleted?
> 
> We need a semaphore of some kind - it doesn't have to be a pod list.
> 
> On uninstall if the semaphore is unset -> `istio-cni` is deleted, and first unhooks everything (disrupting traffic in captured pods) On upgrade, if the semaphore is set -> `istio-cni` is deleted, and unhooks nothing, so that no traffic is disrupted. New `istio-cni` starts up, builds SoTW (just like it does today on first run), maybe triggers some sort of out-of-band repair checks on the previous pods in case we need to update inpod iptables rules or something.

@bleggett  Yes, I'm talking about basically the same thing as you. the semaphore can be stored under a k8s resource and we need to know which are the pods we need to care about.

**Comment by bleggett** [comment]
Closing this in favor of https://github.com/istio/istio/issues/49009 since that's the actual issue here.
