### ISSUE TITLE
default ISTIO_META_DNS_CAPTURE to true

### ISSUE THREAD

**Issue by nmnellis** [istio/istio#49076]
**Describe the feature request**

ISTIO_META_DNS_CAPTURE has been available since Istio 1.8 and is used by many companies in production. Based on my experience this feature is mature and has minimal (if any) unintended impacts to being enabled. 

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[X] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by rvennam** [comment]
I helped a customer who was running a massive environment and they had issues with their DNS server being overloaded. This feature helped them significantly because Istio now performs the resolution.

**Comment by linsun** [comment]
@howardjohn thoughts? I recall you had some objections but don't remember details.

cc @istio/wg-networking-maintainers

**Comment by zirain** [comment]
something I can share, not sure anything updated

Since DNS Proxying has no cache capability, undeclared external domain names are still forwarded to upstream DNS servers each time they are requested. You may still encounter failures.

**Comment by keithmattix** [comment]
I'm a -1 on this; the DNS subsystem in Istio is not as battle-hardened or necessarily preferable to customers' default DNS provider. It's a great feature to be able to turn on, but slurping up users' DNS traffic by default feels dangerous to me

**Comment by christian-posta** [comment]
I'd argue this feature has been in battle for quite a long time now and from my perspective working with many of those large-scale battles, we always enable this by default. From a "battle tested" perspective I'd say this is battle tested. John I think raised some concerns in the past, but I wonder if those have been mitigated. Would be good to hear what he says.

**Comment by howardjohn** [comment]
I am also -1 on this. @costinm has some more context on why that he can better elaborate on than I

**Comment by costinm** [comment]
I am a bit more nuanced on this.


Strong -1 on the entire feature set getting promoted to stable or default.

However a subset of the feature - that is aligned with (real) DNS resolvers should be promoted and used in any environment lacking a secure DNS resolver in the platform - or in cases where platform resolver is slow or lacks ability to support 'split horizon'.

It should never be enabled in environments with a working, secure and standards compliant platform DNS resolver. 

And any feature that is not aligned with DNS practices should not be used. 

In particular auto-allocation of IPs in ServiceEntry or exposing ServiceEntry to DNS is  a normal and expected feature of a DNS resolver - however the granularity and controls around it are off and I think we need to fix them first. The 'proof', like in k8s Gateway, would be having a second implementation backed by a real DNS resolver.

A 'real' DNS resolver is suposed to check dns-sec, use doh/dot/etc when talking to upstream, cache all records, have strict controls and audits, observability and much more. We are not in the business of implementing a competing, complete secure DNS resolver - I hope.

**Comment by hzxuzhonghu** [comment]
I may have a slightly different view in one point.  Because Istio Serviceentry has been GA, and we highly depend on local DNS to provide DNS resolve capability for SE's host , without this SE can not be said GA

**Comment by costinm** [comment]
ServiceEntry can be used to program a "real" DNS resolver too -
external-dns does it for Services/Ingress/Gateway, plenty of tools to
automate that and
it can be done as an istio-ecosystem project.

It won't have the ability of Istio to have any namespace owner set DNS
entries to everyone - but that's a good thing. My concern is not with
having a feature to configure DNS entries - but with having too much
flexibility - and also little controls over who can do that, with strange
granularity that makes it impossible to use any other resolver.

A trimmed down DNS feature - perhaps aligned with ambient design ( with
option of per node or sidecar, with an actual address that can be set in
resolv.conf and
pod spec instead of depending on interception ) and with reduced feature
set is not a bad thing, and I won't debate if it should be on by default
or not - either is fine as long as the user can choose to use a 'real'
secure resolver and not get different behavior.

I do agree that ServiceEntry does need some form of DNS support - and just
like we have a minimal CA we can have a minimal DNS
resolver - but the feature set must be aligned and compatible with 'real'
DNS resolvers ( just like our CA design allows plugging a 'real'
full featured CA).

Just because the code has been merged long ago and it kind of works doesn't
make it production ready or an alternative
to a product that is specialized in DNS.

**Comment by ramaraochavali** [comment]
I think there are two different concepts here that we are debating
`DNS_CAPTURE` - Without this multi cluster stateful set functionalirty(specially TCP stateful sets like Zookeeper, HBase) doest not work. It is also needed for VM access to K8s Services. This is well tested by many companies I believe. I am +1 to enabling this by default
`DNS_AUTO_ALLOCATE` -  I am not sure if this has been battle tested. We use it and some other companies also seem to use it (based on issues raised). We may need proper IPAM to be 100% reliable on this. So I can go either way on this

**Comment by hzxuzhonghu** [comment]
@costinm Good input. istio DNS is not meant to provide complete capabilities of a DNS system, definitely some gaps with kube-dns.

**Comment by costinm** [comment]
Not so much kube dns as all 'enterprise' or 'managed' resolvers - I don't know if kube dns is checking dns-sec signatures and last I checked the DOT support was not best or enabled - and kube dns is restricted to a cluster.

As long as we restrict the features to a point where non-istio integrations are feasible - like we did for CA and as we are doing for telemetry - not bad to have a minimal 'reference implementation'. 

Tools like external dns allow use of real DNS for k8s and istio, and I think that is the ideal for a prod env.

**Comment by costinm** [comment]
@ramaraochavali - I generally agree. We MUST have the base DNS capture for environments lacking a secure resolver, and we must return DNS for service for VMs or cases where VPC-wide DNS are not possible. I have no concern with those 2 features - as long as we validate that the functionality can be substituted with 'real DNS'. 

We did the same for CA - we must have a minimal CA, but we also integrate with other CAs and usually make sure users are not forced to use our minimal CA by having unique features ( I know ambient is pushing this a bit ).

ServiceEntry is an entirely different story - not only the auto-allocation, but also the granularity and security model. There is a huge difference between Istio DNS acting as a secure cache/resolver - returning the same results as kube DNS or any other resolver - versus Istio injecting fake addresses with minimal security and depending on arcane 'exportTo/import' and visibility rules. Istio requires a secure DNS resolver - where fake IPs can't be injected, or our security doesn't work. We can't at the same time making it trivial for users with ServiceEntry permission to create fake DNS entries. 

I am not saying we should not have a mechanism to create 'split horizon'/internal IPs for non-K8S names - but we need a very serious security review and much stricter controls. Using ServiceEntry for this purpose is also not very clear to be the ideal model. 

As we all know, the review process in Istio is pretty broken - we start with 'experiments' where the review bar is pretty low, 
tell users they are safe to use in prod - and 1 year later we go back with 'experiments are used, we can no longer make changes, let's mark them as stable'. What is missing is the deep review that is needed before making a feature long-term supported.   That may be ok for some things - but DNS is so critical to both reliability and security that we need to do better.

**Comment by ramaraochavali** [comment]
>. As we all know, the review process in Istio is pretty broken - we start with 'experiments' where the review bar is pretty low,
tell users they are safe to use in prod - and 1 year later we go back with 'experiments are used, we can no longer make changes, let's mark them as stable'. What is missing is the deep review that is needed before making a feature long-term supported. That may be ok for some things - but DNS is so critical to both reliability and security that we need to do better.

+1

**Comment by dpasiukevich** [comment]
Also in K8S there's an optional feature [NodeLocalDNS cache](https://kubernetes.io/docs/tasks/administer-cluster/nodelocaldns/) for users which have high QPS cacheable traffic (spins up a CoreDNS cache proxy on each node of the cluster).

Having `ISTIO_META_DNS_CAPTURE=true` by default would result that Istio users that need to also have NodeLocalDNS, they would have 2 dns cache servers in the DNS resolution chain.

**Comment by mmerickel** [comment]
As a pretty basic user who wants to have some egress traffic control, I feel pretty trapped (no resolution) by this conversation.
- I need to use ServiceEntry to give istio the ability to control the traffic, and by definition it's external traffic to the mesh.
- I must use virtual ip addresses for non-http/tls traffic.
- The only way my pods will use those virtual ips is if istio captures the dns traffic and returns the virtual ip to my containers.
- For some reason istio does not capture this traffic by default so this is completely broken out of the box.

What am I supposed to do? I see people saying the feature isn't needed if you have "some other secure dns". What is the other dns that will tell deal with these virtual ips, where their only purpose in life is to work with istio? It seems to me that it is a required feature of istio to have this turned on in like 100% of deployments that want any visibility into non-mesh traffic?

**Comment by costinm** [comment]
Few comments: enabling this feature can have very serious security implications, as there is very little control on how DNS is generated. Having it on by default is IMO out of question - there is no good way to RBAC or control this. Users can still use it - but I am very concerned the documentation is not at all clear on the risks.

With ambient DNS capture having a different semantic ( it's no longer each pod getting a different DNS view ) it is even more complexity on any migration.

There are 2 main solutions for egress:
- use original DNS result. This is best option as the result may be signed with DNS-SEC, we don't want to peel off the dns security in Istio. For most cases with resolution NONE it works, in particular after John added targetPort.
- have clients make requests to an .internal name instead of the original DNS - and use a private zone.

The purpose of DNS-SEC and all the DNS security is to make sure that nobody can forge DNS entries - ServiceEntry
is not providing any  security checks, can be used cross namespace, etc. Given that Istio security is based on the result
of the DNS ( which is what we capture ) - and we are a security-focused product I think even users enabling it via ISTIO_META_DNS_CAPTURE may be at risk.

With ambient semantics ( per node, namespace isolation, etc) there may be a path to have a safe use of istio as a DNS 
resolver - but will need a very deep security review.

**Comment by ramaraochavali** [comment]
@costinm Are you referring to DNS_AUTO_ALLOCATE feature or DNS_CAPTURE feature?

**Comment by costinm** [comment]
DNS capture using ServiceEntry IPs.  From what I've seen it can't take over Service IPs - but not at all clear about external IPs. It is effectively a way to inject fake responses into DNS ignoring dns-sec. 

Can be fixed or used safely - with careful RBAC on ServiceEntry or disabling cross namespace visibility - but I don't think we have enough docs or review on the secure use. 

Typical split horizon DNS also allows overrides and bypassing dns-sec - but has clear access control. If used carefully and for users who don't have rsolvers with split horizon - it remains useful, but we need to keep it optional and restrict it so it's equivalent in security.

**Comment by mmerickel** [comment]
not stale
