### ISSUE TITLE
Consider splitting `istioctl proxy-config` to `istioctl ztunnel`

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#49841]
Today we have `istioctl pc workloads` to get info from ztunnel. I wonder if we should split this into `istioctl zc/ztunnel-config`. Ztunnel has many resources like Services, Workloads, Policies, etc. Having these grouped would simplify things and allow it to be easier to split things out. We also can make the `log` manipulation simple, etc.

**Comment by bleggett** [comment]
`istioctl pc workloads` is still _useful_ I think since it's what people reach for already, and I wonder if in e.g. mixed clusters it might not be handy to keep the unified semantics.

maybe use `k8s` style distinguishing prefixes, as filtering/targeting options?

`istioctl pc zt/workloads` `istioctl pc zt/services` > `istioctl pc workloads` gives you All The Things

**Comment by zirain** [comment]
if ztunnel won't support all featueres(bootstrap/ecds/cds/lds/nds) proxy/envoy had, SGTM.

**Comment by hanxiaop** [comment]
> if ztunnel won't support all featueres(bootstrap/ecds/cds/lds/nds) proxy/envoy had, SGTM.

Makes sense to me since those XDS configs are not applied to ztunnel. If we place it under `pc`, it would not only confuse users but also require us to maintain a separate and custom logic for ztunnel config. IIRC there were discussions about placing the command in the appropriate location previously, but the exact location had not been decided at that time.

**Comment by linsun** [comment]
split makes sense given quite some output from pc doesn't apply to ztunnel.
