### ISSUE TITLE
why appliction version must be DNS naming convention

### ISSUE THREAD

**Issue by fudali113** [istio/istio#5004]
https://github.com/istio/istio/blob/f157c74ebfcf9693f5357787925ac91a3a0caf03/pilot/pkg/model/validation.go#L2126

[Traffic Shifting](https://istio.io/docs/tasks/traffic-management-v1alpha3/traffic-shifting.html)
I want to use the format of 1.0.6 to divide my version; I think it should be allowed; Why not use a version number like 1.0.6 ?

**Comment by liamawhite** [comment]
Just trying to chase this up for you. Bear with me!

**Comment by rshriram** [comment]
Because this name is used as the root of a config in DestinationRule.
I am not sure if YAML would complain when you use such things in the Destination rules. Secondly, these names are encoded as part of Envoy's cluster names and stats. So, having dots in the cluster name will lead to issues, since the stats are usually of the form clusterName.somestat.somevalue. We would end up converting the dots to underscores, which would confuse you when you look at the metrics dashboard. 

DestinationRule
Host: foo.com
Subsets:
1.0.6:
- loadBalancingPolicy...

**Comment by liamawhite** [comment]
I think this question has now been answered, please reopen if you have further questions.
