### ISSUE TITLE
Remove `istio.io/for-service-account`

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#50173]
(This is used to request new product features, please visit <https://github.com/istio/istio/discussions> for questions on using Istio)

**Describe the feature request**

With #49700, WaypointServiceAccount "istio.io/for-service-account" has been useless, because the annotation is not checked anymore.

Is there any future use, otherwise please remove it

@ilrudie 

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
Agree this can be dropped

**Comment by ilrudie** [comment]
I agree we can probably remove the annotation. Do we want to totally remove the flag from istioctl too? It seems like there could be value for customizing the sa the waypoint is deployed with even though there isn't a direct correlation between sa and binding anymore. This might be handy once we're working on l4 policy checks to assert that traffic is from a waypoint instead of relying on checks hardcoded into zt...

**Comment by ilrudie** [comment]
Alternatively we can remove and replace it later with something that allows you to name the waypoint and we then just have `<name>-sa` or something for the serviceAccount

**Comment by ilrudie** [comment]
Just ignore my comments above. This discussion occurred in the PR
