### ISSUE TITLE
TestAmbientIndex_Policy test flake

### ISSUE THREAD

**Issue by hanxiaop** [istio/istio#50175]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/50171/unit-tests-arm64_istio/1774707872618254336

cc @ilrudie

**Comment by stevenctl** [comment]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/50182/unit-tests-arm64_istio/1774842142259154944

**Comment by ilrudie** [comment]
TLDR it seems there are just a bunch of unasserted events in this test and that can lead to unreliable behavior since clear isn't as strong as asserting the event. I will work on an update where there should be no unasserted events (probably tomorrow since it got late for me) and I think that should help.

**Comment by ilrudie** [comment]
Looks like asserting all the events helps a lot. Its still rough but will PR something soon. 
```
$ stress ./ambient.test -test.v -test.run TestAmbientIndex_Policy
...
10m0s: 3571 runs so far, 0 failures
```
