### ISSUE TITLE
Validation webhook fails to prevent IST0106 when VirtualService is missing weight attribute during manual editing 'kubectl edit vs' 

### ISSUE THREAD

**Issue by kelvin-j-li** [istio/istio#50228]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We observe that the missing **weight** attribute in virtualservice can cause IST0106

```
 istioctl analyze -A | grep Error
```
Error [IST0106] (VirtualService argocd/vs-demo-pricer-app) Schema validation error: total destination weight = 0

This can lead to very serious problems:
1) **Stale** RDS cause weird 503 nc cluster not_found error 
2) even worse, if istio-ingressgateway is restarted manually or due to system patching, lead to **stale** RDS and lose all porxy configs -- 404 for all api calls

STALE (Never Acknowledged)

This issue is confirmed to affect at least to these 2 versions  -- 1.19.3 and 1.20.2

### Version

```Text
istioctl version
client version: 1.20.2
control plane version: 1.20.2
data plane version: 1.20.2 (12 proxies)
```

### Additional Information

the istio validation webhook should reject the editing of virtualservice if weight is missing from the manifest

**Comment by leosarra** [comment]
Hi @kelvin-j-li ,

I'd like to clarify a point regarding the request "the istio validation webhook should reject the editing of virtualservice if weight is missing from the manifest".
The webhook should not reject edits to a VirtualService simply because the weight is missing from the VS. Weight is an optional parameter, and its absence makes sense for a VirtualService with only one route.

The error message you're encountering in istioctl analyze likely occurs because you have a VirtualService with multiple routes where the sum of the weights for all destinations is zero (either because the weights are absent in all the routes or because they all have weight: 0).

Anyway, I attempted to reproduce the issue by editing an HTTP bin VirtualService with multiple routes to have a total destination weight of zero. The validation webhook behaved as expected and successfully blocked both the edit and the apply operation.

```
[leosarra@workstation istio-1.20.2]$ kubectl edit virtualservice httpbin -n istio-system
error: virtualservices.networking.istio.io "httpbin" could not be patched: admission webhook "validation.isto.io" denied the request: configuration is invalid: total destination weight = 0
You can run `kubectl replace -f /tmp/kubectl-edit-44727324.yaml` to try this update again.

```
To help me troubleshoot further, could you provide a minimal example with steps that reproduces the issue you're facing? This will help me in investigating it further.

**Comment by kelvin-j-li** [comment]
hi @leosarra,
Thanks so much for your reply. I think your summary is correct -- the error was due to multiple routes with 0 sum. 

I was not able to re-produce the issue on my end, because the offending vs was removed. 

You may proceed with closing this issue. 

Thanks.

**Comment by leosarra** [comment]
You are welcome!
I will close the ticket for now.
If you end up encountering the same issue in the future please let ping me and I will take a look :)
