### ISSUE TITLE
Support "exportTo" on "EnvoyFilter

### ISSUE THREAD

**Issue by krissell** [istio/istio#50384]
**Describe the feature request**
Several istio resources support an 'exportTo' Spec field. It allows the object to created in a different namespace (such as istio-system). 
Without this, my operator is forced to create the object directly in istio-system. However, the side effect is my operator can no longer set the owner of the object I'm reconciling (not in istio-system), using: https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/controller/controllerutil#SetControllerReference
due to cross-namespaces references. ie. object being reconciled in is namespace X and the EnvoyFilter is in istio-system.

**Describe alternatives you've considered**
Don't set owner reference. Not a good practice.

**Comment by omni52** [comment]
Maybe I'm missunderstanding you, but I'm quite sure the EnvoyFilter scope is mesh wide by default and you could only limit it's scope with the workload Selector.

**Comment by howardjohn** [comment]
Do you want to write an envoyfilter in namespace A that impacts namespace B?

If so, I don't think this is viable from a security standpoint. Istio-system is able to do this cross namespace stuff because its a privileged namespace. things like service and VS are allowed to because its configuring how to reach that service.

---

Or to write one in namespace A that only impacts namespace A.
