### ISSUE TITLE
Remove init-container based CNI race condition repair for sidecars in favor of untaint controller.

### ISSUE THREAD

**Issue by bleggett** [istio/istio#51176]
**Describe the feature request**

Before the `untaint controller` CNI race condition mitigation existed: https://github.com/istio/istio/pull/48818

we used `istio-validation` init containers + CNI repair to solve this gap for sidecars.
https://istio.io/latest/docs/setup/additional-setup/cni/#race-condition-mitigation

This approach is fundamentally flawed however (e.g: https://github.com/istio/istio/issues/49210)

We should be able to remove `istio-validation` and init-based race condition mitigation and just use/point people at the untaint controller approach instead.

This will require testing, code removal (of the old init stuff), and doc updates.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[x] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Comment by howardjohn** [comment]
I want to do this but I don't see a path to reasonably doing it.

Here is my thought process.
1. We know people hit the race condition commonly in real world
2. When its hit, it will cause broken traffic. This is both unexpected allowance (policy bypass) and unexpected denial (traffic block, usually due to not using mTLS when expected). This is very bad.
3. When its hit, it will be permanent or temporary, depending on if the dynamic 'repair' mode is used; if we remove the init container the dynamic mode will not run, either, so depends on how we do this exactly
4. It is not possible to ensure taint is set on nodes as part of our install. Users must do it, and they must make sure its on ALL node pools, present **and future**.
5. (4) is painful, and as we push to make CNI used more and more, means its painful for all users
6. A significant chunk of users will not follow (4), leading to them hitting (2)

In the end, I expect this to result in one or both of: extreme setup friction and/or outage+policy bypass.

This seems really bad.

Some possible alternatives that sidestep these (most discussed in https://github.com/istio/istio/issues/40303)
* Make taint controller also taint the node, so you don't need to use platform configuration to do it. This is racy if done in a controller. A webhook could do it, but having a webhook on node create is problematic (circular dependency for Istiod). CEL mutating config could do it, but its not shipped yet (not even in 1.30, maybe 1.31). 
* Injected node selector (maybe breaks auto scaler, requires webhook). CEL mutator would make this more promising for ambient
* Injected custom resource (maybe breaks auto scaler, requires webhook). CEL mutator would make this more promising for ambient
