### ISSUE TITLE
How long is the push delay for xds? How to solve

### ISSUE THREAD

**Issue by Webster-Yang** [istio/istio#51370]
How long is the push delay for xds? How to solve

**Comment by wulianglongrd** [comment]
There is currently no indicator that can fully reflect the configuration push delay, probably because of the internal debounce mechanism, but Istio provides indicators at some key steps. Here are some examples:

1. pilot_pushcontext_init_seconds
2. pilot_proxy_queue_time
3. pilot_proxy_convergence_time
4. pilot_xds_push_time
5. pilot_xds_send_time

https://istio.io/latest/docs/reference/commands/pilot-discovery/#metrics

**Comment by zirain** [comment]
[this blog](https://medium.com/airbnb-engineering/improving-istio-propagation-delay-d4da9b5b9f90) will give you some help.
