### ISSUE TITLE
Helm profiles confusing users to put their own config under `defaults`

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#51458]
See https://blog.howardjohn.info/posts/advanced-helm/

I have seen a few people putting all their config under `defaults`. This is not how its supposed to be done; defaults was meant to be internal. We may need an alternative approach to solve this, or improve docs.

**Comment by bleggett** [comment]
In general, `values.yaml` is supposed to be documentation, and in fact most helm autogenerated doc tools treat it as such - it's the source of truth for valid keys in a Helm chart. The key-value pairs in it are supposed to be directly settable, and that will always be the expectation, because that is how Helm works.
