### ISSUE TITLE
Envoy CPU pprof broken due to tcmalloc

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#51810]
We recently moved to tcmalloc. This breaks Envoy CPU profiling support which is critical for operations. We should revert or bring CPU profiling functionality to tcmalloc in Envoy

**Comment by kyessenov** [comment]
System `perf` should be capable of performing CPU profiling. tcmalloc is a memory allocator and has nothing to do with CPU profiling. @briansonnenberg did you have a chance to try `perf` to CPU profile Envoy?

**Comment by howardjohn** [comment]
https://www.envoyproxy.io/docs/envoy/latest/operations/admin#post--cpuprofiler "Requires compiling with gperftool"

`perf` is not really equivilent IMO. It requires root access on the node, struggles to get symbols, and doesn't support the standard pprof format unless you jump through hoops (manually building https://github.com/google/perf_data_converter which requires bazel, etc -- note that gLinux comes with this OOTB to hide this pain).

https://github.com/istio/istio/wiki/Analyzing-Istio-Performance#profile has docs on how it works for below 1.22

**Comment by kyessenov** [comment]
Linux `perf` is the preferred long term direction, hence, modern tcmalloc dropped the signal-based CPU profiling. Some features (overload manager) are better integrated with tcmalloc, so sticking with the outdated perftools will make Istio use a build of Envoy inconsistent with the other production usages and prevent the use of those features.

It might be a good idea to change the debug variant to use gperftools if there's a need to debug in production.

**Comment by howardjohn** [comment]
Why is perf the preferred long term solution? It seems like everything else is going the opposite direction - Golangs pprof, https://grafana.com/docs/pyroscope/latest/configure-client, most rust apps are using https://github.com/tikv/pprof-rs. I thought Google itself internally as well?

**Comment by kyessenov** [comment]
AFAIK Google wide profiler uses `perf record` and upstream kernel has been getting patches to make it more scalable. The rationale that's documented for removing cpuprofiles from tcmalloc was that ebpf/perf events are more precise since signal interrupts influence the program under test. My feeling was that Linux has finally moved on from the state of disrepair in performance tooling (e.g. removal of frame pointers) back to where it was circa early 2000s :)

**Comment by howardjohn** [comment]
Well regardless of Googles internal infrastructure, it still remains that we went from having an easy to access http endpoint that gives reliable profiles in the ideal format, to having to get root into the node, run a program that is probably not on the node and hard to get (need to download the per-kernel version etc), that struggles with symbols due to containerization, and does not output in a readily usable format. 

I don't think this is a very good tradeoff for Istio users.

**Comment by kyessenov** [comment]
I don't think these are fundamentally hard issues - yes, we should improve the user experience for the narrow set of customers who really need to delve into the Envoy internals. The problems you mentioned are solvable: why can't we use a debug sidecar container to simplify the experience?

Any vendor is free to ship Envoy with gperftools and not have some features from Envoys. We added it to OSS because those features would be blocked completely from development with gperftools.

**Comment by howardjohn** [comment]
Documented in https://github.com/istio/istio/wiki/Analyzing-Istio-Performance#istio-122-and-newer. In the future when removing features from Istio it would be good to discuss them with the community and work on updating the documentation.
