### ISSUE TITLE
CNI_NET_DIR deletion on PR #52127 break cni on openshift

### ISSUE THREAD

**Issue by fjglira** [istio/istio#52273]
On PR #52127 linked to issue https://github.com/istio/istio/issues/52172 PR was deleted the CNI_NET_DIR because was not used but this field is being populated by the openshift profile and is used on openshift to locate where the CNI configuration files are to be installed. If we delete this field we are not going to be able to deploy any application with istio injection:

```
kubectl get pods -n bookinfo
NAME                             READY   STATUS     RESTARTS   AGE
details-v1-cf74bb974-vnnd9       0/2     Init:0/1   0          3m22s
productpage-v1-87d54dd59-djzmq   0/2     Init:0/1   0          3m21s
ratings-v1-7c4bbf97db-b54dw      0/2     Init:0/1   0          3m22s
reviews-v1-5fd6d4f8f8-x89gp      0/2     Init:0/1   0          3m21s
reviews-v2-6f9b55c5db-svjfj      0/2     Init:0/1   0          3m21s
reviews-v3-7d99fd7978-qrwsg      0/2     Init:0/1   0          3m21s
```

```
CNI request failed with status 400: 'ContainerID:"f741c70eef632c141df64e41a58c86adb428c25be41f660a6014ff198204111e" Netns:"/var/run/netns/e36df6a1-350c-42c0-a5d7-f7d21abec7dc" IfName:"eth0" Args:"IgnoreUnknown=1;K8S_POD_NAMESPACE=bookinfo;K8S_POD_NAME=reviews-v3-7d99fd7978-qrwsg;K8S_POD_INFRA_CONTAINER_ID=f741c70eef632c141df64e41a58c86adb428c25be41f660a6014ff198204111e;K8S_POD_UID=dfa61557-995a-4263-99db-7dd29884c6ed" Path:"" ERRORED: error configuring pod [bookinfo/reviews-v3-7d99fd7978-qrwsg] networking: [bookinfo/reviews-v3-7d99fd7978-qrwsg/dfa61557-995a-4263-99db-7dd29884c6ed:istio-cni]: error adding container to network "istio-cni": Get "http://localhost:8080/api/v1/namespaces/bookinfo/pods/reviews-v3-7d99fd7978-qrwsg": dial tcp [::1]:8080: connect: connection refused
```

**Comment by bleggett** [comment]
So if I understand this right:

- Istio has no dependency on this env var
- Istio doesn't use it
- It can't break any Istio tests or functionality, because Istio doesn't use it.
- Openshift does use it, and it breaks Openshift.

I'm honestly a little hesitant to add an env var back to an internal Istio component that Istio doesn't use, especially since we can't actually fence this with tests in any way on our end.

Also, it's worth noting- environment variables are _not_ an API we support with back compat guarantees, as a matter of Istio policy, and never have been.

If Openshift needs this value, can it

- Capture the correct value in its own config?
- If it really must introspect Istio internals without using an API, can it inspect the `istio-cni` helm values or (better yet) the volume mounts, which would be the better source of truth anyway?
- Can `openshift` simply apply a pod annotation with this info, and consume that (since we support users adding arbitrary annotations to Istio pods)?

In general, I am a little leery of adding an env var to an internal Istio component that Istio doesn't need or use, so a 3rd-party integration can work - happy to work with you to do this the right way though, I'm just not entirely sure what or how you use this.

**Comment by jwendell** [comment]
I agree. If Istio doesn't use it, we don't need to bring it back.

@fjglira We should identify where it's used (in sail-operator?) and fix it there.

**Comment by fjglira** [comment]
Hey, thanks for the quick reply both. @jwendell the issue is not related to sail-operator, we saw the issue by running the integration test directly on openshift. I’ll check tomorrow morning if the re is a best way to add this

**Comment by jwendell** [comment]
Can this value be set in the profile along with others? e.g.: https://github.com/istio/istio/blob/master/manifests/helm-profiles/openshift.yaml

**Comment by fjglira** [comment]
> Can this value be set in the profile along with others? e.g.: https://github.com/istio/istio/blob/master/manifests/helm-profiles/openshift.yaml

`CNI_NET_DIR` value is set by using `.cni.cniConfDir` from [profile]( https://github.com/istio/istio/blob/master/manifests/helm-profiles/openshift.yaml) yaml

I'm checking where specifically is being used

**Comment by jwendell** [comment]
ok, found it. It's being used here: https://github.com/istio/istio/blob/master/cni/pkg/cmd/root.go#L168

So, I am +1 to get that env variable back.

**Comment by bleggett** [comment]
> ok, found it. It's being used here: https://github.com/istio/istio/blob/master/cni/pkg/cmd/root.go#L168
> 
> So, I am +1 to get that env variable back.

Ugh, I see. We don't use it to actually write anything to `/etc/cni/net.d` anywhere. We write everything to the (fixed) hostmount. We use it  in exactly one spot, in the plugin config, to tell the plugin config to load the kubeconfig we (presumably) wrote to the same spot.

That's annoying.

Yep, bring it back, my bad.

**Comment by bleggett** [comment]
This probably impacted https://github.com/istio/istio/pull/52238 as well in a rather hard-to-test-for-way, actually.

I may remove the dependency on having to write out a kubeconfig in one spot then pass an env var to the plugin just so it can read it from the same spot - that's all a bit baroque.

Raised https://github.com/istio/istio/issues/52315 to actually remove the need for this env var (and the need for the plugin to load a kubeconfig, which is the only reason we need it)

**Comment by bleggett** [comment]
ty @jwendell and @fjglira - thanks!
