### ISSUE TITLE
istioctl should support kubectl impersonation

### ISSUE THREAD

**Issue by dwj300** [istio/istio#52285]
(This is used to request new product features, please visit <https://github.com/istio/istio/discussions> for questions on using Istio)

**Describe the feature request**
We use User Impersonation (https://kubernetes.io/docs/reference/access-authn-authz/authentication/#user-impersonation) to authenticate to our clusters. This works fine in kubectl (via the `--as` flag) and client-go (via the Imersonate option), but istioctl doesn't expose this flag.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[x] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by MorrisLaw** [comment]
This seems to be rehashing an already closed issue we've had around this in the past: https://github.com/istio/istio/issues/22365#issuecomment-700006081

Is your problem solved by the comments/suggestions in that issue?

**Comment by MorrisLaw** [comment]
Any updated opinions on this @esnible @howardjohn , it's been 4 years so you might not remember... here's the seemingly related discussion on this issue: https://github.com/istio/istio/issues/22365

I don't have the full context but I'm assuming that if we haven't added it yet, it may not be necessary?

**Comment by edieYoung** [comment]
After evaluating the workaround mentioned in the thread, we find it's not very convenient and more impotently it bypasses the guardrail that we set up for cluster admin impersonation. So we do think it's worthy to expose a flag in istioctl.
Impersonation is a common technique of avoiding having ambient elevated permissions, and not having to edit the kubeconfig for that makes a better UX and avoids the problem with forgotten implicit high-access-level kubeconfig context.

**Comment by MorrisLaw** [comment]
> After evaluating the workaround mentioned in the thread, we find it's not very convenient and more importantly it bypasses the guardrail that we set up for cluster admin impersonation. So we do think it's worthy to expose a flag in istioctl. Impersonation is a common technique of avoiding having ambient elevated permissions, and not having to edit the kubeconfig for that makes a better UX and avoids the problem with forgotten implicit high-access-level kubeconfig context.

I'd be curious about how this could affect the application of security policies in the mesh...

To be sure we're not undermining the security and operational stability of Istio, we'd probably need to get some input from others (especially @istio/wg-security-maintainers) on this feature request. There's a chance that we are missing some necessary cautions around a feature like this where user privileges are involved. And tbh, I'm not entirely convinced yet of the value of adding this or that it doesn't have any bad implications (granted, I don't have all of the context either).

Let's give the other maintainers some time to look at this, I can add it to next week's agenda too. We have [WG meetings every Wednesday (9am PST/12pm EST)](https://github.com/istio/community/blob/master/WORKING-GROUPS.md#working-group-meetings) if you'd like to join and add to the context that's already in this issue and discuss in real time. Agenda items get recorded, discussed and potentially decided on during the meeting.

We appreciate all user feedback and suggestions, thanks again for bringing this up!

**Comment by rohitagarwal003** [comment]
I wanted to expand on how/why we are using impersonation and why the workaround is not good enough.

We use impersonation as a way to reduce ambient permissions that developers have. We grant our developers reasonably broad read-only access to our Kubernetes clusters. However, instead of granting cluster-admin permissions directly to developer identities, we grant cluster-admin only to a special Kubernetes identity (`compute:cluster-admin`).

This means that when developers run commands like `kubectl` against the cluster, they run those commands with read-only permissions by default. To run a command that can make changes to the cluster, developers need to pass an extra flag (`--as compute:cluster-admin`).

Having to pass an extra flag while making changes to production clusters prevents against mistakes. For example, I may be working against my local Kubernetes cluster (e.g. `KIND`, `minikube` etc.) where I may be making destructive changes. If I switch my terminal to another tab where the context is set to a production cluster, I don't want any accidental commands to modify the cluster to succeed. Requiring an extra flag to be passed in such cases acts as a good reminder (kind of like requiring `sudo` before making changes).

Putting impersonation settings in the kubeconfig weakens this because it's very easy to set the powerful context as the default context for a terminal etc.

**Comment by MorrisLaw** [comment]
That's fair @rohitagarwal003. There has been interest in the past to [use genericclioptions more heavily](https://github.com/istio/istio/issues/19927) in order to get all of the flags that kubectl has, which includes the [--as](https://github.com/kubernetes/cli-runtime/blob/05c203104289f1c45aad2270ecfd6914da158e5b/pkg/genericclioptions/config_flags.go#L53-L55) flag. It got stale and was closed, I'm not sure why it never got completed.

I think this is worth revisiting though, it's been added to the agenda for next weeks meeting. Thanks for adding the extra context for your situation!

**Comment by edieYoung** [comment]
updates: we discussed this with the WG and consensus is made in the [WG meeting](https://docs.google.com/document/d/1wsa06GGiq1LEGwhkiPP0FKIZJqdAiue-VeBonWAzAyk/edit#heading=h.mwhfqxdda5gf) , as per `Consensus: reuse kubectl params make sense for this: add --as and --as-group flags to istioctl`

**Comment by dwj300** [comment]
Closed by https://github.com/istio/istio/pull/52801
