### ISSUE TITLE
istio-init container exit(status 2) when kernel lacks 'iptables-legacy' modules

### ISSUE THREAD

**Issue by ZarrianShi** [istio/istio#52357]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

The current implementation of the iptables detect logic looks like below:
1. Execute `iptables-nft-save/ip6tables-nft-save`. If there are more than three rules and `iptables-nft-save/ip6tables-nft-save` and `iptables-nft --version/ip6tables-nft --version` do not return errors, use the `iptables-nft` series binaries (`iptables-nft`, `iptables-nft-save`, `iptables-nft-restore`).
2. Execute `iptables-legacy-save/ip6tables-legacy-save`. If there are more than three rules and `iptables-legacy-save/ip6tables-legacy-save` and `iptables-legacy --version/ip6tables-legacy --version` do not return errors, use the `iptables-legacy` series binaries (`iptables-legacy`, `iptables-legacy-save`, `iptables-legacy-restore`).
3. Execute `iptables-save` and `iptables --version`. If there are no errors, use the `iptables` series binaries.

In my environment, the host does not have `iptables-legacy` installed, only `iptables-nft`. According to the logic above, istio-init will erroneously select `iptables` series binaries(instead of `iptables-nft`), because the corresponding kernel modules are not installed in my environment, as a result,  istio-init encounters error when executing `iptables-restore`:

![image](https://github.com/user-attachments/assets/7d951476-757b-4df9-96b3-5ecd2167ef41)

And here's the reason:
In the istio-init container, steps 1 and 2 get skipped because the Rules Dump check (>3 rules) are not passed. This is expected since the newly created Pod and it has no existing rules in pod network ns. Therefore, step 3 is executed, which uses the `iptables` commands (`iptables`, `iptables-save`, `iptables-restore`). However, in the `istio-init` context, the `iptables` commands correspond to the `iptables-legacy` commands. Since my host lacks the `iptables-legacy` kernel modules, this triggers the error: `unable to initialize table 'nat'`.

I noticed that the current implementation for selecting the iptables binary was submitted by @bleggett in this Pull Request (https://github.com/istio/istio/pull/49703). The initial discussion of this issue took place in this Issue (https://github.com/istio/istio/issues/49279), where @bleggett described his scenario: in the Ambient mode, the CNI Daemon misplaces rules into the `iptables-legacy` chains when configuring traffic rules in the node network namespace, while k8s adds its rules to the `iptables-nft` chains:

> Seeing an issue where the single ambient iptables rule istio-cni injects into the host-level iptables POSTROUTING chain (for host healthchecks) ends up in the iptables-legacy chain, even though all the other rules (kubelet, CNI, etc) are in the iptables-nft chain.

@bleggett pinpointed the root cause in the old inspection logic:
> This is because our iptables (legacy OR nft) selection logic only checks the container-local binary default, which may or may not actually match what was used or is present on the host node.

He resolved the bug in this scenario by introducing a new detection logic. However, the current solution still faces issues when the host does not support `iptables-legacy` (as described earlier). Essentially, when neither `iptables-legacy` nor `iptables-nft` meet the criteria, it falls back to the `iptables` command. In Istio 1.22's four use-cases, the iptables command could imply different implementations:

| Usage | Using iptables Binaries From | Networking context to select correct binary against | 'iptables' binary corresponding to |
| ------ | ----------------------------- | --------------------------------------------------- | ------------------------------- |
| from CNI plugin (sidecar) | host $PATH | pod netns context | depends on host environment, iptables-legacy or iptables-nft are both possible |
| from init container (sidecar) | init container $PATH | pod netns context | iptables-legacy implementation |
| from CNI agent (ambient) | CNI container $PATH | pod netns context | iptables-legacy implementation |
| from CNI agent (ambient) | CNI container $PATH | host netns context | iptables-legacy implementation |

As you can see, as long as a binary inside the container $PATH executes in the Pod network ns, an error will arise if the host does not have `iptables-legacy` kernel modules installed. Based on my understanding, the current fallback to iptables aims to adhere to the environment settings (assuming `iptables` pointed to the default implementation), but this implementation may deviate from the expected behavior due to the different implications of the `iptables` binary under various conditions. I believe we need a different approach to resolve this issue. Here is a proposed solution inspired by @bleggett 's current implementation. 

First, we need to check what `iptables` implementations the current kernel supports. This could be achieved by inspecting kernel modules. The `/proc/modules` file lists all the kernel modules loaded by the current kernel. This file remains consistent across the host and all containers, indicating the kernel modules loaded by the host's OS.

After determining the supported implementations, we should confirm the binaries corresponding to each supported implementation in the current context. Then, we use these binaries to retrieve the Rule Dump for each implementation. Here’s how to determine the binaries for each implementation:

- For legacy, try executing `iptables-legacy --version`. If no error occurs, use `iptables-legacy`. If it fails, try executing `iptables --version`. If the output does not contains `nf_tables`, use `iptables`. Otherwise, the current environment does not support legacy.
- For nft, try executing `iptables-nft --version`. If no error occurs, use `iptables-nft`. If it fails, try executing `iptables --version`. If the output contains `nf_tables`, use `iptables`. Otherwise, the current environment does not support nft.

By this point, we should have enough information to determine which binary set to use. (the final judgment process is mainly inspired by @bleggett 's approach. Thanks again to him.)

- If both legacy and nft are supported by the current kernel, use the implementation with more than 3 rules for the Rule Dump. (If both have more than 3 rules, may be should report an error or support configuration to specify which one to prioritize for this case?)
- If only one implementation is supported, use the currently supported implementation directly.

I will submit a PR to trying improve the iptables detect implementation, feedback and suggestions are welcome!

### Version

```Text
istio 1.22.2(both controlplane and dataplane)
```

### Additional Information

none

**Comment by bleggett** [comment]
> In the istio-init container, steps 1 and 2 get skipped because the Rules Dump check (>3 rules) are not passed. 

The rules count check is meant to be used as a `tiebreaker` when both `iptables-nft` and `iptables-legacy` are present.

We can't _just_ prefer `nft` in that case jbecause even tho both are available, the host may have preferred to inject rules into `legacy` - and we want to respect that if we can.


If this is the problem, the simpler fix is probably to 

- Identify if both `nft` and `legacy` are present
- If both present, check the rulecount for both.
- If neither have any rules, unconditionally pick `nft`

That should fix your scenario without requiring kmod introspection.

**Comment by bleggett** [comment]
Then we can just add a statement to https://istio.io/latest/docs/ops/deployment/platform-requirements/

that says if both `legacy` and `nft` are present, `nft` will be preferred, and the kmods we already list must be loaded.

**Comment by xocodergit** [comment]
Hi @bleggett , thanks to your reply.

> **If this is the problem, the simpler fix is probably to**
Identify if both nft and legacy are present
If both present, check the rulecount for both.
If neither have any rules, unconditionally pick nft
That should fix your scenario without requiring kmod introspection.

yes, this approach may fix my scenario, but if we pick nft unconditionally, it will also causes an error when host kernel only have legacy modules(some old/customized kernel).

> Then we can just add a statement to https://istio.io/latest/docs/ops/deployment/platform-requirements/
that says if both legacy and nft are present, the required kmods we list already must be loaded for both.

for current implementation, legacy and nft are always present in istio images(CNI Daemon & istio-init).

------

Back to the original issue: we need an approach to determine the appropriate iptables binary to use in all of scenario we may face(CNI Daemon/CNI Plugin/istio-init). for current logic, we are doing like:

1. Does iptables-nft should be pick? if so, pick iptables-nft
2. Does iptables-legacy should be pick? if so, pick iptables-legacy
3. pick iptables

This approach definitely works well on most of scenarios, but because of the complexity of the environment context, iptables can corresponding to different implementation. and this would leads to the problem we have already talked about.

So i think we may need a new approach, which can deal with all our scenarios by one consistent logic. To achieve this, we may answer 3 questions:

1. What implementation(legacy/nft) has been installed in the host kernel (only installed implementation should being considered, check `/proc/modules` is the easiest way to do so)
2. Which binary each implementaion corresponding to (we need to get version and dump rules by executing the binary)
3. If both installed, use corresponding binary to dump their rules, and choose one which have more than 3 rules. (we prefer to choose implementation already have rules)

and then my implementation came up

**Comment by zirain** [comment]
will https://github.com/istio/istio/pull/50328 help?

**Comment by xocodergit** [comment]
> will #50328 help?

this seems talking about something else, or am I misunderstanding ? 🤔

**Comment by bleggett** [comment]
> Hi @bleggett , thanks to your reply.
> 
> > **If this is the problem, the simpler fix is probably to**
> > Identify if both nft and legacy are present
> > If both present, check the rulecount for both.
> > If neither have any rules, unconditionally pick nft
> > That should fix your scenario without requiring kmod introspection.
> 
> yes, this approach may fix my scenario, but if we pick nft unconditionally, it will also causes an error when host kernel only have legacy modules(some old/customized kernel).

I am fine with this - it would only happen if 

- legacy was present
- nft was present
- legacy had rules defined on the host
- nft had rules defined on the host
- legacy host mods loaded
- nft host mods not loaded
- we unconditionally prefer nft as the tiebreaker (newer == better)

We can add a sentence in https://istio.io/latest/docs/ops/deployment/platform-requirements/ that says

"if both iptables-legacy and iptables-nft are present and _in use_ on the node, both must load the following kernel modules"

which will cover this.

> for current implementation, legacy and nft binaries are always present in istio images(CNI Daemon & istio-init).

Correct, the presence of the binaries in the container is moot - it's a question of what rules are defined on the host, and whether the host has met our documented standards for the version of `iptables` that is in use: https://istio.io/latest/docs/ops/deployment/platform-requirements/

If both are "in use" then both must load all the kmods. If only one is in use then only that one needs the kmods loaded. 

The other reason I don't want to autodetect kmods is that could still lead to breakage/confusing behavior - if I have a pod that puts/expects rules in `legacy` but is scheduled on a node where the `legacy` kmods are not loaded - Istio silently inserting rules into `nft` because that's the only one the host has loaded kmods to support would be wrong/confusing from the perspective of that pod.

I would be OK with a startup check that the kmods are loaded, to block `istio-cni` from starting up. But the problem with that is we don't know what kmods _should_ be loaded until we inject into a pod, so that doesn't really work either.


So I would prefer a simpler solution that does the following:

1. Fixes the "tiebreaker logic". If both `legacy` and `nft` have defined rules in the current context, prefer `nft` in that case -> what https://github.com/istio/istio/issues/52357#issuecomment-2253300746 is suggesting.

2. Document PR to add `"if both iptables-legacy and iptables-nft are present and _in use_ on the node, both must load the following kernel modules"` in  https://istio.io/latest/docs/ops/deployment/platform-requirements/

**Comment by zhlsunshine** [comment]
Hi all, some ideas about above discussion:
Firstly, there should be unified instructions for `CNI plugin (sidecar)`, `init container (sidecar)` and `CNI agent (ambient)`, the `unified instructions` means that they may need to follow the same logic to adjust the `iptables rules`.
Secondly, there are considerations on both the `installation of the appropriate series iptables binaries` and `rulecount of corresponding iptables binaries`. And this second point may causes the differences for `CNI plugin (sidecar)`, `init container (sidecar)` and `CNI agent (ambient)`, the `unified instructions` 
At last, make a reasonable and executable logics for choosing the proper iptable binaries. So I suggest that @xocodergit can write a proposal in the community for this. 
BTW, I believe that @bleggett and I are disagree to check `/proc/modules` for inspecting kernel modules due to it would import the OS level dependency of Istio. It's unacceptable.
Please correct me if any incorrect.

**Comment by xocodergit** [comment]
@bleggett Thanks to your reply, I understand that you want to solve the problem more concisely, but I still have some different opinions and hope we can discuss it further.

> I am fine with this - it would only happen if
legacy was present
nft was present
legacy had rules defined on the host
nft had rules defined on the host
legacy host mods loaded
nft host mods not loaded
we unconditionally prefer nft as the tiebreaker (newer == better)

1. In the `istio-init` scenario, legacy and nft binaries is always present
2. both '`legacy had rules defined on the host`' and '`nft had rules defined on the host`' is un-inspectable in `istio-init` container, in fact, we may not really care about how many rules defined by legacy/nft on the host when we're in `istio-init` container --- choose one that have already installed on the host kernel is enough.

so the thing is going to be like: whatever which one we pick unconditionally, the error would occurs if kernel modules corresponding it is not loaded into the host kernel.

> We can add a sentence in https://istio.io/latest/docs/ops/deployment/platform-requirements/ that says
"if both iptables-legacy and iptables-nft are present and in use on the node, both must load the following kernel modules"

the iptables series binaries built-in in images of `istio-init` and `CNI agent` is not installed by users.

**Comment by xocodergit** [comment]
Also thanks to @zhlsunshine , I think we can discuss this in two parts:

# 1.  A unified iptables detect instructions
we need a unified instructions to detect which iptables binary should be used in all scenarios.(`istio-init`, `CNI agent`, `CNI plugin`)

i have described my opinion on this:
> - Determine what implementation(legacy/nft) has been installed in the host kernel (only installed implementation should being considered to use, check /proc/modules is the easiest way to do so)
> - Determine which binary each implementaion corresponding to (we need to get version and dump rules by executing the binary)
> - If both installed, use corresponding binary to dump their rules, and choose one which have more than 3 rules. (we prefer to choose implementation already have rules). else, use the installed one.

I agree with your concern about the OS dependency of checking `/proc/modules`, but I think we can discuss this separately in the part 2.

# 2. How to detect status of kernel modules
well, maybe check `/proc/modules` would introduce some OS level dependencies(although i think it seems ok because iptables it self also depending on the OS). we can check it in other ways if there is a better one.

**Comment by zhlsunshine** [comment]
@xocodergit It really makes sense to have a unified iptables detect instructions for all scenarios.(`istio-init`, `CNI agent`, `CNI plugin`)

**Comment by zhlsunshine** [comment]
Hi @bleggett and @xocodergit, it really makes sense to have a unified iptables detect instructions for all scenarios.(`istio-init`, `CNI agent`, `CNI plugin`), rather than how to fix this problem easily.

**Comment by bleggett** [comment]
> Hi @bleggett and @xocodergit, it really makes sense to have a unified iptables detect instructions for all scenarios.(`istio-init`, `CNI agent`, `CNI plugin`), rather than how to fix this problem easily.

Yes, the current code already is a unified detection mechanism across all of those - the thing at issue is the detection heuristic used (kernel introspection vs checking active rules).

**Comment by bleggett** [comment]
> Hi all, some ideas about above discussion: Firstly, there should be unified instructions for `CNI plugin (sidecar)`, `init container (sidecar)` and `CNI agent (ambient)`, the `unified instructions` means that they may need to follow the same logic to adjust the `iptables rules`. Secondly, there are considerations on both the `installation of the appropriate series iptables binaries` and `rulecount of corresponding iptables binaries`. And this second point may causes the differences for `CNI plugin (sidecar)`, `init container (sidecar)` and `CNI agent (ambient)`, the `unified instructions` At last, make a reasonable and executable logics for choosing the proper iptable binaries.

Yes - the logic is already unified. This is a question about when we should prefer `nft` or not in a "tie" situation, when the heuristic indicates both `legacy` and `nft` are available and in use.

So I suggest that @xocodergit can write a proposal in the community for this. BTW, I believe that @bleggett and I are disagree to check `/proc/modules` for inspecting kernel modules due to it would import the OS level dependency of Istio. It's unacceptable. Please correct me if any incorrect.

My stance is I do _not_ want to check `/proc/modules` since I think we can solve this pretty simply with ~10 line fix (check rule counts for _both_ binaries before choosing one) and a docs change.

**Comment by bleggett** [comment]
@xocodergit 

I would prefer you do the following:

1. Change the code to check the rulecounts for both `iptables-legacy` and `iptables-nft`, if both binaries are present.
2. If _both_ have rulecounts >3 (e.g. both are in use) or _neither_ have rulecounts > 3 - prefer `nft`.

Then we just need a docs PR.

**Comment by xocodergit** [comment]
> I would prefer you do the following to fix this specific issue:
> 
> 1. Change the existing code to check the rulecounts for both `iptables-legacy` and `iptables-nft`, if both binaries are present.
> 2. If _both_ have rulecounts >3 (e.g. both are in use) or _neither_ have rulecounts > 3 -> prefer `nft`.
> 3. A unit test to assert the above behavior.
> 
> Then we just need a docs PR with the one-sentence clarification I mentioned above and you should have a tested fix for this issue without needing to check `/proc/modules`. Checking for kmods (as I mentioned) is not the best detection heuristic to use here, as it will not produce consistent results in all the scenarios the current unified logic needs to operate in.
> 
> Following that, if you would like to propose checking `/proc/modules` then I agree with @zhlsunshine that it would be good to write that up and present it to the community.

The reason why I think a new implementation is needed is that I understand that the current implementation does not work as expected in the istio-init scenario for the following reasons:
- iptables-nft/iptables-legacy MUST EXIST in `istio-init` image
- rule-dump by iptables-legacy-save/iptables-nft-save MUST 0 in pod network ns

As a result, the 'tie' situation is a inevitable in `istio-init`, so the bottom-line logic(pick `iptable`) will definitely be executed, but, whatever we pick unconditionally for this situation(legacy/nft), there will always be situations that cannot be handled expectedly:
- if we pick `iptables-legacy`, then if the host only has nft, an error will occur.
- if we pick `iptables-nft`, then if the host only has legacy, an error will occur.

To resolve this, i prefer the way blow:
> Determine what implementation(legacy/nft) has been installed in the host kernel (only installed implementation should being considered to use, check /proc/modules is the easiest way to do so)
> Determine which binary each implementaion corresponding to (we need to get version and dump rules by executing the binary)
> If both installed, use corresponding binary to dump their rules, and choose one which have more than 3 rules. (we prefer to choose implementation already have rules). else, use the installed one.

I agree with this:
> Checking for kmods (as I mentioned) is not the best detection heuristic to use here, as it will not produce consistent results in all the scenarios the current unified logic needs to operate in.

but maybe we can have a better way to achieve this.

**Comment by bleggett** [comment]
> As a result, the 'tie' situation is a inevitable in `istio-init`, so the bottom-line logic(pick `iptable`) will definitely be executed, but, whatever we pick unconditionally for this situation(legacy/nft), there will always be situations that cannot be handled expectedly:
> 
>     * if we pick `iptables-legacy`, then if the host only has nft, an error will occur.
> 
>     * if we pick `iptables-nft`, then if the host only has legacy, an error will occur.

We have to select the right tool based on the rules that (might) already exist in the netns we are operating in - that must be the only criteria for picking the right `iptables` binary.

If we select the right one based on the loaded kmods instead, there will still be corner cases where the kmods that are loaded do not match the rules that are defined in the netns we happen to be running in, and we can still have a mismatch.

For instance - I have `legacy` and `nft` on my node. I have loaded the Istio-required kmods for `nft`, but not `legacy`. I create some preexisting (host || pod) iptables rules in `legacy` tables (rules that do not require the extra kmods we do, for instance). Us ignoring those existing rules and putting our rules in `nft` tables would be incorrect - the kmods are loaded for `nft` but the environment is using `legacy`.

Adding kmod-based selection also doesn't really solve the problem of needing to arbitrarily prefer `legacy` versus `nft` if both have  loaded kmods all other factors are equal - we still have to "just pick" `nft`.


The Istio detection heuristic needs to be/should be:

- If you have rules defined in `legacy` tables in the netns (which could be a pod OR node) we are checking in, _we must_ use `legacy` binaries. If we cannot because you have rules in `legacy` tables but have not loaded all the Istio-required kmods for `legacy`, you must follow our doc and do so, this is an error and a prerequisites failure.

- If you have rules defined in `nft` tables in the netns (which could be a pod OR node) we are checking in, we _must_ use `nft` binaries. If we cannot because you have rules in `nft` tables but have not loaded all the Istio-required kmods for `nft`, you must follow our doc and do so, this is an error and a prerequisites failure.

- If you have rules defined in (both OR neither), we prefer `nft` unconditionally.

The bug you raised can be fixed relatively simply with the above existing heuristic, without needing to do kmod detection.

So let's fix the bug without kmod detection, and change the doc to say "if you are using both `legacy` and `nft` on the same node and/or in your workloads, the Istio-required iptables kmods must be loaded _for both_"

If you wanna write up a doc for kmod detection that covers all corner cases and is simpler/more reliable than the existing above heuristic, I'd be happy to review it and we can bring it up in the WG, tho.

**Comment by bleggett** [comment]
> In my environment, the host does not have iptables-legacy installed, only iptables-nft. According to the logic above, istio-init will erroneously select iptables series binaries(instead of iptables-nft), because the corresponding kernel modules are not installed in my environment, as a result, istio-init encounters error when executing iptables-restore:

We run `iptables-save` before we run `iptables-restore`, because we use it to check if there are rules already defined.

We can't get to the point where we run `iptables-legacy-restore` unless we have already done `iptables-legacy-save` to try and detect if there are actually rules defined in legacy tables.

If `iptables-legacy-save` did not return an error in your scenario, but `iptables-legacy-restore` did, then there are only a few options:

- `iptables-legacy-save` found rules in legacy tables, and so chose `legacy`. In this case, you must load both sets of kmods, or not define any rules in `legacy` tables in your pods or hosts.

- `iptables-legacy-save` found _no_ rules in legacy tables, but for some reason did not prefer `nft`. This would be a bug, and relatively simple bug to fix.
