### ISSUE TITLE
Deletion of kiali-viewer ClusterRole breaks the upgrade

### ISSUE THREAD

**Issue by himanshujaindev** [istio/istio#52510]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hello @howardjohn 

This [PR](https://github.com/istio/istio/pull/51618/files#diff-c38b7f4fa805cfe3e298682e847051d3326b27c7d586a9775fc0f2a9ebbb0526L137) deletes kiali-viewer ClusterRole, but we have it referenced in kiali ClusterRoleBinding. Upstream [PR](https://github.com/kiali/helm-charts/pull/211/files) also does not completely delete it, rather they have added a flag to control this.

The deletion of ```kiali-viewer``` _ClusterRole_ is breaking the deployment, as we have it referenced in ```kiali``` _ClusterRoleBinding_. What do you suggest we do here? We cannot change the reference to ```kiali``` _ClusterRole_, as it throws the below error.
```
The ClusterRoleBinding "kiali" is invalid: roleRef: Invalid value: rbac.RoleRef{APIGroup:"rbac.authorization.k8s.io", Kind:"ClusterRole", Name:"kiali"}: cannot change roleRef  
```

### Version

```Text
❯ istioctl version
client version: 1.22.0
control plane version: 1.22.2
data plane version: 1.22.2 (290 proxies)

❯ kubectl version
Client Version: v1.28.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.15-eks-db838b0
```

**Comment by himanshujaindev** [comment]
This issue is seen when we perform istio upgrade from 1.20 -> 1.22

**Comment by jmazzitelli** [comment]
Ah, right. The Kiali server helm chart was changed such that both the view-only and read/write roles aren't both created - only the one that is needed is created. This changed in Kiali v1.85.0
* https://github.com/kiali/kiali/issues/7357
* https://kiali.io/news/release-notes/#1850

Perform an uninstall and then re-install. Kiali is stateless so you don't lose any data doing a re-install rather than an upgrade.

```sh
helm uninstall -n istio-system kiali-server
helm install -n istio-system kiali-server kiali/kiali-server
```

As for the [addon yamls](https://istio.io/latest/docs/ops/integrations/kiali/), those are only meant for demo purposes, not for production, and there is no guarantee they support upgrades. So, again, a simple uninstall/re-install should work:

```sh
kubectl delete -f https://raw.githubusercontent.com/istio/istio/release-1.20/samples/addons/kiali.yaml
kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.22/samples/addons/kiali.yaml
```

**Comment by howardjohn** [comment]
Thanks @jmazzitelli !
