### ISSUE TITLE
Ambient (and sidecar TPROXY mode) does not work with GKE intranode visibility

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#52576]
Context https://istio.slack.com/archives/C041EQL1XMY/p1723039587363189
https://github.com/GoogleCloudPlatform/netd/blob/a2d69d0b4bb3e52b1c7e61e9408aa0bc60a31609/pkg/options/options.go#L42
https://github.com/GoogleCloudPlatform/netd/pull/177#issue-1441380837

They set src_valid_mark=1 which breaks TPROXY. Proposed solution is to unset this in the pod network namespace.

cc @bleggett

**Comment by xSAVIKx** [comment]
A hotfix for existing deployments with Istio 1.23 was discussed [here](https://istio.slack.com/archives/C37A4KAAD/p1729693482323299):
1. Set `AMBIENT_TPROXY_REDIRECTION=false` on the CNI daemonset (e.g. with `kubectl  -n istio-system  set env ds/istio-cni-node AMBIENT_TPROXY_REDIRECTION=false`)
2. Restart workloads

Just leaving this here for historical purposes and in case someone faces the same issue till the fix is available.

P.S. v1.24 will also have `env` [exposed](https://github.com/istio/istio/pull/53624) in Helm chart for CNI which allows to apply no-cli fix.

**Comment by bleggett** [comment]
A backport was done for 1.23 but has not been merged yet: https://github.com/istio/istio/pull/53629

**Comment by xSAVIKx** [comment]
> A backport was done for 1.23 but has not been merged yet: https://github.com/istio/istio/pull/53629

Nice! Would be great to have it with 1.23 as well.

**Comment by bleggett** [comment]
cc @istio/release-managers-1-23 :point_up_2: can we get this merged?

**Comment by mikemorris** [comment]
Approved backport for 1.23, patch is small and no change to default behavior so this seems fine.

**Comment by bleggett** [comment]
> Approved backport for 1.23, patch is small and no change to default behavior so this seems fine.

thanks!
