### ISSUE TITLE
Better status writing

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#52602]
Istio writes status now/soon in a few places:

* Analysis: uses status manager, enqueues `diag.Messages` as context and has some special logic in the status manager to translate this into a `UpdateStatus` call.
* Gateway: uses status manager, enqueues the full `Status` object and writes that as an `UpdateStatus` object.
* IP allocation: uses its own queue, with PatchStatus
* (future) ambient status writing (https://github.com/istio/istio/pull/51945): uses its own queue, with PatchStatus

The status manager works by enqueuing some work. It essentially has a map of 'pending work' which is `object key -> controller -> context`. It will process these with dynamic concurrency (a nice feature to avoid serializing all work!). On each object, it fetches that latest object, then applies the context to it in some ways, then calls UpdateStatus.

Effectively, this is a patching mechanism; each controller user just gives info that can be applied to the object. They do not give the whole status object... except the Gateway usage, which passes the whole status object as context, and to 'apply' it does `config.status = context`.

This is problematic, as it could wipe out previous work.

Ideally, all usage is patch based. This could be both in the library, but also in the actual API server call. This is easy for some fields, but harder for condition based ones or Gateway which has many many fields. If we don't have patching, then we need to be able to handle conflicting writings. Today, we don't have conflicting writes, since objects are either GW API or Istio, and there is no overlapping status writers for these types.

Moving to server side apply may be an option here; if we do that, controllers may be able to always write "patch" type logic, and k8s handles the conflicts. However, this may not work well for Gateway API -- in that case, we actually explicitly overwrite status messages written by other controllers in some places.

If we don't have patching, and use a shared queue, we need a method to block a write and have the controller re-queue. With the current semantics, it is fire-and-forget; you `EnqueueStatusUpdateResource` and that is it. We would need one of two things:
* Trust that the object status changing (from the other controllers change) would trigger the caller to reconcile and retry. I don't think this is safe; for example, we could have a conflict with a write that was actually a NO-OP or otherwise didn't trigger a reconciliation.
* We could only support "patch" styles; I don't think this will work well for Gateway usecase
* We could have a callback to tell the caller to retry. This still kind of sucks with Gateway, since we only have one giant `ReconcileEverything()` function, but that is basically what would happen today anyways.

Another option is to forget about trying to use a shared 'status manager' at all. Each controller that wants to write to status can have their own queues and handle things as they see fit. We are already doing this today in 1-2 of the status writers. We could steal the WorkerPool there, and possibly even have a generic shared pool (such that the concurrency of the entire system never exceeds the limit, rather than having N workers * M controllers).

---

This was a sloppy brain dump, hopefully it makes sense... @ilrudie @MorrisLaw @therealmitchconnors

**Comment by MorrisLaw** [comment]
Thanks for sharing all of this context @howardjohn, very helpful!

Initially, I'm inclined to go with what seems to be the more forward-thinking way of having status writing controllers use their own queue and leveraging a generic shared pool. I'm assuming you're leaning towards that as well? Given the Ambient Status Writing PR where it uses it's own queue with PatchStatus.

If we had to stick with a shared status manager though, server-side apply seems ideal since we're letting K8s do it's job. I agree with what you pointed out with the shared queue approach, reconcile and retry loop can get messy when the reconcile loop isn't triggered. I've worked on systems like that and it's my least favorite. It can get super buggy when you're just trusting objects to trigger things as expected; there's always edge cases that get missed and it can get very nuanced. I'm not too familiar with Gateway API limitations around overwriting status but based on what you've pointed out that might be a bad idea. But again, not too familiar.

Assuming controllers write to their own queue and they have a generic shared pool.....

I'm curious about how the flow could look like. Some clarifications/questions:
- have a centralized generic worker pool created that is shared by status update controllers
- the worker pool should have a global limit set for pool size. is there a good method to determining appropriate size or is it decided iteratively/overtime? just a best guess based on number of controllers/expected controllers?
- one of N controllers submits a status update task to it's own queue. completely independent of the design and implementation of other status update controllers and their queues. (side note: might make sense to document best practices for designing controllers for this new way of status writing to ensure some type of standard/expectation when leveraging the shared worker pool... if it's not obvious that is)
- conflict resolution handled by the controllers and their respective queues (maybe include some type of callback mechanism when status update fails)
- how do we handle prioritization of the more critical status updates?
- lastly, if the intent is to move all status writing to one similar model. I'm a big fan of this! Would make things less complicated logically in the codebase instead of having different ways of doing the same thing.

**Comment by ilrudie** [comment]
We have 2 different types of status writing going on as well. There are informational status updates that are useful for understanding the state of the system, troubleshooting, etc... and there are functional status updates which enable some feature to function or proceed. Functional status updates are things we may want to handle differently from informational since things like the gateway deployment controller failing to update the address for gw/waypoint is pretty different in impact from failing to write that a policy was accepted.

**Comment by howardjohn** [comment]
> We have 2 different types of status writing going on as well. There are informational status updates that are useful for understanding the state of the system, troubleshooting, etc... and there are functional status updates which enable some feature to function or proceed. Functional status updates are things we may want to handle differently from informational since things like the gateway deployment controller failing to update the address for gw/waypoint is pretty different in impact from failing to write that a policy was accepted.

I half agree. But also one persons informational status is another's functional, as they could build third-party tooling that depends on the status?

Maybe they shouldn't do that, though. AS part of our status work, we should clear describe the stable and unstable surface

**Comment by ramaraochavali** [comment]
Agree with @ilrudie 's classification of status writing. I think that is a good way to think about optimizing/prioritizing them in shared pool.

**Comment by MorrisLaw** [comment]
> Agree with @ilrudie 's classification of status writing. I think that is a good way to think about optimizing/prioritizing them in shared pool.

Good point. That answers this question I had `how do we handle prioritization of the more critical status updates?`
