### ISSUE TITLE
Intermittent 503 after workload deployment configuring MaxSurge 100%

### ISSUE THREAD

**Issue by shonecyx** [istio/istio#52690]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

For rollout velocity, we'd like to configure the deployment with maxSurge 100%:
```
NAME         READY   UP-TO-DATE   AVAILABLE   AGE
ttlserver4   2/2     2            2           297d

    strategy:
      rollingUpdate:
        maxSurge: 100%
        maxUnavailable: 0
```

However after the rollout there is intermittent 503 and here is the sequence:
```
t0: old pod 1, old pod 2
t1: old pod 1, old pod 2, new pod 1, new pod2
t2: new pod 1, new pod2
```

The 503 depends on the EDS push latency for the new pods, if it pushed in t1 then there is no problem, however if it pushed between t1 and t2 then there will be intermittent 503 until if pushes all new pod IPs to the ingressgateway.

For now we have to keep maxSurge 50% to mitigate this issue and as long as there is good pod the ingressgateway default retry can mitigate, but we still want to enable maxSurge 100% and would like to know if there is a way to permanently fix the 503 issue.

### Version

```Text
istio 1.20
```

**Comment by howardjohn** [comment]
I don't see what we can possibly do here. Istio is an eventually consistent system, as is Kubernetes itself. This exact same issue exists in kube-proxy (and every other k8s networking). The solution is to not tear down the old pods so fast. https://blog.sebastian-daschner.com/entries/zero-downtime-updates-kubernetes is a good guide.

At best you could tune PILOT_DEBOUNCE_AFTER to be lower since Istio imposes a fixed 100ms delay on pushes, but its just a bandaid
