### ISSUE TITLE
missing format: framework.go:206] Log saving inconplete: %s1 error occurred:

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#527]
W0802 03:57:44.441] W0802 03:57:44.439587    6976 framework.go:206] Log saving inconplete: %s1 error occurred:

for instance in
https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_istio/519/istio-presubmit/173/

**Comment by yutongz** [comment]
@chxchx

**Comment by chxchx** [comment]
@ldemailly Errors during log fetching is not the reason to fail presubmit because logs are fetched only after any test has failed (`TestDefaultRouting` of bookinfo in this case). The error encountered when fetching logs is an internal error of stackdriver api, which is rather flaky and I would say happens 5% of the times. There isn't much I can do besides letting users know when this happens and the logs uploaded are therefore incomplete (the program continues fetching other logs despite the error).

I do realize the typo in the console logs and has made a PR correcting this. https://github.com/istio/istio/pull/529

**Comment by yutongz** [comment]
@chxchx  I think one thing you can do is change the log message and avoid using "Failed" or "Error" such that people will not be confused by fetching-log-error.

**Comment by chxchx** [comment]
That is what I did for other errors, but this one is from stackdriver and its message contains the "Error" keyword and was highlighted by Prow. I still want to surface verbatim the stackdriver error message since it could also be other things

**Comment by ldemailly** [comment]
fixed (I believe)
