### ISSUE TITLE
Ambient mode not working when using Kubernetes NetworkPolicy (NetPol) with the Canal (Calico) CNI

### ISSUE THREAD

**Issue by yardenshoham** [istio/istio#52742]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

#### What happened

I am using rke2 with the default CNI (Canal). My CSI is Longhorn. I installed Bitnami's `kube-prometheus` helm chart which comes with a `NetworkPolicy`. I installed Grafana and connected it to Prometheus. I was able to query Prometheus from Grafana.

I installed the ambient helm chart which was released last week. Grafana could no longer able to query Prometheus. I saw the following in the `ztunnel` logs: `connection timed out, maybe a NetworkPolicy is blocking HBONE port 15008: deadline has elapsed`.

I edited the NetworkPolicy of Prometheus:
```diff
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
...
spec:
  ingress:
  - ports:
    - port: 9090
      protocol: TCP
    - port: 8080
      protocol: TCP
+    - port: 15008
+      protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/component: prometheus
      app.kubernetes.io/name: prometheus
...

Then, Grafana was again able to query Prometheus.

#### Expected behavior

I'd expect Istio and Calico to "collaborate" and allow the NetworkPolicy that worked before to keep working. 

### Version

```Text
$ kubectl version

Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.0+rke2r1

$ istioctl version -i default

client version: 1.23.0
control plane version: 1.23.0
data plane version: 1.23.0 (12 proxies)
```

**Comment by yardenshoham** [comment]
Related:
- https://github.com/istio/istio/issues/51603
- https://github.com/istio/ztunnel/pull/1229

CC @bleggett @howardjohn

**Comment by bleggett** [comment]
> I'd expect Istio and Calico to "collaborate" and allow the NetworkPolicy that worked before to keep working. 

NetworkPolicy is not authored or enforced by Istio (by design, as Istio is not a CNI and NetworkPolicy - which is simple and purely L4 - is enforced by the CNI in Kubernetes)

If you set up an allowlist via NetworkPolicy, that by-definition implies everything that is not allowed is denied - this is how Kubernetes NetworkPolicy functions.

NetworkPolicy (like most of K8S) is explicitly declarative - it would be a massive security risk for e.g. Calico to "automatically" allow traffic on ports not listed in a user's NetworkPolicy.

The other option would be to give `istiod` permissions to rewrite your existing cluster-wide NetworkPolicies - which is also extremely undesirable, from both our perspective and a basic K8S security/permissions-boundary perspective.

This is a wontfix, as neither of those two options are something we (or Kubernetes) will ever do - Ambient works by tunneling traffic over 15008 like a VPN, or Wireguard, or SSH - if  you explicitly block the VPN/SSH/Wireguard port with networking policy, your VPN/SSH/Wireguard port won't work.

The solution for this is to add 15008 to any local NetworkPolicy you have in your cluster, which you have already done.

I do agree we should surface this issue more prominently in docs/`istioctl analyze`, so it's less surprising to users that have defined NetPols: https://github.com/istio/istio.io/issues/15281
