### ISSUE TITLE
Services with sidecar cannot talk to services without sidecar when mTLS is globally turned on

### ISSUE THREAD

**Issue by wattli** [istio/istio#5296]
Before customer installing istio sidecar, we have a svc A talking to svc B via http. 

However, if we install sidecar for svc A, and mTLS is turned on globally, i.e., by running istio-auth.yaml in this page: https://istio.io/docs/setup/kubernetes/quick-start.html#installation-steps. Then svc A cannot talk to svc B any more. Because svc A always sends https traffic while svc B expects http traffic.

The idea is when pilot constructs CDS, if mTLS is turned on globally, we always add ssl_context (v1 api)/tls_context (v2 api) to it, no matter whether the upstream service has sidecar or not. This is a bug when upstream service does not have sidecar.

**Comment by linsun** [comment]
Thanks Tao, this sounds reasonable.  What is the rough time frame for this?

**Comment by wattli** [comment]
I am talking with Networking team for support, i.e., we need to know whether the upstream has sidecar.

**Comment by wattli** [comment]
After chatting with @louiscryan , it seems this is pretty expensive to detect whether the other side has sidecar. He will add more context in this issue.

**Comment by louiscryan** [comment]
we're going to have this issue with mesh expansion and other situations where endpoints are registered but we don't know or control how they are registered. I'm wary of depending on Envoy to effectively register an endpoint for a service in the near term. This issue is exacerbated by folks directly creating ServiceEntry resources.

DestinationRule controls how a service is connected to at this layer and AuthorizationPolicy dictates what a service endpoint implements. The flag mentioned above controls global enablement of mTLS and is risky to use in existing clusters where the operator hasn't validated proper migration, i.e its really only safe to use for new clusters.

For folks incrementally rolling out mTLS they should use a combination of AuthorizationPolicy and DestRule to control the migration. AuthPolicy can declare that an endpoint accepts mTLS or Plaintext, then DestRule is updated to require mTLS when reaching that endpoint, then AuthPolicy can be updated to require mTLS once the metrics show that there is no Plaintext traffic.

**Comment by linsun** [comment]
@louiscryan just to make sure we are on the same page... Let's say I have a simple guestbook app that has 2 services (A and B).  I'm moving A to the istio mesh and B continues to run in the same k8s cluster.  A (with envoy side car) calls B (no envoy).  Can you apply AuthorizationPolicy for service B effectively when service B doesn't have side car?    Or are you suggesting using the new Auth policy to disable mTLS for the namespace X that A is deployed to?   And once service B is also moved to the mesh with service A, then user can 1)  test require mTLS among A and B using dest rule 2) enable mTLS for namespace X using Auth policy.

Essentially, user needs to turn off the mTLS globally for the mesh prior to 0.8... with 0.8, this is nicer because users can turn it on or off per namespace via the new AuthPolicy.

**Comment by wattli** [comment]
@incfly @diemtvu

**Comment by costinm** [comment]
For B (no envoy) we can't apply authorization policy or MTLS. What we can
do is set a DestinationPolicy
that configures 'no tls' for connections from A to B.

In 0.8 user should be able to turn on/off MTLS explicitly via
DestinationPolicy, per service (envoy-cluster or hostname).

The default helm templates are set with global MTLS off - we still ship the
'demo' istio-auth.yaml, but we expect
most users will use 'helm template' or 'helm' instead, so at install or
update they can set the global MTLS policy,
and to use DestinationPolicy to fine tune it.

**Comment by costinm** [comment]
There is another strange interaction here - if they are migrating from 0.7
to 0.8/alpha3.
In this case I'm not sure what should happen - in 0.7 we used some service
annotations
to disable mtls for some services. I assume users will keep them while they
upgrade to 0.8,
and create equivalent DestinationPolicy.

**Comment by linsun** [comment]
@costinm @wattli would the service annotation in 0.7 continue to work in 0.8?   It would not be obvious to user to change the service annotation to destinationpolicy as service annotation is at the service yaml today in 0.7. cc @esnible
