### ISSUE TITLE
Global dictionary used Mixer attributes are not updated with istio/api change

### ISSUE THREAD

**Issue by qiwzhang** [istio/istio#5306]
By design, whenever istio/api sha is updated in istio/istio.   It should generate a new 

mixer/pkg/attribute/list.gen.go

file in istio/istio repo if

mixer/v1/global_dictionary.yaml

is changed in istio/api repo

But this is not happen.   It cause Mixer server to use older version of global dictionary, fails the communication between Proxy and mixer.

**Comment by douglas-reid** [comment]
There is a go:generate script for this, iirc. It is a matter of running that when doing the SHA update, I believe.

**Comment by mandarjog** [comment]
And putting it in the build so it acts as agate

**Comment by gargnupur** [comment]
@douglas-reid , @mandarjog, @qiwzhang  : script to do go:generate in this case is mixer_codegen.sh right? But if I simply run this script, I get errors like this:

[libprotobuf WARNING google/protobuf/compiler/parser.cc:547] No syntax specified for the proto file: . Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
2018/06/14 21:34:41 protoc-gen-gogo: error:bad Go source code was generated: 14:1: expected 'IDENT', found 'import'
....
...
--gogoslick-v1.0.0_out: protoc-gen-gogoslick-v1.0.0: Plugin failed with status code 1.

Is anything required to be installed to run this script? 

Also, for this bug I was thinking we can make running this script part of 
"depend" target in Makefile...

**Comment by gargnupur** [comment]
Looks like we have this check depend.diff for vendor changes, extending this to run go generate ./... on Istio repo after any vendor changes..

**Comment by kyessenov** [comment]
Marking test/release since we need a new gate to make sure global dictionary is append-only. Also not 1.0 milestone.

**Comment by gargnupur** [comment]
/cc @ozevren , @geeknoid 
Work done till now: there is a go.generate.diff target in Makefile now which can be run to update generated files in repo. This does not require any tools to be setup on developers box.
Work left: Run this target in circleci. While doing this, I got the error that docker run fails because it can't connect to docker daemon. To solve this, I think following needs to be done:
1) Add the docker files we are using for go generate tools in circle ci docker file
2) Change protoc.sh, counterfeiter.sh, go-bindata.sh, such that it knows they are running in circleci and thus use protoc, counterfeiter and go-bindata commands directly rather than invoking docker run command.
