### ISSUE TITLE
istio-proxy use old pod ip get 503

### ISSUE THREAD

**Issue by buxiaomo** [istio/istio#53709]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Deploy two services, service A(10.244.7.211) will call service B's interface through the service name, when service B() is rebuilt, the Pod IP changes, and A will still use the old Pod IP when calling B.

Before  delete
<img width="1013" alt="image" src="https://github.com/user-attachments/assets/70b1d9ef-abc0-4b4b-9c0b-cd7a24834d6b">

After deletion
<img width="1189" alt="image" src="https://github.com/user-attachments/assets/ade25a50-14bc-4eb5-aaf1-63026c94fecd">

service A istio-proxy log

<img width="1252" alt="image" src="https://github.com/user-attachments/assets/55a4c70f-236b-45e3-afc4-8b1e3b9be704">

### Version

```Text
$ istioctl version
client version: 1.17.1
control plane version: 1.17.1
data plane version: 1.17.1 (633 proxies)

$ kubectl version --short
Client Version: v1.24.12
Kustomize Version: v4.5.4
Server Version: v1.24.12
```

**Comment by howardjohn** [comment]
1. Istio 1.17 is multiple years end of life and not supported. Please upgrade.
2. This is https://istio.io/latest/docs/ops/configuration/traffic-management/traffic-routing/#unmatched-traffic per the "passthroughclsuter". This means your app is picking the pod IP -- not Istio. Plausible caused by https://github.com/istio/istio/issues/27619, etc.
