### ISSUE TITLE
Documentation of defaultEndpoint in kubectl explain

### ISSUE THREAD

**Issue by imschuler** [istio/istio#54239]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

# kubectl explain gateway.spec.servers

shows a defaultEndpoint parameter:

# kubectl explain gateway.spec.servers
...
  defaultEndpoint       <string>
    <no description>
...

No such parameter is listed in the documentation

https://istio.io/latest/docs/reference/config/networking/gateway/

### Version

```Text
# istioctl version
Istio is not present in the cluster: no running Istio pods in namespace "istio-system"
client version: 1.24.1

# kubectl version
Client Version: v1.31.3
Kustomize Version: v5.4.2
Server Version: v1.31.3
```

**Comment by howardjohn** [comment]
This field is `$hide_from_docs` which intentionally does not make it show up. In istio.io that means we can hide it entirely but there is no way to hide it in `explain`.

Maybe we should unhide it (I don't know the history on why it is hidden) or translate `$hide_from_docs` into something like `This field is intentionally undocumented` rather than `""`

**Comment by imschuler** [comment]
thank you for the clarification
