### ISSUE TITLE
Mixer proxy access log should indicate errors

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#5429]
istio-proxy in front of Mixer produces access logs, however they always look at the same.

```
"POST /istio.mixer.v1.Mixer/Check HTTP/2" 200 - 18 0 5 5 "-" "grpc-go/1.11.1" "463fe601-fd1c-9b7b-ad31-6f76bb048ab7" "istio-policy:15004" "10.20.0.84:15004"
```
The return code is always 200.
We should return the check return code in a response header which can be captured in envoy accesslogs.

1. Add a return header
2. Capture return header in a custom envoy access log

**Comment by zainul-ma** [comment]
I also get this 
The return code is always 200.

event the grpc status code has been set to 503
and the pod app log showing grpc status code 503 but istio-proxy show

```
"POST /reverse.Restful/Echo HTTP/2" 200 
```

**Comment by kyessenov** [comment]
gRPC always returns 200 even for error status codes. We would need to parse
h2 trailers to extract the gRPC status. That can incur some CPU cost to
decode h2 traffic.

**Comment by zainul-ma** [comment]
how about the circuit breaker for service that use the gRPC
because as i know in istio , cicuit breaker trip when got error 5xx ?

**Comment by kyessenov** [comment]
It's two types of errors. It's still possible to get TCP or http2 errors to
trigger a circuit breaker on the upstream. These are transport level
errors. It's safe to retry, for example. Application level errors are
different and should not be always retried.

**Comment by lizan** [comment]
Adding [`%TRAILER(X?Y):Z%`](https://www.envoyproxy.io/docs/envoy/latest/configuration/access_log) to log format will log gRPC status.

https://github.com/envoyproxy/envoy/pull/3536 might be also related.

**Comment by zainul-ma** [comment]
ahhaa i see for grpc
but
@kyessenov i try deploy 2 services app service and db service both of them using istio 0.8.0, connection from app to db using protocol tcp
and then i try delete db deployment ,
so at the application level - log app service showing ```failed connect tcp error  .. ... ```
of course because the pod is died
but when i check the ```upstream_rq_pending_overflow``` for make sure the circuit is trip the value got zero
```
kubectl exec -it saving-txn-77965c7c89-rp2kd -- curl localhost:15000/stats | grep pending | grep postgresql
```

and the output
```
cluster.out.saving-postgresql.default.svc.cluster.local|tcp.upstream_rq_pending_active: 0
cluster.out.saving-postgresql.default.svc.cluster.local|tcp.upstream_rq_pending_failure_eject: 0
cluster.out.saving-postgresql.default.svc.cluster.local|tcp.upstream_rq_pending_overflow: 0
cluster.out.saving-postgresql.default.svc.cluster.local|tcp.upstream_rq_pending_total: 0
```

so it's the circuit breaker not working ?

**Comment by douglas-reid** [comment]
Seems like there are two possible actions here:
1. Add the trailer to the log format config for the envoy in front of istio-policy
1. Ensure that some attribute is being populated with the grpc status code in reports to Mixer.

**Comment by kyessenov** [comment]
I suggest 2. as the right approach. We have, in fact, disabled envoy access log in mixer sidecars due to performance concerns. Using istio telemetry for observing gRPC errors is consistent with the overall telemetry story.

Let's close this issue, and open another about general gRPC error monitoring.

**Comment by qiwzhang** [comment]
https://github.com/istio/proxy/issues/1805

**Comment by kyessenov** [comment]
closing since work on grpc attributes commenced.
