### ISSUE TITLE
Upgrade to istio 0.8 leaves istio-ca 0.7 running

### ISSUE THREAD

**Issue by costinm** [istio/istio#5628]
Doesn't block the RC0 - workaround is to delete it manually, but we should fix it or have a script or other tools to fix ( but ideally fix it in the automated script, for example by creating an empty deployment with the same name )

**Comment by costinm** [comment]
Also istio-mixer is left running

**Comment by hklai** [comment]
@wattli can someone from the security team pick this up?

**Comment by wattli** [comment]
Looking...

**Comment by wattli** [comment]
The reason is that we rename ca to citadel and mixer to policy in 0.8. And here is what I can see from my side:

$ k get po -n istio-system
NAME                                             READY       STATUS    RESTARTS   AGE
istio-ca-79556d4848-bvnbp                   1/1       Running     0                   9m
istio-citadel-5b7f966fdc-2wkmj              1/1       Running     0                   6m
istio-mixer-7b7d4dc8db-hn9km              3/3       Running   0                    9m
istio-policy-67b8b5ddc4-sxndz               2/2       Running   0                    6m

Since this is a one-time change, I would say we can either add some command lines in our website to manually delete the deployment (istio-ca and istio-mixer), or we can add it in our istio.yaml and istio-auth.yaml. I am fine either way, what do you guys think? @costinm @mandarjog

**Comment by wattli** [comment]
@douglas-reid

**Comment by wattli** [comment]
PR created: 
https://github.com/istio/istio.github.io/pull/1293

**Comment by hklai** [comment]
Since istio/istio.github.io#1293 is merged, can this be closed now?

**Comment by wattli** [comment]
I am sick today and ask @myidpt to handle it. Thanks Oliver!
