### ISSUE TITLE
Correct instruction for testing mutual TLS task

### ISSUE THREAD

**Issue by diemtvu** [istio/istio#5677]
Command to verify citadel should be:
```bash
kubectl get deploy -l istio=citadel -n istio-system
```
Also, this task should be rewritten to take into account authn policy. In fact, it could be removed to promote the use of authn policy to enable mTLS.

**Comment by diemtvu** [comment]
I think we could drop it to FAQ of how to check Citadel and key/cert installation.
How to verify a connection is in mTLS already mentioned in auth policy task, though we can also emphasize it more (e.g explain why request fail, or how to make curl request from proxy with proper key/cert)

**Comment by myidpt** [comment]
As you mentioned, there are still contents covered in this task that are not covered in authn policy.
I feel our FAQ is not very obvious for users to find :P Maybe we can move this task down to the bottom since it's more for help debugging instead of presenting a feature.

I think besides rewriting the "Before you begin" section, we need to modify/remove the "Verifying service configuration" section because it's still verifying the old global mTLS setting. Diem, do you want to work on this? :)

**Comment by jasmine-jaksic** [comment]
@diemtvu can you update the docs and close this issue?

**Comment by diemtvu** [comment]
#1332 is in review, hopefully it can be done today.
