### ISSUE TITLE
Pilot loses CRD configuration state intermittently

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#5763]
We have observed several times that pilot loses CRD configuration state.
The Issue came to fore while debugging https://github.com/istio/istio/pull/5669

That PR adds a `destination rule` and makes no other changes.
However as a result of adding that rule, it appears that pilot operates on empty config.
Given an empty, config pilot generates empty listeners and pushes them out which causes tests to fail.

There must be other ways to cause this condition.

**Comment by ostromart** [comment]
during TestGateway_HTTPIngress, when rules are applied:
018-05-22T00:05:12.780950Z	info	Running command kubectl apply -n istio-system -f testdata/v1alpha3/ingressgateway.yaml 
2018-05-22T00:05:13.277052Z	info	Running command kubectl apply -n istio-system -f testdata/v1alpha3/destination-rule-c.yaml 
immediately after the second one (destination-rule-c.yaml), we get:

buildGatewayListeners: gateways after merging: &{map[istio-ingressgateway.istio-system.svc.cluster.local:true] map[80:[port:<number:80 protocol:"HTTP" name:"http" > hosts:"uk.bookinfo.com" ] 443:[port:<number:443 protocol:"HTTPS" name:"https" > hosts:"uk.bookinfo.com" tls:<mode:SIMPLE server_certificate:"/etc/certs/cert-chain.pem" private_key:"/etc/certs/key.pem" ca_certificates:"/etc/certs/root-cert.pem" > ]]}
2018-05-22T00:05:13.372570Z	info	Servers: [port:<number:80 protocol:"HTTP" name:"http" > hosts:"uk.bookinfo.com" ]
2018-05-22T00:05:13.373192Z	info	hosts; [uk.bookinfo.com], virtualServices: []
2018-05-22T00:05:13.373281Z	info	omitting HTTP listeners for port &{80 %!d(string=HTTP) %!d(string=http)} filter chain 0 due to no routes
2018-05-22T00:05:13.373410Z	warn	FilterChains are empty!

So no virtualservices at this point i.e. they disappear when the destination rules are applied, which leads to no listeners. Cluster stays in that bad state, so running the same commands manually afterwards fails with the same mode. 
This issue has popped up in other places e.g. https://github.com/istio/istio/issues/5652 but in those cases some subsequent rule application or event (e.g. envoy crash) regenerates the correct listeners.

**Comment by mandarjog** [comment]
@Tahler Can you add the logs from your run this morning ? Just the snippet from istio-pilot discovery container would be good. Thanks.

**Comment by Tahler** [comment]
@mandarjog I pasted the [snippet as a gist](https://gist.github.com/Tahler/c4110f731497f9aaf61f52ac710bea06).

**Comment by rshriram** [comment]
Looking at the logs, this entire thing seems to be happening only for the gateways, not for the sidecars right? As far as gateways are concerned, this error is valid, because there are no virtual services associated with the gateway (yet). In other words, until a virtual service is explicitly bound to the gateway, no traffic will flow through.

**Comment by mandarjog** [comment]
This is none of that. 
It was because the destination rule was incorrect and it ended up ejecting all the destination rules, results in all subset clusters being ejected as well.
After spending all this time finding the bug, it turns out that a [PR](https://github.com/istio/istio/pull/5737) to fix this behaviour was merged yesterday.

@costinm @rshriram we need to add unit tests to `v1alpha3` ASAP. At present that directory has negligible test coverage.
