### ISSUE TITLE
ALPN upgrade to h2

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#5769]
This is a redo of https://github.com/istio/istio/pull/5618.

1. Turn on h2 upgrade when mTLS is turned on and the destination policy is `ISTIO_MUTUAL`.
 This guarantees that the other side is Istio and it is safe to upgrade to h2.
2. Ensure that h2 upgrade is only done when the destination is http/1.1.  (that is do not upgrade from tcp, tcp over h2 is not supported yet)
3. Ensure that ALPN is specified when h2 is already set. This ensures that correct negotiations take place.

**Comment by PiotrSikora** [comment]
I'd argue that we shouldn't ship any release with `"h2"` being advertised and `Http2SettingsOptions` being configured for non-HTTP traffic, so this might be a bit more urgent that 1.0, but I'm not sure how big of a change this is in terms of Pilot code.

We get away with it because Envoy currently ignores both of those for TCP proxy, but it might bite us during upgrades, when we have old Envoys announcing `"h2"` when there isn't any.

This is especially critical with ALPN-based routing (i.e. https://github.com/envoyproxy/envoy/issues/3397) that was already merged into Envoy.

/cc @rshriram FYI

**Comment by mandarjog** [comment]
We have reverted the original PR #5618 so nothing is being upgraded in 0.8 anymore. :-( 

This will follow shortly after 0.8.

**Comment by PiotrSikora** [comment]
cc @duderino @costinm (see #5618 and #6181 for prior work and discussions on the topic).
