### ISSUE TITLE
K8s network policies not taking effect

### ISSUE THREAD

**Issue by mbanikazemi** [istio/istio#5815]
K8s network policies are to take effect for new connections. With Istio, since the proxy (envoy) establishes connections and keeps them alive, even when apps are creating new connections, since the connections being used are already established, k8s network policies, if/when defined won't take effect.

This needs to be at least documented until/if it is decided that this needs to be addressed by for example watching for k8s network policies.

**Comment by andraxylia** [comment]
There should be no conflict with the k8s network policies. Can you provide more details on what does not work?

**Comment by andraxylia** [comment]
@spikecurtis have you noticed anything with Calico?

**Comment by spikecurtis** [comment]
I mean, I can confirm that Calico works by default in the way described: it only applies NetworkPolicy to connection setup.

**Comment by andraxylia** [comment]
thanks @spikecurtis your explanation. So this is specific to the case when the network policy is configured after a connection is already established, and a workaround would be to define the k8s network policy before attempting any connection.

**Comment by spikecurtis** [comment]
We use conntracking to identify packets associated with established connections, which then bypass the full network policy. This is both for speed, and convenience. Not everyone uses kernel conntracking, but I believe operating on connections rather than packets is the standard thing to do (not just Calico).

Without this behavior it is very difficult to manage usable rules. For example, let's say I have a service that listens on port 80, but also needs to call other services. I want to allow clients to connect on port 80, but not any other ports. Without conntracking, when my service calls out, I need to authorize traffic on the port the request uses so that I can receive the response. This is difficult because applications usually get assigned a random port. Conntracking takes care of this.

**Comment by andraxylia** [comment]
I see, thanks for the explanation @spikecurtis

**Comment by ronakpandya7** [comment]
Hello @spikecurtis,

What is the actual timeout for the envoys, so that the networkpolicy take effect on to the given pod ?

Thanks

**Comment by spikecurtis** [comment]
I'm afraid I don't know off the top of my head.  @rshriram do you know?

**Comment by rshriram** [comment]
The two have no relation. Istio does not process network policies

**Comment by spikecurtis** [comment]
Sorry, @rshriram I just meant, do you know how long Envoy keeps connections up by default when configured by Istio?

**Comment by rshriram** [comment]
I think around 60s for h1, perpetual (or upto 1024 requests) for h2, and perpetual for tcp.

**Comment by rachappag** [comment]
When Calico or any other CNI plug-in applies network policies ( IPtables or OVS flows ), it should flush the conntrack on each node `conntrack -F` or  delete specific connections in tracking table `conntrack -D -p tcp --orig-port-dst 8443`

**Comment by xeor** [comment]
Isn't this still a problem? Or where there any solutions made?
