### ISSUE TITLE
Monitor JWT public keys and push LDS when they change.

### ISSUE THREAD

**Issue by diemtvu** [istio/istio#5898]
Background: see [#4917](https://github.com/istio/istio/issues/4917).

**Comment by yangminzhu** [comment]
It seems the pilot now pushes the config to envoy every 60 seconds (See https://github.com/istio/istio/blame/master/pilot/pkg/proxy/envoy/v2/discovery.go#L34)

So is it still necessary to make a push immediately after the public key change? Otherwise we just wait for 60 seconds and pilot will do a new push for us.

cc @costinm, @rshriram, @quanjielin

**Comment by diemtvu** [comment]
This is for tracking purpose, we don't have to implement anything fancy yet. However, it's important to watch out for possible changes in the way pilot pushing LDS/CDS.

**Comment by diemtvu** [comment]
@quanjielin: this is related to https://github.com/istio/istio/pull/7393

**Comment by quanjielin** [comment]
per discussion offline, close this one since it's already fixed.
