### ISSUE TITLE
Enable mesh expansion in istio helm chart

### ISSUE THREAD

**Issue by gyliu513** [istio/istio#6024]
Currently, with istio helm chart, I cannot enable mesh expansion, it is better to add mesh expansion to istio helm chart as well. 

The proposal is we may need to add all of the services at https://github.com/istio/istio/blob/master/install/kubernetes/mesh-expansion.yaml to istio helm chart.

/cc @costinm @sdake @linsun any comments for this?

**Comment by costinm** [comment]
As I mentioned in other threads, my preference is to add Gateway entries,
and an optional 'internal-gateway' component of type
ILB.

We install istio-ca by default - and the secure ports are also enabled by
default: IMHO remote clusters must use secure control-plane
option if ILB is not available.

For 1.0 I think 'secure+regular gateway' is the larger priority, since it
can help in more cases.

**Comment by gyliu513** [comment]
Thanks @costinm , I will check your proposal in mail list and to see how we can proceed with this.

Meanwhile, I want to keep this issue open and append more detail if I have some progress.

**Comment by gyliu513** [comment]
mesh expansion was already in istio chart.
