### ISSUE TITLE
[Q] ingressgateway and ingress resources

### ISSUE THREAD

**Issue by maxkondr** [istio/istio#6067]
Hi,

configuration:
istio: 0.8.0
K8S baremetal installation v1.10.3

I am looking for service mesh integrated with ingress resources and studied: https://istio.io/docs/tasks/traffic-management/ingress/

There I see that `ingressgateway` is used for handling requests from outside of the cluster and we need to use Gateway+ Virtualhost from `networking.istio.io/v1alpha3` API. But it confused me a bit, please clarify the following:
1. is ingressgateway an ingress controller? can it replace NGINX ingress controller?
2. What should we use with ingressgateway to setup ingress resources: Gateway+VirtualHost or usual Ingress can be used as well? Are there any differences?
3. What is the best practices for using ingressgateway on baremetal installations (I mean there is no LoadBalancer) ?  as I understand I can use K8S Service with `type: NodePort` or I can use ingressgateway with `hostNetwork: true`. Are there any other options? 
The advantage of using NGINX is that it is bound to hostNetwork, but accordingly to docs https://istio.io/docs/tasks/traffic-management/ingress/#verifying-the-gateway-for-http the K8S service should be used for ingressgateway usage that involves kube-proxy into processing and add overhead.

Thanks

**Comment by maxkondr** [comment]
@frankbu 

3. Can I run NGINX as a `Gateway` instead of ingressgateway? How should I configure it ?

**Comment by frankbu** [comment]
Since VirtualServices are bound to Gateways, a Gateway implementation needs to know how to talk to Pilot and execute rules. There are 2 possibilities: 1) inject an envoy sidecar into the NGINX container to handle the routes, 2) I believe the NGINX people have created a version that works with Istio (maybe just a POC - I'm not sure).

Closing this issue, since it isn't a bug or feature request. You should ask this kind of question on the Istio user mailing list instead.
