### ISSUE TITLE
Health check port is not intercepted by Envoy

### ISSUE THREAD

**Issue by wattli** [istio/istio#6083]
https://github.com/istio/istio/blob/4042513b5dcc3d79ecfadc4fd503087f7609d1ae/install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml#L42

Currently envoy only captures ContainerPort, but not the ports for health check (for http and tcp). We need to fix this asap.

**Comment by wattli** [comment]
@costinm @louiscryan

**Comment by wattli** [comment]
This is introduced by https://github.com/istio/istio/pull/5070, and based on a discussion with @andraxylia , we will add health check ports to '-b' as well.

**Comment by costinm** [comment]
Why ? As it is, not intercepting health check ports that are not in container is the correct behavior.

**Comment by costinm** [comment]
I mean - once the health check port is working we may intercept them, but that's not ready yet. 

If we do intercept - we'll still need the code that adds a non-mtls tcp listener, which has the same behavior as not intercepting at all, just more complicated. Can you explain what is broken or different ?

**Comment by wattli** [comment]
What's broken:
a) If customers use the same port (say 8080) for regular traffic and health check, then health check will broken when mTLS is enabled.
b) If customers use different port, say 8080 for regular traffic and 8090 for health check, then mTLS is not enforced since clients can reach it at port 8090 without client cert.

Are you proposing a third option other than the two proposed in https://docs.google.com/document/d/1RxO3IBT8z68XNmM8tGWxrUcSbrRneiBWlL1A4qZf3CU?

**Comment by wattli** [comment]
@mandarjog , make sense, just need to mark this issue here. We should fix this once multiplex or your approach is ready. Since I don't think we want to keep this inconsistent interception (same port intercept / different port not intercept) behavior for 1.0.

**Comment by costinm** [comment]
Tao: (a) has nothing to do with how we capture ports. Not sure how it
relates to this bug either.

(b) - yes, if port 8090 is not declared as a container port or istio port,
it will not be intercepted or used by
Istio - no mixer, no mtls, no other Istio feature is enabled. We had
support for excluding ports before,
and the health check were explicitly excluded from MTLS in 0.7 and before,

So no change in behavior - the 8090 healthz didn't have mtls in 0.7 and
doesn't in 0.8.

**Comment by costinm** [comment]
Again - there is no bug to fix here. We have a user requested feature to be
able to exclude ports from capture,
either by opt-in or by opt-out. We have use cases ( dynamic ports ) which
are broken if we intercept everything.
We do not have a full firewall model - where we guarantee we block ports.

I think this is the correct behavior for 1.0 - I'm not aware of anyone
working on firewall or on a different fix for the
security problem that resulted in this fix.

Once we have clear requirements - and time - we can work on firewall
features. The split capture can work,
we still don't have a good solution for dynamic ports - but it's risky and
large effort. If we make a mistake
( like we did with the capture all ) we effectively disable all MTLS and
policy check benefits, since any attacker
could easily bypass them. As long as we claim to provide security features
(mtls, policy) - I think we should be
very careful with our own security.

**Comment by wattli** [comment]
So you think we should keep the current iptable interception behavior as it is for 1.0? To me I am fine either way, but I think we need better documentation on this.

**Comment by wattli** [comment]
Close for now and we can go back to this later if necessary.
