### ISSUE TITLE
fix istioctl bash completion

### ISSUE THREAD

**Issue by ayj** [istio/istio#6119]
Istioctl bash completion stopped working some time back which is useful to save typing for known commands, e.g. `istioctl get dest<TAB>` => `istioctl get destinationrule`

**Comment by vaidsu** [comment]
@ayj I am new to contributions in istio. I tried to do some initial research, I might have missed something, but if you could point to some direction it will be great. 

For instance, I guess (please correct me), istio uses ``cobra`` - hope I am right. 

When I further checked, the interface expects to use a function called [BashCompletionFunction](https://godoc.org/github.com/hyperledger/fabric/vendor/github.com/spf13/cobra#Command). 

I don't find any occurrence of that in the code base:
```bash
find . -name "*.go" | xargs grep -r "BashCompletionFunction"
./vendor/github.com/spf13/cobra/bash_completions.go:	if len(c.BashCompletionFunction) > 0 {
./vendor/github.com/spf13/cobra/bash_completions.go:		buf.WriteString(c.BashCompletionFunction + "\n")
./vendor/github.com/spf13/cobra/command.go:	// BashCompletionFunction is custom functions used by the bash autocompletion generator.
./vendor/github.com/spf13/cobra/command.go:	BashCompletionFunction string
```

Am I in the right track? Since you have mentioned it worked earlier, I am just curious when exactly was it working as I did not find any occurrences in the whole repo. 

Please help.

**Comment by ayj** [comment]
Thanks for reaching out @vaidsu. Take a look at `istioctl collateral completion --bash -o .` That generates a `istioctl.bash` in the current directory that can then be sourced. Printing to stdout is not supported anymore, but we should consider re-adding it. Ideally we could do something like `source <(istioctl collateral completion --bash)` as a one liner. Nice for demos and easy to add to your `.bashrc.`.

cc @geeknoid - collateral is also used for our doc gen. Any changes shouldn't break those pipelines.

**Comment by geeknoid** [comment]
Since we just dump the completion files using Cobra, this must be a bug in Cobra...

**Comment by linsun** [comment]
subscribe

**Comment by esnible** [comment]
It isn't a bug in Cobra.  Cobra only handles subcommand completion by default.  For `istioctl get` and `istioctl delete` we don't use subcommands.  The solution is to follow the example at https://github.com/spf13/cobra/blob/master/bash_completions.md .  I have a pull request available for review.

**Comment by murarisumit** [comment]
So as @ayj mentioned for code completion `istioctl collateral completion --bash` and then `source ./istioctl.bash` is the only way right now, or we are doing it some other way.
