### ISSUE TITLE
How to use multiple citadel in one cluster

### ISSUE THREAD

**Issue by gyliu513** [istio/istio#6182]
In 0.8, we can use external CA key and certificate according to here https://istio.io/docs/tasks/security/plugin-ca-cert/ .

The question is if I have multiple services and I want different services use different key and cert, how to achieve this?

I can start multiple citadel services, but how to let different workload use different citadel services?

/cc @rshriram comments for this?

**Comment by gyliu513** [comment]
I can see that the citadel has a parameter which can define the flag that is it listening via `listened-namespace`, so I can define which namespace that I want the citadel to monitor.

But the problem is that now I can only define one namespace for `listened-namespace`, this is not convenient for me to manage a large cluster with customized CA.

@wattli @rshriram @elevran comments for this?

**Comment by lei-tang** [comment]
@gyliu513  Our answers to your three questions are as follows:

Question 1: The question is if I have multiple services and I want different services use different key and cert, how to achieve this?
Different services will always get different key&cert to identify the workload. Is the question actually about having multiple Citadel (each with different signing key and certificate) and using them to issue certificates to different services? It will be great if you can elaborate your use case for this setup and we can help provide some practice guidance.

Question 2: I can start multiple citadel services, but how to let different workload use different citadel services?
You can run services in different namespaces, and having each different Citadel listening to a separate namespace. This per-namespace Citadel setup is for testing purpose. We’d like to understand your use case better to see what is the best way to support that in production environment.

Question 3: But the problem is that now I can only define one namespace for listened-namespace, this is not convenient for me to manage a large cluster with customized CA.
Currently, Citadel listens to either all namespaces or a particular namespace. If listening to all namespaces is insufficient to your scenario, please let us know. Any particular reason to run multiple citadels which each listening to a different set of namespaces?

**Comment by gyliu513** [comment]
@lei-tang My use case is that I was now grouping some namespaces to a group, and this group of namespaces will be used by a team. And each team want to manage their own cert, so I want to make sure that citadel can be set more fine-grained, such as each citadel can listen to a group of namespaces, but not only one or all.

**Comment by wattli** [comment]
@gyliu513 , this is not something we will be able to support in 1.0. But beyond 1.0, we may plan some resource to support this.

**Comment by gyliu513** [comment]
@wattli I opened an issue at here https://github.com/istio/istio/issues/6312 to trace it.
