### ISSUE TITLE
SpanName always be default-route instead of Api Path in zipkin in Istio0.7

### ISSUE THREAD

**Issue by Yisaer** [istio/istio#6187]
Hello, I use Istio 7.0 and install zipkin by zipkin.yaml in `istio-0.7.1\install\kubernetes\addons`. I use `spring-cloud-sleuth` in my springboot application and request A service which linked to another service.And here is my result.
![1](https://user-images.githubusercontent.com/13427348/41289517-a83b5966-6e7c-11e8-8f95-8314ad450830.png)

as you can see, All spanName are `default-route` instead of API Path
Is it normal or correct? How can I let these spanName be the real API Path.
For now , the only way for me to know its API Path is to find `http.url` in detail.
![2](https://user-images.githubusercontent.com/13427348/41289500-9a654e5a-6e7c-11e8-8d19-0ea9d542dc60.png)

**Comment by objectiser** [comment]
Yes this is the correct behaviour currently.

The problem with using the path as an operation/span name is that it could have path parameters - see https://github.com/opentracing/specification/blob/master/specification.md#start-a-new-span for a discussion on selecting an appropriate operation (span) name.

So the problem is how to identify a meaningful name from the data available to the proxy. The route, although not ideal, can provide useful information when multiple routes are defined.

More useful would be to derive an operation (span) name from some form of API definition - unfortunately this is not available at the moment but possibly in the future.

**Comment by rshriram** [comment]
There was a recent PR that effectively set the default operation to the service host name as the default operation (along with any path/prefix configured by the virtual service).

**Comment by objectiser** [comment]
@rshriram do you know the current situation with using openapi (or some subset) to define the service API, so that we could leverage it to define simple operation names?

**Comment by objectiser** [comment]
Found this https://github.com/istio/api/blob/master/mixer/v1/config/client/api_spec.proto discussed in https://github.com/istio/api/issues/344 - but would need to investigate further and see what is possible.

**Comment by chandresh-pancholi** [comment]
We are facing the same issue with Istio 0.6 version. 
From local, we can see the operation-name in Jaeger but when we hit Istio-ingress. it shows default-route. 
It is difficult to find traces with default-route as it's coming for every api call.

> Desired: "Istio-Ingress --> Service A --> MongDB query"

> Received: Istio-Ingress --> default-route

**Comment by rshriram** [comment]
cc @ayj as he did something recently with HTTPAPISpec.

**Comment by ayj** [comment]
[api_spec.proto](https://github.com/istio/api/blob/master/mixer/v1/config/client/api_spec.proto) allows you to define method/uri_template-to-attribute mappings in the proxy for API attribute generation. The same mappings information could possibly be used by the mixerclient to augment trace span data. cc @qiwzhang @ostromart
