### ISSUE TITLE
UF upstream connection failure results in 503s

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#6372]
https://storage.googleapis.com/istio-prow/pull/istio_istio/6330/e2e-suite-rbac-no_auth/1838/build-log.txt
(search for "failed to complete init")

Demo tests fail to run due to lots of "failed to fetch listeners" and "UF 503" errors:
```
"GET /productpage HTTP/1.1" 503 UF 0 57 0 - "10.12.1.1" "Go-http-client/1.1" "ae346f06-e3d2-959e-ac8a-c1690499ef1b" "35.230.48.115" "10.12.1.11:9080"
```

This is blocking daily builds. /cc @hklai

**Comment by ostromart** [comment]
The issue is that e2e_mixer target is still being invoked with v1alpha1 yaml (ingress) but the code is being forced to run v1alpha3 tests unconditionally (https://github.com/istio/istio/pull/6308/files). 
Some possible solutions:
 1. replace the test/local/e2e_mixer test target with the v2 command
 2. get rid of the v1 target and just use the v2 target for now
