### ISSUE TITLE
Istio download and install fails using curl

### ISSUE THREAD

**Issue by arun-gupta** [istio/istio#6383]
**Describe the bug**

Download and install of Istio using short URL fails:

```
$ curl -L https://git.io/getLatestIstio | sh -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  1448  100  1448    0     0   2771      0 --:--:-- --:--:-- --:--:--  2771
Downloading istio- from https://github.com/istio/istio/releases/download//istio--osx.tar.gz ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9    0     9    0     0     33      0 --:--:-- --:--:-- --:--:--    33
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.
Downloaded into istio-:
ls: istio-: No such file or directory
sh: line 36: cd: istio-/bin: No such file or directory
Add /Users/argu/tools to your path; e.g copy paste in your shell and/or ~/.profile:
export PATH="$PATH:/Users/argu/tools"
```

**Expected behavior**

This works:

```
curl -L https://github.com/istio/istio/releases/download/0.8.0/istio-0.8.0-osx.tar.gz | tar xzvf -
```

**Steps to reproduce the bug**
Steps to reproduce the behavior.

Just give the command on OSX:

```
curl -L https://git.io/getLatestIstio | sh -
```

**Version**
What version of istio and Kubernetes are you using? Use `istioctl version` and `kubectl version`

**Is Istio Auth enabled or not?**
Did you install the stable istio.yaml, istio-auth.yaml.... or if using the Helm chart please provide full command line input.

**Environment**
Which environment, cloud vendor, OS, etc are you using?

macOS 10.12.16

**Comment by subfuzion** [comment]
The actual reference to the link is in the docs [here](https://github.com/istio/istio.github.io/blame/master/content/docs/setup/kubernetes/quick-start.md#L239), but the issue is the [git.io link](https://git.io/getLatestIstio) itself. However, I just tested and the link actually works  for me. The resource was probably temporarily unavailable and the response was the error instead of a valid archive.

**Comment by brunoban** [comment]
If you open the link

`https://git.io/getLatestIstio`

You can see the script that gets triggered. This happened to me yesterday as well, the problem is a rate limit on this curl request to github's API:
```
curl -L -s https://api.github.com/repos/istio/istio/releases/latest
```

If it hits the max limit (which I'm not sure if it's project related or if it has something to do with my own acconut), the script doesn't fetch the latest version of istio properly and that happens. Same thing happened to me yesterday.

**Comment by ymesika** [comment]
If you are behind a company NAT then probably Github API triggered a limitation due to frequent incoming hits coming from the company's network. This is a temporal limitation though.

The Github API is being accessed to fetch the latest Istio version. I wonder if, as part of the release process, we should inject the version into this script to avoid accessing the Github API just for this purpose.

cc @hklai

**Comment by hklai** [comment]
Yes, since we have pretty much standardized our release branching process, we can update the doc (also versioned by releases) and use 

https://raw.githubusercontent.com/istio/istio/<release-branch>/release/downloadIstioCandidate.sh

and hardwire the version in the script in the corresponding release branch.

**Comment by rvennam** [comment]
The script has been updated to output a message with a workaround if this happens.
`Unable to get latest Istio version. Set ISTIO_VERSION env var and re-run. (export ISTIO_VERSION=1.0.4)`

**Comment by arun-gupta** [comment]
@rvennam The default download is still failing:

<img width="999" alt="screen shot 2019-01-04 at 12 14 22 pm" src="https://user-images.githubusercontent.com/113947/50708830-89497e80-101a-11e9-892e-fc565f227c0b.png">

Is this not a problem for all macOS users?

**Comment by rvennam** [comment]
@arun-gupta This isn't a problem for all users. As someone pointed out earlier, I suspect its a github rate limiting issue from your network

Take a look at the sh script : https://github.com/istio/istio/blob/master/release/downloadIstioCandidate.sh#L25
It tries to get the ISTIO_VERSION by curling https://api.github.com/repos/istio/istio/releases/latest

I suspect this curl call is failing for your network. Can you try this in your terminal?
```
curl https://api.github.com/repos/istio/istio/releases/latest
```
You should see large json output.

**Comment by bitencars** [comment]
Hey guys,
I can't download the Istio (1.0.5) last version. I have the same problem... Download doesn't start!!!

**Comment by lxiaodao** [comment]
You can see all release by https://github.com/istio/istio/releases.
And download the special version us command below.
curl -LO https://github.com/istio/istio/releases/download/1.2.5/istio-1.2.5-linux.tar.gz
