### ISSUE TITLE
Istio’s Mixer how to connect  Fluentd DaemonSet?

### ISSUE THREAD

**Issue by jiuchongxiao** [istio/istio#6396]
Istio’s Mixer how to connect  Fluentd DaemonSet?

In your cluster, you may already have a Fluentd DaemonSet running, such the add-on described here and here.

who config out fluentd connect,please help me?

**Comment by douglas-reid** [comment]
@jiuchongxiao Have you looked at the Task on the website related to fluentd logging: https://istio.io/docs/tasks/telemetry/fluentd/ ?

This issue seems more like something that should be discussed on our mailing-lists, rather than tracked in an issue on the repo.  Let's move the discussion to istio-users@googlegroups.com or to the rocket chat (https://istio.rocket.chat/home). I'm going to close this issue.
