### ISSUE TITLE
Are CloudFoundry integration tests broken by TLS Permissive mode?

### ISSUE THREAD

**Issue by rshriram** [istio/istio#6407]
**Describe the bug**
The CF integration tests were passing reliably until the TLS Permissive mode PR (#6121)
 https://circleci.com/gh/istio/istio/118082?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

As of a PR before #6121, i.e. #6330, the CF tests were passing https://circleci.com/gh/istio/istio/117302?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link.

Please fix..
update: This is just a hunch. It may be that the test is actually flakey.

 cc @hklai / @zachgersh or others for CF. 
@incfly / @wattli for the TLS pr

**Comment by rshriram** [comment]
@hklai once this is fixed, we should make the CF integration test a required test, as it has been reliably passing for a while without any flakes.

**Comment by wattli** [comment]
@incfly can you take a look?

**Comment by hklai** [comment]
@rshriram SGTM

**Comment by incfly** [comment]
I'm looking it now.

**Comment by incfly** [comment]
Took a look on recent PR presubmit history, it does seem indicate the multiplexing PR is the culprit. However, when I tried to run the test locally, one commit before the multiplexing, it still fails.

1. `git checkout ef5c5167e1fb6dddb263f49e7f7acb8693950ab9`, this is just one commit before the multiplexing
2. `sudo iptables -t nat -A OUTPUT -d 127.1.1.1/32 -p tcp -j REDIRECT --to-port 15001
set -o pipefail; ISTIO_PROXY_IMAGE=proxyv2 go test -v -timeout 20m ./tests/e2e/tests/pilot/cloudfoundry  \
                | tee -a /tmp/cloudfoundry-before.log`, run the test.
3. I still got the failure.

Meanwhile from the test log, I see the following [stack trace](https://paste.ee/p/KNrAK). It seems like because some we access an element out of the slice index range. That's at [mixer.go#L338](https://github.com/istio/istio/blob/master/pilot/pkg/networking/plugin/mixer/mixer.go#L338).

@rshriram Any idea? Do I miss some steps when trying to run the test locally?

**Comment by kyessenov** [comment]
This is indeed a bug. I'm waiting for https://github.com/istio/istio/pull/6310 to land to get rid of the hack in mixer.go.

**Comment by kyessenov** [comment]
Yeah, once that PR gets in I can submit a fix for the bug in mixer filter
config.

**Comment by rshriram** [comment]
Thanks for debugging @incfly .

**Comment by incfly** [comment]
One more data point, when I create the CP with multiplexing, on `release-1.0-snapshot.0`, the cloudfoundry and multiplexing both tests passed.

**Comment by kyessenov** [comment]
fixed by https://github.com/istio/istio/pull/6442
