### ISSUE TITLE
Error from fetching logs in e2e should be transparent for users

### ISSUE THREAD

**Issue by yutongz** [istio/istio#654]
When istio e2e tests failed, we fetch log from stackdrive. During this process, we throws out several error messages which of course not the actual reason why e2e failed, but those message confuses users and make debug harder, we should just say "info:" or "log warning"

**Comment by chxchx** [comment]
Everywhere else in the code has switched to using words like warning or info. However, all errors returned by StackDriver are surfaced as-is, and may contain keywords like failed or error that prow loves to highlight. I prefer not to mask such errors since they include critical information about what has happened.

**Comment by chxchx** [comment]
Closing this issue now that no longer fetching logs from stackdriver but running kubectl logs instead
