### ISSUE TITLE
Provide an easy way to trace which envoy version is being used in the proxy_debug and release docker images

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#6572]
@mdhume commented on [Tue Jan 30 2018](https://github.com/istio/old_issues_repo/issues/176)

**Is this a BUG or FEATURE REQUEST?:** Feature Request

**Did you review istio.io/help and existing issues to identify if this is already solved or being worked on?**: Yes

**Feature Request:**
Y

**Describe the feature:**

Currently to figure out which envoy version is being used, one would need to trace back by using the docker SHA specified in the pilot repo to the git SHA in the proxy repo, to get the git SHA of the envoy repo.
Even in the docker container version command returns `/usr/local/bin/envoy  version: 0//DEBUG`

Would it be possible to expose this more explicitly as part of the docker or part of the github repo itself?

**Comment by irisdingbj** [comment]
User can log in the istio-proxy container and use the envoy admin port to get the envoy version they used, eg: curl localhost:15000/server_info 
envoy 0/1.7.0-dev//RELEASE live 58024 58024 0

So seems we only need to add a doc about this?

**Comment by irisdingbj** [comment]
@elevran @rshriram  what is your comments about above way to get envoy version? If you agree that method, I will submit a PR to add info in our doc.

**Comment by rshriram** [comment]
Envoy version will not work because of the way we compile Istio proxy. But if you figure out how to add the version info while compiling proxy, it would be very helpful. It requires some bazel stuff. Best place to start is istio/proxy code - look at the bazel stuff used to compile. And compare with how envoy adds the version info using Bazel.

**Comment by irisdingbj** [comment]
@rshriram sorry but I have not got your point about " Envoy version will not work because of the way we compile Istio proxy."
I logged in my istio-proxy container and can get the version info: curl localhost:15000/server_info
envoy 0/1.7.0-dev//RELEASE live 57964 57964 0 

The istio-proxy container image I used is:
istio-proxy:
    Container ID:  docker://03d73e719a5231254d845daa3095b03112da8bf94c89dd4a6ad3813ac164a802
    Image:         docker.io/istio/proxyv2:0.8.0
    Image ID:      docker-pullable://istio/proxyv2@sha256:1930f0603321b1917b2249c576ecb4141aaceeaae5fcc0760b6a88dc88daea3e

**Comment by elevran** [comment]
envoy and istio-api versions are added as labels to images (i.e., available via `docker inspect -f '{{ .Config.Labels }}' $image`)
