### ISSUE TITLE
Allow disabling of Galley web-hook registration in Helm

### ISSUE THREAD

**Issue by ozevren** [istio/istio#6783]

**Comment by ayj** [comment]
Fixed by https://github.com/istio/istio/pull/6690. Validation (via webhook) can be disabled with [this](https://github.com/istio/istio/blob/12d362277ca15bcb7784eb1a65f6277a47d87fd8/install/kubernetes/helm/istio/values.yaml#L106) option.

We'll need to document in the k8s setup instructions when this option should be disabled (e.g. unsupported k8s provider, older versions).
