### ISSUE TITLE
Question: Custom Mixer Template Types

### ISSUE THREAD

**Issue by jon-whit** [istio/istio#6795]
I'm reading into Mixer templates and trying to figure out how to most elegantly solve the following use case:

We have a gRPC service that stores a mapping between users and the permissions the user has been assigned. JWTs are used for end-user authentication on protected service paths. We would like to use Mixer to get the permissions associated with the subject of the request at request time (either as an attribute generation step or during the mixer check call) and leverage the RBAC adapter to permit/deny the request based on the users permissions (permissions will be set as attributes of the request context).

----------------------------------------

My question is, would this functionality best be exposed by introducing a custom template that is an Attribute Generator template type? What would be the recommended approach here? The reason we have to do this is because we don't have control over the JWTs that are being crafted for our organization, so we have to reach out to gain additional meta about the subject before we can make authorization decisions about the subject. In the near future we won't have this problem, because the JWTs will contain this meta, but for now we need to be able to do this.

**Comment by liminw** [comment]
@jon-whit, sorry for the long delay. I was OOO while the issue was assigned to me. And I did not notice it till now. I saw you started another email thread to discuss this topic. I am not sure if your question is already answered. 

Currently the only supported way for "groups" is that you add the group information as a JWT claim. And for now, the JWT claim can only be a single string. But we are aware of the issue, and plan to fix it soon (to allow multiple strings in a JWT claim). 

So today you can specify in ServiceRoleBinding:
```
subjects:
- properties:
    request.auth.claims[group]: "abc"
```
If you have a "group" claim in your JWT that is "abc", it will pass authorization check. 
```
  group: "abc"
```

We will soon support the case that if you have a "group" claim in your JWT that has multiple strings, it will also pass the authorization check. 
```
group: ["abc", "xxx"]
```
I understand that you do not have control over the JWTs for now, and you want to instrument this "user->groups" mapping from your own service endpoint. We have an ongoing discussion on how to support this use case. Ideally, we should let you configure the endpoint you want to retrieve information from, and Istio fetches the information for you. This way, you do not need to develop your own adapter just for the purpose of retrieving group information. I think the use case you described is a common use case that we would like to support. I apologize that we do not have a good story at this point. But we are working on that and hopefully will add such support soon.

**Comment by jon-whit** [comment]
@liminw Thank you for your response! This support will really help out. Is there an ETA on when this support might roll out (v1.1, v1.2, etc..)?

**Comment by liminw** [comment]
@jon-whit This feature is currently under discussion/design. Once we have settled on the design and planning, I will be able to give you an estimate on the timeline.
