### ISSUE TITLE
Remove Eureka support

### ISSUE THREAD

**Issue by ymesika** [istio/istio#6917]
Eureka v2.0 [has been discontinued](https://github.com/Netflix/eureka/wiki).
We should consider removing the installation support and docs from our future releases.

**Comment by ijsnellf** [comment]
cc @costinm @rshriram @frankbu ^^^

**Comment by ijsnellf** [comment]
Assigning myself unless someone else wants this.

**Comment by ijsnellf** [comment]
Should be done now.

**Comment by pparth** [comment]
Eureka V2 was never released and Eureka V1 is the one still used by Netflix. Eureka V1 is also widely used by the community. I do not understand how you ended up with such a decision to completely remove the bits based on information which is not even true. In any case, is there a REAL reason for deprecating the Eureka Pilot platform adapter? If so, how do you propose a current Eureka-based micro-services system is going to be rolled out to a new, Istio-based, Kubernetes-based system without the use of such an adapter?

**Comment by vasilievip** [comment]
@pparth we ended up with "eureka sidecar" which puts sidecar IP's of pods into eureka, there is limitations, however solution seems to be working. If you interested - we can opensource it.
<img width="827" alt="eureka_sidecar" src="https://user-images.githubusercontent.com/1525698/69108642-24c4c180-0a2a-11ea-907e-7abb047f96c3.png">

**Comment by pparth** [comment]
@vasilievip  This is the solution we eventually came up with too. We are currently working on a light-weight Quarkus-based Java eureka client sidecar service. 
Can you mention some of the problems you encountered with this approach?

**Comment by vasilievip** [comment]
First one is that our producer services published on 8080 port and if you switch-off ribbon+eureka on consumer, feign goes to http://service-name/..., which is routed to 80 port. All services with eureka were deployed as headless in k8s and in order to avoid code changes (e.g. placing service+port name into configs for feign) or deploying proxy between consumer and producer, we need to redeploy all services with k8s service which routes 80 and 8080 to 8080. Initially we did setup subnet for k8s services for low number because of headless k8s services usage, but now we need to re-subnet k8s services network, which eventually results in re-setup of all k8s clusters.

Second one is that we wanted to enable "deny everything which is not allowed" for traffic management, but services which still use ribbon+eureka not known to istio, basically calls outside of mesh to sidecar is going from outside of mesh, so we decided to postpone this policy until everything is migrated.

We implemented sidecar in python, so it is very lightweight.
