### ISSUE TITLE
Issues with Calico (NetworkPolicy) and Istio

### ISSUE THREAD

**Issue by Stono** [istio/istio#7025]
Hey, 
We're currently trying to enable Calico NetworkPolicy for services which are currently part of our Istio mesh.  What we're seeing is rules gradually be applied, take this example..  I missed out a required inbound rule, and as you can see, gradually over time we start to see failures.

<img width="408" alt="screen shot 2018-07-11 at 22 18 25" src="https://user-images.githubusercontent.com/1486729/42599976-c9ea0fc4-8558-11e8-8917-99ccf42b199b.png">

It feels to me like NetworkPolicy, when envoy is in play, is only being applied to new connections rather than existing ones, and envoy is doing some keep alive (can anyone confirm this)?

I also feel this *may* be a duplicate of https://github.com/istio/istio/issues/5815, but i'd like someone with a bit more understanding of istios interaction with Calico to confirm.

Ta

**Comment by Stono** [comment]
Ok, is there a time out on that connection?  Or is that something we can configure.

Feels a bit "brute force" to have to restart every application in order to apply a network policy.

**Comment by rshriram** [comment]
I don't know the timeouts off the top of my head. But eventually, these persistent http connections die away due to inactivity. the only exception being TCP. Now the question is how long is this "eventually", for which I don't have an answer :(. I need to dig into Envoy code to give you the exact answer.
