### ISSUE TITLE
Citadel's SPIFFE-based cert should probably include the Subject DN

### ISSUE THREAD

**Issue by adamglt** [istio/istio#7153]
**Is your feature request related to a problem? Please describe.**
Certs generated by Citadel contain nothing but the Subject Alternative Name (SAN), in accordance with SPIFFE's view (https://github.com/spiffe/spiffe/issues/56 and https://github.com/spiffe/spiffe/pull/75/files).
This is a bit awkward for enterprise adopters that want to gradually introduce Istio into older infrastructure, which often (or near always) rely on the SubjectDN (O=something CN=something.else...).

**Describe the solution you'd like**
Citadel already allows for a const "O" entry using the `--org` flag.  
We could probably include the same spiffe URI as the CN, which should be good enough for most cases.  
I can't think of a specific issue that might arise, but I guess it can be configurable.

**Describe alternatives you've considered**
Destroying the corporate structure and retiring to a remote island.

**Additional context**
Excluding tests/flags, it's pretty much a one-liner. I'm just not sure it's in line with Istio's views on the subject, so opinions are welcome.

at: https://github.com/istio/istio/blob/91a85fa9917b45705d8a24ede6c1f167b61e4019/security/pkg/pki/util/generate_csr.go#L55
```
// GenCSRTemplate generates a certificateRequest template with the given options.
func GenCSRTemplate(options CertOptions) (*x509.CertificateRequest, error) {
	template := &x509.CertificateRequest{
		Subject: pkix.Name{
			Organization: []string{options.Org},
+++			CommonName: options.Host,
		},
	}
```

**Comment by justinburke** [comment]
> This is a bit awkward for enterprise adopters that want to gradually introduce Istio into older infrastructure

Hi, could you say a bit more about this older infrastructure. Presumably the infrastructure isn't able to parse the SAN extension field or URIs, correct? Additionally, the older code isn't going to be able to interpret the "spiffe://" URI format (otherwise it would just be updated to pluck the URI from the SAN field directly). Can you help us better understand the goal of copying the SPIFFE URI into the CN field?

**Comment by justinburke** [comment]
cc @evan2645

**Comment by adamglt** [comment]
Well, the systems I'm talking mostly verify clients with basic ACL/Whitelist based stuff.  
So they'd have the basic capability to inspect a subject DN (signed by a trusted CA) and verify it, with no real parsing beyond that.  
The full spiffe URI would just be like any other "service identity" string.

**Comment by adamglt** [comment]
More specific example: most Java-based stuff (e.g. Kafka, Cassandra, other Apache stuff) usually default to the JDK's implementation of inspecting an X509 Principal.

For example, Kafka uses this: http://hg.openjdk.java.net/jdk8u/jdk8u/jdk/file/15ef6431fffc/src/share/classes/sun/security/x509/X509CertImpl.java#l1821
(basically the subject DN)

You can obviously swap most of those out without too much effort, but there's a mountain of systems we can't (/won't) touch.

**Comment by adamglt** [comment]
All good, I'll try to clarify our case (and future uses).

The JDK does provide an easy way to extract SANs, but the standard behavior we find in most systems is identifying a client using the SubjectDN.  
Specifically in Kafka, the default behavior for extracting a string-based ID from a session is here: https://github.com/apache/kafka/blob/65b5ccf6413369aa4f21c72abcdf31ca72a79b00/clients/src/main/java/org/apache/kafka/common/security/authenticator/DefaultKafkaPrincipalBuilder.java#L113

Which eventually gets to the JDK's `SSLSessionImpl.getPeerPrincipal()` (http://hg.openjdk.java.net/jdk8u/jdk8u/jdk/file/15ef6431fffc/src/share/classes/sun/security/ssl/SSLSessionImpl.java#l565), which returns `peerCerts[0].getSubjectX500Principal();` - leading to the code in the comment above.

This identity is then checked against Kafka's basic ACL implementation, allowing you to specify things like `ID:O=bla;CN=abcd-in-bla; can consume topic1`, `ID:O=bla2;CN=xyz-in-bla2; can produce to topic2;`, etc.

As the names suggest, these are the default behaviors, and in Kafka's case - replacable.
You can provide a different `jar` with your own `PrincipalBuilder` and `Authorizer` to the Kafka broker, and identify/authorize clients however you'd like.

The case with other, non open source and not so actively maintained is very different, and sooner or later you run into `LegacySystemX` that whitelists post-handshake clients based on `X500Principal` and nothing else.  
In these cases, if it finds the `spiffe` URI in the CN, it can just be regarded as any other internal client (non resolvable string) and whitelisted as such.  
It's not an ideal usecase (obviously), but it seems like a logical bridge between the current (/old) standards and spiffe.

I can't speak for the correctness or implications of putting the actual spiffe URI itself in the CN - I don't know enough about that domain to really tell right from wrong. Ideally/eventaully, I guess there should be some way to configure how the CSR transforms into a SubjectDN.

**Comment by justinburke** [comment]
> As the names suggest, these are the default behaviors, and in Kafka's case - replacable.
> You can provide a different jar with your own PrincipalBuilder and Authorizer to the Kafka broker, and identify/authorize clients however you'd like.

It seems like Kafka in particular is sufficiently extensible that we don't have to create a workaround for that system. It's been a useful example Java system to consider for the purposes of this discussion, but it appears that we could implement a way for Kafka to pluck out the URI SAN field of a certificate. Is that accurate?

> The case with other, non open source and not so actively maintained projects is very different, and sooner or later you run into LegacySystemX that whitelists post-handshake clients based on X500Principal and nothing else.

I think I understand where you're going with this example, but it's honestly difficult to help without more specifics. Perhaps the foundational systems for those legacy apps would be extensible, even if the legacy app itself is not?

Some other things we should consider regarding this change request:
(1) Once we include a spiffe URI in the CN, we effectively can never remove it. Once the Citadel CA begins publishing certs with the spiffe URI in the CN, we should assume that some systems will rely on it. Therefore, this isn't a short-term, stopgap measure. 

(2) Inclusion of the spiffe URI in the CN is not part of the spiffe SVID specification. It's not against the spec, but it's not part of it. The significance here is that including it in Citadel doesn't mean that other spiffe CAs will also decide to include it. Systems relying on the CN field may only ever work with a single CA system (Citadel). Both as Istio matures and the spiffe spec gains broader industry traction, we should assume that other CAs will be built to support the spiffe spec (but without CN field support).

(3) The PKI community is trying to move away from the unstructured CN field. It's been deprecated for a decade or so. Absent a sufficiently compelling specific use case which requires the CN field, we should err on the side of being compliant with outstanding (current) specifications.

**Comment by adamglt** [comment]
> It seems like Kafka in particular is sufficiently extensible that we don't have to create a workaround for that system. It's been a useful example Java system to consider for the purposes of this discussion, but it appears that we could implement a way for Kafka to pluck out the URI SAN field of a certificate. Is that accurate?

Well, kinda. The part about Kafka allowing this extension point is of course true.  
My point was more about the default behavior of Kafka - until googling `kafka spiffe` comes up with more than `here are some results with 'spiffe' omitted`, people are going to use (and rely on) the common behaviors.  

It's one of the most likely systems to be found in large enterprises, and as a result - extremely prone to be customized to the point of global uniqueness, immediately becoming a legacy system itself.  
A good exercise in understanding the realities of productionized Kafka is counting fortune100 companies using Kafka versions older than 5 years.  
If you allow multiple entries per company (e.g. running separate Kafka 0.7 _and_ 0.8 clusters because of some inability to upgrade), you might end up with more than 100.

> Once we include a spiffe URI in the CN, we effectively can never remove it.

I don't think the backwards compatibility aspect of it is that severe, feature flags / deprecation notices are still possible, although not ideal.

I do agree with the overall point (protecting Istio from day1-deprecated features), and the things I control (e.g. our internal Kafka, Cassandra, legacy stuff) can and probably will adapt to _eventually_ read SAN.  

Out of our internal scope, though - I know from experience that other firms, clients, banks, etc will brush off a change request to modify authentication behavior in almost every non-0day scenario.  
We (and probably every financial firm on the planet) have at least one live session with a client using their home made encryption, and a 3 year old patch waiting to be deployed "when they're ready".

Perhaps this issue should have a corresponding issue in SPIFFE talking about how SVID can support a more gradual change.  
If you feel they're not very likely to support that flexibility, I guess we can close this.

**Comment by evan2645** [comment]
The SPIFFE spec has purposefully omitted text relating to the CN and other commonly-used fields in order to allow for "dual-use" certificates and migrations. There are a ton of existing systems utilizing various fields in the Subject (as you have noted), and we definitely don't want you to have to choose one or the other when trying to adopt SPIFFE.

So, as @justinburke has mentioned, the SPIFFE stance is use the CN as you please... however I think there are a few downsides to putting a SPIFFE ID in the CN. First, I think a lot of software has certain expectations of what to find in CN (e.g. a hostname), and a SPIFFE ID is likely a surprise. Will the Kafka ACL system accept a full SPIFFE ID as a value? They have `:`s and `/`s etc. I wouldn't be surprised to find breakage around this in various softwares for one reason or another. It would be good to ensure this actually works as intended before making any changes.

Second, in the general case, there are many folks for whom CN already has a meaning. If developers come to expect SPIFFE IDs in CN, minting dual use certs and migrating from a non-SPIFFE system to a SPIFFE system will be much more difficult. This is a concern that has been explicitly voiced by users in the SPIFFE community in reference to this github issue.

Finally, the current state represents a carrot in that "if you implement SAN URI, you can get SPIFFE compatibility". If we put SPIFFE IDs in CN, we will need a stick "you must implement SAN URI or your stuff will stop working". Given that PKI community is trying to move away from CN, putting a SPIFFE ID there feels kind of like a step backwards IMO.

All that said, I think that ultimately compatibility is in everyone's best interest. Historically, CN has been hostname... SPIFFE is trying to correct a lot of problems that have come from that, however if we are looking for CN compatibility, I'd prefer to see a hostname (i.e. a DNS name) there than a SPIFFE ID. I realize that this also brings its own challenges. If putting a SPIFFE ID in CN is absolutely necessary for compatibility, I'd strongly recommend it be optional and not the default. I doubt that the SPIFFE community will want to change the spec to address CN field directly, however we can raise the topic on our next community call if necessary.

Hope this helps.

**Comment by adamglt** [comment]
> Will the Kafka ACL system accept a full SPIFFE ID as a value? They have :s and /s etc. I wouldn't be surprised to find breakage around this in various softwares for one reason or another. It would be good to ensure this actually works as intended before making any changes.

Yeah, works with Kafka's basic ACL/Authorizer (no hostname verification).  
I see the point though - switching the mentioned legacy systems to no-verification (for those  who require it) would have the same operational (bureaucratic) effort as just accepting SANs.

RE: everything else - points accepted, maybe we can rephrase the issue to focus on the real problem - adopting SPIFFE gradually, through some dual-use CA (and can Citadel provide that?).

Can/should Citadel allow _some_ customization, so it lets users create dual-use certificates? i.e.: 
- *Default* - SPIFFE section remains as is, everything else defaults to empty excepts Org (as it is now)
- *User provides some set of flags / CRD* - Citadel resolves a static config to some transformation `t` where `t(flagConsts, certificateSigningRequest/serviceAccount) + SPIFFE = dual_use_cert` (this is already precedented with the `--org` flag, albeit not dynamic)
- *User provides an endpoint for Citadel to query before signing* - seems over the top.

If this isn't the way forward, how does a user get Istio + dual-use certs?  
Is dropping Citadel for something home-grown but retaining all related Istio features possible/recommended?

**Comment by myidpt** [comment]
cc @wenchenglu @wattli 
I think the best way to solve this issue is to have a thorough discussion on next SPIFFE community meeting. Istio security can follow the decisions made on the meeting.

One side note: CN does not support multiple values; SAN supports multiple values. We should think about whether this is good enough for all the use cases.

**Comment by wattli** [comment]
I agree with @justinburke and @evan2645 's points. CN is something we want to get rid of and we don't want put it back in Citadel. Looking forward to the spiffe discussion.

**Comment by adamglt** [comment]
Here's the Kafka `PrincipalBuilder` we're using right now - https://github.com/Traiana/kafka-spiffe-principal

As mentioned, with Kafka it's easy enough to plug in something else.  
For other systems - I don't there's a way around some dual-use CA.

**Comment by myidpt** [comment]
@adamglt 
We have brought up this up on SPIFFE and Istio team meetings. We agree to have Citadel support encoding SPIFFE identity in the X.509 certificate Common Name field, with the following constraints:

1. Encoding identity in CN is not enabled by default. It is controlled by a flag (possibly Citadel command line flag).
2. Certificate SAN field always carries the SPIFFE identity, it is not affected by the flag.
3. We should start with minimal support. The flag controls encoding CN for all the certificates issued by Citadel.

adamglt, it will be appreciated if you or some one from your team can implement this feature. Otherwise, the implementation may take some time :)

**Comment by adamglt** [comment]
Couple questions in #7629, probably easier to discuss there

**Comment by boeboe** [comment]
Related to https://github.com/istio/istio/issues/40615 and https://github.com/istio/istio/issues/42114
