### ISSUE TITLE
I can't test Ansible installer with daily builds

### ISSUE THREAD

**Issue by tvieira** [istio/istio#7250]
**Describe the bug**
With the current Ansible installer, you can't test it with daily builds or custom builds. No matter what build I download, it will always look at github istio latest release (at the moment, 0.8.0) and install this version.

**Expected behavior**
I should expect the installer to figure out what is the current release from the release tarball I downloaded, pull and install the related images.

**Steps to reproduce the bug**
Download latest daily build from https://gcsweb.istio.io/gcs/istio-prerelease/daily-build/ and follow the instructions at https://preliminary.istio.io/docs/setup/kubernetes/ansible-install.html - it doesn't matter if it is OpenShift or kubernetes 

**Version**

```bash
$ istioctl version
Version: release-1.0-20180719-09-15
GitRevision: e695b0a289014e4e5ac08998dde70432d3acc46f
User: root@0681b4aee144
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.4", GitCommit:"bee2d1505c4fe820744d26d41ecd3fdd4a3d6546", GitTreeState:"clean", BuildDate:"2018-03-12T16:21:35Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
(istio-release-1.0-20180716-16-37)

$ minikube version
minikube version: v0.28.1
```

**Is Istio Auth enabled or not?**
It doesn't matter for this issue.

**Environment**
Running on Linux Fedora 28, minikube with KVM.

**Comment by geoand** [comment]
When I was thinking about it a while back (although I didn't ponder this too much), I didn't come up with a solution that would work for both the downloaded artifact and local development mode

**Comment by LillyWu** [comment]
@geeknoid  do you have any interest on my above PR to fix this? 

Users could set the release tag in the ansbile-playbook command line directly.
If they want to user their local playbooks, they only need to set the `istio_release_tag` to the correct version and the istio project path with `"istio": {"dest": <PROJECT_PATH>,` . Once these two parameters set, the local ansible playbook/roles will be used rather than the remote.

**Comment by geoand** [comment]
@LillyWu We used to have support for multiple istio versions like your PR adds, but it turned out to be a hassle because it's hard for the playbooks to account for the differences between Istio versions so it was removed.

In my mind what we need is the following:

* The playbooks should operate under the assumption that they are part of an Istio release, that is that all the necessary Kubernetes - Istio resources can be found in a path relative to the playbooks.
* Provide an override to the location of the Kubernetes Istio Resources. This should only be necessary for those who develop the playbooks because when working from source the Kubernetes Istio resources needed by the playbooks are not available.
