### ISSUE TITLE
Prow /retest  <testName> causes the test to be skipped and marked as test “passed” 

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#7255]
Prow /retest <testName> causes the test to be skipped and marked as test “passed” 

cc @rshriram

**Comment by sebastienvas** [comment]
/retest is to retest all the tests, and if there is no change /retest will not run a specific passing test. In order to run a specific test, you need to run /test <test> as dictated by the bot in the comments.

There were some issues related to this fixed in Prow, so I upgraded Prow with the latest. Please re-open this bug when you see this happening.
