### ISSUE TITLE
externalTrafficPolicy should be set to Local for ingress

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#7328]
For `origin.ip` to be available, kubernetes should not obfuscate client IP. This requires configuring ingress service external traffic policy per https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#service-v1-core.

**Comment by PiotrSikora** [comment]
@kyessenov is there anything blocking change to `Local`? If not, do you want to fix that or should it be assigned to someone else?

**Comment by kyessenov** [comment]
Please go ahead.

**Comment by rshriram** [comment]
This would cause uneven load won’t it? The doc is not clear on how traffic reaches the service ip in the first place and how this works with load balancer service types.

**Comment by PiotrSikora** [comment]
@rshriram possibly, assuming that we have many instances of the gateway.

**Comment by rkpagadala** [comment]
@kyessenov  We want to cut a build for 1.0.1 on Friday, what is the status of this bug

**Comment by kyessenov** [comment]
Why me? Check with @costinm .

**Comment by PiotrSikora** [comment]
@rkpagadala see https://github.com/istio/istio/pull/7918.

**Comment by kyessenov** [comment]
I'd like to reiterate that we would like this set on ingress envoys. The load-balancing concern is outside of scope of istio, since it is usually handled by an external / cloud load balancer on the path to istio installation, and not programmed through k8s APIs.

**Comment by donbowman** [comment]
+1 but be aware of https://github.com/kubernetes/kubernetes/issues/65387

**Comment by smawson** [comment]
Anything left to do here? This is a stale?

**Comment by PiotrSikora** [comment]
@smawson Due to the discussion in #7918, we now have the ability to configure `externalTrafficPolicy` (release-1.0: #7918 and #9143, release-1.1: #8941 and #9704, master: #8941 and #9703), but it's still set to the default value (`Cluster`, which obfuscates client IP), and requires operators to opt-in into `Local`.

My understanding is that there is no desire to flip the default to `Local` until it's proven safe in all environments Istio is being used, so I'm going to change the milestone to "nebulous future", since there is nothing else to be done for the time being...

cc @costinm @mandarjog @rshriram
