### ISSUE TITLE
balancing between services hosted on differente namaspaces

### ISSUE THREAD

**Issue by jeusdi** [istio/istio#7357]
**Is your feature request related to a problem? Please describe.**
I'd like to load balancing traffic between two services (v1, v2) running on two different namespaces.

**Additional context**
Guess `service:v1` is running on `ns1`, and `service:v2` on `ns2`.

Up to now, I've been able to create a virtual service and a destination rule, but both services running inside the same namespace.

    apiVersion: networking.istio.io/v1alpha3
    kind: DestinationRule
    metadata:
      creationTimestamp: null
      name: recommendation
      namespace: istio-project
    spec:
      host: recommendation
      subsets:
      - labels:
          version: v1
        name: version-v1
      - labels:
          version: v2
        name: version-v2

And a `VirtualService`:

    apiVersion: networking.istio.io/v1alpha3
    kind: VirtualService
    metadata:
      creationTimestamp: null
      name: recommendation
      namespace: istio-project
    spec:
      hosts:
      - recommendation
      http:
      - route:
        - destination:
            host: recommendation
            subset: version-v1
          weight: 75
        - destination:
            host: recommendation
            subset: version-v2
          weight: 25

This configuration is balancing between both services.

How can I change that in order to get my goal?

**Comment by pamelin** [comment]
Hey @jeusdi,  I'm not sure if you've tried using fully qualified domain names for services?

In your `VirtualService` you would use `recommendation.ns1.svc.cluster.local` for `v1` and `recommendation.ns2.svc.cluster.local` for `v2` similar for `DestinationRule` you would use full host name instead of short. You would need two `DestinationRules` one per service in the different namespace. I haven't tested it but by the look at the documentation it should work: https://istio.io/docs/reference/config/istio.networking.v1alpha3/#Destination
