### ISSUE TITLE
Does Istio implement load balancing algorithm based on latency?

### ISSUE THREAD

**Issue by agile6v** [istio/istio#7360]
As the title describes. Thanks.

**Comment by sdake** [comment]
@agile6v thank you for your question.  The Istio community is striving to answer these sorts of questions via stackoverflow (here: https://stackoverflow.com/questions/tagged/istio) so that everyone can benefit from the global knowledge base provided by stackoverflow.  Would you be kind enough to close this issue and ask your question there?

Cheers
-steve

**Comment by agile6v** [comment]
OK. Thanks.
