### ISSUE TITLE
Istio/envoy route not updated when pod switch replicasets (changing labels) with GRPC

### ISSUE THREAD

**Issue by sanguinius69** [istio/istio#7411]
**Describe the bug**
When moving one pod from one Replicaset (app=A) to another Replicaset (app=B,version=v1) by relabeling, istio is not picking up the new route (envoy is not updating the endpoints with the correct IP) The pods have a GRPC server running on port 80. No problem with HTTP it seems 

**Expected behavior**
I should have an endpoints in istio-proxy to route to live pod

**Steps to reproduce the bug**
Have a replicaset with label app=a, create another replicaset with label app=b,version=v1 with also destinationrule and virtualservices already created, move the pod by using kubectl label --overwrite, it is not possible to reach it for --several-- minutes (might be more)
When I look in any istio-proxy container with 
```istioctl proxy-config pilot POD_NAME  eds ```

then I find my clustername entry but the endpoint is empty:
```
--
  "clusterName": "outbound|80|v1|APP.NAMESPACE.svc.cluster.local",
  "endpoints": [
    ]
```

**Version**
K8s version: v1.9.7-gke.3
Istio version: 0.8.0 

**Is Istio Auth enabled or not?**
no it is not
**Environment**
Using GKE

**Comment by Disturbing** [comment]
Istio Team - could use some love here <3

**Comment by john-a-joyce** [comment]
Have you been able to try this using 1.0 code and if so do you still see this issue.   We are investigating a possible issue that could be the same,  but the setup is a bit different.  We are using 1.0 but it's a multicluster setup.  It is also on a GKE environment.    The endpoint that isn't populated is from a remote cluster.   Still doing a root cause but can provide an update here if we find something concrete.
