### ISSUE TITLE
why not use slack for user channels?

### ISSUE THREAD

**Issue by dunjut** [istio/istio#7554]
Hi, this is a simple question and probably not much valuable to developers.

Kubernetes, CNI, calico, envoy and a lot more, they all use slack for users communication, why istio chooses RocketChat instead?

**Comment by thisisnotapril** [comment]
Hi @dunjut! We chose RocketChat as it is an open source chat program.

**Comment by dunjut** [comment]
@thisisnotapril It's really a perfunctory reply.

If open source is the only reason, why not host istio on gitlab?

**Comment by thisisnotapril** [comment]
@dunjut when the Steering committee was reviewing the chat options it was right after Slack had changed to cut off APIs; and we had a good bit of feedback from the community and other project leaders that this was a turn-off and not the spirit they wanted to see. The feedback was that as an open source project we should support other open source projects! 

Since a user chat program was a new add it was easier to follow that philosophy than a large migration would require. Totally valid question for our overall providers. Honestly it hasn't been considered because it hasn't been raised as an issue + the overall pains of migration. Going forward as we consider adding in new tools the open source aspect is something that will be factored in evaluating those tools.

**Comment by thisisnotapril** [comment]
@dunjut btw i'm going to move this issue/convo to the community repo so it'll be there for other folks who have the same question.

**Comment by thisisnotapril** [comment]
Issue moved to [istio/community #70](https://github.com/istio/community/issues/70) via [**ZenHub**](https://www.zenhub.com/)
