### ISSUE TITLE
Envoy TLS connection remains alive after certificate expired

### ISSUE THREAD

**Issue by wattli** [istio/istio#7630]
Reported by a customer from slack, full context:

I am trying to verify that proxies reject certificates which have expired. I have a 1.0 mesh running with MTLS enabled. I deploy bookinfo and verify it's operational. I ssh to the host running the bookinfo productpage pod, disable ntp, and change the time to a date outside the certificate validity period. I tail the productpage proxy and details proxy logs. I curl the productpage expecting to see an unresponsive details service or some type of error related TLS handshake failure, but I see no errors and the bookinfo app runs normally. Am I missing something? For more details: https://gist.github.com/danehans/e5f2749b59a68e4170482974845fad02

The steps you provided me helped. I also had to delete the `istio.default` secret, so Citadel would create a new `istio.default` secret with the shortened NotBefore and NotAfter dates. However, I am still not seeing the expected behavior or any log messages from the sidecar proxies indicating TLS connection/handshake failures. I am still able to access the productpage ingress gateway. Sometimes productpage loads with details, sometimes it doesn't. The same goes for reviews. I have verified the sidecar proxies are using the updated client cert and the date is well after the `Not After` date of the cert:
```# kubectl exec $(kubectl get pod -l app=details -o jsonpath={.items..metadata.name}) -c istio-proxy -- cat /etc/certs/cert-chain.pem | openssl x509 -text -noout  | grep Validity -A 2
        Validity
            Not Before: Aug  2 18:23:13 2018 GMT
            Not After : Aug  2 18:26:13 2018 GMT```

```# kubectl exec $(kubectl get pod -l app=details -o jsonpath={.items..metadata.name}) -c istio-proxy -- date
Thu Aug  2 18:52:36 UTC 2018```

After restarting the proxy containers, I see the expected behavior. It appears that the proxy reads the certs:
```2018-07-31T21:07:19.154995Z    info    Monitored certs: []envoy.CertSource{envoy.CertSource{Directory:"/etc/certs/", Files:[]string{"cert-chain.pem", "key.pem", "root-cert.pem"}}}```
but it does not use them:
```[2018-07-31 21:07:19.201][21][info][config] external/envoy/source/server/configuration_impl.cc:50] loading 0 static secret(s)```
Maybe because they are expired?
Citadel is not running.
I set the following Helm TLS params: `--set global.mtls.enabled=true` and `--set global.controlPlaneSecurityEnabled=true`
When I `curl -I http://$DETAILS_SVC_IP:9080/details` from the productpage proxy, I get this error: `curl: (56) Recv failure: Connection reset by peer`. This is what I would expect to see without having to restart the proxies.

**Comment by danehans** [comment]
I'm the person that reported the above issue via Slack. For additional information regarding:

> The steps you provided me helped.

The steps taken were:
- Update the Citadel deploy with `--workload-cert-ttl=3m` and `--max-workload-cert-ttl=5m`
- Delete `secret/istio.default` so Citadel creates a new secret that includes the reduced cert expiry times.
- Verify that proxies get the new certs.
- Remove the Citadel deploy so proxies are unable to get new certs.

After waiting well beyond `--max-workload-cert-ttl=5m`, I expect bookinfo services to be unable to communicate with one another, but they can. After restarting the proxies, I then see the expected behavior. It appears proxies are reading certs from memory and not from disk.

**Comment by lizan** [comment]
Can you paste [/certs](https://www.envoyproxy.io/docs/envoy/latest/operations/admin#get--certs) 
output from envoy admin port here as well?

**Comment by incfly** [comment]
Before:
```
// 20180806154345
// http://localhost:15000/certs

{
  "ca_cert": "Certificate Path: /etc/certs/root-cert.pem, Serial Number: 01cdf79db6441d0805805a52b103ba71, Days until Expiration: 364",
  "cert_chain": "Certificate Path: /etc/certs/cert-chain.pem, Serial Number: 9bbac65fe1160e9070a06bb47027fffc, Days until Expiration: 89"
}
```

After

```
// 20180806155001
// http://localhost:15001/certs

{
  "ca_cert": "Certificate Path: /etc/certs/root-cert.pem, Serial Number: 01cdf79db6441d0805805a52b103ba71, Days until Expiration: 364",
  "cert_chain": "Certificate Path: /etc/certs/cert-chain.pem, Serial Number: d4046685dbd4295fde995a64cd197093, Days until Expiration: 0"
}

```

So this means the cert reloading succeed? but the `listener.10.56.3.18_9080.http.10.56.3.18_9080.downstream_rq_2xx` is keep increasing while I continuously send requests...

**Comment by PiotrSikora** [comment]
`Serial Number` changed, so yes, certificate chain was updated.

**Comment by JimmyCYJ** [comment]
cc @lizan

**Comment by incfly** [comment]
After more investigation, the summary is: connection between sidecars are established before cert expired, and still persist after cert expired, so the request can still go through. According to @lizan , this is an expected Envoy behavior.

@danehans some more details:

1. Modified istio-citadel generate a short TTL certificate
2. Pilot agent detects that, restart the Envoy, note at this point the cert is still valid.
3. Connection/handshake is established successfully.
4. Cert expire, connection is still there.

At the first glance, this can be a security threat, and we can let Envoy to kill the connection after the cert expire. However, discussed with @lizan , this might not be ideal, because it can cause networking outage when all Envoy detects the updates, and trying to kill the connection at the same time.

**Comment by danehans** [comment]
@incfly I have validated your findings and created a detailed write-up [here](https://gist.github.com/danehans/e5f2749b59a68e4170482974845fad02#file-ct1631-md).

Envoy v2 API Connection Manager uses the [idle_timeout](https://www.envoyproxy.io/docs/envoy/v1.7.1/api-v2/config/filter/network/http_connection_manager/v2/http_connection_manager.proto) configuration parameter to close inactive connections after a period of time. By default, Envoy will never close an idle connection and it appears that Istio does not support configuring this parameter. Please confirm.

I don't understand why tearing down an idle connection is not ideal. This would not effect all proxies, just connections between proxies that have exceeded the `idle_timeout`. Furthermore, Envoy supports the `drain_timeout` configuration parameter to gracefully shutdown H2 connections (5s default).

If my finding are correct, this is considered, by many, a security vulnerability. Please let me know if the title of this issue should be changed or a new issue created to address the `idle_timeout` configuration issue.

**Comment by lizan** [comment]
Tearing idle connections are not a problem, but that doesn’t resolve the
issue. Active connections are still alive and killing all active
connections after certain time after certificate renewal is not ideal, it
will cause many reconnection happen at same time. For non-HTTP protocols
the sidecar cannot do graceful tear down either.

**Comment by danehans** [comment]
@lizan Yes, I understand. Dealing with active connections is not my issue at this time. Allowing idle connections to permanently exist is my issue. I need the ability to set `idle_timeout` for Envoy's using Istio.

**Comment by danehans** [comment]
As for how to deal with active connections, why not implement [RFC 5746](https://tools.ietf.org/html/rfc5746)? It's my understanding that BoringSSL [supports 5746](https://github.com/google/boringssl/blob/master/include/openssl/tls1.h#L231-L232) and Envoy supports server-side TLS [renegotiation](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/auth/cert.proto.html?highlight=allow_renegotiation). However, I'm unsure if Envoy fully supports RFC 5746.

**Comment by lizan** [comment]
Renegotiation is generally considered insecure. BoringSSL doesn't support server-side renegotiation, it only does handle server-initiated renegotiation when it acts as client, see [here](https://boringssl.googlesource.com/boringssl/+/master/PORTING.md#tls-renegotiation). Allowing renegotiation is more security vulnerable than what it fixes. TLS 1.3 dropped renegotiation support at all.

**Comment by PiotrSikora** [comment]
Erm, you focused so much on updates from Citadel, that I've completely missed the real issue you were talking about, sorry about that!

Yes, certificates (and their expiration) are verified only at the connection time, during TLS handshake. This is true for all TLS connections in general, and not specific to Istio / Envoy. That is because clients are pretty much only verifying that they're connected to the correct host.

Since renegotiation is basically non-existent in TLS nowadays, there is no way to refresh certificates on the existing connection, though there is some work on [Secondary Certificates in HTTP/2](https://tools.ietf.org/html/draft-ietf-httpbis-http2-secondary-certs), which would allow to use new certificates for new requests over existing HTTP/2 connection. This would help HTTP/2 and gRPC on connections that outlive the validity of certificates used to establish the connection.

Alternatively, we could simply tell clients to stop sending new requests on the "expired" connection and re-connect to get new certificate.

**Comment by danehans** [comment]
@lizan @PiotrSikora thank you for the additional information. As I mention in https://github.com/istio/istio/issues/7630#issuecomment-411899637, tearing down idle connections is priority #1 for me. Do you see any issues with adding support to configure Envoy's `idle_timeout`? I may be able to take this on with some direction.

**Comment by lizan** [comment]
Add support `idle_timeout` would be nice anyways, so go for it.

> Alternatively, we could simply tell clients to stop sending new requests on the "expired" connection and re-connect to get new certificate.

Eventually we would need this ability to fully address the issue.

**Comment by PiotrSikora** [comment]
As @lizan mentioned, adding ability to configure `idle_timeout` is fine.

However, it really doesn't address the expired certificates issue, since clients making a request every few seconds will never be effected by it, therefore it's trivial to circumvent `idle_timeout`-based solution to this problem.

**Comment by PiotrSikora** [comment]
(Not stale)

**Comment by hd-deman** [comment]
(Not stale)

**Comment by ramaraochavali** [comment]
@lizan @PiotrSikora My understanding is that for listeners this is not a problem - but for clusters, even if certs are updated envoy connections are not dropped and in for some scenarios where a mesh client (cluster) talks to a server that is not on mesh, for some servers it looks like requests are failing with connections using expired certs. Is that because of server renegotiation?

**Comment by ramaraochavali** [comment]
On rereading the code, it looks like secrete update (not initial fetch) via SDS, does not put listener/cluster in to warming and hence existing connections( with old secrets) are never dropped. Is my understanding correct? @lizan
