### ISSUE TITLE
Multiple virtualservices on the same host do not merge

### ISSUE THREAD

**Issue by patrickppeng** [istio/istio#7674]
**Describe the bug**
I did the similar test with deploying 2 applications as reported in #6046 - bookinfo and httpbin. One of the applications always returns 404 in the following cases:

case 1: single namespace
bookinfo app - bookinfo-gateway and bookinfo virtualservice
httpbin app - httpbin-gateway and httpbin virtualservice

case 2: single namespace with single gateway
bookinfo app - bookinfo-gateway and bookinfo virtualservice
httpbin app - httpbin virtualservice (with short name bookinfo-gateway defined in gateways list)

case 3: multiple namespaces with single gateway
bookinfo app - bookinfo-gateway and bookinfo virtualservice in namespace1
httpbin app - httpbin virtualservice in namespace2 (with fqdn bookinfo-gateway.namespace1.svc.cluster.local defined in gateways list)

the application returns 200 if I removed the other virtualservice file in above case.
here are the yaml files of the gateway and virtualservices for case 2:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.istio.io/v1alpha3","kind":"Gateway","metadata":{"annotations":{},"name":"bookinfo-gateway","namespace":"default"},"spec":{"selector":{"istio":"ingressgateway"},"servers":[{"hosts":["*"],"port":{"name":"http","number":80,"protocol":"HTTP"}}]}}
  clusterName: ""
  creationTimestamp: 2018-08-03T18:35:36Z
  generation: 1
  name: bookinfo-gateway
  namespace: default
  resourceVersion: "10845"
  selfLink: /apis/networking.istio.io/v1alpha3/namespaces/default/gateways/bookinfo-gateway
  uid: 039d51b8-974c-11e8-a97b-00505680c68c
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP
```
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.istio.io/v1alpha3","kind":"VirtualService","metadata":{"annotations":{},"name":"bookinfo","namespace":"default"},"spec":{"gateways":["bookinfo-gateway"],"hosts":["*"],"http":[{"match":[{"uri":{"exact":"/productpage"}},{"uri":{"exact":"/login"}},{"uri":{"exact":"/logout"}},{"uri":{"prefix":"/api/v1/products"}}],"route":[{"destination":{"host":"productpage","port":{"number":9080}}}]}]}}
  clusterName: ""
  creationTimestamp: 2018-08-03T19:10:19Z
  generation: 1
  name: bookinfo
  namespace: default
  resourceVersion: "10535"
  selfLink: /apis/networking.istio.io/v1alpha3/namespaces/default/virtualservices/bookinfo
  uid: dce03829-9750-11e8-a97b-00505680c68c
spec:
  gateways:
  - bookinfo-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        exact: /productpage
    - uri:
        exact: /login
    - uri:
        exact: /logout
    - uri:
        prefix: /api/v1/products
    route:
    - destination:
        host: productpage
        port:
          number: 9080
```
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.istio.io/v1alpha3","kind":"VirtualService","metadata":{"annotations":{},"name":"httpbin","namespace":"default"},"spec":{"gateways":["bookinfo-gateway"],"hosts":["*"],"http":[{"match":[{"uri":{"prefix":"/status"}},{"uri":{"prefix":"/delay"}},{"uri":{"prefix":"/headers"}}],"route":[{"destination":{"host":"httpbin","port":{"number":8000}}}]}]}}
  clusterName: ""
  creationTimestamp: 2018-08-03T18:57:54Z
  generation: 1
  name: httpbin
  namespace: default
  resourceVersion: "10157"
  selfLink: /apis/networking.istio.io/v1alpha3/namespaces/default/virtualservices/httpbin
  uid: 20d0e173-974f-11e8-a97b-00505680c68c
spec:
  gateways:
  - bookinfo-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /status
    - uri:
        prefix: /delay
    - uri:
        prefix: /headers
    route:
    - destination:
        host: httpbin
        port:
          number: 8000
```

**Expected behavior**
I assume both case 2 and case 3 (#6483 should have fixed the issue) should work in 1.0. 

**Version**
Version: 1.0.0
GitRevision: 3a136c90ec5e308f236e0d7ebb5c4c5e405217f4
User: root@71a9470ea93c
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.6", GitCommit:"a21fdbd78dde8f5447f5f6c331f7eb6f80bd684e", GitTreeState:"clean", BuildDate:"2018-07-26T10:04:08Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by rshriram** [comment]
This has nothing to do with gateway namespace. You are using wildcard host in two virtual services bound to same gateway. think of this as merging two VirtualHost entries in nginx, both on same port and both specifying same host (*).  It will have non-deterministic behavior. The same behavior happens here as well when you specify two virtualhosts with same host values, bound to same gateway

**Comment by vadimeisenbergibm** [comment]
@patrickppeng You have to specify different hosts in different virtual services.

**Comment by patrickppeng** [comment]
Thanks for the clarification. It works well with different hosts. 
My follow-up question is which way is usually recommended to create the "Ingress-like"?  a gateway-virtualservice pair or multiple virtualservices bound to a single gateway? or any of the combinations?

**Comment by amishra1982** [comment]
@rshriram @vadimeisenbergibm 
Hostname per service seems a lot to ask customers to setup/configure if we have more than say 10 services to be exposed. 
Here is a scenario where a standard nginx has worked well for me in the past 
1. Create a server nginx conf such that it can listen on just one host name
2. Have a bunch of config files included which can be used for redirection. The key is that each service just brings it's own configuration for redirection but the access to service is always using one host name.

Wondering how this can be done using Istio ingress-gateway? 
i.e something like do not treat virtualservice with same host as error but really treat as a merge. This way each service can bring their own match parameters and not need to keep modifying the same Virtual service using something centralized. 
May be these last few statements are based on me not knowing if there is a way to achieve this already.

**Comment by kyessenov** [comment]
cc @rshriram @louiscryan 
This is an issue for a customer. The customer uses helm to manage multiple services. These services share the host but use different URI matches on two virtual services. What should be the advice for people who use helm to manage ingress-type resources?

**Comment by louiscryan** [comment]
@amishra1982 In step 2 of your nginx example something was composing multiple nginx conf files into a single file that nginx then loaded.

One option that we recommend is to use some form out out-of-band composition of these files into a single VirtualService resource which is then pushed. This requires you to roll your own composition today but this is something people do a lot with CI/CD systems using pretty much any text templating system. 

Examples here include
https://github.com/shyiko/kubetpl
or for more sophisticated use
https://ksonnet.io

This is an area of investigation in Istio to see if we want to bake some capability like this into the product but it will take a while to settle on a solution and it may be that doing this work with Git + CI/CD + file composition is a better overall approach

**Comment by jshaw86** [comment]
> One option that we recommend is to use some form out out-of-band composition of these files into a single VirtualService resource which is then pushed. This requires you to roll your own composition today but this is something people do a lot with CI/CD systems using pretty much any text templating system.

@louiscryan this is not acceptable, and a clear regression of virtual services from the ingress resources that existed in 0.6. What is the complication of just supporting what was supported in 0.6? Doing this kind of post processing especially in dynamic systems causes a ton of edge cases for the post processor specifically around the removal and updating of routes.

This should be fixed ASAP, to be in parity with the way it worked in 0.6. 

@ZackButcher ^^

**Comment by louiscryan** [comment]
@jshaw86 

There are some conflicting concerns here that make arbitrary merging problematic. The first is the ordering of matches. If we tried to merge two VirtualServices for the same host we need an absolute ordering of matches otherwise we have non deterministic behavior which wouldn't be OK.

In a shorthand example

"for host * match query param a=b and route to X"
"for host * match path /hello and route to Y"

We can't infer a safe ordering for these matches, it would need to be explicit. This is a major reason why we moved away from merging and revised the API which was alpha in 0.6. (Aside this issue also plagues the K8S Ingress API which continues to support merging)

Even if the matches were constrained to path segments and not other properties of the traffic you can still have ordering issues when merging.

Another concern here is the use of '*' as the host in your examples. Its pretty unusual to define application specific routes on such a permissive domain match. Typically what we expect to see is a very specific domain coupled with specific routes like this. In the common case the host and associated VirtualService are fairly tightly coupled in terms of lifecycle and so having a single unit of edit is a reasonable option

I'd like to understand a bit better your use-cases around declaring host names and relationships to declaring VirtualServices for them. In particular:

- is this for internal routing or ingress use-cases
- how many real host names do you have, both internal and ingress
- how many routes are there typically per host name
- is the owner of the host name also the owner of the routes. Is this equally true for ingress and internal

One reason I ask about the distinction between ingress and internal if it's fairly common to have a large monolithic virtual host at the edge which routes to many services internally. They are sometimes partially wildcarded but they're still pretty restricted to a sub-domain. The fact that this virtual host is shared among many teams requires a shared authoring model (argument for distinct units of edit) but it's also extremely sensitive and needs to be validated (argument for single unit of edit and validation).

Happy to keep working through this but I want to make sure we really understand the requirements before committing to adding complexity to the API.

**Comment by jshaw86** [comment]
@louiscryan thanks for your response! I've provided a relatively contrived but as simple example as I can provide to help with context below. 

Just a couple of comments before I describe the scenario:
1. The host * is not part of our specific requirements.
2. Order is not a concern because we're not submitting nested routes.
3. If the user is going to submit nested routes where absolute ordering is necessary then that's up to them to do that properly not the opinion of Istio because envoy supports this behavior.

The scenario is you have **serviceA** and **serviceB** each belong behind a single subdomain **subdomain1** and are routed to unique input channels. The input channels cannot be added to the host because they would violate [RFC-1035]( https://tools.ietf.org/html/rfc1035#section-2.3.4) size limits as we don't have control over what they are.

`
---
- apiVersion: networking.istio.io/v1alpha3
  kind: VirtualService
  metadata:
     ...
    name: serviceA
    ...
  spec:
    gateways:
    - istio-gateway
    hosts:
    - subdomain1.some.host.com 
    http:
    - match:
      - uri:
          exact: /run/before/input-channel-6351547589003002
      - uri:
          exact: /ping/run/before/input-channel-6351547589003002
      route:
      - destination:
          host: serviceA.common-ns.svc.cluster.local
          port:
            number: 8080
---
- apiVersion: networking.istio.io/v1alpha3
  kind: VirtualService
  metadata:
    ...
    name: serviceB
    ...
  spec:
    gateways:
    - istio-gateway
    hosts:
    - subdomain1.some.host.com 
    http:
    - match:
      - uri:
          exact: /run/before/input-channel-5361011480850776
      - uri:
          exact: /ping/run/before/input-channel-5361011480850776
      route:
      - destination:
          host: serviceB.common-ns.svc.cluster.local
          port:
            number: 8080
`

I would constrain scope here, leverage reasonable assumptions to get the job done. We're/were EEP so I'm happy to come to MV or SF office and work with ya'll.

**Comment by parasyte** [comment]
> Even if the matches were constrained to path segments and not other properties of the traffic you can still have ordering issues when merging.

Really? Does that mean merging the following examples would be nondeterministic?

* `for host example.com match path /hello and route to X`
* `for host example.com match path /world and route to Y`

**Comment by louiscryan** [comment]
Sorry I should be more precise and say prefix rather than segment, but there is still an issue. Using regex syntax to make the issue clearer ...

for host example.com match path /h.* and route to X       # a strict textual prefix match
for host example.com match path /hello/.* and route to Y # a segmented path prefix match

You can adopt longest-prefix wins  but then the author of the first rule is confused when they get no traffic even if their rule was put in the system first.

With distinct resources it's hard to validate as a single logical resource. These rules combined make no sense but independently they're fine. If you wanted to reject the creation of one based on the existence of the other you could but that also creates an ordering problem for the editors

**Comment by parasyte** [comment]
I understand the concern, but this argument is a clear strawman. The possibility of ambiguities is problematic, I will concede that.

The problem we are facing is not with ambiguous matches. We are currently blocked because Istio does not support merging routes *at all*. Give us enough rope to hang ourselves. That's all I'm asking.

**Comment by rshriram** [comment]
@jshaw86 / @parasyte etc.. would supporting the following semantic (and ONLY THE FOLLOWING semantic) help:

1. If two virtual services have the same host (literal string for string comparison), 
    newVirtualService.HTTPRoutes = concat(v1.httproutes, v2.httproutes)
    newVirtualService.TCPRoutes = concat(v1.tcproutes, v2.tcproutes)
   where v1 and v2 are determined by creation timestamp (i.e. oldest resource is first, the other is second). If you have conflicting routes in v1 and v2, we won't make any attempt to merge them.

 2. if you have three virtual services, v1 for `*.com`, v2 for `*.com` and v3 for `*.foo.com`, then when setting up routes for baz.foo.com, we use v2, while when setting up routes for example.com, we use the concatenation of v1+v2 (as defined in 1)

This is pretty doable. In fact, we could do the same for DestinationRules as well, where subsets from different rules could be merged together. 

Doing any form of path/prefix merging requires more thought as it has larger ramifications.

**Comment by parasyte** [comment]
@rshriram :+1: That sounds reasonable to me. We are already disambiguating paths, just need the capability to share a single gateway. (Which seems best served by multiple VirtualService resources.)

**Comment by amishra1982** [comment]
@rshriram Sounds better. but what does the following really mean "while when setting up routes for example.com, we use the concatenation of v1+v2 (as defined in 1)"

If V1 has URI match of /U1, routing to serviceA  and V2 has URI match of /U2, routing to serviceB then ... when example.com/U1 is invoked, serviceA will get the request. If example.com/U2 is invoked serviceB is invoked.

Also, is gateway set to * in all the scenarios that you mentioned above. If possible, sample gateway and V1, V2 in your example would help me confirm that this is helpful.

**Comment by nrjpoddar** [comment]
@amishra1982, @parasyte would be great to hear your feedback if [VirtualService delegation](https://goo.gl/jSZTjW) proposal solves this issue.

Having one VirtualService resource to look at for a named hostname and conditionally delegate to other VirtualService resources (which inherit the hostname from parent) gives you the isolation and flexibility operators want.

**Comment by jshaw86** [comment]
@nrjpoddar if i understand the proposal correctly, if you want to "merge" VS resources you have to explicitly delegate from a parent resource instead of a more convention based approach that @louiscryan laid out in #7793?

**Comment by nrjpoddar** [comment]
Yes at a high level that makes sense. Being able to delegate provides ownership and control where you still have one place to go to if you want to know about routes affecting a hostname. You can follow the graph if that resource delegates to other resources but it is easy to grok what's happening in the system.

In the approach mentioned in https://github.com/istio/istio/issues/7793, you will have to mentally merge all the resources for the host (i.e. build a tool or do it manually) every time you change any of these resources as there's no priority or ordering among these resources.

Both the approaches give you the feature you want but have tradeoffs around usability, manageability and adding RBAC for configuring your mesh.

**Comment by nrjpoddar** [comment]
@amishra1982 you only to have to update the "root" resource if have added a new service which needs routing based on path matches for the same host. The routes for the delegated service are in the child VirtualService resource which the service owners can manage. You get different files which you want, the framework does the merge but the users intent in captured in the config via delegation.

@jshaw86 we had issues when debugging different VirtualService resources with no precedence but purely convention based merging. I can see that for your case convention based merging simplifies the configuration as the routes are rather simple.

**Comment by parasyte** [comment]
@nrjpoddar That's right. It was designed for simplicity on purpose. 😄

**Comment by amishra1982** [comment]
@nrjpoddar Well, I do not agree to the path of having to change files as services get installed. if that were the case, would just update the virtual service to include all needed URIs. My opinion is to give more thought and treat multiple files as pure conf files which can be merged.
