### ISSUE TITLE
Re-enable TestValidatorToRememberValidation

### ISSUE THREAD

**Issue by JimmyCYJ** [istio/istio#7696]
**Describe the bug**
[TestValidatorToRememberValidation](https://github.com/istio/istio/blob/master/mixer/pkg/runtime/config/validator/validator_test.go#L292) is skipped, and there is no explanation or issue attached. File this issue to keep track.

cc: @mandarjog @douglas-reid

**Comment by smawson** [comment]
Kuat can you try enabling this again and seeing if it is still flaky?

**Comment by smawson** [comment]
Mandar giving this to you, why was this test submitted disabled?

**Comment by mandarjog** [comment]
@ozevren This issue is of stateful validation, referential integrity. 

If a yaml file submits "A, B and C" subdocuments where C depends on B and B depends on A. In that case the validator should remember what it has recently validated because the next validation call based on previous can come in *before* the previous doc is fully committed to the API server.
We decided that this was not needed at the time, so disabled test.


Are we supporting referential integrity ? I am closing this issue. @ozevren please re-open it if this needs to be there.

**Comment by ozevren** [comment]
No, there is no support for referential integrity. Should we keep the bug open to remove the test then?
