### ISSUE TITLE
VirtualServices should support fault injection, timeout, etc for HTTPS traffic

### ISSUE THREAD

**Issue by blaketastic2** [istio/istio#7752]
We'd like a way to set timeouts, inject fault, etc. on HTTPS traffic. Currently, TlsRoute doesn’t support the behavior that's experienced going through HTTP traffic with HttpRoute object

**Comment by ZackButcher** [comment]
To add some context, today Istio is implemented to handle HTTPS just like TCP. We cannot implement these features for TCP traffic in general since we have no way of knowing what any given packet in the stream means.

However, I think we do have enough information for HTTPS traffic to support a subset of fault injection (just delays, we can't return specific response codes in an HTTPS stream), and automatic timeouts for responses. @rshriram thoughts here, and do we actually have the information to do this kind of stuff for HTTPS traffic?

**Comment by rshriram** [comment]
https://istio.io/docs/reference/config/istio.networking.v1alpha3/#ConnectionPoolSettings-TCPSettings supports timeouts for TCP.

**Comment by rshriram** [comment]
fault injection is a todo

**Comment by kyessenov** [comment]
@blaketastic2 what properties of HTTPS traffic are you interested in? Anything beyond source/dst IPs and maybe SNI?

**Comment by blaketastic2** [comment]
I think the original intent of this request was to give us the ability to inject some timeout/delay/fault on external service integrations. Right now(as far as I'm aware), I can't simulate the external service being slow if that service is HTTPS.

**Comment by shovelend** [comment]
Is there any news on this matter? We'd like to play around with fault injection on HTTPS traffic as well to test circuit breaking. Could you please give us an update?
