### ISSUE TITLE
Allow secure naming to have more explicit constraints on identity

### ISSUE THREAD

**Issue by louiscryan** [istio/istio#7756]
@wattli @rshriram @costinm

Today the list of identities that envoy validates when connecting to a downstream cluster is generated by Pilot inferring from the endpoints of the workloads mapped into the service. This mechanism is somewhat circular in nature and makes some sweeping assumptions about how securely endpoints are added to a service by a service registry.

This policy is pretty liberal and the scoping rules may need to be locked down further.

In Kubernetes a Service resource can have spoofed endpoints injected into it if the attacker is able to compromise a K8S namespace. If namespaces are fairly open this attack is not unrealistic. Some of this is mitigated by recommending Service definitions to use label selectors that select endpoints from only a single deployment (and by implication from a single service account). While labels may be a sufficient mechanism technically, we should investigate whether it is also usable. 

An alternative approach would be to have some declaration on a service that constrains the identities for the endpoints which can be bound to the service. Such a constraint is important for the ServiceEntry API which is not coupled to the K8S deployment topology and this is likely to be important for other service registry integrations into Pilot

**Comment by wattli** [comment]
@louiscryan , i think this is an interesting idea. Let me make sure I understand the suggestion: are we suggesting to provide this alternative approach as an improvement, and if customers declare this access control explicitly, we should follow it otherwise we will fall back to what we have now (i.e., secure naming by inferring)? 

And I am not sure the UX change, does this mean customers need to manually declare the expected service account for every service or it's just for a limited number of them. I would have less concern if it is the latter.
