### ISSUE TITLE
ingress error in shared cluster

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#777]
W0913 05:50:45.201] E0913 05:50:45.199935     892 framework.go:197] Failed to complete Init. Error unable to find ingress ip

happens sporadically (probably related to a test finishing when one is starting)

e.g.
https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_istio/739/e2e-suite-rbac-auth/524/

**Comment by andraxylia** [comment]
We need to see if this is still an issue after the rbac changes. @myidpt is the right person to look at it, last time we saw the issue was because certifs were not available.

**Comment by myidpt** [comment]
I have the experience of waiting long for the ingress service to get an external IP. So I suspect this is just because the delay of K8s external IP provision. It seem to me the cert volume mount is unrelated, because the volume mount could fail the ingress deployment, but not the ingress service.

Should we try to increase the retries?
https://github.com/istio/istio/blob/master/tests/e2e/util/kubeUtils.go#L123

**Comment by ldemailly** [comment]
increasing retries doesn't help; it always fail when it fails, it waits 4 minutes or so already

I'm pretty sure we are causing the failure indirectly, we do need to dump more information while we wait or when we fail (use mandar's debug functions)

**Comment by andraxylia** [comment]
@myidpt you are right, it is not related to certs.

**Comment by ldemailly** [comment]
I'm pretty sure it's not GKE but us leaking resources or doing something wrong, we should have a smoking gun before we think it must be GKE; it's not a good philosophy to assume one's code is perfect and bugs must be elsewhere (even though that may end up being the case rarely)

**Comment by xiaolanz** [comment]
any progress on this bug?

**Comment by ldemailly** [comment]
I'm not looking at it, I'm writing some basic test that are somewhat related but not specifically looking at this. I think oncall or someone else familiar with ingress should

**Comment by xiaolanz** [comment]
I didn't see any recent errors on this. close it for now. Reopen when new incident is found.

**Comment by ldemailly** [comment]
it's back (see a bunch of failing PRs https://prow.istio.io/?job=e2e-suite-rbac-auth since about 6pm)

cc @andraxylia who has most affected PRs 

might need an ingress cleanup (and find the source of the leak ?)

**Comment by sakshigoel12** [comment]
@andraxylia can you give an update here?

**Comment by andraxylia** [comment]
This is some issue with the cluster, prod-eng should follow up on this. Changed the priority, it does happen periodically, but it's not blocking the release.

**Comment by ldemailly** [comment]
it was blocking the release but thankfully someone either cleaned up or increased the quotas

we need to get to the bottom of the issue though or it'll keep coming back

**Comment by guptasu** [comment]
@sebastienvas can you please help triage this and have someone look into this. We want a clean oncall bug list. This one has been hanging for some time.

**Comment by sebastienvas** [comment]
I don't think we want to remove it from the oncall, we should leave it such that the next oncall does not create a duplicate. There is a issue file for GKE to fix this. I don't think there is anything else we can do.

**Comment by andraxylia** [comment]
Clarification if issues are followed up by the original person oncall, or handed over to the next person is missing from the oncall duties.

In any case, we should not change the oncall label, maybe just re-assign if it is handover.

As for this issue, we got to the bottom of it, it is a bug out of our control. We can work around it by changing our scripts to delete any LoadBalancer type service before deleting the cluster. Even better, we can pre-allocate the external IPs , add them to a pool, and assign them programmatically in test. This will speed up execution as well, it take about 40s to get an external IP.

So this issue is now triaged, I will remove the oncall label.

**Comment by ayj** [comment]
@sebastienvas @andraxylia - can we close this one? It hasn't seen any real activity in 5+ months.
