### ISSUE TITLE
Standardize on envoy node name format and use it as the primary identifier

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#7783]
At present the envoy `--service-node` name is generated by proxy agent using values of `POD_NAME, POD_NAMESPACE` passed using k8s downward API.

`sidecar~10.60.7.11~myapp-84fcdcbcf9-dj7qn.default~default.svc.cluster.local`

Mixer filter  sends `source.workload.uid` and `destination.workload.uid` to Mixer during every call.
These values are computed by pilot (mixer plugin) and placed in the mixer filter config. Since these `uid` values are different for every sidecard that is requesting config from pilot, every piece of config produced for `http_connection_manager` is different and not cacheable.

If Mixer filter uses envoy `node_id` as the `uid`, pilot does not need to configure it in per filter config.  The resulting config will be same in that case (except for source aware routing.)

-  Standardize on the new node id format   (remove ip address from it)
-  Mixer client uses `node-id`
-  Pilot also switches to using the presented workload ID.
- Ensure that pilot / mixer client continue to accept the current node id format.

The fully qualified name of a workload is  `pod-name . pod-namespace  . cluster`
In multi cluster scenario cluster is important, in single cluster it is ignore.

Generally the fully name should contain name and registry `<some name>@<some registry>`

**Comment by mandarjog** [comment]
@louiscryan @costinm

**Comment by kyessenov** [comment]
Correction: UID is of the form `kubernetes://redis-master-2353460263-1ecey.my-namespace`

**Comment by kyessenov** [comment]
In the interest of time, we should push the logic into mixer to decode the node ID attribute. Envoy should switch from `destination.uid` and `source.uid` to using `envoy.node.id` attribute (which should be always sent), and Mixer can restore the attribute using the direction attribute. I also suggest to drop `destination.namespace` and `source.namespace` and restore that on Mixer. This restoration should happen prior to APAs since config resolution requires namespace.

**Comment by rosenhouse** [comment]
For Cloud Foundry integration, we want endpoint identity to be authenticated.

We imagine this info being encoded in the client-cert which Envoy uses when connecting to Pilot/Mixer.  If client-cert is present, Pilot/Mixer would validate that the endpoint id presented in the XDS request matches what's present in the client cert.

Thoughts?

cc @shalako @sreetummidi

**Comment by shalako** [comment]
@rosenhouse Looking at the OP above, by `endpoint id` do you mean the proposed `node id`? This is the identity of the sidecar? 

How would this work for gateways, which should also only receive a subset of config? Gateways are a little different from sidecars because, while all instances of a group of gateways should receive the same config, just as all sidecars of the same app should receive the same config, sidecars must be uniquely identified to prevent misrouting on ingress, and gateways are disposable. I suppose it can't hurt to have all gateways uniquely identified also.

**Comment by rosenhouse** [comment]
Yes, I mean `node id` here, and yes this is the identity of the sidecar (and by extension, the pod / workload it is proxying for).  `node` here is not a K8s "node" but instead the network node in the mesh, effectively a unique workload id, like a "container id" in CF Diego.

You're right that there's less a risk for the edge gateways maliciously requesting incorrect config.  But there is an attack where a malicious workload with access to Pilot could impersonate an edge gateway by acting as an XDS client with a forged ID, and thereby discover information about routes and backend clusters belonging to other tenants.  Requiring all clients of Pilot to provide client-certs with metadata matching their claimed node id would prevent this.
