### ISSUE TITLE
integration test for "sourceLabels are checked against a Service, not the Pod as documented"

### ISSUE THREAD

**Issue by esnible** [istio/istio#7787]
The documentation four sourceLabels says they apply to "workloads" but the example at https://istio.io/docs/reference/config/istio.networking.v1alpha3/#HTTPFaultInjection-Delay says they apply to *pod* labels.

To reproduce, I first deployed Bookinfo and the example VirtualService at https://istio.io/docs/reference/config/istio.networking.v1alpha3/#HTTPFaultInjection-Delay .

```
$ kubectl exec -it productpage-v1-f8c8fb8-ttlld -c istio-proxy -- curl localhost:15000/config_dump | grep fixed_delay
$ kubectl label pod productpage-v1-f8c8fb8-ttlld env=prod
pod/productpage-v1-f8c8fb8-ttlld labeled
$ kubectl exec -it productpage-v1-f8c8fb8-ttlld -c istio-proxy -- curl localhost:15000/config_dump | grep fixed_delay
$ kubectl label service productpage env=prod
service/productpage labeled
$ kubectl exec -it productpage-v1-f8c8fb8-ttlld -c istio-proxy -- curl localhost:15000/config_dump | grep fixed_delay
             "fixed_delay": "5.000s"
```

I expected the delay to appear after I labeled the *pod*, not the *service*.

Once the sourceLabels have matched the VirtualService may stick around even if they no longer match:

```
$ kubectl label service productpage env-
service/productpage labeled
$ kubectl label pod productpage-v1-f8c8fb8-ttlld env-
pod/productpage-v1-f8c8fb8-ttlld labeled
kubectl exec -it productpage-v1-f8c8fb8-ttlld -c istio-proxy -- curl localhost:15000/config_dump | grep fixed_delay
             "fixed_delay": "5.000s"
```

I discovered this by noticing the sourceLabels were not respected for pods started with `kubectl run`.

I did not see any integration tests using sourceLabels.

**Comment by esnible** [comment]
One more thing about the behavior sticking after the labels have been removed.  After running the above commands to remove the labels from the pod and service the `istioctl proxy-status productpage-v1-f8c8fb8-ttlld.default` shows a difference between the routes, not the expected "Routes Match" final output.

**Comment by andraxylia** [comment]
This is strange. Pilot implementation computes the labels to match against from the pod labels:
https://github.com/istio/istio/blob/master/pilot/pkg/serviceregistry/kube/controller.go#L469

Can you confirm by doing an envoy config_dump, rather than by observing the behavior?

**Comment by esnible** [comment]
The description above shows Envoy co fig dump confirmation.

**Comment by andraxylia** [comment]
thanks @esnible I had missed it.

**Comment by rshriram** [comment]
Can you repeat the experiment by adding the pod labels alone and waiting for sometime? Alternatively add labels to the deployment. I suspect that you are seeing the labels kicking in with a delay. 

Also, its unclear how things work when you launch a pod by hand in an deployment (bookinfo uses deployments).

I went through the code cursorily, and GetProxyServiceInstances (which returns the pod labels) is fetching the pod labels only. So, there is definitely some staleness issue here.

**Comment by andraxylia** [comment]
If we implement #8318 this will not longer be an issue.

**Comment by jotak** [comment]
Hi,
I posted a topic on istio-users ( https://groups.google.com/forum/#!topic/istio-users/8MEXiwGfhqw ) that seems to me related to this ticket, but I'm not sure... Could you confirm if it's the same problem?
Thanks

**Comment by esnible** [comment]
@jotak I suspect this is the same issue.  I discovered this defect doing something similar to your istio-user message.

**Comment by jiuchen1986** [comment]
@andraxylia

**Comment by jiuchen1986** [comment]
@andraxylia 
Can you help us on this issue: https://github.com/istio/istio/issues/8595?
It seems that the pilot can't get correct labels, which are used to identify the gateway pods, when the gateway pods are using the host network.
THX.

**Comment by klarose** [comment]
I ran into a similar issue today. I have a worker pod which only consumes services -- it does not expose any. It has a label, say "app: worker".

I want to control its communication with services in the cluster, so I want to apply http routing rules based on its "app: worker" sourceLabel. However, I found that it never matched. 

When I created a bogus service which selected my worker pod, while also having the "app:worker" label, my routing rules started to work. When I deleted it, they stopped working. Creating the service again caused it to start working again.

Now, I thought: is it matching the service's labels, or is it just using the service to "enable" matching? So, I removed the labels from the service. It continued to work.

So, it looks like the service being present is sufficient to cause the source labels of the workload to be matched. This aligns with what @jotak posted, I think.

@jiuchen1986 I'm not sure what this has to do with gateway pods or the host network. I'm not forwarding to an egress gateway here; my policy is applied at the sidecar. Nor am I using the host network -- my pod is using the default container network. I suspect the issue is more fundamental. I suspect that workloads without a matching service either aren't going down the path which maps labels to and from them, or they go down that path but hit an exception which causes them to short-circuit the label evaluation.

**Comment by mitchhh22** [comment]
Experiencing the same issue here... any idea if this is being worked on?

**Comment by fbcbarbosa** [comment]
We have the same issue at production with Istio 1.0.2; we have two services, a worker and a api, and we have them call a third service (let's call it service C). 

C's virtual service has some routing rules like this:

```
...
    - sourceLabels:
        app: my-app-worker
    - sourceLabels:
        app: my-app-api
...
```

We noted that only `my-app-api` matches the rules, while `my-app-worker` does not _until_ we created a bogus service for our worker. Then it started to work.

We'll roll with the bogus service for now.

**Comment by shakti-das** [comment]
Just noticed the same issue in our self-managed k8s environment as well. When the labels were only at `Deployment` label, the pilot logs were showing the related clusters in `ProxyStatus.pilot_eds_no_instances`. After adding labels to the `Service`, the related clusters were immediately removed from `ProxyStatus.pilot_eds_no_instances`.

**Comment by esnible** [comment]
@andraxylia @geeknoid If we don't plan on fixing this for 1.0 and 1.1 should we document the problem in networking/v1alpha3/virtual_service.proto ?  Or hide the fields from the docs?

**Comment by andraxylia** [comment]
The istio/api should be the source of truth, not the code.

The fact we did not get to fix a bug in the implementation does not make it less of a bug.

**Comment by frankbu** [comment]
@esnible Your original scenario, at the top of this issue, seems to be fixed. I can't reproduce it. I'm guessing the problem before had to do with caching, but it's fixed now. The code was always using the pod labels, but I think that what was happening before was that unless the service changed (in any way) it didn't refresh the pod labels. I was going to prove it by changing the line where you add the `env=prod` label to the service:
```
$ kubectl label service productpage env=prod
```
to just add any label, e.g., `foo=bar`:
```
$ kubectl label service productpage foo=bar
```
and confirm it worked because the pod had the right label. But I didn't get that far, since it worked as soon as the label was added to the pod. If I change the pod label to `env=foo`, then it doesn't get the rule, as expected.

So it's all working as designed now. But ... there is another issue that was mentioned in the later comments - labels don't work on pods that don't have at least a dummy service. 

Looking at the code, that makes sense, because the only way it ever knows about a source is if it finds a Service, or Endpoint, for it. It uses the service/endpoint to get to the pod.

So, for this, we'll need to document it clearly or consider fixing it (e.g., create some kind of dummy endpoint for standalone pods). This might be a bigger issue that just using standalone pod labels for source match.

**Comment by esnible** [comment]
This defect going away by itself with 1.1 is great news.

@frankbu Istio has a few gaps when the number of Services for a pod is != 1.  Let's work together to document them.

Before we close this item let's create an e2e test for sourceLabels.  Where should it go, `e2e-simple`?

**Comment by frankbu** [comment]
@esnible, I think adding a test to e2e-simple would be good. I also thought it would be good to add a sourceLabels check in the unittest too.

https://github.com/istio/istio/blob/e4d174a8625e0ce63cc47c65354df619f4047846/pilot/pkg/serviceregistry/kube/controller_test.go#L402

Now that I've looked at this unittest, though, I think it could use a complete rewrite, since what it's currently doing seems like total nonsense.

**Comment by Dan-Coleman** [comment]
I can confirm I am having the same issue when trying to route v1 and v2 of a 'frontend' deployment to v1 and v2 of a backend deployment. I had to create a service for the 'frontend' and this then started working with the sourceLabel routing rules.

**Comment by esnible** [comment]
@andraxylia I noticed that sourceLabels/source_labels on HTTPMatchRequest were marked `$hide_from_docs` two weeks ago.  Are these fields now deprecated?

https://github.com/istio/api/commit/0e77ec00236554f76109f0e917c6a11de3fa97f7#diff-0820bb0406265ba9b9a9e11dcec06601

**Comment by howardjohn** [comment]
@rshriram ^ can you answer this?

**Comment by frankbu** [comment]
My understanding is that sourceLabels is deprecated because it performs poorly. I recently removed all the sourceLabels examples from the doc: https://github.com/istio/istio.io/pull/4953

**Comment by fbcbarbosa** [comment]
Hi, just to be clear, is there a plan to remove support to sourceLabels routing in future istio releases then? And if so, since the Traffic Routing api is marked stable, can I assume it will remain working for at least one year before the first release in which it is marked as deprecated?

We're using it in some services, just wanted to know if we should be checking for alternatives for our use-case.

**Comment by rshriram** [comment]
Yes it will be supported for one or two releases. Not sure about the 1 year thing though. Btw, you can achieve the same effect as source routing by using the Sidecar crd. Can you describe your scenario so that we get an idea of how you are using the source routing?

**Comment by camhine** [comment]
>  Can you describe your scenario so that we get an idea of how you are using the source routing?

Not sure how others are using it but I have a scenario.

We push out a set of deployments under a single version label. The idea is that there is a separate set of deployments for every release. When a new version is released we run smoke tests against the new set of deployments before promoting the new version.

We use sourceLabels to ensure that the deployments in a release talk to other deployments within that release - not another version which may still be running in the mesh. The virtual services end up looking a bit like:

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: my-service
spec:
  hosts:
  - "my-service"
  gateways:
  - gwy
  - mesh
  http:
  - match:
    - sourceLabels:
        version: next-version
    route:
    - destination:
        host: my-service
        subset: next-version
  - route:
    - destination:
        host: my-service
        subset: current-version
```

I've had a look at the sidecar [docs](https://istio.io/docs/reference/config/networking/v1alpha3/sidecar/) but it's not obvious to me how I would achieve a similar thing using it. Is this what you meant by 'Sidecar crd'?

**Comment by frankbu** [comment]
@camhine if you deploy your next-version services in a different namespace than the current-version ones, then you can configure a sidecar in both namespaces to only expose services in the same namespace (e.g., `./*`). This way services in the next-version namespace will only ever call other next-version services.

**Comment by fbcbarbosa** [comment]
@rshriram we're using sourceLabels with a fault abort 100% filter to limit access to certain APIs - which, I imagine, is not really a recommended use case.

I guess we should probably be using [Denials and White/Black Listing](https://istio.io/docs/tasks/policy-enforcement/denial-and-list/). We were making use of routing rules already and it just grew out of that.

**Comment by howardjohn** [comment]
@frankbu I think you can also use the workload selector and keep them in the same namespace. In one, specify `./v1` and in the other `./v2`?

**Comment by frankbu** [comment]
@howardjohn Unless I'm misunderstanding your suggestion, I don't think that works because the service names would have to be different. The problem is that all versions of a service make calls to other services using the same name, regardless of version. Even my suggestion gets a little complicated if all service requests are made using FQDN like `service1.ns.svc.cluster.local` (which we recommend), instead of short just a name `service1`. Although that can be made to work using `VirtualServices` in multiple namespaces for the same actual host, it does get a little complicated.

Unless I'm missing something, I'm starting to wonder if we should reconsider deprecating `sourceLabels`. Is there a serious issue with performance, or other problems, that we really need to avoid?

^^^ @rshriram

**Comment by frankbu** [comment]
Because more people are using it than we had originally thought, we decided not to deprecate `sourceLabels` after all. See https://github.com/istio/api/pull/1108
