### ISSUE TITLE
Support merging of VirtualService resources on the same host

### ISSUE THREAD

**Issue by louiscryan** [istio/istio#7793]
@rshriram @costinm @andraxylia 

The fact that we require VirtualServices to be a monolithic unit of edit is proving problematic for users. Largely because it presents impedance in development workflows and existing CI systems or that were used to producing mergeable Ingress resources.

We adopted a monolithic resource approach as it allowed for total validation of the intent of routing within a context including the ability to validate for obvious conflicts. A single resource also has advantages when managing rollout of changes that could break production as it's a single unit to push through canary and rollback if necessary

If we support a merging protocol similar to the one @ZackButcher previously documented for Ingress 

https://docs.google.com/document/d/1z9jOZ1f4MhC3Fvisduio8IoUqd1_Eqrd3kG65M6n854/edit#heading=h.yiu7n85qkofa

Fundamentally the solution would state
- If you want absolute control over order then use a single resource
- If you use multiple resources then the system will merge them and apply a standard ordering of the form

longest path prefix > longest path suffix > longest path pattern match > age of merged resource (creation timestamp) > default route

This form of merging is pretty typical and gives precedence to URLs as a hierarchical namespace. We use of 'age of merged resource' to give precedence to resources that are already running in production and are more likely to be safe. We put 'default' at the end as it is effectively a match with no condition.

Similarly we can support merging for TCP & TLS resources. TCP has a hierarchy as does the SNI suffix matching in 

Note that while this solution is somewhat orthogonal to the RBAC discussion here 

https://docs.google.com/document/d/17K0Tbp2Hv1RAkpFxVTIYPLQRuceyUnABtt0amd9ZVow/edit

it does overlap as it presents a different approach to the editing model. The solution presented here doesn't suggest a security model though it presumes that one can be layered on top separately

**Comment by louiscryan** [comment]
Linking some related issues here

https://github.com/istio/istio/issues/7674
https://github.com/istio/istio/issues/6486
https://github.com/istio/istio/issues/6070
https://github.com/istio/istio/issues/7776
https://github.com/istio/istio/issues/7529

It's worth noting from these that merging helps with a number of other known issues
- mapping k8s ingress 1-to-1 into VirtualService and then doing the merge. A feature that was dropped in 1.0 and needs to be revived.
- enabling auto-cert provisioning to create a resource to merge that captured the authorization handshake

@ayj it's worth noting that with Pilot implementing merging this has an affect on the validation phase of Galley. Pilot may decide to reject the resource because it can't be merged with the others its aware of. This is particularly important when there is more than one system providing VirtualService resources to Pilot at the same time.

**Comment by rshriram** [comment]
Per discussion on slack, can we start with the simple merging where we simply **concatenate** the http/tcp/tls blocks in a virtual service, while keeping the default route in the end? Looking at all the issues, the simple concatenate and order by time will satisfy all the issues you pointed to above.

Btw, the same should also be applicable for Destination rules as it too is a single unit of edit. No point in using subsets in a separate virtual service but defining the subsets in one global destination rule. So we need to do the same merging there as well. And it does bring about some interesting issues (subsets with same names and different labels, etc.).

**Comment by lucasponce** [comment]
Side question.
In terms of CRD, how this is going to be planned ? Pilot/Galley will manage all the VS generated by the user and create a new synthethic CRD VS with the merge, deleting the previous ones ? The old ones will remain with some flag like "active/non active" ?

I try to figure out the final picture from the third party tooling that manages configuration (i.e. Kiali) and adds additional semantic validation (i.e. a VS defined where no host is located, or similar validations).

**Comment by linsun** [comment]
Another request for this from @nmnellis a while back:  https://github.com/istio/istio/issues/5006

+100 for supporting a simple merge of VS for the same host.  cc @frankbu @ijsnellf @GregHanson @esnible

**Comment by nrjpoddar** [comment]
@louiscryan I think that the functionality requested in this feature (delegation of edit) is a subset of functionality covered in the [VirtualService Delegation](https://docs.google.com/document/d/17K0Tbp2Hv1RAkpFxVTIYPLQRuceyUnABtt0amd9ZVow/edit) proposal. The proposal provides a delegation of edit in a way that RBAC and delegation of permission can be added in future.

I'm not sure how you can add permissions/RBAC (for e.g. separate ownership for Public/Private hostnames) in the solution mentioned here. It feels like this is solving for specific cases rather than a flexible config model for users. In this solution for every hostname a user would have to list all VirtualService resources, then do a mental merge of all VirtualServices sharing the hostnames (as there is no order or priority via config) before adding more routes.

**Comment by andraxylia** [comment]
@lucasponce The merging will likely need to be done in Pilot, not in Galley, otherwise it would mean too much component specific knowledge in Galley.

**Comment by ayj** [comment]
> Pilot may decide to reject the resource because it can't be merged with the others its aware of

The notion of per-resource applied/operational status would be useful here. Resources that were previously _applied_ to configuration maybe later become _un-applied_ due to higher precedence resource. https://github.com/istio/istio/issues/7794 proposes a feedback loop between Pilot and Galley where this operational status (include merge confligs) could be reported.

**Comment by louiscryan** [comment]
@nrjpoddar I've added some comments in that design doc. One of the concerns with the delegation proposal is that by having a single root resource you force a read-modify-write cycle on that resource for the injection of additional behavior into that host. We have a few data points indicating that creates some impedance for users (lets encrypt capture, CI systems, k8s ingress).

These things are not mutually exclusive but we do need to prioritize based on some collective agreement about relative value. Happy to follow up offline or discuss at the next WG meeting

**Comment by lucasponce** [comment]
@andraxylia But the merging is "virtual" I mean. An user would see the original config resources (VS, DR) or those will be gone and at the end the final CRD will be the "composed/merged" resource managed by Pilot ?
Perhaps that's my main doubt.
I'm thinking in scenarios Kiali is managing today:
![image](https://user-images.githubusercontent.com/1662329/44030083-f7948862-9eff-11e8-82e9-0cb78163c66b.png)
Where it will add additional "semantic validation" over the configuration resources.

**Comment by andraxylia** [comment]
@lucasponce the merging is virtual, it is not correct to replace the original resources. It is correct to set the value of the status field - similar to how a Pod status would change to Scheduled, running etc. The doc explains more about the merging.

**Comment by nrjpoddar** [comment]
@louiscryan Thanks for your feedback. With VirtualService delegation I agree there's a read-modify-write cycle only on the "root" resource and only for injecting additional behaviors as your mentioned.

This issue also exists in the convention based merging proposal as you can have scenarios where you would have to update/patch a resource rather than creating new ones which can follow the merge convention and inject additional behaviors.

Would love to chat offline early this week if it works for you.

**Comment by andraxylia** [comment]
@nrjpoddar @louiscryan I would prefer if the approach gets discussed during the networking meeting this Thursday rather than in offline chats.

**Comment by bmarshall13** [comment]
@louiscryan, I assume that CreationTime is a last-resort sort key, just to ensure that pilot always resolves the same config for a given set VirtualServices, and it is not intended to be exploited for any priority resolution. Is that correct?

Also, what does “longest path pattern match” mean? I would assume it means the longest path matched by a regex, but I don’t see how that can be implemented at config merge time.

**Comment by louiscryan** [comment]
@bmarshall13 

Yes, it's there so we can produce a deterministic output, no one should rely on it for real priority.

By "“longest path pattern match” I mean the longest regex specification, not the longest text that could be matched by that. This is clearly a very rough approximation of specificity (and therefore priority) but it may be better than nothing

@nrjpoddar The examples I gave around merging (let encrypt, ingress, CI) don't typically require read-modify-write. They are fully specified by outside systems so they only need write & delete semantics typically.

**Comment by frankbu** [comment]
@louiscryan I'm wondering how well this design works for virtual services with multiple hosts, the use case where the the first host (that should be merged) is an external host bound to a gateway (e.g., `bookinfo.com`) and the second host is the internal service name (e.g., `reviews.default.svc.cluster.local`).

In this case, each virtual service typically serves two purposes:
1. defines the external paths that should route to the service.
2. defines the rules (e.g., version routing) for the service.

Two hosts are used so that when we upgrade a service from version v1 to v2, for example, we don't have to add the new routing rule in two different virtual services (one for `bookinfo.com` and one for `reviews.default.svc.cluster.local`).

If we use a delegation approach, like @nrjpoddar's proposal, we can move the two function into separate virtual services (one host each) and then we can configure the routing rules in the delegate virtual service that applies regardless of whether the request is from an internal or external caller.

With this merging proposal, we have the advantage of not needing to update the root virtual service whenever we add or remove external paths, but on the downside, we need to add `AND path matches` to every route rule in the virtual services.  If you forget one, the rule from some team can suddenly start capturing all traffic that isn't already captured by other path-specific matches in rules that happen to be higher precedence in the merged sort order.

I'm wondering if it might make sense to add a new top level default path match field in a virtual service that is automatically applied to every rule in the service, or something like that? That would certainly make it cleaner. Maybe even requiring something like that before virtual services can be merged?

I'm assuming this is one of, if not the primary use case (separating monolith paths into team-specific virtual services) driving the merging requirement, so I think we should make sure it works well for this case.

**Comment by nrjpoddar** [comment]
@frankbu that's an interesting scenario. In my opinion the proposal here and the VirtualService delegation are both needed and are not exclusive. Convention based merging is great for path prefix matches and as @louiscryan pointed out for systems like let's encrypt, ingress which only require add/delete semantics.

For more complicated merging, delegation makes sense as it assigns a user defined priority and reuse of config via composability. Combining both is really powerful and I think will solve your use case.

**Comment by louiscryan** [comment]
I agree with @nrjpoddar here. Delegation would be within the context of a match expression which naturally implies an AND with the matches in the specification being delegated to. Note that the AND can be elided if the outer condition is a strict subset of the inner one, in the case of paths this works pretty well. E.g. outer path match is '/sales' and delegated match is '/sales/advertising'

**Comment by rshriram** [comment]
why cna't the delegation be done as part of pre-processing? After all, its just a construct to reduce the repeated configuration. ITs not something that influences runtime routing. A galley plugin could read in the virtual services with delegation and spit out the final processed virtual service without delegation. Will simply the code inside pilot as well. And allows for people to turn this on demand rather than doing this for everyone. And with some smarts, we could allow people to define the merge semantics they want, that befits their organization rather than imposing one format for everyone. 

Essentially, the "concatenation" proposed in this issue can be part of the core. Its simply appending multiple rules into one. The delegation, which requires merging can be done as a galley pre-processor plugin, (same as the hostname ownership as well).

**Comment by ZackButcher** [comment]
I agree in principle with Shriram here: there's not one obviously best way to merge VS clauses.vThe general problem is that while HTTP may be "simple" enough (in practice it remains to be seen given we support matching on things like port, gateway, etc), other protocols aren't necessarily. Defining merge semantics per-protocol is going to be a real drag.  In my opinion the right thing for us to do here is develop a simple CLI to iterate on how merging might work, verify with real users that what we want to do solves their pain points. Then we can codify that as part of Pilot's implementation. (And certainly we can define protocol specific merge semantics and for the rest just say "concat them together".)

However, I _do_ think that if we're going to change Pilot to support merging in the short term, we can carve out a subset of HTTP to define reasonable merge behavior that's better than "concat the clauses together" (that's why I wrote the document about VS merging to do just this eight months ago :) ). 

So taking a stab at a "reasonable" merging algorithm, taking in to account the fact that we have matches other than just exact/prefix/regex on the URI, I think the order of merged clauses should be in these groups:

1. Exact URI matches (order doesn't matter, but we'll say longest to shortest)
2. Prefix URI matches, ordered shortest to longest
3. Regex URI matches, in creation timestamp order ("length" is meaningless for regexes, unless we're talking about the maximum length of a string in the language they'll match, and we can't determine that statically)
    > We might want to special case the `.*` regex to the very end
4. Non-URI matches in creation timestamp order (we could also potentially order them by number of predicates, most to fewest)
5. The fallthrough/default route (the oldest default route wins)

Within each of the 1,2,3 blocks (the URI matching blocks), we'll order by number of other predicates in the match to tiebreak when the matches are the same length. When two match conditions have exactly the same number of predicates, we'll put them in creation time stamp order. We do not differentiate between the type of predicate (i.e. we don't say "gateway matches before port matches but after..."). In other words, given three separate VirtualServices like:

```yaml
hosts:
- ratings.prod.svc.cluster.local
http:
- match:
  - headers:
      end-user:
        exact: jason
    uri:
      prefix: "/ratings/v2/"
  route:
  - destination:
      host: a
---
hosts:
- ratings.prod.svc.cluster.local
http:
- match:
  - headers:
      end-user:
        exact: jason
    gateways:
    - "billy"
    uri:
      prefix: "/ratings/v2/"
  route:
  - destination:
      host: b
---
hosts:
- ratings.prod.svc.cluster.local
http:
- match:
    uri:
      prefix: "/ratings/v2/"
  route:
  - destination:
      host: c
```
(note all match on identically the same host and URI prefix) we should produce the merged VirtualService:

```yaml
hosts:
- ratings.prod.svc.cluster.local
http:
- match:
  - headers:
      end-user:
        exact: jason
    gateways:
    - "billy"
    uri:
      prefix: "/ratings/v2/"
  route:
  - destination:
      host: b
- match:
  - headers:
      end-user:
        exact: jason
    uri:
      prefix: "/ratings/v2/"
  route:
  - destination:
      host: a
- match:
    uri:
      prefix: "/ratings/v2/"
  route:
  - destination:
      host: c
```

**Comment by rshriram** [comment]
I am not sure ordering by URIs first and then tie-breaking by other params is the way to go. We have several parameters (ports, gateways, source labels). We are also eliding headers, authorities, methods, schemes. We need to define a natural order of merging across all these parameters (and keep the door open for future match parameters we introduce. For example, some have been asking for source CIDRs in http matches as well).

Why can't we take an alternate approach and define a `mergeKey` field in every match condition? At runtime or in galley, we can sort by the merge key in the match conditions and order them.  The key space can be partitioned across teams (e.g., "global-..", "team1-..."). 

We could even define a new API that defines the composition order for virtual services based on the merge keys (it could be alphabetic by default). I think this is similar to what @frankbu was suggesting earlier. Define a host or path and define the key prefixes - which control the order of concatenation of virtual services. 

We can handle the degenerate case of K8S ingress, lets encrypt etc. by simple time based concatenation and it will work for the most part, because these systems tend to define disjoint resources mostly. The only case we elide is one where k8S ingress users start defining overlapping ingress resources (one defines /acme, and another defines /acmefoo). These people who have complex ingress resources with potentially overlapping routes/paths etc. are likely to be careful and examine the istioctl tool generated virtual service rather than trusting us to auto-merge.

**Comment by bmarshall13** [comment]
If these changes are going to be made in pilot (or any public API), I suggest that any "conflicting" VirtualService resources (or match rules) be ignored. i.e. Keep only the oldest, instead of including all sorted by creating time. 

This would allow the merge ordering to start simple, and become more complex over time, without breaking existing use cases.  Any new merge rules added in future versions will gives clear ordering to previously conflicting (and ignored) resources which can't break an existing functioning config. 

This assumes that if there are conflicts, the user is aware and has removed the conflicts. Ideally this is in VirtualService status, but it can be as simple as a pre-upgrade check. "Remove these VirtualService rules to prevent config changes after the upgrade"

If all rules are included in the live config with simplistic ordering that is made more intelligent during an upgrade, then a set of VirtualServices that are implementing the user intent may break. There may not be a set of VirtualServices in the new version that will satisfy the user goals. (Like what happened from v1alpha1 to v1alpha3).

This might make fewer people happy now, but at least we won't make happy people unhappy in the future.

**Comment by Bessonov** [comment]
> Fundamentally the solution would state
> - If you want absolute control over order then use a single resource

Full ack. Furthermore, I can imagine an attribute like `order`.

> - If you use multiple resources then the system will merge them and apply a standard ordering of the form
>
> longest path prefix > longest path suffix > longest path pattern match > age of merged resource (creation timestamp) > default route

My use case is to routing to different services, which should have own `VirtualService` configuration, but share same `host`. I can split it just by prefix. Therefore, my suggestion for the first step is just to concatenate routes and don't care about ordering (but wildcard). First match wins. For an absolute control everyone can stay with single `VirtualService`.

**Comment by andraxylia** [comment]
This was implemented.
