### ISSUE TITLE
Mixer should remove sensitive attributes in telemetry

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#7814]
Currently, Mixer places no restrictions on which telemetry adapters can access sensitive headers (e.g. `Authorization` or `X-Api-Key`). This poses a risk of a replay attack by anyone having access to the logs.

- We need to insert a processor early in mixer runtime that removes these attributes / attribute values
- We need to allow configuration of what headers to remove (not all authentication headers are standard, some names are custom)
- We need to encourage offloading authentication to the proxy if possible, so that only the decoded authentication info is passed to the authorization adapters

ref https://github.com/istio/proxy/pull/1908
ref https://github.com/istio/proxy/issues/1905

/cc @geeknoid @mandarjog @jboeuf

**Comment by geeknoid** [comment]
Note that adapters can't access attributes directly, the operator has to configure things to deliver the attributes to the adapter.

The solution here is to support a canonical means to edit maps such that the operator can delete request headers that shouldn't be delivered to a specific adapter.

**Comment by kyessenov** [comment]
If I understand it correctly, the following should be a fairly easy contribution:
- add `sanitizer` APA
- config for this APA should be in global scope, and have the following parameters:
  * template variety
  * attribute names or attribute name [ keys ] to delete
-  allow APAs to apply deletes to attribute bags, not just add them

Sounds good?

**Comment by geeknoid** [comment]
A few of us just had a discussion on this:

- We don't need to strip attributes away from the attribute stream. Operators must explicitly configure things to expose specific attributes to specific adapters. We'll want some static verification to catch case where the wrong attribute is used perhaps. This analysis can be done in Galley in the context of its general purpose analysis framework.

- Request headers is what is the real problem here. Different adapters may get request headers and it's not OK for all adapters to get the double-top-secret request header values. To solve this, we could implement a fairly simple APA, combined with a simple change in the proxy:

- Instead of sending the request.headers attribute, have the proxy send the request.fulheaders attribute. Same payload, just a new name.

- Implement a mapeditor APA. It's job is to consume request.fullheaders and produce request.headers. By default, we'd configure the APA to strict the sensitive headers. Existing config consuming request.headers would continue to work and would only be exposed to the safe set of headers.

**Comment by kyessenov** [comment]
Don't you still need to strip `request.fullheaders`? Would that be done in mapeditor APA? I think that sounds similar to what I had in mind.

**Comment by qiwzhang** [comment]
Can the APA just process request.headers directly without proxy creating a new attribute name?

**Comment by geeknoid** [comment]
In the scheme I described, the proxy just produces request.fullheaders. The
APA (in Mixer) ingests this and produces request.headers.

The operator can then use either attribute when passing request headers to
an adapter, but would typically use request.headers only.

This is not about removing any attributes, it is about preventing
accidental disclosure of information. The operator is still free to use
request.fullheaders if desired, it's their choice,

**Comment by kyessenov** [comment]
Not stale I think.
