### ISSUE TITLE
mixer JWT tests are failing

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#7867]
Recent changes to the proxy JWT filter changed how data is passed between filters. It's no longer using a special header. Tests need to be updated to reflect that.

/assign @diemtvu

**Comment by quanjielin** [comment]
below mixer test failure(https://github.com/istio/istio/pull/7791)  ```Origin authentication failed``` comes from authn filter validateJwt fail because of parsing metadata (change made in https://github.com/istio/proxy/commit/afc72d706414feb0f8b684d6f3f70bd33e87fb07)


/mixer/test/client/istio_authn_origin_jwt_bound_peer/authn_report_test.go

/cc @quanjielin

**Comment by qiwzhang** [comment]
@lei-tang I remember you wrote these tests. Could you help to fix them?  Thanks

**Comment by lei-tang** [comment]
@qiwzhang Yes, will do.

**Comment by lei-tang** [comment]
The fix is in https://github.com/istio/istio/pull/8050.
