### ISSUE TITLE
Automatically synchronize between secrets and istio-ingressgateway certs

### ISSUE THREAD

**Issue by dunjut** [istio/istio#7976]
**Is your feature request related to a problem? Please describe.**

Currently istio-ingressgateway only supports tls certificates through volume mount at deploy time. Adding new certificates requires editing and re-deploying the ingress-gateway pod (as discussed in [issue#7658](https://github.com/istio/istio/issues/7658))

**Describe the solution you'd like**

One way to dynamically adding certificates is to make istio-ingressgateway discover secrets from pilot, but this seems not available in a period.

**Describe alternatives you've considered**

Another way is to watch kubernetes secrets with specially annotations and synchronize their cert data into istio-ingressgateway cert path. This has been done by us throuth the [cert-sync](https://github.com/dunjut/cert-sync) tool (a very early version though).

**Additional context**

Either way, we'd like to stick with the community and do not go far away on our own path. So we are thinking that, if it's possible, would the community adopt and help improve cert-sync as an official solution before a better one comes out?

**Comment by incfly** [comment]
Thanks for explaining how `cert-sync` tool works. Here's my thoughts and understanding:

**Cert Sync**
It basically makes ingress gateway able to watch the resources and secrets (representing user provided tls key cerst). And add that to specific path (based on the rule pattern), since it's shared with Envoy ingress container's volume.

We are in process of using new Envoy SDS API to provision key and cert. A DameonSet called Node agent will run on every node, acting as SDS Server to respond with key and cert.

Given that, I think we can instead let the node agent to watch secrets and push it back to Envoy. And Pilot needs some updates to push relevant SDS config to ingress Enovy based on Gateway CRD.

This will entails a bit of additional work, but I think it unifies the certificate provision story better.
/cc @costinm to comment.

**Comment by dunjut** [comment]
@incfly Thanks for sharing the plan.

Is there a link we can see the design doc? What time can we expect to test new provision API?

**Comment by dunjut** [comment]
ping @incfly @costinm 

Any updates?

**Comment by costinm** [comment]
I think using something like cert-sync is very reasonable - however I think
it's a bit too complex.
We could simply watch the secrets from pilot-agent ( or some other binary
that ships with ingress).
Probably best option would be to create a separate binary - for example
k8s-pilot-agent. We did have
k8s-specific code in agent before, and it would simplify a lot of other
problems, no need to watch the files
in the shared file system.

Node agent and sds serve slightly different purpose - they create
short-lived certificates for service-to-service.

This will also make the integration with ACME certs easier, and simplify
the management of ingress.

If someone can contribute this - either starting from cert-sync, or from
the existing code in pilot for watching
secrets (used by multi-cluster) - it's a feature we may even merge into 1.0
branch, since it solves a major usability
problem for ingress.

**Comment by myidpt** [comment]
@costinm I lean toward using the security node agent for this purpose. The security node agent already implements the SDS API, and it is planned to support retrieving cert from:
1. Citadel
2. k8s secret
3. ACME, Let's Encrypt
4. other CAs via custom adaptors

Given what the security node agent does, reusing it for all cert provisioning purpose can reduce the security components, so it makes more sense. The security node agent runs as daemon set, vs. cert-sync runs as a binary in pod. They can be deployed automatically as part of the control plane, so we won't have regression in UX.

**Comment by myidpt** [comment]
https://docs.google.com/document/d/1agtVQADCk32mLwot8iygVGhHcP1Lna7G1Cne4Zwllgg/edit#heading=h.qex63c29z2to

**Comment by incfly** [comment]
This is outdated right? Any other bug number to replace? @myidpt

**Comment by myidpt** [comment]
Actually we are using this one to track. We should link related PRs to this issue :)
