### ISSUE TITLE
helm: missing CRDs for dogstatds and cloudwatch

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#8003]
Helm install is missing CRDs for two mixer adapters.

**Comment by douglas-reid** [comment]
This indicates to me that we probably should consider a better way for controlling inventory and requested adapter CRDs.

If I have no intention of using dogstatsd and cloudwatch, why would I want CRDs in my cluster for them?

At the very least, we need to consolidate down to ~3 CRDs, instead of having one per adapter.
