### ISSUE TITLE
Sidecar proxy adds 6 seconds to Pod startup 

### ISSUE THREAD

**Issue by tcnghia** [istio/istio#8131]
**Describe the feature request**
When a Pod with HTTPGet ReadinessProbe get injected with sidecar, the time to reach Readiness increases by 5-6 seconds.

**Describe alternatives you've considered**
Removing the ReadinessProbe, but that transfers the problem to user requests.

**Additional context**
- This 6 seconds doesn't include the additional time of the Init container.
- In the log we notice that there may be some `sleep(5s)` involved in this delay.  See https://github.com/knative/serving/issues/1345 for more information.

**Comment by sdake** [comment]
cc @PiotrSikora 

Please take a look at https://github.com/knative/serving/issues/1297#issuecomment-401058968 - there is a 5 second sleep during Envoy's startup.  The knative project use case is to spin up pods and kills them off dynamically depending on load.  During a spinup under load, unhealthy upstream often occurs (in my testing), however, I did notice it takes some time for the knative application pods (like helloworld) to start up on which should otherwise be a very fast pod start.

**Comment by tcnghia** [comment]
This was in 0.8.0.  I have not investigated this issue 1.0.x yet.

**Comment by PiotrSikora** [comment]
1. Are you also using Pilot or only Istio Proxy?
2. How many listeners / clusters are the proxies configured for?
3. A lot of startup issues were fixed in 1.0.0 and 1.0.1, so please test with the latest version, since you're unlikely to get any help for 0.8.
4. I recall `GrpcMuxImpl::establishNewStream()` retry timeout being fixed in Envoy, but I cannot find any PRs for it now.

**Comment by tcnghia** [comment]
@PiotrSikora I retried with 1.0.0 and it seems only take 1-2 seconds from the container starting to pass readiness check.  So this issue is fixed for 1.0.0.
