### ISSUE TITLE
Jaeger doesn't record the full call chain

### ISSUE THREAD

**Issue by chanjarster** [istio/istio#8155]
**Describe the bug**
Jaeger doesn't record the full call chain

I used [emojivoto][1] demo app( [yaml file][3] ) to see how istio tracing works. I found that jaeger can't record all spans in trace record.

According to below figure, the trace should have at least 3 spans: **vote-bot -> web-svc -> voting-svc**, but I only got 2 spans: **vote-bot -> web-svc**.

![Emojivoto Topology][2]

[1]: https://github.com/BuoyantIO/emojivoto
[2]: https://github.com/BuoyantIO/emojivoto/raw/master/assets/emojivoto-topology.png
[3]: https://github.com/BuoyantIO/emojivoto/blob/master/emojivoto.yml

**Expected behavior**

Jaeger can record full call chain.

**Steps to reproduce the bug**

1. download [emojivoto.yaml][3]
1. modify yaml file add `istio-injection: enabled` to `emojivoto` namespace.
1. `kubectl apply -f emojivoto.yaml`
1. Wait a few minutes
1. Open Jaeger to see traces.

**Version**

```
$ istioctl version
Version: 1.0.0
GitRevision: 3a136c90ec5e308f236e0d7ebb5c4c5e405217f4
User: root@71a9470ea93c
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean

$ kubectl version --short
Client Version: v1.11.2
Server Version: v1.11.1
```

**Is Istio Auth enabled  or not?**

```
helm install install/kubernetes/helm/istio --name istio --namespace istio-system \
  --set gateways.istio-ingressgateway.type=NodePort \
  --set gateways.istio-egressgateway.type=NodePort \
  --set tracing.enabled=true \
  --set servicegraph.enabled=true \
  --set grafana.enabled=true
```

**Environment**

On-premise OpenStack

**Cluster state**

 Too big(5g), not uploaded

**Comment by chanjarster** [comment]
Hi, @douglas-reid . 

How can I confirm that whether pod forward trace headers or not?

**Comment by douglas-reid** [comment]
@chanjarster you will need to look at the source code. a cursory look at the repo didn't return any results when I tried searching for "trace" and "b3" and other related terms and glancing at the source for the `web-svc` didn't show any special trace handling.

Distributed tracing is one of the few things that requires app-level support. Headers must be forwarded from the app for every outgoing call for it to work properly. Please see: https://istio.io/docs/tasks/telemetry/distributed-tracing/#understanding-what-happened for a discussion of this requirement.

I'm going to close this issue for now, as I believe this isn't an Istio issue. Please feel free to reopen if you feel otherwise (for example if emojivoto is indeed propagating trace context, etc.).

**Comment by chanjarster** [comment]
@douglas-reid Thanks for explanation.
