### ISSUE TITLE
When tagging a release, don't have daily release build in helm

### ISSUE THREAD

**Issue by k** [istio/istio#8203]
**Describe the bug**
{{ Succinctly describe the bug }}
When uninstalling and reinstalling the chart, my grafana pod stopped being able to start because the new image was throwing a db migration error.

**Expected behavior**
{{ What did you expect to happen? }}
When reinstalling the chart, it would still work.

**Steps to reproduce the bug**
{{ Minimal steps to reproduce the behavior }}
Install the istio chart using branch release-1.0

**Version**
{{ What version of Istio and Kubernetes are you using? Use `istioctl version` and `kubectl version` }}

Not using istioctl, used helm install on branch release-1.0.

```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.6", GitCommit:"a21fdbd78dde8f5447f5f6c331f7eb6f80bd684e", GitTreeState:"clean", BuildDate:"2018-07-26T10:04:08Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Is Istio Auth enabled or not?**
{{ Did you install the stable istio.yaml, istio-auth.yaml.... or if using the Helm chart please provide full command line input }}
no

**Environment**
{{ Which environment, cloud vendor, OS, etc are you using? }}
aws

I believe that when making a release, the helm chart should be tagged with the appropriate image instead of the daily release build:

https://github.com/istio/istio/blob/1.0.0/install/kubernetes/helm/istio/values.yaml#L9

should instead be `1.0.0`

Thoughts?

**Comment by ymesika** [comment]
Agreed. The `1.0.0` tagged version of this file should point to `1.0.0`.
The `release-1.0-latest-daily` value picks up the latest 1.0.x build which isn't desired when working with the `1.0.0` tagged branch or the downloaded released source code.

cc @hklai

**Comment by hklai** [comment]
All daily releases should have the correct tag in values.yaml.

I verified the tar balls in https://gcsweb.istio.io/gcs/istio-prerelease/daily-build/release-1.0-20180823-09-15/gcr.io/ and found the right tag in install/kubernetes/helm/istio/values.yaml.

**tag: release-1.0-20180823-09-15**

Similarly, LTS releases should have the LTS version tag. The values.yaml in the tar balls on https://github.com/istio/istio/releases/tag/1.0.0 have the following correctly.

**tag: 1.0.0**


On the other hand, **tag: release-1.0-latest-daily** in https://github.com/istio/istio/blob/1.0.0/install/kubernetes/helm/istio/values.yaml#L9 is expected, as it is a floating tag which points to the latest daily build. It is meant for developers who tries to install from the source directly, instead of using any release artifacts. In that case, the latest daily release will be used instead.

**Comment by ymesika** [comment]
@hklai Sounds reasonable but I downloaded https://github.com/istio/istio/archive/1.0.0.zip and it has **tag: release-1.0-latest-daily**.

**Comment by hklai** [comment]
https://github.com/istio/istio/archive/1.0.0.zip is a source code archive, so its values.yaml has the original tag value.

On the other hand, the release artifacts (i.e. istio-1.0.0-linux.tar.gz, istio-1.0.0-osx.tar.gz, and istio-1.0.0-win.zip) should have the right tag 1.0.0.

**Comment by k** [comment]
Okay thanks for the info @hklai, so it sounds like if I want the source for a specific tag or date I should download the release artifiacts from the releases tab or find it in that gcsweb online directory

**Comment by hklai** [comment]
@k Correct.

I am closing this as I think this has been resolved. Feel free to reopen if you see more issue.
