### ISSUE TITLE
perf: Tracing (Jaeger) optimization

### ISSUE THREAD

**Issue by jnativio** [istio/istio#8275]
**Describe the feature request**
Reduce the cost of the Istio Tracing component in terms of CPU usage and introduced latency.

**Comment by cmluciano** [comment]
Is this with both Jaegar and Opentracing?

**Comment by suryadu** [comment]
As shown in fig 3.2.5.1 of Istio Performance report (https://docs.google.com/document/d/1ob9M2TfI5GS3_rqrEhWFIpVyfFVKPTE8N3YZpeiDJxw/edit?usp=sharing), 20% of Istio CPU cycles are spent in tracing component. This is the default configuration cost and there is no additional tracing enabled for application or any other component. This issue is to track all the work to reduce the costs of tracing in Istio.

**Comment by jnativio** [comment]
This issue should remain open.
