### ISSUE TITLE
perf: Ingress Gateway optmization

### ISSUE THREAD

**Issue by jnativio** [istio/istio#8277]
**Describe the feature request**
Improve performance of the Ingress Gateway

**Comment by cmluciano** [comment]
Can we add more context to this in terms of what we think the bottleneck is? Also we should add SLIs to indicate what we are targeting in general.

**Comment by suryadu** [comment]
As shown in fig 3.2.5.1 from Istio performance report (https://docs.google.com/document/d/1ob9M2TfI5GS3_rqrEhWFIpVyfFVKPTE8N3YZpeiDJxw/edit?usp=sharing), ingress gateway consumes 27% of Istio's overall CPU consumption. As this is one of the major components adding to the additional capacity requirements of Istio service mesh, this issue is to track all the optimization work around ingress gateway to reduce this CPU consumption. 

Some of the ideas that we are experimenting with are kernel level tuning, Upstream and downstream keep alive configuration, reducing the context switching costs through increased concurrency etc.,

**Comment by jnativio** [comment]
This issue should remain open.
