### ISSUE TITLE
perf: Egress Gateway optimization

### ISSUE THREAD

**Issue by jnativio** [istio/istio#8278]
**Describe the feature request**
Improve performance of Egress Gateway

**Comment by suryadu** [comment]
This issue is to track all the performance optimization work around egress gateway. This includes the network latency as well as traffic encryption costs of accessing a 3rd party cloud service from an application microservice using Istio service mesh. @jnativio is currently working with @vadimeisenbergibm on characterizing this cost using acmeair microservices benchmark and mongoDB data service using Istio egress gateway.

More details soon.

**Comment by jnativio** [comment]
This issue should remain open.
