### ISSUE TITLE
perf: Statsd Prometheus bridge optimization

### ISSUE THREAD

**Issue by jnativio** [istio/istio#8279]
**Describe the feature request**
Improve performance of the statsd-prom-bridge component.

**Comment by suryadu** [comment]
As shown in fig 3.2.5.1 in the Istio performance report (https://docs.google.com/document/d/1ob9M2TfI5GS3_rqrEhWFIpVyfFVKPTE8N3YZpeiDJxw/edit?usp=sharing), there is about 9% of Istio cpu cycles spent on Statsd prometheus bridge. This issue is to track all the optimization work around this to reduce the cpu consumption

**Comment by jnativio** [comment]
stats-prom-bridge component was eliminated from Istio. By comparing the last build where this component was still present with one where it was removed, we can have an estimate of the gains in performance and cpu usage. Using the acmeair workload with a moderate traffic (20 jmeter clients), there is a gain of 7.5% in throughput and 10.8% less CPU utilization by Istio (including sidecars) for 1K tps. The following charts illustrate the gains:

![image](https://user-images.githubusercontent.com/18554027/46376588-5a5eed80-c664-11e8-9298-53379a4f5079.png)

![image](https://user-images.githubusercontent.com/18554027/46376889-33ed8200-c665-11e8-99d6-b998671c8d6b.png)

![image](https://user-images.githubusercontent.com/18554027/46376927-5089ba00-c665-11e8-98a4-f7cfcf16b64d.png)

@mandarjog
