### ISSUE TITLE
perf: Improve the auto-scale parms for Istio components

### ISSUE THREAD

**Issue by jnativio** [istio/istio#8282]
**Describe the feature request**
Currently, the cpu requests for Istio components are set to 10m which is very low, causing the hpa rules to trigger as soon the pods are deployed.

**Describe alternatives you've considered**
Use more realistic values to avoid unnecessary auto-scaling.

**Comment by suryadu** [comment]
This issue is to bring stability to Istio through adjusting the default auto-scale policy threshold higher. This is applicable for both telemetry as well as ingress Gateway pod auto-scaling.

**Comment by klarose** [comment]
I think the request number is too low. For example, ingress gateway is at 50% of 80% *idle*. It's not doing anything, yet it is consuming "5m".  I don't think increasing the thresholds for the HPA is answer 80% seems like a fine number. The cpu request from the istio components needs to be more realistic.

For another example, my telemetry pods are using 20m pretty much idle. Because of this, the autoscaler immediately spins them up to the max. It's relying on an assumption that adding instances reduces load, but when the idle load is above the threshold? It just doesn't work!

An alternative, I guess, could be to put a "baseline" offset into the autoscaler. I.e. we expect a pod to use 20m when idle, so if it's using 25m, then it's really only at 50% of its 10m capacity.

**Comment by jnativio** [comment]
@klarose Our analysis is correct regarding the cpu requests being the reason for the immediate scale up without return. The question is why this parm was set so low for the Istio pods. Maybe it has to do with allowing the kube scheduler to place them without much restriction.
