### ISSUE TITLE
request.auth.claims[scope] does not allow a JWT with additional scopes

### ISSUE THREAD

**Issue by cameronmoreau** [istio/istio#8319]
**Describe the bug**
When enabling RBAC, the `request.auth.claims[scope]` [authorization property](https://istio.io/docs/reference/config/authorization/constraints-and-properties/#properties) only matches exact strings. The service role is not bound when a token contains sufficient scopes, but also has additional scopes.

**Expected behavior**
If the token has all the scopes the property value asks for, it should pass; even if the token has additional scopes that are not in the property value.

**Note:** Wildcards can be used for the beginning and end of the string, but this is very limited when validating scopes of a JWT.

**Steps to reproduce the bug**
1. Enable mTLS (istio-auth.yaml) on app similar to BookInfo
1. Enable JWT Policy
1. Configure a ServiceBindingRole with the following subject properties
```
subjects:
  - user: "*"
    properties:
      request.auth.claims[scope]: "foo.read foo.write"
```
4. Visit the page with a JWT containing the following or equivalent scopes
```{..., "scope": "foo.read foo.write foo.update"}```

**Version**
```
○ → istioctl version
Version: 1.0.1
GitRevision: 42773aacced474d97159902d20579a25b1f98106
User: root@832d5020b1d4
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean
```
```
○ → k version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-18T11:36:43Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Is Istio Auth enabled or not?**
`istio-auth.yaml` enabled on demo BookInfo app with the example [JWT Policy enabled](https://istio.io/docs/tasks/security/authn-policy/#end-user-authentication)

**Environment**
```minikube version: v0.28.1```

**Cluster state**
[istio-dump.tar.gz](https://github.com/istio/istio/files/2329196/istio-dump.tar.gz); jwks information in the JWT Policy may need to be updated so that tokens can be generated with scopes relevant for this issue.

Related Issue: https://github.com/istio/istio/issues/8466

**Comment by yskopets** [comment]
`request.auth.claims[groups]` is another example where support for arrays of strings is necessary

**Comment by liminw** [comment]
In Istio 1.0, Istio RBAC does not support JWT claims with array type. We recently added this support (bullet 3 of issue #6984). We are in the process of updating documentation. It will be available in 1.1 release. @lei-tang

In the example, your JWT claim should contains an array:

`{..., "scope": ["foo.read", "foo.write", "foo.update""]}`

ServiceRoleBinding should be:
```
subjects:
  -  properties:
       request.auth.claims[scope]: "foo.read"
  -  properties:
       request.auth.claims[scope]: "foo.write"
```
For request.auth.claims[groups], you will be able to use "group" field in ServiceRoleBinding:
```
subjects:
  -  group: "foo.read"
```
which is equivalent to 
```
subjects:
  -  properties: 
      request.auth.claims[groups]: "foo.read"
```

**Comment by yskopets** [comment]
@liminw Thank you!

**Comment by cameronmoreau** [comment]
Confirmed that istio 1.1.0.Snapshot.1 fixes the described issue 👍 Thanks!

**Comment by lei-tang** [comment]
The PR #7747 fixed this issue. Thanks for confirming that the fix works!

**Comment by ncouse** [comment]
The fix above seem to address Issue #8319, but not this issue (i.e. space separated scope string)

As per draft RFC for OAuth Token Exchange - Section 4.2, the `scope` claim is a space separated string of scopes, and not a list.

 https://tools.ietf.org/html/draft-ietf-oauth-token-exchange-16#section-4.2

The `scope` claim is also currently a _temporarily_ registered claim with IANA: https://www.iana.org/assignments/jwt/jwt.xhtml

Various OpenID Connect Authorisation Servers have supported with format for some time. Keycloak, for example has been returning the JWT `scope` claim in this format since v4.0.0.Final. Note that space separate string has been long an OAuth2 standard for token responses, so this format in JWT claims would have been expected.

As noted above I can use only use the prefix and postfix wildcard to try to get around this, but I can't guarantee in what order the scopes will be returned, so this is not an approach that works.

---

So if my JWT `scope` claim looks like this (genuine example from Keycloak)
```
"scope": "openid profile email"
```

How can I match against the `profile` scope for example?

**Comment by maarek** [comment]
I am having this same issue with Auth0 as JWT provider. They provide scope as a space delimited string.

**Comment by dinvlad** [comment]
Any updates on this issue?
