### ISSUE TITLE
sequencing VirtualServices and DestinationRules

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#8420]
_(Customer feedback for 1.0, please do not remove the label)_

A deployment is packaged together with istio resources in a helm chart. Whenever a new version is released, helm is used to upgrade the chart (e.g. updating a container, changing the virtual service for canary rollout, etc). During the upgrade, an old chart is taken down and replaced with the new chart. 503s are observed for up to 40s.

Feedback 1: Recommendation https://istio.io/help/ops/traffic-management/deploy-guidelines/#503-errors-while-reconfiguring-service-routes is deemed unacceptable. It is impossible to insert a sleep in between destination rule and virtual service in helm packages.

Feedback 2: Unclear expectations on configuration propagation. Customer observed delays up to 40s of consistent 503s, caused by NR and UH envoy errors. For sequencing to work, should the customer wait 40s for each resource?

/cc @rshriram @costinm @louiscryan

**Comment by kyessenov** [comment]
@rshriram What is the right tool that customers should use for packaging their own applications with istio configs? According to the latest CNCF survey, helm is used by 68% of respondents.

**Comment by rvora** [comment]
@rshriram Can you clarify what you mean by "the actions helm does are precisely what we tell people to not do"?

Reason I am asking is that helm doesn't seem to be the culprit here. The root cause is within Istio - the need to sequence operations (add/delete) on VirtualServices and DestinationRules. Anyone using kubectl / kubeapi directly to make changes to istio config would also run into the same problems if they were not aware of the dependencies.

**Comment by rvora** [comment]
@rshriram Also, the idea of sequencing config updates is a difficult one right now in most CI/CD platforms. The suggested algorithm in the above mentioned link (Feedback 1) is very difficult to implement deterministically - what does "wait for a few seconds" mean? What if "few seconds" is not enough in one k8s cluster but enough in another k8s cluster? Is there a way to ask Istio / Envoy if the changes have been propagated?

**Comment by ayj** [comment]
related: https://github.com/istio/istio/issues/6082 and https://github.com/istio/istio/issues/882

Some of the current solutions for observing operational status of configuration:

- Dump the proxy status and work backwards from envoy listeners/routes/clusters to determine whether the latest Istio configuration is applied - https://github.com/istio/istio/issues/882#issuecomment-397438591
- Use pilot / proxy telemetry to observe the health of their configuration. Working backwards from these derived configuration stats back to Istio API configuration is left as an exercise for the user.

Neither is an ideal solution to this issues original problem (or  https://github.com/istio/istio/issues/882
). Exposing the pre-computed aggregate operational status of each configuration in the CRD status subresource would be a useful building block for higher-level operators (human or code) to sequence rollout of new/upgraded configuration.

cc @ozevren @geeknoid

**Comment by rshriram** [comment]
@rvora I agree that the sequencing has inherent non-determinism in that no amount of wait is a definite guarantee that one resource has reached pilot/envoys. However, at the infrastructure level (i.e. at Istio level), the lack of sequencing presents even greater problems. Istio has no way of knowing whether the sequence is complete or not. For example, if a new virtual service is added, it has no way of knowing whether or not a destination rule will be added or not, or whether it was added and has not yet reached the particular pilot, due to eventual consistency. Any solution we pick for this will have much bigger drawbacks system wide. If a pre-existing virtual service depends on a DestinationRule, and the user deletes a destination rule, do we pull that virtual service out of every sidecar/gateway? or do we simply pull out only the affected routes in which case, you get 404s instead of 503s. Add in some eventual consistency, you will soon see that what one Pilot sees is not what the other Pilot will see (one pilot sees new virtualservice, old destination rule, and other sees vice versa). One part of the mesh will have newer configuration while the other will have stale or inconsistent configuration..
From an application design point of view, you will have much bigger issues to tackle if istio attempted the sequencing, as there are too many error/corner cases that result in a non-deterministic 404s, 503s, etc.

In reality, you typically don't have to wait that long between a destination rule and virtual service. If your helm upgrade "replaces" the rules without deleting and adding them, using the same resource names, then things should be fairly quick.

I bet the 40s you are seeing is because of some delay/throttle that we have in the code (one of the many environment variables that control push, debounce, etc. - cc @costinm / @mandarjog ) thats causing this

**Comment by adamzhoul** [comment]
@rshriram  do you have any suggestion when facing 40s delay. how to debug this. find the problem.

since envoy follows eventual consistency, I think it is necessary to write the script when upgrade or change the config. 

the key point should be how to make the propagation fast enough, and how to make sure it's done.

**Comment by rshriram** [comment]
The 40s is not from Envoy. It’s some sequence of timers or throttles in pilot.

**Comment by nixgadget** [comment]
So do we have a solution to this problem for those of us using helm ?

**Comment by rvora** [comment]
@nixgadget No there is not a deterministic solution and based on this thread and other conversations with Google team I don't think there will be.

Good news (kind of) is that newer versions of Istio have reduced the window where you get 503s. The other mitigation strategy is to implement a canary release process - a bit tricky with Helm but doable in theory. I have yet to implement and test that myself but I do intend to. I'll update here if I find any useful tips implementing that.

**Comment by nixgadget** [comment]
I'm thinking of a similar solution using a `job` in the Helm `post-install` to inject the rules. will also post back if it works within the next few days.

**Comment by loewenstein** [comment]
I liked a lot what @ayj wrote...

> Exposing the computed aggregate operational status of each configuration in the CRD status subresource would be a useful building block for higher-level operators (human or code) to sequence rollout of new/upgraded configuration.

Is it doable? It's probably quite some work to do, but reporting back rollout state information to the Istio CRDs sounds a lot like a good idea.

**Comment by andraxylia** [comment]
@costinm @sdake  would the à-la-carte installer solve this problem?

**Comment by andraxylia** [comment]
@ostromart would the operator solve this?

**Comment by howardjohn** [comment]
@andraxylia the operator/install have no control over applied virtualservice/destination rule. Only galley/pilot could be "smart" here and even that does not seem needed/feasible. If you apply a virtual service and DR at the same time they will be pushed together to envoy at the same time, with clusters first. I suspect this issue was around from before this was the case?
