### ISSUE TITLE
MCP server shouldn't immediately re-push NACK'd config updates

### ISSUE THREAD

**Issue by ayj** [istio/istio#8471]
The MCP server layer should avoid immediately re-pushing previously NACK'd resources to the same client. Instead, the server should wait until a new resource version is published before sending the next MCP config response.

**Comment by kyessenov** [comment]
Are there any chance of ephemeral errors in MCP? In Envoy's xDS, the re-push is controlled by a rate-limiter due to ephemeral validation errors (mostly because of referential integrity, plus higher level coordination such as mounting files, etc). 

I agree that permanent errors should not be retried. However, if you have more than one source of truth to the MCP client (two MCP servers, higher-level coordinator), then you might have temporal inconsistencies.

**Comment by ayj** [comment]
I'm not aware of any ephemeral validation errors in the current usage of MCP with Mixer and Pilot. My first thought is to restrict usage of ACK/NACK to permanent errors (e.g. config is not well formed, type not supported, etc) and use another mechanism for reporting transient referential integrity issues (e.g. status API).

That said, rate limiting retries would provide some resiliency to avoid terminally blocked states due to buggy clients, temporal inconsistencies across re-connects, etc.

**Comment by kyessenov** [comment]
In xDS, NACK and status are used for the same purpose, status is OK for ACK, and not OK with error details for NACK. Separating the two seems to be rather confusing.

There is also an interesting case of downstream systems rejecting the config. For example, if envoy rejects with NACK, does pilot also reject with NACK? Does it retry instead?

I can imagine similar things happening in Mixer. If an OOP rejects adapter config, what should Mixer be reporting to MCP server.

**Comment by ayj** [comment]
Fixed by https://github.com/istio/istio/pull/9498
