### ISSUE TITLE
Resolve Mixer Policy's use of namespace in Galley for MCP resources

### ISSUE THREAD

**Issue by ayj** [istio/istio#8487]
The scope of [Mixer Policy API resources](https://github.com/istio/api/blob/master/policy/v1beta1/cfg.proto) is resolved per-request in the Mixer runtime. This resolution requires knowledge of mesh and namespace scoped resources. With the introduction of MCP, Galley can perform this scope resolution such that Mixer can be programmed with pre-resolved configuration. Mixer would no longer need knowledge of namespaces and scope resolution could be moved closer to config ingestion time.

**Comment by ayj** [comment]
cc @ozevren @mandarjog

**Comment by ozevren** [comment]
I think we should categorize things we can do here a bit and compare alternatives.

Local Name resolution:
As a low hanging fruit, the local => qualified name resolution within a namespace should be pretty mechanical and uncontroversial.

Reference resolution:
If we keep the current object model, then there is not much change we can do.  Inter-type references (i.e. instance/rule/handler) are still references. Galley can do the pruning before sending the config set down, but this doesn't absolve Mixer from doing its own pruning though. However, if we change the object model so that things get inlined directly, then we can inherently avoid the references and the need for pruning. This is where bloat can creep in due to duplication. Still, it may end up worth doing this to simplify the object model overall.

Ruleset resolution:
The rule set selection in Mixer is namespace-based, so the resources still needs to be grouped/keyed with namespace. *Some* resources (e.g. rule) still need to declare the namespace they associate with, whether through a convention of encoding it in the resource name, or having an explicit field declaring the namespace they belong to. (At MCP level we may add support for explicit namespaces).

Default ruleset:
Mesh v.s. namespace scoped config can be handled by simply tagging the mesh one specifically. Mixer will still need to retain the fallback logic (which is not expensive or out-of-place within Mixer anyways).

**Comment by kyessenov** [comment]
I don't a good design in mind. It all sounds reasonable. Ideally, Mixer only sees referentially consistent snapshots. That may be hard to achieve in xDS per-resource-type model (see all the 503s issue in envoy caused by this). There is a third requirement that I missed:

3. It would be great if MCP can specialize config for the MCP client. For example, a mixer serving a particular namespace should only receive config for that subset (or even fancier, filter our symbolic predicates in rule conditions that are trivially false).

**Comment by ozevren** [comment]
Re #3: I think that is quite achievable, but it needs to be designed.. and staffed. :)
The tricky part there is sharded Mixer deployment (or rather, overall sharding, canarying model for Istio that is future-compatible).

Galley can then easily create scoped config for different Mixer instances.

**Comment by ozevren** [comment]
Mixer seems to be changing drastically very soon. Does this issue still makes sense in that context?

**Comment by kyessenov** [comment]
Mixer runtime is changing but the config model has not been resolved. So I think it's still important to decide where the config overloading/overriding happens.

**Comment by ayj** [comment]
I don't think this will be relevant anymore with the move to mixer v2.
