### ISSUE TITLE
provide a way to know if a circuit breaker is currently open or closed

### ISSUE THREAD

**Issue by jmazzitelli** [istio/istio#8902]
**Describe the feature request**
It would be nice for Istio to provide some way to know if a circuit breaker is currently opened or closed.

**Describe alternatives you've considered**
There is no way to know this - even metrics that resulted in an open circuit breaker won't tell you it was produced due to an injected fault.

**Additional context**
This was briefly brought up on the [istio-users mailing list here](https://groups.google.com/forum/#!msg/istio-users/GMaLai6aTa4/ymfDMu8TCQAJ;context-place=forum/istio-users). In that thread, Jason Young recommended I create this issue.

This is also a feature that Kiali could be able to use to tell users if a circuit breaker is currently open or closed. See: https://issues.jboss.org/browse/KIALI-470

**Comment by denniseffing** [comment]
+1

Circuit breaker states are a very important indicator for overall system health.

**Comment by ijsnellf** [comment]
We'd need to expose metrics from Envoy. Taking a cursory look through the Envoy docs, the closest thing I see is `upstream_rq_pending_overflow`. But that is

> Total requests that overflowed connection pool circuit breaking and were failed

See:
https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/circuit_breaking

I wonder if it is something we can upstream into Envoy.

**Comment by venilnoronha** [comment]
I've created envoyproxy/envoy#4762 to track this on Envoy. I'll send in a PR for this if everything goes well there.

**Comment by venilnoronha** [comment]
Created a PR on Envoy - envoyproxy/envoy#4781

**Comment by venilnoronha** [comment]
Supporting this needs additional work on Istio around consuming Envoy stats. Issue #9827 tracks that.

**Comment by mandarjog** [comment]
@jmazzitelli Mixer captures the reason for a request failure as the `context.proxy_error_code`
when `context.proxy_error_code=UO`   (Upstream overflow (circuit breaking))  it means that this request was rejected by the circuit breaker.

This attribute is being sent to mixer, but it is not yet defined as part of the vocabulary.

**Comment by venilnoronha** [comment]
@mandarjog we have some [new stats](https://www.envoyproxy.io/docs/envoy/latest/configuration/cluster_manager/cluster_stats#circuit-breakers-statistics) that directly expose the circuit breaker state, and they're not necessarily request bound. I think there's also a separate use-case for Kiali to consume these.

**Comment by douglas-reid** [comment]
@venilnoronha one of the issues that will be exposed by those stats is that the istio clusters may not align with the other service/workload-oriented stats. However, I think we should pursue both avenues.

**Comment by mandarjog** [comment]
Does kiali consume stats from Prometheus today? If so it should have access to all envoy stats already.

Adapters are request bound today, so any information conveyed to them will be sampled at the request boundary. We can have mixer filter reach into local prom and provide arbitrary metrics if requested.


The other use case is direct api, like statsd direct api (prom is a bit wierd because it is pull), we have several docs about that already.

**Comment by jshaughn** [comment]
@venilnoronha , @douglas-reid , I played a bit with this yesterday to see if Kiali could offer up more information about the frequency and/or timing of CB state change, and/or rate of rejections due to the CB.  I pretty much came up empty but perhaps I'm not looking in the right place.  Using the [circuit breaking example](https://istio.io/docs/tasks/traffic-management/circuit-breaking/) I flooded httpbin service with a continuous stream of concurrent requests to generate rejections throughout several scrape intervals.  I could not find any default metrics/TS reflecting any CB activity for my destination rule on the httpbin service.  Should I have been able to see something or is there manual configuration required?

**Comment by douglas-reid** [comment]
@jshaughn the response flags should be available, same as the fault injection stuff. It is surprising that you aren't seeing that reflected.

**Comment by douglas-reid** [comment]
@jshaughn using the istio telemetry service, I can see metrics directly related to my circuit breaking in the task:

I ran fortio twice:

```
Sockets used: 5 (for perfect keepalive, would be 2)
Code 200 : 37 (92.5 %)
Code 503 : 3 (7.5 %)
```

and

```
Sockets used: 21 (for perfect keepalive, would be 4)
Code 200 : 21 (52.5 %)
Code 503 : 19 (47.5 %)
```

And then I executed the following query in Prometheus:
`sum(istio_requests_total{destination_service="httpbin.default.svc.cluster.local"}) by (response_code, response_flags, source_app)`

```
{response_code="200",response_flags="-",source_app="fortio"}	118
{response_code="503",response_flags="UO",source_app="fortio"}	22
{response_code="503",response_flags="-",source_app="fortio"}	5
```

Note the `UO` response flags.

**Comment by jshaughn** [comment]
@douglas-reid I was looking in the wrong place.  I was trying to utilize [these Envoy metrics](https://www.envoyproxy.io/docs/envoy/latest/configuration/cluster_manager/cluster_stats#circuit-breakers-statistics).  I didn't even realize that istio_requests_total had a response_flags label.  That's awesome and I'll look into again soon.

**Comment by douglas-reid** [comment]
@jshaughn ok. I'm going to close this issue for now. please feel free to reopen (or file anew) if you encounter other issues.
