### ISSUE TITLE
dashboard divides by zero producing NaN and red output in bookinfo GKE example

### ISSUE THREAD

**Issue by sdake** [istio/istio#8969]
**Describe the bug**
Deploy bookinfo and land on http://INGRESSIP:15031//dashboard/db/istio-mesh-dashboard

Red displayed with NaN - see screenshot.

**Expected behavior**
NaN not displayed - instead 0 TPS displayed and not in red

**Steps to reproduce the bug**
deploy bookinfo, open grafana page to the mesh overview.

**Version**
master.

**Installation**
```
1844  helm template istio --namespace istio-system --set global.hub=docker.io/sdake --set global.tag=sdake --set grafana.enabled=true --set telemetry-gateway.grafanaEnabled=true > gateway.yaml
```
NB: I have not pushed my containers, so please use the default hub and tags.
<img width="1423" alt="screen shot 2018-09-25 at 8 52 24 pm" src="https://user-images.githubusercontent.com/755849/46056401-4f0c3f00-c105-11e8-8788-f95a7d9c1ee3.png">

**Environment**
{{ Which environment, cloud vendor, OS, etc are you using? }}

**Cluster state**
{{ If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue. }}

**Comment by douglas-reid** [comment]
@sdake this has been previously discussed. I'm open to any workaround for figuring out how to get Grafana to not color `NaN` results. I'm not sure that this is supported by their current widgets.

The underlying problem is the following: there is no (recent) traffic to those services. It is incorrect to report 100% success rate and also incorrect to report 0% success rate. Dividing by zero is problematic, but `NaN` seems legit for these cases.

Last I checked: the Grafana widget accepts 2 boundaries for color -- and no exemptions.
