### ISSUE TITLE
Moving to workload centric policies

### ISSUE THREAD

**Issue by liminw** [istio/istio#8990]
Today we use the terminologies "services", "workloads", "hosts" in our policies interchangeably. This will likely cause confusion and ambiguity on the exact meaning of the policies. In the meanwhile, workload related attributes has been introduced to [Istio attribute vocabulary](https://preliminary.istio.io/docs/reference/config/policy-and-telemetry/attribute-vocabulary/). Towards the goal of having consistent terminology across all Istio policies, and making the policy semantics more accurate, we are thinking of moving away from the term "services" and instead using "workloads". This applies to authentication policies, authorization policies, and more. This issue is filed to collect feedback on this topic.

**Comment by liminw** [comment]
/cc. @louiscryan @geeknoid @diemtvu @costinm @wenchenglu @yangminzhu @ayj @ozevren @douglas-reid

**Comment by geeknoid** [comment]
A couple bullets from an email thread we had for context:

- We have DestinationRule.host and ServiceEntry.hosts in networking, and AccessRule.services and RbacConfig.Targets.services in the security space. The fact we're using different words to mean the same thing is not good for our users. Even if nothing else changes, I think we should deprecate the use of *.services and replace with .hosts for consistency.

- More important than the naming however are the semantics. Since many host names can point to a single workload, it doesn't seem possible to enforce policies on host names. More specifically, a caller can call a given workload through different host names and so can experience different policies. That doesn't seem secure or desirable. The real thing that runs code and against which policies can be enforced systematically is the workload. So how is the many-to-one mapping handled? This situation is what drove Mixer's design away from services and towards being focused on workloads.

**Comment by geeknoid** [comment]
And I haven't thought this through yet, but we need to see whether ServiceRole and ServiceRoleBinding should also be renamed to something less servicy. I don't know, I'm just bringing it up for discussion.

**Comment by diemtvu** [comment]
Here is a [design doc](https://docs.google.com/document/d/1eInPqAjOfsyJWtMIOeRRza0b0aErKqVzO9mbxNKcucA/edit#) that  try to address the second bullet point. 

IMO, it makes sense to be workload-centric for things that affect inbound configs. However, for outbound, service (or host) could be acceptable.
