### ISSUE TITLE
e2e tests for min/max TLS protocol version and cipher suite

### ISSUE THREAD

**Issue by ijsnellf** [istio/istio#9104]
There are no e2e tests for min/max TLS protocol version and cipher suite. See https://github.com/istio/api/pull/645 and https://github.com/istio/istio/pull/9103

Go doesn't seem to have an easy way to use an older version of TLS so we can easily test this.

**Comment by PiotrSikora** [comment]
You should be able to use [`tls.Config`](https://golang.org/pkg/crypto/tls/#Config) to set min/max protocol versions in Go, e.g.
```
cfg := &tls.Config{
    MinVersion:    tls.VersionTLS10,
    MaxVersion:    tls.VersionTLS11,
}

conn, err := tls.Dial("tcp", "127.0.0.1:443", cfg)
if err != nil {
    ...
}
defer conn.Close()
```
Background: I'm in process of [modernizing TLS defaults in Envoy](https://github.com/envoyproxy/envoy/issues/5401), so it would be great to make sure that configuring TLS protocol versions in Istio works, so that users can re-enable older protocols if needed.

**Comment by PiotrSikora** [comment]
@ijsnellf any chance this could make it before 1.1? Thanks!

**Comment by iftachsc** [comment]
+1. when is this expected to be out? thanks.

**Comment by myidpt** [comment]
This is a nice to have test, but not high priority in the short term. I added "help wanted". It would be great if someone from community can help out.

**Comment by PiotrSikora** [comment]
This would be good to add since upstream changed defaults (removed TLS 1.0 and TLS 1.1 from client-side defaults), so not having this might bite us in 1.5.
