### ISSUE TITLE
Istio service creation results with unexpected http errors such as 431 and 404

### ISSUE THREAD

**Issue by stepanv** [istio/istio#928]
Upon a sequential creation of 2 Envoy enabled services, the http communication between them (i.e., client -> server) results with unexpected errors.

On the client side, the progression of http errors received is:
`404` (not always), then `503`, then lot of `431` (not always) and finally `200`.

On the server side, I can see in the access log: `503`, hundreds of `431` per second, hundreds of `200` per seconds, and then after a while I see `200` for each single request.

Istio version: `2.4.0`
K8S version: `1.7`

## Steps to reproduce the issue:
```
# Install 'sleep' and 'httpbin'
kubectl apply -f <(./bin/istioctl kube-inject -f samples/sleep/sleep.yaml) && sleep 10 && kubectl apply -f <(./bin/istioctl kube-inject -f samples/httpbin/httpbin.yaml)

# And before the 'httpbin' deployment+service are created, run following curl
# As you can see, it prints error codes delimited with '.'
# it runs `curl` against the 'httpbin' service every second
kubectl exec $(kubectl get pod -l app=sleep -o jsonpath='{.items[0].metadata.name}') -- bash -c "while true; do curl -s -o /dev/null -w "%{http_code}." --connect-timeout 10 httpbin:8000/headers & sleep 1; done"

```
The curl may not return 200 for a long time, the output might be:
```
000.000.000.000.000.000.000.404.404.404.404.404.404.404.503.503.503.503.503.503.503.503.431.431.431.431.431.431.431.431.431.431.431.431.431.431.431.431.431.431.431.431.431.431.431.431.431.431.431.431.431.431.431.431.431.431.431.431.431.431.431.431.431.431.431.431.431.431.431.431.431.431.431.431.431.431.431.431.431.431.431.431.431.200.431.200.431.431.431.431.200.200.200.200
```
The output is not always the same, sometimes, I don't get `404` and sometimes I don't get `431`. Rarely, the service never starts returning `200` and gets stuck with returning `431`.

Looking at the output, I'll see thousands of `431` logged by the Envoy at `httpbin` pod:
```
kubectl logs $(kubectl get pod -l app=httpbin -o jsonpath='{.items[0].metadata.name}') -c istio-proxy

... envoy startup ...

}I0925 12:55:58.028625      35 watcher.go:221] Envoy command: [-c /etc/istio/proxy/envoy-rev0.json --restart-epoch 0 --drain-time-s 45 --parent-shutdown-time-s 60 --service-cluster istio-proxy --service-n
ode sidecar~10.99.30.59~httpbin-2011435279-b1624.default~default.svc.cluster.local]
[2017-09-25 12:55:58.036][53][warning][main] external/envoy/source/server/server.cc:149] initializing epoch 0 (hot restart version=8.2490552)
[2017-09-25 12:55:58.048][53][warning][main] external/envoy/source/server/server.cc:317] starting main dispatch loop
[2017-09-25 12:55:58.133][53][warning][main] external/envoy/source/server/server.cc:301] all clusters initialized. initializing init manager
[2017-09-25 12:55:58.195][53][warning][config] external/envoy/source/server/listener_manager_impl.cc:451] all dependencies initialized. starting workers
[2017-09-25T12:56:30.874Z] "GET /headers HTTP/1.1" 503 UH 0 19 1 - "-" "curl/7.35.0" "c8b1d3ce-4726-9562-af7c-0b060affb1a7" "httpbin:8000" "-"
[2017-09-25T12:56:31.891Z] "GET /headers HTTP/1.1" 503 UH 0 19 0 - "-" "curl/7.35.0" "97cbc0a6-3719-9d33-ad10-ee5cdd68237b" "httpbin:8000" "-"

... several 503 go here

[2017-09-25T12:56:43.261Z] "GET /headers HTTP/1.1" 431 - 0 0 0 - "-" "curl/7.35.0" "fe9d5c2e-6435-9b75-bc30-ec91203bd44f" "httpbin:8000" "-"

... here, I do see 6398 records of 431 http codes in 12 secods, that is around 533 records per second

[2017-09-25T12:56:55.921Z] "GET /headers HTTP/1.1" 431 - 0 0 372 371 "-" "curl/7.35.0" "f25e858e-a823-9ed5-8deb-b4dd7c22ab88" "httpbin:8000" "10.99.30.59:8000"
[2017-09-25T12:57:01.107Z] "GET /headers HTTP/1.1" 200 - 0 430 10 4 "-" "curl/7.35.0" "3f7e7985-dd59-9ba1-9f9c-717f6eb876da" "httpbin:8000" "127.0.0.1:8000"

... here, I do see 4820 records of 200 http codes in 7 secods, that is around 600 records per second 

[2017-09-25T12:57:09.973Z] "GET /headers HTTP/1.1" 200 - 0 430 42 34 "-" "curl/7.35.0" "fba063ac-505e-9c90-8e45-d305ab99dcb4" "httpbin:8000" "10.99.30.59:8000"
[2017-09-25T12:57:10.978Z] "GET /headers HTTP/1.1" 200 - 0 430 3 1 "-" "curl/7.35.0" "9d381471-f6c8-9888-bb8a-26d6af472296" "httpbin:8000" "127.0.0.1:8000"

... and now, I finally see one request per second

[2017-09-25T12:57:11.981Z] "GET /headers HTTP/1.1" 200 - 0 430 5 1 "-" "curl/7.35.0" "6c25b58a-4680-9bdf-ae23-5bde1d7481b1" "httpbin:8000" "127.0.0.1:8000"
[2017-09-25T12:57:12.985Z] "GET /headers HTTP/1.1" 200 - 0 430 4 1 "-" "curl/7.35.0" "89d2ab37-5169-9041-88cc-24145abd6d84" "httpbin:8000" "127.0.0.1:8000"

... and so on
```
I don't usually get the `431` errors if the services were both created and then the `curl` was executed.

## Desired behavior
I would expect to see `503` error codes and then `200`.
I don't think `404` makes sense but that's probably a philosophical question.
And finally, it looks like that `431` errors correlate with an insane load (maybe that relates to https://github.com/istio/pilot/issues/978 but I'm just guessing).

**Comment by ldemailly** [comment]
will put this as 0.2 for now but will be a patch release most likely or 0.3

**Comment by kyessenov** [comment]
431 sounds like the same bug as you pointed out. Do let us know if you have more information as we're trying to understand the iptables/hairpin issue that's like the root cause of it.

**Comment by rshriram** [comment]
can you try this out with latest release and see if the bug persists?

**Comment by bmarshall13** [comment]
I can confirm this is still an issue with 0.7.1

I also think I have a root cause:
When pilot calculates the clusters and listeners for a sidecar, it does not include the inbound cluster/listener until the pod is marked ready by kubernetes. However, it still includes itself as an outbound cluster, which may or may not include itself as a member.

You can test this by adding a readiness exec probe that can be manually triggered. Mark the pod as not ready, and the `in.<port>` cluster and the `http_<pod_id>_<port>` listener disappear. 0.7.1

When the sidecar doesn't have its inbound cluster configured, an inbound request will use the `http_0.0.0.0_port` listener instead, which will be routed as if it were an outbound request. Since the oubound cluster includes the pod's self ip, this creates a loop.

This means you will see:
 - 404 (No Route) when the outbound cluster has no endpoints
 - 431 (Header too large, i.e Request loop) when the outbound cluster includes itself. 
 - 200 (incorrectly) when there are other ready pods in the cluster, since the request will be re-routed. I have not investigated this case, but I assume this is not desirable as it will mess up circuit breaking add latency, may still result in a larger loop, etc.

Because the proxy learns about its inbound listeners at the same time as other proxies consider it ready to send requests, you will have this period of 404,431 errors.  It also breaks kubernetes tcp/http readiness probes on service ports (even without mTLS), since the port will return errors until the pod is ready, and the pod won't be ready until the probe succeeds

IMO, A pod's inbound service port should always be configured. A hard-coded, static fallback that always returns an error for inbound requests might even be warranted to protect against other corner cases.

Code pointer:

@kyessenov Is this the iptables/hairpin issue you were talking about?


Code pointers:
 - clusters/listeners are only generated for proxyInstance: https://github.com/istio/istio/blob/master/pilot/pkg/proxy/envoy/v1/config.go#L154
 - proxyInstances only includes ready endpoints: https://github.com/istio/istio/blob/release-0.7/pilot/pkg/serviceregistry/kube/controller.go#L353

**Comment by markstgodard** [comment]
I also encountered something similar with 0.7.1.

I have a service A that talks to service B, and when I make a request to service A via the ingress, I get an HTTP 431 (which looks to be a loop when I look at the trace in jaeger

![image](https://user-images.githubusercontent.com/405082/39102810-a15352b2-466c-11e8-875e-bf1dc5287117.png)

**Comment by rshriram** [comment]
can you try with the latest 0.8 release and let us know if the issue persists?

**Comment by rshriram** [comment]
closing as stale..
