### ISSUE TITLE
istio blocking ports 

### ISSUE THREAD

**Issue by rushins** [istio/istio#9806]
**Describe the bug**
{{ Succinctly describe the bug }}
using ISTIO-proxy the system port is not working. 
**Expected behavior**
{{ What did you expect to happen? }}
remove ISTIO-Proxy the system port is working
**Steps to reproduce the bug**
{{ Minimal steps to reproduce the behavior }}
GKE Kubernetes with simple SAP HANA database
**Version**
istio 1.0
{{ What version of Istio and Kubernetes are you using? Use `istioctl version` and `kubectl version` }}

**Installation**
{{ Please describe how Istio was installed }}
we follow GKE link https://cloud.google.com/kubernetes-engine/docs/tutorials/installing-istio

**Environment**
{{ Which environment, cloud vendor, OS, etc are you using? }}
SUSE Linux 
**Cluster state**
{{ If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue. }}

**Comment by hzxuzhonghu** [comment]
Do not get what you are asking?

**Comment by rushins** [comment]
basically our Container (which is SAP HANA database) has the same hostname and IP address with ISTIO-proxy container ? and this cause our HANA database connectivity issues. IF we run without ISTIO Proxy this works and with ISTIO-PROXY this breaks connectivity on the container ? does it make understand now ?

**Comment by esnible** [comment]
The application container and the istio-proxy container MUST have the same address.

For Istio to work properly the app container (your HANA database) must accept localhost connections.  I am not familiar with your database but I have used other database middleware with Istio.

`kubectl exec -it <pod> bash` to get into your container.  Once in, test it in the usual way for the service it offers, for example:

* `curl localhost:5984/_all_dbs` (for CouchDB)
* `mysql -p -h localhost -P 3306` (for MySQL).

_localhost_ connections should not be affected by Istio.  If you have a problem here, fix it here.
Because svcB and its sidecar share a single network so talking to _localhost_ should be the same
on the sidecar as within svcB.

If your application cannot talk on _localhost_ because it explicitly binds listening sockets
to an IP address it will not work under Istio.

Run `netstat -tulpn` and make sure the *Local Address* is 0.0.0.0 or 127.0.0.0 for all listeners.  Applications that explicitly listen on their external address (e.g. 10.233.98.142) will not work under Istio.  This is because the Envoy proxy traffic does not come from off-pod
and will appear to your application as if it arrived via _localhost_.
