### ISSUE TITLE
istio support pod graceful shutdown 

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#9818]
In pod spec there is a `TerminationGracePeriodSeconds`, indicating the max duration to allow pod terminate gracefully.   Pod in this phase is still running, but is being deleted and should not have new requests/connections comes in.

In istio, if a pod with not nil `DeletionTimestamp`, it should not be treated as an endpoint.  Pilot should generate eds without such deleting pod.

**Comment by louiscryan** [comment]
Should see how we tie K8S shutdown hooks to

https://github.com/envoyproxy/envoy/issues/1990

**Comment by munrodg** [comment]
@ZackButcher can you take a look at this issue.

**Comment by duderino** [comment]
@costinm @rshriram @frankbu how would you go about implementing this?

**Comment by elevran** [comment]
Perhaps I misunderstood the OP's intent, but TTBOMK, terminating pods are removed from the service's endpoint list (see [docs here](https://kubernetes.io/docs/concepts/workloads/pods/pod/#termination-of-pods), and [here](https://cloud.google.com/blog/products/gcp/kubernetes-best-practices-terminating-with-grace); and [code here](https://github.com/kubernetes/kubernetes/blob/54dc9db17b1ce17be884c35de3a60144199fe4c0/pkg/controller/endpoint/endpoints_controller.go#L439).
Since EDS for k8s is based on the [endpoint list](https://github.com/istio/istio/blob/b8e30e07ec7b36cf1ba1b445b78c81fdf0d417b9/pilot/pkg/serviceregistry/kube/controller.go#L437), won't these terminating pods be removed from EDS automatically?

During termination, existing connections are expected to drain and are thus still candidates from the client's envoy point of view until closed. 
- Shutdown hooks can be used to make the server side envoy close idle connections (i.e., with no pending requests), effectively removing them from clients' proxy connection pool faster.
- An alternative could be for client side proxies to close idle connections and remove them from the pool when the endpoints are removed from EDS.
The first option may be simpler to implement.

**Comment by hzxuzhonghu** [comment]
>Since EDS for k8s is based on the endpoint list, won't these terminating pods be removed from EDS automatically?

Exactly, pilot will remove it from EDS.

**Comment by liamawhite** [comment]
closing in favour of #7136.
