### ISSUE TITLE
readiness check fails when rbac is enabled

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#9921]
readiness check fails when rbac is enabled with a 403.

Kublet does not present a cert so I am not sure which identity the rbac will apply to.
Side injector should automagically insert rules to allow access to the readiness / liveness checks.

If proxy agent takes over readiness / liveness checks then should not be an issue.

If this is the case, please provide clarity in config examples and docs.

**Comment by liminw** [comment]
I had a discussion with @mandarjog today on this issue. The proposal is to add a default RBAC rule to allow any user (user: "*") to access "/healthz" path. @mandarjog, do you plan to make the change?

**Comment by duderino** [comment]
@liminw mjog agreed to the solution but didn't agree to do the work.

The minimum for 1.1 is to document the behavior.  Per mjog "If this is the case, please provide clarity in config examples and docs."

If a fix can't be provided in 1.1 timeframe, please move to 1.2 after the documentation fix is made.

**Comment by liminw** [comment]
I checked with @wattli. It seems that @incfly 's health check change is still not in yet. And [the doc regarding health check](https://preliminary.istio.io/help/faq/security/#k8s-health-checks) still describes the old behavior. 

Since the RBAC related documentation mentioned in this issue is only relevant in the context of the new way of health check. I will wait for @incfly 's change in and relevant health check doc updated.

**Comment by liminw** [comment]
Dependency on issue #9921
